### ISSUE TITLE
join_implementation.rs assumes `Reduce` always produces an arrangement, but `ReducePlan::DistinctNegated` doesn't.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#10022]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What was the issue?

Compare [this code](https://github.com/MaterializeInc/materialize/blob/e20628c3b/src/transform/src/join_implementation.rs#L150-L154) to [this code](https://github.com/MaterializeInc/materialize/blob/e20628c3b/src/dataflow-types/src/plan/reduce.rs#L426-L441).

The join implementation selection code assumes that a `Reduce` node will always produce a particular arrangement, but that isn't true in general, depending on which reduce plan is selected.

Fortunately, nothing can trigger this now, since we never plan `DistinctNegated`. But we should someday (if not, we might as well delete the code...) and at that point, we will need to fix this bug.

Fixing this in the most straightforward way would require us to know in MIR which `ReducePlan` variant is to be used, so that we can read that when choosing a join implementation. But today, we only pick a `ReducePlan` during LIR planning.

**Comment by ggevay** [comment]
Good catch!

Fortunately, the join implementation wouldn't blow up even if we run into the bug in the future after adding a case where we plan `DistinctNegated`. The only negative effect of the bug is that it would mislead the join algorithm choice and the join ordering code, but things won't blow up, because in any case, we add an MIR ArrangeBy to inputs that need it, and then LIR planning will translate that into an LIR ArrangeBy if there is no arrangement already. (An arrangement might or might not exist before an MIR ArrangeBy. LIR planning decides whether to actually create an arrangement right there.)

It's indeed tricky to fix this, because (as you also noted) we decide on the Reduce implementation later than `JoinImplementation` runs. There were discussions at some point about moving `JoinImplementation` to the LIR planning, so maybe it will be easier to fix the bug after that.

**Comment by antiguru** [comment]
Related: #19466 which removes the `ReducePlan::DistinctNegated` implementation.
