### ISSUE TITLE
persist: re-enable flaky test

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10488]
The persistence tests seem to be flaky when logical compaction is disabled. I'm sending a PR to skip that test for now. This issue is to track the proper diagnosis and fix.

**Comment by benesch** [comment]
Marking this as a release blocker until we've diagnosed why this is a problem.

**Comment by ruchirK** [comment]
I'm removing the release blocker label here as the persist team is ok with the release moving forward despite this regression

**Comment by ruchirK** [comment]
Update: I'm having a hard time reproducing this on either my laptop or a r5a.4xl ec2 instance. On my laptop I wasted a bunch of time on a git bisect rabbit hole chasing a test failure that wasn't a crash, and yet ended up being totally spurious. On the ec2 instance, I haven't yet been able to make the persist tests fail.

The persist tests were failing pretty repeatably on ci so going to try re-pushing to ci and perhaps trying with a ci like instance to see that repros.

**Comment by ruchirK** [comment]
A glimmer of good news: I'm able to reproduce the original failure on `827645e5884f81c955b2985492cbb4ac2cef79ae` (the commit just before Nikhil reverted the tests).

To summarize my current understanding:

1. at v0.19.0 persist tests with logical-compaction-window=off were fine
2. At some indeterminate point most likely around last weekend they regressed
3. Nikhil reverted those tests
4. At some indeterminate point the regression happened to self correct, and now I can't reproduce the failure on main?

I'll try to bisect down where we actually started to fail between v0.19.0 and `827645e5884f81c955b2985492cbb4ac2cef79ae` and where we stopped failing between ``827645e5884f81c955b2985492cbb4ac2cef79ae`  and current HEAD to hopefully understand what is going on

**Comment by ruchirK** [comment]
re. 2 - `b1b54fb719c8ebbf162c4cb5ad7934618e918bf7` looks like the first bad commit

**Comment by ruchirK** [comment]
re. 4 - the regression was fixed in `4f53f0e3f7243e0d0c6660f74282505ea4dd6f9d` . This pair of commits makes sense as a pair that would tickle and then untickle this bug as they both change things at the intersection of the bindings persisted to sqlite, the bindings persisted in persistent collections, and the interaction between persist and sources, but given the sheer number of moving parts here its going to take me a little bit of time to unravel exactly what regressed and why it improved. I think we can re-enable the logical-compaction=off tests though they seem fully stable on main

**Comment by benesch** [comment]
Long since stale. Persist works completely differently now.
