### ISSUE TITLE
Text indexes and "order by" index are much slower than Postgres

### ISSUE THREAD

**Issue by Linksku** [MaterializeInc/materialize#10738]
### What version of Materialize are you using?

v0.19.0

### How did you install Materialize?

APT package

### What was the issue?

I tested different types of `select`s using indexes and 2 kinds of queries are much slower than Postgres:

1. Text indexes, e.g. `select id from "testMV" where name = 'string' limit 1`

2. Order by (both `asc` and `desc`), e.g. `select id from "testMV" order by id limit 1`

With 1 million rows, both of these take more than 100x the amount of time as Postgres, about 200ms vs 1ms on a laptop. Other query types take only about 2x the amount of time as Postgres. Both of these queries take a similar amount of time as filtering by an unindexed column, so I'm assuming Materialize is doing a table scan. If it does a table scan for these simple queries, then it'll be way too slow for larger tables.

Since it'll be difficult to match Postgres's performance, would it be recommended to push the materialized data back to Postgres and then read from Postgres? E.g. main Postgres -> CDC -> Materialize -> Kafka -> read-replica Postgres. Or are there plans to address the common performance issues?

### Table/view

```
CREATE TABLE test (
    id bigint NOT NULL,
    name character varying NOT NULL
);
```

```
create materialized view "testMV" as select id, name from test;
create index "testMV_idx_id" in "testMV" (id);
create index "testMV_idx_name" in "testMV" (name);
```

### Additional tests

This takes ~2ms and returns 1 row: `select id from "testMV" where id <= 1`
This takes ~200ms and returns 1 row: `select id from "testMV" where id <= 1 order by id`

**Comment by wangandi** [comment]
Materialize indexes can be thought of hash indexes. Thus, of the cases you have listed, the only query that we would expect to be improved by the creation of an index is `select id from "testMV" where name = 'string' limit 1`. (As an aside, our hash indexes should be able to support queries like `select id from "testMV" where name IN ['string', 'string2'] limit 1`, but we just haven't gotten around to that yet.)

I looked at the plan for your query:
```
materialize=> explain raw plan for select id from test where name = 'string';
                Raw Plan                
----------------------------------------
 %0 =                                  +
 | Get materialize.public.test (u19)   +
 | Filter (varchartostr(#1) = "string")+
 | Project (#0)                        +
```
It looks like our plan casts the name column to type `string` before comparing, so the index you need to create in order to speed up this query is `CREATE INDEX "testMV_idx_name_as_string" ON "testMV" (name::string);`.

That said, it is completely unintuitive that you were supposed to create an index on `"testMV" (name::string)` and not `"testMV" (name)`, and I have passed along this issue to the relevant team members.

**Comment by wangandi** [comment]
As for what we recommend you do for the other queries:
Materialize is optimized for [view maintenance](https://materialize.com/blog-olvm/). As a user, you should decide, what question (or class of questions) do you want answered again and again as your data changes? Once you decide on the question (or class of questions), you convert it into a query and create a materialized view that selects that query.

If the question you want to ask over and over again is `select id from test order by id limit 1`, you should `CREATE MATERIALIZED VIEW test_min_id AS select min(id) from test`. The view `test_min_id` will only have 1 row, so `select * from test_min_id` should be super fast.

If the class of questions you want to ask over and over again is `select id from test order by id limit k` where the value of `k` varies, figure out `n`, the max value of `k` that you would realistically ask for, and then `CREATE MATERIALIZED VIEW test_min_n_ids AS select id from test order by id limit <n>`. `select * from test_min_n_ids order by id limit k` will still be quite fast because while Materialize does do a view scan, there are only `n` rows in the view, and `n` should be several orders of magnitude less than 1 million.

**Comment by benesch** [comment]
> That said, it is completely unintuitive that you were supposed to create an index on `"testMV" (name::string)` and not `"testMV" (name)`, and I have passed along this issue to the relevant team members.

Seems like an optimizer issue to me. Casting a varchar to a string is a trivial operation that ought to get constant folded away: https://github.com/MaterializeInc/materialize/blob/d1cf87fba64605815ae10c321c927b8e19b07587/src/expr/src/scalar/func/impls/varchar.rs#L17.
