### ISSUE TITLE
Use postgres' LISTEN/NOTIFY to support TAIL inside the pgwire protocol

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1076]
[PG docs](https://www.postgresql.org/docs/11/sql-listen.html)

It might be a bit hard to test in rust right now, based on [this 1-month-old reddit thread](https://www.reddit.com/r/rust/comments/dgl6hi/how_to_postgres_listen_notify/), but it does seem possible, and testing in pgjdbc would be actually more useful, too.

**Comment by rjnn** [comment]
This came up in a prospect conversation. Given this was originally filed last year without concrete user feedback, I wanted to note that the prospect was extremely positive on how this would be a great fit for reading from large numbers of heterogenous views/queries as:

1) one kafka topic per query would be overkill on the kafka side
2) polling materialize requires materialize to meet very stringent p99.9%s on each polling request.

In contrast, they can tolerate weaker p99 latencies with LISTEN/NOTIFY, and it would be their chosen deployment strategy.

We should scope out how much work this would be to support so that we can appropriately milestone and schedule it, cc @cuongdo.

**Comment by benesch** [comment]
To be quite honest I don't understand the suggestion here. I was confused when this issue was originally filed, and doubly so now. 

`NOTIFY` is not meant for transferring large amounts of data. The payload is limited to 8K. So you'd send a notification like "check view07", and the client would need to go `SELECT * FROM view07` to retrieve the new data. That doesn't sound like a great user experience to me?

Concretely, what problem are we trying to solve? What would this give us over the existing `TAIL` implementation? Why can't they just open a connection and run `TAIL` for every query of interest?

**Comment by sploiselle** [comment]
@benesch I believe this gist of this is how to get `TAIL` to work with something like a JDCB driver; the postulation is that `LISTEN`/`NOTIFY` might give us the right semantics to support that. No idea if this particular approach is feasible or not.

**Comment by rjnn** [comment]
Sorry, I did the cc ping just to alert him that this issue exists, so that he was aware of the "alternate paradigm" when it came to documenting things, so that we're not caught off-guard

**Comment by benesch** [comment]
We support this in the pgwire protocol via `COPY`, cursors, and streaming directly for clients that support it, so closing this!
