### ISSUE TITLE
Add precision type modifier to time, timestamp and interval types to improve compatibility with Postgres

### ISSUE THREAD

**Issue by nharring-adjacent** [MaterializeInc/materialize#10837]
### Feature request

The Postgres definitions of `time`, `timestamp` and `interval` all support an optional type modifier to limit digits of precision retained for the seconds field which is not currently present in the equivalent Materialize types. The current Materialize behavior operates using the maximum digits Postgres supports, so Materialize will never return answers which are less precise than the equivalent query in Postgres; however, the difference in precision can compound through arithmetic operations and yield meaningfully different answers to the same query.

**Comment by Linksku** [comment]
I also want to add that allowing `timestamp(3)` should improve compatibility with Kafka timestamps, which only support milliseconds. Since Materialize's timestamps are microseconds, it's pretty tricky to get Kafka to interpret them correctly. I may have to change all `timestamptz`s to `bigint`s.

Related Kafka issue: https://issues.apache.org/jira/browse/KAFKA-10561
