### ISSUE TITLE
regression: SELECT against a postgres source never returns

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11170]
### What version of Materialize are you using?

c5e680282b

### How did you install Materialize?

Docker image

### What was the issue?

This has happened once in CI https://buildkite.com/materialize/tests/builds/30325#0839949a-2e35-4cde-876f-5dd54f88e358 and once for me on a scratch machine. The symphoms are as follows:

1. querying the postgres source hangs and never returns.
2. It is possible to create new connections to the database, so the coordinator is not wedged
3. It is possible to query other tables
4. COPY TAIL does not return anything
5.  AS OF 0 and AS OF very_large_number also hang
6. It is posssible to use Ctrl+C to terminate the query

**Comment by mjibson** [comment]
https://github.com/MaterializeInc/materialize/pull/10997 comes to mind as a possibility.

**Comment by philip-stoev** [comment]
@mjibson Yes , seems like a "timestamps are not advancing" type of situation. Since this is very difficult to repoduce, could you suggest any debugging / tracing /println-ing that I can put in so that if I am able to reproduce it once, enough debugging information is captured?

**Comment by mjibson** [comment]
The `AS OF 0` failing actually makes me think this isn't 10997. That PR allows a query that we previously didn't allow, where if a thing advertised a since and upper of 0, we previously would have complained (with "no complete timestamps") but now will say "oh, sure, timestamp 0 is fine because the thing says that will be its first complete timestamp". However, since testdrive retries, even if it had gotten the no complete timestamps error it would have eventually resolved and the tests pass. But after 10997 the SELECT will block, but we'd still expect it to eventually return because it eventually returned before the PR anyway.

When I see bugs like this I will add a println around the timestamp used by a peek (say, the `timestamp` variable at https://github.com/MaterializeInc/materialize/blob/0aba0e4b6b0a9173af3ca5b330791fd677d4deca/src/coord/src/coord.rs#L2929). This lets me see the chosen timestamp for a query. We still need information about the since and upper of the thing being queried, so we know the state of the source/index/table/etc. I'm not aware of a great way of doing that besides adding more printlns to `determine_timestamp` (around things like `least_valid_read` and `least_valid_write`), or maybe using some internal introspection mz_* thing. I've wanted a thing that would help debug this for a long time.

**Comment by philip-stoev** [comment]
This is a duplicate of https://github.com/MaterializeInc/materialize/issues/11170 , fixed by https://github.com/MaterializeInc/materialize/pull/11141 . I did not realize that #11170 has not yet been fixed yet in full in "main" . There go 2 working days bisecting.
