### ISSUE TITLE
Spec out the behavior of `AS OF now()`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11188]
Forked from "item 2" in #10587.

It is not clear what the behavior of `AS OF now()` should be. Here is an example of a defect in the current behavior, courtesy of @philip-stoev:

```
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now            | count  
---------------------------+--------
 2022-02-10 12:59:04.72+00 | 100000
...
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
ERROR:  Timestamp (1644497944988) is not valid for all inputs: [Antichain { elements: [1644497944999] }]
```

Thoughts from @frankmcsherry:

> This is "in spec" at the moment, but we should be able to fix it. Imo the coordinator should probably not compact things past now() rendering them invalid at the moment. Afaict, the only way to get the "is not valid for all inputs" is to have a query that prescribes a query time, and unfortunately if inputs have been compacted past that time we cannot pick a new time to catch up to (without violating the AS OF constraint). But we can prevent the coordinator from compacting past now().

Additional Slack discussion: https://materializeinc.slack.com/archives/CMHDK0DK8/p1647096901970989

**Comment by mjibson** [comment]
I think we should probably try to not break too many users. Here's a proposal. `AS OF EARLIEST IN TIMELINE` returns the `since`. `AS OF LATEST IN TIMELINE` returns the `upper`. `AS OF now()` is an alias for `AS OF LATEST IN TIMELINE`. Making now an alias feels like it'll not break people, and we can stop telling anyone to use it? I'm also fine just making it error instead, but that seems maybe abrupt. One problem with that is it won't match `now()` in a select list but...I am perhaps not worried about that too much because mixing now with timestamps has always been wrong but we did it anyway.
