### ISSUE TITLE
Chaos Test kafka integration

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1130]
Currently it is possible for us to produce _incorrect_ data if kafka restarts but materialize stays up.

We don't know all the ways that this can go wrong, so we need to have a set of data that we understand well enough that we can spot problems if we turn kafka off and back on again.

**Comment by wangandi** [comment]
> Currently it is possible for us to produce _incorrect_ data if kafka restarts but materialize stays up.

@quodlibetor Is there a particular query associated with the incorrect data production? In what way is the data incorrect?

**Comment by wangandi** [comment]
A basic spec-ing out of my impression of what the chaos test should look like.

* The test script shall do the following:
    1. Turn on `materialized` + relevant dependencies.
    2. Spawn a monkey command that runs in the background.
    3. Start some form of test application that runs in foreground. Whatever this application is, it will run one or more sql queries/statements in materialize against some load
    4. Within X amount of time after the test application turned on in step 3 has been running, the monkey will shut down dependent component Y for Z amount of time, after which the monkey will restart the dependent component. X, Y, and Z are all randomly generated.
    5. Repeat step 4 if we desire to test multiple instances of chaos per run
    6. The test application should verify that `materialized` conforms to some <goal>. The most basic goal would just be that `materialized` does not crash. An advanced goal would be to ensure that `materialized` returns some expected answer in f(Z) time.

* When we add chaos testing to Buildkite, it should be a separate pipeline just like full sqllogictest. Due to the randomized nature of the chaos testing, we wouldn't want to block merges if we manage to stumble upon an error in one run.

I have several questions about the parameters of the chaos testing:

* Do we just care about Kafka restarting, or do we also care about other parts of the streaming pipeline? I'm in favor of including anything Materialize directly interfaces with, such as Schema Registry and anything that would prevent something that Materialize directly interfaces with from running correctly, i.e. Zookeeper. I'm not sure if we need include Debezium considering it is one step removed from us.
* Do we just care about dependent components restarting? Or would we also like to simulate other issues, like a message with a particular timestamp being very laggy, or network issues? 
* What's the longest amount of time that we want to test a component being down for? Several minutes? Alternatively, we could make the maximum downtime be a function of the randomly generated timeout setting for that component. 
* Should data be pre-loaded in Kafka by the time a component is brought down, or should data still be streaming in?

**Comment by quodlibetor** [comment]
These are great questions! I think the way you're thinking about it is right, and that we should phase the work so that we can start with basic sanity checking and work our way through to deep confidence.

Direct answers:

> * Do we just care about Kafka restarting, or do we also care about other parts of the streaming pipeline?

I think we care about everything, but different things different amounts, see the phases I suggest below.

> * Or would we also like to simulate other issues, like a message with a particular timestamp being very laggy, or network issues?

This is interesting! I think we should create a separate issue to track network performance. I do think it's important, but sorta out of scope, and should probably be integrated with our consistency-verification testing.

> * What's the longest amount of time that we want to test a component being down for? Several minutes?

Yeah it would be nice if this were parameterizable, but I'd say at least 10 seconds while we're under low load (10s of updates per second), and several minutes if mz & co are under high load (meaning 100s or 100s of thousands of updates per second)

> * Should data be pre-loaded in Kafka by the time a component is brought down, or should data still be streaming in?

Both, see my suggested phases below.

---

To that end:

## phase 1

Basic sanity checking

Only Unreliable thing is Kafka:

### setup

* Known snapshot of a DB, with a deterministic script that can write to it

### chaos

1. restart kafka, ensure no data has changed
1. start and stop the data generator and verify that data looks right
1. restart kafka, ensure things look right
1. keep the data generator going and restart kafka, verify

## phase 2

CDC sanity

Unreliability of kafka + debezium

### setup

same as phase 1

### chaos

Same as phase 1, but we double the number of pauses/restarts to do everything for both kafka and and debezium

1. restart kafka, ensure no data has changed
1. start and stop the data generator and verify that data looks right
1. restart *debezium*, ensure no data has changed
1. start and stop the data generator and verify that data looks right
1. restart kafka, ensure things look right
1. keep the data generator going and restart kafka, verify
1. keep the data generator going and restart *debezium*, ensure things look right


## phase 3

Infrastructure confidence

Unreliability of everything

As a fully separate test, we run the same script as before but randomly kill various services and bring them back up.

**Comment by quodlibetor** [comment]
to be clear: those phases are just what I'm imagining, I do _not_ think that we have to do them if you think that there's a better way to do it!

**Comment by ruchirK** [comment]
@wangandi -- you can build on top of the billing demo for this if you'd like. I was curious so I ran the billing demo and shut off kafka in the middle (after the demo script was done writing to it). Materialize handled requests correctly while kafka was down and after kafka was restarted but I saw a bunch of 

```
Feb 20 16:24:29.426 ERROR dataflow::source::kafka: duplicate Kakfa message received
```
and

```
Feb 20 16:26:16.412 ERROR coord::timestamp: Failed to obtain Kafka Watermark Information: u60/u62 Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
```

I'm going to add correctness checks in billing demo soon (thats part of the 0.2 milestone) and I think this could be an interesting extension of that.

(Not trying to tell you what to do by any means -- feel free to fully disregard :) )

**Comment by cuongdo** [comment]
@wangandi Could you pick up this work again after wrapping up your current upsert work? I believe you've already made progress.

**Comment by cuongdo** [comment]
Assigned to @JLDLaughlin, who is taking this issue over.

There are at least two types of Kafka chaos we should test:
1. Kafka broker stopping and restarting
2. Debezium connector stopping and restarting

I believe these cover the real-world cases we've seen so far.

cc @benesch for additional thoughts

**Comment by benesch** [comment]
Stopping/starting is definitely the place to start. It would also be great if we could inject some chaos on the level of a single Kafka API request. What happens if we randomly drop some Kafka requests on the floor? What happens if we make every metadata request take 5s to complete? What happens if we drop all messages for one partition for a minute? 

That's probably too many ideas to be actionable, but just a blanket turning up the latency on all the Kafka requests from 10ms to a few seconds would be very high value.

**Comment by JLDLaughlin** [comment]
For posterity, a first version of this exists now! Details and instructions are here: https://github.com/MaterializeInc/materialize/tree/master/test/chaos

**Comment by cuongdo** [comment]
Our basic chaos tests are sufficient for now. Filed #3611 as a followup.
