### ISSUE TITLE
platform: networking not robust against incomplete handshakes - pinging a TCP socket causes the various daemons to disconnect

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11444]
### What version of Materialize are you using?

v0.23.1-dev

### How did you install Materialize?

Docker image

### What was the issue?

If an open TCP socket on coord / dataflowd receives a connection that is then terminated, it will either exit or refuse to service future connections.

Internally, this is a problem for testing, as e.g. test/cluster/mzcompose.py can not use any `wait_for_tcp` directives to make sure each container is fully up before starting another one.

More importantly however, this is going to be a problem in any network environment where port scans and other such traffic may happen. Even in the absence of third-party actors on the network, the daemons themselves may happen to not complete a handshake before terminating for some reason, leaving their counterparty in a bad state. This is especially important in the case the daemon that has been pinged does not exit , but stays up but is unable to accept any new actual connections.

So I think all networking must be made robust against incomplete handshakes. This ticket is intentionally vague on which daemons/ports are affected partially because I am lazy to produce a targeted test case and partially to make the discussion and a fix generic and across the board, rather than about a particular service pair/tcp port.

To reproduce, attempt to modify test/cluster/mzcompose.py to wait for each daemon to become pingable before moving on to the next one. I can provide a diff if needed.

**Comment by antiguru** [comment]
Thanks for pointing out this problem! Some parts can accept reconnects, but it's behind a flag because we're not sure what it should look like in the future. #11394 added a `--linger` flag to `dataflowd`, where it learns the ability to accept another connection after the previous one vanishes. It's not perfect as someone could just connect to the port and idle, but it's a step in the right direction.

**Comment by benesch** [comment]
Eh, I think this is actually working as designed at the moment! These processes are not really meant to be operated directly by humans, but always orchestrated via Kubernetes. Several of the services can only handle one coordinator connection over their lifetime and simply must be restarted if that connection ever goes away; therefore exiting on any sort of failed TCP connection is exactly the right approach. It all works out fine in Kubernetes land, because Kubernetes will simply restart the process.

We can add a different port with a health endpoint, for sure, but I don’t think there is anything fundamentally wrong with the current philosophy, given the current use cases for `dataflowd`.

**Comment by benesch** [comment]
@philip-stoev `storaged` and `computed` both expose an "internal HTTP port" now, by default on 6877, that has an /api/healthz endpoint, among other things. It is safe to connect to this port repeatedly. Similarly, it is safe to connect to the controller port multiple times. You still can't ping the timely ports—those are single use—but that is by design, and a failed handshake will (correctly) cause a crash. I think this should be considered sufficient to call this closed!

**Comment by benesch** [comment]
Hearing nothing, optimistically calling this one closed!
