### ISSUE TITLE
[Epic] Correctness prop #2: Linearized source creation

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11632]
## Product Outcome
Users never experience a state in materialize that wasn't in their upstream systems. 

## Work items

* [x] #13639

### Additional context
---
The second of three consistency desiderata.

Materialize assigns timestamps to all events, and behaves as if the events occur in this order. Materialize can and should respect the orders presented by its external input sources. For example, in mirroring a transaction log from a serializable source, Materialize should reflect the serialized order of events experienced by that source (if that information is available).

This issue connects with other issues we have tracked about respecting transaction boundaries in the source, and may not be fundamentally novel in that sense. It exists so that we can track progress toward making this concrete claim.

This property seems almost exclusively in the domain of the source implementations. It requires some ownership to make sure we get it right (e.g. we must not only order events correctly but not drop them, among potentially other subtleties).

---

**Comment by benesch** [comment]
I'm going to remove the **M-platform-blocker** label. We believe we do this correctly for direct PostgreSQL sources. We do this correctly for Kafka sources, in that we preserve partition order. There is one wrinkle with Debezium + Kafka, where one might hope that we would support the transaction metadata topic to preserve transaction order from the upstream database, but we do not.

What's lacking here is documentation. Leaving this issue open to track adding documentation that publicly commits us to the above.

**Comment by frankmcsherry** [comment]
I think we are farther away from closing this issue than documentation, unfortunately! I could be wrong, but:
1. We present postgres sources as queryable with empty contents until the snapshot loads. However, we don't have any evidence that the tables were actually empty (pedantically, they could have been the result of `CREATE TABLE AS`).
2. We present post-compaction upsert Kafka data in offset order, but this may reveal impossible states. For example, if I wrote to Kafka `"A: 1"`, then `"B: 2"`, then `"A: 7"` I may be shown  `"B: 2"`, then `"A: 7"` exposing a state with a `B` present but not an `A`, which is incompatible with the order of events.

I think both of these are fixed by assigning all updates in the initial snapshot the same timestamp, and using that timestamp for the `since` (making it unqueryable before this time).

**Comment by benesch** [comment]
Ah, I see. I didn't read that as a hard requirement of the issue description as written. It feels like there is a philosophical question of whether sources must spring into existence with their initial contents, or whether there is always a moment before the beginning of any reported events in which every source is empty.

I think that (1) makes quite a bit of sense for PostgreSQL sources, given the existence of `CREATE TABLE AS`. We should respect the fact that tables in PostgreSQL can spring into existence with initial data.

With Kafka, the problem is more general than the initial load, no? At any point, if ingestion falls behind the compactor, we may observe states that did not actually exist. It's most acute during initial load, because initial load of a sufficiently old topic is _guaranteed_ to have had compactions; whereas you'd hope steady-state ingestion is staying well ahead of the compactor.

But... imagine a fast-changing Kafka topic with an hour long compaction policy. If Materialize has a two hour outage, when it comes back online, it will miss some of the data in the topic, and present states that did not actually exist in Kafka.

In a live conversation with @frankmcsherry just now, he proposed that we solve this like so: on every reboot of a `storaged` process handling a Kafka source, ask Kafka for the maximum offset, and then timestamp everything between the last offset ingested and the current offset reported by Kafka with the same timestamp. 

There still exists a very minor race. If the compactor manages to delete data between when we're told about the maximum offset and when we can ingest up to the maximum offset, we're out of luck. But making this 100% correct is impossible with Kafka's API. You'd need an API like "tell me about the current maximum offset, and don't compact up to that offset until I acknowledge that I've read all the data through that offset", and that API just does not exist.

**Comment by petrosagg** [comment]
The approach checks out to me!

> If the compactor manages to delete data between when we're told about the maximum offset and when we can ingest up to the maximum offset, we're out of luck. But making this 100% correct is impossible with Kafka's API.

I think we could make this tighter if we wanted to because we can check for max offsets during the initial load and realize that "oh while reading up to what I thought was the max X more messages have arrived", pushing the target offset further until we're below some threshold

**Comment by benesch** [comment]
We got a question on the community Slack today about our failure to uphold this property: https://materializecommunity.slack.com/archives/C015KDVS7EV/p1684887031685089

The example given is _very_ concise and really drives home why this is important.
