### ISSUE TITLE
[Epic] Protobuf support for ComputeCommand

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#11735]
This story is part of the overall versioning epic that spans all teams.

### Goals

* Introduce protobuf types for transitive dependencies of [`ComputeCommand`](https://github.com/materializeinc/materialize/blob/ca1fbefda/src/dataflow-types/src/client.rs#L108-L141)
* Implement mapping between regular and Protobuf-variants of types

### Non-Goals

* End-to-end version upgrades

### Acceptance criteria

The communication layer accepts data in a stable representation specific to the API versions it supports.

### Subtasks

The following subtasks enumerate all structures that need to be serialized as Protobuf.

- [x] #12242
- [x] #12461
- [x] #11737
- [x] #12240
- [x] #11971
- [x] #11738
- [x] #11739
- [x] #11927
- [x] #11928
- [x] #11970
- [x] #11929
- [x] #11930
- [x] #11740
- [x] #11742
- [x] #11743
- [x] #11744
- [x] #11745
- [x] #12125
- [x] #12333
- [x] #11972
- [x] #11973
- [x] #11750
- [x] #11751
- [x] #11752
- [x] #11753
- [x] #11754
- [x] #11755
- [x] #11760
- [x] #11759
- [x] #11756

### Related
* [Implementation strategy alternatives (Google doc)](https://docs.google.com/document/d/1OBc3bDZa6ag3a-LoBV8JqMqJ9CKv2qQz2IVgD6TcpjI/edit)
* [Binary architecture braindump (Notion)](https://www.notion.so/materialize/Binary-architecture-braindump-062b27e3d21c491cbfbd011972192181)

**Comment by aalexandrov** [comment]
@sploiselle / @mjibson as we are working our way through all of the types that are listed in this meta-issue, I am a bit worried about conflicts with concurrent modifications on these structures due to SQL evolution. Do you know issues that are planned for the next 2-3 weeks on that end? We might have to coordinate a bit in order to avoid massive merge conflicts.

**Comment by sploiselle** [comment]
All of the items listed in `mz_expr` are stable and I don't expect any substantial changes to them in the next 2-3 weeks. Are there any particular changes you're worried about?

@petrosagg has been working on moving the `mz_expr::scalar::func::*` implementations to dynamic dispatch on and off again. Currently, this is only supported for `UnaryFunc`, so that code is in a bit of an odd state. If you can make the current split state of the code work with protobufs, though, I imagine that it will be possible for us to reach the end goal of a world where all of those items are handled via dynamic dispatch.

**Comment by aalexandrov** [comment]
No, I just want to raise awareness that efforts such as adding new function types or moving types around might create conflicts for types that are currently in progress. I am working on `UnaryFunc` now, but sadly this is not a one-day job.

**Comment by sploiselle** [comment]
Ah @aalexandrov, we're likely to add new functions in the next 2-3 weeks, but those items are most likely to be additions of very small changes. The SQL team is glad to handle/help during the rebase process if that turns out to be challenging whatsoever.

**Comment by petrosagg** [comment]
@sploiselle I moved a few more functions over https://github.com/MaterializeInc/materialize/pull/11788

We need a few more pushes to finally complete the transition

**Comment by aalexandrov** [comment]
> We need a few more pushes to finally complete the transition

I think we can allocate some cycles of doing that as part of this effort.

**Comment by sploiselle** [comment]
@aalexandrov Sounds good--thank you!

**Comment by lluki** [comment]
Do we need support `timely::progress::Timestamp` typed commands or is `mz_repr::Timestamp` (= a single u64) enough?

**Comment by mjibson** [comment]
I'm not sure about that specific question but we need to support changing `mz_repr::Timestamp` to an `i64`, which may happen at some later date, so just don't make things too dependent on `u64`.

**Comment by lluki** [comment]
So if at any point in time (ignoring a phase where we have to remain backwards compatible) only have to support one type, then I'd simply encode it as `u64` for now.  If we go to `i64` that should not be too complicated, as far as I can see there are only two cases where we actually encode it in a message (`Peek` and `Plan::Constant`). 

If on the other side we use these two or more different timestamp types at the same time, it might be worth it to come up with something smarter (to automatically infer the type from a message, for example).

**Comment by mjibson** [comment]
We will only ever have one. If we switch, it'll be everything at once.

**Comment by aalexandrov** [comment]
Closing this now... :tada: :tada: :tada:
