### ISSUE TITLE
storage: decide whether the remapping collection itself must preserve transactional boundaries

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11952]
The [reclocking implementation design document](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220411_reclocking_implementation.md#remap-policy) makes the following claim:

> We will impose an additional policy constraint on our implementation: if transactional boundaries are present in the upstream source, events in the same transaction must be mapped to the same timestamp.

@petrosagg had a concern about this constraint: https://github.com/MaterializeInc/materialize/pull/11718#discussion_r853709649

I want to make sure we hash this out! To me it seems quite important that reclocking collection never produce a mapping that cleaves an upstream transaction in two, but perhaps I don't understand something about the decoding pipeline.

cc @petrosagg @frankmcsherry

**Comment by frankmcsherry** [comment]
Is there an explainer for how things work in the case of "we do reclocking, and only discover transaction boundaries later in the decoding pipeline"? Like, we do introduce timestamps (somehow) in that case, but then .. are careful to only delay the timestamps of contributions to a transaction?

As another example, CDCv2 basically doesing give af about timestamps you assign to the data that get read out of Kafka, or wherever, and just independently determines what timestamps it should use and takes care of all that, but it does fall outside the standard pipeline that we use. Is this maybe a sign that not everything needs to fit in this framework, just the things that don't come with timestamping opinions? Or maybe it's more subtle in that the transaction folks come without total timestamping information, but still have opinions.

**Comment by petrosagg** [comment]
Here is how I understand the space of transactions and reclocking. 

1. The source's gauge by itself encodes the transaction boundaries. This is the case with pg sources where it will emit a transaction with the same offset (the commit lsn). In those cases reclocking preserves the boundaries trivially because it will associate a particular offset with a particular timestamp.
2. The transaction boundaries are discovered later in the pipeline and gauges don't encode anything related to transactions. In those cases the reclocking operation does not have to preserve the boundaries because downstream processing will reconstruct transactions by either delaying timestamps to appropriate time (this is what happens when we process the debezium transaction topic) or it will completely ignore them and reconstruct a stream some other way (e.g CDCv2).

So my main point is that reclocking shouldn't care about maintaining transaction boundaries, only that a particular gauge offset is mapped 1-1 to a particular timestamp (modulo compaction).

Since we're here, I wanted to mention the opposite problem that reclocking can cause which is something we discussed with Kyle too. Imagine a kafka topic that receives two writes `w1` and then `w2` but when we reclock the topic we bundle `w1` and `w2` into the same timestamp. In this case if a user creates the trivial sink to their kafka that just `selects * from src` it's possible that they see `w2` and then `w1`, which is extremely surprising.

In order to fix this issue we need to come up with a function with the following signature:

```rust
fn interpolate(
    since_ts: Timestamp,
    since_frontier: Vec<(PartitionId, Offset)>,
    upper_ts: Timestamp,
    upper_frontier: Vec<(PartitionId, Offset)>,
    gauge: (PartitionId, Offset)
) -> Timestamp
```

which has the property that for every value of `gauge` that is between the `since` and `upper` frontiers it returns a **unique** timestamp that is between `since_ts` and `upper_ts` and maintains the property that for a given partition `p1` and offsets `o1`, `o2` where `o1 < o2` then it maps `interpolate(p1, o1) < interpolate(p1, o2)`.

If you imagine the since/upper frontiers arranged in a grid with columns being the partitions involved and offsets increasing downwards then we could implement this with some kind of space filling curve that has the above properties (I believe Z-Order does).

**Comment by frankmcsherry** [comment]
> Imagine a kafka topic that receives two writes w1 and then w2 but when we reclock the topic we bundle w1 and w2 into the same timestamp. In this case if a user creates the trivial sink to their kafka that just selects * from src it's possible that they see w2 and then w1, which is extremely surprising.

I'm confused about how they see "w2 and then w1" as opposed to "both w2 and w1" which seems like a legit outcome?

**Comment by petrosagg** [comment]
What I meant by "and then" was in a spacial sense, that in the sink kafka topic `w2` will have an earlier offset than `w1`

**Comment by benesch** [comment]
> The source's gauge by itself encodes the transaction boundaries. This is the case with pg sources where it will emit a transaction with the same offset (the commit lsn). In those cases reclocking preserves the boundaries trivially because it will associate a particular offset with a particular timestamp.

Porting over my comment from the prior discussion here. Doesn't each message have its own LSN? In the `wal_start` field of the `XLogDataBody` type? https://github.com/MaterializeInc/materialize/blob/07c8bd965b9928886d310fe36093cf13d08bfbb7/src/storage/src/source/postgres.rs#L404

We just (correctly) ignore it in our impl, and replace it with the end LSN of the transaction instead.

> The transaction boundaries are discovered later in the pipeline and gauges don't encode anything related to transactions. In those cases the reclocking operation does not have to preserve the boundaries because downstream processing will reconstruct transactions by either delaying timestamps to appropriate time (this is what happens when we process the debezium transaction topic) or it will completely ignore them and reconstruct a stream some other way (e.g CDCv2).

So, the Debezium txn topic approach sketches me out a bit! If the data topic operator were to produce timestamps that skewed wildly with the metadata topic operator, the ingestion process has latency proportional to the amount of skew. In other words, it creates an implicit coupling between the timestamps assigned by these two operators that ought to be independent, IMO.

It seems like we should hoist the data ingestion out of timely, so that we don't need to invent a timestamp for it. And then the moment we attach a timestamp is the moment we join the data with the output of the timestamp bindings collection.

**Comment by petrosagg** [comment]
> Doesn't each message have its own LSN?
> We just (correctly) ignore it in our impl, and replace it with the end LSN of the transaction instead.

Yes and yes, and I think this is the only sensible thing we could do because the intra-transaction LSNs might jump backwards. But even if they didn't we should still put the responsibility of encoding transaction boundaries into offsets (if any) to the source implementation and not on reclocking.

> If the data topic operator were to produce timestamps that skewed wildly with the metadata topic operator, the ingestion process has latency proportional to the amount of skew. In other words, it creates an implicit coupling between the timestamps assigned by these two operators that ought to be independent, IMO.

Yes that's currently the case but only because Chae wanted to merge the initial implementation before fixing this. In timely when you create an operator with more than one inputs you can be explicit about how the timestamps of those inputs flow into the output, and in particular we want the dbz tx operator to declare that the data collection timestamps never flow into the output and only the metadata collection timestamps do. The issue for this is https://github.com/MaterializeInc/materialize/issues/11792 and the timely API used to describe this is [`OperatorBuilder::new_input_connection`](https://docs.rs/timely/0.12.0/timely/dataflow/operators/generic/builder_rc/struct.OperatorBuilder.html#method.new_input_connection) (see the docs for the `connection` argument).

**Comment by benesch** [comment]
> > Doesn't each message have its own LSN?
> > We just (correctly) ignore it in our impl, and replace it with the end LSN of the transaction instead.
> 
> Yes and yes, and I think this is the only sensible thing we could do because the intra-transaction LSNs might jump backwards. But even if they didn't we should still put the responsibility of encoding transaction boundaries into offsets (if any) to the source implementation and not on reclocking.

What's the rationale? It seems easier (to me) to reason about the pipeline if data timestamps are 100% determined by the remap collection.

> > If the data topic operator were to produce timestamps that skewed wildly with the metadata topic operator, the ingestion process has latency proportional to the amount of skew. In other words, it creates an implicit coupling between the timestamps assigned by these two operators that ought to be independent, IMO.
> 
> Yes that's currently the case but only because Chae wanted to merge the initial implementation before fixing this. In timely when you create an operator with more than one inputs you can be explicit about how the timestamps of those inputs flow into the output, and in particular we want the dbz tx operator to declare that the data collection timestamps never flow into the output and only the metadata collection timestamps do. The issue for this is #11792 and the timely API used to describe this is [`OperatorBuilder::new_input_connection`](https://docs.rs/timely/0.12.0/timely/dataflow/operators/generic/builder_rc/struct.OperatorBuilder.html#method.new_input_connection) (see the docs for the `connection` argument).

Oho! Cool. So the only constraint, IIUC, is that the data operator use the same timestamp _type_ as the metadata operator? But it could use integer timestamps that count up monotonically from 0, for example?

**Comment by petrosagg** [comment]
> Oho! Cool. So the only constraint, IIUC, is that the data operator use the same timestamp type as the metadata operator? But it could use integer timestamps that count up monotonically from 0, for example?

That's right!

**Comment by benesch** [comment]
Discussion has proceeded by way of this design doc! https://www.notion.so/materialize/Source-ingestion-pipeline-1681a9b12245438ba4381ddde3f8af77
