### ISSUE TITLE
A first query (while indexing) returns incorrect result

### ISSUE THREAD

**Issue by tankoand** [MaterializeInc/materialize#12019]
### What version of Materialize are you using?

v0.26.0 (07670312b)

### How did you install Materialize?

Docker image

### What was the issue?

I'm using Materialize v0.26 with a source DB Postgres 14. After initializing a Postgres source with:

`  CREATE materialized SOURCE mz_source
    FROM POSTGRES
      CONNECTION 'host=xxx port=5432 user=xxx dbname=xxx password=xxx'
      PUBLICATION 'mz_source';
      CREATE VIEWS FROM SOURCE mz_source;`

, the CPU is very active. If in that time, I try to execute a query such as `SELECT count(*) from table1` (table1 is from the Postgres), it returns incorrect result (0) and takes a long time to finish. When I try to execute the same query again, it is finished immediately and result is correct.

### Relevant log output

```source
Nothing relevant in logs.
```

**Comment by frankmcsherry** [comment]
Hi! What you are seeing is a reflection of the fact that Materialize is an *asynchronous* replica of postgres, and only provides [serializability](https://jepsen.io/consistency/models/serializable) rather than [strict serializability](https://jepsen.io/consistency/models/strict-serializable) with respect to external sources. We intend to do the latter for postgres sources, for the same reason you expected to see a non-zero output, and there is an issue to track our progress: https://github.com/MaterializeInc/materialize/issues/11531

**Comment by philip-stoev** [comment]
@petrosagg this was detected and fixed once already when pg-cdc sources were introduced. Previously, the source was returning an empty result set until the snapshot was complete. With the fix , it started returning "no complete timestamps yet" if I recall correctly. I wonder what regressed now so that returning the empty result set is back.
