### ISSUE TITLE
Create sources "as of" a timestamp/frontier

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1210]
When loading data from long lived logs, we have a great deal of historical detail presented to us. Differential dataflow respects the rich detail and both computes and maintains all of this detail, doing a fair bit of work to relate the history of your view across the loaded data.

Often no one cares about the past, and just wants to get going on their current view, from now (or maybe now minus a few minutes).

If sources were created with a timestamp or frontier indicating that they are only usable after these times, we could compact times as we load the data, which results in less compute and memory used as we load things up. We bypass "slow mode", which appears to be us serving answers from arrangements of rich and complicated histories, and generally are much better.

Additionally, I think we'll need to get our heads around sources having an "as of" time in that several classes of inputs will possibly be self-compacting. If Debezium crashes, it may need to do a new full table scan, and has missed some changes that the database underwent. On recovery, it has a consistent view but only one that is valid from the recorded times going forward.

Related to #1074 

cc @jamii @quodlibetor

**Comment by nacrooks** [comment]
A possible workaround is to use Kafkacat, which allows you to copy a topic to a different topic starting from a particular offset

**Comment by ruchirK** [comment]
Documenting a few thoughts from a conversation I had with @nacrooks 

I don't think AS OF (earlier time) is possible for sources that do realtime timestamping, simply because the mapping from messages <-> timestamps is not known at the time a user instantiates the source, and all of the records in a source get mapped to timestamps that come _after_ source creation. This is not an issue for BYO consistency because it is known in advance which messages have which timestamps

Two workarounds:

1. AS OF NOW -- have the code read in current max offsets (or whatever indicator of write progress like line number) and compact and coalesce all records before that time
2. AS OF (kafka offset) -- likely not really a workable solution for multi-partition topics unless the user wants to specify a list of offsets? Also very kafka specific.

**Comment by frankmcsherry** [comment]
This seems maybe fine, for it not to work? I think of RTTS as doing some impromptu compaction, and if you tried to load up a source that only had compacted input (for some reason) it should probably fail too (ideally at CREATE SOURCE time).

Perhaps related to RTTS though, it might be good to be able to pilot its timestamps a bit more. At least, if the goal is to get the input all in at some time like NOW and not have it slow-roll the dataflow, that seems like a similar goal as AS OF.

**Comment by frankmcsherry** [comment]
Comment from discussion with @ruchirK 

The intent of this issue is more aligned with instantiating sources with an `as_of` argument than it is adding `AS OF` syntax to the `CREATE SOURCE` command. Both are reasonable to investigate, but the former is (I believe) the one that leads to improving the user experience of loading data without historical detail.

This is difficult to prompt in materialized at the moment, as the only dataflows that install sources are materializations, and the only dataflows that provide `as_of` times are peeks. If we allowed peeks against unmaterialized views or sources, this would immediately become a pain point that the issue would fix. That we cannot easily wire up the dataflows that would make the remedy easily available may be more the subject of #2310.

**Comment by rjnn** [comment]
Just a heads up that one prospect gave me the valuable feedback that this feature is super important because _oftentimes the start of the stream is full of bad dev data_ and things only iron out (in terms of schema being ironed out, all columns being present, NULL treatment, etc.) after some point in time. They know the offset at which they want to read, but they do need the knob to keep Materialize from throwing parsing errors or other such things before that point. (e.g. if they switched out Avro schemas in a backward-incompatible way)

**Comment by frankmcsherry** [comment]
Just to call out an important difference: this isn't meant so much as starting from a weird Kafka offset, which is probably an important thing independently, but rather making sure that timestamps can be compacted up to some specific logical timestamps in materialized. We might want to file that under a separate issue, though!

**Comment by rjnn** [comment]
Oops! Filed #2656 to track that, thank you!

**Comment by frankmcsherry** [comment]
This is partially addressed by https://github.com/MaterializeInc/materialize/pull/2797 but which does not get at `CREATE SOURCE .. AS OF ..` (rather, it is about creating the source in the dataflow layer to respect the supplied `as_of` frontier).

I don't want to close this without trying to capture the thinking about what `CREATE SOURCE .. AS OF ..` would want / need / is it even important, but we could consider a newly formed issue about that topic. Any thoughts on that @ruchirK?

**Comment by frankmcsherry** [comment]
Closing in favor of #2862
