### ISSUE TITLE
[adapter] Reduce `TAIL` read latency after write by closing timestamp

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#12198]
### Feature request

It seems that on writes (in 0.26 LTS) at least, on an `INSERT` we do not immediately close out the timestamp we used for the write. This means that one observing the table through a `TAIL` may have to wait for the background thread to close out the timestamp and make the data visible.

We could instead respond to each `INSERT` by enqueueing a need to close out the timestamp at which we inserted, which we can do almost immediately (as soon as the internal clock has moved one millisecond forward).

**Comment by mjibson** [comment]
This was fixed by #12330. However we don't have a test that makes sure it won't get un fixed in the future should we implement some WAL thing. This request is at a natural tension with perf.

**Comment by mjibson** [comment]
For example, we could very reasonably start caring about users who run INSERT at a more than 1000 per second. The change in 12330 makes it so that that workload will start producing table diff timestamps unboundedly in advance of the system clock and all other realtime source data, which is just bad and will cause joins between tables and realtime stuff (including catalog tables) to block until the realtime sources catches up to whatever the unbounded insert timestamp was. Or maybe there's storage perf issues that cause us to want to batch things (which was the initial reason we did this in the first place). Fixing either of those would "regress" this issue. We may need to design something that can do both of these well.

I've put up PRs in the past (https://github.com/MaterializeInc/materialize/pull/11150, https://github.com/MaterializeInc/materialize/pull/10173) that do something along those lines, or at least make it possible. The thing we might want is: if a table write comes in, block it for 1ms and then commit all other writes that have occurred over that time too, such that we bundle all writes together (good for storage perf), can assign all of them a timestamp that is *not* ahead of the system clock (good for joining with realtime sources), and then can also safely close that timestamp (good for this issue).

**Comment by mjibson** [comment]
cc @jkosh44

**Comment by jkosh44** [comment]
I'm in the process of writing a design doc that references the issue @mjibson brought up and hopefully provides some fixes. I'm hoping to get a PR with it open by EOD.
