### ISSUE TITLE
[Epic] Make Kafka ENVELOPE NONE Sources Fault Tolerant

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12203]
### Description

As part of the [source ingestion pipeline](https://github.com/MaterializeInc/materialize/pull/12109), one of the three properties we desire to satisfy is fault tolerance:

> Our choice of t is meant to provide a "consistent snapshot" of our source pipeline. It is a moment at which we know exactly where we were in input processing (indicated by the reclocking collection), what our "state" was, and what the output corresponded to. With this consistent snapshot, one can resume work and proceed as if without interruption. Multiple concurrent instances should also produce identical outputs, because of the consistent snapshot and deterministic execution (onward, from the reclocking input).

We will start with the simplest case, Kafka `FORMAT BYTES ENVELOPE NONE` sources, for M1, and expand out to everything else for M2 (soft goal of `FORMAT AVRO`).

### Tasks

TBD!
- [ ] Revive pre-Platform persistence test; make sure `ENVELOPE NONE` plus sinks on top of it is represented

**Comment by benesch** [comment]
It's tough to say _exactly_ what the work item here will be until @petrosagg's PR for #12209 lands. Roughly, though, imagine that #12209 is  source ingestion pipeline where we read bytes from Kafka, starting from the beginning of the topic, and write them to persist... but when we restart, we start _again_ from the beginning, and emit a bunch of duplicates into the persist collection. This is technically still definite (i.e., it satisfies #11528), but not the desired behavior of the system. The work item here, then, is to adjust the pipeline so that it restarts in the case of a crash from exactly the point that it left off.

**Comment by nmeagan11** [comment]
Linking the PR: https://github.com/MaterializeInc/materialize/pull/12216

**Comment by benesch** [comment]
Note that #12216 only addresses #12209! This issue will still need to be tackled, i.e.:

> The work item here, then, is to adjust the pipeline so that it restarts in the case of a crash from exactly the point that it left off.

**Comment by petrosagg** [comment]
I believe this is done now that https://github.com/MaterializeInc/materialize/pull/13369 is merged

**Comment by nmeagan11** [comment]
Great, closing!
