### ISSUE TITLE
Rebrand differential/timely env vars as Materialize env vars

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#1223]
There are a few environment variables that control the behavior of Timely and Differential. I'd like us to rebrand these env vars as Materialize env vars or command-line flags, just to reduce the number of concepts that someone interacting with Materialize needs to learn about.

**Comment by cirego** [comment]
Should we bump up the priority of this issue?

It's confusing that we have specific code to handle this in `materialized`, specifically for DEFAULT_PROGRESS_MODE and DIFFERENTIAL_ environment variables.

**Comment by cirego** [comment]
#5055 is an example of why it's confusing.

**Comment by rjnn** [comment]
I disagree with this issue's intent.

> I'd like us to rebrand these env vars as Materialize env vars or command-line flags, just to reduce the number of concepts that someone interacting with Materialize needs to learn about.

The list of environment variables is not long - and they control things that are fairly deep into the weeds in Timely/Differential. One cannot reasonably control those knobs without knowing about Timely/Differential. To make an analogy, this issue proposes something like changing a knob in a car labeled 'fuel injector mixture ratio' to 'car mixture ratio', because fuel injectors are an additional concept that get in the way of changing the mixture ratio. I would instead argue that anyone who doesn't understand fuel injection shouldn't go anywhere near the mixture ratio knob. (Now if, on the other hand, there was a knob on the car labeled "really fast mode", which under the hood manipulated the mixture ratio, that's fine, but that is not what is being proposed here).

#5055 is a separate issue. `DEFAULT_PROGRESS_MODE` is perhaps a knob that could be renamed in order to be more self-explanatory (`TIMELY_PROGRESS_MODE` perhaps? Again, I don't necessarily want to propose a concrete name, because I also do not know what it actually controls). The correct resolution for #5055 isn't to wrap this up with a bowtie, pretend that we know what we're doing, and call it `MZ_PROGRESS_MODE` or `--mz-progress-mode`, it's to propose a rename upstream.

**Comment by benesch** [comment]
> I disagree with this issue's intent.
> 
> > I'd like us to rebrand these env vars as Materialize env vars or command-line flags, just to reduce the number of concepts that someone interacting with Materialize needs to learn about.
> 
> The list of environment variables is not long - and they control things that are fairly deep into the weeds in Timely/Differential. One cannot reasonably control those knobs without knowing about Timely/Differential. To make an analogy, this issue proposes something like changing a knob in a car labeled 'fuel injector mixture ratio' to 'car mixture ratio', because fuel injectors are an additional concept that get in the way of changing the mixture ratio. I would instead argue that anyone who doesn't understand fuel injection shouldn't go anywhere near the mixture ratio knob. (Now if, on the other hand, there was a knob on the car labeled "really fast mode", which under the hood manipulated the mixture ratio, that's fine, but that is not what is being proposed here).

For posterity, I think this analogy misses the mark. The situation in Materialize is more like if your car has a knob somewhere labeled "Stanadyne mixture ratio" rather than "fuel injector mixture ratio". If you don't know much about cars, you're probably not going to touch the knob either way. But you'll have to Google "Stanadyne" to figure out what the heck it is, whereas you might be able to intuit immediately that "fuel injector mixture ratio" is not the knob you're looking for.

Similarly, "dataflow" is more likely to evoke the right intuition in a user than "timely" or "differential" is. Sure, yes, you can't possibly set these knobs without knowing a lot about timely or differential. But the point is the person who sets the knobs will often be different than the person staring down an invocation of `materialized`. For someone relatively unfamiliar with the product, `--dataflow-idle-merge-effort` is more likely to spark the right intuition than `--differential-idle-merge-effort.`

Anyway, the counter argument here, discussed offline, is that it is important to folks that we make the distinction between closed-source Materialize and open-source T/D clear. Retaining the T/D "brand" in our CLI is one way to do that. I cede to that argument, but I am convinced that we're taking a minor hit to usability as a result.

I'm going to close this out, because #5058 in concert with some upstream changes to T/D mean that T/D no longer look at environment variables for configuration. We'll reintroduce environment variable control with a consistent naming scheme for all CLI arguments, so you'll have something like `MZ_DIFFERENTIAL_IDLE_MERGE_EFFORT`. I think that keeps everyone happy: Materialize gets a consistent, branded naming scheme for its environment variables, but the T/D brand is retained.
