### ISSUE TITLE
compute: consider eagerly compacting canceled peeks in controller

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12255]
During #12179, it was surfaced that [`PeekResponse::Canceled`](https://dev.materialize.com/api/rust/mz_dataflow_types/enum.PeekResponse.html#variant.Canceled) could be refactored away, if desired.

There are currently several compute clients (partitioned, replicated) that listen for the `PeekResponse::Canceled` response and use it as a signal to clean up internal state about e.g. which peeks are outstanding. These clients could instead be pivoted to clean up their state when observing a [`ComputeCommand::CancelPeeks`](https://dev.materialize.com/api/rust/mz_dataflow_types/client/enum.ComputeCommand.html#variant.CancelPeeks) _command_.

The implications of this refactor are still in need of some thought. Off the top of my head, it seems like it might be worthwhile, as it will allow us to eagerly remove state about canceled peeks even if replicas are unhealthy.

cc @frankmcsherry @antiguru

**Comment by frankmcsherry** [comment]
To record the discussion: the reason this is non-trivial is that `PeekResponse` is used as positive confirmation back from workers of how they resolved a peek, explicitly distinguishing between rows returned and cancelation. Because the receipt of a cancel request can race with the production valid response, the worker is the only source of truth on which happened. The `PeekResponse` is used to reclaim resources in the compute control plane, and would need to be replaced by a new protocol which doesn't end up sitting on half-formed response data, nor unbounded peek tombstones.

**Comment by frankmcsherry** [comment]
There is a specific behavior we want to introduce that might be a good repurposing of this issue, or it could be a new issue:

When one issues a `SELECT` that stalls out for some reason, e.g. because it has a cross join or `generate_series`, one wants to be able to cancel the SELECT. You can, but the cluster is not usable for a while (until the work has sorted itself out). Sometimes this can crash a cluster (oops) in which case on restart we would like the cancelation to have removed the need to rehydrate the peek. I think this is a fine place to do it, in that we bring the replica up in a consistent state, and the anxiety about race conditions at workers is less stressful.

**Comment by benesch** [comment]
> There is a specific behavior we want to introduce that might be a good repurposing of this issue, or it could be a new issue:
> 
> When one issues a `SELECT` that stalls out for some reason, e.g. because it has a cross join or `generate_series`, one wants to be able to cancel the SELECT. You can, but the cluster is not usable for a while (until the work has sorted itself out). Sometimes this can crash a cluster (oops) in which case on restart we would like the cancelation to have removed the need to rehydrate the peek. I think this is a fine place to do it, in that we bring the replica up in a consistent state, and the anxiety about race conditions at workers is less stressful.

Yes, exactly! I've retitled the issue to be about solving this specific problem.

**Comment by frankmcsherry** [comment]
Fixed by #12536
