### ISSUE TITLE
connectors: Passwords stored in secrets are being echoed back to client as part of error message

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12470]
### What version of Materialize are you using?

v0.26.1-dev (39050cfed)

### How did you install Materialize?

Docker image

### What is the issue?

Running this:

```
create secret pass as 'f1';
CREATE CONNECTOR schema_reg
  FOR CONFLUENT SCHEMA REGISTRY 'http://localhost:8082'
  USERNAME 'materialize'
  PASSWORD pass;
CREATE MATERIALIZED SOURCE connector_source
  FROM KAFKA CONNECTOR schema_reg TOPIC 'foo';

```

Produces this:
```
ERROR:  Failed to create and connect Kafka consumer: Client config error: No such configuration property: "password" password f1
```

The password that one assumed was irreversibly securely stored has been echoed back to the user as part of the error message.

**Comment by nharring-adjacent** [comment]
This error is coming from inside librdkafka unfortunately: https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/pure.rs#L113

**Comment by JLDLaughlin** [comment]
@benesch thinks this may have been fixed. @jkosh44 would you be able to confirm and close?

**Comment by jkosh44** [comment]
The repro query is no longer a valid due to change of syntax. The updated syntax would be:
```
CREATE SECRET pass AS 'f1';
CREATE CONNECTION schema_reg
  FOR CONFLUENT SCHEMA REGISTRY
  URL 'http://localhost:8082',
  USERNAME 'materialize',
  PASSWORD SECRET pass;
CREATE SOURCE connector_source
  FROM KAFKA CONNECTION schema_reg TOPIC 'foo';
```

This gives the following error
`ERROR:  1.3.schema_reg is not a kafka connection`
which is a completely different error but doesn't echo the password.

If you run the following instead, which is closer to the provided query
```
CREATE SECRET pass AS 'f1';
CREATE CONNECTION schema_reg
  FOR CONFLUENT SCHEMA REGISTRY
  URL 'http://localhost:8082',
  USERNAME 'materialize',
  PASSWORD pass;
CREATE SOURCE connector_source
  FROM KAFKA CONNECTION schema_reg TOPIC 'foo';
```
You get the following error: `ERROR:  invalid PASSWORD: must provide a secret value` which also doesn't echo the password.

I don't really know the context of this issue, but it seems to me like it's resolved.

**Comment by JLDLaughlin** [comment]
thank you @jkosh44 !
