### ISSUE TITLE
Reclocking may not be correct in the presence of restarts or concurrency

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#12600]
Reclocking of source offsets, as implemented here: https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/source/reclock.rs#L211 is likely not correct in the presence of concurrent writes to persist:

The general process for reclocking of messages (consisting of `(data, offset, pid <partition id>)` is to collect those messages, then periodically group those messages by `pid`, and use `persist` to _durably_ associate a _timestamp_ with the _max_ of all those offsets; this is intended behavior, many offsets may be "grouped" into one timestamp (cc confirm with @cjubb39 and @petrosagg)

However, if multiple `ReclockOperator`s are running at the same time, they may produce non-definite sources, as the _grouping_ of messages is inconsistent; for example:

The first operator receives `[(d1, 1, p0)]`, uses persist to record offset `1` as timestamp `10`, and emits `(d1, 10, +1)`.
The second operate receives `[(d1, 1, p0), (d2, 2, p0)]`, uses persist to record offset `2` as timestamp `11`, and emit `(d1, 11, +1)` and `(d2, 11, +1)`

Currently, we do not ever run `ReclockOperator`s concurrently, but in the presence of regular restarts, we could (and as I understand it, after https://github.com/MaterializeInc/materialize/pull/12216 merges, will) be re-reading upstream sources from their beginning offset, which can cause the exact same race as described above: The before and after instances may produce different streams. Its unclear to me what happens when we try to persist the data though!

**Comment by cjubb39** [comment]
Ahh good pickup.  The issue here is that we can assign an incorrect binding to a given offset.  The _binding shard itself_ will still be correct but there's not currently a way for the `timestamp_offsets` function to indicate that it may be correct to assign different timestamps to different offsets in the range `last_call_max_observed_offsets` -> `current_call_max_observed_offsets`

Why I believe the persist shard itself to have correct data:
- In the situation you describe, if op1 is able to durably persist offset `1` at ts `10`, then op2 _must_ read in that binding before successfully committing offset `2`.  This is ensured by:
  - `compare_and_append` will fail if the `expected_upper` is not correct.  If op1 succeeded committing offset `1` at `10`, the `expected_upper` is now `10`.
  - After getting an error from `compare_and_append`, op2 will read from the persist shard until it's read through ts `10`.
  - Since it now has a persisted binding for offset `1`, it will try to commit `(partition_id, 11, +1)`, indicating that _offset 2 only_ should be assigned ts `11`. [The diff is computed by `observed_max_offsets[partition_id] (= 11) - 10`]
- Say the `compare_and_append` with this new binding succeeds (if it fails, then some other opN is doing the same thing): now it will read up through ts `11` and happily return `partition_id -> (11, +2)` at which point, source2 will incorrectly assign ts `11` to both offsets 1 and 2.

The issue here is that we're incorrectly interpreting the reclocking persist shard.  It will likely be convenient to fix this in coordination with #12557

**Comment by guswynn** [comment]
@cjubb39 I agree that we never persist the wrong thing, but we can forward the wrong thing to compute!

I think you make a good point about https://github.com/MaterializeInc/materialize/issues/12557: we may need to change the api of `timestamp_offsets` in similar ways to fix both issues! Lets talk about details in the hangout tomorrow!
