### ISSUE TITLE
computed: CPU and memory consumption continue after a supposed cancellation

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12759]
### What version of Materialize are you using?

v0.26.1-dev (4d55c67a3)

### How did you install Materialize?

Built from source

### What is the issue?

CPU usage and memory growth continue in `computed` even after a cancellation has supposedly occurred:

To reproduce:

```
drop table if exists t1;
create table t1 (f1 DOUBLE);
CREATE DEFAULT INDEX ON t1;
SET statement_timeout = "1 s";
insert into t1 SELECT generate_series FROM generate_series(1,100000000);
```
This screenshot was taken **after** the timeout above occured and the client was notified that the operation has timed out.

![Screenshot from 2022-05-30 11-20-07](https://user-images.githubusercontent.com/1279722/170949773-54431031-9fad-4bb8-9a4b-87fbe61e259b.png)

Eventually the memory consumption goes down and the CPU subsides.

**Comment by philip-stoev** [comment]
I think this is another instance of https://github.com/MaterializeInc/materialize/issues/8853 , except that there was no loss of interactivity .

**Comment by teskje** [comment]
I also think this is the same as #8853. The loss of interactivity seen in #8853 was probably due to the old binary architecture. With the Platform, an unyielding dataflow operator in a replica will not block environmentd, so there is no loss of interactivity anymore.

@philip-stoev Should we close as duplicate?
