### ISSUE TITLE
OOM when planning/explaining large join

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#12935]
### What version of Materialize are you using?

Platform staging release 72f77e534121c561c0a1c6645d671ed71b9f52e3

### How did you install Materialize?

Materialize Cloud

### What is the issue?

This causes an OOM in `coordd` :

```
CREATE VIEW billion AS SELECT * FROM generate_series(0, 999) AS x, generate_series(0, 999) AS y, generate_series(0, 999) AS z;
EXPLAIN PLAN FOR SELECT count(*) FROM billion;
```

---

See also: [Slack discussion](https://materializeinc.slack.com/archives/CM7ATT65S/p1654543837829169)

**Comment by umanwizard** [comment]
The problem is here: https://github.com/MaterializeInc/materialize/blob/da4de73bd/src/transform/src/reduction.rs#L460-L462

**Comment by umanwizard** [comment]
Fix incoming

**Comment by wangandi** [comment]
A more detailed explanation of what happened here:

The plan starts off looking roughly like this: 
```
%0 = 
| Constant (0) ... (999)

%1 =
| Constant (0) ... (999)

%2 =
| Constant (0) ... (999)

%3 =
| Join %0 %1 %2
| Reduce group=()
| | agg count(true)

<irrelevant stuff>
```

At this stage the join does not get constant-folded because of the limit that `FoldConstants` will evaluate at most 10k rows.

However, after projection pushdown, the plan looks like this:

```
%0 = 
| Constant (() x 1000)

%1 =
| Constant (() x 1000)

%2 =
| Constant (() x 1000)

%3 =
| Join %0 %1 %2
| Reduce group=()
| | agg count(true)

<irrelevant stuff>
```

It turns out that our code that folds a join of constants is smart. It realizes that the join only produces one distinct row, and you can calculate the number of copies of said row by multiplying the counts from each input. So it folds the join by concatenating the three `()` and taking 1000 to the third power. From the perspective of `FoldConstants`, it only evaluated one row. 
https://github.com/MaterializeInc/materialize/blob/cc053d0ee2c31c5095669f7a35c472a1d171956c/src/transform/src/reduction.rs#L323-L329

After folding the join, the plan now looks like:

```
%0 = 
| Constant (() x 1000000000)
| Reduce group=()
| | agg count(true)

<irrelevant stuff>
```

It turns out that our code that folds a reduction over a constant is significantly less smart. When it sees that a row is supposed to have multiple copies, it makes that many copies of the column that will be aggregated on and sticks it into a vector.
https://github.com/MaterializeInc/materialize/blob/cc053d0ee2c31c5095669f7a35c472a1d171956c/src/transform/src/reduction.rs#L483-L485
Thus, the OOM is caused by the sudden creation of 1 billion copies of `Datum::True` at once.

While @umanwizard has fixed the issue, we may want to looking into making folding a reduction over a constant smarter. We should be able to calculate the count of `Constant (() x 1000000000)` by looking at the row count as opposed to creating a billion-length vector. If we are calculating the min/max of a constant, we should be able to ignore the multiplicity of the rows.

**Comment by umanwizard** [comment]
I think we should change the system so that aggregation functions take iterators of `(Row, diff)` pairs rather than `Row`s. This would allow every function to be rewritten to take diffs into account.
