### ISSUE TITLE
Poor query latency in Materialize Cloud

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12944]
Something periodically goes very wrong in the coordinator in the new Materialize Cloud, resulting in massive latency spikes for queries that don't involve either the catalog or the dataflow layer:

```
materialize=> select 1;
 ?column? 
----------
        1
(1 row)

Time: 19.222 ms
materialize=> select 1;
 ?column? 
----------
        1
(1 row)

Time: 21.871 ms
materialize=> select 1;
 ?column? 
----------
        1
(1 row)

Time: 739.938 ms
materialize=> 
```

The latency is even worse when tables are involved:

```
materialize=> create table t (a int);
insert into t values (1);CREATE TABLE
Time: 4535.090 ms (00:04.535)
materialize=> insert into t values (1);
INSERT 0 1
Time: 442.190 ms
materialize=> select * from t;
 a 
---
 1
(1 row)

Time: 2994.823 ms (00:02.995)
materialize=> 
```

These numbers are bad enough that I suspect this is a misconfiguration that will be easy to fix, rather than a fundamental design issue.

**Comment by benesch** [comment]
cc @jkosh44 @frankmcsherry @umanwizard @guswynn

**Comment by umanwizard** [comment]
cc @antiguru -- maybe this is the cause of the big slowdown in table queries you were seeing earlier.

**Comment by aljoscha** [comment]
With https://github.com/MaterializeInc/materialize/pull/12997, the situation has improved by _a lot_. At least in my testing query times are down to about 160ms.

As a band aid, we could set `--logical-compaction-window=off` to further reduce this by quite a bit. The reason is that this disables half of the persist calls that we have to periodically do for each table.

**Comment by benesch** [comment]
These issues have long been resolved.
