### ISSUE TITLE
Revive table data after restart

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#13007]
### Feature request

In Platform, tables are supported via the persistence layer.  After a restart, the table definition exists, but the data is missing.  This issue is about reviving the table data after a restart.

Relevant discussion from slack:

> Does storage even need to provide a truncate API? Just make adapter read out all the existing data, negate it, and stuff it in alongside all the new updates. (edited) 

## Test Plan

- [ ]  Revive and re-enable enable the table-persistence workflow in `test/persistence`
- [ ]  Re-enable table-based tests in Zippy

**Comment by benesch** [comment]
@petrosagg very nearly accomplished this as part of #12840, but backed out the change because persisting data in system tables causes _incorrect_ behavior: https://github.com/MaterializeInc/materialize/pull/12840/files#diff-8cb017eb837d9b1fb8253f9b0d0ddc478858a91a8579a163a8bb11a00577f85eR396-R400

So the engineering work here is to delete that conditional. That will make all tables persistent, user _and_ system.

Instead adapter will need to empty out all existing system tables before bootstrapping  by synchronously read in all the existing data, negate it, and writing it back to persist. Ideally we'd do this in the `bootstrap` method in the coordinator, at the same timestamp as the production of the new data, and so the diffs just compact away. 

The test plan will be to add a new workflow to `test/restart` that verifies that table data survives a restart. @philip-stoev may have additional advice here.

**Comment by jkosh44** [comment]
> Instead adapter will need to empty out all existing system tables before bootstrapping by synchronously read in all the existing data, negate it, and writing it back to persist. Ideally we'd do this in the bootstrap method in the coordinator, at the same timestamp as the production of the new data, and so the diffs just compact away.

In order for this to work properly wouldn't we need some form of STORAGE command reconciliation OR just not send any create source/table commands during bootstrapping?

**Comment by petrosagg** [comment]
@jkosh44 I don't think you need command reconciliation because when you send a CreateSources command STORAGE doesn't guarantee that the storage collection will be empty. In the case of tables it might have some data in it. The idea is that ADAPTER could interogate STORAGE for the current upper of the tables it needs to be empty, read out all the data, and then call `append` with a batch that retracts all previously added data. (With care of consolidating them in memory first to avoid an exponentially increasing the size of the collection).

**Comment by jkosh44** [comment]
@petrosagg So the ADAPTER can send a CreateSources command to STORAGE, and if that source already exists then STORAGE is smart enough not to create a new one?

**Comment by petrosagg** [comment]
exactly. Also in the future STORAGE will verify that any duplicate CreateSource commands for the same global id agree on their descriptions and only then return success. If you attempt to rebind a GlobalId of a storage collection to something other than the first command specified it will produce an error.
