### ISSUE TITLE
SHOW SOURCES gets slow over time

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#13335]
### What version of Materialize are you using?

main

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Using a mz platform region, I have noticed the SHOW SOURCES command gets slower over time. After about two days, with sources installed and ingesting into persist, it takes > 5 seconds to respond. It does seem reproducable, though takes time :( 

### Relevant log output

```source
none
```

**Comment by sjwiesman** [comment]
@JLDLaughlin I'm guessing this is surfaces, but I'm not really sure.

**Comment by benesch** [comment]
Ah, yes, this is expected—but obviously not desirable. We're constantly accumulating state in the storage layer right now (nothing happened at 5pm, nothing happened at 6pm, nothing happened at 7pm, ...), and never compacting that down.The epic to follow is https://github.com/MaterializeInc/materialize/issues/11491. I'll link this issue there, so that we remember to retest once compaction lands.

**Comment by sjwiesman** [comment]
I will. I’ll leave something running over the weekend and give an update on Monday.

**Comment by aljoscha** [comment]
@sjwiesman Any update? :sweat_smile:

**Comment by sjwiesman** [comment]
Whoops sorry. I haven’t run into any issues in weeks. This is safe to close
