### ISSUE TITLE
recorded views: duplicate data in view after restart

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13452]
### What version of Materialize are you using?

dd6b23bbd8b0e2ae7cc4ebe5985c07dfe6f06142

### How did you install Materialize?

Docker image

### What is the issue?

Unfortunately if all Mz components are restarted together, a recorded view will show data that has been deleted as well as duplicate data.

To reproduce, clone `https://github.com/philip-stoev/materialize/`, branch `checks-recorded-views` and run:

```
./mzcompose down -v ; ./mzcompose run default --check RecordedViews --scenario=RestartEntireMz
```

The testdrive will block waiting for the materialized view to begin returning the correct results, but this never happens.

Expected result is:

```
materialize=> SELECT LEFT(f1, 3), COUNT(*) FROM recorded_views_table GROUP BY LEFT(f1, 3);
 left | count 
------+-------
 T1B  | 10000
 T2B  | 10000
 T3B  | 10000
(3 rows)
```

```
materialize=> SELECT * FROM recorded_view1
materialize-> ;
 left | count 
------+-------
 T1B  | 10000
 T1B  | 10000
 T1B  | 10000
 T2A  | 10000
 T2B  | 10000
 T2B  | 10000
 T2B  | 10000
 T3B  | 10000
 T3B  | 10000
```

Note that there are multiple things wrong with this output:
- the `T2A` rows are present at the end of the test even though they were deleted earlier
- The rest of the rows are triplicated, which indicates that a new copy arrived in the recorded view every time Mz was restarted during the test.
- the result is also incorrect in the sense that the result of the recorded view should have been grouped by the first column, but there are multiple instances of each column value, the grouping having been defeated somehow.

The issue is not repeatable if:
- Mz is not restarted
- if computed only is restarted
- if normal materialized views are used instead of recorded views

The queries involved are in `misc/python/materialize/checks/recorded_views.py` if you would like to run them manually.

**Comment by teskje** [comment]
It looks like merging https://github.com/MaterializeInc/materialize/pull/13458 has fixed the bug. I cannot reproduce it on main, neither with the minimal example nor with the mzcompose test case. @philip-stoev can you confirm it's fixed?

**Comment by teskje** [comment]
To elaborate on what the issue was:

An invariant required by the sink part of a recorded view is that the sink holds back its dataflow inputs' `since`s, so they are alway less than the sink's `upper`. In the minimal example that means the table's `since` must always be less than the sink's `upper`. Then, on a restart of environmentd, the sink dataflow's `as_of` is picked to be the largest of all the dataflow inputs' `since`s. So because of the above invariant, the dataflow's `as_of` is also less than the sink's `upper`. This means that the initial updates arriving at the sink, which represent the snapshot of all the dataflow's inputs at time `as_of`, is sinked at a time before the sink's (and therefore the storage collection's) `upper`, so persist simply ignores  these updates. This is how we avoid duplicates in the face of an environmentd restart.

What went wrong here is that during bootstrapping adapter would advance the `since`s of tables (and possibly also sources) to the local write timestamp, before the bootstrapping process was able to create any potential dependants that would want to set read holds to prevent such an advancement. In the minimal example, what happened was:
1. Adapter bootstraps table `t`. As part of that, it advances `t`'s `since` to the local write timestamp, which is beyond the recorded view's `upper`.
2. Adapter bootstraps the recorded view. The sink dataflow's `as_of` is selected based on the `since` of `t`.
3. The recorded view starts sinking updates at a time beyond the persist shard's `upper`, so the whole snapshot of `t` is written again and we end up with duplicates.

#13458 fixes this by deferring all frontier advancements that adapter wants to make during bootstrapping until after all catalog objects have been created and have been given the chance to install read holds.

**Comment by philip-stoev** [comment]
@teskje yes, this appears fixed now. I will push the test to "main" .
