### ISSUE TITLE
Integrate `EXPLAIN TIMESTAMP` to the new code path

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#13476]
- Extend `parse_explain_new` to handle `TIMESTAMP` as a new (pseudo-)stage.
- Extend `plan_explain_new` to produce a new `ExplainPlan::Timestamp` variant if for `EXPLAIN TIMESTAMP`.
- Factor out the code that handles `EXPLAIN TIMESTAMP` in `sequence_explain_old` and call it from `sequence_explain` for the new `ExplainPlan` variant.

**Comment by aalexandrov** [comment]
Picking this up, I will open a PR for this tomorrow and ping @mjibson for review.

**Comment by mjibson** [comment]
An idea I had with andi: make `EXPLAIN TIMESTAMP` its own parsed statement type that is then handled completely separately from all of the other explain stuff. Not sure if this is a good idea or not, but because it's so different it seems easier to not attempt to wedge it in to a structure where it doesn't fit.

**Comment by aalexandrov** [comment]
> Not sure if this is a good idea or not, but because it's so different it seems easier to not attempt to wedge it in to a structure where it doesn't fit.

In the long run we might be able to reconcile it, but as I am expecting more changes in the "EXPLAIN $OPTIMIZER_STAGE " path of `sequence_explain` as part of #13139, so a split seems better for now.

**Comment by aalexandrov** [comment]
> My proposal is to do this at a higher level, so it doesn't show up in ExplainStage at all.

OK, so you suggest having giving this new structure it's own `parse_` and `plan_` functions?

**Comment by aalexandrov** [comment]
> its own parsed statement type

OK, I see, then instead of:

```rust
Token::Keyword(EXPLAIN) => Ok(self.parse_explain()?),
```

you will peek at the next word and go to `parse_explain_timestamp` if it is `TIMESTAMP`?

**Comment by mjibson** [comment]
> you will peek at the next word

Yes, I suppose that's what would happen. I am not convinced this is a good idea because it allows the syntax to diverge which could be confusing to users (although, we currently don't even document this option on purpose, because it's mostly only useful for internal debugging). I'm in favor of doing whatever is easiest for you. If that's integrating with the new syntax, great. If it is making it separate so the new code doesn't need to care about it, great also.
