### ISSUE TITLE
Replicas without an AZ should have the least-full one picked

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#13498]
### Feature request

When creating a replica without an explicit availability zone, it should default to picking the least-full AZ automatically. This needs to be coordinated with the cloud team to determine the information when spawning a new compute replica.

**Comment by teskje** [comment]
I'm trying to figure out if this issue is still relevant. A lot has changed with the way how we select AZs for replicas. I believe this describes the current approach: https://github.com/MaterializeInc/materialize/pull/21090/files#diff-d5c7b469cb99b14f9f32840eb795d0fed9424cb637c8bf3b325de6a9a0650b5aR108-R122

@antiguru I'm not quite sure what "least full" means in this context. If it means that no two replicas should be spawned in the same AZ (assuming enough AZs) then I think this issue can be closed.

**Comment by antiguru** [comment]
Irrelevant since #20815.
