### ISSUE TITLE
recorded views over upsert sources: "Invalid data in source, saw retractions (1) for row that does not exist" after restarts

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13496]
### What version of Materialize are you using?

v0.26.1-dev (889df4949)

### How did you install Materialize?

Docker image

### What is the issue?

A test that creates recorded views over Kafka upsert sources and performs restarts of the complete Mz instance will eventually reach this situation:

```
materialize=> select * from view8;
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Null, Null, Int64(0), Int64(0)]
```

Curiously, the problem is reproducible even if we only ever ingest 1 message into the kafka topic. There are no upsert updates or deletions.

Note that to my understanding, kafka upsert sources will currently re-ingest the entire topic when starting up rather than starting from where they left off pre-restart.

@petrosagg

**Comment by teskje** [comment]
The "Invalid data in source..." error is produced by the code path that tries to fulfill the SELECT. If you use a TAIL instead, you can see the actual data in the recorded view:

```
materialize=> COPY (TAIL (SELECT * FROM view8)) TO STDOUT;
1657199235000	-1	\N	\N	0	0
1657199235000	1	0	0	1	1
```

Note that the `since` has already been advanced, so it is not visible anymore, which of the two events arrived first.

**Comment by philip-stoev** [comment]
The data produced by TAIL is still invalid though. What is missing is a "+1" for the "\N" data.

**Comment by teskje** [comment]
Yes, definitely! Sorry, I'm just writing down my findings as I discover things :)

**Comment by teskje** [comment]
I've made some progress. I couldn't reproduce the issue outside of zippy, nor was I able to simplify the existing test case significantly, but at least I can add logging to the Materialize code. And thankfully, the bug reproduces in zippy every time :)

I've added logging to the persist_sink in compute. This is what the sink sees (shortened timestamps for readability):

* Shard `upper`: 0
* Sink `upper`: 0
* Update: `([NULL, NULL, 0, 0], 145000, +1)`
    * Note that the update is not yet written, because it is beyond the sink's `upper`
* Sink `upper`: 086001
    * Update is still pending.
* Shard `upper`: 086001
* Materialize is killed 
* Materialize is started
* Shard `upper`: 086001
* Sink `upper`: 0
* Update: `([NULL, NULL, 0, 0], 0, +1)`
    * Note that this update has a different time than in the previous Materialize incarnation!
* Sink `upper`: 086001
    * The update is now written to persist. _But_ because the update's time is less than the current shard `upper`, persist assumes that it has already seen the update, so it is ignored!
* Sink `upper`: 152000
* Update: `([NULL, NULL, 0, 0], 152000, -1)`
* Update: `([0, 0, 1, 1], 152000, +1)`
* Shard `upper`: 152000
* Sink `upper`: 152001
    * Both above updates are written to persist. Because they are at times beyond the current shard `upper`, they are actually written.
* Shard `upper`: 1520001

So this is how we end up with a stray retraction for `([NULL, NULL, 0, 0], 152000, -1)` in the persist shard. The issue is that the collection we sink seems to be non-definite (in that the initial update occurs at varying times). `persist_sink` only works correctly for definite collections.

The question I cannot answer yet is where the non-definiteness comes from. Is this related to how our Kafka sources work? @philip-stoev indicated above that UPSERT sources are not persisted, which would point in that direction.

**Comment by teskje** [comment]
Yes! Those initial updates of `[NULL, NULL, 0, 0]` occur at the `as_of` of the sink dataflow. So the issue seems to be that for some reason we pick an `as_of` of 0 the second time around. I'm going to look at why that happens next. I don't know how persist_source is involved yet, but if there are no bugs, the `as_of` should be picked based on the `since`s of the dataflow inputs/persist_sources.

**Comment by teskje** [comment]
Summarizing my current knowledge here:

The core issue is that after an environmentd restart it is possible that adapter selects an `as_of` for the recording sink dataflow that is before the `as_of` selected when that dataflow was first created. This allows the following scenario to happen:

1. Adapter receives CREATE MATERIALIZED VIEW (formerly CREATE RECORDED VIEW).
2. Adapter builds the sink dataflow. It picks the upper bound of all input `since`s as the dataflows `as_of` (`as_of1`).
3. Adapter sends the dataflow description to compute, compute starts running the dataflow.
5. The dataflow sees a progress update at `t1`, which is before `as_of1` (`t1 < as_of1`). [Explanation of why this can happen.](https://materializeinc.slack.com/archives/CMNT2QSBZ/p1658839622865099)
6. The progress update causes an `append` call on the persist shard that is the sink target. This advances the shard's upper to `t1`.
7. Materialize restarts. Note that at this point no data has been written to the persist shard, but its upper was advanced to `t1`.
8. Adapter rebuilds the sink dataflow during its bootstrap process. For the `as_of` (`as_of2`) it again picks the upper bound of all input `since`s. There is no guarantee that `as_of2` is beyond `as_of1`. It is possible that `as_of2 < t1 < as_of1`. Let's assume this is the case.
9. Adapter sends the dataflow description to compute, compute starts running the dataflow.
10. The dataflow produces the initial snapshot of data at `as_of2`.
11. The data update causes an `append` call on the persist shard that is the sink target. But because the time of the update (`as_of2`) is less than the shard's upper (`t1`), persist assumes that it has already seen this update and ignores it! 
12. The dataflow produces a retraction for some update inside the snapshot that was mistakenly not written. We end up with negative multiplicities in the persist shard.

The implementation assumed that `since`s will only advance, meaning `as_of2 < as_of1` could never happen, but this is not true across Materialize restarts. During restart, the storage controller reads back the `since`s of storage collections from their respective persist shards. If persist held back compaction for any reason, the restored `since`s might be less than what the storage controller reported before the restart. In general, we should never rely on persist compaction to have occurred for correctness. So deriving dataflow `as_of`s from the `since`s of their input collections on restart is a mistake.

One idea we had is to instead derive the sink dataflow `as_of` from the target persist shard's upper during restart: `as_of2 = upper - 1`. https://github.com/MaterializeInc/materialize/pull/13589 is an implementation of this idea. Unfortunately, it doesn't help. The above scenario can still occur, only that we now select `as_of2 = t1 - 1`, which is still less than `t1`, so this doesn't solve anything.

There are at least two plausible solutions to this issue:
- Remember the original sink dataflow `as_of` (`as_of1`) across restarts. Then on restart make sure that `as_of2 >= as_of1`. https://github.com/MaterializeInc/materialize/issues/13222 will allow us to implement this solution.
- Have the `persist_sink` operator read back the contents of its target persist shard to determine if new updates have been already written or not. Then write any updates that are missing. https://github.com/MaterializeInc/materialize/pull/13740 is a draft implementation of this idea.

We'll probably want both compute command durability and self-healing `persist_sink`s, as both make Materialize more robust in general.
