### ISSUE TITLE
adapter: don't forget to garbage collect secrets

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13579]
The [design of the `SecretsController`](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220303_secrets.md#transaction-integration) can result in secrets that fail to clean up if a crash occurs at the wrong time:

> The above integration is designed so that failures result in orphaned secrets in the secrets controller; i.e., secrets that exist in the secrets controller but have no corresponding entry in the catalog. (The inverse would not be permissible: a secret that exists in the catalog must be known to the secrets controller.) The coordinator will periodically attempt to garbage collect orphaned secrets, either at startup or in a background task.

We need to add this loop to clean up any such orphaned secrets.

**Comment by mjibson** [comment]
Because the secrets controller doesn't have a list api, this requires writing down secrets to delete somewhere into the stash, processing them at some point, and then removing from the list once processed. That seems like a useful enough thing that it should be generalized to work on more things than just secrets.

**Comment by benesch** [comment]
Secrets controller should learn a list API, IMO! WALing deletion ops is
nice but doesn’t let us clean up things that have historically leaked.
