### ISSUE TITLE
`CREATE MATERIALIZED VIEW` could support `REFRESH` modifiers

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#13762]
### Feature request

Materialized views have various rules for when they should be refreshed. Ours are by default `REFRESH ON COMMIT`, in Oracle's vocabulary (https://docs.oracle.com/cd/B19306_01/server.102/b14200/img_text/create_mv_refresh.htm). In that same vocabulary, there are interesting options like `ON DEMAND` and `NEVER REFRESH` among others. These both seem valuable and at least one seems not hard to do.

`ON DEMAND` allows the user to manually refresh the view, and roughly corresponds to pausing the ingestion in to a dataflow, while continuing to downgrade input capabilities, and on resumption advance all updates to the resumed time. It seems mechanically not that hard to do, and largely just requires `persist_source` to be able to learn about the goal of ceasing ingestion. We might also need some compaction hooks, or just skip those and train the source to re-ingest from a snapshot (not ideal, but possible).

`NEVER REFRESH` allows the user to indicate that the view should never be refreshed. This is *amazing* from a performance point of view, because it means that we can *seal* the `persist` collection. Sealed collections have very exciting performance properties in DD, which we haven't really investigated at MZ. But, they allow joins for example to execute much more efficiently: when one joins a collection with a sealed collection, the collection does not need to be maintained in an arrangement (once the initial snapshot is past). This can dramatically reduce the memory footprint of e.g. joins of fact tables against Slowly Changing Dimension tables, if these were implemented as `NEVER REFRESH` materialized views.

cc: @ahelium 

**Edit:** EPIC that covers some of this (except for `ON DEMAND`): https://github.com/MaterializeInc/materialize/issues/22878

**Comment by heeringa** [comment]
https://github.com/MaterializeInc/developer-experience/discussions/139

**Comment by rjnn** [comment]
Could one alter a materialized view to change refresh type? The fact that that seems feasible (correct me if I’m wrong!) is also exciting.

**Comment by ggevay** [comment]
We discussed this in a Compute meeting today, and had some thoughts worth recording here.

### Workaround: keep it at 0 replicas most of the time

As @jan pointed out, there is a workaround that might somewhat work even today without any changes to the system: Just create a dedicated cluster for your mat view, and keep it at 0 replicas most of the time, and set it to 1 replica when you want a refresh. You can monitor `mz_frontiers` to know when it's done refreshing so that you can set it back to 0 replicas.

One caveat is that the above setup will hold back Persist compactions while there are 0 replicas. (After the refresh completes, Persist can compact stuff older than the refresh.) We are not really sure how bad of a problem this is. It probably means you don't want to wait too much between two refreshes. Note that if we properly implement `REFRESH ON DEMAND` instead of relying on this workaround, then we wouldn't have this problem.

Another caveat of the above setup is that the system wouldn't allow you to join this mat view with something else that is updated normally, because the timestamps wouldn't line up (even in `SERIALIZABLE` mode). This might actually be ok for one big customer whose needs prompted this whole discussion now, but we still need to verify this with them. If we properly implement `REFRESH ON DEMAND` instead of relying on this workaround, then I'm still not sure how exactly this limitation would be solved.

### Thoughts on `REFRESH ON DEMAND`

In `REFRESH ON DEMAND` mode, we could implement the refreshes by spinning up a dataflow that is somewhat similar to Peek dataflows: it would have to operate on a snapshot, so it could use the monotonic one-shot SELECTs optimizations. (This would be another advantage of implementing this feature properly instead of relying on the above workaround.)

@antiguru pointer out that even with `REFRESH ON DEMAND`, you wouldn't want to keep the cluster replicas around all the time, so either you would have to manually do the same 0-1 replicas dance as in the above workaround, or we'd have to devise some new cluster management mechanism that would spin up cluster replicas automatically for a REFRESH. Maybe `REFRESH ON DEMAND` mat views wouldn't be associated with a cluster at all, but we would just create a whole new cluster for each refresh.

It has been pointed out that a large part of the `REFRESH ON DEMAND` work might be @MaterializeInc/adapter work, but some discovery work is still needed to confirm this.

**Comment by ggevay** [comment]
We are thinking about doing `REFRESH EVERY <period>`, specifically with very low frequencies, e.g., 1 day. For this case, we are planning to launch a (single-time) dataflow at each refresh instead of keeping a dataflow running all the time.

At each refresh
- our read holds on inputs would jump forward to the time of the next refresh minus 1 ms (to not block compaction of our inputs, which would be low-to-medium scary for Persist sources and even worse for indexes, whose memory usage could grow by an arbitrary factor).
- our output mat view's since and upper would span the entire refresh interval (including the point of the refresh only at the start), so that the output mat view can be queried together with other objects that are being refreshed at a normal cadence. In other words, we would signal to the system that the output mat view won't change until the next refresh.

A limitation is that the output mat view won't allow querying while the refresh dataflow is running. This is acceptable for the specific user for whom we are building this (because this will happen outside business hours), but we might want to think about solving this in the long run, because some other user might not want "downtime" even outside of business hours, or might want refreshes more often than the length of a business hours interval. (We could maybe remove this limitation as follows: We start the refresh dataflow not at midnight, but before it, so that it can hydrate before reaching midnight, and it would have only a little work left to do around midnight to just process the data that came in around midnight. Then it wouldn't be a single-time dataflow, because we would need to set the dataflow as_of to be around the time when we start up the dataflow, but would still need to set until to midnight. There is also the question of how do we know how much earlier than midnight we have to start it. For this, we might take the run time of the last refresh dataflow to be indicative of how much time the next one will take.)

One more thing that we might do in the long run is to not just allow big intervals in the refresh period, but seamlessly allow the entire theoretical range of values for the refresh period. If the refresh interval is smaller than re-running a single-time dataflow on the entire input would take, then we could switch to the implementation approach outlined in https://github.com/MaterializeInc/materialize/issues/6745, i.e., having a continuously running dataflow that would tick at a slower than normal frequency.

**Comment by ggevay** [comment]
Note that currently the `REFRESH` options epic (https://github.com/MaterializeInc/materialize/issues/22878) covers most of this issue. The only thing not covered there is `REFRESH ON DEMAND`, where the user can issue a command to refresh the MV at any time.

**Comment by ggevay** [comment]
Closing this, as it has been mostly implemented, see https://github.com/MaterializeInc/materialize/issues/26010.

Changing REFRESH options on an already existing MV is tracked in https://github.com/MaterializeInc/materialize/issues/26572.

`REFRESH ON DEMAND` is also closely related to https://github.com/MaterializeInc/materialize/issues/26572.
