### ISSUE TITLE
cockroach: investigate what happens with connections and DNS

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#13941]
If there are 3 nodes in a cluster, do we cache the DNS resolution of one and always use it? If so, try to make our connections use a new IP each time they reconnect.

**Comment by benesch** [comment]
I looked into this! Cockroach Cloud puts an ELB in front of the cluster. The hostname that we're given resolves to that ELB rather than any particular node in the cluster. So we're totally good here. On failure, all we need to do is retry connecting to the hostname that we already have and we'll get routed to a healthy node.
