### ISSUE TITLE
cannot append updates: InvalidBounds { lower: Antichain { elements: [1659591912362] }, upper: Antichain { elements: [1659591912314] } }

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14062]
### What version of Materialize are you using?

environmentd v0.26.1-dev (d23b1a035)

### How did you install Materialize?

Docker image

### What is the issue?

Seen in CI on a test that has historically been quite stable. The test kills and restarts `storaged`:

```
platform-checks-materialized-1    | thread 'tokio:work-1' panicked at 'cannot append updates: InvalidBounds { lower: Antichain { elements: [1659591912362] }, upper: Antichain { elements: [1659591912314] } }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06136b3f9e749f899-1/materialize/tests/src/storage/src/controller.rs:1483:42
```
 
https://buildkite.com/materialize/tests/builds/38938#0182675f-f59e-4cb2-a451-aa98cc6046f4

**Comment by aljoscha** [comment]
I'm medium sure that this is caused by this change: https://github.com/MaterializeInc/materialize/pull/14003. cc @frankmcsherry & @jkosh44 

I'm more sure that this is ultimately caused by a footgun in the persist `WriteHandle` API: The code in question [1] uses `fetch_recent_upper()`, assuming that this will update the internal `upper` field of the `WriteHandle`. Then, the code uses `upper()` to see what state we are in. This, however, will be using an outdated upper.

@danhhz The most obvious fix would be to change `fetch_recent_upper()` to also update the internal `upper` field of the handle. WDYT?

[1]
https://github.com/MaterializeInc/materialize/blob/dc150cf6026c8167f065c9365bceca4fdbb2a0f6/src/storage/src/controller.rs#L1450

**Comment by frankmcsherry** [comment]
O I C

**Comment by frankmcsherry** [comment]
This is easy to fix in the code too, if there is some reason not to update `WriteHandle`. But I agree that fixing the footgun is a great thing to do.

**Comment by danhhz** [comment]
wow no kidding, it sure doesn't. fetch_recent_upper is meant to update self.upper, too

**Comment by danhhz** [comment]
fix is up in https://github.com/MaterializeInc/materialize/pull/14075

looks like we even had a unit test for the bad behavior 😬. this all seems to have gotten missed when we pulled `append` out as a sugar method on top of `compare_and_append` (`append` was originally also a state command)

**Comment by antiguru** [comment]
This problem still happens: https://buildkite.com/materialize/tests/builds/39333#01828cce-2050-4190-9b00-72fbd91e72d0

**Comment by aljoscha** [comment]
This one is not happening anymore, it seems?

**Comment by aljoscha** [comment]
@philip-stoev is this one still happening? last asked almost a month ago so seems to be fixed? 😅

**Comment by philip-stoev** [comment]
I have not seen it recently.
