### ISSUE TITLE
MZ_OBJECTS doesn't contain all objects

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#14237]
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Built from source

### What is the issue?

`mz_objects` is a catalog view that is supposed to be a single place to look at all the created objects in Materialize. Specifically it's supposed to contain all objects that are identified by a `GlobalId`. However, we have recently added some new object types without adding them to this view.

`mz_objects` currently contains:
- tables
- sources
- views
- materialized views
- sinks
- indexes

Which means it doesn't contain the following items that use a `GlobalId`
- Types (probably on purpose)
- Functions (probably on purpose)
- Secrets
- Connections
- Storage Collections

**Comment by jkosh44** [comment]
I say "probably on purpose" above for types and functions for the following reasons
- They have existed for a long time and have never been included in the view (the docs leave them out too https://materialize.com/docs/sql/system-catalog/#mz_objects).
- They would probably clutter the view.

Though I don't know for sure.

**Comment by benesch** [comment]
I _think_ it's meant to contain everything, but I am also not sure. For a brief second, I thought "maybe it's just supposed to contain relations", but then I looked and we have a _separate_ table called `mz_relations`. That table is likely missing materialized views—at least it's missing them in the docs—and that should be corrected too!

**Comment by JLDLaughlin** [comment]
cc @ggnall + @chaas

**Comment by chaas** [comment]
@JLDLaughlin I see this marked as "good first issue" - let me know if you think I should work on it, depending on priority.
Also I tested out `mz_relations` and it does include materialized views, so it looks like just the docs need to be updated.

**Comment by jkosh44** [comment]
FYI, the view definition can be found here: https://github.com/MaterializeInc/materialize/blob/49e19abc4d70e481bedf8350040a4f962a9d56e8/src/adapter/src/catalog/builtin.rs#L1262-L1273

**Comment by chaas** [comment]
Update: I will include everything identified by `GlobalId` and is namespaces to a schema. This includes:
* Tables
* Sources
* Views
* Materialized views
* Sinks
* Indices
* Connections (to add)
* Secrets (to add)
* Types (to add)
* Functions (to add)

`mz_objects` is used to generate `pg_class`. In looking at how to handle the downstream effects on `pg_class`, the [postgres docs](https://www.postgresql.org/docs/current/catalog-pg-class.html) define it as "tables and most everything else that has columns or is otherwise similar to a table. This includes indexes, sequences, views, materialized views, composite types."
Aka not everything in `mz_objects` fits. It seems more appropriate to include the types in `mz_relations` (tables, sources, views, materialized views) plus `mz_indexes`. That _excludes_ sinks, connections, types, functions, or secrets. 

`mz_objects` is also used in the dbt adapter for the macro `list_relations_without_caching`. Given the description, I'll filter to only include relations here too. Since it's currently including indices and sinks, should I continue including those as well?

**Comment by morsapaes** [comment]
> mz_objects is also used in the dbt adapter for the macro list_relations_without_caching. Given the description, I'll filter to only include relations here too. Since it's currently including indices and sinks, should I continue including those as well?

It should preserve all objects currently in `mz_objects`, _including_ indexes and sinks.

**Comment by benesch** [comment]
I think both `pg_class` and `list_relations_without_caching` should be switched to use `mz_relations` instead of `mz_objects`?

**Comment by morsapaes** [comment]
We could union `mz_relations`, `mz_sinks` and `mz_indexes` to achieve the same result in the adapter. We'd still need to pull in `mz_objects` to grab the schema (and database) an index is associated with it, but that's reasonable.

**Comment by benesch** [comment]
> We could union `mz_relations`, `mz_sinks` and `mz_indexes` to achieve the same result in the adapter. We'd still need to pull in `mz_objects` to grab the schema (and database) an index is associated with it, but that's reasonable.

Wait, I'm confused. The `list_relations_without_caching` macro is looking for sinks and indexes? Shouldn't it only be looking for ... relations?

**Comment by ahelium** [comment]
In the dbt-adapter we extend the [Relation](https://docs.getdbt.com/reference/dbt-classes#relation) class to [include](https://github.com/MaterializeInc/materialize/blob/main/misc/dbt-materialize/dbt/adapters/materialize/relation.py#L25) Sources, Sinks, Materialized Views, and Indexes (though we deprecated these in favor of including them on creation of views or materialized views). Since we do that, `list_relations_without_caching` should return those types so we can call drop on them the same way we do the postgres built in materializations. Happy for other approaches, though!
