### ISSUE TITLE
SELECT query expressions can be marked as append-only

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#14351]
### Feature request

Most relation expressions in a SELECT query can be marked as "monotonic" or "append-only", as the snapshot should be non-negative, and .. if we execute things well .. we will issue no retractions. At least, we will not look at the results of the query after retractions. This has the potential to enable a variety of optimizations, not least that `TopK` operators will be able to run much more efficiently.

There are some non-append-only moments, if you have `Negate` operators for example, but .. most operators should probably be able to use their monotonic plan options.

**Comment by aalexandrov** [comment]
I think monotonicity is a function of an `MirRelationExpr` shape and the `monotonic` flags of its sources. Given that, shouldn't we just assume that `storaged` sources are monotonic and let the storage layer ensure this at runtime?

**Comment by aalexandrov** [comment]
> `Reduce` will have its output be append-only also, even though it wouldn't normally be such on an append-only input.

I'm not sure I follow. I thought that `Reduce` in general might retract an aggregated value `d` at time `t+1` (which represents the result up to time `t`) in order to replace it with `d'` at time `t+1` (which represents the changed result). I can see that after we see all updates for `t+1` the count for an arbitrary `d` should never be negative, and this is true for most of the `MirRelationExpr` variants.

Maybe I'm mixing up the following two properties:
1. At any time `t`, the sum of the diffs `r` for each data point `d` is going to be positive.
2. At any time `t`, the diff `r` in all update triples `(t, r, d)` is going to be positive.

I think "the snapshot should be non-negative" refers to (1).

**Comment by frankmcsherry** [comment]
For the specific case of a SELECT query, we are only interested in the snapshot. Although there might be retractions at `t+1`, the only thing `computed` will do with the dataflow is inspect its results at `t` and then allow the dataflow to shut down.

**Comment by aalexandrov** [comment]
OK, got it, so this is something that we can do in order to plan the execution of one-off queries more efficiently.

**Comment by frankmcsherry** [comment]
Yes, sorry perhaps the title should be `SELECT` *command*` rather than `SELECT` *query*. For the SQL command that issues a SELECT, we should be able to end up using the monotonic implementations of those operators.

**Comment by aalexandrov** [comment]
So when we install a dataflow for a `SELECT` command, we wait for the write frontier for all sources to advance to `t` and then compute the dataflow by consuming a snapshot at `t` for each source?

I don't see how this will work otherwise, e.g. if we take a snapshot from the query sources at some time `t' < t` and then consume the updates until we reach `t`.

**Comment by frankmcsherry** [comment]
https://github.com/MaterializeInc/materialize/pull/14361 should provide the ability to load up arrangements with a termination time, essentially the interval `[since, upper)` rather than just `[since, ..]`. This should allow imported arrangements at least to terminate early once `upper` has been reached. We would still need to do the same sort of thing with `persist_source` (@sploiselle and @aljoscha are in charge of that code, and no reason to barge in there yet).

**Comment by ggevay** [comment]
https://github.com/MaterializeInc/materialize/issues/17358 is similar

**Comment by vmarcos** [comment]
Fixed by #18546. This PR provides the feature behind the feature flag `enable_monotonic_oneshot_selects`. Some follow-up work refining when to perform consolidation in single-time plans is the subject of https://github.com/MaterializeInc/materialize/issues/18732. I believe that when we address #18732, the we will also be able to close #17358.
