### ISSUE TITLE
Tables are inconsistent about using _id suffix

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14398]
## What's wrong?
We should be consistent in using the `_id` suffix for all columns that represent an identifier.

## What should we do?
Identify all the instances and change the column names.
Some examples:
* Every table with a `worker` column (this will include tables defined in `builtin.rs` as well as from the Compute Logs (in `https://github.com/MaterializeInc/materialize/blob/main/src/compute-client/src/logging.rs)
* Perhaps other Compute Logs columns such as `operator` and `channel`?

Please share if you know of any other examples not mentioned above.

**Comment by chaas** [comment]
Some others I'm planning to change
* `operator` -> `operator_id` (in eg `mz_arrangement_batches_internal`)
* `source_node` -> `source_node_id` and `target_node` -> `target_node_id` (in eg `mz_dataflow_channels`)?
    * Should these actually be `source_operator_id`, since they're ids of operators? Perhaps @vmarcos or @teskje you'd know?
* `channel` -> `channel_id` in `mz_message_counts`  
* `source` -> `source_id` in `mz_materialization_dependencies`

cc @benesch

**Comment by vmarcos** [comment]
> 
> * `source_node` -> `source_node_id` and `target_node` -> `target_node_id` (in eg `mz_dataflow_channels`)?
>   
>   * Should these actually be `source_operator_id`, since they're ids of operators? Perhaps @vmarcos or @teskje you'd know?

I just learned this one recently, but as far as I understand, the meaning of the `source_node` and `target_node` columns is as follows: These two columns list the last element in the address list for the operator coming from `mz_dataflow_addresses`. The prefix of the address list, on the other hand, is associated in `mz_dataflow_addresses` itself to the id of a channel that can be looked up in `mz_message_counts`. 

An example of this understanding is given at https://github.com/MaterializeInc/materialize/issues/14443#issuecomment-1230409415. In our troubleshooting doc, we also explain a bit the concept of an address list as composed of dataflow (first element), followed by region of the dataflow (second element), followed by subsequent sub*-regions: https://materialize.com/docs/ops/troubleshooting/#i-found-a-problematic-operator-where-did-it-come-from. 

The above complicates naming the `id` column of `mz_dataflow_addresses`, because it is at times an operator id and at times a channel id.

> * `source` -> `source_id` in `mz_materialization_dependencies`
> 

This is also a bit of a confusing name for a column in that a source here is not understood in the same way as in `mz_sources`. That is, a source for a collection in `mz_materialization_dependencies` is a broader concept, and can be another collection. So the id can correspond to, e.g., an index id, a materialized view id, a source id, or a table id.

**Comment by chaas** [comment]
Interesting, in the [developer docs](https://materialize.com/docs/sql/system-catalog/#mz_dataflow_channels), the definition of source_node is "The ID of the source operator. Corresponds to mz_dataflow_operators.id."

And the definition of source in `mz_materialization_dependencies` in those docs is "The ID of the source. Corresponds to mz_sources.id."

So are these docs no longer correct? I guess in that case to avoid confusion we could leave the names as is, but update the documentation to communicate the different meaning.

**Comment by teskje** [comment]
> @teskje Would you know the semantics here?

I don't know for sure. Looking at the code, `source_node` comes directly from this timely logging [ChannelsEvent](https://github.com/TimelyDataflow/timely-dataflow/blob/204b444f8ad4c78f08585c7ffeb5c318b424d0d2/timely/src/logging.rs#L63-L73). In there, `source_node` is `source.0`, so the index of the operator that is the source of the channel the event is about.

There are a couple places where an index of 0 is hardcoded, for example [here](https://github.com/TimelyDataflow/timely-dataflow/blob/204b444f8ad4c78f08585c7ffeb5c318b424d0d2/timely/src/progress/subgraph.rs#L382) and [here](https://github.com/TimelyDataflow/timely-dataflow/blob/204b444f8ad4c78f08585c7ffeb5c318b424d0d2/timely/src/dataflow/operators/enterleave.rs#L103). I'm not sure if it acts as a placeholder there, or if it refers the a special operator (like the first one in the current scope). 

I'm sure @frankmcsherry and @antiguru know more!

**Comment by chaas** [comment]
This is super helpful, thank you! 

> I don't know for sure. Looking at the code, source_node comes directly from this timely logging [ChannelsEvent](https://github.com/TimelyDataflow/timely-dataflow/blob/204b444f8ad4c78f08585c7ffeb5c318b424d0d2/timely/src/logging.rs#L63-L73). In there, source_node is source.0, so the index of the operator that is the source of the channel the event is about.
What is the difference between the id of the operator and the index of the operator? Is it that they are scope-local indexes?
Not really sure than what to call it if that's the case, since it's not an "id"...perhaps we just keep `source_node` and improve documentation.

> For mz_materialization_dependencies, I like your idea of using import_id, but then perhaps we should use export_id instead of dataflow to keep consistency with the concepts in the code? I believe that relates to issue https://github.com/MaterializeInc/materialize/issues/14397 as well. For reference, the struct I am looking at is DataflowDescription in src/compute-client/src/command.rs.
Sounds good! Accomplishing two tickets at once :)

**Comment by frankmcsherry** [comment]
> What is the difference between the id of the operator and the index of the operator? Is it that they are scope-local indexes?

Each operator does have a scope-local index and a timely global identifier. I *hope* that is how they are being used, but if something seems off we should double check! There is (or has been) a relation containing `addresses` that relates these.

**Comment by benesch** [comment]
I'd advocate for `from_node` or `from_index` instead of `source_node` and `to_node` or `to_index` instead of `target_node`, just to avoid using the overloaded term "source". But it's a week preference.
