### ISSUE TITLE
Timeout using `kafka_time_offset` in a Redpanda source.

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#14456]
### What version of Materialize are you using?

v0.26.0

### How did you install Materialize?

Docker image

### What is the issue?

A [community user](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1661528126789009) reports getting a timeout using a ` kafka_time_offset` in a Redpanda topic with 15 partitions.

As @guswynn reports:

Materialize uses a _fixed 10 second timeout on metadata lookup when doing `kafka_time_offset`_:

https://github.com/MaterializeInc/materialize/blob/08f85cbe45972eb894ceb62f58806dc4ea7faa5a/src/kafka-util/src/client.rs#L71

https://github.com/MaterializeInc/materialize/blob/08faeec0f443c349fd3b1d1e1df449cc42d6c626/src/sql/src/kafka_util.rs#L339

While 10 seconds sounds enough to request a topic's metadata it could be not enough for some cases.

### Relevant log output

```source
Meta data fetch error: OperationTimedOut (Local: Timed out): OperationTimedOut (Local: Timed out)
```

**Comment by joacoc** [comment]
@aljoscha agree!

**Comment by uce** [comment]
@aljoscha 

> From his most recent messages it sounds like there was just no data for the requested time. In that case, increasing the timeout would just mean they have to wait longer for this to fail?

Gus mentioned in Slack that we use timeouts inconsistently. 10s sounds like a sane default, but we might want to have an issue to consolidate configuration of these options in the future.

> From his most recent messages it sounds like there was just no data for the requested time. In that case, increasing the timeout would just mean they have to wait longer for this to fail?

The timeout seems to be high enough to actually fetch the metadata. According to [the docstring](https://github.com/MaterializeInc/materialize/blob/c7d8dfb/src/sql/src/kafka_util.rs#L294-L297) and [the code](https://github.com/MaterializeInc/materialize/blob/c7d8dfb/src/sql/src/kafka_util.rs#L353-L364) we should be looking up the end offset/high watermark in case that no data is available and I'm wondering whether there's something fishy going on there (since in all other cases it seems to be working as expected).

**Comment by aljoscha** [comment]
Summoning @bkirwi, who knows more about the workings of Kafka itself and might be able to help.

**Comment by bkirwi** [comment]
Unfortunately not a Redpanda expert, which it sounds like is the relevant tech here. :/

At the client and wire-protocol level this call is cheap. In Kafka IIRC it's normally a binary-search on an index, which is fast. I have a vague memory of some cases where it would be slow when messages weren't being assigned timestamps (falling back to a scan of the data) but anyways that's not relevant to Redpanda.

From the docs, this returns:
> a mapping from partition to the timestamp and offset of the first message with timestamp greater than or equal to the target timestamp. null will be returned for the partition if there is no such message.

So it's never supposed to _wait_ for data.

I suspect the most likely issue is a problem in either the Redpanda cluster or on the network. Cluster logs might help narrow things down?

**Comment by bkirwi** [comment]
I'd be fairly surprised if it was the end-offset fetch -- it's hard to imagine a design for Redpanda where that call isn't extremely efficient -- but unsure!

This does seem like the sort of thing one makes configurable... though 10s feels very reasonable to me.
