### ISSUE TITLE
[Epic] Horizontally scalable request layer (e.g. `pgwired`)

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#14568]
At the moment, all communication from clients goes through `environmentd`, which maintains the catalog, performs optimization, sends requests to `clusterd`, and passes results back to the client. Both data and control are multiplexed on the same connection.

The result of this multiplexing is
* increased effort for `environmentd` to provide data to clients,
* inability to restart independently of client connections, and
* risk of exhausting resources within `environmentd`.

Edit: Renamed the new component to `pgwired` based on feedback.

## Goals

Split the control and data plane into separate entities. This could be achieved using the following approach:
* Introduce an `pgwired` that accepts client connections, forwards requests to `environmentd`, and collects results from `environmentd` or `computed` directly.
* `environmentd` maintains its current responsibility but does not transfer data from `computed` to clients because that data is exchanged directly.
* `computed` hands the result of inserts directly to `persist` instead of passing data through `environmentd`
* `pgwired` needs to be stateless to avoid conflicts with `environmentd`'s state.
* The rollout needs to happen in a backwards-compatible fashion.

## Non-goals

* Move more processing, such as optimization, out of `environmentd`.

## Tasks

* Design the structure of `pgwired`
  * Derive a minimal protocol that allows `pgwired` to discover which services it needs to talk to.
* Implement the protocol between `pgwired` and `computed`, while preserving the existing communication channel.

## Alternatives

* Use Persist to move data between components of the system.

**Comment by benesch** [comment]
@mjibson has wanted this for a while! One nit: I wouldn't call the new proposed binary `adapterd`, since most of the "adapter" layer will still live in `environmentd`. @mjibson has proposed `pgwired`, which I like! Though if these handle HTTP connections too... I'm sure there's an even better name we could come up with.

A few things to consider:

  * How do we automatically scale `pgwired`? This is the core problem that we need to solve to make this approach worthwhile, IMO. If there's one `pgwired` handling all client connections, we're strictly worse off than before, as far as I can tell, because we've got an extra network boundary that's not in service of scalability or fault tolerance.
  * Our cloud infrastructure layer is not yet equipped to handle multiple `pgwired`s. With multiple `pgwired`s, we'll need a load balancer. (Right now we're able to provision environments pretty quickly because we get away with _not_ provisioning a load balancer.)
  * The current versioning and deployment scheme involves force-upgrading all binaries to the same version. That's going to frustrate the goal of restarting `pgwired` less frequently than `environmentd`. We'd need more granular versioning, so that `pgwired` is only restarted when the `environmentd`—`pgwired` protocol evolves.


----

> `computed` hands the result of inserts directly to `storaged` instead of passing data through environmentd

Probably s/`storaged`/`persist` here?

**Comment by benesch** [comment]
From [Slack](https://materializeinc.slack.com/archives/C018238000L/p1662858271665289?thread_ts=1662785751.064289&cid=C018238000L): @frankmcsherry notes that a good litmus test for `pgwired` is whether it allows us to efficiently support Fivetran ingest. The gist is that Fivetran ingest would require handling many large `COPY FROM`, `INSERT`, and `SELECT` statements. See https://github.com/MaterializeInc/materialize/issues/5188 for details.

**Comment by benesch** [comment]
Superseded by #21843/#20966.
