### ISSUE TITLE
Disallow `HashMap` and `HashSet` iteration

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#14587]
Both `HashMap` and `HashSet` have unspecified iteration orders. This non-determinism leads to errors (across multiple processes), inconsistency for e.g. explain plans, and general non-reproducibility of flaky behavior. 

Each have deterministic replacements, `BTreeMap` and `BTreeSet`, which are potentially slower in some cases, though also potentially faster in other cases. Ideally, we would use the btree variants by default, and the hash variants only when we really need to.

One thing we could do along the way is to disallow iteration of these structs, as their iteration order is not well-specified. This currently results in various errors which likely includes some false positives (things like `iter().all( ... )`). I haven't gotten to see all the errors yet, as `bin/check` bails out once the first file errors. 

The change to make to `clippy.toml` is to add these two new lines to `disallowed-methods` (ht @antiguru):
```
disallowed-methods = [

    { path = "std::collections::HashMap::iter", reason = "non-deterministic iteration order" },
    { path = "std::collections::HashSet::iter", reason = "non-deterministic iteration order" },

    ...
```

**Comment by frankmcsherry** [comment]
Current warnings about uses of `iter` on these types (not including e.g. `drain` or `keys` or others):
```
src/avro/src/schema.rs:57:9
src/avro/src/schema.rs:66:28
src/avro/src/types.rs:435:17
src/proto/src/lib.rs:236:9
src/orchestrator-process/src/lib.rs:314:22
src/persist-client/src/internal/metrics.rs:815:36
src/persist-client/examples/source_example.rs:845:13
src/expr/src/linear.rs:445:25
src/expr/src/relation/canonicalize.rs:231:23
src/expr/src/relation/join_input_mapper.rs:235:9
src/expr-test-util/src/lib.rs:721:9
src/storage/src/sink/kafka.rs:1254:49
src/storage/src/source/postgres.rs:467:29
src/storage/src/source/source_reader_pipeline.rs:221:42
src/storage/src/source/source_reader_pipeline.rs:798:42
src/storage/src/storage_state.rs:249:31
src/storage/src/storage_state.rs:253:20
src/storage/src/types/sources.rs:1116:28
src/expr/src/scalar/func.rs:6596:40
src/compute-client/src/plan/join/mod.rs:196:32
src/compute-client/src/plan/threshold.rs:86:26
src/compute-client/src/plan/mod.rs:54:27
src/transform/src/demand.rs:120:39
src/transform/src/demand.rs:194:42
src/transform/src/demand.rs:204:78
src/transform/src/demand.rs:231:35
src/transform/src/join_implementation.rs:163:34
src/transform/src/nonnull_requirements.rs:77:29
src/transform/src/nonnull_requirements.rs:112:24
src/transform/src/nonnull_requirements.rs:175:82
src/transform/src/nonnull_requirements.rs:214:25
src/transform/src/predicate_pushdown.rs:765:20
src/transform/src/predicate_pushdown.rs:806:49
src/transform/src/dataflow.rs:369:54
src/compute/src/compute_state.rs:560:31
src/compute/src/sink/persist_sink.rs:177:35
src/sql/src/plan/lowering.rs:898:61
src/sql/src/plan/lowering.rs:1087:61
src/sql/src/plan/lowering.rs:1538:21
src/sql/src/plan/query.rs:1873:29
src/sql/src/plan/query.rs:1879:32
src/sql/src/plan/statement/ddl.rs:2858:12
src/sql/src/plan/statement/ddl.rs:2874:12
src/sql/src/query_model/attribute/core.rs:204:5
src/sql/src/query_model/dot.rs:266:17
src/sql/src/query_model/rewrite/rule/simplify_outer_joins.rs:96:31
src/sql/src/query_model/rewrite/rule/simplify_outer_joins.rs:99:31
src/sql/src/query_model/rewrite/rule/simplify_outer_joins.rs:216:37
src/sql/src/query_model/test/catalog.rs:166:29
src/sql/src/query_model/test/catalog.rs:169:29
src/sql/src/query_model/test/catalog.rs:172:29
src/adapter/src/coord/sequencer.rs:639:28
src/adapter/src/coord/sequencer.rs:1494:50
src/adapter/src/coord/timeline.rs:608:37
src/adapter/src/explain_new/lir/text.rs:529:23
src/adapter/src/catalog/builtin.rs:2240:29
src/adapter/src/catalog/builtin.rs:2464:46
src/adapter/src/catalog.rs:1066:42
src/adapter/src/catalog.rs:3110:39
src/adapter/src/catalog.rs:3145:39
src/adapter/src/catalog.rs:3274:31
src/testdrive/src/action/kinesis/verify.rs:86:17
src/testdrive/src/action/kinesis/verify.rs:87:17
src/testdrive/src/bin/testdrive.rs:450:17  src/avro/src/schema.rs:57:9
src/avro/src/schema.rs:66:28
src/avro/src/types.rs:435:17
src/proto/src/lib.rs:236:9
src/orchestrator-process/src/lib.rs:314:22
src/persist-client/src/internal/metrics.rs:815:36
src/persist-client/examples/source_example.rs:845:13
src/expr/src/linear.rs:445:25
src/expr/src/relation/canonicalize.rs:231:23
src/expr/src/relation/join_input_mapper.rs:235:9
src/expr-test-util/src/lib.rs:721:9
src/storage/src/sink/kafka.rs:1254:49
src/storage/src/source/postgres.rs:467:29
src/storage/src/source/source_reader_pipeline.rs:221:42
src/storage/src/source/source_reader_pipeline.rs:798:42
src/storage/src/storage_state.rs:249:31
src/storage/src/storage_state.rs:253:20
src/storage/src/types/sources.rs:1116:28
src/expr/src/scalar/func.rs:6596:40
src/compute-client/src/plan/join/mod.rs:196:32
src/compute-client/src/plan/threshold.rs:86:26
src/compute-client/src/plan/mod.rs:54:27
src/transform/src/demand.rs:120:39
src/transform/src/demand.rs:194:42
src/transform/src/demand.rs:204:78
src/transform/src/demand.rs:231:35
src/transform/src/join_implementation.rs:163:34
src/transform/src/nonnull_requirements.rs:77:29
src/transform/src/nonnull_requirements.rs:112:24
src/transform/src/nonnull_requirements.rs:175:82
src/transform/src/nonnull_requirements.rs:214:25
src/transform/src/predicate_pushdown.rs:765:20
src/transform/src/predicate_pushdown.rs:806:49
src/transform/src/dataflow.rs:369:54
src/compute/src/compute_state.rs:560:31
src/compute/src/sink/persist_sink.rs:177:35
src/sql/src/plan/lowering.rs:898:61
src/sql/src/plan/lowering.rs:1087:61
src/sql/src/plan/lowering.rs:1538:21
src/sql/src/plan/query.rs:1873:29
src/sql/src/plan/query.rs:1879:32
src/sql/src/plan/statement/ddl.rs:2858:12
src/sql/src/plan/statement/ddl.rs:2874:12
src/sql/src/query_model/attribute/core.rs:204:5
src/sql/src/query_model/dot.rs:266:17
src/sql/src/query_model/rewrite/rule/simplify_outer_joins.rs:96:31
src/sql/src/query_model/rewrite/rule/simplify_outer_joins.rs:99:31
src/sql/src/query_model/rewrite/rule/simplify_outer_joins.rs:216:37
src/sql/src/query_model/test/catalog.rs:166:29
src/sql/src/query_model/test/catalog.rs:169:29
src/sql/src/query_model/test/catalog.rs:172:29
src/adapter/src/coord/sequencer.rs:639:28
src/adapter/src/coord/sequencer.rs:1494:50
src/adapter/src/coord/timeline.rs:608:37
src/adapter/src/explain_new/lir/text.rs:529:23
src/adapter/src/catalog/builtin.rs:2240:29
src/adapter/src/catalog/builtin.rs:2464:46
src/adapter/src/catalog.rs:1066:42
src/adapter/src/catalog.rs:3110:39
src/adapter/src/catalog.rs:3145:39
src/adapter/src/catalog.rs:3274:31
src/testdrive/src/action/kinesis/verify.rs:86:17
src/testdrive/src/action/kinesis/verify.rs:87:17
src/testdrive/src/bin/testdrive.rs:450:17
```

**Comment by frankmcsherry** [comment]
An example from `explain`: 
```rust
/// Helper struct for rendering a permutation.
struct Permutation<'a>(&'a HashMap<usize, usize>);

impl<'a> fmt::Display for Permutation<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut pairs = vec![];
        for (x, y) in self.0.iter() {
            if x != y {
                pairs.push(format!("#{}: #{}", x, y))
            }
        }

        if pairs.len() > 0 {
            bracketed("{", "}", separated(", ", pairs)).fmt(f)
        } else {
            separated("", vec!["id".to_string()]).fmt(f)
        }
    }
}
```

**Comment by aalexandrov** [comment]
I'm fixing the above example in #14535.

**Comment by frankmcsherry** [comment]
No, it was actually a different issue (in dataflow filter pushdown). The issues are everywhere! :D

**Comment by frankmcsherry** [comment]
We just saw this again in `NATURAL JOIN` column ordering, where the column identifiers were in `HashSet`s so their ultimate order was non-deterministic. I don't think we got as far as knowing if this was out of spec, but non-deterministic column orders certainly felt bad.

**Comment by teskje** [comment]
Replacing most `Hash` collections with their respective `BTree` equivalents sounds like a sane first step to make. It should be fine to do that for all maps/sets that are keyed by `Ord` types and that don't get very large, as for those the performance differences are likely negligible. Replacing large maps/sets sounds more scary, as we don't know without benchmarking how switching the collection type affects performance.

For me the main question is how we should deal with collections that need to stay `Hash`, either because their keys don't (and cannot) impl `Ord`, or because converting them into their `BTree` style causes performance regressions. For those cases we still need access to the `Hash` collections. We want a way to disallow using those in ways that exhibit non-determinism (basically any kind of iteration) by default. But it must be possible to opt out of that restriction, ideally by way of some code annotation that causes you to stop and think.

I can think of a couple approaches of implementing this "disallow by default":

1. Explicitly forbid the `HashMap`/`HashSet` methods that perform iterations in the `clippy.toml`. Drawbacks are that we actively need to add new methods that are added in new Rust releases. Also, I am not sure if it is possible to forbid trait methods, like `into_iter` that way.
2. Forbid creation the `HashMap`/`HashSet` types in the `clippy.toml`. Instead provide `mz_ore::collections` to replace them. The ore types would wrap the std types and re-export only those methods that are safe (i.e. don't rely on iteration). The ore types would also expose iteration methods, but in a way that requires explicit silencing of warnings to use them. An advantage of this approach would be that the ore types could expose safe methods that internally perform iteration but don't expose this (like the `.iter().all(...)` pattern Frank mentioned above).
3. The stdlib already contains annotations for methods that perform unstable iteration: [rustc_lint_query_instability](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#685). I'm not sure how useful they are to us though. I think we could enable them with compiler `-Z` flags, but that requires a nightly compiler. It's also not clear how one would opt out of this lint and if all iteration methods are even correctly annotated (e.g. [`HashMap::values` is not](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#422)).

Approach 3 doesn't seem feasible. Between 1 and 2 I like 2 more, mainly because it makes it convenient to define safe iteration wrappers.
