### ISSUE TITLE
Test analytics uploading is flaky

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#14602]
### Buildkite link

* https://buildkite.com/materialize/tests/builds/40831#018300f2-8c03-4266-befb-0969fa9fa74f
* https://buildkite.com/materialize/tests/builds/40831#018300f2-8c02-48c6-aef4-4e83735267c6
* https://buildkite.com/materialize/tests/builds/40831#018300f2-8c38-4eda-8189-0d2589b8e405
* https://buildkite.com/materialize/tests/builds/40831#018300f2-8cb2-4d37-a517-f404a2b12364

### Relevant log output

```source
2022-09-03T01:49:37.852504Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping
==> test/sqllogictest/postgres/pgcrypto/sha2.slt
2022-09-03T01:49:38.212213Z ERROR mz_stash::postgres: postgres stash connection error: error communicating with the server: Transport endpoint is not connected (os error 107)
    PASS: success=22 total=22
PASS: success=12130 total=12130
==> Uploading report for suite 'sqllogictest' to Buildkite Test Analytics
mzcompose: test case workflow-default failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

(the JSON error is the common part in all failures).

**Comment by aalexandrov** [comment]
Possibly related to #14544.

**Comment by benesch** [comment]
Ah, looks like uploading to Buildkite Test Analytics fails sometimes. That's too bad. We can probably rig this up to give us more logs, at the very least.

**Comment by aalexandrov** [comment]
@benesch is the Buildkite Test Analytics controlled by some of our CI files (`*.yaml`, `*.json*`, `*.py`) that I can look at for doing what you suggested?

**Comment by aalexandrov** [comment]
Assigning myself to add some more log statements to look during the next incident.

**Comment by benesch** [comment]
I think we probably know enough! This happened during the test analytics outage: https://www.buildkitestatus.com/incidents/dd90g1tff5tt

https://github.com/MaterializeInc/materialize/blob/183401d56fca5ece166065d8fe00d29dfda46c0b/misc/python/materialize/ci_util.py#L70-L71

In particular, the call to `res.json()` exploded. I suspect this is because the HTTP response was something like "504 service unavailable", rather than valid JSON. I would suggest the following:

 * Wrap L52-70 in a `try ... except` where the exception handling just prints the failures
 * Change `res.json()` to `res.text()`—we're just printing the JSON directly to stdout, so no point in decoding it as JSON
 * Remove `res.raise_for_status()`

This runs the risk of us not noticing usage errors in TA (e.g., we change the JSON payload in an invalid way), but I think that's okay. Better than failing CI when there's a TA outage.

**Comment by uce** [comment]
@aalexandrov Philip is picking this up this week.
