### ISSUE TITLE
docs: document index usage patterns

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#14645]
### Documentation request

*Split out from #12700.* Requested by @rjnn.

Our docs on indexes should clearly state when an index can be used in a where clause.

Is an index usable to speed up a `SELECT … WHERE x=y, a=b` query when the columns in the where clause are a strict match of the index columns? A lexical prefix of the index columns?

We should document this because:
  a) users coming from significant OLTP experience expect one thing
  b) users new to databases expect another thing

**Comment by morsapaes** [comment]
@joacoc has been digging into this in #13127 (though that PR in specific is scoped to the binary).

**Comment by uce** [comment]
@morsapaes Is this on DevEx to document (with support from other teams as needed) or do you expect another team to do this? I've put tentatively put this on the compute project.

**Comment by morsapaes** [comment]
@joacoc's PR is still pending review. I'd expect this to be easily transferrable to the new architecture, but if compute taking over shortens the review cycle for a revised version, that'd be really helpful.

**Comment by uce** [comment]
I've added @teskje as reviewer to that PR, because he mentioned this independently today. Let's try to get PR over the finish line (with modifications as needed for the new arch)? Until you ping someone on compute, let's assume that DevEx has this covered 😊

**Comment by morsapaes** [comment]
Thanks, @uce!

**Comment by ggevay** [comment]
There were some recent improvements in index usage patterns in the https://github.com/MaterializeInc/materialize/issues/13151 epic. In short:
- We can now do an index lookup for an OR of multiple literal constraints: E.g., earlier we did index lookup for things like
`WHERE a = 5 AND b = 6`,
now we can also do
`WHERE (a = 5 AND b = 6) OR (a = 8 AND b = 9)`.
- This means we can now do index lookups for IN lists, because those are internally translated to an OR of literal constraints: E.g., we are now able to do an index lookup for `WHERE a IN (1,2,3,7)` (and also for `WHERE (a,b) IN ((5,6), (8,9), (10,14))`).
- One limitation still is that we sometimes don't translate the above literal constraints into index lookups if there are joins in the query: https://github.com/MaterializeInc/materialize/issues/14500 A workaround is to ask the user to build an index for the entire query except for the literal constraints, and then query the index with just the literal constraints. For example, let's say the user wants to run the following query many times, with different numbers in the IN list:
```
SELECT a,b
FROM t1, t2
WHERE 
  t1.k = t2.k AND
  (a,b) IN ((5,6), (8,9), (10,14));
```
then the workaround is to build the following index:
```
CREATE VIEW only_the_join AS 
(SELECT a,b
FROM t1, t2
WHERE t1.k = t2.k);

CREATE INDEX ind ON only_the_join (a,b);
```
And then query the index with the literal constraint:
```
SELECT a,b
FROM ind
WHERE (a,b) IN ((5,6), (8,9), (10,14));
```
This query will use the fast path (i.e., won't build a dataflow, but just quickly read the appropriate values from the index).

**Comment by ggevay** [comment]
I'll write up the info from my previous comment (+ some new info) into a documentation PR some time in the next few days.
