### ISSUE TITLE
doc/user: Update CTE Known Limitations to reflect changes

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#14711]
### Documentation request

The [known limitations](https://materialize.com/docs/sql/select/#known-limitations) section cites an issue #4867 twice, and that issue is now closed.

Unclear if that means those limitations are no longer around, but worth checking.

**Comment by morsapaes** [comment]
@aalexandrov might be the person to ping here!

**Comment by ggevay** [comment]
The 2nd one is no longer true. (We have RelationCSE.)

The 3rd limitation will soon be removed. And in the meantime it should link to https://github.com/MaterializeInc/materialize/issues/17012 instead of https://github.com/MaterializeInc/materialize/issues/2516

I'm not sure about the first one. The following seems to run fine. so maybe it's resolved?
```
create table t1 (f1 integer, f2 integer);

insert into t1
with mutually recursive (iteration limit 10)
  c0(a int, b int) as (select f1, f2 from t1 union select a+1, b+1 from c0)
select * from c0;
```
Or did the original issue mean an INSERT or UPDATE _inside_ a CTE? Does the standard allow that?

**Comment by ggevay** [comment]
Figured it out with Sean's help: https://materializeinc.slack.com/archives/C02FWJ94HME/p1685024215722939?thread_ts=1685023278.642589&cid=C02FWJ94HME

```
with
  cte as (insert into t1 select 1 as a, 2 as b RETURNING a+a, b+b)
select * from cte;
```

works in Postgres, but not in Materialize.

**Comment by ggevay** [comment]
Fixed in https://github.com/MaterializeInc/materialize/pull/19488
