### ISSUE TITLE
persist: massive spike in consensus scan bandwidth

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#14719]
After the release w/ incremental state our consensus scan usage skyrocketed, and we're now pulling down 600-700MiB/s from CRDB. That's a lot!

<img width="859" alt="Screen Shot 2022-09-08 at 12 21 37 PM" src="https://user-images.githubusercontent.com/785446/189189200-7391b14b-b52d-477b-84fe-5996714249c4.png">

**Comment by danhhz** [comment]
end of day summary: we're pretty sure at this point that some, but not all, shards are not running gc. every theory we've come up with for why hasn't quite panned out yet

I should write up more details here, but tbh my brain is completely fried at this point

the best evidence we've had so far is that the most recent rollup of the affected shards seems to have seqno, seqno_since, and last_gc_req line up with expectations, but there are an unbounded number of rollups registered in state. these rollups exist in blob and consensus is not being truncated.

https://gist.github.com/danhhz/e08bc67f9e0df8fbb77f9b2aee137917

**Comment by danhhz** [comment]
Grabbed the most recent 100 diffs to get a sense for what the traffic on this shard is like. It seems to be exactly what you'd expect for a shard being updated once per second by a single writer, successfully applying compactions, and with a single reader periodically heartbeating its lease

https://gist.github.com/danhhz/ccaed64b4830073e2df33666d06a7523

**Comment by danhhz** [comment]
Some takeaways from staring at this:

- I'm becoming uncomfortable with any cmd skipping assigned maintenance. It's hard enough to reason about the behavior of maintenance assignment without having to consider them being skipped.
- StateVersions::fetch_live_diffs existing is probably a bad idea. It's one problem for us to be leaking state into crdb because we're not running gc. It's another to be scanning over all of them. This was written the way it was (disclaimer: by me) so that we could do one fetch, but after this incident, I'm inclined to replace it with two calls. One to fetch `current` and a followup to fetch all diffs between the most recent rollup and current.

**Comment by danhhz** [comment]
Okay walking through why gc might not be running:
- Both pods that are writing to this shard got bounced 39h ago (long after the issue started), so I don't think e.g. gc is permanently wedged somehow (unless it re-wedges on restart)
- last_gc_req is getting updated (as seen in the rollup I posted yesterday). this only happens when `maybe_gc` returns a gc req (https://github.com/MaterializeInc/materialize/blob/af749ea093e179a4c34ba32fc7dfa8f6788983cc/src/persist-client/src/internal/state.rs#L552), so reqs are being generated
- we've thought through the early return at the beginning of gc, it's tested, and it seems to work in practice, so i think that one is okay https://github.com/MaterializeInc/materialize/blob/af749ea093e179a4c34ba32fc7dfa8f6788983cc/src/persist-client/src/internal/gc.rs#L206-L215
- this leaves us, I think, with only:
  - the maintenance that includes this gc req is being dropped by whoever it's assigned to. pretty sure that it would just be whatever writer comes along first after the reader updates its seqno hold. i don't see any of the cmd types that drop maintenance in my manual scan of diffs in consensus above
  - gc starts but is stuck somehow. go had an http handler that returned the stacktraces of all goroutines (including how long they've been parked, if applicable) that would be pretty amazing to have here (with s/goroutines/tokio tasks/)

**Comment by danhhz** [comment]
One interesting find: the diffs we write to durable storage never include updates to last_gc_req becuase we compute the diff before we call `maybe_gc` on `new_state`. The rollups do, because they're a directly serialized version of the in-mem version of state. This is suspicious, but I haven't yet figured out how it would explain our symptoms

https://github.com/MaterializeInc/materialize/blob/af749ea093e179a4c34ba32fc7dfa8f6788983cc/src/persist-client/src/internal/machine.rs#L537-L568

**Comment by danhhz** [comment]
okay next steps are..... 

- we could build and deploy a custom build to devex's env with additional logging
- we could manually run gc through persistcli
- ???

**Comment by danhhz** [comment]
Got a fix up in https://github.com/MaterializeInc/materialize/pull/14789

fyi @benesch, good news is we could potentially write up a tool to fix existing instances of this in prod. bad news is we'll continue to get new instances until the fix gets deployed

**Comment by benesch** [comment]
> Got a fix up in #14789
> 
> fyi @benesch, good news is we could potentially write up a tool to fix existing instances of this in prod. bad news is we'll continue to get new instances until the fix gets deployed

Ack. How dire do you think it is? #14789 looks really small and targeted. We could potentially issue v0.27.0-alpha.21 with #14789 cherry-picked in and deploy that to cloud this week, even though we weren't planning to.

**Comment by benesch** [comment]
And—huge thank you for finding this bug! Previews period working as designed. 😅

**Comment by benesch** [comment]
Sounds good!

**Comment by danhhz** [comment]
Fix for this has merged. Leaving the issue open until it's been deployed to prod and we've confirmed that the overall consensus scan behavior has been fixed

**Comment by pH14** [comment]
This one has been fixed for a while
