### ISSUE TITLE
sql: support `date(timestamp)` function

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#14803]

**Comment by sjwiesman** [comment]
relevant community slack thread https://materializecommunity.slack.com/archives/C015KDVS7EV/p1659644665202489

**Comment by chaas** [comment]
There's no record of that function in the [postgres docs](https://www.postgresql.org/docs/current/functions-datetime.html). because it's actually a type cast that uses function-like syntax https://www.postgresql.org/docs/13/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS.

The best solution would be to implement this the way postgres does and support all function-like syntax casts that postgres does. However, if we want to get this out by the next release, I can implement `date(timestamp)` as a function for now, and we can replace with generic casting later.

**Comment by mmclead** [comment]
the devs at Looker apparently didn't read that disclaimer and made  their generated SQL wrap all dates with `DATE(the_timestamp)` instead of using the normal cast.   

Dates are the only place they do this.
For example, `week` has this in the SQL: `TO_CHAR(DATE_TRUNC('week', the_timestamp), 'YYYY-MM-DD')`
But for displaying things per day, it always puts the `DATE(the_timestamp)` function on.

**Comment by morsapaes** [comment]
FYI, @joacoc @ahelium.

**Comment by mjibson** [comment]
Merged, will be in the next release.
