### ISSUE TITLE
regression: No such key in record: transaction - sink schema does not correspond to topic content

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14825]
### What version of Materialize are you using?

a229fba

### How did you install Materialize?

Docker image

### What is the issue?

`$ kafka-verify` is no longer able to verify sink output unless a key is present. The error returned by testdrive:

```
No such key in record: transaction
```

seems to indicate that the schema that we publish does not match the actual contents of the topic.

https://buildkite.com/materialize/nightlies/builds/1158#01833bc4-a65c-4dff-ac81-b352cafb80e7

**Comment by philip-stoev** [comment]
@bkirwi this issue seems to be caused by this commit:

```
commit 3a4603d01c948de5c465b92e32e13d43d5fd33d2
Author: Ben Kirwin <bkirwi@materialize.com>
Date:   Tue Sep 13 15:36:58 2022 -0400

    [sinks] Replace the transaction field with a Kafka header in the sink (#14678)
```

I will fix the test to use keys, but I wonder if there is a problem in the product as well. The error message seems to indicate that a `transaction` key is expected , but no such string constant is used in str/testdrive , only in src/interchange . I checked the sink schema  that is published to the schema registry and the contents of the sink topic, and there is no mention of `transaction` in either. To reproduce:

```
$ set-regex match=\d{13} replacement=<TIMESTAMP>

> CREATE MATERIALIZED VIEW v1 (f1) AS VALUES (1)
> CREATE CONNECTION IF NOT EXISTS csr_conn
  FOR CONFLUENT SCHEMA REGISTRY
  URL '${testdrive.schema-registry-url}';

> CREATE CONNECTION IF NOT EXISTS kafka_conn FOR KAFKA BROKER '${testdrive.kafka-addr}';
> CREATE CONNECTION IF NOT EXISTS csr_conn FOR CONFLUENT SCHEMA REGISTRY URL '${testdrive.schema-registry-url}';
> CREATE SINK s1 FROM v1
   INTO KAFKA CONNECTION kafka_conn (TOPIC 'kafka-sink-1')
   FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn;

$ kafka-verify format=avro sink=materialize.public.s1
{"before": null, "after": {"row": {"f1": 123}}, "transaction": {"id": "<TIMESTAMP>"}}
```

**Comment by philip-stoev** [comment]
@bkirwi I could not fix the test after all.

I tried all sorts of options to `kafka-validate`, including `headers=materialize-timestamp`, but I can not get it to bulge . Your help would be much appreciated.

**Comment by bkirwi** [comment]
Hi @philip-stoev! I think this is the change working as intended.

One bad thing you're running into is an unhelpful `verify` error message. In particular, `No such key in record: transaction` means that the "expected"  message had a `transaction` field, but the "actual" message did not. This is expected: my PR intentionally removes that field from the message body. Quite confusingly, that error doesn't have anything to do with what Kafka refers to as the record key. (It looks like [we have control over that error message](https://github.com/MaterializeInc/materialize/blob/3a4603d01c948de5c465b92e32e13d43d5fd33d2/src/testdrive/src/format/avro.rs#L129) -- IMO it would be better to change it to "No such field in record" or something similar.)

Here's how I might adapt the test you pasted:

```
> CREATE MATERIALIZED VIEW v1 (f1) AS VALUES (1)
> CREATE CONNECTION IF NOT EXISTS csr_conn
  FOR CONFLUENT SCHEMA REGISTRY
  URL '${testdrive.schema-registry-url}';

> CREATE CONNECTION IF NOT EXISTS kafka_conn FOR KAFKA BROKER '${testdrive.kafka-addr}';
> CREATE CONNECTION IF NOT EXISTS csr_conn FOR CONFLUENT SCHEMA REGISTRY URL '${testdrive.schema-registry-url}';
> CREATE SINK s1 FROM v1
   INTO KAFKA CONNECTION kafka_conn (TOPIC 'kafka-sink-1')
   FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn;

$ kafka-verify format=avro sink=materialize.public.s1
{"before": null, "after": {"row": {"f1": 123}}}
```

ie. remove the transaction field from the expectation, and also remove the regex replacement, since it's no longer needed. You shouldn't need to use the new `header=` thing unless you explicitly want to verify the specific timestamps, which it sounds like probably you don't care.

I hope that all makes sense! Happy to follow up if it's still troubling.

**Comment by philip-stoev** [comment]
@bkirwi oh thanks I got it all wrong and wasted several hours instrumenting testdrive with println! . I will remove the "transaction" from the expected results and fix the test. Thanks again.
