### ISSUE TITLE
regression: Filter no longer pushed to one side of an outer join

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14905]
### What version of Materialize are you using?

0d5dd469394359a5412bd06618a3e44c9e11e2f6

### How did you install Materialize?

Docker image

### What is the issue?

In revision `0e23dd73636914e97cc18f11b0f91e28f688ff40`, the plan for the following query:

```
SELECT *
  FROM t2 AS a1
  left JOIN t2 AS a2
    ON (a1 . f1 = a2 . f1)
 WHERE (a2 .f2 = 1)
    OR (a1 . f1 = 6 AND a1 .f2 = 3 AND a2 .f2 = 4)
    OR (a1 . f1 > 0 AND a1 . f1 = 6) ;
```

Was as follows:

```
%0 = Let l0 =
| Get materialize.public.t2 (u4)
| ArrangeBy (#0)

%1 = Let l1 =
| Join %0 %0 (= #0 #2)
| | implementation = DeltaQuery
| |   delta %0 %0.(#0)
| |   delta %0 %0.(#0)
| Filter (#0) IS NOT NULL
| Project (#0, #1, #3)

%2 =
| Get %1 (l1)
| Filter (null || ((#0 = 6) && (#0 > 0))) <- HERE
| Project (#0)
| Distinct group=(#0)
| ArrangeBy (#0)

%3 =
| Join %0 %2 (= #0 #2)
| | implementation = DeltaQuery
| |   delta %0 %2.(#0)
| |   delta %2 %0.(#0)
| Filter (null || ((#0 = 6) && (#0 > 0)))
| Project (#0, #1)
| Negate

%4 =
| Get materialize.public.t2 (u4)
| Filter (null || ((#0 = 6) && (#0 > 0)))

%5 =
| Union %3 %4
| Map null, null

%6 =
| Get %1 (l1)
| Map (#0 = 6)
| Filter ((#3 && (#0 > 0)) || (((#3 && (#1 = 3)) && (#2 = 4)) || (#2 = 1)))
| Project (#0, #1, #0, #2)

%7 =
| Union %5 %6
```

The `Filter (null || ((#0 = 6) && (#0 > 0)))` was pushed all the way to `%2`,  which is either incorrect or a general AI move given the fact that this is an outer join with a bunch of predicates. I tried to reason about it for a bit and it seems correct, though Postgres does not do it.

However, in the current main, `0d5dd469394359a5412bd06618a3e44c9e11e2f6` the plan does not have that Filter pushed/pulled that high.

Dataset:

```
DROP SCHEMA public CASCADE;

CREATE SCHEMA public;

CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t1i1 ON t1(f1);
CREATE INDEX t1i2 ON t1(f2, f1);

-- one NULL row in t1

INSERT INTO t1 VALUES (NULL, 0);

-- values 1 and 2 have 2 rows each in t1

INSERT INTO t1 VALUES (1, 1);
INSERT INTO t1 VALUES (1, 1);
INSERT INTO t1 VALUES (2, 2);
INSERT INTO t1 VALUES (2, 2);
INSERT INTO t1 VALUES (3, 3);
INSERT INTO t1 VALUES (4, 4);
INSERT INTO t1 VALUES (5, 5);
INSERT INTO t1 VALUES (6, 6);
INSERT INTO t1 VALUES (7, 7);
INSERT INTO t1 VALUES (8, 8);

-- value 9 not present in either table

CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t2i1 ON t2(f1);
CREATE INDEX i2i2 ON t2(f2, f1);

-- two NULL rows in t2

INSERT INTO t2 VALUES (NULL, 0);
INSERT INTO t2 VALUES (NULL, 0);

INSERT INTO t2 VALUES (1, 1);

-- value 2 has 2 rows in t2
INSERT INTO t2 VALUES (2, 2);
INSERT INTO t2 VALUES (2, 2);

-- value 3 has no rows in t2
INSERT INTO t2 VALUES (4, 4);
INSERT INTO t2 VALUES (5, 5);
INSERT INTO t2 VALUES (6, 6);
INSERT INTO t2 VALUES (7, 7);
INSERT INTO t2 VALUES (8, 8);

-- value 9 not present in either table

CREATE TABLE t3 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t3i1 ON t2(f1);
CREATE INDEX i3i2 ON t2(f2, f1);
```

**Comment by ggevay** [comment]
The change happens in 5bfd3d043784134a3c7b265fcab64b8e004b2f13, which is my variadic AND/OR commit. Should I take the issue from you, @aalexandrov ?

**Comment by ggevay** [comment]
I figured it out, with the help of #14913, which pointed my attention to `predicate_pushdown`. There are two problems:

### 1.

`undistribute_and_or` misses the absorption opportunity in this expression:
```
(
	null ||
	(#2 && null && (#1 = 3)) ||
	(#2 && (#0 > 0))
)
```
There are two undistribution opportunities here: either the `null` from the 1. and 2. arguments of the OR, or the `#2` from 2. and 3. arguments of the OR. These two opportunities overlap, so you can only perform one of them. `undistribute_and_or` is not smart enough to try both of these, because trying both and recursing in both directions would lead to an exponential explosion in query optimization time. So it just picks one arbitrarily, and before the variadic AND/OR commit, `undistribute_and_or` was lucky to pick the `null`, which leads to an absorption that makes the 2. argument disappear:
`null || (#2 && (#0 > 0))`.
After the variadic AND/OR commit, we randomly pick the `#2` (due to some random change in the `cmp` of `MirScalarExpr`), which doesn't lead to a meaningful simplification.

I'll open a PR tomorrow to add a bit of smart to `undistribute_and_or`: when choosing `indexes_to_undistribute`, it will prefer indexes that lead to an absorption. This is just a few lines of extra code there, and I think such a choice is always at least as good as any other choice, and often better.

### 2.

Even the more complicated unreduced expression should be possible to be pushed down into the join input, but our `predicate_pushdown` code misses this fact due to MFP CSE messing with us in a similar way as in the literal constraints detection in `CanonicalizeMfp`. There `CanonicalizeMfp::inline_literal_constraints` solves this problem, maybe something like that would be applicable also in `predicate_pushdown`. I might open an issue tomorrow for this problem.

**Comment by ggevay** [comment]
I tried to do the above-mentioned change to `undistribute_and_or`, but unfortunately it's not solving the problem. Things are happening a bit differently than I thought: The wrong undistribution that prevents the absorption happens already before the nulls are introduced by the predicate pushdown pushing through the map. This means that after the nulls are introduced it's no longer possible to undistribute the null. The reason why the old code before the variadic AND/OR commit was not running into this problem is that it was _missing_ the undistribution opportunity _before_ the nulls are introduced. This is because before the variadic AND/OR, undistribution from a chain of ORs could happen only from two adjacent OR arguments.

So the TLDR is that we are simplifying AND/OR trees only heuristically, and due to various random changes that happened when introducing variadic AND/OR, the heuristic regressed in some cases.

In general, simplifying AND/OR trees seems NP-hard, so unfortunately I don't think we can aim for avoiding such regressions in all cases. Still, I think `undistribute_and_or` is smarter now than it was, i.e., it almost certainly covers more cases than before. It's just that the cases covered now are not a superset of the old cases.

Anyhow, I'll open a PR for the absorption stuff, because even if it's not solving this specific issue, it might help in other cases.
