### ISSUE TITLE
scope clusters to the logical database

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#15029]
### Feature request

Materialize supports the postgres database abstraction, and clusters allow for strict use case isolation. However, clusters are currently global and not scoped to any given db. This feels confusing as most (all?) other catalog objects (views, tables, indexes, mvs, sources, sinks) are scoped.

**Comment by sjwiesman** [comment]
cc @chaas @ggnall I'm looking to start a conversation, I'd be curious to understand if there's a compelling reason not to do this.

**Comment by benesch** [comment]
So this was an intentional choice, back in the days of the [platform UX design](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/ux.md#cluster)! I'm short on time but here's the tl;dr:

  * It matches how warehouses work in Snowflake, which are analogous to clusters.
  * It matches how [publications](https://www.postgresql.org/docs/current/sql-createpublication.html) work in PostgreSQL, which are similarly groupings of things (tables, specifically) across multiple schemas.
  * It will play better with SQL RBAC, because there is only one database, one schema, one item, and one cluster at play. If clusters were scoped to a schema, there'd be two databases, two schemas, and two items and play, and the access control rules would get complicated.

**Comment by sjwiesman** [comment]
> It will play better with SQL RBAC, because there is only one database, one schema, one item, and one cluster at play. If clusters were scoped to a schema, there'd be two databases, two schemas, and two items and play, and the access control rules would get complicated.

I don't fully understand this last point. Aren't things clearer if clusters are scopped to the database? If you don't have access to a db than you don't have access to any of it's clusters. In the current model you could run a workload on a cluster created and being used by someone from a db you don't have access to.

**Comment by benesch** [comment]
> > It will play better with SQL RBAC, because there is only one database, one schema, one item, and one cluster at play. If clusters were scoped to a schema, there'd be two databases, two schemas, and two items and play, and the access control rules would get complicated.
> 
> I don't fully understand this last point. Aren't things clearer if clusters are scopped to the database? If you don't have access to a db than you don't have access to any of it's clusters. In the current model you could run a workload on a cluster created and being used by someone from a db you don't have access to.

Do you mean scoped to the database or to the schema? Everything else is scoped to the schema, not to the database. If we take clusters scoped to a schema as an example...

```
CREATE DATABASE benesch;
CREATE DATABASE seth;
CREATE CLUSTER benesch.public.c (REPLICAS r1 (SIZE 'small'));
CREATE VIEW seth.public.foo AS ...;
CREATE DEFAULT INDEX ON seth.public.foo IN benesch.public.c;
```

Is this allowed? Am I allowed to create a index in your schema in my cluster in my schema? I think it depends if I have the `USAGE permission` on `benesch`, `USAGE` permission on the `benesch.public` schema, `USAGE` on the `benesch.public.c` cluster, `USAGE` on the `seth` database, and `CREATE` on the `seth.public` schema. Or something along those lines. I couldn't find any prior art for a DDL statement that created an object that referred to objects in two separate schemas. 

The RBAC rules are simpler in a world where clusters are global. It's just `USAGE` on the `seth` database, `CREATE` on the `seth.public` schema, and `USAGE` on, say, the global `c` cluster.

And if you don't allow objects to cross schemas like this, you'd substantially limit the usefulness of clusters; e.g., if you want multiple developers to all share the same `dev` account. 

----

I forgot to mention before, too—there's prior art in PostgreSQL itself, in the form of [tablespaces](https://www.postgresql.org/docs/current/manage-ag-tablespaces.html). A table can belong to a tablespace, which is the physical location on disk where the tablespace is stored. Tablespaces are global, just like clusters. A lot of the design is cribbed from tablespaces, since we _know_ that there won't be (m)any weird edge cases in permissioning like this, because PostgreSQL has already made it work reasonably sanely for tablespaces.

**Comment by benesch** [comment]
> Thank you for humoring me :)

Always! I'm not 100% satisfied with the design myself, but it seemed like the best of the available options.
