### ISSUE TITLE
storage + adapter: add validation for source connections

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#15082]
See also the [**Connection and source validation braindump**](https://www.notion.so/materialize/Connection-and-source-validation-477045065ef1481d90d25e06dbeca4b6) in Notion.

----

Currently we don't provide user-facing validation on creation of a connection or source. This means that if a user mis-types an input (password, kafka topic name) or if something in the configuration changes down the road, we're silently failing to ingest from the source.

There are a few reasons why simply validating on `CREATE CONNECTION` or `CREATE SOURCE` would not be a sufficient solution:
* Some users actually want to create a connection that will fail, in order to get a persisted connection id, which the user then whitelists on their source (e.g. in Kafka). In that case, we'd only want to run validation later, and would want to allow the `CREATE` to go forward even though the connection would fail.
* Something might change with the source/connection at a time after creation that causes the connection to fail, and we'd want to catch & surface those issues as well.
@benesch may have more reasons why that I didn't catch.

As such, a proposed solution might do the following:
1) Add validation on `CREATE CONNECTION`, toggled by an option. This way users who wish to validate immediately can, but those with use cases detailed above are not required to.
2) Provide a command to run validation on an existing connection at any point after creation. This way a user can check whether a connection works after performing some changes or setup on their end.
3) Add validation on `CREATE SOURCE`, again toggled by an option as with step 1.
4) Perform ongoing heartbeat checks on existing sources to notify if the connection fails at some point after creation (already tracked in #13453).

cc: @ggnall @nmeagan11

**Comment by nmeagan11** [comment]
Historical issue as an example: https://github.com/MaterializeInc/materialize/issues/6186

**Comment by bkirwi** [comment]
> a persisted connection id

Can you elaborate on what this means in the Kafka context? In general it would be nice if our behaviour was predictable enough that users didn't need to have something fail before it could succeed...

**Comment by bkirwi** [comment]
> Provide a command to run validation on an existing connection at any point after creation.

Hopefully after https://github.com/MaterializeInc/materialize/issues/12864 this can just be a select!

**Comment by benesch** [comment]
> Historical issue as an example: #6186

I think that one's different, actually! #6186 is about syntactic errors not being rejected. Whereas this issue is about syntactically valid `CREATE SOURCE` statements that result in an invalid connection.

> > a persisted connection id
> Can you elaborate on what this means in the Kafka context? In general it would be nice if our behaviour was predictable enough that users didn't need to have something fail before it could succeed...

It's quite a bit more clear with AWS connections, once we add those back for S3 sources. Details here: https://github.com/MaterializeInc/cloud/issues/2837#issuecomment-1142453135

With Kafka, though, I think there's something similar with consumer group IDs! Imagine by default we use a consumer group named `materialize-$ENVID-$CONNID-$SOURCEID`. You might want to write a Kafka ACL that only allows the user associated with the connection to use consumer groups named `materialize-$ENVID-$CONNID-*`. You can't write that policy until you know the connection ID, and you won't know the connection ID until `CREATE CONNECTION` has succeeded... so if `CREATE CONNECTION` one day learned to verify that it had the appropriate ACLs, there'd need to be a way to turn that _off_ to solve this chicken-and-egg problem.

It's all a bit contrived with Kafka, though. Like, we can just let the user specify a fixed `GROUP ID PREFIX`, allow that in their ACLs before they create the connection—problem solved.

With AWS, though, it's critical for the security of IAM role delegation that _we_ generate the external ID based off of factors outside the customer's control. So the chicken-and-egg problem is fundamental there.

**Comment by benesch** [comment]
I wrote up a [braindump](https://www.notion.so/materialize/Connection-and-source-validation-477045065ef1481d90d25e06dbeca4b6), which tries to distill what @chaas has in the issue description into a slightly more prescriptive philosophy where it makes sense, and call out what's still in the proposal phase.

**Comment by benesch** [comment]
We're having particular trouble surfacing to users when their AWS PrivateLink connection fails. See, for example incident 42 (MaterializeInc/cloud#5761).

We probably _do_ want to pursue (4), with additional PrivateLink goodness, like opening a TCP connection and reporting whether that succeeds/fails in addition to reporting whether the higher level protocol (SR, Kafka, etc) succeeds/fails. If TCP connections succeed but something else fails, that's a good signal that PL is working but the configured auth method is wrong, for example.

**Comment by sploiselle** [comment]
This is being worked on in #19487

**Comment by petrosagg** [comment]
This is now done
