### ISSUE TITLE
Support complex denormalized data with static typing

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1514]
We have support in the backend for arbitrary nested datastructures. In the sql frontend we only expose these via the jsonb type, which requires run-time type-checking and casting (as well as downstream issues like https://github.com/MaterializeInc/materialize/issues/1476). 

We could also expose these via sql arrays/records with statically known types derived from eg json or protobuf schemas. This would allow a richer variety of types (eg all kinds of numbers), compile-time checking and less casts (which means less typing).

I haven't looked at the record api yet but the array api seems easy to implement, at least for the 1d case.

Postgres also has apis for converting between dynamically typed json and statically typed arrays/records eg `jsonb_to_record`.

**Comment by benesch** [comment]
We've made substantial progress here, such that it is time to close this issue in favor of the finer-grained work-
tracking issues that remain.

#3505 added basic support for anonymous record types. #2644 added basic support for a `LIST` type. That leaves #3516 to finish out named record type support, and #2997 to productionalize the `LIST` type.

@umanwizard is actively working on hooking #3505 up to the Avro decoder, so that we actually decode nested Avro records into nested tuples. I don't think we have a public issue for that, but it should be obvious to folks who can see the private event stream what issue is tracking that work.
