### ISSUE TITLE
SHOW views in [schema] takes > 1min to respond

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#15193]
### What version of Materialize are you using?

 v0.27.0-alpha.23 (8246581f

### How did you install Materialize?

Materialize Cloud

## Reproduction instructions:
1. Create new cluster replica
2. Set to active cluster 
3. Run show views in {schema}

**Expected result:**
Returns takes > 1 min

**Actual result:** 
Should return in <10 seconds

## Resolution (Open)
* We were not able to reproduce this issue ourselves
* ~30min later the query worked as expected. We are not sure why.

`explain timestamp for select * from mz_views;` returns: 
<img width="911" alt="CleanShot 2022-10-05 at 17 39 44@2x" src="https://user-images.githubusercontent.com/4104582/194102641-380418a0-581b-4c60-87df-40114d019d7b.png">

More details: https://materializeinc.slack.com/archives/C040W9SRS80/p1664980934815089

**Comment by jkosh44** [comment]
By the way, after reading the slack conversation, it's possible that this `EXPLAIN TIMESTAMP` is misleading. It was run about 20 minutes after the issue was encountered and about 5 minutes after running `EXPLAIN TIMESTAMP` the issue was gone. So it is _possible_ (but not certain) that there was some timestamp selection issue which corrected itself before `EXPLAIN TIMESTAMP` was run.

Completing this issue: https://github.com/MaterializeInc/materialize/issues/14915, would make scenarios like this less ambiguous because we'd have the exact timestamp selection logic for each query in the logs.

**Comment by benesch** [comment]
Mentioned to @frankmcsherry in person, but recording here for posterity: I believe this is currently "in spec." When `CREATE CLUSTER` returns, it does not guarantee that those compute resources have actually come online—just that their request has been durably recorded. In the worst case, it might take minutes or hours for the cluster to come online, because we've run out of compute resources and need to ask AWS for another VM—and AWS might not have another VM available for us!

We definitely need to improve visibility of cluster status, though! I think right now it's tucked away in `mz_cluster_replica_status`, and we haven't been good about telling users about that table, and that they need to look there before they can start running queries on a cluster.
