### ISSUE TITLE
Adapter: Create default indexes for SHOW commands

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#15366]
### Feature request

Running `SHOW` commands should always be fast so user have a pleasant experiencing navigating through their deployment. Recently `SHOW` has been slow and there is no way for users to create indexes to speed them up. #3751 has been proposed as one potential solution to this problem. 

Another potential solution is to create default indexes for all `SHOW` commands in the `mz_introspection` default cluster. Additionally all `SHOW` commands can be automatically routed to the `mz_introspection` cluster, regardless of the users active cluster. This would ensure that `SHOW` commands always are fast and easy to execute.

**Comment by benesch** [comment]
> Additionally all `SHOW` commands can be automatically routed to the `mz_introspection` cluster, regardless of the users active cluster. This would ensure that `SHOW` commands always are fast and easy to execute.

I like the spirit, but the heuristic here seems a bit messy. What if the `SHOW` command is nested? E.g., `SELECT * FROM (SHOW ...)`. What cluster does that run on? Will it be surprising that if you switch from a `SHOW` command to a `SELECT` against the system catalog (because you need to dig deeper), suddenly you're back on the normal cluster? What if you _really_ want to override the cluster on which a `SHOW` runs? Do we need a `cluster_i_really_mean_it` variable?

**Comment by benesch** [comment]
I might start by issuing a `NOTICE` when there was an index available on the `mz_introspection` cluster and _not_ in the active cluster. Something like:

NOTICE: This query may be faster if you switched to the mz_introspection cluster.

**Comment by chaas** [comment]
@benesch We're going to go forward with the just the change to create default indexes for all SHOW commands in the `mz_introspection` default cluster, unless you have any hesitations.

We'll make a separate ticket around adding the `NOTICE` you suggested and updating docs to guide users to run their SHOW commands on that cluster.

**Comment by benesch** [comment]
> unless you have any hesitations.

No, having the indexes around sounds great!
