### ISSUE TITLE
`environmentd` startup is slow

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15379]
Starting up `environmentd` has gotten quite slow. With 122 objects in the catalog it takes a minute or more for `environmentd` to start accepting connections, according to @philip-stoev.

Slack conversation: https://materializeinc.slack.com/archives/CL68GT3AT/p1665561006329699

A big part of the problem is that `environmentd` synchronously connects to all replicas at startup.

This becomes more important with zero downtime version upgrades (https://github.com/MaterializeInc/materialize/issues/13042), since a key component of our plan there (at least, at the moment) is being able to restart `environmentd` very quickly.

Related issues:

  * #15368
  * #14599
  * #15380

**Comment by benesch** [comment]
@chaas @ggnall wanted to toss this one onto your radars. Would be good to get this someone on the priority queue.

**Comment by benesch** [comment]
> A big part of the problem is that environmentd synchronously connects to all replicas at startup.

This was a serious problem in today's live debugging session. We observed the DevEx `environmentd` take multiple _minutes_ to restart, as it was attempting to connect to various cluster replicas and storage hosts that were in crash loops.

**Comment by arusahni** [comment]
Another data point: With #_incident-7, Datalot's envd pod took 15 minutes to start up after I killed it.

**Comment by benesch** [comment]
Slack discussion here: https://materializeinc.slack.com/archives/CM7ATT65S/p1666625687941239. The issue seems to be that some persist shards have a massive and increasing number of blob parts that take an increasingly long time to download.

**Comment by jkosh44** [comment]
I just wanted to highlight some things from the slack discussion. 
- During bootstrapping, we read in the contents of all the system tables. This part was identified as being extremely slow.
- The two specific system tables that were taking a long time were `mz_internal.mz_cluster_replica_statuses` and `mz_internal.mz_cluster_replica_heartbeats`.
- Those two tables do not have a lot of rows. They have one row per replica which is generally a single or double digit amount of rows.
- These two tables did have an enormous amount of data in persist.
- `mz_cluster_replica_heartbeats` is frequently updated and `mz_cluster_replica_statuses` may be frequently updated in some scenarios.

Some remaining open questions are:
- If those two tables have so few rows, then why is there so much data in persist? Is something wrong with compaction or stuck `since`s?
- These two tables have no relationship to the amount of objects in the catalog. Is there another source of slow down that is related to the amount of objects in the catalog? Or is the number of objects in the catalog not a source of slow down?

**Comment by danhhz** [comment]
> If those two tables have so few rows, then why is there so much data in persist? Is something wrong with compaction or stuck sinces?

If we can get some environment+shard ids then we can poke at metrics to see if any compaction issues jump out

**Comment by danhhz** [comment]
Nevermind! Just saw in the slack thread that paul had already done this

**Comment by danhhz** [comment]
what's the status here?

**Comment by mjibson** [comment]
Probably massively improved due to a bunch of stash improvements, but we don't currently measure this. I've added measuring this to https://github.com/MaterializeInc/materialize/issues/15906.

**Comment by danhhz** [comment]
👍 I'm asking because I have this listen on the "persist fires" meta issue. do we think there's still more persist compaction improvements necessary or is that back in adaptor's court?

**Comment by chaas** [comment]
Closing this as resolved since the issues causing the acute slowness are resolved. Please reopen if major slowness is still being observed.

We are adding metrics to measure environmentd startup speed in #15906.
We will plan make further improvements to environmentd startup speed as part of our regularly scheduled work in the future.

**Comment by philip-stoev** [comment]
another one presumably due to caching a negative DNS response - https://github.com/MaterializeInc/cloud/issues/4599
