### ISSUE TITLE
The `collection_timestamp` column in `mz_storage_usage` may contain multiple distinct values per reporting interval

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15464]
### What version of Materialize are you using?

 v0.28.0-dev (006fff5f3)

### How did you install Materialize?

Docker image

### What is the issue?

The `collection_timestamp` value is not stable enough to be used as a filtering or a grouping key in the `mz_storage_usage` view.

With the reporting interval set to 1 minute:

```
materialize=> select collection_timestamp, sum(size_bytes) from mz_storage_usage group by collection_timestamp order by collection_timestamp;
    collection_timestamp    |    sum    
----------------------------+-----------
 2022-10-17 12:51:55.67+00  |    162605
 2022-10-17 12:52:56.432+00 |    378534
 2022-10-17 12:54:07.379+00 | 141706905
 2022-10-17 12:55:07.398+00 | 158787078
 2022-10-17 12:55:07.399+00 |   1165910
```

There are two separate measurements for the `2022-10-17 12:55:07` minute, differing by 1ms . Any statistics will be incorrect unless those two are summed together. This means that naive queries such as :

```
select sum(size_bytes) from mz_storage_usage
where collection_timestamp = (
  select max(collection_timestamp) from mz_storage_usage
);
```

may fail to return a complete snapshot of the current usage.

To prevent this, some centralized piece of code needs to calculate the `collection_timestamp` so that it is shared by the data obtained for all database objects at this reporting interval.

To reproduce:

1. Apply patch:

```
diff --git a/misc/python/materialize/mzcompose/services.py b/misc/python/materialize/mzcompose/services.py
index 5615451c1..a9a367265 100644
--- a/misc/python/materialize/mzcompose/services.py
+++ b/misc/python/materialize/mzcompose/services.py
@@ -62,6 +62,7 @@ class Materialized(Service):
                 "MZ_SOFT_ASSERTIONS=1",
                 "MZ_UNSAFE_MODE=1",
                 "MZ_EXPERIMENTAL=1",
+                "MZ_STORAGE_USAGE_COLLECTION_INTERVAL=60s",
                 f"MZ_PERSIST_BLOB_URL={persist_blob_url}",
                 f"MZ_ORCHESTRATOR_PROCESSDATA_DIRECTORY={data_directory}",
                 # Please think twice before forwarding additional environment
```

2. Run:
```
cd test/zippy
 ./mzcompose run default --scenario KafkaSources --actions 100
```
to get some sources in, even though the same result should be achievable with any other framework or test.

**Comment by jkosh44** [comment]
The issue is that we determine the timestamp of each shard-id (which each correspond to a single row in `mz_storage_usage`) independently:
https://github.com/MaterializeInc/materialize/blob/cd9de90c07a1765f7b31c77666205fc99b9d596f/src/adapter/src/coord/message_handler.rs#L110-L124
https://github.com/MaterializeInc/materialize/blob/cd9de90c07a1765f7b31c77666205fc99b9d596f/src/adapter/src/catalog.rs#L4424-L4429
https://github.com/MaterializeInc/materialize/blob/cd9de90c07a1765f7b31c77666205fc99b9d596f/src/adapter/src/catalog.rs#L1186-L1201

So each row in the same update can be a couple milli-seconds off from each other. The fix would be to use a single timestamp for all updates. I'll have a PR shortly.

**Comment by chaas** [comment]
Thanks for the quick fix @jkosh44 !
