### ISSUE TITLE
persist: stop depending on read leases for correctness

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#15511]
### Feature request

Currently, a persist shard allows any number of leased ReadHandles. Each of these gets a capability on the shard's since. Concretely, this means that if handle A downgrades the since, it doesn't affect handle B. The shard-global since only downgrades to some point once all registered ReadHandles have downgraded since to that point. This structure makes it easy to independently reason about ReadHandles usage e.g. a new dataflow spins up and temporarily holds back the since to its as_of while it reads a snapshot of the (unboundedly large) full shard contents. To prevent a process crash (no polite expiration of the ReadHandle) from permanently wedging the shard-global since, each of these handles are given a (relatively long 15m) time-based lease. If we haven't heard from a ReadHandle in that long, we remove it from the registration, potentially allowing the since to jump forward.

This has already led to several production bugs.

In practice, some MZ ReadHandles are more "critical" than others. Each storage collection's data shard has a ReadHandle maintained in the storage controller on environmentd that holds back the since. Ditto the remap shard has one in the reclock operator. If any of those lose their lease (e.g. miss heartbeats or, more insidious, the process takes too long to restart) the since might advance out from underneath it in a way that is not easily recoverable. OTOH, if the same thing happens to a ReadHandle in some persist_source operator, we can always crash the dataflow and restart (not ideal, but recoverable).

We've been playing whack-a-mole with lease timeouts as they pop up, but I feel strongly that this is not a viable long-term strategy. Even with vigorous testing and release qualification, it will always be possible that a bug of this sort might sneak into prod. Once we become a source of truth, this would be a fairly catastrophic failing of our correctness and durability promises to the customer.

As a result, I propose that we alter persist so that these two types of ReadHandle usages are modeled in two different ways in the code. The "critical" usages will no longer use time based leases. The "non-critical" usages can continue to be time-based leases because that's much simpler to use when we can (we'll keep playing whack-a-mole with them and also figure out better testing strategies, I feel okay about this).

So if we don't have time-based leases for "critical" ReadHandles, then how do we prevent a process crash from permanently wedging the shard-global since? Luckily, the controller has already solved this for us with the "epoch" fencing token.

From Joe

> The stash contains a field called "epoch". When a new Coordinator starts up it increments that field by 1. A Coordinator will include its own epoch in every stash transaction. If the Coordinator's epoch doesn't match the epoch in the stash, then the transaction is rejected.

We will similarly use the same epoch token for "critical" ReadHandles. Each downgrade_since on a "critical" ReadHandle will include the epoch. If this is the largest epoch ever seen (alternative: most recently registered epoch), we'll process the downgrade_since. If it's not, then we know this process is no longer in charge and leave the ReadHandle's since alone.

This is not a new idea! Aljoscha already has a PR implementing this from a while ago: #13347. However, since then, we've evolved our thinking a bit (or at least I've evolved my own opinions). That PR gives a shard only one since capability and makes it fenced. I think it's useful/easier to continue to have an arbitrary number of time-leased since capabilities for things like persist_source.

One question I have here is whether each shard should get one "critical" ReadHandle or an arbitrary number of them:
- As far as I know, there is exactly one "critical" ReadHandle per shard.
- But if we commit to this and it's wrong, or becomes wrong in the future, we'll have to change how we do this handling again, which will likely involve an annoying/subtle migration of durable persist state. OTOH, it's possible that more care needs to be taken by persist users if we support more than one (e.g. the storage controller will have to be very careful to durably write down the ReaderId of the critical handle before registering with it, otherwise it might crash at the wrong time and permanently wedge the shard-global since).

**Comment by danhhz** [comment]
Another concern I have is, if the remap shard's "critical" handle lives in storaged, if we'll have the right epoch plumbed there. But I think I heard we might be moving that to the storage controller?

**Comment by frankmcsherry** [comment]
Some thoughts: 

1. It isn't immediately clear that you even need the fencing. We should probably do it, but there could just be a handle that can compare and swap the `since`, held only by `environmentd`. Fencing may help us stay sane, but I think a good thing happens even if they just fight on it (e.g. either call can advance, and if either call does advance then no reason that call couldn't have succeeded in the first place).
2. I think in terms of the path from here to there, we can start to structure all other uses of existing read handles to not rely on their capability. This is what was missing around #13347: that the users of the read handles need to update their behavior first. Compute is on the way to doing that (@teskje is working on this presently) and .. idk about storage we should check. We probably need to train `storaged` to communicate back the `since` requirements to the controller, which is then the source of truth.

**Comment by frankmcsherry** [comment]
> But I think I heard we might be moving that to the storage controller?

I think this is the only sane place to have them. From compute experience, at least, if individual `storaged`s are able to zip `since` bounds forward, they can invalidate them for other replicas, forcing crashes due to tight races rather than allowing the controller to dictate when replicas are up/down.

**Comment by danhhz** [comment]
> 1. It isn't immediately clear that you even need the fencing. We should probably do it, but there could just be a handle that can compare and swap the since, held only by environmentd. Fencing may help us stay sane, but I think a good thing happens even if they just fight on it (e.g. either call can advance, and if either call does advance then no reason that call couldn't have succeeded in the first place).

compare_and_swap_since also sounds lovely (and I like not having to bake the mz-specific epoch into the persist abstraction), great idea! I think we still need to decide on one vs many of these though. e.g. compare_and_swap lets us deal with two environmentds fighting each other, but will we ever have a case where some second part of the code will also want a "critical" handle? i.e. how confidant are we that the controllers will always be the one-and-only "critical" handle?

> 2. I think in terms of the path from here to there, we can start to structure all other uses of existing read handles to not rely on their capability. This is what was missing around https://github.com/MaterializeInc/materialize/pull/13347: that the users of the read handles need to update their behavior first. Compute is on the way to doing that (@teskje is working on this presently) and .. idk about storage we should check. We probably need to train storaged to communicate back the since requirements to the controller, which is then the source of truth.

one of the nice things about keeping the old handles for persist_source is that we can break this up into two steps: (1) add the ability to register a "critical" handle (2) swap out the various current ReadHandles that are "critical" with this new thing. even if we want to always have exactly one of these, it's pretty easy to start with zero-or-one and move to always-one once we finish upgrading the usages. in particular, I very much don't want to be personally on the hook for fixing up all the usages of persist.

**Comment by bkirwi** [comment]
Generally enthusiastic!

I really like the idea of having multiple critical handles. For example, when working on the Kafka sink we've had a few bugs where we allowed the since to change between when we chose the as-of and when the sink actually started up. With critical handles, you can imagine a flow like:
- `environmentd` mints a new handle for a sink at sink-creation time.
- The handle (or its corresponding reader id, or however we want to think of it) is passed to storaged over the grpc connection when it starts.
- `storaged` uses that handle to read from the sunk collection, downgrading it as it makes progress.
- When the sink is deleted and `storaged` is shut down, `environmentd` drops the handle.

Cuts out the risk of time-of-check/time-of-use bugs, and generally seems amenable to more "local" reasoning. (eg. after the handoff, the storage controller doesn't need to do anything to ensure the sink's handle / as-of remains valid.)

**Comment by frankmcsherry** [comment]
Tagging in @jkosh44 as a stakeholder on the possibility that "critical read handles" might be mutated only by `compare_and_swap` behavior, with consequences for concurrent `envd` execution. We discussed briefly, and 1. it seems not insurmountable, but 2. there is some non-trivial guidance to provide for the storage controller to make sure that two controllers don't fight over who is in charge of the handle. I think we only concluded for (2.) that it is non-trivial, not that we knew the extent of the guidance (e.g. in bootstrap, the controller should accept races and retry, out of bootstrap conflicts should result in shutdown, life is hard if there are two concurrent processes in bootstrap at the same time).

**Comment by bkirwi** [comment]
A few storage folks were discussing the read handle advancement today, re #15822, and none of us could offhand come up with a situation where we needed fencing on the since. In the usages we were aware of, it would be safe to implement `downgrade` as taking the `join` of the current and updated since, converging instead of conflicting.

I don't think I understand the full set of concerns we hav with environmentd, though. Is there some reason I'm missing why it's important for the read handles to fence each other out in that situation?

**Comment by jkosh44** [comment]
I think the join approach should work. I was mainly concerned about multiple Coordinators entering some form of live-lock while attempting to compare and append the `since` at the same time.

The one assumption this makes is that Coordinators with a lower epoch will always use lower timestamps to update the `since`. For example, if some old Coordinator tries to update `since` to `Timestamp::MAX`, then it will be bad. I believe that this is a valid assumption, I just wanted to point that out.

**Comment by pH14** [comment]
Another possibility we've been discussing is letting the client pass along an opaque token when registering and downgrading the `since` of critical handles. The `compare_and_swap` operation can then be on `(token, since_update)`. If the operation fails because the token doesn't match, the caller can decide how to resolve the conflict.

In the cases mentioned so far, it could play out like this:

For guarding against concurrent `envd`, the token could be the `envd` epoch. If `compare_and_swap(epoch, since)` fails, the caller can then determine if it was because the persisted epoch is more recent than what it has, and then the rogue `envd` panics when it learns it's out-of-date.

In the sink case, where it sounds like fencing out processes is not needed, the token can be hardcoded to something simple (e.g. 0), and so the usage reduces down to a `compare_and_swap` on the `since` values like what has already been discussed.

**Comment by jkosh44** [comment]
I think the fencing token would also work well for concurrent `envd`s. New Coordinators will initialize read policies on all objects as part of bootstrapping, which will end up fencing the `since`s of all objects.

**Comment by jkosh44** [comment]
Also I just remembered another concern we had with the original compare and swap approach. It doesn't seem like it's part of the current design, but I just wanted to write it down, so we have a record of it. One of the proposals was that we do a compare and swap on the `since`s, and if it failed the Coord would step down. The problem was that an older Coord could end up fencing out a newer Coord during bootstrap.
The fix would have been to only retry the compare and append in bootstrap, but if more than one Coord are in bootstrap at the same time, then it's unclear who should win.

**Comment by bkirwi** [comment]
> In the sink case, where it sounds like fencing out processes is not needed, the token can be hardcoded to something simple (e.g. 0), and so the usage reduces down to a compare_and_swap on the since values like what has already been discussed.

IIUC the CAS-with-token approach is strictly more expressive than the join approach I was asking about -- it's possible to emulate the latter with the former -- so that ought to work. (cf. last-write-wins, which would risk lost progress.)

> In the sink case, where it sounds like fencing out processes is not needed

FWIW, the intuition for why this is the case is that the sink only reports progress to the read handle (today via the storage controller, potentially soon with this new mechanism) once durable progress has been made in the underlying computation, and that computation is itself monotonic. (We never "unpublish" messages, etc.) So if one storaged reports that we no longer need data before time `t0`, and another reports that we no longer need data from before `t1 > t0`, we can confidently record `t1`.

One reason I'm bullish about the join idea is that this seems like a very natural property that should generalize to most (all?) other parts of materialize, since timely's whole schtick is this monotonic progression of time and we're pretty faithful to those semantics. But I'm definitely not familiar with enough corners to be authoritative there!

**Comment by danhhz** [comment]
We'll still have remap shards and sink sharkds after 15961, but I'm comfortable closing this after 15961 lands and splitting those out into separate issues

**Comment by danhhz** [comment]
The controller usage merged! \o/

That's enough validation of the interface that I'm comfortable closing the persist part of this work (this issue), and splitting out the remaining places we want to use this into separate issues:

- remap #11908
- sinks #16120
