### ISSUE TITLE
Link new SSH Bastion integration guide to SSH Connection

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#15652]
### Documentation request

Let's reference the new, kick-ass [SSH Integration Guide](https://materialize.com/docs/integrations/postgres-bastion/) from the [SSH Section](https://materialize.com/docs/sql/create-connection/#postgres-ssh) of the Postgres source.

**Comment by morsapaes** [comment]
To make sure that we do all the work in one sit (rather than patch and forget), this issue should also cover:

#### 1. Adding an `Authentication` section in the Postgres source connector page
  This once existed for Kafka, and was removed when we added reference documentation for `CREATE CONNECTION` in [#13876](https://github.com/MaterializeInc/materialize/pull/13876/commits/7f820b6a971df104609ce458c4bd12e5e9a65bab). This section should clearly state what the options are, starting with SSH tunneling (then PrivateLink, in the near future, for AWS-managed PostgreSQL instances).
  
#### 2. Adding an SSH Bastion connection example under `Examples`
  So users don't have to jump back and forth between the source connector page and `CREATE CONNECTION`. We should start thinking about converting examples that are used cross-page to shortcodes, to reduce the maintenance burden of updating them.

#### 3. Adding an `Authentication` section in the relevant integration guides
  This will be the same for every guide, so it may be . It's likely that we could turn whatever we come up with in **1.** into a shortcode, and just use that. As a first step, we can just add the examples to each page manually, but should open a follow-up issue to revise examples and reduce repetition where possible!
