### ISSUE TITLE
Kafka Sources: support accessing metadata in dataflows

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1577]
related to #1562, there are 

1. timestamp
2. key
3. kafka record header

that we should expose.

Details forthcoming

**Comment by benesch** [comment]
FWIW I don't think these columns should be hidden. Hidden columns are confusing. Let's just make Kafka sources have these columns by default, and you can project them away if you don't want them.

**Comment by benesch** [comment]
I've updated the title to be less prescriptive about the correct solution to this problem.

**Comment by frankmcsherry** [comment]
From discussion: It would be great to get a read on the intended uses of these columns. 

In particular, uses of the columns seem like they will be very hard to *retract*, as future statements about changes will have different timestamps and offsets, for sure (no worries about key, I suppose).

In differential, "timestamp" is a thing that the system knows how to compact as it advances, but importantly it doesn't get presented upwards as data for reasons like this (you could produce some data that aren't retractable, because future changes wouldn't happen at the same timestamp).

If the uses are "I want to write `SELECT *, max(timestamp), max(offset) FROM ..` we should work on finding better idioms for presenting this information. Some of it would be easy to present through logging sources, if meant purely for diagnostics. If there are other uses, we should get in and try and figure out if Materialize will do the right thing with the data, or just head down some unstable path towards memory exhaustion.

**Comment by wangandi** [comment]
`source::kafka` now returns the key of any message, though for non-upsert envelopes, the key quickly gets dropped.

**Comment by benesch** [comment]
Jotting down a musing from Slack: the best design for including message headers that I can think of involves adding a new column called `headers` to Kafka sources that has type `map[text => text]`.

**Comment by quodlibetor** [comment]
> In particular, uses of the columns seem like they will be very hard to retract, as future statements about changes will have different timestamps and offsets, for sure (no worries about key, I suppose).

As mentioned in the comment that linked here: we are now doing this retraction-tracking work in both UPSERT envelopes that we support. It would be reasonable (although perhaps memory-intensive) to do the same thing for metadata values.

**Comment by frankmcsherry** [comment]
It shouldn't be that memory intensive if we push down the linear operators that do demand. This is already in place for vanilla upsert, and would just require committing to the set and location of fields. Please don't do this at the moment though, as I have two other PRs that currently touch thing stuff and already conflit with each other.

**Comment by elindsey** [comment]
Note that Kafka keys are now accessible (https://github.com/MaterializeInc/materialize/issues/5863), this task is only for the additional work of making Kafka metadata accessible.

**Comment by elindsey** [comment]
Some recent discussion that motivates including offset as well: https://materializeinc.slack.com/archives/C02CB7L4TCG/p1629317802004100

I think that brings the current list of things we'd like to make accessible in the dataflow to:
- kafka timestamp
- kafka offset
- record header

**Comment by frankmcsherry** [comment]
The use case for `offset` might plausibly also want the part identifier too. They didn't ask for that, but their query would only make sense in a single-part setting, unless they also had the part id (more complicated when there are multiple parts, but they could plausibly make sense of it).

**Comment by elindsey** [comment]
Oh good call, offset ordering only makes sense in the context of a partition - updated

**Comment by benesch** [comment]
Do we have a design for this? Adding these columns by default is backwards incompatible since the column names might clash with existing column names. Also might cause a serious increase in memory usage for topics with tons of small records.

**Comment by elindsey** [comment]
There was a design doc for exposing keys (the aspect of Kafka metadata that was broken off from this task and implemented) https://github.com/MaterializeInc/materialize/pull/6661

I suspect we'll need another doc building on that one to determine if these should all be opt-in like keys and what that syntax should look like, or if we think these are valuable enough to break backwards compatibility and include by default.

**Comment by benesch** [comment]
Got it, thanks! We can consider designs too where existing Kafka sources don't get the new columns added automatically, but new Kafka sources do.

**Comment by quodlibetor** [comment]
I've added a design doc (#8239) for all the non-headers fields. I believe that headers is a bit worse than described in https://github.com/MaterializeInc/materialize/issues/1577#issuecomment-729332533 : their values aren't guaranteed to be text, and there is no type information provided with them. So if a user adds a field like `attempt_num` as a java long we'll just the 8-byte array, which would be nonsense if interpreted as a string.

There are obviously solutions to that, but they require more work and there are multiple reasonable designs. @nmeagan11 have we gotten active requests for access to headers in addition to the metadata?

Also, @benesch you said in https://github.com/MaterializeInc/materialize/issues/2268#issuecomment-614984781 that metadata columns make retractions impossible, is that specifically for Debezium data, or is there a more general issue?

**Comment by frankmcsherry** [comment]
I think retractions become possible (in some circumstances) by projecting away the metadata that prevent the retraction. For example, projecting away the offset, so that a retraction at a different offset can cancel the original. This makes the most sense in the "raw bytes" setting, rather than "value added" settings like DBZ, where they would need to understand to project away this information too (simply glomming it on to the results of DBZ updates are unlikely to produce correct results).

One thing this calls out though is that the persistence folks likely need some help in projecting away this information too. "Source persistence" with the additional metadata fields will not compact down to anything small, unless they have permission to project away the metadata. It's not clear where this permission would come from, as we cannot currently create sources with a non-optional view attached to them (internally we do this, but afaik there isn't a user-facing mechanism for this).

**Comment by quodlibetor** [comment]
After speaking with @nmeagan11 and @krishmanoh2 we've confirmed that right now we have no one who has ever asked for access to headers.

**Comment by mxcoder** [comment]
Sorry, I just found out this issue, but please consider this as a +1 on being able to read headers. We use them for tracing and record metadata (eg. record is valid or not) and it would be super helpful if we could use these fields in the queries.

**Comment by quodlibetor** [comment]
Thanks @mxcoder! I've created the above issue to track the work, feel free to comment on or react to it. If you wouldn't mind speaking a bit to your use case for headers I think it would help us prioritize or test them.

In particular I'm curious if your use of headers comes from some framework, and separately what use cases having access to them from materialize would enable.

**Comment by mxcoder** [comment]
Thanks @quodlibetor . Absolutely, so in our case we're building stream processors that consumes, joins, validates and produces kafka messages from CDCs. 
The message payload is protobuf serialized, so we decided to use headers to include metadata about the process, for example a boolean flag that says if the record is valid/complete or not, this enables us to do quick filtering to sink or log the results in subsequent subsystems without requiring to do the protobuf deserialization.

Right now we're leveraging the Python Faust Stream-processing library for most of our processors, but we're looking into other tooling, but thinking to leverage headers in the same or similar way.

As we're using kafka to transmit CDCs, the messages are keyed and materialize is allowing us to build quick in-memory representations whenever we do variations to our processors, allowing to do for end to end QA.

Our team would really like to use materialize to be able to do a query like this:
```
SELECT COUNT(*)
FROM mv_table_1
WHERE headers.is_valid IS TRUE
```

**Comment by quodlibetor** [comment]
Awesome, thanks!

**Comment by quodlibetor** [comment]
Actually, I have a follow-up question:

Are you rolling your own custom CDC format, or are you using Debezium or Materialize format CDC messages?

**Comment by mxcoder** [comment]
I believe we're using the binary upsert envelope, which we relied on after using Debezium in the past. Basically our messages are always keyed and either tombstones or some binary data (protobuf), the sources I'm defining as:
```
CREATE SOURCE IF NOT EXISTS source_A FROM ... ENVELOPE UPSERT;
```

**Comment by quodlibetor** [comment]
Great, thanks, that helps!
