### ISSUE TITLE
Postgres Sources May Try to Snapshot Unrelated Table

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15889]
### What version of Materialize are you using?

Cloud

### How did you install Materialize?

Materialize Cloud

### What is the issue?

A user had a publication with multiple tables, but only specified one in their `FOR TABLES (...)` statement. However, the user was encountered errors of the form `ERROR:  Source error: X: failed during initialization, must be dropped and recreated: missing data for column`. Once they created a publication containing only the one table they wanted to read into Materialize, they no longer saw the error.

This signifies two possible bugs:
1. It looks like we're trying to snapshot an unrelated table.
2. It looks like there is a bug in our `COPY` parser.

Additional context can be found [here](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1667495704567519?thread_ts=1667325066.316519&cid=C01CFKM1QRF).

**Comment by benesch** [comment]
cc @petrosagg

**Comment by petrosagg** [comment]
Yeah this is a leftover from how the source was previously working where it also produced a snapshot for all the tables because the `CREATE VIEWS` statement came afterwards and so we didn't know what tables were of interest when the ingestion started.

Previously we were just storing text encoded columns so this never failed but now that we attempt to fully process the tables it does if an unrelated table has unsupported columns. I think @sploiselle is working on making the source only snapshot and stream the requested tables
