### ISSUE TITLE
Checking `REPLICA IDENTITY` When Connecting a Postgres Source

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15890]
### Feature request

As described in https://github.com/MaterializeInc/materialize/issues/15874, we must set `REPLICA IDENTITY` to `FULL` for Postgres sources. It would be nice if users had a way to test for the current value of `REPLICA IDENTITY` when creating a connection to speed up development.

**Comment by materializesupport** [comment]
@nmeagan11 Expand on this a bit to share a potential ideal path:

- When a customer first connects to Materialize, we perform the check on their behalf
    - If the check passes (`REPLICA IDENTITY` is set to `FULL`), continue as we normally would
    - If the check fails, alert|notify the customer and provide three options:
        - Attempt to set `REPLICA IDENTITY` to `FULL` on each table, or;
        - Self-serve (allow the customer to make the changes manually);
        - Ignore

**Comment by benesch** [comment]
The credentials Materialize is using to connect to the upstream database may not have the permission to change the `REPLICA IDENTITY` to `FULL`. Also the idea of Materialize having the ability to do that at all, even if it's fully under the user's control, is disconcerting. Recommend we start with providing guidance to the user about how they can fix this upstream.

Not entirely clear on the semantics of "Ignore", but I think we should to hard reject any tables that do not have `REPLICA IDENTITY FULL`. Even though it technically works with an `INSERT` only table, that's not a common use case at all, and it's too much of a footgun to have lying around IMO.

**Comment by morsapaes** [comment]
> Also the idea of Materialize having the ability to do that at all, even if it's fully under the user's control, is disconcerting. Recommend we start with providing guidance to the user about how they can fix this upstream.

💯 

I struggle to see any path of action in this issue beyond making it clearer in the documentation that configuring the upstream database for logical replication is a pre-requisite, and pointing users to that section in the PostgreSQL CDC guide. Our error message is very clear, and even provides users with the `oid` for the table that is misconfigured:

```nofmt
ERROR: ERROR:  Source error: u396: Old row missing from replication stream for table with OID = 21454. Did you forget to set REPLICA IDENTITY to FULL for your table?
```

From here, it should be straightforward to check the `REPLICA IDENTITY` for the table using:

```sql
default=# SELECT CASE relreplident
          WHEN 'd' THEN 'default'
          WHEN 'n' THEN 'nothing'
          WHEN 'f' THEN 'full'
          WHEN 'i' THEN 'index'
       END AS replica_identity
FROM pg_class
WHERE oid = '21454'::regclass::oid;

 replica_identity
------------------
 full
(1 row)
```

We've discussed in the past how prescriptive we should be IWRT database configuration (see [this](https://materializeinc.slack.com/archives/C03SXGGEN3Y/p1665274893139709) and [this](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1663781789239589) threads), and the general consensus is that evaluating and testing the impact of enabling logical replication should be on the user (also because there aren't "one-size-fits-all" recommendations).
