### ISSUE TITLE
Print `count(*)` as `count(*)` in EXPLAIN

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#15939]
### What version of Materialize are you using?

3c9876d6bbaa2da26283f2abb6e8f90bd52192d7

### How did you install Materialize?

Built from source

### What is the issue?

`count(*)` is currently printed as `count(true)` in EXPLAIN, which might be confusing for users. It even confused me: I just saw it in an EXPLAIN output, and totally thought that the `true` is coming from some optimizer-internal struct that has a field about nulls or distincts or whatever, and the true is the value of that field. Then I dived into the code, and it turned out that it's just the _expression_ of the count: https://github.com/MaterializeInc/materialize/blob/87975f95be8a25381f2ebbac7d1eddf3dba3d75a/src/sql/src/func.rs#L2465

**Comment by aalexandrov** [comment]
I'm not sure this falls within the "D-good first issue" tag. The referenced line indicates that `count(*)` is equated to `count(true)` in the planning phase, so I don't think that differentiating between these two cases will be a trivial task.

One will first need to:

1. introduce a dedicated `HirScalarExpr` encoding to be derived from `count(*)`, and then
2. ensure that the new encoding as operationally handled the same way as `count(true)` throughout the codebase.

This will also only show solve the problem for `EXPLAIN RAW PLAN`. The same exercise will have to be done for `MirScalarExpr` in order to cover most of the optimization stages.

**Comment by ggevay** [comment]
I was just thinking to print `count(*)` even if the user wrote `count(true)`. First, the user probably won't write `count(true)`, and even if someone does write that, they probably won't have a problem with realizing that `count(*)` is the same thing.

**Comment by tokenrove** [comment]
I noticed that Postgres encodes this as an aggregate function with no arguments (https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/parser/gram.y;h=9384214942aad42c191c1b8269eac0b68f0372aa;hb=HEAD#l8364) which might be a nicer encoding of this idea, although a quick glance at how to represent that here doesn't make it look much better; I guess we do treat it as nullary earlier on.  It seems like the least invasive change might be to introduce an additional AggregateFunc, CountAsterisk/CountCardinality.  I opened a PR that just prints `count(true)` as `count(*)` as an incremental improvement, though I'm not so happy with it yet.
