### ISSUE TITLE
long running load generator source uses an atrocious amount of space

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#15968]
### What version of Materialize are you using?

 v0.30.1 (85b85f6d1)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

I created a 3xsmall load generator source: `CREATE SOURCE ticker FROM LOAD GENERATOR COUNTER (TICK INTERVAL = '1s') WITH (SIZE = '3xsmall')` on Oct 13th, and it has been running since.

I wanted to see how much storage it was using, so I looked at `mz_storage_usage`.

The most recent collection:
```
materialize=> select * from mz_storage_usage where object_id = 'u2' order by collection_timestamp desc limit 1;
 object_id | size_bytes  |   collection_timestamp    
-----------+-------------+---------------------------
 u2        | 50616082861 | 2022-11-08 16:21:49.54+00
```

That's ~50GB.

But more troublingly, we have `601` collections total:
```
materialize=> select count(*) from mz_storage_usage where object_id = 'u2';
 count 
-------
   601
```

And if we look at the last 5, we see that the space usage is cumulative:

```
materialize=> select * from mz_storage_usage where object_id = 'u2' order by collection_timestamp desc limit 5;
 object_id | size_bytes  |    collection_timestamp    
-----------+-------------+----------------------------
 u2        | 50616082861 | 2022-11-08 16:21:49.54+00
 u2        | 50415130779 | 2022-11-08 15:18:10.088+00
 u2        | 50219840784 | 2022-11-08 14:14:51.775+00
 u2        | 50030808427 | 2022-11-08 13:11:32.115+00
 u2        | 49836166524 | 2022-11-08 12:08:10.943+00
```

If we sum up `size_bytes`, we get ~9.3 terabytes of used space, a terrible, horrible, no good, very bad size:

```
materialize=> select sum(size_bytes) from mz_storage_usage where object_id = 'u2';      sum      
---------------
 9305163124549
```

What do I want? Not that^.

**Comment by rjnn** [comment]
there are two separate issues here:

1. first, feels like perhaps a persist compaction bug. why do we have 600 extra collections hanging around without being garbage collected? That's a 186x blowup for what could, in principle be 50gb cc @danhhz 

2. the load generator source surely should be able to more effectively store the seconds. Right now its storing a kilobyte of data each second, according to my back-of-the-envelope. cc @mjibson

**Comment by rjnn** [comment]
Edit: scratch (1) above. According to [Frank](https://github.com/MaterializeInc/materialize/issues/15962#issuecomment-1307546138), I'm reading the table wrong.

(2) still feels like an atrocious amount of space used.

**Comment by danhhz** [comment]
Looking at arjun's env in us-east-1, I see two storage pods over the last 30 days. One of them (u19) wrote something once and never again, and the other (u2) seems to have been writing a very small amount of data more or less constantly, so I'm going to guess that's the one running the counter demo source. All of the following analysis depends on that assumption being correct.

According to persist metrics, this node ingesting a relatively flat 74 B/s of "goodput" (data being handed to persist). This also includes timestamp and diff information, so I'd expect 8 (the counter val) + 8 (a length of the encoded row) + 8 (the ts) + 8 (the diff) = 32. No idea where the discrepancy between 32 and 74 is coming from (do we have remap shards for the demo sources? maybe it's from the ProtoRow encoding?)

However, it is writing ~ 2KiB/s of actual bytes to s3 on behalf of this ingestion. The difference between 74 B/s and 2 KiB/s is pure overhead of the persist columnar format. I recall measuring that more in the range of a few hundred B/s at some point, so that's surprising. (Note that we don't pay this overhead if there is _zero_ data, the counter demo source of one value per second is exactly the worst case for this format overhead.)

The difference between 2 KiB/s * 2246400s (4.6 GiB) and whatever actual values we're seeing in the billing table (~50GiB) is, as far as I know, going to fall into 2 buckets:
- The first is data we're intentionally holding onto because there is a "seqno hold" (imagine some snapshot working though a very large persist shard, we can't do it with sinces for Reasons). There is a bug that is being tracked as part of the [persist fires umbrella issue](https://github.com/MaterializeInc/materialize/issues/15638) where these [seqno holds are getting unexpectedly stuck](https://github.com/MaterializeInc/materialize/issues/15937). It's under active investigation.
- The second is blobs that we've accidentally leaked. This can happen in the course of normal operation if we get a crash at just the wrong time. We've done 90% of the work needed on a tool to discover and clean up these leaked blobs, but it got put on hold until we finish up on the persist fires issue.
- (Plus maybe I'm not thinking of something or there's an unknown bug)

There's definitely a few things to look into here.

**Comment by benesch** [comment]
This has been improved in a couple ways. Seqnos no longer get stuck. The usage we bill users for no longer includes leaked blobs. Compaction is still not perfect, but improvements are tracked in https://github.com/MaterializeInc/materialize/issues/16607.
