### ISSUE TITLE
Add various metadata to compute pods as k8s labels

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#15994]
### Feature request

We want at least:

* The name of the service (e.g. "compute")
* A human-readable name corresponding to the cluster, replica, and process (e.g. "default.r1:0"), or perhaps separate labels for each
* The T-shirt size of the replica (e.g. "xlarge")

@hlburak , @jpepin

**Comment by benesch** [comment]
Can you say more about why we want this? Is it just to make debugging easier in k9s? Or is it helpful in feeding into Grafana?

**Comment by umanwizard** [comment]
@jpepin suggested this, I believe to make it easier to group things in Grafana.

Is there a good reason _not_ to have it?

**Comment by benesch** [comment]
> Is there a good reason not to have it?

Separation of concerns, mostly!

For example, the human-readable name for a replica is not an inherent property of the compute pod, and might change due to an `ALTER ... RENAME`. I don't think we support that today, but we'll want to eventually. So attaching the human-readable name to the pod is a recipe for staleness and confusion.

The service name is already available as the `environmentd.materialize.cloud/namespace` label, which is either "compute" or "storage".

I think adding the t-shirt size as a label (or annotation?) would make sense, as that _is_ an inherent property of the pod. Changing the size of a compute replica (or storage host) requires creating new pods. So 👍🏽 from me on that.

**Comment by umanwizard** [comment]
We could always change the labels if you change the human-readable name...

Alternatively, we could surface the human-readable name to Materialize GlobalID mapping in one of the exported SQL queries -- @jpepin do you think that would be good enough? (Probably hard to use that for filtering in Grafana, but at least you could have all the info in one place)

**Comment by benesch** [comment]
> We could always change the labels if you change the human-readable name...

Not without restarting the pod.

> Alternatively, we could surface the human-readable name to Materialize GlobalID mapping in one of the exported SQL queries -- @jpepin do you think that would be good enough? (Probably hard to use that for filtering in Grafana, but at least you could have all the info in one place)

Yes, that's my strong recommendation. We've got https://github.com/MaterializeInc/cloud/issues/4521 tracking that.

**Comment by jpepin** [comment]
@umanwizard - Do we have a way to get this information now?

**Comment by umanwizard** [comment]
Yes, we should have this information since #4521 has been completed.
