### ISSUE TITLE
`ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017068 which is ahead of now, 1668084008628` after restarting MZ

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16007]
### What version of Materialize are you using?

9c189a419f70c0aac0113b5bbed90352b55b6da5

### How did you install Materialize?

Docker image

### What is the issue?

The Zippy tests restart Mz. After that second, I think, restart, the log has several of the log lines below.

To reproduce:

1.

```
cd test/zippy
./mzcompose down -v ; ./mzcompose run default --scenario=KafkaSources 
```

2. In another window, repeatedly run:
```
docker logs zippy-materialized-1 2>&1 | grep ERROR
```
until the log lines appear.

### Relevant log output

```source
environmentd: 2022-11-10T12:40:08.628914Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017068 which is ahead of now, 1668084008628
environmentd: 2022-11-10T12:40:08.650687Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017069 which is ahead of now, 1668084008650
environmentd: 2022-11-10T12:40:08.671811Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017070 which is ahead of now, 1668084008671
environmentd: 2022-11-10T12:40:08.708988Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017071 which is ahead of now, 1668084008708
environmentd: 2022-11-10T12:40:08.730461Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017072 which is ahead of now, 1668084008730
environmentd: 2022-11-10T12:40:08.752634Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017073 which is ahead of now, 1668084008752
environmentd: 2022-11-10T12:40:08.785149Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017074 which is ahead of now, 1668084008785
environmentd: 2022-11-10T12:40:08.815320Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017075 which is ahead of now, 1668084008815
environmentd: 2022-11-10T12:40:08.829883Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017077 which is ahead of now, 1668084008829
environmentd: 2022-11-10T12:40:08.829926Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017076 which is ahead of now, 1668084008829
```

**Comment by jkosh44** [comment]
Ok so this is actually expected. When we restart environmentd, the new Coordinator needs to grab a new timestamp range which needs to be a certain interval larger than the previous range and is often ahead of real time. The situation will quickly fix itself because the new timestamp is usually only a couple of seconds ahead of real time. So maybe this log line is a bit misleading.

However, this does make me realize about a potential problem. If the Coordinator is in a restart loop, then continuously getting a new range can push the global timestamp far ahead of real time. This will result in permanent damage because the global timestamp is persisted in the stash.

I propose the following solution:

1. On startup, if the Coordinator's new timestamp is `N` times larger than real time, then the Coordinator will block and wait until that timestamp is less than `N` times larger than real time.
2. Only log the error shown above in this issue if the timestamp is `N` times larger than real time.

For `N` I think a good value would be 10.

This has the following nice properties:
- The Coordinator can rapidly reboot up to `N` times without having block at all. This is especially nice for tests that may rapidly reboot the Coordinator and not want to wait around.
- The permanent damage to the global timestamp is limited to `N` times the timestamp range interval.
- We only log timestamp issues if things have gotten really bad.

@mjibson I'm curious if you have any thoughts on this.

**Comment by mjibson** [comment]
What's the current timestamp range interval? I looked around a bit but couldn't find it. This is the thing where a coord leases out timestamp ranges? Or is it writing to stash anytime an oracle advances its timestamp?

What would happen if coord always waited on startup for now to catch up?

**Comment by jkosh44** [comment]
> What's the current timestamp range interval?

15 seconds: https://github.com/MaterializeInc/materialize/blob/dc9132c5658eabe5848fee2abd5de8515e39f86b/src/adapter/src/coord/timeline.rs#L138-L145

So we'd allow a Coordinator to get 150 seconds ahead of real-time before we start to worry.

>  This is the thing where a coord leases out timestamp ranges?

Yes, the Coordinator will allocate a range of timestamps equal to 15 seconds at a time.

> Or is it writing to stash anytime an oracle advances its timestamp?

No, it's only writing to stash if it tries to advance it's timestamp to a value outside of it's current allocated range.

> What would happen if coord always waited on startup for now to catch up?

It would be correct, but it would potentially slow down start up and tests that perform rapid restarts. The common case is for a new coord to allocate a timestamp range ahead of now, since now is likely in the old Coord's allocated range. This usually corrects itself after a little more than 15 seconds because the global timestamp can move much slower than real time.

**Comment by jkosh44** [comment]
I spoke to @mjibson about this. We agree with the general approach but had the following notes:
- When the Coordinator starts up and the global timestamp is larger than the system clock by any amount, then writes to tables and Strict Serializable reads will all block until the system clock catches up to the global timestamp. So for any N greater than 0, we allow the system to start up in a state where certain actions are not immediately available.
- Avoiding blocking during start up in the common case is still a nice property to have because
  - It makes certain tests faster.
  - Users can still perform DDL, non-Strict Serializable reads, and `SET`.
- Therefore we are going to do the following:
  - Decrease timestamp range interval from 15 seconds to 5 seconds.
  - Limit N to 1 or 2.
  - Only log an error if the global timestamp gets N * timestamp_range_interval ahead of the system clock.
