### ISSUE TITLE
environmentd: investigate why respond immediately is not deterministic in test_explain_timestamp_table

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#16115]
We expect `test_explain_timestamp_table` to have deterministic respond immediately. Currently if a sleep is injected before the explain it can change.

**Comment by jkosh44** [comment]
I looked into this, apparently this has to do with how persist initializes the upper of tables. The upper is initialized to 0 and then quickly, but asynchronously, advances to a non-zero value. If the upper is 0 then it can't respond immediately. If it's non-zero then it can respond immediately.

I'm not sure if initializing to 0 is expected or not, but it seems reasonable that it's up to the Coordinator to advance the table to the proper initial upper. What's confusing to me is how creating the table doesn't advance the upper to the current global timestamp. When we create the table we perform a system table write which advances all tables to the current global timestamp. I debugged this test and confirmed that group commit successfully executes an append including the new table with a non-zero timestamp. Then after the append has completed we run `EXPLAIN TIMESTAMP` which gets the upper of the table from the storage controller, which responds with 0.

So it seems like to me that there's a race condition going on somewhere.

Also it would probably be ideal if we could just specify an initial upper when creating the table.

**Comment by jkosh44** [comment]
Oh I figured it out, this is actually pretty interesting. We perform the system write at the end of `catalog_transact`, but before we actually create the table. So the table exists in the catalog but not in STORAGE/persist. So the system write attempts to advance the new table to the current global timestamp, but fails because the table doesn't exist. Somehow this doesn't fail group commit or the other writes, and doesn't even log an error.
