### ISSUE TITLE
Subscribe and peek hang if the cluster it's running on is dropped

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#16121]
### What version of Materialize are you using?

platform

### How did you install Materialize?

Built from source

#### Subscribe

In one `psql` shell, run:

```
COPY (SUBSCRIBE (SELECT * FROM mz_cluster_replicas)) TO STDOUT;
```

In another, run:

```
DROP CLUSTER default;
```

Note that the subscribe will hang forever and not show any errors.

#### Peek [Resolved]

In one `psql` shell, run:

```
CREATE TABLE t (); 
SELECT * FROM t AS OF 18446744073709551615;
```

In another, run:

```
DROP CLUSTER default;
```

Note that the peek will hang forever and not show any errors.
Note this specific reproduction only works in unsafe mode. It is possible but more difficult to reproduce without `AS OF`.

**Comment by benesch** [comment]
I believe closely related to #6303.

**Comment by teskje** [comment]
It looks like to solve this we could either:
* Have the compute controller emit a `SubscribeResponse::DroppedAt` for each subscribe active on a compute instance that is dropped.
* Have adapter cancel any subscribe active on a compute instance that it is about to drop/has just dropped.

@jkosh44 Do you have a preference?

**Comment by jkosh44** [comment]
I have a very very slight preference for the second option. 

One note I have is that it may be a bad UX that we allow someone to drop a cluster if there are active `SUBSCRIBE`s. Should we require they include `CASCADE` in these scenarios or some other keyword to make sure they understand that they are cancelling someone else's query?

**Comment by teskje** [comment]
Oh, that's a good though! We should probably inform the dropping user that he is cancelling active subscribes, and inform the subscribing user that their subscribe was canceled because the cluster was dropped.

**Comment by jkosh44** [comment]
I just updated this to include peeks to since they suffer from the exact same issue.

**Comment by jkosh44** [comment]
This issue also exists if you drop the queried object. For example:
In one `psql` shell, run:

```
CREATE TABLE t (); 
SELECT * FROM t AS OF 18446744073709551615;
```

In another, run:

```
DROP TABLE t;
```

https://github.com/MaterializeInc/materialize/pull/17476 Fixes this specific version of the issue with SUBSCRIBE.

**Comment by jkosh44** [comment]
I think this also probably includes dropping cluster replicas if your query targets a specific replica?

**Comment by teskje** [comment]
> I think this also probably includes dropping cluster replicas if your query targets a specific replica?

This should not happen! When the replica targeted by a subscribe goes away, the subscribe returns an error, and then I think the coordinator drops it.

**Comment by jkosh44** [comment]
The peek side of this issue has been resolved. The subscribe side is a little more tricky, and I have a hunch it's do to the complexity described in https://github.com/MaterializeInc/materialize/issues/21081.

I tried to take the same approach for clusters that I took for peeks, but the subscribe still hangs. My guess is that the subscribe is waiting for a message from the cluster that the subscribe has been removed, but the cluster is removed before it sends this message.

**Comment by teskje** [comment]
I've put up https://github.com/MaterializeInc/materialize/pull/24545 to at least move subscribes from the compute controller and emit a NOTICE when the target cluster is dropped.

That's not a full solution, as @jkosh44 points out. The subscribe doesn't get terminated on pgwire, and I think the assumption that this is because adapter is waiting for compute `SubscribeResponses` that never arrive is spot on. Once the cluster has been dropped in the compute controller, no responses can ever arrive from that cluster again.

Do we know why adapter doesn't remove cancelled subscribes immediately but waits for the compute controller to return some response? Is it because the adapter logic would be confused by responses for subscribes that it doesn't know about anymore? I think that can be solved by making the compute controller stop returning responses for subscribes that have been dropped by adapter. The fact that it currently does is a smell IMO.

**Comment by benesch** [comment]
> Do we know why adapter doesn't remove cancelled subscribes immediately but waits for the compute controller to return some response? Is it because the adapter logic would be confused by responses for subscribes that it doesn't know about anymore?

The reason it was originally implemented as such was to ensure that the end-to-end tests of cancellation verified that the underlying dataflow was actually aborted. Suppose adapter were to return immediately, before waiting for the underlying dataflow to abort. It would then be easy for a regression to slip in where the dataflow was not actually canceled, but the test still passed—e.g., because adapter stopped sending the cancellation request to compute, or because compute stopped processing the request correctly. 

These days, there's enough observability of the dataflows in compute that I think you could write a test like...

1. Issue a `SUBSCRIBE`.
2. Observe from another session that a dataflow has been created to handle the `SUBSCRIBE`.
3. Cancel the `SUBSCRIBE`.
4. Observe that the original session is ready for another query.
5. Observe that the dataflow for the `SUBSCRIBE` is cleaned up within a reasonable of time

...and then you'd be free to refactor the cancellation protocol without fear of regressions in the actual cancellation of the underlying dataflows.
