### ISSUE TITLE
SCHEMA REGISTRY URL is interpreted as just hostname:port; path path is lost

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16131]
### What version of Materialize are you using?

v0.33.0-dev (74f61e77a)

### How did you install Materialize?

Docker image

### What is the issue?

This works even though the schema registry URL is grossly invalid:

```
> CREATE TABLE t1 (f1 INTEGER);

> CREATE CONNECTION kafka_conn
  TO KAFKA (BROKER '${testdrive.kafka-addr}');

> CREATE CONNECTION IF NOT EXISTS csr_conn TO CONFLUENT SCHEMA REGISTRY (
    URL '${testdrive.schema-registry-url}/FOO/BAR/BAZ'
  );

> CREATE SINK kafka_sink FROM t1
  INTO KAFKA CONNECTION kafka_conn (TOPIC 'testdrive-kafka-sink-${testdrive.seed}')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
  ENVELOPE DEBEZIUM;
```

An examination of the log of the schema registry shows that none of the HTTP requests made by Mz to the schema registry include `FOO/BAR/BAZ`, which tells me that we strip it on the Mz site by interpreting `URL` as just a hostname + port , rather than the full-blown URL it actually is.

**Comment by mjibson** [comment]
This is indeed [by design](https://github.com/MaterializeInc/materialize/blob/a8da0b1746a4d9dcade4a4a0effa8601c9596f58/src/ccsr/src/client.rs#L47), but I'm not sure what that design is because I don't know anything about schema registry or its URLs. Am investigating if we're doing something wrong or should error if a user specifies a path.
