### ISSUE TITLE
Catchable panics

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#16236]
In Materialize, we currently abort on panics. The main reason for doing so is that we want to avoid scenarios where tasks/threads could panic and quit without the rest of the code relying on these tasks/threads noticing, which could leave us in a silently broken state. Instead, we abort the whole process and give it a chance to restart in an orderly fashion.

The issue with always aborting is that we cannot catch panics even when it would be safe and desirable to do so. For example, we know that the optimizer is prone to panicking due to bugs and it is unrealistic to find and fix them all in the near term. There are other independent tasks running inside environmentd (like the k8s service watcher, and soon the configuration updater) that can be easily restarted if they crash, so it would be desirable to do so instead of making the fate of environmentd depend on them.

We should try to find an alternative way of handling panics that a) allows the usage of `catch_unwind` to intentionally catch and handle panics and b) aborts the whole process if a panic is not handled.

### Related Discussions

* Catching panics is one way of better isolating query processing: https://github.com/MaterializeInc/materialize/issues/16217
* Discussion about panic handling [in Slack](https://materializeinc.slack.com/archives/CMH6PG4CW/p1668770406693129)

**Comment by benesch** [comment]
Thanks very much for filing this one, @teskje!

Just to add a bit more color on this point:

> For example, we know that the optimizer is prone to panicking due to bugs and it is unrealistic to find and fix them all in the near term.

On a few occasions, folks have asked "why not ban `unwrap` and `expect` in the optimizer, and require code to always return errors instead of panicking?" The most compelling argument against this for me is slicing. Are we also willing to ban slicing, and require that all code use `.get` instead? Enforcing that mandate would make for very unidiomatic code.

----

Here's a quick sketch of how we could fix this. We introduce a thread-local variable called `ABORT_ON_PANIC`. This variable defaults to true.  The panic hook installed by `mz_ore::process::set_abort_on_panic` is adapted to _only_ abort if `ABORT_ON_PANIC` is true. Then we introduce a custom `catch_unwind` function that sets `ABORT_ON_PANIC` to `false` and _then_ calls the normal `catch_unwind` function.

We can do something similar for futures.

**Comment by benesch** [comment]
Tried this out in https://github.com/MaterializeInc/materialize/pull/16263, and it worked!
