### ISSUE TITLE
Add support for fuzzing SQL

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#16255]
> At the moment, the test framework for SQL uses a static set of queries. Fuzzing is a technique to expand the set of queries we test against using a grammar-driven approach.

Ideally we'd use coverage-directed fuzzing but basic grammar-based fuzzing has already been revealing crashes.  The goal here is specifically to stress planning and optimization.

Eventually we'd
- generate examples in nightly, curating a record of what's been tried, [like hypothesis does](https://hypothesis.readthedocs.io/en/latest/database.html);
- run against our recorded examples on each PR, without generating new ones
but until we have persistence of results, we should at least do this in nightly.

sqlsmith was used in the past (#8497) which used a service; we will instead do our fuzzing with tools that run locally to the CI.  See also #1722, #3818 (fuzzing Avro), #602 (fuzzing wire protocols) -- the latter two would be good cases for something like honggfuzz or afl.

**Comment by tokenrove** [comment]
Note that @philip-stoev has an elaborate grammar-driven generator he uses in a more directed fashion.  We discussed also using it for this but I think we felt using a separate tool was probably appropriate here; I want to be able to have fine control over generated depth and so on.  I have been using a modified copy of dharma for my own fuzzing, after a bit of evaluation of grammarinator, but I'm going to look at whether sqlsmith would be better to restore.

**Comment by tokenrove** [comment]
Grammarinator is nice because it takes an ANTLR grammar: https://github.com/renatahodovan/grammarinator and has some interesting mutation and transformation tools.

However, dharma is much simpler: https://blog.mozilla.org/security/2015/06/29/dharma/ (I'm using [this fork](https://github.com/posidron/dharma)) and with one small modification (below), is quite convenient for quickly throwing together queries.

```patch
diff --git a/dharma/core/extensions.py b/dharma/core/extensions.py
index 2635129..2260ecf 100644
--- a/dharma/core/extensions.py
+++ b/dharma/core/extensions.py
@@ -78,10 +78,10 @@ class MetaChoice:
     def __init__(self, choices, parent):
         self.parent = parent
         self.choices = choices
-        self.choices = [x.strip() for x in self.choices.split(",")]
+        self.choices = [self.parent.machine.parse_xrefs(x.strip()) for x in self.choices.split(",")]
 
     def generate(self, state):
-        return random.choice(self.choices)
+        return self.parent.eval(random.choice(self.choices), state)
 
 
 class MetaRange:
```

Note that neither of these tools have a feature I consider essential, which is attributing the grammar with distributions or conditions, but I used them as it was easy to get started with them here.  I thought about resurrecting an old ABNF-directed fuzzer that I wrote ages ago that had this feature, but that was more work than I wanted to put in for this presently.  At least they both support controlling the depth, which is also essential for grammar-driven fuzzing.

[Building Fast Fuzzers](https://arxiv.org/pdf/1911.07707.pdf) is a good read not only for the main focus of the paper, but as a quick survey of some existing tools.

**Comment by def-** [comment]
I have been exploring a bit here, trying out [SQLsmith](https://github.com/def-/sqlsmith/tree/materialize), [SQLancer](https://github.com/def-/sqlancer) and found some issues. Both are not yet in fully running states. SQLsmith needs to limit the number of joins to make sure we don't run into [Loss of Interactivity](https://github.com/MaterializeInc/materialize/issues/17652) issues, SQLancer needs more [catalog items](https://github.com/MaterializeInc/materialize/issues/17739) to generate interesting queries and has some remaining errors (for example too many tables).

**Comment by def-** [comment]
Added two subitems now: https://github.com/MaterializeInc/materialize/issues/17864 & https://github.com/MaterializeInc/materialize/issues/17865

**Comment by def-** [comment]
I'd say we have enough fuzzing for now (SQLsmith, SQLancer, RQG, parallel-workload, output-consistency, data-ingest). There might always be more to be done, but we can create new issues for more concrete items then.
