### ISSUE TITLE
`mz-environmentd.test.pgwire` is flaky

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#16294]
### Buildkite link

https://buildkite.com/materialize/tests/builds/45749#0184ba44-d518-4a58-98c3-a0ca514d0104

### Relevant log output

```source
mz-environmentd.test.pgwire
thread panicked while panicking. aborting.
/usr/local/bin/run-tests: line 23:  2505 Aborted                 "/tests/$binary" -Z unstable-options --format json --report-time
{"type":"suite","event":"started","test_count":11}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_arrays"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_bind_params"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_conn_startup"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_conn_user"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_copy"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_partial_read"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_pgtest"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_pgtest_mz"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_read_many_rows"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_record_types"}
{"type":"test","event":"started","name":"mz-environmentd::test::pgwire::test_simple_query_no_hang"}
{"type":"test","name":"mz-environmentd::test::pgwire::test_partial_read","event":"ok","exec_time":9.065248586}
{"type":"test","name":"mz-environmentd::test::pgwire::test_simple_query_no_hang","event":"ok","exec_time":9.403725741}
{"type":"test","name":"mz-environmentd::test::pgwire::test_conn_user","event":"ok","exec_time":9.456056777}
```

### Additional thoughts

It passed on the retry.

**Comment by ggevay** [comment]
And one more instance: https://buildkite.com/materialize/tests/builds/45752#0184ba91-19b9-491c-bf51-f9be0777a7d8

**Comment by teskje** [comment]
Another one: https://buildkite.com/materialize/tests/builds/45693#0184a9da-7f06-4764-a4c2-ee77fc8acc3f

**Comment by jkosh44** [comment]
I've been able to reproduce this locally and have narrowed it down to the following 3 tests:
- test_bind_params
- test_conn_startup
- test_record_types

**Comment by jkosh44** [comment]
There seems to be some panic that happens when executing this `EXPLAIN`: https://github.com/MaterializeInc/materialize/blob/b2751bb71c852a7f3cce16bb9640bf7e5b96c44f/src/environmentd/tests/pgwire.rs#L54-L57

Then when aborting and dropping everything this line panics: https://github.com/MaterializeInc/materialize/blob/b2751bb71c852a7f3cce16bb9640bf7e5b96c44f/src/adapter/src/util.rs#L150

Attached is a binary and core dump of an example panic.

**Comment by jkosh44** [comment]
If we convert the `panic` to an `error` log, then we can see that the original panic comes from here: 
https://github.com/MaterializeInc/materialize/blob/21a989b10aba5330ea3a3859ad4dffead939c743/src/adapter/src/coord/sequencer.rs#L2672-L2676

**Comment by jkosh44** [comment]
@aalexandrov I'm not really familiar with the EXPLAIN code, any idea why that might panic?

**Comment by jkosh44** [comment]
Unfortunately even after converting this `panic` into an `error`: https://github.com/MaterializeInc/materialize/blob/b2751bb71c852a7f3cce16bb9640bf7e5b96c44f/src/adapter/src/util.rs#L150

There's yet another `thread panicked while panicking. aborting.`. This panic is located here: https://github.com/MaterializeInc/materialize/blob/9e641d3a09f3c281cb6be09d3818d9677838eb4d/src/ore/src/thread.rs#L26-L30

Which comes from dropping this object: https://github.com/MaterializeInc/materialize/blob/9e641d3a09f3c281cb6be09d3818d9677838eb4d/src/adapter/src/client.rs#L36-L45

Which comes from dropping this object: 
https://github.com/MaterializeInc/materialize/blob/9e641d3a09f3c281cb6be09d3818d9677838eb4d/src/environmentd/src/lib.rs#L363-L371

Which comes from dropping this object:
https://github.com/MaterializeInc/materialize/blob/9e641d3a09f3c281cb6be09d3818d9677838eb4d/src/environmentd/tests/util.rs#L262-L267

**Comment by jkosh44** [comment]
@aalexandrov I'm going to pass this one to you, since it looks like it's an issue with explain. I added some print statements around the failure. I'm not sure what the `trace` variable is, but it's missing an entry that's expected to exist. What's interesting is that even when the test passes, the contents of that list can vary wildly. Note I found this easier to repro when running multiple tests at once, but that might have just been a placibo effect.

Here's some examples of some passing tests:

- `trace: [TraceEntry { instant: Instant { tv_sec: 16457, tv_nsec: 437314734 }, duration: 10.719183ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16457, tv_nsec: 437615988 }, duration: 19.57002ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }]`
- `trace: [TraceEntry { instant: Instant { tv_sec: 16560, tv_nsec: 104442239 }, duration: 17.511151ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16560, tv_nsec: 104729183 }, duration: 27.97201ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }]`
- `trace: [TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 973903964 }, duration: 71.006µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 973946167 }, duration: 113.209µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 973976187 }, duration: 143.229µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 973991134 }, duration: 158.176µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974005929 }, duration: 172.971µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974030481 }, duration: 197.523µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974045101 }, duration: 212.143µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974059230 }, duration: 226.272µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974074886 }, duration: 241.928µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974097646 }, duration: 264.688µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974115636 }, duration: 282.678µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974135099 }, duration: 302.141µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974153172 }, duration: 320.214µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974170135 }, duration: 337.177µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974187469 }, duration: 354.511µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974205996 }, duration: 373.038µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974223526 }, duration: 390.568µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974284599 }, duration: 451.641µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974304488 }, duration: 471.53µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974318699 }, duration: 485.741µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974338007 }, duration: 505.049µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974402064 }, duration: 569.106µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974443801 }, duration: 610.843µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974464911 }, duration: 631.953µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974502725 }, duration: 669.767µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974542342 }, duration: 709.384µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974562430 }, duration: 729.472µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974576725 }, duration: 743.767µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974590861 }, duration: 757.903µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974605051 }, duration: 772.093µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974620955 }, duration: 787.997µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974636703 }, duration: 803.745µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974653600 }, duration: 820.642µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974705668 }, duration: 872.71µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974726073 }, duration: 893.115µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974746902 }, duration: 913.944µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974765819 }, duration: 932.861µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974783269 }, duration: 950.311µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974801545 }, duration: 968.587µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974821295 }, duration: 988.337µs, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974856631 }, duration: 1.023673ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974916156 }, duration: 1.083198ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974937591 }, duration: 1.104633ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974955033 }, duration: 1.122075ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 974977897 }, duration: 1.144939ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975013338 }, duration: 1.18038ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975034669 }, duration: 1.201711ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975088876 }, duration: 1.255918ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975168483 }, duration: 1.335525ms, path: "optimize/global", plan: "Return\n  Get l1\nWith\n  cte l1 =\n    Map (42)\n      Get l0\n  cte l0 =\n    Constant\n      - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975216997 }, duration: 1.384039ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975233203 }, duration: 1.400245ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975246897 }, duration: 1.413939ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975258323 }, duration: 1.425365ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975270080 }, duration: 1.437122ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975281526 }, duration: 1.448568ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975292770 }, duration: 1.459812ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975303765 }, duration: 1.470807ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975315355 }, duration: 1.482397ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975326698 }, duration: 1.49374ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975338162 }, duration: 1.505204ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975350655 }, duration: 1.517697ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975362396 }, duration: 1.529438ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975373471 }, duration: 1.540513ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975384768 }, duration: 1.55181ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975396458 }, duration: 1.5635ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975436171 }, duration: 1.603213ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975508476 }, duration: 1.675518ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975529006 }, duration: 1.696048ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975538604 }, duration: 1.705646ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975551066 }, duration: 1.718108ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975562314 }, duration: 1.729061ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975597801 }, duration: 1.764548ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975662974 }, duration: 1.829721ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975692361 }, duration: 1.859403ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975742805 }, duration: 1.909847ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975764812 }, duration: 1.931854ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975776896 }, duration: 1.943938ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975787142 }, duration: 1.954184ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975797383 }, duration: 1.964425ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975807101 }, duration: 1.974143ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975880342 }, duration: 2.047384ms, path: "optimize/global", plan: "Return\n  Get l0\nWith\n  cte l0 =\n    Constant\n      - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 975969751 }, duration: 2.136793ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976040133 }, duration: 2.207175ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976057281 }, duration: 2.224323ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976077461 }, duration: 2.244503ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976097089 }, duration: 2.263836ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976212123 }, duration: 2.379165ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976264560 }, duration: 2.431602ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976308212 }, duration: 2.475254ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976377872 }, duration: 2.544914ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976428167 }, duration: 2.595209ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976484704 }, duration: 2.651746ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976513144 }, duration: 2.680186ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976577770 }, duration: 2.744812ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976651723 }, duration: 2.818765ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976764931 }, duration: 2.931973ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976816438 }, duration: 2.98348ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976875071 }, duration: 3.042113ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976902670 }, duration: 3.069712ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 976933576 }, duration: 3.100618ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977126165 }, duration: 3.293207ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977264672 }, duration: 3.431714ms, path: "optimize/global", plan: "Return\n  Get l1\nWith\n  cte l1 =\n    Map (42)\n      Get l0\n  cte l0 =\n    Constant\n      - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977351767 }, duration: 3.518809ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977388675 }, duration: 3.555717ms, path: "optimize/global", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977501619 }, duration: 3.668661ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977585722 }, duration: 3.752764ms, path: "optimize/global", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977623936 }, duration: 3.790683ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977686939 }, duration: 3.853686ms, path: "optimize/global", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 977981589 }, duration: 6.672549ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }]\nentry: Some(TraceEntry { instant: Instant { tv_sec: 16813, tv_nsec: 973903964 }, duration: 71.006µs, path: "optimize/global", plan: "Constant\n  - (42)\n" })\nrow: Some(Row{[String("Constant\n  - (42)\n")]`

and a failed test:
`trace: [TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 426609587 }, duration: 16.233509ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 426683933 }, duration: 16.307855ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 426804524 }, duration: 16.428446ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 428191960 }, duration: 17.815882ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 428339282 }, duration: 17.9638ms, path: "optimize", plan: "Constant\n  - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 429816367 }, duration: 19.440885ms, path: "optimize", plan: "Map (42)\n  Constant\n    - ()\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 430555071 }, duration: 20.178993ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 430626204 }, duration: 20.250126ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }, TraceEntry { instant: Instant { tv_sec: 16587, tv_nsec: 430807618 }, duration: 20.430759ms, path: "optimize", plan: "Explained Query (fast path):\n  Constant\n    - (42)\n" }]`

**Comment by aalexandrov** [comment]
I've changed the `panic` to an `Internal` adapter error in #16350. Let's hope this reveals more about the failing test. I'm not sure how this could happen, as I'm not mutating shared state and the produced trace _should always contain_ the paths for the stages that can be individually selected (`raw`, `decorrelated`, `optimized`, `physical`).

**Comment by aalexandrov** [comment]
@jkosh44 how do I reproduce this locally? Simply running

```rust
bin/cargo-test -p mz-environmentd
```

is not enough.

**Comment by jkosh44** [comment]
@aalexandrov You may also want to re-enable the test since I disabled it.

It was very difficult to repro, but here's how I managed to do it.
1. Delete all tests in `mz-environmentd::tests::pgwire` except for `test_bind_params`, `test_conn_startup`, and `test_record_types`.
2. Run `cargo build --bin storaged --bin computed`
3. Repeatedly run `cargo test --test pgwire -- -Z unstable-options --format json --report-time --show-output` until the error happens. Usually it takes no more than 20 runs.
For whatever reason I was getting more luck reproducing the error when I'd run the compiled test directly, for example `/home/joe/materialize/target/debug/deps/pgwire-159bc79ad5f15415 -Z unstable-options --format json --report-time --show-output`, but I think that was just random chance.
Also don't forget to set the env var `POSTGRES_URL=postgres://joe@%2Fvar%2Frun%2Fpostgresql`

**Comment by aalexandrov** [comment]
I'll dig deeper tomorrow and report findings here.

**Comment by aalexandrov** [comment]
The trace of the failed test has multiple identical entries with `path: "optimize"` (in fact, no other paths exist in that trace). In theory the path should be unique per entry, and the entry with `optimize/global` should also be there.

**Comment by lluki** [comment]
Still happening:
 * https://buildkite.com/materialize/tests/builds/48871
 * https://buildkite.com/materialize/tests/builds/48845

**Comment by jkosh44** [comment]
> Still happening:
> 
>     * https://buildkite.com/materialize/tests/builds/48871
> 
>     * https://buildkite.com/materialize/tests/builds/48845

I'm not entirely sure that it's the same issue. It might just be happening in the same test. I'm also seeing this same flakiness is `test_auth_base()`.

**Comment by mjibson** [comment]
This repos locally when run in a loop. Looking.
