### ISSUE TITLE
"Invalid data in source, saw retractions" after UPDATE on a table with index , serializable isolation level

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16507]
### What version of Materialize are you using?

 v0.34.0-dev (b7ca2f48c)

### How did you install Materialize?

Docker image

### What is the issue?

```
materialize=> CREATE TABLE t1( x INTEGER);
materialize=> SET transaction_isolation=serializable;
INSERT INTO t1 VALUES(1);
CREATE INDEX t1i1 ON t1(x);
UPDATE t1 SET x=1;
UPDATE t1 SET x=2;
UPDATE t1 SET x=3;
UPDATE t1 SET x=4;
SELECT * FROM t1;
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Int32(1)]
```

Note that `UPDATE t1 SET x=1;` above returned `UPDATE 0`, which means no rows were updated. I guess this is expected given that we have no "read your writes" guarantee. However, the table should not become borked. Dropping the index does not cause the error to go away.

**Comment by jkosh44** [comment]
Good find @philip-stoev, here's what's going on. A read then write plan works in the following way:
1. Read the contents of a table at a selected timestamp.
2. Append retractions for all rows read.
3. Append new values.

(In reality step 2 and 3 happens in a single step).

This issue was happening due to the use of serializable mode and an index. There's some race conditions here, so it wouldn't always fail in the exact same way, but this is roughly what was happening.
1. Insert 1 at `ts`. The table looks like:
```
| value       | time | diff |
| ----------- | ---- | ---- |
| 1           | ts   | + 1  |
```
2. Read from the index at `ts`, which returns 1. Retract 1 and insert 1 at `ts+1`. The table looks like:
```
| value       | time   | diff |
| ----------- | ----   | ---- |
| 1           | ts     | + 1  |
| 1           | ts+1   | - 1  |
| 1           | ts+1   | + 1  |
```
3. Read from the index at `ts+1`, which returns 1. Retract 1 and insert 2 at `ts+2`. The table looks like:
```
| value       | time   | diff |
| ----------- | ----   | ---- |
| 1           | ts     | + 1  |
| 1           | ts+1   | - 1  |
| 1           | ts+1   | + 1  |
| 1           | ts+2   | - 1  |
| 2           | ts+2   | + 1  |
```
3. Read from the index at `ts+1` (**here's the error**), which returns 1. Retract 1 and insert 3 at `ts+3`. The table looks like:
```
| value       | time   | diff |
| ----------- | ----   | ---- |
| 1           | ts     | + 1  |
| 1           | ts+1   | - 1  |
| 1           | ts+1   | + 1  |
| 1           | ts+2   | - 1  |
| 2           | ts+2   | + 1  |
| 1           | ts+3   | - 1  |
| 3           | ts+3   | + 1  |
```

The table is now permanently corrupted because the last retraction doesn't correspond to any row.

The fix is to select a read timestamp as if it was strict serializable for all read then write queries.
