### ISSUE TITLE
mz_source|sink_status uses a window function

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16584]
### What version of Materialize are you using?

v0.35.0-dev

### How did you install Materialize?

Docker image

### What is the issue?

As @frankmcsherry observed, the mz_source|sink views use a window function. This may not be very performant and there is a general drive to disallow window functions until they are fixed.

The canonical way to do the same calulcation would be to use the `SELECT DISTINCT ON (col_name) ... FROM table_name ORDER BY timestamp_col DESC` which will result in an optimized dataflow.

@bkirwi FYI

**Comment by ggevay** [comment]
I think this is not actually fixed by #16593. `MZ_SOURCE_STATUS` still has the `row_number() over`, which will be slow with the current window function implementation: Row numbers for entire window partitions (the entire histories) will be recalculated from scratch for every new record.

This would be solved eventually by https://github.com/MaterializeInc/materialize/issues/16758, but that might take some time, so this might cause CPU usage issues already before that. So if it's not hard to change the view definition from `ROW_NUMBER` to a `DISTINCT ON`, then maybe we should do that.

**Comment by bkirwi** [comment]
@ggevay - the idea was that the replacements for the row-number views had landed in the PR you linked, but we kept the old names/definitions around to give the frontend some time to migrate. Removing the old definitions is tracked under https://github.com/MaterializeInc/materialize/issues/16550.

If you like we can keep this open in the meantime for visibility too, but there's not really any more work to be done outside of the other ticket.

**Comment by ggevay** [comment]
Ah, sorry, I should have more carefully read that PR to see that you are planning to delete the old ones. Ok, so if the old ones will be deleted within a few weeks, then it should be fine.

**Comment by bkirwi** [comment]
All good! I should have left a comment in the code so they didn't raise concerns for those grepping around.
