### ISSUE TITLE
storage: `mz_storage_shards` grew to 60GB

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16712]
### What version of Materialize are you using?

v0.36.2

### How did you install Materialize?

Materialize Cloud

### What is the issue?

In @ggnall's environment (77d74a2a-c087-4510-9fde-7e3d4fbd0672), the `mz_storage_shards` shard (s7c8fd8f9-e079-4a8d-9bd9-019ad0a76a78) grew to an encoded size of 68GB:

![image](https://user-images.githubusercontent.com/882976/208281647-92391aec-1781-4cd4-806c-e91fd3520d8b.png)

The bug seems to have occurred somewhere around 11/26 (v0.32.3). I really have no idea what was going on there. It's not entirely clear to me whether compaction was falling way behind, or we were failing to emit incorrect retractions while trying to truncate the shard during `environmentd` startup. 

In any case, `environmentd` became unable to recover even when given all the RAM available on a single machine, as the `truncate_managed_collection` requires loading up the entire `mz_storage_shard` persist shard into memory.

I was able to nurse the environment back to health by triggering a manual compaction. This brought the size of the shard down by half (??), at which point `environmentd` was able to start up after using 100GB (!!) of memory:

![image](https://user-images.githubusercontent.com/882976/208281742-1f698d47-ac28-4295-91b2-3f8ae2b0b63f.png)

The reported size of the shard is still ridiculously large. The shard appears to have correct contents, in that `SELECT count(*) FROM mz_internal.mz_storage_shards` returns "48". But there's a batch with 200 (!!) parts, each 183MB in size, that accounts for the bulk of the 36GB in the shard. Here's a dump of the current consensus state: https://gist.github.com/benesch/4bbca89a90e038daef19146220e37350. I also dumped the contents of one of those 183MB batch parts: https://www.dropbox.com/s/dr5as86aulyy8f4/graham-stuck-shard.txt?dl=0.

Lots and lots of this in the batch part:

```
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": 1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": -1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": 1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": -1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": 1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": -1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": 1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": -1
    },
    {
      "k": "\"\\n1\\n\\u{6}B\\u{4}s291\\n'B%s7cc688ac-970e-4325-95e8-51438b43ec4b\"",
      "v": "\"\"",
      "t": 1669643489770,
      "d": 1
    },
```

I'm really not sure what to make of this. Why wouldn't those updates get consolidated? How'd we accumulate so many of them in the first place?

cc @sploiselle @danhhz @pH14

**Comment by pH14** [comment]
Whoa! This one is strange... immediate thoughts:

1. We currently have a bug/omission where we _do not_ consolidate user batch parts by default. So direct ingestion from a source or table writes do not necessarily consolidate out updates unless they were done at a higher level than persist. https://github.com/MaterializeInc/materialize/pull/16602 will fix this, but in the mean time, it's not impossible for a batch to contain unconsolidated updates. (A batch written by compaction should always consolidate though!)
2. The massive batch listed in the consensus state gist most likely did not originate from compaction, as it has `since=[0]` which is always true for user batches, but only true for compaction batches if the shard's `since` is `[0]`, which is not true here.

Crucially, I think these two points imply that the call into `persist` really did try to link in that much data at once (!), rather than it being some artifact of compaction gone wrong or other persist-internal behavior. I'm not familiar with `mz_storage_shards`, but where I'd want to follow up on next is investigating any way a large batch could be written into this table

**Comment by danhhz** [comment]
> I'm not familiar with mz_storage_shards, but where I'd want to follow up on next is investigating any way a large batch could be written into this table

@sploiselle Any ideas here?

**Comment by sploiselle** [comment]
"Managed collections'" reconciliation strategy is what we're seeing here: we
truncate the shard' contents on boot, and then reinsert everything we want to be
there.

I was naively under the impression that this use case wouldn't be pathological
(i.e. would consolidate to 0), but it's very possible this would blow up like
we're seeing, espcially in the face of crash looping. That's my hunch.

I'm working on a refactor that instead performs reconciliation in memory to
alleviate this issue.

**Comment by danhhz** [comment]
Oh, good to know! It should be far less of an issue after 16602 (I thought we were consolidating user batches all along, but had mis-remembered)
