### ISSUE TITLE
Wrong results: Data doubly ingested in sink if environment ID has changed

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16902]
### What version of Materialize are you using?

v0.37

### How did you install Materialize?

Docker image

### What is the issue?

The Checks-based upgrade test is failing with an error where data is **sometimes** being ingested twice in a sink.

The reason is that the Mz version being upgraded from is being started with 

```
MZ_ENVIRONMENT_ID=mzcompose-test-00000000-0000-0000-0000-000000000000-0
```

but the version being upgraded to is started with:

```
MZ_ENVIRONMENT_ID=docker-mzcompose-00000000-0000-0000-0000-000000000000-0
```

This is due to this special case in `services.py` : 
```
        if not environment_id:
            # TODO(benesch): remove this special case when v0.39 ships, since
            # the legacy upgrade tests will no longer be testing v0.37.1.
            if image is not None and image.endswith("v0.37.1"):
                environment_id = "mzcompose-test-00000000-0000-0000-0000-000000000000-0"
            else:
                environment_id = DEFAULT_MZ_ENVIRONMENT_ID
```

Normally, we would chalk this to be a "testing only-issue that would never happen in the cloud because environment IDs are stable there", and I could apply a kludge on the testing side but I would like to elevate this to an actual product bug:

- this has already happened once in testing. The first time this happened it was a panic, now it is duplicate data, which is worse.
- do we have any protections in the cloud against the environment Ids not changing **ever**? What if we decide to change the naming scheme for the regions of a certain provider? What if we decide to migrate all of our tenants from some problematic region of one cloud provider to a better region?
- if the environment IDs do change, there is no error or panic on startup. Instead, everything seems to work. Except that sinks will **sometimes** have **duplicate data**.
- we have made customer's Kafka's installations yet another store of state data for the Mz system. This is on top of K8s, CRDB, S3 and possibly others. That is too much of a state to get right every time, especially since there is no reconciliation procedure when the state diverges.

I think this should work as follows:
- environment  ID should be stored in CRDB
- environmentd should refuse to start if the enviroment ID from the command line and the one in CRDB do not match.

**Comment by bkirwi** [comment]
> do we have any protections in the cloud against the environment Ids not changing ever?

I can't speak to this precisely... but I do believe that changing the environment id would be catastrophic for many parts of the product, not just the progress topic. (eg. the CRDB and S3 paths both depend on the environment ID in prod.)

> I think this should work as follows: [...]

This sounds reasonable to me. I assume the stash is the right place for this sort of thing? Not the expert there.

We previously explored storing the progress topic name in the source definition as part of purification. If we did so, the Kafka stuff would at least be protected from changing environments. (And while lots of stuff depends on the env id, only the progress topic uses the argument to the binary so far AFAICT.) May be worth revisiting that at some point too.

> we have made customer's Kafka's installations yet another store of state data for the Mz system.

This I think is unavoidable. There's just no way to avoid sinking duplicate data without keeping state in the destination system. (We need some way to determine whether data has been written or not when we hit an indeterminate error like a network timeout.)

But this doesn't contradict your main point of course -- the information needed to decide what progress topic to look at isn't stored in Kafka, but in K8s or some test equivalent, and that's the bit that's causing us trouble.

**Comment by benesch** [comment]
> Normally, we would chalk this to be a "testing only-issue that would never happen in the cloud because environment IDs are stable there", and I could apply a kludge on the testing side.

That is still my recommendation, yeah. I would not consider it a kludge, but rather making the test a closer representation of our production environment. 

IMO, part of the problem here is that we are testing upgrades using mzcompose rather than Kubernetes. I know we've talked about this in the past, and some amount of manually driving the upgrade process in tests sounded inevitable in order to inject the kind of faults you want to inject, but it also means that we're not testing orchestration that's representative of what we're running in cloud.

> What if we decide to change the naming scheme for the regions of a certain provider? What if we decide to migrate all of our tenants from some problematic region of one cloud provider to a better region?

Not sure you'll find this convincing, but we'll never do either of those things. The naming scheme is forever. We'll have to find some way to evolve it if necessary that doesn't involve changing the names of existing regions. We also simply _cannot_ migrate tenants from one region to another; they are specifically purchasing Materialize in the named region, and there may be compliance issues with migrating them to a different reason.

That said, we could certainly stand to have a bit more protection against changing environment IDs. I'm not sure that this should be `environmentd`'s responsibility to enforce, though. It might be more natural to perform this enforcement in the cloud test suite, for example: https://github.com/MaterializeInc/cloud/blob/1e14c04ac92d55c2a337807b955ce8fbe4a7df26/k8s_tests/assert/environmentd_statefulset.yaml#L63-L64.

**Comment by benesch** [comment]
https://github.com/MaterializeInc/materialize/pull/16925 should fix the specific presentation of this problem on main.

**Comment by philip-stoev** [comment]
> IMO, part of the problem here is that we are testing upgrades using mzcompose rather than Kubernetes. 

For the record, an upgrade test is also running in cloudtest, where supposedly the same orchestrator  that drives the upgrade will be used that is used in production as well.

**Comment by benesch** [comment]
That's great!

**Comment by aljoscha** [comment]
What should we do about this issue? It seems we'll never address the issue as initially reported?

**Comment by benesch** [comment]
Yeah, I'm not particularly worried about this! Would be good to add test coverage to cloud on this front that asserts the environment ID never changes, but I don't think we necessarily need to add additional protection against changing environment IDs to `environmentd` itself.

**Comment by benesch** [comment]
Closing as wontfix. Changing the environment ID of a running `environmentd` process is not meant to work, and thus the cloud orchestration layer is careful to ensure that it never changes.
