### ISSUE TITLE
cloudtest is flaky

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#16974]
### Buildkite link

https://buildkite.com/materialize/tests/builds/47820#0185838d-1768-4900-9e3f-7727082ad9f3

### Relevant log output

```source
$ kubectl --context=kind-cloudtest delete all --all
W0105 20:23:07.307971      23 loader.go:221] Config not found: /kube/config
```
```


### Additional thoughts

_No response_

**Comment by benesch** [comment]
Known issue that will clear up in a few days, once PRs that introduce the broken state stop being run in CI. https://github.com/MaterializeInc/materialize/pull/16934#issuecomment-1371172312 for context. I did verify that the Buildkite failure you linked is the result of an agent getting corrupted due to running cloudtest with a buggy commit (https://buildkite.com/materialize/tests/builds/47745#01858344-4449-414e-8f5f-6749505fd29a).
