### ISSUE TITLE
Support an HTTP POST source

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1701]
Something like `CREATE SOURCE <name> FROM 'port://[<host>:]<port>' ...` (maybe `tcp://..` instead?) which will open a port and allow line-based input to it, making materialized function as a server to arbitrary TCP clients. It should error if the port is taken.

The optional `<host>:` allows people to add/remove security by inserting either `localhost`, `0.0.0.0`, or some IP that they have control over.

I believe that adding some `WITH` options to describe the format (e.g. `WITH (format='http')` to parse headers allowing fore security) could be reasonable.

**Comment by rjnn** [comment]
@awang this has come up in several prospect conversations. I think we should think about up-prioritizing this as its a relatively easy win. I am considerably less worried about the lack of durability guarantees - given how up front we have been about this (and can continue to be) I don't think there's a problem there.

This source type makes for a lot of compelling demos and prototypes. I am struck by how this essentially was the 0.1 API for talking to elasticsearch (there was nothing else).

**Comment by benesch** [comment]
I'm not nearly as optimistic as you are about this being an easy win, @rjnn.

I'm still stuck on the fact that this source seems paradigmatically incorrect. Maybe I am not imaginative enough, but I don't see what the use case is for sources whose data you have no hope of recovering if Materialize is restarted. At the very least you have a nasty coordination problem, where you need to indicate to the data generator that you need a fresh copy.

I actually think #1704/#2237 better fit into the existing product philosophy, as they are both pull-based sources. Note that pull-based sources don't need to involve inefficient polling; the way both file and Kafka sources work is that you pull in data until you are caught up, and then you request a notification when there is new data to pull. This is also how the server-sent event protocol described in #2237 works, based on my read of that protocol.

Is there maybe an X/Y problem here? What is it that our customers want to do that they can't easily do today?

**Comment by frankmcsherry** [comment]
I'd just like to call out that there might be a reason to support even those things that are paradigmatically incorrect, if it gets more people trying out the system. We support several things now that are way off base (file sources, fifos) but are an important part of getting folks in the door.  We've had some comments that everything we can do to reduce the friction of trying out the software helps when it comes to adoption. If lots of folks would be able to try out Materialize with a POST endpoint easily but not otherwise, I can see the argument for putting it together. Perhaps not as part of the enterprise-ready final product, but as the first step in a conversation about why it might be worth the effort to think about investing in a more durable input.

**Comment by benesch** [comment]
> If lots of folks would be able to try out Materialize with a POST endpoint easily but not otherwise, I can see the argument for putting it together.

I can too! I'm mostly afraid of classifying this as an easy win. There is a heavy lift required, both on the scoping/design front and on the implementation front.

  * Are we going to allow `CREATE SOURCE` to open arbitrary ports? I mentioned above this makes me nervous. 
  * What does the HTTP API look like? What format does the data come in as? Can you send batch records or do you have to make a separate POST request for each message? Are there efficiency concerns?
    * HTTP has its own `Content-Type` headers that will fight with our source formats.
    * Do we need to build in load shedding (i.e., send back 429s) if we're getting too much data?
  *  How does timestamping fit into the picture? At the very least we will need to hook up the real-time logic. It's not clear to me that it would even be possible to get BYO consistency to work.
  * This is the first source that will push data from the coordinator to the dataflow workers. We don't have the machinery for doing that right now.
  * What happens to the data in the source when Materialize crashes and reboots?

We've incurred a ton of tech debt with our sources as it is, and introducing a new source type that does not match the existing paradigm will require taking on additional debt that makes me uncomfortable.

Even if we scope down the feature to its bare minimum, we now have what I'll term "product debt": a feature that might not match expectations. Yes, we can document the limitations; and yes, users will _say_ they can abide by the limitations; but these things have a way of creeping into important production cases nonetheless, and then there is sales pressure to shore up the feature in a way we hoped to avoid. In particular, I'm worried that if we are ever forced to productionalize this source that its push-based design will make load shedding irritating.

Anyway, in a world where we've got source persistence and have paid down a lot of the tech debt around our source implementations, a lot of these concerns will be mitigated. 

@rjnn, can you provide some more color re: this question from above?

> Is there maybe an X/Y problem here? What is it that our customers want to do that they can't easily do today?

I'm very enthusiastic about making Materialize easier to get going with, but if the goal is to get something in the 0.4/0.5 timeframe, I think we need to find a solution that's more aligned with the existing source paradigm.

**Comment by ruf-io** [comment]
Even if this had to be an extra service that we included in the cloud product, I think this idea would be useful for a big long-tail of lower-volume use cases.

It has become pretty standard for SaaS tools to give users the ability to specify webhooks and payloads to target based on actions inside a tool. In the marketing space, for example:
- Email services sending webhooks on deliver/open/click of emails.
- Web Tools sending webhooks on customer visit/interaction/conversion.
- Ad network tools triggering webhooks on impression, etc...

While it would probably be better for users to take events from something like kafka, a webhook would make it very easy to set up test use cases and join 3rd party datasources in with a larger 1st party CDC or kafka stream to do things like enrichment.

**Comment by benesch** [comment]
Not to worry, @ruf-io, this is very much something we intend to consider eventually. There are just a number of technical blockers in the way.

**Comment by cirego** [comment]
This feature sounds awesome -- writing to a source should be as easy as writing a message to Kafka! In that respect, why require a different port per source? Would one of the following work:

- Use the URL path to identify the source and use HTTP Authorization to authenticate per source?
- Use an HTTP header to identify the source?

While operationally mature organizations can open ports easily between services, many organization have draconian policies that make the opening of new ports unworkable (and certainly not automatable).

**Comment by benesch** [comment]
I think you may have missed some of the discussion @cirego. I mentioned that here: https://github.com/MaterializeInc/materialize/issues/1701#issuecomment-578894698

**Comment by cirego** [comment]
> I think you may have missed some of the discussion @cirego. I mentioned that here: [#1701 (comment)](https://github.com/MaterializeInc/materialize/issues/1701#issuecomment-578894698)

Sorry, I should have been more explicit. I didn't miss your comments -- I was agreeing with your comment!

**Comment by benesch** [comment]
Oh, gotcha!

**Comment by awang** [comment]
https://github.com/MaterializeInc/materialize/pull/6208 is a step in the direction of this!

**Comment by benesch** [comment]
> #6208 is a step in the direction of this!

Minor quibble: it makes Materialize work out of the box with one particular HTTP-based standard for streaming data. It does not however make any strides towards addressing the concrete proposal on the table here, which is inventing a new protocol for pushing data into Materialize over HTTP. It is possible that some of the users interested in the latter will be satisfied by the former, but by and large these are distinct features that serve different use cases.

**Comment by benesch** [comment]
Materialize today supports an [HTTP API](https://materialize.com/docs/integrations/http-api/), which lets you say things like:

```
POST /api/sql
{
     "query": "INSERT INTO my_json_table VALUES ($1)",
     "params": ['{"some": "payload"}']
}
```

In theory this gives you interop with a wide class of HTTP based tools. But it's become increasingly clear (to me, at least) that what we really need is support for directly rigging up Materialize to webhooks. Imagine if you could connect GitHub or Segment webhooks directly to Materialize! Then you wouldn't need Kafka and/or a microservice as an intermediary.

Unfortunately it is difficult to make our existing HTTP work with common webhook-delivering software. Most tools that allow delivering webhooks do so on their terms. You specify the URL, and they determine everything else: the shape of the request, the headers in the request, etc.

Even Segment, which offers a very [customizable webhook destination](https://segment.com/docs/connections/destinations/catalog/actions-webhook/), is not configurable enough to permit constructing the HTTP POST /api/sql request above that would allow the webhook's JSON payload to be written to a SQL table.

But, all is not lost! There is a relatively simple webhook source we could add to Materialize. Imagine:

```
CREATE SOURCE somedb.public.segment_events FROM HTTP REQUESTS (
    VALIDATE USING SELECT headers->>'signature' = sha256hash(body)
);
```

This would create a source named `segment_events` with the following columns:

Name | Type
----|----
`headers` | map[text => text]
`body` | text

An HTTP request to `POST /api/webhooks/somedb/public/segment_events` would write to that source _if_ the `VALIDATE USING` SQL returns `true` when run against the incoming event. (If validation fails, Materialize returns 401 to the caller; otherwise it returns 200.)

Then you're just a few `CREATE VIEW`s away from whatever analysis your heart desires.
