### ISSUE TITLE
storage: reusable reclocking

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17021]
### Feature request

⚠️ **WARNING** ⚠️ This is a draft of an idea. Think about this at your own risk! 

## Summary

Promote the reclocking collection that is implicitly associated with each source in Materialize to a first-class concept that can be independently manipulated—i.e., created, dropped, or associated with multiple sources.

When Materialize is used with Kafka sources and sinks, this allows for Materialize to participate in end-to-end schema changes.

## Details

Imagine that we introduce `SOURCE PROGRESS` objects to Materialize. A source progress object is the user-facing term for the reclocking operator. They can be created and dropped via the usual `CREATE` and `DROP` verbs:

```sql
CREATE SOURCE PROGRESS src_prog FOR KAFKA (CONNECTION kafka_conn, TOPIC 'foo');
DROP SOURCE PROGRESS src_prog;
```

The Kafka progress object produces a collection with data `(partition, timestamp)`, describing the reclocking decisions that Materialize has made.

We'd extend a Kafka sources to allow specifying `PROGRESS` in place of `TOPIC`:

```
CREATE SOURCE src1 FOR KAFKA (PROGRESS src_prog);
CREATE SOURCE src2 FOR KAFKA (PROGRESS src_prog);
```

Both of these sources would produce identical data _at identical times_.

The real magic kicks in when the upstream Kafka topic undergoes a schema change. Suppose topic `foo` is Avro formatted with records of shape `{a: int}`, with the following data:

```
{a: 1}
{a: 2}
{a: 3}
```

Suppose you create a source in Materialize with an explicit reclocking relation:

```
> CREATE SOURCE PROGRESS foo_prog FOR KAFKA (CONNECTION kafka_conn, TOPIC 'foo');
> CREATE SOURCE foo FOR KAFKA (PROGRESS foo_prog);
> SELECT * FROM foo;
a
---
1
2
3
```

Now suppose the topic undergoes a schema change, in the sense that new records are written with an additional `b: text` field:

```
{a: 1}
{a: 2}
{a: 3}
{a: 4, b: "hallo"}
```

We can create a new source in Materialize that reuses the existing progress topic:

```
> CREATE SOURCE foo_new FOR KAFKA (PROGRESS foo_prog);
> SELECT * FROM foo_new;
a  | b
---|---
1  |  NULL
2  |  NULL
3  |  NULL
4  | hallo
```

A key point is that the timestamps of the data in `foo_new` and `foo` line up exactly. Downstream applications could consistently cut over to the new schema at their desired time.

We could also build consistent cutover for sinks. See https://github.com/MaterializeInc/materialize/issues/26350 for details.

## Motivation

This is a solution to the schema change problem that I've been kicking around for a while. It has the appealing property that it allows Materialize to handle arbitrary changes to upstream schemas; the downside is that it requires re-ingesting the data in full. Wanted to get it down in writing since there's been some discussion lately about `persist` supporting schema changes (#16625).

## Open questions

* Are there other exciting use cases for reusable reclocking collections?

## See also

* #3616
* #3909
* #16625
* #26350

cc @danhhz @aljoscha @petrosagg @frankmcsherry @sploiselle @guswynn @uce @sjwiesman @morsapaes @heeringa

**Comment by benesch** [comment]
One other weirdness to note: this plays very strangely with Kafka retention policies. If the upstream Kafka topic has a retention policy, data that was present in the original source may be just straight up missing in the new source. I think this works out fine with compaction and `ENVELOPE UPSERT`, though.

**Comment by frankmcsherry** [comment]
I think it has the same problem we current have with upsert, which is that if we do not present a snapshot of the upsert as it exists the moment we look at it, we are in trouble. For example, imagine the topic contains
```
(key1, val1)
(key2, val2)
(key1, val3)
```
We might record times for these things, but if the `(key1, val1)` entry is compacted away while we are not looking, then we may present invalid data (e.g. a `key2` record without yet a `key1` record).

**Comment by benesch** [comment]
> I think it has the same problem we currently have with upsert, which is that if we do not present a snapshot of the upsert as it exists the moment we look at it, we are in trouble. For example, imagine the topic contains
> 
> ```
> (key1, val1)
> (key2, val2)
> (key1, val3)
> ```
> 
> We might record times for these things, but if the `(key1, val1)` entry is compacted away while we are not looking, then we may present invalid data (e.g. a `key2` record without yet a `key1` record).

Yeah, hmm. Wonder if we could do something like set the since of the new source to the current upper of the reclocking collection. Actually, kind of feels like you want `CREATE SOURCE … AS OF`, so you can dial around what historical detail to preserve, based on what you know to be true about the amount of historical detail that remains upstream.

**Comment by frankmcsherry** [comment]
Yeah it seems a bit tricky. Given that Kafka could in principle delete historical data at any moment, it feels like we need to complete a clean read through some `offset`, and then look up what time that corresponds to in the reclocking, and .. idk it sorta seems like maybe it would be hard to successfully use historical data. Though .. it also seems hard to guarantee any data from Kafka generally (e.g. if a source goes to sleep for two days).

**Comment by petrosagg** [comment]
Kafka has two modes of deleting old data and we must document to users
which one should be used depending on whether the topic is being ingested
raw or with an upsert envelope.

The first mode is simple trucation of messages that are older than some
offset. In this mode we are not able to recreate a source, even if it is
ingested raw, because we won't be able to recreate a snapshot.

The second mode is key based compaction where Kafka always retains the
latest value for a given key when compacting. On top of that it must be the
case compaction never outruns the offsets that we periodically commit to
the Kafka broker. If both these conditions are met we are guaranteed that
we can recreate the snapshot, exactly as dictated by the remap collection.

Assuming that we have clearly documented all these we can say that
behaviour outside of these conditions is unknown, and probably wrong. So if
users want the option value of reingesting the topic in the future they
need to make sure to uphold the protocol.

**Comment by bkirwi** [comment]
> On top of that it must be the case compaction never outruns the offsets that we periodically commit to the Kafka broker.

Note that Kafka [allows you to set a minimum retention time](https://kafka.apache.org/documentation/#topicconfigs_min.compaction.lag.ms), even for compacted topics. Like for time-based retention, you can't really get hard guarantees out of it... but, much better than nothing.

> Are there other exciting use cases for reusable reclocking collections?

I don't know about _exciting_, but...
- A _sink_ could also produce a reclocking collection, associating the mz timestamp with the offsets in the topic it writes. (Since the producer knows the offset every published message gets, this would be easy data to collect.) This would be usable as a replacement for the old consistency topic, or for some of the same things that we're hoping to use the newly-exposed source reclocking collections for.
- Reclocking collections could be written to Kafka sinks, or read from Kafka sources. (With some restrictions: we'd need to require a single-partition topic, for example.) One use-case you could imagine for this is a multi-region materialize setup: if I have a collection in us-east-1 I want to reproduce exactly in us-west-2, I could: sink out the collection in us-east-1 to `topic`, sink out the resulting reclocking collection, load that reclocking collection in us-west-2, then create a source in us-west-2 pointed at `topic` and my reclocking collection.

**Comment by benesch** [comment]
@bkirwi 🤯 that meets my definition of exciting, for sure. I love it!

**Comment by sploiselle** [comment]
Postgres sources' current design gives us a chance to tinker with this idea because all data from the replication slot shares reclocking data. Once we can add new subsources, we have in some way "reused" the reclocking data with bringing a new source up to date. Sketch of this design in #18182

**Comment by benesch** [comment]
While thinking about making subsources a flavor of tables, I just stumbled onto a very elegant API for reusable reclocking: https://github.com/MaterializeInc/materialize/issues/20208#issuecomment-1955401921

**Comment by benesch** [comment]
Going to close this out, as we'll get reusable reclocking "for free" with subsources-as-tables (#20208) and the musing about `ALTER SINK` now has a dedicated issue in #26350.
