### ISSUE TITLE
storage: do not leak persist shards

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#17320]
### Feature request

We currently leak most persist shards that we create, but this does not have to be the case.

To support this we could support the following:
- #17105
- #17327
- Introduce a [dropped source WAL](https://www.notion.so/materialize/DROP-SOURCE-WAL-7ee332c9cfcd4188a0f8aeb352f9d937); note that this implementation also somewhat mitigates apparent inconsistency in the presence of `StorageResponse::DroppedIds`.
- Ensure `StorageResponse::DroppedIds` consistently returns when storage workers drop dataflows.

**Comment by benesch** [comment]
cc @crohorner for ops tracking

**Comment by sploiselle** [comment]
@frankmcsherry After some discussion with @danhhz and @petrosagg, curious if you have a take on this--when we drop sources from the catalog, we downgrade their read handles to the empty antichain, but do not do the same with their write handles. Petros pointed me to some discussion you all had recently about a similar situation (believe regarding `DROP SINK`), but I am curious if you would be comfortable with/it makes sense to you to downgrade the write handles to the empty antichain in the case of sources we know we can no longer read from + have dropped all of their writers.

Part of what motivates this is, from my understanding from convos with Dan, we only understand that a persist shard is totally droppable once both its read and write handles are closed. So not closing the write handles means we have these persist shards in a kind of limbo state.

I'm of the understanding that there are a few different approaches to this, but wanted to get a sense of the acceptability/ramifications of this before digging into the "how."

**Comment by frankmcsherry** [comment]
I think my input on this was mostly that if dropping the source does something surprising to the write handle, that has the potential to make post-hoc debugging weirder. For example, it potentially introduces some non-determinism about whether data landed or not. A reader can no longer tell the difference, but if anyone is trying to understand the state of the shard, it could still be confusing.

There's a sane way forward where e.g. `DROP WHATEVER` is spec'd to be both "seal the writing to the shard, and then also drop read handle". This makes it a lot clearer e.g. that this implementation would not be acceptable for concurrent access to the catalog, in which someone else may still think they hold a read handle. Or at least, the odd implementation of obliterating the dropped thing rather than politely stepping away would be clearer.

Maybe the difference here is that if there exist two read handles to some frontier, `persist` should hold open the minimum of the frontiers, and closing one does not harm the other. If there exist two write handles, persist should hold open the maximum of the frontiers, and sealing one harms the other.

**Comment by danhhz** [comment]
> Maybe the difference here is that if there exist two read handles to some frontier, persist should hold open the minimum of the frontiers, and closing one does not harm the other. If there exist two write handles, persist should hold open the maximum of the frontiers, and sealing one harms the other.

If i'm reading this correctly, this is exactly what persist does now.

**Comment by sploiselle** [comment]
@frankmcsherry Given that we can support the desired behavior (i.e. we never compact away values, and sealing a shard can cause others to panic), sounds like you are comfortable with sealing shards when their collections are dropped. Is that fair to say or have I misunderstood/mischaracterized something?

**Comment by frankmcsherry** [comment]
Sorry for the latency. Summary of some thoughts typed into Slack:

1. Sealing the writer (writing through the `[]` frontier) seems "not strictly necessary" from an architectural point of view. One could plausibly (idk in our code) drop the writer without sealing the data. This has the appealing property that it leaves the data in a state that is less ambiguous (how far did we write; if someone else actually holds a read handle are we correctly communicating that the source is guaranteed unchanging, or are we leading to confusion by announcing a thing we don't really know).
2. If sealing the writer is necessary (e.g. for `persist` to grok that a writer has finished) it might force us to write non-robust code, where one of multiple writers is obliged to close things out just to cleanly shut down, and we'll need to revisit that in a world with multiple shared writers. In that world, not much to be done at the moment if we value collection the shards more than the hypothetical clarity of only saying things we locally know to be the case (about further updates to the shard).

@danhhz do you know if (2.) is the case, and if so any interest in discussing whether it should be the case for all time? If we end up in a world where we can have multiple writers and critical read handles, say a replicated `adapterd`, then if they are written to seal shards on shutdown we'll have to find and rip out all that code when we do it, I think.

**Comment by aljoscha** [comment]
As of https://github.com/MaterializeInc/materialize/pull/14704, persist only special cases a shard that has `upper == [] && since == []`. In those cases, it replaces all state by an efficient tombstone.

I think requiring `upper == []` here might be too strict a requirement because it forces us to sometimes _lie_ (as Frank expressed above, in different words). There are legitimate moments in the code where we _do_ advance a shard's `upper` to `[]`. We do this for finite sources, where we advance both the data and remap shard to `[]`. In those cases we're not lying, we truly know that there will never be more data for those shards, we have seen it all.

The reason I use _lying_ for other cases, like finalization, is that we don't know what other data would be in the interval between _current upper_ and the empty frontier that we're advancing to. This is problematic if there are still readers of the shard, that suddenly "believe" we know more than we actually do.

It feels like "finalizing" a shard, for example, when dropping something, should only require advancing the `since` to `[]`. And persist can implement an efficient tombstone for that case, but only when the "global" `since` goes to `[]`, meaning when there are no more life `ReadHandles` that are holding it back, in which case it's also impossible to create `ReadHandles` for a since other than `[]`. (This business about the global since is implemented like that today, I'm just spelling it out for this conversation).

When `since == []` but the `upper` is different from `[]` we're in a situation where we can still write to the shard, but no-one can ever read those changes. It seems persist would have to have the optimization that we still only keep a tombstone, and silently drop writes. Only after checking that the writes are legal, with respect to the current `upper` of course. 

@danhhz What do you think about that (proposed, a strawman) change to the persist tombstone optimization.

@sploiselle Whatever comes out of this, we need to make sure that all moments in the code where we finalize shards are updated to reflect the current thinking.

**Comment by danhhz** [comment]
IIRC the `upper == []` bit came out of attempting to make the shard tombstones fully idempotent. Concretely, imagine the following scenario:

- Some shard is made a tombstone by the shard-global since being advanced to `[]`
- The upper is still at some non-empty frontier `[x]`
- Someone creates a new write handle and does a `compare_and_append(updates, [x], [y])`

It feels like we have a few options:
- (A) Panic instead of letting them create the new write handle (or error, but I suspect in practice that this would end up being an `expect` at every callsite)
- (B) Panic at the `compare_and_append` (or error, but I suspect in practice that this would end up being an `expect` at every callsite)
- (C) Error on the compare_and_append by lying and returning an upper mismatch
- (D) Accept the compare_and_append. This is tricky because we probably want someone to delete the data on s3 (the whole point here being to free up data on s3 once we've lost the capability to ever read it again). We have to write a new version of state anyway to advance the upper, so that's fine (modulo the tombstone not really being guaranteed to be a tombstone), but it definitely feels like a bunch of edge cases here around tombstones that I worry would be under-tested in practice.
- Something else?

There's also a similar scenario but for a writer that is registered at the time the shard-global since advances to `[]` and makes the shard a tombstone. This probably eliminates (A) as an option.

I'm not wed to the `upper = []` requirement, it was just the best I came up with in response to the above (concretely: it's impossible to construct a valid `compare_and_append` with an expected upper of `[]`). Perhaps we like (B) better? (C) feels pretty bad. (D) is somewhat stressful, but might actually be the best option for something like replicated adaptord (though I very much don't pretend to understand the requirements there yet)?

@frankmcsherry How would you feel about something like (B) for now and then revisit (D) as part of the scope of replicated `adapterd`?

**Comment by aljoscha** [comment]
> (B) Panic at the compare_and_append (or error, but I suspect in practice that this would end up being an expect at every callsite)

You're thinking (B) for now, among other things, because it seems to be a usage error in most cases? When adapterd (or someone) is trying to write, it better also hold a read handle so that it can read what it just wrote or read updates that other concurrent writers might have written. In general, why would anyone write when it's impossible for anyone to read anything.

**Comment by danhhz** [comment]
> When adapterd (or someone) is trying to write, it better also hold a read handle

Atm, it would be even stronger than that because of critical handles. A writer doesn't need a read handle as long as the controller hasn't advanced the `CONTROLLER_CRITICAL_SINCE` to `[]`.

But now that you mention it, I think I'm missing some context on the global view of shutdown. Is there a situation where some clusterd (either compute or storage) is still writing to a shard the the point that it's finalized? If so, then we'd need to handle things more gracefully than (B)

**Comment by sploiselle** [comment]
This is done from the perspective that persist shards will not leak, given that Materialize occasionally restarts to reconcile the adapter catalog against the `METADATA_COLLECTION`.
