### ISSUE TITLE
[Epic] Enable out-of-core for research/testing

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#17566]
### Product Outcome

Some workloads show temporary memory spikes. While we’re working to avoiding these spikes, we also want to add resilience to them by enabling out-of-core for specific instance sizes. While it is not a general tool to scale Materialize to orders-of-magnitude more memory, it can enable more efficient rehydration and specific customer workloads.

### Specification

TODO

### Design

There is not yet a design for this feature.

The cloud design for upsert spill to disk (https://github.com/MaterializeInc/cloud/issues/5909) may be relevant, as if we switch to an instance type with local disks attached for upsert spill-to-disk, we'll be able to piggyback on that work for out-of-core execution.

### Required Issues (Must Haves)

* Enable swap for specific instances in cloud (XL+) on personal stacks and staging.

**Comment by benesch** [comment]
Loose sketch of a design: we default enable swap for clusters of xlarge+. This will likely require a separate provisioner for xlarge clusters using an instance type with lots of local disk (i4i?), since swap is enabled/disabled at the node level.

In terms of rollout: perhaps we introduce a new size on staging only called `xlarge-swap` that uses the separate provisioner with swap enabled? Then compute can do additional testing and validation. Once we're happy with it, we can enable swap by default for xlarge+, and remove the staging-only xlarge-swap size.

**Comment by jonathan-k-shapiro** [comment]
Complete for now. 
@vmarcos [documented observations in Notion](https://www.notion.so/materialize/Validating-Out-of-Core-for-Compute-with-Swap-in-Cloud-0f7ea02814db46449d22f9db55ce365c)

**Comment by jonathan-k-shapiro** [comment]
Closing since the research has been enabled.
