### ISSUE TITLE
Pause Postgres Source Replication 

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#17572]
### Feature request

The request is twofold:

- to be able to pause PG replication either on the Materialize side or on the PG side (without falling over on the Materialize side) and
- for Materialize to continue serving views from a Postgres paused source 

A non-request is to be able to start the source back up again -- although this seems like it would be handy in practice.

> Is there a way to pause replication (on the Materialize or Postgresql side) for a little while and let the replication slot  queue and yet still answer queries in Materialize?
We sometimes have a need to temporarily stop replication, typically during some sort of maintenance activity, but still want the Materialize database to do its best effort and share what it already knows about the data with clients that ask.  It doesn't matter if Materialize ever catches back up with the replication stream, we have the option of slipping another one in after the maintenance completes and cutting over to that.  What we can't live with is Materialize going down altogether if we cut off its replication feed.

**Comment by petrosagg** [comment]
Some thoughts on this feature request.

First, I think we should describe this feature one level of abstraction higher, where we give users the ability to pause a source (maybe also a sink?) regardless of the source implementation. In other words, it shouldn't be a pg specific feature. 

The next thought I had is that we need to clarify what we mean by "for Materialize to continue serving views". It could mean one of two things:

1. We stop ingestion and so the upper frontier stops advancing. The source and any dependent views are queryable but only in serializable mode
2. We stop ingestion but we keep the reclock machinery up and running so the shard keeps ticking forward with empty updates. In this case the source and any dependent views are always queryable and unchanging

1 is easier to implement than 2 but both are doable

Finally, about resuming a paused ingestion, it is a fairly easy stretch goal because we already have code to handle this situation. When a cluster fails or crashes causes all sources to effectively be paused, and the system appears to work in mode 1 from above. When a cluster comes back up we already have code that resumes ingestion. If we wire these two things all the way back to some SQL syntax a user could both pause and resume a source

**Comment by rotten** [comment]
This might be even extensible to an option on the source to handle different failure scenarios sort of like this:

1. FAIL - if the source is interrupted, do not resolve queries - go into hard failure mode.
2. IGNORE - if the source is interrupted, continue to operate as normal (perhaps emitting a log and/or client warning)
3. PAUSE - continue to operate, but no longer accept new data from the source whether or not it is working properly
4. SKIP - do not try to catch up if the source is interrupted and then resumes, instead just take in the new data
5. RESTORE from Start - if the source is interrupted, rebuild the views from scratch when it resumes

At a basic level, being able to tell Materialize that we are taking a source or the network path to the source down for maintenance but we want to continue serving requests while in maintenance mode is what we really need.  The rest of these might be incorporated for higher automatic site reliability at some point.

**Comment by sploiselle** [comment]
For customers using Neon PG instances as sources, a feature like this is a prereq to let them use [Neon's auto-suspend feature](https://neon.tech/docs/guides/logical-replication-neon#logical-replication-and-auto-suspend).

**Comment by benesch** [comment]
Going to call this one complete. You can pause a PostgreSQL source by removing all replicas of the cluster on which it is running. As long as you're using `serializable` isolation, the source and its downstream views will still be queryable.
