### ISSUE TITLE
[Epic] persist: design for backup/restore

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#17605]
### Feature request

(tbd)

**Comment by bkirwi** [comment]
I'm currently working on sketching this one out. Two broad questions to help scope the implementation:
- **What window of time do we want to be able to restore backups over, at what granularity?** If we want to be able to restore to a particular instant within the last day, we’ll need fine-grained capture of all changes to CRDB and S3. If we want to be able to restore from or inspect a years-old backup, we’ll want sparser backups on cheaper storage.
- **Are backups user-facing in any way?** Do we want to expose any of the backup and restore functionality to users (eg. via a SQL API or writing in to support) or is it purely an internal tool for disaster recovery? If we're keeping long-term backups, do we need to allow users to opt out for GDPR compliance?

I'm not sure who's all interested in this one, but cc at least @danhhz and @aljoscha and @benesch!

**Comment by benesch** [comment]
Looping in @heeringa and @frankmcsherry for the product questions.

My model for this is that we want something similar to Snowflake's ["fail-safe storage"](https://docs.snowflake.com/en/user-guide/data-failsafe). The only way in which it's exposed to users is as part of the storage usage costs on the bill; to actually _access_ the data due to a disaster event, you need to contact Snowflake support.

> * **What window of time do we want to be able to restore backups over, at what granularity?** If we want to be able to restore to a particular instant within the last day, we’ll need fine-grained capture of all changes to CRDB and S3. If we want to be able to restore from or inspect a years-old backup, we’ll want sparser backups on cheaper storage.

> What window of time do we want to be able to restore backups over, at what granularity?

I'll throw out a proposal to get things started: hourly for 7 days, daily for 30 days?

> Are backups user-facing in any way? 

I can't come up with a good reason that they should be! I think we basically already have user facing backups in sinks, and user facing restores in sources. Particularly in a future world where we support S3 sources and sinks. It seems nice to avoid introduce a new user concept of "backup" and "restore", and instead just talk about "scheduled one-shot sinks to S3."

**Comment by heeringa** [comment]
Thanks for the tag @benesch! 

> I can't come up with a good reason that they should be! I think we basically already have user facing backups in sinks, and user facing restores in sources. Particularly in a future world where we support S3 sources and sinks. It seems nice to avoid introduce a new user concept of "backup" and "restore", and instead just talk about "scheduled one-shot sinks to S3.

I agree with Nikhil.  There are more natural approaches to user-facing backups I'd want to explore first.  I would also want to get a better pulse on customer demand followed by some user requirements.

**Comment by bkirwi** [comment]
Great! That all makes sense to me.

So, tentatively declaring as out of scope / potential future S3 sources/sinks project:
- User-facing API. We'll treat this as an internal tool. (Though it sounds like we may still want users to know about backups / let them request a restore via support, a la Snowflake's fail-safe storage.)
- Long-term backups. We won't worry about being able to restore from backups >30d old.

It also sounds like we're fine with snapshot-style periodic backups, vs. something like [postgres' continuous backup / point-in-time recovery](https://www.postgresql.org/docs/current/continuous-archiving.html). (I'm not yet sure whether point-in-time restore is any extra work, but it's nice to have the flexibility of course!)

**Comment by bkirwi** [comment]
I've posted the current state of the design exploration is at https://github.com/MaterializeInc/materialize/pull/18157.

Since we're not planning to start work anytime soon, we haven't hammered out an exact implementation plan and I've left this as a draft PR. Nevertheless - feedback always welcome!

**Comment by danhhz** [comment]
Getting out a design doc was the intended scope of this issue, so now that we have https://github.com/MaterializeInc/materialize/pull/18157, I'm going to closed it as finished. We'll schedule any work to implement the design doc separately
