### ISSUE TITLE
Deleting an RDS instance doesn't cause source error

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#17924]
### What version of Materialize are you using?

v0.44.3

### How did you install Materialize?

Materialize Cloud

### What is the issue?

I tore down an RDS instance in AWS, and I didn't see any errors (in mz_source_status_history) for ~15 minutes. After restarting the source cluster, an error was recorded as expected.

### Relevant log output

I deleted the RDS instance at 10:50.

```source
COPY (SUBSCRIBE ( SELECT * FROM mz_internal.mz_source_status_history)) TO STDOUT;
1677783968950   1       2023-03-02 18:45:55.938+00      u6      running
1677783968950   1       2023-03-02 18:45:54.937+00      u6      starting
1677784045413   1       2023-03-02 19:07:25.413+00      u6      starting
1677784046414   1       2023-03-02 19:07:26.414+00      u6      stalled error connecting to server: failed to lookup address information: Name or service not known: failed to lookup address information: Name or service not known
```
```

**Comment by dseisun-materialize** [comment]
@sploiselle is the metapoint here that if there's a break in the ability to connect to postgres we don't surface it for 15 minutes?

**Comment by sploiselle** [comment]
I wouldn't classify this as a bug because the replication protocol AFAIK doesn't require a "farewell message" or anything like that. Because there's no "terminating" signal, we cannot discern this case (the server being torn down) from being partitioned away from RDS.

This looks like the timeout feature is working exactly as intended and I would be inclined to close as "won't fix" (which is totally fine, @RobinClowers--would prefer to get pings on things that seem goofy to you in hopes of being able to improve the UX!).

If there is appetite for detecting these cases more quickly, we could shorten the timeout duration, but do want to stress that this doesn't actually change the semantics of detecting than an RDS instance has been destroyed.

**Comment by RobinClowers** [comment]
So just to be clear, I didn't get an error until I restarted, I guess I'm wondering how long it would take before showing an error if I had never restarted?

**Comment by sploiselle** [comment]
Ah, my apologies, Robin––I misread this:

> I didn't see any errors (in mz_source_status_history) for ~15 minutes

The timeout is somewhere in the ballpark of 15 minutes, so I thought you were saying you didn't see any errors for 15 minutes, and then saw errors. I didn't realize you _had_ to restart to encounter an error.

We have a test for approximately this in `test/pg-cdc-resumption/toxiproxy-close-connection.td`, so it's surprising to hear that tearing down the instance did nothing at all. I wonder if RDS just doesn't close the client connection that's open? Will test this out.

**Comment by RobinClowers** [comment]
Yeah, I could have done a better job explaining exactly what happened :) It's possible that I just restarted it right before I hit the timeout, I should have waited longer before restarting.

**Comment by sploiselle** [comment]
Hmm, I can't repro this locally whatsoever. Deleting the RDS instance starts causing timeouts in ~60 seconds and I start generating errors immediately, though the status does thrash between `starting` and an error as the source attempts to reconnect.

@RobinClowers which environment was this in? And have you seen it occur more than once?

**Comment by RobinClowers** [comment]
Confirmed, this is fixed now, thanks for looking into it!
