### ISSUE TITLE
Installation guide link broken or missing

### ISSUE THREAD

**Issue by gkaretka** [MaterializeInc/materialize#17982]
### Documentation request

I was unable to find proper installation guide on the main site, link shows 404 [https://materialize.com/docs/install/](https://materialize.com/docs/install/)

**Comment by morsapaes** [comment]
Where did you run into this URL, @gkaretka? There is no longer an option to install Materialize locally since we moved to a distributed, cloud-native architecture (see [this announcement](https://materialize.com/blog/next-generation/) for an overview). You should sign up for access [here](https://materialize.com/register/).

**Comment by gkaretka** [comment]
Link was in some older tutorial (mid 2021). Thanks for clarification.
