### ISSUE TITLE
thread 'test_old_storage_usage_records_are_reaped_on_restart' panicked at 'assertion failed: `(left == right)` in cargo test

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18108]
### What version of Materialize are you using?

33fde6d8fb

### How did you install Materialize?

Docker image

### What is the issue?

```
thread 'test_old_storage_usage_records_are_reaped_on_restart' panicked at 'assertion failed: `(left == right)`
  left: `104`,
 right: `0`: Records were not reaped!', src/environmentd/tests/server.rs:740:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<i32, i32>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:199:5
   4: server::test_old_storage_usage_records_are_reaped_on_restart
             at ./tests/server.rs:740:9
   5: server::test_old_storage_usage_records_are_reaped_on_restart::{closure#0}
             at ./tests/server.rs:674:59
   6: <server::test_old_storage_usage_records_are_reaped_on_restart::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
https://buildkite.com/materialize/tests/builds/51358#0186db14-e262-498d-9fc5-8af580c6d647

ci-regexp: test_old_storage_usage_records_are_reaped_on_restart

**Comment by sploiselle** [comment]
This flakes for me locally on `827ef0c2841678d14ca5a72ffa9dea0fe2144e47` (`main`)l

**Comment by necaris** [comment]
Yes, this one's my fault -- not sure how to improve the test here!

**Comment by jkosh44** [comment]
I have two thoughts here:
- We can hopefully use deterministic timestamps instead of sleeps to ensure that a certain amount of time has passed.
- The test seems to assert that the storage count after a restart is 0. I think this probably has a race condition where we gather more storage usage after the restart but before the query executes. Instead we can assert that the min timestamps in `mz_storage_usage_by_shard` after the restart is larger than the max timestamp before the restart.

I'll play around with this locally and see if it works.

Also @aljoscha I see that you're assigned, but my assumption is that you're not actively working on it since this isn't exactly a storage issue? If you are then let me know and I'll let you continue.

**Comment by necaris** [comment]
@jkosh44 thanks! Please lmk if you'd like me to take over on a fix or anything -- I can try some variations later today when I get time.
