### ISSUE TITLE
storage: dropped sources and sinks resurrect on rehydration

### ISSUE THREAD

**Issue by tgillstar** [MaterializeInc/materialize#18102]
### What version of Materialize are you using?

v0.45.0

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The stack trace in question is here: https://materializeinc.slack.com/archives/C04DJT084KA/p1678733512043639?thread_ts=1678717973.657229&cid=C04DJT084KA

Graphana:
https://grafana.dev.materialize.com/goto/pM3jgJ-4k?orgId=1

Related Slack threads:
https://materializeinc.slack.com/archives/C04DJT084KA/p1678717973657229

**Comment by benesch** [comment]
@sploiselle, @aljoscha, @petrosagg and I have all dug into this. The problem is that dropping a source or a sink that was created from `IN CLUSTER` does not remove that source or sink from the rehydration client. If the cluster restarts but environmentd does not, the source or sink will spring back to life.

In theory the `StorageResponse::DroppedIds` response will eventually cause the controller to clean up the state in the happy path. Certainly there is an edge case (described in #17559) where an ill-timed cluster crash will prevent this from happening, but @sploiselle were unable to reproduce the happy path when testing locally.

Slack conversations:

  * https://materializeinc.slack.com/archives/C04DJT084KA/p1678738696341189?thread_ts=1678717973.657229&cid=C04DJT084KA
  * asdf

Open PRs:

  * https://github.com/MaterializeInc/materialize/pull/17559
  * https://github.com/MaterializeInc/materialize/pull/18069#issuecomment-1465093782

**Comment by aljoscha** [comment]
Possibly related issue: https://github.com/MaterializeInc/materialize/issues/18112
