### ISSUE TITLE
Rework `predicate_pushdown` so it is `recursion_safe`

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#18167]
### Size estimate
S

### Notes
Maintains `Let`-based context.

**Comment by ggevay** [comment]
I think we could make it safe for LetRec if we simply don't push into such a `Get` whose Id is used somewhere in a back-edge, i.e., that is referred to from the next iteration. In the long term, there might be more opportunities for safe predicate pushdown even into some of these Gets, but the most important cases would already be covered simply with the above rule:

What the above would cover:
- Pushing down a predicate inside a single iteration, e.g., through the `Get a2` in the below example.
- Pushing into the Union input that is the base case, i.e., close to the sources.
- Pushing into a "side-input", e.g., to the `Get src2`. (In a real example, this could be the edges dataset of a graph in a transitive closure computation, and maybe we are filtering edges with a certain property.)

What the above wouldn't cover:
- Pushing something into the recursion from above, e.g., through the `Get a3` at the top in the below example.
- (Pushing from one iteration into a previous one, e.g., through the `Get a3` near the bottom. But I think this is fine; we don't want to do this even later, since this could cause infinite loops by a predicate going around infinitely.)

Example:
```
return
  ...
    Get a3 // (We will want to push through here eventually, but not necessarily in the first version.)
Let a3 =
  ...
    Get a2
Let a2 = 
  ...
    Join
      Get a1
      Get src2 // "side-input"
Let a1 = 
  ...
    Get a0
Let a0 =
  union
    ...
      Get a3  // back edge. (I think we don't want to push through here at all.)
    ...  // base case
      Get src1
```

And a rough idea for the long term to enable pushing something into the recursion from above:
- When we are thinking whether to push into the `Get a3` at the top, we make an optimistic/pessimistic fork of the plan: the current plan will be the pessimistic version, but we create an optimistic version, where we push the predicate into the `Get a3` at the top as if the same predicate would already be present also on the bottom `Get a3`.
- Then we continue with the normal pushdown on the optimistic plan until fixpoint.
- At the end, we check the condition that we optimistically assumed, i.e., that the same predicate that was present on the top `Get a3` reached also the bottom `Get a3`. If this optimistic condition holds now then we take the optimistic version as the final result, and if it still doesn't hold then we take the pessimistic version as the final result.

**Comment by aalexandrov** [comment]
Is "side-input" another term for a loop-invariant variable (that is, a binding that is not bound within the scope of the nearest enclosing `LetRec`?

**Comment by aalexandrov** [comment]
An [discussion with an example](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1689267415296699) where the optimistic approach will have some benefit.
