### ISSUE TITLE
Rework `union_branch_cancellation` so it is `recursion_safe`

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#18176]
### Size estimate
XS

### Notes
At first glance it seems already `recursion_safe` (the transform does not maintain a `Let`-based context), but at the same time the logic seems a bit to involved. needs deeper analysis.

**Comment by ggevay** [comment]
We'll need to make it differentiate between Gets to the same Id if the meaning of the Id is different between the two Gets due to referring to different iterations.

**Comment by ggevay** [comment]
Or maybe this problematic case can't happen: If `UnionBranchCancellation` is looking at two Gets to the same Id, then I think these have to be under the same Let binding. This is because the recursion of `compare_branches` starts from two things in the same Let binding (from two inputs of a Union), and then I think it can't go into different Let bindings from there.
