### ISSUE TITLE
persist: add mfp pushdown details to EXPLAIN

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#18305]
It's almost certain that, as soon as we have filter pushdown, a common question users (and we) will have will be "why didn't this query get the optimization?" followed probably by "why did this query that got the optimization not get even faster than it did?"

The full answers will require bits of information from various places, but it seems likely that the way it gets presented to users will _handwaves_ be through `EXPLAIN`.

More details in [this code review thread](https://github.com/MaterializeInc/materialize/pull/18237#discussion_r1143583557) (copy-pasted below).

**Comment by aalexandrov** [comment]
Note that the current `EXPLAIN` support will only display which predicates are made available to the sources API. What the sources API does with them (in particular, whether some partition pruning happens) cannot be determined at the moment when rendering the `EXPLAIN` output, so you might end up with false positives under the `Source` sections.

If you want more precise outputs you will need to make this information available to the `ExplainMultiPlan` structure.

**Comment by bkirwi** [comment]
Thanks for the context!

> You need to figure out how the SourceInstanceArguments attached to SourceInstanceDesc are made available to persist in the rendering code [...]

For posterity, the source imports are unpacked [here](https://github.com/MaterializeInc/materialize/blob/26f23fd7271cf92c7c8b0dc4ba4711999b45999a/src/compute/src/render/mod.rs#L199) and the metadata is passed through [here](https://github.com/MaterializeInc/materialize/blob/26f23fd7271cf92c7c8b0dc4ba4711999b45999a/src/compute/src/render/mod.rs#L223).

> There is a high chance that things still work and you just need to flip a switch somewhere.

I'm not sure what you mean by "still work", or what switch you have in mind... could you elaborate here?

> However, at the moment we cannot distinguish between filters that will be acted upon and those that will be just ignored by the storage layer.

At a first pass, I've got fairly high confidence that we could detect and report filters that we can _attempt_ to optimize, ie. those that have numeric columns where the MFP bounds the range. The main challenge here is that our prototype filter implementation is written as a predicate on blocks instead of an explicit set of range bounds, but this seems surmountable.

Knowing whether a user will see any optimization in practise also involves knowledge of the exact batch/part boundaries in Persist's spine. To my knowledge this information is not currently available until rendering time, and rendering is not run as part of a typical explain. It also involves async calls to fetch persist state, whereas IIUC explain currently runs synchronously and does not have access to a persist client. (@aalexandrov - am I understanding explain correctly here?) Enriching our `EXPLAIN * PLAN` output with MFP data seems like it may be prohibitively invasive.

`EXPLAIN TIMESTAMP` works a little differently, though - it runs optimization, than enhances it with live data about the currently-available timestamps from the storage controller. It also runs async code, to obtain a recent timestamp. Adapting the `EXPLAIN TIMESTAMP` model to obtaining filter pushdown details seems relatively straightforward.

**Comment by aalexandrov** [comment]
> I'm not sure what you mean by "still work", or what switch you have in mind... could you elaborate here?

cc @petrosagg should know what happens with `SourceInstanceArguments` when they leave the ownership boundary of compute. AFAIK currently this should be available to `persist_source` (or at least it shouldn't be so hard to wire this through), but this structure is not interpreted when rendering and/or executing the source.

**Comment by aalexandrov** [comment]
> IIUC explain currently runs synchronously

How is this reflected in the code? AFACT the none of the `sequence_~` functions are marked as `async`.

https://github.com/MaterializeInc/materialize/blob/f48f4b1e2628609cb20acb7204e7d417ac0d5a23/src/adapter/src/coord/sequencer/inner.rs#L2388-L2398

**Comment by bkirwi** [comment]
We have basic explain support in main for a while now... I'll close this for now, and we can reopen if it turns out we want some of the more elaborate explain support discussed above.
