### ISSUE TITLE
ILIKE and regexp_match with i-flag broken by (possibly) predicate canonicalization

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#18494]
### What version of Materialize are you using?

v0.47.0 

### How did you install Materialize?

Materialize Cloud

### What is the issue?

`ILIKE` does not appear to be case sensitive:

```
select * from mz_secrets where name ILIKE 'pg%';
 id | schema_id |  name   | owner_id
----+-----------+---------+----------
 u1 | 3         | pg_pass | u2
(1 row)
materialize=> select * from mz_secrets where name ILIKE 'PG%';
 id | schema_id | name | owner_id
----+-----------+------+----------
(0 rows)
```

**Comment by philip-stoev** [comment]
The `normalize_ops` transform is to blame:

```
 22072   | optimize/local/logical/normalize/0000/normalize_lets                              | Filter (#0 ilike "%PG_PASS%")        
  +
         |                                                                                   |   CrossJoin                          
  +
         |                                                                                   |     Constant                         
  +
         |                                                                                   |       - ()                           
  +
         |                                                                                   |     Get materialize.public.t1        
  +
         |                                                                                   | 
 129956  | optimize/local/logical/normalize/0000/normalize_ops                               | Filter "%PG_PASS%" ~~(#0)            
  +
         |                                                                                   |   Get materialize.public.t1     
```

**Comment by philip-stoev** [comment]
This also seems incorrect:

```
diff --git a/src/sql/src/func.rs b/src/sql/src/func.rs
index 98056336a..e280765e8 100644
--- a/src/sql/src/func.rs
+++ b/src/sql/src/func.rs
@@ -3312,7 +3312,7 @@ pub static OP_IMPLS: Lazy<BTreeMap<&'static str, Func>> = Lazy::new(|| {
             params!(Char, String) => Operation::binary(|ecx, lhs, rhs| {
                 let length = ecx.scalar_type(&lhs).unwrap_char_length();
                 Ok(lhs.call_unary(UnaryFunc::PadChar(func::PadChar { length }))
-                    .call_binary(rhs, IsLikeMatch { case_insensitive: false })
+                    .call_binary(rhs, IsLikeMatch { case_insensitive: true })
                     .call_unary(UnaryFunc::Not(func::Not))
                 )
             }) => Bool, 1630;
```
But fixing it does not fix the underlying problem.

**Comment by philip-stoev** [comment]
Even with `canonicalize_equivalences` nerfed the query is still incorrect.

**Comment by nrainer-materialize** [comment]
For the sake of completeness: This also applies to `regexp_match` when used with `i` flag.

**Comment by ggevay** [comment]
There are at least 4 bugs here, possibly 5:
- Philip wrote "the arguments to the regexp function have been reversed!" -- This is actually only the printing in EXPLAIN. I'll change the EXPLAIN format.
- EXPLAIN prints the unary version of ILIKE the same as LIKE, i.e., it simply ignores the `case_insensitive` field. Also easy to fix.
- The `(Char, String)` overload of `!~~*` incorrectly sets `case_insensitive` to `false`. (Philip also found this one.)
- (This is the big one, observed in the issue description.) The protobuf serialization forgets the `case_insensitive` field. This is because it simply calls `as_str()` on the regex, which gives the original regex string, but doesn't include any of the build options, from which `case_insensitive` would be relevant for us. So upon deserialization it just uses the regex string to rebuild the regex, not knowing about the `case_insensitive` field. I can fix this by calling `compile` in `impl RustType<ProtoMatcher> for Matcher`, giving it the `case_insensitive` field, which we are saving as part of our `Matcher`.
- I'm still investigating, but it seems the `serde_regex` external dependency also makes the exact same mistake explained above made by our protobuf serialization. If this is true, it would affect the derived `Deserialize` and `Serialize` implementations. I'll try to reproduce this outside of Materialize and report it to `serde_regex`, and let's hope they fix it. In the meantime, I hope I can fix this by manually writing `Deserialize` and `Serialize` implementations instead of deriving them using `serde_regex`.

**Comment by ggevay** [comment]
(Still working on it ([WIP branch](https://github.com/ggevay/materialize/tree/ilike-fixes)), will continue next Thursday when I'm back from vacation.)

**Comment by ggevay** [comment]
PR: https://github.com/MaterializeInc/materialize/pull/20602
