### ISSUE TITLE
Change id column in catalog tables mz_databases and mz_schemas to namespaced id

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18506]
The current state of affairs is that there are no system databases so we didn't need separate namespaces for the IDs. The system schemas are all identified by their lack of a database.

However, in order to be consistent with the rest of our catalog tables, and to be safe in case we would want namespaced ids in the future, it would be better to change these columns now if possible.

The main complication is that many other catalog tables, such as `mz_objects` have foreign key references to the `mz_schemas` `id` column, so all of those relations would need to be updated too.

Since this is a backwards incompatible change, the first step here is to understand whether and users have already created user-defined objects, such as views and materialized views, over `mz_databases`, `mz_schemas`, or any other catalog relation with a foreign key reference to those tables.
This can be done via an `mzadmin` script https://www.notion.so/materialize/Running-a-SQL-query-against-environments-during-a-release-468626c947734d3abf8e1d8860292d9d, example query [here](https://materializeinc.slack.com/archives/C02FWJ94HME/p1679479741477409?thread_ts=1679343376.530329&cid=C02FWJ94HME).
If so, we need to figure out how many/the impact, and determine next steps from there.
If not, we can proceed with the change.

**Comment by parker-timmerman** [comment]
For my own reference, what this issue is referring to is changing the `id` column in the [`mz_databases`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1386) and [`mz_schemas`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1396) built-in tables to go from a plain number, e.g. `42`, to a system or user namespaced id, e.g. `u42` (indicating a user made object with id 42). All of the ids in both of these tables currently are user defined, so in that sense the migration is just prefixing the current id with a `u`.

### What Needs to Change

From an initial glance of the codebase, these are all of the various things that we'd need to change, in addition to the two tables themselves:
* [`database_id`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1398) column in the `mz_schemas` built-in table.
* `schema_id` in the following built-in tables or views:
  * [`mz_tables`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1440) table
  * [`mz_connections`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1451) table
  * [`mz_sources`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1472) table
  * [`mz_sinks`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1488) table
  * [`mz_views`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1504) table
  * [`mz_materialized_views`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1516) table
  * [`mz_types`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1529) table
  * [`mz_functions`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1600) table
  * [`mz_secrets`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1654) table
  * [`mz_objects`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1932) view
  * [`mz_relations`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin.rs#L1922) view
* [`DatabaseKey`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/storage.rs#L2443) which is used in the `"database"` collection within the Stash
* [`SchemaKey`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/storage.rs#L2470) which is used in the `"schema"` collection within the Stash
* [`SchemaValue.database_id`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/storage.rs#L2476) which is used in the `"schema"` collection within the Stash
* [`DatabaseId`](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/names.rs#L662) newtype
* [`SchemaId`](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/names.rs#L635) newtype

> Note: there are also several indexes that are on the `schema_id` column from the above mentioned tables, which I don't think would require any changes are they would get re-built on upgrade? But I need to verify this.

At a minimum we'd need to have two migrations, one to update the stash to convert both the databases and schemas collection to the new namespaced ids, and then a second to migrate all of the built-in tables. These can happen separately, but the stash change should occur first to prevent being lossy.

### Checking Users

Before doing any migrations though, we want to make sure we don't break any users existing workflows. The `mz_materialized_views` and `mz_views` tables have a `definition` column, which stores the `SELECT` query used to generate the object. We can use the `mzadmin` tool to look at all users to see if they have objects that rely on these columns, and thus would need to be updated. What we don't have anyway to track though are adhoc `SELECT` queries users run that might depend on these columns, and this change would most likely then break these queries.

### Next Steps
@chaas I'll do what you proposed and write a query to determine if any user objects depend on the aforementioned tables and views. If there aren't any then we can think about how to detect if there are any adhoc `SELECT`s that reference these objects, or if there are, we can try and dig deeper to see if any of them rely on the columsn we'd be changing.

**Comment by parker-timmerman** [comment]
Fixed with #18719, will go out with `v0.52`
