### ISSUE TITLE
Hard-to-observe memory spike in production cloud service

### ISSUE THREAD

**Issue by necaris** [MaterializeInc/materialize#18534]
Memory spikes in customer environment causing `environmentd` to repeatedly crash out of memory. See context from Slack: https://materializeinc.slack.com/archives/C05176ZA1K6/p1680278895417419

**Comment by benesch** [comment]
Discussion from incident 46 and fallout suggests that this might be related to the hourly storage usage collection. We tracked down a CPU issue.

Slack conversation: https://materializeinc.slack.com/archives/C04LQV4KUR4/p1680598960137519?thread_ts=1680561100.901549&cid=C04LQV4KUR4

I'm going to toss this one onto the storage board so that it has somewhere to live.

**Comment by necaris** [comment]
Would it make sense to do the storage usage collection less often, to minimize this?

**Comment by benesch** [comment]
Probably not worth it as a bandaid, IMO! An environment that OOMs every four hours is still real bad. 

I think we're out of the woods on this for now since we bumped the default `envd` memory allocation to 16GB. But it is still suspicious.

**Comment by benesch** [comment]
Closing as nonactionable.
