### ISSUE TITLE
arm: Rounding difference in test/sqllogictest/funcs.slt

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18746]
### What version of Materialize are you using?

c98ba6114f361bcf63a1d4ebaff425ca51652641

### How did you install Materialize?

Built from source

### What is the issue?

On Linux arm64:
```
[2023-04-12T16:02:55Z] ==> test/sqllogictest/funcs.slt
[2023-04-12T16:02:56Z]     SELECT cbrt(3::int)
[2023-04-12T16:02:56Z]     OutputFailure:test/sqllogictest/funcs.slt:410
[2023-04-12T16:02:56Z]             expected: Values(["1.4422495703074083"])
[2023-04-12T16:02:56Z]             actually: Values(["1.4422495703074085"])
[2023-04-12T16:02:56Z]             actual raw: [Row { columns: [Column { name: "cbrt", type: Float8 }] }]
[2023-04-12T16:02:56Z]     ----
```
Is this an expected based on different rounding on different CPU arch that we can live with? In that case I can look into adapting the test. But would be good to check first.
Found in https://buildkite.com/materialize/tests/builds/53499#01877628-21ef-44bc-95cb-c2b73033ad52

**Comment by antiguru** [comment]
Yes, I'd agree that this is likely from a difference in CPU architecture, although it is still surprising. At the moment, we don't offer too many guarantees around floating point evaluation, which means that we can swap operator order, which might have an impact on procision. Even setting parallelism might affect precision.. Ideally the tests compare floats using `|x-y| < eps` instead of using equality, which allows a certain amount of error.

Tagging @aalexandrov and @tokenrove for their opinion.

**Comment by tokenrove** [comment]
These differ by 1 ULP, which is to be expected.  Float comparisons should use an epsilon based on expected ULPs.

**Comment by tokenrove** [comment]
Also cbrt invokes libm's cbrt(3), which we'd expect to have minor differences not only between architectures but even libc implementations.

**Comment by antiguru** [comment]
Maybe we could change test to:
```
moritz=> SELECT cbrt(27::float8)::float4;
 cbrt
------
    3
(1 row)
```
