### ISSUE TITLE
SHOW SOURCES doesn't list sizes for sources created in an existing cluster

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#18855]
### What version of Materialize are you using?

v0.51.0 (9b4eae274)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When you create a cluster and replica for a source ahead of time and then create the source in that cluster using the `IN CLUSTER` option, the `SHOW SOURCES` command does not list the `size` for the source. 

For example, using the Kafka topics for our getting started guide (excluding the commands for creating secrets and connections):

```
CREATE CLUSTER ingest REPLICAS (small_replica (SIZE = '2xsmall'));

CREATE SOURCE items
  IN CLUSTER ingest
  FROM KAFKA CONNECTION kafka_connection (TOPIC 'mysql.shop.items')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_connection
  ENVELOPE DEBEZIUM;

CREATE SOURCE purchases
  IN CLUSTER ingest
  FROM KAFKA CONNECTION kafka_connection (TOPIC 'mysql.shop.purchases')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_connection
  ENVELOPE DEBEZIUM;

SHOW SOURCES;

        name        |   type    | size
--------------------+-----------+------
 items              | kafka     |
 items_progress     | subsource |
 purchases          | kafka     |
 purchases_progress | subsource |
(4 rows)
```

When you create the cluster and replica with the source using the `WITH SIZE` option, the size shows up fine.

**Comment by morsapaes** [comment]
This is expected, after [Cloud #4929](https://github.com/MaterializeInc/cloud/issues/4929). The `SIZE` option was kept as an interim option ahead of implementing multi-purpose clusters to avoid confusion as to why you can't create sources/sinks and materialized views/indexes in the same cluster. When you use `SIZE`, a dedicated _linked cluster_ is created, along with a replica with the specified size (_i.e._ a pod); when you use `IN CLUSTER`, the source uses resources in the existing cluster, so it makes sense that no size is displayed. Once the work is completed, `SIZE` will be deprecated and the `IN CLUSTER` clause will be optional (by default, a source/sink will be created in the active cluster). There's more context around this [here](https://www.notion.so/materialize/Cluster-unification-472efd2e9b8d4286bacc91b84d6b6f71).

This hasn't been a source of confusion because we've had a FE built into the onboarding process so far, and linked clusters were never exposed as a user-facing concepts since the intent was for them to be disappear in the short-term (as noted in the [v0.39 release notes](https://materialize.com/docs/releases/v0.39/#v0390)). To be fair, I expected all phases of the unification work to be implemented in sequence, but the remaining work has been deprioritized (AFAIU). @frankmcsherry: rounding off the unification work with multi-purpose clusters would help streamline onboarding, as well as reduce the upfront number of clusters and cluster replicas needed to get started.

**Comment by jseldess** [comment]
Thanks for the context and history, @morsapaes! Feel free to close this.
