### ISSUE TITLE
`EXPECTED GROUP SIZE` used to mean `EXPECTED GROUP COUNT`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#18883]
### What version of Materialize are you using?

main

### How did you install Materialize?

Docker image

### What is the issue?

In https://github.com/MaterializeInc/materialize/pull/18606 we landed changes that use the `EXPECTED GROUP SIZE` option to inform both hierarchical group planning and top k planning. For example, in 
```sql
SELECT
    sum(revenue) AS revenue
FROM (
    SELECT l_orderkey,
           sum(l_extendedprice * (1 - l_discount)) AS revenue
    FROM lineitem
    GROUP BY l_orderkey
    OPTIONS (EXPECTED GROUP SIZE = 7)
    ORDER BY revenue DESC
    LIMIT 10
);
```
the `EXPECTED GROUP SIZE = 7` supplies the hint that both each group by `l_orderkey` expects to have seven elements, and also that we expect to have seven distinct `l_orderkey`s.

I believe it will be confusing for `EXPECTED GROUP SIZE` to describe what is perhaps better described as `EXPECTED GROUP COUNT` as the two are fundamentally unrelated. It seems not hard to introduce `EXPECTED GROUP COUNT` in addition, with the added benefit that you can use both in the same query with different values.

**Comment by benesch** [comment]
cc @tokenrove @vmarcos @teskje

**Comment by teskje** [comment]
Seems like a fine suggestion to me. Also shouldn't be hard to implement, if @tokenrove and @vmarcos agree.

**Comment by vmarcos** [comment]
Just to clarify this further, is the proposal here to default to `EXPECTED GROUP SIZE` and then only allow for `EXPECTED GROUP COUNT` when there is ambiguity? Or is it to use `EXPECTED GROUP SIZE` for reductions and `EXPECTED GROUP COUNT` for top-k queries?

Consider the following top-k query specified with a `LATERAL` pattern:

```sql
CREATE TABLE cities (
    name text NOT NULL,
    state text NOT NULL,
    pop int
);

SELECT state, name FROM
    (SELECT DISTINCT state FROM cities) grp,
    LATERAL (SELECT name FROM cities WHERE state = grp.state
             OPTIONS (EXPECTED GROUP SIZE = 1)
             ORDER BY pop DESC NULLS LAST LIMIT 3);
```

It seems to me that above we'd really like to say `EXPECTED GROUP SIZE` and not `EXPECTED GROUP COUNT`, since we want not the number of states but rather the number of cities per state? So would it be a bug to allow for `EXPECTED GROUP COUNT` in such a formulation?

Now, let's revise the example a bit:

```sql
CREATE TABLE cities (
    name text NOT NULL,
    state text NOT NULL
);

CREATE TABLE counties (
    city text NOT NULL,
    state text NOT NULL,
    county text NOT NULL,
    pop int
);

SELECT state, city, max_county_pop FROM
    (SELECT DISTINCT state FROM cities) grp,
    LATERAL (SELECT city, max(pop) as max_county_pop FROM counties WHERE state = grp.state
             GROUP BY city
             OPTIONS (EXPECTED GROUP SIZE = 50, EXPECTED GROUP COUNT = 100)
             ORDER BY max_county_pop DESC NULLS LAST LIMIT 3);
```

In the above formulation, it would make sense to say both `EXPECTED GROUP SIZE` (number of counties per city) as well as `EXPECTED GROUP COUNT` (number of cities per state), where the former would be applied to the reduction and the latter to the top-k computation.

**Comment by tokenrove** [comment]
It seems to me that this issue might be better broadened to encompass rethinking query hints for rendering: how they're parsed and what their semantics should be, since it's also quite tricky to get these options in the right place, and it's not clear to me that this bandaid is the right one.

**Comment by vmarcos** [comment]
Given the recent work on  `mz_expected_group_size_advice` (#21077), I have a proposal so that we can work on an MVP for this issue:

1. Let's implement Frank's syntax suggestion of an `EXPECTED GROUP COUNT` applying to top-k only in the case that the input to the top-k computation comes from a reduction as outlined in the examples of https://github.com/MaterializeInc/materialize/issues/18883#issuecomment-1517596850. 
2. When an hint is not used, we just do not emit any errors nor notices.
3. The `EXPECTED GROUP COUNT` syntax can be mapped internally to the `expected_group_size` of `TopK` when the `TopK` is on the results of a reduction and ignored otherwise, and we can keep the remaining implementation untouched.
   
The suggestion above has the following characteristics:
  * We still get to keep to semantic hints, which are more in line with the current product design.
  * In the current product, we do not provide any errors or notices on hints not applying, so we can keep the same consistent behavior for the `EXPECTED GROUP COUNT`. This is also how most DBMS treat query hints.
  * We do not have to adapt the implementation substantially throughout the code as the `EXPECTED GROUP COUNT` would just be mapped internally to the `expected_group_size` field of `TopK` in very specific conditions. This does have the disadvantage that someone reading `EXPLAIN` output would not see the string `exp_group_count`, but rather `exp_group_size` for the `TopK`. This is an understandability price to pay for no changes in MIR nodes, but we'd be accepting a trade-off to get more simplicity for the change.

The path above has the plus of being implementable without a more involved design. In addition, when two different suggestions come out of `mz_expected_group_size_advice` that apply to the same query block, then we would be able get the best tuning and memory reduction by being able to supply two different hints when there is ambiguity.

**Comment by aalexandrov** [comment]
> We do not have to adapt the implementation substantially throughout the code as the `EXPECTED GROUP COUNT` would just be mapped internally to the `expected_group_size` field of `TopK` in very specific conditions.

Why cant you just rename the `TopK` field?

**Comment by teskje** [comment]
Here is another query where this query hint came up in the past:

```
select distinct on (a) a, b from t options (expected group size 15) order by a;
```

This is optimized to this dataflow:
```
                  Optimized Plan
---------------------------------------------------
 Explained Query:                                 +
   Finish order_by=[#0 asc nulls_last] output=[#0]+
     TopK group_by=[#0] limit=1 exp_group_size=15 +
       Get materialize.public.t                   +

(1 row)
```

**Comment by vmarcos** [comment]
Results from our weekly team discussion: There was convergence that the best trade-off between understandability and change simplicity would come from taking the approach of hints being about configuring low-level operators instead of the approach of hints being about semantic properties as discussed in https://github.com/MaterializeInc/materialize/issues/18883#issuecomment-1581171470. I will follow up with a short design document to iron out syntax and backwards compatibility.

**Comment by frankmcsherry** [comment]
Fwiw, I think I might be wrong that `EXPECTED GROUP COUNT` is the right term. In the example above, it is the number of groups that feed in to the `LIMIT`, but in some other world there may not be groups at all. I'm not sure what you call it then (I'm not sure I understand the grammatic fragment), but it's something about `EXPECTED LIMIT SIZE` maybe?

**Comment by aalexandrov** [comment]
> but in some other world there may not be groups at all.

This is why I suggested `EXPECTED RESULT SIZE` above. I think there are two alternative approaches:

1. Design the hints around the SQL syntax (these are called "semantic hints" above).
2. Design the hints around the `MiRelationExpr` syntax (I think these are called "syntactic" or "low-level" hints) below.

Although (2) sounds appealing, it suffers from the that the `SELECT` block that the `OPTIONS` block annotates might be planned using more than one `MirRelationExpr` operator of the same kind. For example, given

```sql
CREATE TABLE r(x int, y int, z int);
```
the output of
```
EXPLAIN RAW PLAN FOR SELECT * FROM (SELECT DISTINCT ON(x) * FROM r LIMIT 10);
```
contains two `TopK` operators:
```
+------------------------------+
| Raw Plan                     |
|------------------------------|
| TopK limit=10                |
|   TopK group_by=[#0] limit=1 |
|     Get materialize.public.r |
+------------------------------+
```

**Comment by ggevay** [comment]
> contains two TopK operators

But there are also two SELECTs, so we can put the EXPECTED TOPK GROUP SIZE hint on either the inner or the outer one.

**Comment by aalexandrov** [comment]
> But there are also two SELECTs, so we can put the EXPECTED TOPK GROUP SIZE hint on either the inner or the outer one.

I guess you can write

```sql
SELECT * 
FROM (
  SELECT DISTINCT ON(x) *
  FROM r
  OPTIONS (TOPK GROUP SIZE 15)
  LIMIT 10
)
OPTIONS (TOPK GROUP SIZE 10)
```

to set different parameter values for the inner and the outer select.

**Comment by ggevay** [comment]
> Note that both TopK operators result from planning the inner SELECT.

Hmm, you are right. One TopK comes from the DISTINCT ON, and one comes from the LIMIT.

**Comment by vmarcos** [comment]
Woudn't a workaround here be to rewrite the SQL into two blocks? For example:
```sql
SELECT * 
FROM (
  SELECT DISTINCT ON(x) *
  FROM r
  OPTIONS (EXPECTED GROUP SIZE 15)
)
OPTIONS (EXPECTED GROUP SIZE 10)
LIMIT 10;
```
I tried the above out, but the second hint seems to be ignored:
```
materialize=> explain plan for materialized view mv;
                  Optimized Plan                  
--------------------------------------------------
 materialize.public.mv:                          +
   TopK limit=10                                 +
     TopK group_by=[#0] limit=1 exp_group_size=15+
       Get materialize.public.r                  +
 
(1 row)
```
But that is probably a separate bug. The main problem we are discussing here is how to break the ambiguity within a single query block without the workaround, right?

By the way: The workaround of breaking the query into multiple query blocks works for the query at the top of the issue. I will capture this in the design doc as well.

**Comment by aalexandrov** [comment]
> The main problem we are discussing here is how to break the ambiguity within a single query block without the workaround, right?

Yes, this was my intention.
