### ISSUE TITLE
LaunchDarkly gets wedged and stops updating

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#18941]
### What version of Materialize are you using?

v0.51.0

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When doing a routine update of the `max_sources` parameter from 25 to 50 for a customer, we found that the change was not properly being picked up by by LaunchDarkly, i.e., `SHOW max_sources` continued to report 25. Furthermore, `ALTER SYSTEM SET max_sources=50` did nothing, as it was quickly overwritten back to 25. A lack of logging prevented me from finding out what was going on in the LD client, so we have no idea what was causing this.

However, note that it was present in multiple prod environments (both the customer and our prod sandbox), so this is probably a critical issue.

The workaround is to reboot, after which the new values get picked up and LD gets unstuck.

**Comment by umanwizard** [comment]
Open support request with LaunchDarkly: https://support.launchdarkly.com/hc/en-us/requests/40165

**Comment by aalexandrov** [comment]
Actions taken so far (feel free to edit this message as we make further progress):

1. A that will allow us to temporary disable sync landed in #18951 thanks to @umanwizard.
1. I've identified a pattern where several environments got wedged in a similar way after receiving an "end of stream" event (details are in the linked LaunchDarkly support request).
1. I've bumped up logging of one of our DevEx environment to "launchdarkly_server_sdk=debug,eventsource_client=debug,info", so we can get more insights when this happens next time. We might have to fine-tune this if the log of that environment is chatty.

**Comment by benesch** [comment]
We believe that fixing the Cilium bug may mitigate this issue. @arusahni set up a personal stack with the _broken_ version of Cilium so that @aalexandrov can keep debugging. Details here on Slack: https://materializeinc.slack.com/archives/CTESPM7FU/p1682685687925629?thread_ts=1682628989.195099&cid=CTESPM7FU

**Comment by benesch** [comment]
I spent some time looking into the LaunchDarkly protocol today. Server-side SDKs are pushed flag updates via a server-sent events (SSE) stream at https://stream.launchdarkly.com/all. The protocol is very simple, and can easily be observed with `curl`. Here's a snapshot of me `curl`ing the production SSE stream earlier today:

```
$ curl -NfsSLH 'Authorization: <REDACTED>' https://stream.launchdarkly.com/all | ts '%b %d %H:%M:%.S'
May 07 13:42:54.709355 event:put
May 07 13:42:54.736370 data:{"path":"/","data":{"segments":{"capacity_customer"...
May 07 13:42:54.737559 
May 07 13:42:54.737582 :
May 07 13:42:54.737593 :
May 07 13:45:54.711407 :
May 07 13:48:54.710810 :
May 07 13:51:54.811593 :
May 07 13:54:54.712194 :
May 07 13:57:54.754269 :
May 07 13:59:53.137807 event:patch
May 07 13:59:53.137908 data:{"data":{"clientSide":false,"clientSideAvailability"...
May 07 13:59:53.137935 
May 07 14:00:19.347011 event:patch
May 07 14:00:19.347117 data:{"data":{"clientSide":false,"clientSideAvailability"...
May 07 14:00:19.347144 
May 07 14:00:54.717240 :
May 07 14:03:54.800786 :
May 07 14:06:54.719937 :
May 07 14:09:54.720762 :
May 07 14:12:54.721756 :
May 07 14:15:54.784162 :
May 07 14:18:54.723312 :
May 07 14:21:54.827091 :
May 07 14:24:54.725685 :
```

Notice how every 3m we receive a message that is simply `:`. This is an SSE comment, and is a keep-alive message from the server. If we don't receive these keep-alive messages after, say, 10m, that is a very strong signal that the connection is broken.

I think we should instead patch the LaunchDarkly client to expose a callback whenever an SSE event is received by the client. Then we can provide a callback which updates a Prometheus gauge to the current time. We can prominently display that metric in Grafana, and possibly even alert on it.

@aalexandrov [proposed on Slack](https://materializeinc.slack.com/archives/C0462P62MRQ/p1683127454744239) that we implement our own form of failure detection by flipping a known flag value back and forth every 30-60m. I think patching the LD client directly has several advantages over the flag-flipping approach:

  * We can detect failures in <5m, rather than in 30 or 60m.
  * Applies uniformly to CI, staging, and production environments.
  * No additional infrastructure to run. That means a shorter path to alerting on this metric. (It's a bit scary to need to alert on a sentinel flag flipping happening every 60m; that means the job that flips the flag is a critical part of prod infrastructure, as if that job stops working then we'll have spurious alerts about not observing the flag flipping.)

The downside, of course, is that we have to maintain a fork of the LD client, but:

  1. We already do.
  2. This seems like a patch they'd be happy to accept upstream.

**Comment by necaris** [comment]
I like this plan of just listening in on the SSE stream (in general, I don't think SSE is used enough ;-))!

**Comment by benesch** [comment]
@aalexandrov mentioned on Slack that we already attempt to do this, I think via https://github.com/MaterializeInc/rust-server-sdk/commit/dcda26dad12a871795a6958ef238536c27c67164. However, my read of that code is that we're executing a callback every time we successfully report an event from client -> server. But what was breaking was events from server -> client!

The code for events from server -> client lives here: https://github.com/launchdarkly/rust-server-sdk/blob/296fa3fa26c382566d6c30730adb797b3ddf7b97/launchdarkly-server-sdk/src/data_source.rs#L148

I think the answer is we want callbacks and metrics for _both_. We want both the last time the client successfully contacted the server _and_ the last time the server successfully contacted the client.

This also presuambly explains why the LD UI was showing "last heard from client at <...>", even for broken environments. I bet those environments were successfully reporting client -> server events the whole time, since those go through separate short-lived TCP connections.

**Comment by aalexandrov** [comment]
> I think the answer is we want callbacks and metrics for both. We want both the last time the client successfully contacted the server and the last time the server successfully contacted the client.

@benesch I tagged to for review of a PR that implements the proposed approach in MaterializeInc/rust-server-sdk#1

**Comment by benesch** [comment]
Thanks, left some comments there!
