### ISSUE TITLE
Adding support for CREATE IF NOT EXISTS for views

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#1899]
We currently support CREATE IF NOT EXISTS for sources, but not for views. We currently only support CREATE OR REPLACE for views.

**Comment by kujon** [comment]
Can I claim it, please? 🤚

**Comment by benesch** [comment]
Hi @kujon, thanks for your interest in helping out!

This issue is a priority for our next release, so we’re likely to have someone working on this by the beginning of March. If you think you can get it done by then, please feel free! Just know that we may need to take over work on this issue as we approach the deadline for our next release.

We have some other good first issues that our off the critical path, too. For example: https://github.com/MaterializeInc/materialize/issues/1734

**Comment by kujon** [comment]
Thanks for getting back so quickly @benesch. I've got a prototype [here](https://github.com/MaterializeInc/materialize/pull/2080). Need to add some tests.

**Comment by wangandi** [comment]
Resolved by #2080
