### ISSUE TITLE
Unclear error message: ERROR:  must be owner of TABLE materialize.public.atest1

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19004]
### What version of Materialize are you using?

https://github.com/MaterializeInc/materialize/pull/18980

### How did you install Materialize?

Built from source

### What is the issue?

The error message indicates that only the owner has this permission, but superuser also does. In Postgres the error message is less specific: `WARNING:  no privileges were granted for "atest1"`

**Comment by jkosh44** [comment]
What's the specific scenario for this error message?

**Comment by def-** [comment]
```
materialize=> GRANT SELECT ON atest1 TO PUBLIC;
ERROR:  must be owner of TABLE materialize.public.atest1
```

**Comment by jkosh44** [comment]
I think actually this error message is fine as is. In general PostgreSQL tries to avoid mentioning that superusers could have performed the following action. superusers can do any action, so including that in every error message would be overly verbose and redundant.

In this specific scenario in PostgreSQL, in order to grant a privilege you must have a grant option for that privilege, which is why they don't only say "must be owner of ...". In Materialize we don't have a concept of grant options, so only owners (and superusers) can grant privileges. 

In PostgreSQL, when only an owner (or superuser) can perform some action, then they'll have an error message of the format "Must be owner ...". For example, 
```
postgres=# CREATE ROLE r1;
CREATE ROLE
postgres=# CREATE TABLE t ();
CREATE TABLE
postgres=# SET ROLE r1;
SET
postgres=> DROP TABLE t;
ERROR:  must be owner of table t
```
Even though any superuser could have dropped that table.

Thoughts?
