### ISSUE TITLE
adapter: `depends_on` set is not always accurate

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#19080]
### What version of Materialize are you using?

v0.53.0-dev

### What is the issue?

Before planning a statement we [generate a set](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/coord/command_handler.rs#L469-L472) of `GlobalId`s that we depend on with name resolution. This set is not always accurate as our set of dependencies can change after planning. For example, `SHOW INDEXES on <table>`, based on name resolution we have a dependency on `<table>`, but after planning our only dependency is on a system table.

@jkosh44 and I were talking and we think we should probably add a method called `depends_on(...)` to the `enum Plan` that returns the set of `GlobalId`s. In the common case name resolution is probably enough, but the `Plan` should be the source of truth.

**Comment by jkosh44** [comment]
This is likely related to #18908

**Comment by jkosh44** [comment]
> @jkosh44 and I were talking and we think we should probably add a method called depends_on(...) to the enum Plan that returns the set of GlobalIds. In the common case name resolution is probably enough, but the Plan should be the source of truth.

I looked into this briefly, it works very well for DML, like `SELECT` and `INSERT`, but not very well for any other plans. For example `CREATE CONNECTION` has no good way of extracting all of the referenced global IDs.

**Comment by benesch** [comment]
I think the trouble here stems from confusion about what a dependency is. I contend there are two important meanings of "dependency":

  1. An object required while planning an `mz_sql_parser::ast::Statement`.
  2. An object required to determine the timestamp of a `MirRelationExpr` in a plan.

Part of what's funny here is that (1) and (2) can be disjoint sets! As @ParkMyCar points out in the issue description, with a query like `SHOW INDEXES on <table>`, (1) depends only on `<table>` while (2) depends only on `mz_indexes`.

Notably, I'm not sure "what does this `Plan` depend on?" is a useful question to ask? Who cares? I mean that in the genuine sense. I'm not sure what component cares, in the general sense, about what a particular `Plan` depends on. The catalog cares about what objects needed to exist to _produce_ that plan, and the sequencer cares, for select/insert/update plans, what dependencies need to be considered for timestamp selection, but neither component cares about other `GlobalId` fields hanging out in the `Plan`.

With this framing, let's take another look at https://github.com/MaterializeInc/materialize/pull/19648. The original code computed (1)-style dependencies and used them in two places: one place where (1)-style dependencies were called for, and one place where (2)-style dependencies were called for. The new code computes (2)-style dependencies and uses them in both places—fixing one bug but making another bug! I think the fix, then, is to compute _both_ (1)-style and (2)-style dependencies, and use each in the appropriate place.

Having paged all this in, I think the original issue, as filed, is not correct! Let me explain.

> Before planning a statement we [generate a set](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/coord/command_handler.rs#L469-L472) of GlobalIds that we depend on with name resolution. This set is not always accurate as our set of dependencies can change after planning. For example, SHOW INDEXES on <table>, based on name resolution we have a dependency on <table>, but after planning our only dependency is on a system table.

In fact the set _is_ accurate ... for (1)-style dependencies, which is all that `depends_on` is meant to reflect here.

So I think the bug here is really that this is all massively confusing and underdocumented, even though it's technically "in spec."

**Comment by benesch** [comment]
> I think the trouble here stems from confusion about what a dependency is. I contend there are two important meanings of "dependency":
> 
> 1. An object required while planning an `mz_sql_parser::ast::Statement`.
> 2. An object required to determine the timestamp of a `MirRelationExpr` in a plan.
> 
> Part of what's funny here is that (1) and (2) can be disjoint sets! As @ParkMyCar points out in the issue description, with a query like `SHOW INDEXES on <table>`, (1) depends only on `<table>` while (2) depends only on `mz_indexes`.
> 
> Notably, I'm not sure "what does this `Plan` depend on?" is a useful question to ask? Who cares? I mean that in the genuine sense. I'm not sure what component cares, in the general sense, about what a particular `Plan` depends on. The catalog cares about what objects needed to exist to _produce_ that plan, and the sequencer cares, for select/insert/update plans, what dependencies need to be considered for timestamp selection, but neither component cares about other `GlobalId` fields hanging out in the `Plan`.
> 
> With this framing, let's take another look at #19648. The original code computed (1)-style dependencies and used them in two places: one place where (1)-style dependencies were called for, and one place where (2)-style dependencies were called for. The new code computes (2)-style dependencies and uses them in both places—fixing one bug but making another bug! I think the fix, then, is to compute _both_ (1)-style and (2)-style dependencies, and use each in the appropriate place.
> 
> Having paged all this in, I think the original issue, as filed, is not correct! Let me explain.
> 
> > Before planning a statement we [generate a set](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/coord/command_handler.rs#L469-L472) of GlobalIds that we depend on with name resolution. This set is not always accurate as our set of dependencies can change after planning. For example, `SHOW INDEXES on <table>`, based on name resolution we have a dependency on `<table>`, but after planning our only dependency is on a system table.
> 
> In fact the set _is_ accurate ... for (1)-style dependencies, which is all that `depends_on` is meant to reflect here.
> 
> So I think the bug here is really that this is all massively confusing and underdocumented, even though it's technically "in spec."

I put up https://github.com/MaterializeInc/materialize/pull/20319 to use type safety to enforce good behavior.

**Comment by jkosh44** [comment]
> I think the trouble here stems from confusion about what a dependency is. I contend there are two important meanings of "dependency":
> 
>   1. An object required while planning an `mz_sql_parser::ast::Statement`.
> 
>   2. An object required to determine the timestamp of a `MirRelationExpr` in a plan.
> 
> 
> Part of what's funny here is that (1) and (2) can be disjoint sets! As @ParkMyCar points out in the issue description, with a query like `SHOW INDEXES on <table>`, (1) depends only on `<table>` while (2) depends only on `mz_indexes`.

We have another similar issue to this (https://github.com/MaterializeInc/materialize/issues/23153), so I'm revisiting our current understanding of dependencies. I don't fully understand why `mz_indexes` is not in set (1). We substitute `SHOW INDEXES ON <table>` for `SELECT _ FROM mz_indexes WHERE id = <table_id>` during planning. If for whatever reason `mz_indexes` didn't exist, then planning would fail. So I would argue that planning does in fact rely on `mz_indexes` and `mz_indexes` should belong to both set (1) and (2).

There may actually be three important meanings of "dependency":

1. An object required while planning an `mz_sql_parser::ast::Statement`. 
2. An object required to determine the timestamp of a `MirRelationExpr` in a plan.
3. An object directly referenced in SQL. This is useful for RBAC (and maybe other things), we don't want to require permissions on objects used to implement functions/casts.

Right now we're using (3) in every place where we should be using (3) and (1).

**Comment by benesch** [comment]
> There may actually be three important meanings of "dependency":
>
> 1. An object required while planning an `mz_sql_parser::ast::Statement`.
> 2. An object required to determine the timestamp of a `MirRelationExpr` in a plan.
> 3. An object directly referenced in SQL. This is useful for RBAC (and maybe other things), we don't want to require permissions on objects used to implement functions/casts.
> 
> Right now we're using (3) in every place where we should be using (3) and (1).

This sounds right to me!
