### ISSUE TITLE
AssertionError: "since" timestamp of mv (1683879932799) is less than "since" timestamp of its source table (1683879933000)

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19243]
### What version of Materialize are you using?

d5bd7d4691f7fb7340c69af84b5334c5615ffccf

### What is the issue?

Running `bin/mzcompose --release --find cluster run test-mv-source-sink` a few times locally I still sporadically get a failure with the materialized view having an older timestamp than the source table:
```
mzcompose: test case workflow-test-mv-source-sink failed:
Traceback (most recent call last):
  File "/home/deen/git/materialize2/misc/python/materialize/mzcompose/__init__.py", line 416, in test_case
    yield
  File "/home/deen/git/materialize2/misc/python/materialize/cli/mzcompose.py", line 589, in handle_composition
    composition.workflow(args.workflow, *args.unknown_subargs[1:])
  File "/home/deen/git/materialize2/misc/python/materialize/mzcompose/__init__.py", line 332, in workflow
    func(self)
  File "/home/deen/git/materialize2/test/cluster/mzcompose.py", line 1475, in workflow_test_mv_source_sink
    assert (
AssertionError: "since" timestamp of mv (1683880144289) is less than "since" timestamp of its source table (1683880145000)
```
I modified my change to make it fail reliably in CI too: https://github.com/MaterializeInc/materialize/pull/19238/commits/9e9f895426b3ca9912664a62f41d0e9318b5d0a0 Edit: My attempts to make it reproduce in CI failed, but locally it's easy, so that's strange.

Follow-up to https://github.com/MaterializeInc/materialize/issues/19151

**Comment by sploiselle** [comment]
@jkosh44 Is there a chance this test/issue shows an issue with strict serializability? Glad to chat to provide more context if it's not totally clear.

**Comment by jkosh44** [comment]
This is maybe related to this issue: https://github.com/MaterializeInc/materialize/issues/18561? I haven't looked at `since` initialization in awhile, but I wouldn't be surprised if the initial `since` of a Materialized View did not account for the current `since` of all dependent objects.

> Is there a chance this test/issue shows an issue with strict serializability?

I'm not sure it's an issue with strict serializability specifically or some other correctness property, but either way it is probably a violation of some correctness property.

**Comment by jkosh44** [comment]
@def- This the test that's flaky right: https://github.com/MaterializeInc/materialize/blob/1632d531f5dc9d5eaa53f0f65f7a1cde4d53829c/test/cluster/mzcompose.py#L1469-L1477?

I think we should just remove that assert since in general it's not guaranteed to be true. For example, it's possible that the source was compacted before the materialized view was compacted and in terms of correctness that's totally fine.

**Comment by def-** [comment]
Right, should this change be generally correct? https://github.com/MaterializeInc/materialize/pull/19255
