### ISSUE TITLE
MFP Pushdown: Access to unrelated tables is slowed down by MFP pushdown

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#19402]
### What version of Materialize are you using?

v0.56.0-dev (e03849c)

### What is the issue?

With the test cases from #19400 and #19399 , clusterd begins to spin at 100% on one core. However, this prevents unrelated queries from being answered using the remaining workers.

To reproduce, use the test case from #19399 and run the slow `SELECT` query in a loop . In a separate console:

```
materialize=> create table t2 (f1 integer);
CREATE TABLE
materialize=> insert into t2 values (1);
INSERT 0 1
materialize=> \timing on
Timing is on.
materialize=> select * from t2;
 f1 
----
  1
(1 row)

Time: 3655.738 ms (00:03.656)
```

**Comment by bkirwi** [comment]
> However, this prevents unrelated queries from being answered using the remaining workers.

I think the story here is that all filter pushdowns in a dataflow are evaluated on a single arbitrarily chosen worker. Classically this is pretty cheap, and we've never avoided assigning more work to that arbitrary worker, but if that worker is blocked than all dataflows will stop making progress.

I think the linked tickets have the same underlying cause that we have a tentative fix for. But we'll see how things look once #19399 is complete!

**Comment by bkirwi** [comment]
#19448 fixed the underlying issue here.

The outstanding question is: is it a problem that that bug was able to block other dataflows?

In general, a hung thread in any dataflow is able to prevent that worker from making progress on that or any other dataflows, which will bring the whole replica to a standstill. So to a certain extent this is just a property of timely.

The usual approach to dealing with blocking / CPU-intensive code is to fork it off to a background task, and that would work well here too. However: this code is not supposed to be CPU-intensive! So currently that task would have almost no work to do. Any task-forking we do here would be purely defensive.

My current feeling is that it's not worth adding overhead to every filter call to protect us against slowness in the interpreter, given that this has only happened once and was a straightforward fix. However: if we end up making the interpreter slower, or we have more difficult performance bugs there, I would change my mind about this!

So I think this can be closed for now... but I'll leave it open for a couple days in case folks disagree with anything above.
