### ISSUE TITLE
add crash reporting

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1943]
[Sentry](https://sentry.io) makes crash reporting much more pleasant to collect, we should consider adding this.

**Comment by benesch** [comment]
Just noting that Sentry isn't really built for this use case. It's not clear there's a better product out there, but we should at least do a search.

**Comment by ruchirK** [comment]
I think this is what Backtrace was made for + they have Rust support and a free tier https://backtrace.io/for/rust/

**Comment by sploiselle** [comment]
# Integrating crash reporting into Materialize

Generating crash reports largely requires:

1. Generating `minidump` files from code during errors 

1. Sending these `minidump` files from a crashed client to some central server
that aggregates all crashes.

## Generating `minidump` files

There are two standard bearers in generating `minidump` files, both from Google:

- [Breakpad](https://github.com/google/breakpad) 

- [Crashpad](https://chromium.googlesource.com/crashpad/crashpad/), Breakpad's
successor

### Breakpad vs. Crashpad

Breakpad's `minidump` generation and sending is done in-process, which means it
cannot send reports for errors when killed by the OS, e.g. segfaults.

Crashpad was Google's solution to this shortcoming by creating a secondary
process that runs alongside your primary application and detects if it's killed.
However, in all of my reading, this sounds as if it must be a separate
executable shipped alongside your binary.

## Aggregating `minidump` files

There are, again, two prime candidates for aggregating crash data:

- [Backtrace](https://backtrace.io/) 

- [Sentry](https://docs.sentry.io/platforms/native/minidump/)

### Backtrace vs Sentry

Sentry's documentation is much more mature than Backtrace's but I haven't had a
change to use either of their interfaces to compare their products directly.

Some people on the team have had more experience with Sentry that they have
found dissuasive, but it seems like we'd be using the tool slightly differently
than previous teams they've been on have, so I don't think we should disqualify
it.

# Assessment

For generating `minidump` files, I believe that **Breakpad** is the better
solution because:

- Lets us continue distributing a single binary

- Its downside of not being able to report errors like segfaults is largely
mitigated by Rust's memory safety

For aggregating `minidump` files, I am going to continue exploring. Fortunately,
this is a fairly straightforward change to make at any point, as Breakpad only
requires changing a single line of code to send crash reports to different
servers.

# Integration

The work of actually integrating Breakpad is still a todo, and the UX is totally undetermined. The idea here is to gate error reporting behind some kind of user acknowledgement, but TBD what that looks like.

**Comment by benesch** [comment]
Thanks for digging in on all of this, Sean! I have some musings.

The first is that we shouldn't feel limited to deploying a single binary. I launched an eng@ discussion about this last December: https://groups.google.com/a/materialize.io/forum/?utm_medium=email&utm_source=footer#!msg/eng/4lNhg_iEN7k/NfAE3jsnAgAJ. The tl;dr is that I think Cockroach got unnecessarily hung up on the idea of "single binary deployment." I think the real goal is "dead simple deployment", and `apt-get` and `brew` and tarballs that you unpack into `/usr/local` can get you to that goal while also allowing you to distribute multiple binaries.

All that to say that I don't think we should necessarily discount Crashpad just because it runs out of process. There's enough C/C++/unsafe code in our dependencies that I'm sure we'll see some segfaults in time.

Have you looked into how either of these libraries would be integrated into Rust? AFAICT neither seems to have a good -sys crate on crates.io yet. There's https://crates.io/crates/libbreakpad-client-sys and https://crates.io/crates/breakpad but neither has seen an update in years.

There's also [sentry-rust](https://github.com/getsentry/sentry-rust), but I seem to remember you having some reservations about that library? Also it doesn't deal with minidumps at all, as far as I can see; it instead seems to parse Rust backtraces directly: https://github.com/getsentry/sentry-rust/blob/master/src/integrations/failure.rs.

**Comment by sploiselle** [comment]
Good to know about Crashpad's eligibility! If this is on the table, it certainly has its advantages. In my conversations with @cuongdo, he mentioned the strong preference for the CRL-style single binary, but I see that @rjnn has previously given the nod for shipping other tools alongside the primary binary.

As for integrating the tool, I looked into the configuration needed for Breakpad more extensively. Given that it's a deprecated project with a simple API, I assumed its API would be stagnant and that the library I was looking into (https://crates.io/crates/breakpad) not being updated wasn't surprising. Maybe this is foolhardy, but I was advised that "a lot of people" are still deploying apps with Breakpad, so wasn't too concerned. However, if we wanted to move forward with Crashpad, I'd need to do more digging.

The reservations with `sentry-rust` are:

- Locks you into Sentry, as opposed to being able to change aggregators by pointing the `minidump` uploads to another host.
- The library's event processing offers much more than we actually need for crash reporting. I figured this also needs more scoping out w/r/t user privacy to ensure we're appropriately ham-stringing the library to ensure it doesn't wind up capturing user data, when that really isn't what we're attempting to do with it.

Because of the above reasons, I didn't delve much further into it, given the popularity and prevalence of Break/Crashpad. Figured these would accomplish the same thing without the downside, and is what (unfairly) lead to my characterization that there was only one way to accomplish the kind of error reporting we wanted. I should've been more clear that the vendor-agnostic tools I found seem to largely rely on `minidump`, but other options might (and as you pointed out _do_) exist.

In the end, I'm hoping to perform more trials with this to ensure our commitment to an approach meets our needs. This isn't something I'm working on immediately, so glad to do more thorough research or field other options if they're things you suggest.

**Comment by benesch** [comment]
No, this is fantastic! Just wanted to get these discussions in while it’s all still fresh in your mind.

Re breakpad: yeah, the fact that it’s three years out of date isn’t hugely problematic on its own, but there is no associated Git repository that I can find, and it depends on some old versions of other crates that are fairly incompatible with the 2020 Rust ecosystem. I’ve been burned by this in the past—most crates on crates.io are unmaintained or broken—so my default state is sadly pessimistic these days. We’ll likely need to maintain our own breakpad- or crashpad-sys trait, which is totally doable (we’re doing it now for libsasl2), but just one more thing to weigh.

**Comment by sploiselle** [comment]
Would this general disposition lean you to favoring Sentry overall, who handsomely pay people to maintain this compatibility for you? They have a [Native SDK](https://blog.sentry.io/2019/12/19/debugging-a-segfault-in-rust) that has fewer bells and whistles, while definitely working with Rust via FFI.

**Comment by benesch** [comment]
Not necessarily, actually! What they have you do in that blog post is essentially create a (bad) sys crate, and creating a good sys crate is left as an exercise to the reader. Since neither has a plug n play minidump based solution available it’s about the same amount of effort to integrate either, with the minidump route.

**Comment by cuongdo** [comment]
>  In my conversations with @cuongdo, he mentioned the strong preference for the CRL-style single binary, but I see that @rjnn has previously given the nod for shipping other tools alongside the primary binary.

I do not personally feel strongly about having a single binary -- I was echoing the general sentiment at the time. Let's make pragmatic decisions while trying to keep deployment relatively straightforward.

**Comment by quodlibetor** [comment]
I don't particularly care how many binaries we ship, but I do have a pretty strong opinion that _running_ a single binary should always do the right thing, or error loudly (but maybe suppressably). So if typing `materialized` in a shell requires another binary to be present that's fine.

We could also, I believe, embed some crashpad binary inside the materialized binary and just fork it on startup, keeping our binary deployment simple and impossible to mess up. It will make building more complex, but it'll reduce roadbumps to good crash reports.

---

Also, while we might not get many internal segfaults, I wouldn't be surprised if we create more memory leaks. If having an external process increases our likelihood of getting dumps on OOM-kill then that would be very much worth it.

**Comment by benesch** [comment]
Not to worry. That's how crashpad works. You need to have the crashpad helper binary on the system somewhere, but it will be automatically launched and daemonized by materialized.

**Comment by benesch** [comment]
This got done! #15005.
