### ISSUE TITLE
spill-to-disk: Data not cleaned up from disk on DROP SOURCE

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#19558]
### What version of Materialize are you using?

 v0.57.0-dev (0bc8fd30c)

### What is the issue?

After dropping the source, the data in the RocksDb directory remains.

So we have:

```

materialize=> show sources;
 name | type | size 
------+------+------
(0 rows)
```

and yet:

```
materialize@5efadb300ace:/mzdata/source_data$ du -h
258M	./u2-replica-4/u4/2
258M	./u2-replica-4/u4/1
258M	./u2-replica-4/u4/3
258M	./u2-replica-4/u4/0
1.1G	./u2-replica-4/u4
1.1G	./u2-replica-4
4.0K	./s2-replica-3
4.0K	./u1-replica-1
48K	./u3-replica-5/u8/2
48K	./u3-replica-5/u8/1
48K	./u3-replica-5/u8/3
48K	./u3-replica-5/u8/0
196K	./u3-replica-5/u8
200K	./u3-replica-5
4.0K	./s1-replica-2
1.1G	.
```

**Comment by philip-stoev** [comment]
@guswynn FYI

**Comment by benesch** [comment]
It's just the process orchestrator that will exhibit this problem, right? The Kubernetes orchestrator will offload the problem of allocating these scratch directories to Kubernetes, and so it's Kubernetes's problem to clean up the scratch directories.

So I'd suggest just adding a scope guard to the process orchestrator right here...

https://github.com/MaterializeInc/materialize/blob/0b3f914dc612d5ccc4ef0a0244f59e46172be909/src/orchestrator-process/src/lib.rs#L527

that removes the scratch directory when dropped. That will clear out the scratch directory for a cluster whenever `DROP CLUSTER` is run. Small chance that `environmentd` crashes after accepting a `DROP CLUSTER` command but before updating the process orchestrator for that dropped cluster but that's fine. We don't need 100% reliability out of the process orchestrator since it's just for local development.

But, wait, hang on, the problem is deeper than this, no? If you have `CREATE SOURCE ... IN CLUSTER`, and you drop that source, we ought to clean up _that source's_ scratch directory, no? We really need the double protection here. The cluster itself should clean up the per-source scratch directory if the source is dropped but the cluster lives on, and the process orchestrator should clean up the per-cluster scratch directory if the cluster is dropped along with it sources.

**Comment by moulimukherjee** [comment]
@guswynn Yup, this is on my list 👍
