### ISSUE TITLE
Improve tracing filter support for platform

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#19843]
Two main upgrades we should perform (see https://materializeinc.slack.com/archives/CM7ATT65S/p1686343764202809?thread_ts=1686336740.198459&cid=CM7ATT65S for context):

- [x] Change `Targets` to `EnvFilter`. This did not work when we first enabled per-layer filtering, as 
  - Note that there _may_ be some complexity here with the max-level: https://github.com/tokio-rs/tracing/issues/2413, so this change needs to be made carefully
- [ ] Change the dynamic filtering to use LaunchDarkly, instead of http requests.
   - Note that this config will need to be distributed over the compute command protocol

**Comment by guswynn** [comment]
@pH14 I think translating the `--log-filter` into a `--system-parameter-default` is fine, and if both are passed, ignore the `--log-filter`

**Comment by pH14** [comment]
Hm.. that's also turning out to have some tricky/subtle behavior because `--system-parameter-default` sets the _default_ value for a SystemVar, but if the SystemVar is already set to a non-default value, changing the default won't be picked up until the var is `reset` which feels non-obvious.

I kind of wonder if we want to deprecate `--log-filter` to be a real in-case-of-emergency-break-glass type knob that overrides the filter on startup (giving us the desired log level between init and building the catalog), but may be overwritten by LD /ServerVar updates at any time? Not sure...

**Comment by pH14** [comment]
Eh... talking myself into it, I think `--log-filter` will realistically only be used in local dev, and setting the initial SystemVar default + being able to toggle it dynamically in SQL should be sufficient for most use cases. There _can_ be weird edges (you set a dynamic value, restart `envd` with `--log-filter` and briefly see the right log lines before it re-syncs with the catalog and undoes the change) but hopefully few and far between.

**Comment by guswynn** [comment]
deprecating `--log-filter` seems totally reasonable to me!

**Comment by pH14** [comment]
What I'm leaning towards here is splitting the filtering into two components:

1. `mz_log_filter` / `mz_opentelemetry_filter` system vars
2. `--startup-log-filter` / `--startup-opentelemetry-filter` that apply before (1) is available. For `envd` this is the time until the catalog is accessed, for `clusterd` this is the time before it receives a compute/storage command with the updated filter system vars.

(1) makes it easy to manage the filters in the steady state, and (2) is for emergencies / folks who need to debug pre-catalog/rpc startup issues. We then deprecate and/or remove `--log-filter`, since it's an awkward middle ground that's not quite (1) nor (2) -- my vote is to just rip off the bandaid and remove `--log-filter` with an informative error message, but open to other softer approaches here.

I think this approach makes the nuances of filtering clear, and it also solves some tricky implementation-detail questions I've run into when trying to keep `--log-filter` around. Open to any feedback on this setup!

**Comment by benesch** [comment]
That's an absolutely great idea. I love it.

**Comment by pH14** [comment]
Rolled out EnvFilters + system vars, and https://github.com/MaterializeInc/materialize/pull/19973 to make sure our spans are well-behaved. All set here!

**Comment by guswynn** [comment]
thanks for pushing this through @pH14 !!
