### ISSUE TITLE
Docs: Aurora postgres LSN query doesn't work

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#19880]
### Documentation request

This query in step 4 doesn't work in Aurora:

```sql
SELECT extract(epoch from now() - pg_last_xact_replay_timestamp()) AS replica_lag;
```

Maybe we can come up with a query that's more agnostic of which particular flavor of Postgres is being used? Maybe something like:

```sql
SELECT
    slot_name,
    pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(),restart_lsn)) as replication_lag
FROM
    pg_replication_slots;
```

This is a data size behind rather than an amount of time behind.

### Affected Pages

- https://materialize.com/docs/ingest-data/postgres-amazon-aurora/

**Comment by benesch** [comment]
Good catch, @chuck-alt-delete! In fact the query we're currently recommending does not have the correct semantics, as far as we can tell!

The @petrosagg-approved query is _almost_ equivalent to your recommendation, except that 1) it uses `confirmed_flush_lsn` instead of `restart_lsn` and 2) it uses `pg_size_pretty` to humanize the bytes. I think Petros is right that we should be using `confirmed_flush_lsn` and not `restart_lsn`. Whether we use `pg_size_pretty` is purely a matter of taste. Difference between using and not using `pg_size_pretty` is shown below:

```
benesch=*# select pg_current_wal_lsn() -  confirmed_flush_lsn as replication_lag_bytes from pg_replication_slots;
 replication_lag_bytes 
-----------------------
                599008
(1 row)

benesch=*# select pg_size_pretty(pg_current_wal_lsn() - confirmed_flush_lsn) as replication_lag_bytes from pg_replication_slots;
 replication_lag_bytes 
-----------------------
 585 kB
(1 row)
```

The query I'd recommend is:

```sql
SELECT
    pg_size_pretty(pg_current_wal_lsn() - confirmed_flush_lsn)
    AS replication_lag_bytes
FROM pg_replication_slots
[WHERE slot_name = ...]
```

Users can determine the replication slot name associated with their PostgreSQL source in Materialize by querying `mz_internal.mz_postgres_sources`. For example:

```
materialize=> select * from mz_internal.mz_postgres_sources;
 id  |               replication_slot               
-----+----------------------------------------------
 u11 | materialize_7d298cf3c9d14552928473c77ada782c
(1 row)
```
