### ISSUE TITLE
Design doc for Webhook Source

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#19952]

**Comment by benesch** [comment]
Wanted to jot down some quick thoughts about sequencing. @ParkMyCar I'd try to do something like this if possible:

Work stream one:

  * A draft design doc that focuses on the `CREATE SOURCE` syntax and wrestles with the questions we were wrestling in in the meeting, like `INCLUDE HEADERS`. I would just stub out the implementation section for now.
  * A very hacky prototype that just wires up the parsing and planning, where the only outcome of creating an HTTP POST source is the installation of the HTTP handler that just echos the data to the terminal and then sleeps for a second. This will simulate what would happen when we actually commit the write to disk. 
  * Iteration on the doc/prototype in tandem, and actually testing the prototype against our [candidate webhook sources](https://github.com/MaterializeInc/materialize/issues/19951#issuecomment-1594107557) (Segment, GitHub, Slack is the current set) to shake out problems in the syntax etc. [Tailscale Funnel](https://tailscale.com/blog/introducing-tailscale-funnel/) or [ngrok](https://ngrok.com) are your friends here.
  * We should even consider putting the local prototype in DevEx/FE hands to see how they like it.

Work stream two: shake out the actual implementation in the storage controller. This too will probably require iterating on the design doc and a prototype in concert. 

I have a loose shape of the storage controller API/implementation in my head, but verbalizing it would require actually doing some amount of the work. What I can tell you is that for the thing I have in mind, the bones of the prototype shouldn't take more than a day or two of work for someone familiar with the storage controller—and that should be enough substantce to actually write the details into the design doc. @ParkMyCar / @petrosagg / @sploiselle — if you find that the prototype is taking vastly longer than this, give me a ping and we can put our heads together.

Once you've got those prototypes, you should be able to go back to the design doc and polish it up. 

FWIW, if it's helpful in making forward progress, you could even _merge_ that hacky prototype that just logs webhook contents to stdout, as long as the feature is behind an unsafe LD flag.

Let me know if that plan sounds crazy, or if it seems too prescriptive! I'm approaching this largely from the perspective of "what derisks as much work as possible up front", and that may be incompatible with the reality of the code in front of you.

**Comment by ParkMyCar** [comment]
Sorry @benesch I totally missed this comment earlier! Thanks for the guidance!

This sequencing largely sounds good to me, let's consider the design doc I already put up as a total draft and can iterate on it. Otherwise I'll start prototyping and get stuff in the adapter setup, e.g. parsing and HTTP endpoints. In terms of storage implementation, Sean and I met yesterday and I have a good idea of how to proceed, I'll work storage out as a second step in prototyping.

The only divergence I have from this plan would be the prioritization of features like `INCLUDE HEADERS`. What do you think about building literally the absolute minimum, i.e. support for just `CREATE SOURCE <name> FROM HTTP REQUESTS`, and getting that into a good enough state to ship behind a LaunchDarkly flag? Reason being, I think the best quality feedback we can get from users (internal or external) would be to give them a working source and let them build mat views on top of it. From there we figure out what is still missing, and prioritize that work, e.g. SQL syntax and implementation. Thoughts? :)

**Comment by benesch** [comment]
> In terms of storage implementation, Sean and I met yesterday and I have a good idea of how to proceed, I'll work storage out as a second step in prototyping.

Awesome! What you wrote in your design doc about the `monotonic_append` API seemed great.

> The only divergence I have from this plan would be the prioritization of features like `INCLUDE HEADERS`. What do you think about building literally the absolute minimum, i.e. support for just `CREATE SOURCE <name> FROM HTTP REQUESTS`, and getting that into a good enough state to ship behind a LaunchDarkly flag? Reason being, I think the best quality feedback we can get from users (internal or external) would be to give them a working source and let them build mat views on top of it. From there we figure out what is still missing, and prioritize that work, e.g. SQL syntax and implementation. Thoughts? :)

Ah, will be good to shake this out! I'm all for leaving header validation out of the internal MVP, but I left some comments on the design doc about why I think we need header validation before we turn this on for any real users.
