### ISSUE TITLE
An optimizer trace bug

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#19995]
### What version of Materialize are you using?

fd0a1285f400b39090bada00a1852598d2cf721c

### What is the issue?

[This trace](https://gist.github.com/ggevay/2d2262f6ff84af7370cea9cc8738f7df) has various issues:
- It shows as if `inline_views` turned the constant singleton into the empty constant, but this is not the case. (`NonNullRequirements` does this.)
- Stepping on from `inline_views` we get to `normalize_lets`, where the original Constant comes back.
- Hitting `n` a few more times, we arrive at `optimize/raw` according to the title in the right panel, but `optimize/raw` should have been earlier.

I obtained the trace from the constant folding example from [here](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1686919212265659?thread_ts=1686919149.040909&cid=C02PPB50ZHS).

@aalexandrov, could you please look into this? (not urgent)

**Comment by aalexandrov** [comment]
The `inline_views` plan is a smell, I'll investigate, thanks for reporting this!

> Hitting n a few more times, we arrive at optimize/raw according to the title in the right panel, but optimize/raw should have been earlier.

This is more of a feature in the optimizer in that hitting "n" will cycle through the stages, so after the last stage `optimize` you go back to `optimize/raw`.

**Comment by ggevay** [comment]
>> Hitting n a few more times, we arrive at optimize/raw according to the title in the right panel, but optimize/raw should have been earlier.

> This is more of a feature in the optimizer in that hitting "n" will cycle through the stages, so after the last stage optimize you go back to optimize/raw.

Oh, ok, sorry!

**Comment by aalexandrov** [comment]
Closing this, as this is most likely an issue with the UI, not the actual tracing infrastructure that lives in this repo.

I'll track the fix in the UI repo: MaterializeInc/mztrace-explorer#8.

**Comment by aalexandrov** [comment]
Urgh... this was a tricky one. 

At the moment the tracing code is going to use the "fast path plan" instead of the actual plan for every entry of type `DataflowDescription<OptimizedMirRelationExpr>` and `DataflowDescription<Plan>`:

https://github.com/MaterializeInc/materialize/blob/9e480a9d104d6a734937758062a787f4f217a20c/src/adapter/src/explain/optimizer_trace.rs#L120-L132

observe how `drain_explainable_entries` will map the `TracePlan<T>` into a `TracePlan<String>` by explaining either the plan representing by this entry or the `fast_path_plan` passed as an optional third parameter:

https://github.com/MaterializeInc/materialize/blob/9e480a9d104d6a734937758062a787f4f217a20c/src/adapter/src/explain/optimizer_trace.rs#L168-L183

If the `ExplainConfig::no_fast_path` parameter is turned on when rendering the explain output everything works as expected.
