### ISSUE TITLE
environmentd: make a second runtime for persist work

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#20042]
We have had 2 issues in the last few weeks where persist work took all available env CPU and did not pre-empt to other tokio tasks. We think a separate tokio runtime would allow the linux scheduler to pre-empt and thus not starve out other tasks, critically the coordinator task. Make a second runtime where we can put persist work.

**Comment by guswynn** [comment]
Cpu-bound work on a second runtime will help, but will still cause problems for other timer- and io- bound work on the same (persist) runtime. There is also some (probably unimportant) overhead to running extra runtimes.

There is some more information here: https://ryhl.io/blog/async-what-is-blocking/.

However, this was accidentally cpu-bound, so maybe its worth it for safety here

**Comment by ParkMyCar** [comment]
For my own understanding, instead of a second runtime why couldn't we use [`tokio::spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html)? Tokio maintains an entirely separate thread pool specifically for blocking/CPU intensive tasks, to prevent starvation of other async tasks

**Comment by danhhz** [comment]
Discussion seems to be happening in multiple places :)

This is a CYA for situations where a bug causes cpu-bound work that wasn't meant or expected to be cpu-bound

**Comment by danhhz** [comment]
Closed by https://github.com/MaterializeInc/materialize/pull/20447

> Idk if this is the right spot for brainstorming, but might it make sense to either ask or insist that data-intensive work be moved to a clusterd process? It's an alternate approach to the same problem, and perhaps this issue just wants to be about the "second runtime" approach, but I thought I'd bring it up!

Ah, sorry Frank! Missed this when you said it. This issue was motivated by situations where bugs led to things being intensive that shouldn't have been intensive. So more of a CYA than running intentionally intensive things in the wrong place
