### ISSUE TITLE
quote_ident doesn't quote reserved keywords

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20065]
### What version of Materialize are you using?

main

### What is the issue?

Mz:
```
materialize=> select quote_ident('array'), quote_ident('bigint');
 quote_ident | quote_ident
-------------+-------------
 array       | bigint
(1 row)
```
Different in postgres:
```
deen=> select quote_ident('array'), quote_ident('bigint');
 quote_ident | quote_ident
-------------+-------------
 "array"     | "bigint"
(1 row)
```
Was introduced in 62b51567b4f200b07d708c00e1f197a992226995

**Comment by sploiselle** [comment]
This is just because we have a different list of reserved keywords than Postgres.

PG:

```
sean=# create table array ();
ERROR:  syntax error at or near "array"
LINE 1: create table array ();
```

MZ:

```
materialize=> create table array ();
CREATE TABLE
```

**Comment by sploiselle** [comment]
Details can be found in the code here: https://github.com/MaterializeInc/materialize/blob/fa1a8893b3ce27a29cd648e3dd84e92f366c1829/src/sql-parser/src/keywords.rs#L60

**Comment by sploiselle** [comment]
No, our parser is very different than PG's. We use a hand-rolled recursive descent parser, while I believe PG's is generated from some version of `yacc`/`bnf`. We're able to support things with much more finesse than they are because we can control things at the level of token parsing, while PG's fidelity is more at the "rule" level.
