### ISSUE TITLE
[SQLsmith] ERROR: internal error: unexpected NULL with mz_global_id_to_name

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20079]
### What version of Materialize are you using?

940dc019cc35d57b05c848f5c78bccc1cef5481f

### What is the issue?

```
materialize=> SELECT WHERE mz_internal.mz_global_id_to_name((SELECT NULL FROM pg_catalog.pg_matviews)) @> pg_catalog.jsonb_build_array();
ERROR:  Evaluation error: internal error: unexpected NULL
materialize=> SELECT mz_internal.mz_global_id_to_name((SELECT NULL FROM mz_catalog.mz_sinks)) AS c5;
ERROR:  Evaluation error: internal error: unexpected NULL
```

ci-regexp: internal error: unexpected NULL

**Comment by ggevay** [comment]
This is coming from `error_if_null`. There is an slt test (funcs.slt:1569) that says that an error is expected if the second argument is null, so the behavior seems almost correct. I think the only problem is that this is classified as an internal error, which suggests a bug in Materialize, when in fact this seems to be more like an error in the input data: The second argument of `error_if_null` must not be null. We could just modify the error to be some other type of error, unless there is some important reason for this being an internal error. @jkosh44, what do you think?

**Comment by ggevay** [comment]
Additionally, we might want to slightly modify the definition of `mz_global_id_to_name`. It currently gives this as the second arg to `error_if_null`:
`'global ID ' || $1 || ' does not exist'`
The problem with this is that it will give an unhelpful error msg when `$1` is null. I think we should wrap the `$1` into another `error_if_null`, which would catch the situation when `$1` is null, and print an error that says something like "`mz_global_id_to_name` given a null input". What do you think, @sploiselle?

**Comment by ggevay** [comment]
Ok, so if I understand correctly, the reasoning is that `mz_internal.mz_error_if_null` is an internal function, so it is meant to be called by other internal stuff, so a null being passed to it is in no way a user error, but an error in that other internal stuff that's calling it, so it _is_ an internal error. So this would mean that we don't modify the implementation of `error_if_null`, but we modfiy the implementation of `mz_global_id_to_name` to catch the null and print a helpful error instead of an internal error. Makes sense to me!

**Comment by sploiselle** [comment]
@jkosh44 `error_if_null` should return an internal error if the value passed to the second argument is NULL because that would mean you were going to return a NULL-valued error message to the client, which doesn't seem right.

However, I have a change locally that removes the `internal error` prefix from the properly formed error returned from `error_if_null`--guess I can split that out and put up that PR.

You're right about this case that it's confusing how that could occur with the filter on `$1`. I stumbled across this locally a little bit ago inadvertently fixed it by fixing some other issue with the subquery I was feeding into what I thought was the first argument to `mz_error_if_null`. I shrugged it off but you're right that, at the very least, would be useful if someone had an explanation as to why it occurs in planning.

**Comment by sploiselle** [comment]
Put up #20089 to improve `err_if_null` errors

**Comment by ggevay** [comment]
Oh, you are right that `$1` should never be null, due to the check at the beginning of the query. This looks like another case of https://github.com/MaterializeInc/materialize/issues/17189... I'll add it there and maybe also create an individual issue for it.

**Comment by ggevay** [comment]
@sploiselle addressed a part of this in https://github.com/MaterializeInc/materialize/pull/20089:
- The "normal" error path of `error_if_null` now prints an error that is not an "internal error".
- When the error msg argument of `error_if_null` is null, the error msg will now print this more clearly.

The original queries from the issue description print this now:
```
materialize=> SELECT WHERE mz_internal.mz_global_id_to_name((SELECT NULL FROM pg_catalog.pg_matviews)) @> pg_catalog.jsonb_build_array();
ERROR:  Evaluation error: internal error: unexpected NULL in error side of error_if_null
materialize=> SELECT mz_internal.mz_global_id_to_name((SELECT NULL FROM mz_catalog.mz_sinks)) AS c5;
ERROR:  Evaluation error: internal error: unexpected NULL in error side of error_if_null
```

I'm closing this issue.

However, as @jkosh44 [noted](https://github.com/MaterializeInc/materialize/issues/20079#issuecomment-1602653211), something is still very wrong: the `WHEN $1 IS NULL THEN NULL` check doesn't seem to be working. I opened a [separate issue for this](https://github.com/MaterializeInc/materialize/issues/20199), and added it to [the big evaluation order issue](https://github.com/MaterializeInc/materialize/issues/17189).
