### ISSUE TITLE
Schema created by an Kafka avro sink cannot be read back by a Kafka source

### ISSUE THREAD

**Issue by sthm** [MaterializeInc/materialize#20112]
### What version of Materialize are you using?

 v0.57.8 (1f8d4427a)

### What is the issue?

When creating a sink with Avro format, the schema is automatically inferred and created in schema registry if it does not already exists. However, the schema generated by an upsert sink is not compatible with the schema that is expected by a source consuming the same data: When the schema is created by the sink, the key is contained in the value schema and the key schema. But the source expects the key only in the key schema.

Steps to reproduce:

```
staging > CREATE TABLE avro_input (id int NOT NULL, ts timestamp DEFAULT now());
CREATE TABLE

staging > CREATE SINK avro_sink
  FROM avro_input
  INTO KAFKA CONNECTION confluent_cloud (TOPIC '...')
  KEY (id) NOT ENFORCED
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION confluent_schema_registry
  ENVELOPE UPSERT;
CREATE SINK

staging > CREATE SOURCE avro_source
  FROM KAFKA CONNECTION confluent_cloud (TOPIC '...')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION confluent_schema_registry
  ENVELOPE UPSERT;
ERROR:  column "id" specified more than once
```

I would have expected that the schema created by the sink can be reused by the source. Manually removing the key from the value schema fixes the issue.

**Comment by petrosagg** [comment]
> Manually removing the key from the value schema fixes the issue.

This would be an incorrect schema though because our sink does actually write the full row, including the key, as the value of each record. Removing the key part from the value schema only works because we're not ignore the data written there.

The problem is that when using `ENVELOPE UPSERT` you *must* include the key of the records into the output rows because this is the only way for us to rehydrate the upsert state on restart. So in your example we look at the topic and we see a key schema of `(id int)` and a value schema of `(id int, ts timestamp)` and by default concatenate the value to the key and produce the schema `(id int, id int, ts timestamp)`, which has the duplicate name. We do offer some control of how the key gets embedded the final row through the `INCLUDE KEY AS <foo>` option but what you really want here is some kind of option that lets the source know that "the key should be extracted by the value, figure out the indices".

**Comment by sthm** [comment]
Petros has convinced me that this works as intended. I've created a feature request to handle the thing I'm trying to do more gracefully: https://github.com/MaterializeInc/materialize/issues/23925.
