### ISSUE TITLE
Improve Docker image discipline

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2011]
I think we should be more disciplined about our Docker images. Our Docker Hub organization has our core product (materialized) mixed in with things only useful in CI (ci-builder, ci-cargo-test) mixed in with some occasionally useful demo tools, like peeker and billing-demo.

As a user it's not clear what's important and what's not. Our CI-only images are helpfully prefixed with `ci-`; ideally we would have picked a consistent naming scheme for our demo images too (`demo-billing`, `demo-peeker`, etc.). It might be too late to change this.

It is also quite confusing that there is both a `cli` and an `mzcli` image. IMO `cli` should be removed from Docker Hub, as the image takes less than 10s to build. At the very least it should be called `demo-cli`, or something along those lines.

I'd also like to unify how these images are built. `ci-builder` has a bespoke scheme, and has to, in order to break a chicken-and-egg problem, but everything else should be built automatically. `cli` and `chbench` both have build scripts that are run manually and don't produce tags besides latest, while `billing-demo` and `peeker` are built automatically and have releases that match materialized's.  Perhaps everything should follow the `billing-demo`/`peeker` lead?

/cc @umanwizard @quodlibetor

**Comment by quodlibetor** [comment]
I agree everything should have a consistent name (demo-*), but I would rather we not have `build:` sections in our docker compose files and it is easier to say never use them than use your judgement, because even when they start small they can grow big.

All our `ci-*` were private when I last looked, specifically to keep the UI looking clean. I suppose there might be problems for that for repeatability outside of the org? I'd be tempted to leave it as is until we get complaints, unless you're saying it's fine because they're prefixed.

I would rather rename `demo-cli` than get rid of it, I imagine adding more things to it rather than less, and we should use it as the cli for all our demos so that we've got a central place to customize things. I'm surprised and glad that it takes <10s to build, the apt update can be annoying.

`peeker` should probably be renamed to something more like `loadtest-peeker` and `chbenchmark` to `loadtest-chbenchmark`.

**Comment by quodlibetor** [comment]
we could also create different docker hub orgs, as a different namespacing scheme, I think I've seen other orgs do that.

**Comment by benesch** [comment]
Ok, I think you've convinced me that for end users it makes sense to never have a `build` service in a compose file. The build script approach seems pretty close to the ideal, except for the chicken-and-egg problem if you auto-build. Like, it's impossible to have CI push out a new version of an image and also update the compose file to that image in the same commit.

**Comment by quodlibetor** [comment]
yeah we could make `dc.sh` take an arg so it becomes `dc.sh up :demo: v0.1.0` but that's terrible.

If we are assuming that we're running from inside a git repo we could look for the _current_ git tag, otherwise use `latest`, or specify running from a version. That might work, although it seems complicated.

**Comment by quodlibetor** [comment]
we could also add a magic `:released:` version to dc.sh `dc.sh --version :released:` which will find the highest-valued non-rc tag in the repo? Again, complex.

**Comment by quodlibetor** [comment]
related to #2077 , which proposes a universal way to build all our demo images.

**Comment by rjnn** [comment]
@benesch giving you a mandate to address this in the 0.4 timeframe (by fiat, if necessary).

**Comment by benesch** [comment]
Closing as stale. The Docker image is no longer an important part of our offering, so the way we litter our Docker Hub account with lots of images is not a problem.
