### ISSUE TITLE
Roundtrip tests for AstDisplay

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20127]
### Feature request

As we've seen some type constructs didn't work properly in AstDisplay. We should add all remaining constructs to verify that they work correctly. See https://github.com/MaterializeInc/materialize/issues/20110

Should use missing coverage info in AstDisplay and in parser to find all missing tests.

**Comment by mjibson** [comment]
The existing test is at https://github.com/MaterializeInc/materialize/blob/c4a8c41dc8a15ce7b5620cde60c9762e7448c3b3/src/sql-parser/tests/sqlparser_common.rs#L104C4-L104C14

It reads the files in https://github.com/MaterializeInc/materialize/tree/main/src/sql-parser/tests/testdata and does parse and re-parse tests: https://github.com/MaterializeInc/materialize/blob/c4a8c41dc8a15ce7b5620cde60c9762e7448c3b3/src/sql-parser/tests/sqlparser_common.rs#L133

If we can get the code coverage suite to show us which parts of AstDisplay are untested when running that test that would be super valuable. We have now had multiple bugs (some pretty bad) because we ended up persisting incorrect view definitions to disk.

**Comment by def-** [comment]
> If we can get the code coverage suite to show us which parts of AstDisplay are untested when running that test that would be super valuable. We have now had multiple bugs (some pretty bad) because we ended up persisting incorrect view definitions to disk.

That is one thing I wanted to do, but it is not sufficient. If you have a construct that is never printed in AstDisplay, then the coverage can't warn you about code you forgot to write.

**Comment by mjibson** [comment]
> If you have a construct that is never printed in AstDisplay, then the coverage can't warn you about code you forgot to write.

The reparse step protects against that. We print the AstDisplay format, parse that, then assert that the original and re-parsed statements have exactly the same rust structure.

**Comment by def-** [comment]
Before:
![Screenshot 2023-07-13 at 00 36 53](https://github.com/MaterializeInc/materialize/assets/2335377/5be77ed3-c511-489c-9e28-3599f0d0fcb2)
After:
![Screenshot 2023-07-13 at 00 37 05](https://github.com/MaterializeInc/materialize/assets/2335377/f935021c-dfc6-46cc-92a6-817ee849f5a2)
So far so good.
