### ISSUE TITLE
slt: test for `0` to `1` transitions in `mz_arrangement_sharing`

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#20179]
The values in `mz_internal.mz_arrangement_sharing` represent how many times the trace of each arrangement is retained.

A change from `1` to any `n` in the count field of `mz_arrangement_sharing` is fine, as trace handles are just cheap reference-counted pointers. However, any increase from `0` to `1` should be thoroughly investigated, as it means we are causing data to be retained that wasn't before.

The values in this table are structural; that is, they should only depend on the query plan. They should not depend on the amount of data in the inputs, nor on any non-deterministic decisions like e.g. whether compaction has run to completion for a given arrangement.

See also: original suggestion from @umanwizard in [Slack](https://materializeinc.slack.com/archives/C01LKF361MZ/p1687815124481629).

**Comment by def-** [comment]
I'm currently playing around with this by appending something like this to all SLT files:
```
# Check arrangements, seeing new arrangements can mean a significant increase
# in memory consumptions and should be understood before adapting the values.
query T
SELECT mdo.name FROM mz_internal.mz_arrangement_sharing mash JOIN mz_internal.mz_dataflow_operators mdo ON mash.operator_id = mdo.id ORDER BY mdo.name;
----
```
My main concern is that this won't interact well with the newly introduced `--auto-index-selects`. CC @vmarcos  So maybe we have to define some SLT files to only be run with `--auto-index-selects`.
```
==> test/sqllogictest/aggregates.slt
2023-06-27T09:43:24.879550Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping
    SELECT mdo.name FROM mz_internal.mz_arrangement_sharing mash JOIN mz_internal.mz_dataflow_operators mdo ON mash.operator_id = mdo.id ORDER BY mdo.name;
    InconsistentViewOutcome:test/sqllogictest/aggregates.slt:629
            expected from query: Success
            actually from indexed view: PlanFailure { error: db error: ERROR: cannot create view with unstable dependencies
    DETAIL: The object depends on the following unstable objects:
        mz_arrangement_sharing
        mz_dataflow_operators

    Caused by:
        ERROR: cannot create view with unstable dependencies
        DETAIL: The object depends on the following unstable objects:
            mz_arrangement_sharing
            mz_dataflow_operators
```
I'm going to hardcode ignore the auto-index-select for these queries for now as a PoC and will see how far that will go.

**Comment by vmarcos** [comment]
I think that @umanwizard's comment [here in Slack](https://materializeinc.slack.com/archives/C01LKF361MZ/p1687863851460309?thread_ts=1687815124.481629&cid=C01LKF361MZ) is important to take into account. We want to check `mz_arrangement_sharing` for either indexed or materialized views.

In addition, since the introspection data might need some time to catch up, this is likely easier to implement in `testdrive` than in `sqllogictest`. Perhaps we could create a `testdrive` file out of the indexed views and materialized views that we can find in `sqllogictest` files? Then for each such indexed/materialized view, we can first create the indexed/materialized view, check `mz_arrangement_sharing`, and then drop the view?

**Comment by vmarcos** [comment]
We can create a candidate SLT list with something like `grep -ri "CREATE " test/sqllogictest/* | grep -i "VIEW" | awk '{sub(/:.*/, ""); print}' | sort -u | wc -l`
