### ISSUE TITLE
Creating matviews of SHOWs causes error: corrupt catalog: failed to deserialize item u2 (u2.u7.mat_connections): no schema has been selected to create in

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20188]
### What version of Materialize are you using?

661a46e23be610acfbb44feec32b23a4888cb5ee

### What is the issue?

```
$ cat test/testdrive/x.td
> CREATE MATERIALIZED VIEW mat_clusters AS SELECT name FROM (SHOW CLUSTERS);
> CREATE MATERIALIZED VIEW mat_connections AS SELECT name, type FROM (SHOW CONNECTIONS);
> CREATE MATERIALIZED VIEW mat_databases AS SELECT name FROM (SHOW DATABASES);
> CREATE MATERIALIZED VIEW mat_objects AS SELECT name FROM (SHOW OBJECTS);
> CREATE MATERIALIZED VIEW mat_schemas AS SELECT name FROM (SHOW SCHEMAS);
> CREATE MATERIALIZED VIEW mat_secrets AS SELECT name FROM (SHOW SECRETS);
> CREATE MATERIALIZED VIEW mat_sinks AS SELECT name, type, size FROM (SHOW SINKS);
> CREATE MATERIALIZED VIEW mat_sources AS SELECT name, type, size FROM (SHOW SOURCES);
> CREATE MATERIALIZED VIEW mat_tables AS SELECT name FROM (SHOW TABLES);
> CREATE MATERIALIZED VIEW mat_views AS SELECT name FROM (SHOW VIEWS);

> DROP MATERIALIZED VIEW mat_clusters
> DROP MATERIALIZED VIEW mat_connections
> DROP MATERIALIZED VIEW mat_databases
> DROP MATERIALIZED VIEW mat_objects
> DROP MATERIALIZED VIEW mat_schemas
> DROP MATERIALIZED VIEW mat_secrets
> DROP MATERIALIZED VIEW mat_sinks
> DROP MATERIALIZED VIEW mat_sources
> DROP MATERIALIZED VIEW mat_tables
> DROP MATERIALIZED VIEW mat_views

$ bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive run default x.td
[...]
> DROP MATERIALIZED VIEW mat_clusters
rows match; continuing at ts 1687884795.6343117
^^^ +++
x.td:12:1: error: corrupt catalog: failed to deserialize item u2 (u2.u6.mat_connections): no schema has been selected to create in
     |
  11 |
  12 | > DROP MATERIALIZED VIEW mat_clusters
     | ^
+++ !!! Error Report
1 errors were encountered during execution
files involved: x.td
```
But from outside of testdrive (via psql) this works fine, so I'm a bit confused.

**Comment by jkosh44** [comment]
The error is not happening in the test statements itself, it is happening when we try and dump the on disk catalog and compare it to the in memory catalog here:
https://github.com/MaterializeInc/materialize/blob/aed814f9eefe3fcb36d2ced45ec394a10cd328a9/src/testdrive/src/action/sql.rs#L130-L154

That's why it doesn't seem to repro.

You can repro this locally via `psql` by running the following:
```
CREATE MATERIALIZED VIEW mat_clusters AS SELECT name FROM (SHOW CLUSTERS);
CREATE MATERIALIZED VIEW mat_connections AS SELECT name, type FROM (SHOW CONNECTIONS);
CREATE MATERIALIZED VIEW mat_databases AS SELECT name FROM (SHOW DATABASES);
CREATE MATERIALIZED VIEW mat_objects AS SELECT name FROM (SHOW OBJECTS);
CREATE MATERIALIZED VIEW mat_schemas AS SELECT name FROM (SHOW SCHEMAS);
CREATE MATERIALIZED VIEW mat_secrets AS SELECT name FROM (SHOW SECRETS);
CREATE MATERIALIZED VIEW mat_sinks AS SELECT name, type, size FROM (SHOW SINKS);
CREATE MATERIALIZED VIEW mat_sources AS SELECT name, type, size FROM (SHOW SOURCES);
CREATE MATERIALIZED VIEW mat_tables AS SELECT name FROM (SHOW TABLES);
CREATE MATERIALIZED VIEW mat_views AS SELECT name FROM (SHOW VIEWS);
DROP MATERIALIZED VIEW mat_clusters;
```
and then attempting to restart Materialize.

**Comment by jkosh44** [comment]
The reason it only showed up on the `Drop` is because we don't dump the catalog on `CREATE MATERIALIZED VIEW` statements.

**Comment by jkosh44** [comment]
I found the issue. At a high level `SHOW` commands are unmaterializable, they rely on the current schema and therefore are meaningless in a materialized view. The fact that they are allowed in materialized is a bug. When we reboot and try and re-plan the materialized view, we have no idea what schema to use and panic. I'll post an in depth walk through of the bug in the next comment.

**Comment by jkosh44** [comment]
When we boot up, we load all of the catalog items and attempt to deserialize each one:

https://github.com/MaterializeInc/materialize/blob/aed814f9eefe3fcb36d2ced45ec394a10cd328a9/src/adapter/src/catalog.rs#L4363-L4430

Deserializing the item involves parsing the item:

https://github.com/MaterializeInc/materialize/blob/aed814f9eefe3fcb36d2ced45ec394a10cd328a9/src/adapter/src/catalog.rs#L7195-L7203

Parsing it involves planning it:

https://github.com/MaterializeInc/materialize/blob/aed814f9eefe3fcb36d2ced45ec394a10cd328a9/src/adapter/src/catalog.rs#L7205-L7225

Deep in the planner, when we plan a query with `SHOW CONNECTIONS` (and many other `SHOW` commands), we get the current schema to limit the connections to connections only in the current schema (`from` here is `None` since the `SHOW CONNECTIONS` didn't specify a `FROM` clause):

https://github.com/MaterializeInc/materialize/blob/aed814f9eefe3fcb36d2ced45ec394a10cd328a9/src/sql/src/plan/statement/show.rs#L331-L336

Since no schema name was provided (`schema_name` is `None` below), we attempt to resolve the active schema:

https://github.com/MaterializeInc/materialize/blob/aed814f9eefe3fcb36d2ced45ec394a10cd328a9/src/sql/src/plan/statement.rs#L582-L593

This happens in bootstrapping so there is no active schema. Even if there was, it would likely be different than the active schema that the materialized view was created with. So an error is thrown:

https://github.com/MaterializeInc/materialize/blob/aed814f9eefe3fcb36d2ced45ec394a10cd328a9/src/sql/src/plan/statement.rs#L595-L600



The reason we don't accurately identify that the view is unmaterializable is probably due to: https://github.com/MaterializeInc/materialize/issues/19080
