### ISSUE TITLE
storage/sources: make (sub)sources a flavor of tables

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20208]
Sources are one of the first concepts users have to learn in Materialize. As is, we roughly expose three different interfaces for sources: single-output **sources** (Kafka, Webhook), **multi-output sources** (PostgreSQL, MySQL), and **push sources** (Fivetran); each of which requires users to learn to query different object types for data: **sources**, **subsources**, and **tables**.

More than fragmenting the user experience, this has also required us to introduce and maintain special syntax for each of these interfaces over time. We realized that [turning all queryable source objects into a flavor tables](https://github.com/MaterializeInc/materialize/issues/20208#issuecomment-1955401921) would help reduce confusion and build a good foundation for other desirable features, like [in-place schema changes](https://github.com/MaterializeInc/materialize/issues/15897).

**Related issues**

- [x] (Pre-requisite) https://github.com/MaterializeInc/materialize/issues/24773
- [x] https://github.com/MaterializeInc/materialize/issues/26389
- [ ] https://github.com/MaterializeInc/materialize/issues/15897

<hr>

**Original context** (from @sploiselle)

> I believe we mis-generalized the notion of sources/subsources because the first set of sources we built only represented a single collection, so we conflated the notion of an ingestion (let's call it a `SERVER`) and a demultiplexed output of that ingestion, which we could call a `SOURCE`, which is currently akin to a subsource.

> For some sources, the ingestion is inextricably linked to a persist shard (e.g. Kafka), but for others (Postgres, complex load generator sources), we leave behind a vestigial collection that is queryable but always empty––there is no need or imaginable use for this shard. However, if we separated the notion of `SERVER` and `SOURCE`, we could instead describe a PG `SERVER` and all of its tables (which are currently `SUBSOURCE`s) could be promoted to `SOURCE`; for Kafka, we could create a Kafka `SERVER` and its single `SOURCE` remains a `SOURCE`.

**Comment by sploiselle** [comment]
Something akin to "foreign data" is, I think, the appropriate parallel in Postgres: https://www.postgresql.org/docs/current/ddl-foreign-data.html

**Comment by benesch** [comment]
My two cents!

  * Servers in SQL/MED are most equivalent to connections in Materialize.
  * Foreign tables in SQL/MED are most equivalent to subsources in Materialize.
  * There is no SQL/MED-equivalent concept for sources, because in SQL/MED, external tables are inert, and fetch data only when queried.
  * We should be careful about taking design inspiration from SQL/MED because it is a prescriptive can of worms that we will never support ([Slack conversation](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1688001757856599?thread_ts=1687959381.788109&cid=CU7ELJ6E9)). Way back when, we intentionally used different terms than SQL/MED to avoid giving users the false impression that we are SQL/MED compatible.

In my ideal world:

  * We rename "subsource" to "[read-only] table." `SHOW TABLES` shows these tables. `mz_tables` reports them as tables, but with a `read_only: bool` column or somesuch indicating that these tables are read-only.
  * We start describing sources as "components that read data from an external system and write it to tables in Materialize."
    * This works perfectly for PostgreSQL sources, where the source relation is a stub relation that is always empty. In SQL, we even already allow using `TABLE` in place of `SUBSOURCE` (e.g. `ALTER SOURCE ... ADD TABLE`). We disallow `SELECT`ing from the source itself.
    * Kafka sources are trickier, because of the issue mentioned in the description: the source relation itself has the data. The most backwards compatible option is to declare that a Kafka source creates a table of the same name, and then report the name as a table in `mz_tables` _and_ as a source in `mz_sources`. This is still a special case, but I think we have a better explanation/justification.
    * Alternatively, we could change the behavior of `CREATE SOURCE s FROM KAFKA ...` so that it creates a source named `s` and a read-only table named `s_topic` (or `s_topic1`, `s_topic2`, ... whatever is available). This would mirror PostgreSQL and more directly reifies the concepts, but I think would be quite a bit less ergonomic. I'm also not sure how we'd migrate existing sources to this new model.
  * The explainer for why one source can ingest only a single Kafka topics but one source can ingest multiple PostgreSQL topics is because sources are 1:1 with changefeeds. In Kafka, the changefeed is a single Kafka topic, whereas in PostgreSQL, the changefeed is a single PostgreSQL publication.

**Comment by sploiselle** [comment]
From a user ([Slack](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1702651111408609)):

> Why can I query from some sources but others I can't have to query from subsources

**Comment by benesch** [comment]
cc @petrosagg — this is the issue for "sources as tables" that we were discussing today.

**Comment by benesch** [comment]
One idea we've had recently is to say that the source _is_ its progress relation. I really like this idea. Been noodling on the syntax to support it. Here's a quick rundown of what the new API would look like.

Create a Kafka source that reads from a topic named `t`:

```sql
CREATE SOURCE kafka_src
FROM KAFKA CONNECTION kafka_conn (TOPIC 't')
FOR ALL TABLES
```

`kafka_src` is the progress relation for the source, and a table named `t` is automatically created in the same schema as `kafka_src`.

----

Create a Kafka source that reads from a topic named `t` with a custom table name:

```sql
CREATE SOURCE kafka_src
FROM KAFKA CONNECTION kafka_conn (TOPIC 't')
FOR TABLES (t AS my_t)
```

`kafka_src` is again the progress relation for the source. The data is in a table named `my_t`.

----

Create a PostgreSQL source:

```sql
CREATE SOURCE postgres_src
FROM POSTGRES CONNECTION postgres_conn (TOPIC 'topic')
FOR ALL TABLES
```

`postgres_src` is the progress relation; there is no separate `postgres_src_progress` relation created. Otherwise this command works the same way that it does today.

----

Add a new table to a PostgreSQL source:

```sql
CREATE TABLE my_new_table FROM SOURCE postgres_source (upstream_schema.upstream_table);
```

This would replace the `ALTER SOURCE ... ADD {SUBSOURCE|TABLE}` command.

----

Add a new table to a Kafka source:

```sql
CREATE TABLE kafka_copy FROM SOURCE kafka_src ("t");
```

At first this looks weird. Why would you ever want two copies of a Kafka source? It turns out this lets you incorporate upstream schema changes without losing reclocking information! This would get us reusable reclocking (https://github.com/MaterializeInc/materialize/issues/17021), without needing to introduce a new `SOURCE PROGRESS` concept.

**Comment by bosconi** [comment]
Related items:
* [Deprecate subsources Notion doc](https://www.notion.so/materialize/Deprecate-subsources-422d359cae554d46b21664a3fe2f719c?pvs=4)
* [Generate subsources after planning sources](https://www.notion.so/materialize/Generate-subsources-after-planning-sources-683772c62d8e46e1a0c8945fe789f545?pvs=4)
* Draft PR https://github.com/MaterializeInc/materialize/pull/27320
