### ISSUE TITLE
productionize shard finalization

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#20222]
Shard finalization ran into some issues in https://github.com/MaterializeInc/cloud/issues/6705 and after investigating, there remain several bugs with it:

- [x] We rarely advance since to `[]` on drop https://github.com/MaterializeInc/materialize/pull/20206
- [x] Remap and status shards are not added to the WAL
- [x] There are shards in the WAL that do not have since/upper advanced to `[]`, so even if we fix the ongoing behavior we'll still need a way to finalize shards in unexpected states. Same issue but possible to see even with the above fixes: there's a race where we could add a shard to the WAL but crash before advancing since to `[]`
- [ ] We can spawn expensive maintenance tasks for the finalization ops that don't respect the intended concurrency limits

We've discussed adding a `PersistClient::finalize` call that would perform the necessary tombstone operations, after it ensures that there are no active leased handles to the shard. This could simplify the advance-since-to-empty-frontier-advance-upper-to-empty-frontier dance we attempt to do right now.

**Comment by bkirwi** [comment]
I think we've made some good progress here since this was originally written:
- Remap shards are managed like everyone else. (Status shards are builtins, none of which are finalized, so I think that's okay.)
- The finalization logic has been spawned into a separate task.

Some things are still outstanding:
- I have a PR up that closes one remaining hole where an untimely crash could cause a shard to not be fully cleaned up. (There's an additional question around dealing with GC that I'm not sure of.)
- We still don't impose a concurrency limit.

**Comment by bkirwi** [comment]
We've got a new ticket for limiting maintenance concurrency: https://github.com/MaterializeInc/materialize/issues/24055

Since that's the last bit of this ticket that isn't complete - going to close this out.
