### ISSUE TITLE
Improve upgrade test error messages 

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#20297]
@jkosh44 reports that debugging failures in "Platform checks upgrade in Cloudtest/K8s" is painful, because:

1. The error doesn't tell you where the failing line comes from (i.e. what file it's from).
1. The error doesn't tell you what specific upgrade path is being tested.
1. The error doesn't tell you what version of Materialize is being run when the test failed.

On top of all of that it's a fairly slow test making discovery of these facts very slow. It took Joe 2-3 hours to discover the answer to (1) and (3), and he never figured out the answer to (2).

**Comment by philip-stoev** [comment]
With respect No 1 telling you the file, this is a generalized problem when testdrive fragments are being embedded in .py files. Possible solutions include:

1. Catch testdrive errors and annotate them with the name of the py file that called the testdrive fragment.
2. Instead of passing SQL queries to testdrive via stdin, pass them via temporary file. The temporary file name will then be printed as part of the error message and that name can then be made descriptive enough to allow debugging. Alexander used this trick in test/sql-feature-flag:

```
 with tempfile.NamedTemporaryFile(
        mode="w",
        dir=c.path,
        prefix="phase-reset-all-",
    ) as tmp:
...
            tmp.flush()
            c.exec("testdrive", os.path.basename(tmp.name))
```

**Comment by philip-stoev** [comment]
With respect to No 2, the test indeed should print the value of `LAST_RELEASED_VERSION` at the start of the test. Otherwise, it is buried in the kail.log artifact file.

**Comment by philip-stoev** [comment]
With respect to No 3 , yes the test was indeed missing sufficient debugging output - the `ReplaceEnvironmentdStatefulSet` operation was marked in the logs, but maybe the output should be enhanced to print something like "replacing environmentd stateful set from version X to version Y".
