### ISSUE TITLE
Enable `EXPLAIN` for instrospection user

### ISSUE THREAD

**Issue by sthm** [MaterializeInc/materialize#20478]
### Feature request

The field engineering team is using teleport for troubleshooting customer environments without access to customer data. It's a valuable tool that avoids sometimes tedious back and forth with customers. However, it's currently not possible to retrieve the explain plan of a query through that mechanism.

```
localhost > explain SELECT * FROM auctions LIMIT 1;
ERROR:  permission denied for SOURCE "materialize.qck.auctions"
```
It would be great to extend the permissions of the introspection users to enable explain statements. Nikhil does [not have any security related concerns](https://materializeinc.slack.com/archives/C04R299RJ7R/p1689087263002679).

**Comment by jkosh44** [comment]
Currently, in order to explain a query the user needs the same set of privileges that would be required to execute the query. This was modeled after PostgreSQL. For this specific query the user would need:
- `USAGE` privileges on the `qck` schema.
- `SELECT` privileges on the `auctions` source.

One option is to lift this restriction and not require `SELECT` privileges on the source. If we do that then we would have to make sure that's it's not possible to leak any sensitive data through `EXPLAIN`.

Another option is to add a new type of privilege called `EXPLAIN` that allows a user to explain queries involving certain objects.

Either way, we would still need to make sure that the `mz_introspection` user has `USAGE` privileges on all schemas, as that's required to look objects up in a schema.

**Comment by chaas** [comment]
Linking in conversation from slack https://materializeinc.slack.com/archives/C02FWJ94HME/p1689264753940949 

According to our data management policy, we are ok to allow the `mz_introspection` cluster to execute `EXPLAIN` since `EXPLAIN` does not ever print customer data. `USAGE` on databases & schemas is also ok because it does not grant access to any customer data.

Access to clusters is not a concern b/c `EXPLAIN` plans do not run on a cluster, and can thus be "run" on the `mz_introspection` cluster. 

We still need to make a decision per @jkosh44 's comment above to either not require `SELECT` privileges on an object to run `EXPLAIN` or add a new type of privilege called `EXPLAIN`.

**Comment by chuck-alt-delete** [comment]
Could we also let the introspection cluster "impersonate" another cluster when running explain? Something like `EXPLAIN MATERIALIZED VIEW v IN CLUSTER c` to show what the plan is as if it were being planned in cluster `c`? For example, cluster `c` might have indexes that change the `EXPLAIN` output and we'd want to see that (for example to check that a join is type `delta` rather than `differential` when run in a particular cluster).

**Comment by sjwiesman** [comment]
This has come up again as a request from field eng
