### ISSUE TITLE
adapter: add peek fast path label for mz_time_to_first_row_seconds

### ISSUE THREAD

**Issue by maddyblue** [MaterializeInc/materialize#20917]
We should add a label to the mz_time_to_first_row_seconds metric with information about if a peek was fast path or not (may also want constant or not). Might not need to be a label, could also be teaching `statement_kind_label_value` about the different peek buckets.

See: https://github.com/MaterializeInc/materialize/pull/20532

**Comment by mjibson** [comment]
Motivation: being able to assume latency blips in the fast path label are bad and thus suitable for alerts (vs maybe someone is running an exploratory query and it's fine/expected to take a long time).

**Comment by benesch** [comment]
The motivation is that we're searching for a way to distinguish between "production queries" and "development queries" when monitoring latency. In normal usage of Materialize, customers are both 1) running queries that serve production use cases and 2) running exploratory queries/developing new use cases. We want to monitor and eventually alert on (1) while filtering out noise from (2). E.g., if someone runs `SELECT * FROM massive_new_source`, that query is expected to have massive latency, and we don't want that to skew our understanding of "are the production use cases for this customer getting the query latency they expect?"

The problem is: how do we identify which queries are production queries and which queries are development queries? In an ideal world, we'd tell users "set your application name to something that starts with `production_` (e.g., `production_app1`) if you are running queries that are important." But a solution that requires users to hold Materialize in such a specific way will never work.

@danhhz had the insight that a fast-path peek is probably a good proxy for "production query." We expect most production queries to be simple reads out of indexes, maybe with a filter/projection/map applied—which is exactly a fast path peek! That's not to say you won't have development queries that are fast-path peeks, but hopefully those are also fast and don't skew the data too much.

**Comment by mjibson** [comment]
See https://github.com/MaterializeInc/materialize/pull/20862 for a thing that is threading through peek execution strategy into the protocol layer. Probably should wait for that to land.
