### ISSUE TITLE
Support the DIFF envelope for file sources

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2091]
We should expand Materialize's understanding of sources to include batched source data. 

For example, imagine we have some directory `/data` that has a new file `source_data_[version].json` written to it every hour. The `source_data_[version].json` will include some number of duplicates from the previous version and some number of updates/new entries. We should be able to create a source that matches on a file pattern, picks up new files, and pushes their contents into Materialize.

We have discussed a few ways to potentially implement this:
- Create two Materialize sources: one for insertions, one for deletions. With each new file we see, send the contents of the last file to the deletion source and the contents of the new file to the insertion source. Create a view on the diff.
- Do something similar to the first option, but use [mkfifo files](http://man7.org/linux/man-pages/man3/mkfifo.3.html).
- Absorb this complexity into Materialize.

cc: @frankmcsherry, @benesch, @rjnn, @quodlibetor, @ruchirK for any thoughts or items I missed

**Comment by frankmcsherry** [comment]
> create a view on the diff.

It should be pretty easy for us to do 
```sql
create view current as 
select * from insertions
except all
select * from deletions;
```
However, this has some protective measures in it to ensure that we don't delete things that do not exist in `insertions`. Roughly, the plan looks like
```rust
deletions
    .negate()
    .concat(insertions)
    .threshold()  // <-- I am stateful! Track the whole collection!
```
Both `negate()` and `concat()` are stateless, but `threshold` keeps around what is essentially a copy of the data, so it can watch for things going negative.

It might be worthwhile to have a way to get a blessed "I am only subtracting things I have inserted" construction to keep this totally stateless. If we can, then the above has no cost until used, and any eager filtering and projection substantially reduces the data, whereas with the `threshold()` I think we have no choice but to materialize the pre-projected data (we could move the filter up and not maintain that data).

**Comment by rjnn** [comment]
I want to simplify this a bit, as I think there's an elegant solution here that's even cleaner, so here's a restated description and motivation (I have updated the title):

Imagine you have a file source, call it a 'customers' table. To keep things
simple, this file source is a CSV. The "customers" table is infrequently updated
via an ETL pipeline (this is easily generalizable to ORC files kept S3), but
given the criticality of it, it is never overwritten. So the TAIL option that
file sources currently support doesn't come into play. Instead, the ETL pipeline
produces a `customers_[DATE]` file every day.

This file source is important to support in Materialize, because views over
event streams need to be joined to the customers table to extract various bits
of metadata. Given that the main motivation for using Materialize is for this
rich join support, supporting the ergonomics of file source is important. A
recurring theme from users has been that these file sources do look like the
above pattern, than a TAILed file (particularly since TAIL does not support
deletes, and that object source files are nontrivial to modify in place).

The problem for Materialize comes with switching over from `customers_01` to
`customers_02`. Currently all we can ask if for users to create entirely new
views over `customers_02` that match their views on `customers_01`. But this
results in a lot of wasted computation. For views where nothing changes between
`customers_01` and `customers_02`, there is also the problem that you might not
want to re-emit messages to downstream sinks.

One candidate solution here is to support a `diff` envelope: the envelope
definition is simple: it's the output of running the `diff` program between
`customers_01` and `customers_02`, with accompanying `+`s and `-`s and line
numbers`.

In addition we can then think about supporting syntax like `ALTER
SOURCE foo SET FILENAME TO `customers_2`, which could run the `diff` program and
stream in the changes, which would give users an elegant pattern to follow.

The potential here is huge, because in most cases, tables like `customers` are
usually massive, but the deltas between day-to-day dumps are small (e.g. how
often do you change your credit card address versus swipe your card?). Regular
data warehouses today do massive amounts of redundant computations due to being
unable to flow through retractions through their entire dataflow, so they have
no option but to recompute results entirely. The cost savings here could be very
meaningful.

**Comment by frankmcsherry** [comment]
Annoyance to consider: if line numbers are presented as columns, adding a line anywhere in a file will *change* all records afterwards, even if just by their line number column. Unless the numbers of additions and deletions sync up again through good luck.

I'm more positive on this than I am on line numbers though.

**Comment by rjnn** [comment]
Oof yeah. That's not good.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frankmcsherry** [comment]
I think it’s possible that presenting line numbers, Kafka offsets, timestamps etc as data may be an antipattern. Do we have collected use cases for them?

**Comment by benesch** [comment]
One thing that came up a lot with basic file sources (no diff) was just listing them in order. Without the line number, you can't order by anything useful, in many cases.

**Comment by rjnn** [comment]
I think upon further reflection, supporting things like DIFFs makes line numbers less tenable... It's a bit of an antipattern.

**Comment by benesch** [comment]
I think possibly this bifurcates nicely on whether or not you're using some sort of an envelope, whether it's an upset envelope or the Debezium-style envelope. If you're using an envelope, you fall into the "advanced consistency" bucket, I think, and probably want to treat collections like the multisets that they actually are.

If you're not using an envelope, you probably fall into the "yolo consistency" bucket, and want to treat collections as an ordered append-only log. In that case you probably want line/offset/record numbers, and it should be safe to expose them?

**Comment by rjnn** [comment]
I think @benesch is correct here.

**Comment by antiguru** [comment]
Not planned.
