### ISSUE TITLE
pg-cdc: A source does not produce updates even though its _progress is advancing.

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#20936]
### What version of Materialize are you using?

 v0.63.4 (5e60b7e16)

### What is the issue?

As observed in the shared eng sandbox. A postgres source is stuck like this:

```
 select count(*) from public_pg_cdc.people;
708
```

This no longer reflects the reality of the upstream postgres database, which is continuously being modified. At the same time, the `_progress` subsource keeps incrementing and `EXPLAIN TIMESTAMP` does not report any stale timestamps and reports "can respond immediately = true".

The issue persists across restarts of the clusterd. Creating another completely identical postgres source replicates and updates successfully.

**Comment by sploiselle** [comment]
To begin triaging this, I could use a `TRACE` log from the storage crate from environment with the currently broken and an additional, new, duplicate version of the source (that ostensibly seems to work).

**Comment by benesch** [comment]
We had a bug (or perhaps limitation) when this was filed where we invalid replication slots wouldn't mark the source as failed. I suspect that's what happened here—the original replication slot got invalidated by PostgreSQL, but Materialize didn't notice. Fixed by https://github.com/MaterializeInc/materialize/pull/23467.
