### ISSUE TITLE
`EXPLAIN` should print `Get` differently when it's using an existing index

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#21192]
Currently, [it's hard to explain to users](https://github.com/MaterializeInc/materialize/pull/21137/files#r1294355659) what an `ArrangeBy` means when they see it in an EXPLAIN plan: In many cases, it is just signaling that an existing arrangement will be used. So if there is an ArrangeBy in the plan, it might or might not build an arrangement as part of this dataflow.

After https://github.com/MaterializeInc/materialize/pull/21119, it would now be easy to also modify the printing of `ArrangeBy`s that will just reuse an index. https://github.com/MaterializeInc/materialize/pull/21119 already computed this knowledge, we'd just need to let EXPLAIN know at the point where it's printing the `ArrangeBy`. I'd propose we add a `reuse_index` flag to the MIR ~~`ArrangeBy`~~ (Edit: `Get` would be better, so that we can also prettyprint full index scans, where there is no `ArrangeBy`). The flag would be set by `CollectIndexRequests`, and would be used only by EXPLAIN.

**Comment by aalexandrov** [comment]
I suggest the following sequence of refactorings to accommodate for the intended change:

1. Introduce a generic parameter on `MirRelationExpr` of type `M = ()`. The default will ensure that we that places that just spell `MirRelationExpr` will not need to be touched. This is similar to the `T: AstInfo` generic parameters in the AST structs (e.g. `Expr<Aug>`).
2. Introduce a `meta: M` in the `Get` field.
3. Introduce a transform `MirRelationExpr<()> ⇒ MirRelationExpr<NodeId>` where each node is annotated with a unique ID within the resulting plan (for example based on post-order traversal). For the first iteration, only `Get` nodes will know about their ID because nobody else will have a `meta: M` field, but we can then gradually build this capability.
4. Rework `CollectIndexRequests` to attach a `NodeId` to each `IndexUsageType` it emits.
5. Rework `DisplayText` implementations in order to special-case the rendering of `Get` nodes referenced by an `IndexUsageType`.

**Comment by aalexandrov** [comment]
The benefit of this approach is that we can reuse steps (1)-(3) for other "observability" features. For example, once we have `meta: M` added to all `MirRelationExpr` variants, we can 

1. Run `enumerate` before `MIR ⇒ LIR` lowering,
2. Extend LIR in a similar way.
3. Pass the `NodeId` to the LIR fragment generated for each MIR node.
4. Use the `NodeId` value in LIR to generate region names when rendering.
5. Aggregate statistics (scheduling, memory) based on the region names from (4) in order to attach them as attributes to the `OPTIMIZED` or `PHYSICAL` plans.

**Comment by ggevay** [comment]
We had a long discussion about this in the Optimizer sync on Friday with @aalexandrov and @mgree, and we decided to do this a bit later.

The above might work, and there is also a slightly different approach: Instead of saving the numbering inline, we could recompute the numbering every time when we want to look something up in the numbers -> metadata hashmap. To avoid accidentally mutating the `MirRelationExpr` between computing some metadata and using the metadata, we could create a marker wrapper type `FrozenMirRelationExpr` (which would be somewhat similar to `OptimizedMirRelationExpr`). Note, that with the generic type approach, the non-mutation would be enforced by having a different type after the annotations are added.

We also talked about having inline annotations also when we are still mutating the tree (which wouldn't fit the alternative approach here, but would maybe fit Alex's approach above), but this seems like a much larger refactoring.

**Comment by mgree** [comment]
One other concurrent change that come up as a possibility (but doesn't seem worthwhile right now) is to use hashconsing as a source of node numbering/metadata indexing. This would be a big change, though it would probably yield some memory wins in the optimizer. We decided this probably wasn't worth it right now.

**Comment by aalexandrov** [comment]
> One other concurrent change that come up as a possibility (but doesn't seem worthwhile right now) is to use hashconsing as a source of node numbering/metadata indexing.

There is an issue for that: #10501.
