### ISSUE TITLE
Prototype a better metric for understanding CPU

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#21743]
## Problem
- CPU metrics are misleading due to idle compaction. 

## Solution
- Prototype a metric for % of each 1s clock tick that is spent advancing timestamps vs. merging batches

**Comment by ggnall** [comment]
## Notes
- @parkerhendo and @frankmcsherry to experiment with visuals. Assumption is that we can show a ratio (or raw XXms / 1s) as a current value and as a timeseries. Consider alternatives indicators for healthy, unhealthy, or size up/down.
- @umanwizard to pick up as a skunkworks project.

**Comment by teskje** [comment]
I did some measurements with this metric. Details below.

### Setup

* Deploy a version of Mz that emits fine-grained updates for dataflow import and export frontiers (rather than updates rounded to 1s as introspection sources normally provide).
* Run this query in a `SUBSCRIBE`:
  ```sql
  WITH
     import_frontiers AS (
         SELECT export_id, min(time) AS time
         FROM mz_internal.mz_compute_import_frontiers
         GROUP BY export_id
     ),
     caught_up AS (
         SELECT export_id, e.time = i.time AS caught_up
         FROM mz_internal.mz_compute_frontiers AS e
         JOIN import_frontiers i USING (export_id)
     )
  SELECT bool_and(caught_up) FROM caught_up
  ```

  This query returns a single `caught_up` flag that is true when all dataflows on the replica have an export frontier that is caught up with its corresponding import frontiers.
* Install a simple dataflow that has to perform the same amount of work every second:
  ```sql
  CREATE SOURCE count FROM LOAD GENERATOR COUNTER (MAX CARDINALITY = 1) WITH (SIZE = '3xsmall');
  CREATE TABLE t (a int);
  CREATE VIEW load AS SELECT * FROM count, t;
  CREATE DEFAULT INDEX ON load;
  ```

  By inserting different amounts of record into `t`, we can control the amount of load on the replica.

* Insert different amounts of records (`N`) into `t`, run the above `SUBSCRIBE` for 10 minutes each time, to collect data.

  For `N`, the following values were chosen: `100000`, `200000`, `300000`, `400000`, `500000`, `600000`, `700000`

### Results

The below graphs list the busy times (in ms/s) for the different values of `N`. Each graph shows results averaged over a different period length. The longer the period, the smoother the busy time curve looks.

* period: 10s
  ![busy_10s](https://github.com/MaterializeInc/materialize/assets/4521314/daa08c00-eb42-41bd-bd37-97b38d17405c)

* period: 30s
  ![busy_30s](https://github.com/MaterializeInc/materialize/assets/4521314/ec0ce218-d8e6-487c-a055-12bf2f0a0e62)

* period: 60s
  ![busy_60s](https://github.com/MaterializeInc/materialize/assets/4521314/c3261eb4-14b1-45d8-b5ca-160b8fbeaee5)

### Discussion

From the above results we can say:

* The metric is generally working. At `N = 600000` fast-path queries against the replica under test became noticeably slower (> 1s) and at `N = 700000` the replica was nearly unresponsive.
* The metric is very spikey. For comparison, the CPU utilization during this experiment is shown below. It's way less variable.

  ![Screenshot 2023-10-13 at 16 07 28](https://github.com/MaterializeInc/materialize/assets/4521314/3b0e931c-ef95-446c-a181-4e4a72461f69)

* In contrast to CPU utilization, the delivery of this metric is affected by the load on the replica under test. If the replica is heavily loaded, frontier updates will be delayed too. Which means that for these periods of time we might not be able to produce a metric value at all. We could just default to 100% utilization in this case, but that might not always be correct (e.g. the reason we are not receiving responses might be a network outage).

**Comment by teskje** [comment]
I ran a second test to prove that this metric is not skewed by idle merging like CPU usage is. 

## Setup

* Deploy a version of Mz that emits fine-grained updates for dataflow import and export frontiers (rather than updates rounded to 1s as introspection sources normally provide).
* Run these commands:

  ```sql
  CREATE TABLE t (a int);
  CREATE DEFAULT INDEX ON t;
  INSERT INTO t SELECT generate_series(1, 20000000);
  INSERT INTO t VALUES (1);
  \watch 1s
  ```

  This creates a large index and then continues to trickle updates into it, which make DD continuously busy with idle merging.

For an `xsmall` replica, this makes its single worker thread spin at 100% CPU usage. However, the replica still responds quickly to queries, showing that it is not really loaded.

## Results

The below graph shows busy times collected over 10 minutes, averaged over periods of 10s.

![idle-merging](https://github.com/MaterializeInc/materialize/assets/4521314/d8b55252-1490-48e0-810d-2be8595518f1)

## Discussion

The results show that the busy time metric is not skewed by idle arrangement merging, so it is better than CPU usage in this regard. Notice again the spikiness though.

**Comment by ggnall** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/issues/17002#issuecomment-1805768513, which improves the usefulness of CPU.
