### ISSUE TITLE
Add additional indexes for console

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#21858]
### Feature request

We discovered some un-indexed queries in console. Generally speaking we just want to make sure these queries don't require a persist call, full scans aren't a big issue.

`mz_sources`
`mz_sinks`
`mz_materialized_views`
`mz_indexes`

I noticed there are indexes on the respective show views, I wonder if we can just swap them for the underlying table? The show indexes for other object types, such as connections and secrets appear to work this way.

**Comment by chaas** [comment]
Example: the query in this issue https://github.com/MaterializeInc/materialize/issues/21269 would be optimized by an index on `mz_sources`.
```
materialize=> SELECT s.id
FROM mz_catalog.mz_sources AS s
INNER JOIN mz_internal.mz_source_statuses AS st ON st.id = s.id;
```

Explain plan
```
Explained Query:
  Project (#0)
    Join on=(#0 = #1) type=differential
      ArrangeBy keys=[[#0]]
        Project (#0)
          ReadStorage mz_catalog.mz_sources
      ArrangeBy keys=[[#0]]
        ReadIndex on=mz_source_statuses mz_source_statuses_ind=[differential join]

Used Indexes:
  - mz_internal.mz_source_statuses_ind (differential join)
```

**Comment by chaas** [comment]
I agree with the idea to see if we can repurpose the show indexes, moving the indexes to the underlying objects that the show command runs on rather than the view.
Those index on the `schema_id`, so we'd still need to do a full scan on the index, but like you said, the actual size of the data is small so a full in-memory scan of the index should be fine. As long as we're not hitting persist.

**Comment by chaas** [comment]
I looked into trying to replace the show command indexes with ones on the underlying object. For e.g. `SHOW SOURCES` this involved replacing the original `mz_show_sources_ind` with two others
1) `ON mz_catalog.mz_sources (schema_id)`, called `mz_show_sources_ind`
2) `ON mz_catalog.mz_sources (cluster_id)`, called `mz_sources_cid_ind`

This is the explain plan before
```
Explained Query (fast path):
  Project (#1..=#4)
    ReadIndex on=mz_internal.mz_show_sources mz_show_sources_ind=[lookup value=("u25")]

Used Indexes:
  - mz_internal.mz_show_sources_ind (lookup)
```

This is the explain plan after
```
Explained Query:                                                                  +
   Return                                                                          +
     Union                                                                         +
       Map (null)                                                                  +
         Union                                                                     +
           Negate                                                                  +
             Project (#3, #4, #6)                                                  +
               Join on=(#8 = #12) type=differential                                +
                 ArrangeBy keys=[[#8]]                                             +
                   Get l1                                                          +
                 ArrangeBy keys=[[#0]]                                             +
                   Distinct group_by=[#0]                                          +
                     Project (#4)                                                  +
                       Get l0                                                      +
           Project (#3, #4, #6)                                                    +
             Get l1                                                                +
       Project (#1..=#3, #5)                                                       +
         Filter (#0 = "u3")                                                        +
           Get l0                                                                  +
   With                                                                            +
     cte l1 =                                                                      +
       ReadIndex on=mz_catalog.mz_sources mz_show_sources_ind=[lookup value=("u3")]+
     cte l0 =                                                                      +
       Project (#2..=#4, #6, #8, #12)                                              +
         Filter (#8) IS NOT NULL                                                   +
           Join on=(#8 = #11) type=differential                                    +
             ArrangeBy keys=[[#8]]                                                 +
               ReadIndex on=mz_sources mz_sources_cid_ind=[differential join]      +
             ArrangeBy keys=[[#0]]                                                 +
               ReadIndex on=mz_clusters mz_clusters_ind=[differential join]        +
                                                                                   +
 Used Indexes:                                                                     +
   - mz_internal.mz_clusters_ind (differential join)                               +
   - mz_internal.mz_show_sources_ind (lookup)                                      +
   - mz_internal.mz_sources_cid_ind (differential join)                            +

```

From the above, it seems like it's more complicated than an easy swap to get the new indexes to be as performant as the existing one for SHOW commands. Rather than risk affecting performance on those, it might be easier in the short term to add new indexes on id to the objects you listed above, then migrate over the SHOW indexes separately as a follow up.

**Comment by chaas** [comment]
Discussed in adapter & console weeklies - we will start by indexing all the base mz_catalog/mz_internal tables used by the console, as well as add indexes on frequently-executed queries, such as ones that are run on a polling basis or on every page load.
Pros of this approach:
- Avoids hitting persist for console queries, which should speed up queries
- Doesn't require adding or modifying indexes every time a console query is changed or added

Cons:
- Manual - have to identify the base tables and manually add the indexes, if new console queries use new tables, we still need to remember to index those tables
- Queries themselves are not all indexed, so still may be expensive to execute
- We're increasing memory usage on customer mz_introspection clusters for these indexes

Full list of mz_catalog/ mz_internal tables used by the console, see https://docs.google.com/spreadsheets/d/1VPMergE7iE-_QCfi74lu8fT2Bb2eyibk-kRax13QmNA/edit#gid=0.
Ones needing an index:
`mz_catalog.mz_indexes` ON `id`
`mz_catalog.mz_relations ` ON `id`
`mz_catalog.mz_roles ` ON `id`
`mz_catalog.mz_sources` ON `id`
`mz_catalog.mz_sinks` ON `id`
`mz_catalog.mz_materialized_views` ON `id`
`mz_internal.mz_cluster_links` ON `cluster_id`
`mz_internal.mz_object_dependencies` ON `object_id`
`mz_internal.mz_cluster_replica_history` ON `dropped_at`
`mz_internal.mz_show_my_schema_privileges` ON `privilege_type`

Open for discussion:
`mz_internal.mz_cluster_replica_utilization` ON `replica_id` - is there a reason we wouldn't want to index this?
`mz_internal.mz_compute_exports` - this is per-replica, so I don't think we can index it on the introspection cluster
`mz_internal.mz_dataflow_arrangement_sizes` - same as ^, this is per-replica
`mz_catalog.mz_audit_events` - maybe we shouldn't index this one b/c it can get very large? Not sure where this is used in the console specifically.

 @RobinClowers / @SangJunBak can you review this list and let me know if you think we should exclude any of them?

Also, @RobinClowers I didn't include the complicated dependency graph queries and the catalog tables they use, since I wasn't sure what you wanted to do for those. Feel free to add them to this list if you think they should be indexed.

**Comment by RobinClowers** [comment]
I had Parker T add `mz_object_fully_qualified_names` which is indexed, but I realized that in order to work for us, it needs to include the database and schema IDs as well, to support filtering on them. That said, it might make sense just to index the underlying tables anyway.

**Comment by RobinClowers** [comment]
Also thanks again for doing such a thorough review of the queries!

**Comment by RobinClowers** [comment]
`mz_cluster_replica_utilization` appears to over things that are indexed, unless I'm reading the plan wrong? 
```
materialize=> explain select * from mz_internal.mz_cluster_replica_utilization;
                                                                                 Optimized Plan
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Explained Query:                                                                                                                                                               +
   Project (#0, #15, #19..=#21)                                                                                                                                                 +
     Filter (#3) IS NOT NULL                                                                                                                                                    +
       Map (((uint8_to_double(#16) / uint8_to_double(#10)) * 100), ((uint8_to_double(#17) / uint8_to_double(#11)) * 100), ((uint8_to_double(#18) / uint8_to_double(#12)) * 100))+
         Join on=(#0 = #14 AND #3 = #7) type=differential                                                                                                                       +
           ArrangeBy keys=[[#0]]                                                                                                                                                +
             ReadIndex on=mz_cluster_replicas mz_cluster_replicas_ind=[differential join]                                                                                       +
           ArrangeBy keys=[[#0]]                                                                                                                                                +
             ReadIndex on=mz_cluster_replica_sizes mz_cluster_replica_sizes_ind=[differential join]                                                                             +
           ArrangeBy keys=[[#0]]                                                                                                                                                +
             ReadIndex on=mz_cluster_replica_metrics mz_cluster_replica_metrics_ind=[differential join]                                                                         +
                                                                                                                                                                                +
 Used Indexes:                                                                                                                                                                  +
   - mz_internal.mz_cluster_replicas_ind (differential join)                                                                                                                    +
   - mz_internal.mz_cluster_replica_sizes_ind (differential join)                                                                                                               +
   - mz_internal.mz_cluster_replica_metrics_ind (differential join)                                                                                                             
```

**Comment by RobinClowers** [comment]
RE `mz_catalog.mz_audit_events`, Parker T also added mz_object_lifetimes with just create and drop events, which is indexed. I think we should switch all our queries to use that instead of the audit events table.

**Comment by RobinClowers** [comment]
I think we should also index `mz_internal.mz_object_dependencies` and `mz_internal.mz_compute_dependencies`, for the dependency graph. Those tables are not huge, maybe a few thousand small rows in most cases.

**Comment by chaas** [comment]
> mz_cluster_replica_utilization appears to over things that are indexed, unless I'm reading the plan wrong?

Ah I didn't check the explain plan for these to see if they're already over indexed things.
Doing that I realized:
`mz_relations`: if we index `mz_sources` and `mz_materialized_views` we don't need this one.
`mz_internal.mz_show_my_schema_privileges`: if we index `mz_roles` we don't need this one.

> I had Parker T add mz_object_fully_qualified_names which is indexed, but I realized that in order to work for us, it needs to include the database and schema IDs as well, to support filtering on them. That said, it might make sense just to index the underlying tables anyway.

Hmm not seeing that one indexed. It uses `mz_objects`, `mz_schemas`, and `mz_databases`, which are indexed, but if we're running it with every query we might as well make the view fully useful & index it separately.

> RE mz_catalog.mz_audit_events, Parker T also added mz_object_lifetimes

Confirmed that one is also indexed!

Updated list:
`mz_catalog.mz_indexes` ON `id`
`mz_catalog.mz_roles ` ON `id`
`mz_catalog.mz_sources` ON `id`
`mz_catalog.mz_sinks` ON `id`
`mz_catalog.mz_materialized_views` ON `id`
`mz_internal.mz_cluster_links` ON `cluster_id`
`mz_internal.mz_object_dependencies` ON `object_id`
`mz_internal.mz_compute_dependencies` ON `dependency_id`
`mz_internal.mz_cluster_replica_history` ON `dropped_at`

**Comment by chaas** [comment]
This is merged! I didn't make the Thursday release cutoff, so this won't go out until the week of 10/16.

On staging, even when creating a lot of objects, the memory utilization was only 1%, so as long as we monitor customers post-release, I'm not worried.
These 9 new indexes should only have max tens of thousands of rows each, and probably much less in practice, so the memory usage is small.
