### ISSUE TITLE
adapter: catalog consistency violation

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#21958]
See https://github.com/MaterializeInc/materialize/pull/21957

**Comment by mjibson** [comment]
`test/testdrive/kafka-avro-sinks-defaults.td`:

```
# Limited test
> CREATE TYPE point AS (x integer, y integer);
> CREATE TYPE custom_map AS MAP (KEY TYPE = text, VALUE TYPE = bool)
> CREATE TABLE t (c1 point, c2 text NOT NULL, c3 integer[], c4 custom_map);
> INSERT INTO t SELECT ROW(1, 1)::point AS c1, 'text' AS c2, ARRAY[1 , 2] as c3, '{a=>true}'::custom_map as c4;

> CREATE MATERIALIZED VIEW v AS SELECT * from t;

> DROP SOURCE upsert_input CASCADE;
> DROP TABLE t CASCADE;
> DROP TYPE point;
> DROP TYPE custom_map;
```

**Comment by moulimukherjee** [comment]
Looks like the `c3 integer[]` column was the problem. Stopped erroring out after removing it.

**Comment by jkosh44** [comment]
> Where is the CREATE statement being transformed in step (4)?

It's actually name resolution itself that does this transformation:

https://github.com/MaterializeInc/materialize/blob/f0ef1ffa4d394723150a6b9a1ad261cc9407a4c8/src/sql/src/names.rs#L1219-L1257

Specifically the fact that we return a `ResolvedDataType::Named` with an `id` of `array_item.id()` causes the resolved type to be `_int4` instead of `int4[]`. There actually is no `ResolvedDataType` variant that could represent `int4[]`.

One solution is to always include both the named array type and the array element type in the resolved IDs. So for example, both `CREATE TABLE t (a int4[])` and `CREATE TABLE t (a _int4)` would include the Global ID for `int4` and `_int4` in the set of resolved IDs.

**Comment by jkosh44** [comment]
> The issue results in an item's dependencies changing after a restart, how are these dependencies used and what is the observable behavior from a user's perspective?

The dependencies are saved in the in-memory catalog and used for the `references()` method:
https://github.com/MaterializeInc/materialize/blob/b56c83ef5c514699260156afbdca8325107b1a20/src/catalog/src/memory/objects.rs#L823-L840

That method is used to:

- Populate the `mz_object_dependencies` table.
- Check if an item has any unstable references.
- Check if something should run on `mz_introspection`.
- Find all transitive storage and compute dependencies.

**Comment by mjibson** [comment]
> One solution is to always include both the named array type and the array element type in the resolved IDs.

This seems good to me?

**Comment by jkosh44** [comment]
> > One solution is to always include both the named array type and the array element type in the resolved IDs.
> 
> This seems good to me?

Me too, this is what I ultimately decided on implementing: https://github.com/MaterializeInc/materialize/pull/25739. Just waiting on CI.
