### ISSUE TITLE
Convert internal clusters to managed clusters

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#22326]
### Feature request

Once #19762 lands, we'll support the notion of managed clusters. We should convert clusters managed by Materialize (`mz_introspection`, `mz_system`) to use managed clusters.

**Comment by jubrad** [comment]
One note here is that due to https://github.com/MaterializeInc/materialize/issues/20010, there won't be a way to resize of the introspection/system cluster without some downtime. Just want to check that we're ok with the ramifications of this for support.
cc @pH14

**Comment by chaas** [comment]
I'm ok with a short amount of downtime for resizing these clusters because if we're doing a resize outside of the release window, it's presumably because there's an issue causing downtime anyways. As such, the incremental additional downtime of the resize is not going to have a significant impact.
@pH14 do you have an opinion from the support/monitoring/uptime perspective?

**Comment by pH14** [comment]
No concerns here, I agree that we only need to resize when there's already an issue so it's sort of moot
