### ISSUE TITLE
sql: Add hint to error message for unquoted but cased identifier

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#22427]
### Feature request

[Slack](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1697484191320669)

Postgres spec requires that we normalize identifier to lowercase, this makes querying tables with upper case identifiers really frustrating, e.g.

```sql
materialize=> CREATE TABLE foo1 ("X" int);
CREATE TABLE

materialize=> INSERT INTO foo1 VALUES (1), (2), (3);
INSERT 0 3

materialize=> SELECT X FROM foo1;
ERROR:  column "x" does not exist
```

We should either add a hint to the error to let the user know:

1. They provided an uppercase identifier that we normalized to lowercase, they need to surround the identifier in quotes to preserve casing.
2. The column they specified does not exist, but there is a column with a similar name.

**Comment by benesch** [comment]
> The column they specified does not exist, but there is a column with a similar name.

I would suggest starting with this fix, as it's more targeted! If you have a table with column `Foo` (but no `foo`) and someone shows up asking for an identifier `foo`, it is almost _certainly_ a typo and the hint to use `"Foo"` instead is almost certainly right.

This will also handle cases where a user _does_ double quote the miscased reference(`"foo"`), but legit just got the casing wrong inside of their double quotes.

> They provided an uppercase identifier that we normalized to lowercase, they need to surround the identifier in quotes to preserve casing.

There are some ORMs and such that will always use uppercase but unquoted identifiers, as in:

```
CREATE TABLE FOO (ILIKESHOUTING TEXT);
SELECT ILIKESHOUTING FROM FOO;
```

And this is totally fine because they're consistently relying on the lowercase normalization everywhere. So sending a notice in this case has the potential to be misleading.
