### ISSUE TITLE
regression: compute replica in the shared dev environment is OOMing after upgrade 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#22431]
### What version of Materialize are you using?

v0.73.0 (4fc7b0654)

### What is the issue?

The compute replica that is used to run the materialized views of the canary workload that is running in the shared dev environment has started OOMing after being trouble free for the past 30 days:

https://console.materialize.com/regions/aws-us-east-1/clusters/u145/qa_canary_environment_compute?timePeriod=43200

![image](https://github.com/MaterializeInc/materialize/assets/1279722/1f8cf8b7-ec02-44bf-b1ab-174d11a61b52)

The replica is currently unhealthy and apparently can not recover on its own.

**Comment by philip-stoev** [comment]
![image](https://github.com/MaterializeInc/materialize/assets/1279722/b71132cb-6d6a-477f-9ec5-7a5d52094c4a)
container uptime

**Comment by teskje** [comment]
The replica is healthy again, fixed by the following steps:

* Unset `enable_mz_join_core` in LD for the env, to switch on the DD join.
* Spawn an `xlarge` replica (although `large` would have been enough).
* Wait until the `xlarge` has fully hydrated all dataflows, giving storage permission to compact all dependencies.
* Drop the `xlarge` replica again.
* Set `enable_mz_join_core` in LD again for the env.
* Restart the original replica.

I've opened a ticket to track improving `mz_join_core` to make it able to handle workloads like this: #22438.

I think we can close this issue, or at least remove the `release-blocker` label. This is not a new bug, just one that was triggered by the extended replica downtime.

**Comment by philip-stoev** [comment]
Closed in favor of https://github.com/MaterializeInc/materialize/issues/22438
