### ISSUE TITLE
Sinks do not create compute dependencies

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#22625]
### What version of Materialize are you using?

v0.74.2 (22b33ffe8)

### What is the issue?

Despite being a compute object, sinks do not create an entry in `mz_compute_dependencies` for the upstream object they depend on.

We noticed this problem while developing the dependency graph, but presumably this might cause other issues as well.

**Comment by teskje** [comment]
Wait, sinks are not compute objects but storage objects! `mz_compute_dependency` only contains dependencies for objects maintained by compute, which is why sinks don't show up.

Storage objects are (this might be incomplete):
* Sources
* Sinks
* Tables
* Storage-managed collections (aka. `BuiltinSource`s)

**Comment by teskje** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/issues/23017
