### ISSUE TITLE
doc/user: expand monitoring documentation with alerting + key alerting thresholds

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#22921]
### Documentation request

We've added tool-specific guides to our docs ([Grafana](https://materialize.com/docs/manage/monitor/grafana/), [Datadog](https://materialize.com/docs/manage/monitor/datadog/)), but lack guidance on setting up alerting, in particular around what threshold values to look out for.

cc @MaterializeInc/devex

**Comment by joacoc** [comment]
I'm self-assigning this. I will begin this in the mid/end of the following week unless we have a big priority. I have related material.

**Comment by joacoc** [comment]
@morsapaes, does it make sense to have a dedicated page for '_Metrics_' in the Monitoring section? In it, I can dive deeper into details.

**Comment by joacoc** [comment]
Draft of threshold metrics that come to mind (warning and trigger values are speculative):

Metric | Warning | Trigger | Description
-- | -- | -- | --
CPU | - | 100% | CPU usage in a cluster.
Memory | 80% | 90% | Memory usage in a cluster.
Latency | p99 > 100ms | p99 > 1s | Latency from the activity log.
Distribution | > 20% | > 30% | Worker processing time distribution.
Lag | > 1s | > 1m | Lag for a particular Materialized View or Index.
Status | - | On Change | Source status.
Credits | - | credit consumption rate > X | Credit consumption in the last hour.

I'm looking for more metrics that I may be missing. cc @ggnall

**Comment by ggnall** [comment]
The list looks pretty good. I'm not 100% sure what the difference between warning and trigger is.

With idle merge changes, we might have better guidance on a CPU trigger, but 100% feels fine. 

Is this something users are going to grok? What's the purpose here, to detect worker skew? 
>Distribution

I wonder if these should be intentionally user defined. E.g. latency is arbitrary based on the work being done and query patterns. Maybe the trigger is like "your view's SLA" or similar. 
>Latency, Lag, Status, Credits

---

On another note, perhaps there's an approach to using grafana, etc to trigger on anomalies rather than explicit values? Going off of https://us-4286.app.gong.io/call?id=9001637805897218348

**Comment by joacoc** [comment]
> The list looks pretty good. I'm not 100% sure what the difference between warning and trigger is.

For me, a warning is like saying, "_this is acceptable but near the limit, watch out_," while a trigger is more like, "_something is off, take action_."

> Is this something users are going to grok? What's the purpose here, to detect worker skew?

Only in cases were a user is performing a cross-join or a join that unbalances workers. I noticed @chuck-alt-delete paying attention to it a short time ago and thought it could be useful for others too.

> I wonder if these should be intentionally user defined. E.g. latency is arbitrary based on the work being done and query patterns. Maybe the trigger is like "your view's SLA" or similar.

I agree with this. We can't set the value for Latency. I changed to "avg + %".

> On another note, perhaps there's an approach to using grafana, etc to trigger on anomalies rather than explicit values? Going off of https://us-4286.app.gong.io/call?id=9001637805897218348

Grafana introduced [anomaly detection](https://grafana.com/blog/2022/12/22/introducing-outlier-detection-in-grafana-machine-learning-for-grafana-cloud/) recently, but it is not yet available to everyone. Datadog has it in their free version, also they have forecasting, that I found very useful for memory consumption forecasting. If we want to suggest these approaches, we should broaden the scope from 'Alerting + Alerting Thresholds' to simply 'Alerting' and include these practices as suggestions.

**Comment by sthm** [comment]
How do we think about re/hydration with respect to these alerts? These thresholds feel like a good start, but many of them will likely trigger after each maintenance window.

**Comment by joacoc** [comment]
@sthm, that's a good detail. Datadog/Grafana offer [downtimes](https://docs.datadoghq.com/monitors/downtimes/)/[muting](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/mute-timings/). We could suggest this as a practice for the maintenance window.

**Comment by joacoc** [comment]
Draft created. Additional decisions taken open for change:
1. Renamed _Lag_ to _Freshness_ to match the console.
2. _Latency_ and _credits_ are in a dedicated **SLA Thresholds** table to differentiate from the other thresholds. Derived from @ggnall comment.
3. Distribution and Freshness are in the normal threshold table due to our specific preferences in the console (regarding freshness) and in the documentation (regarding distribution) for these values.
4. I added a section for the maintenance window. Derived from @sthm comment.

Notes taken during the process:
1. Troubleshooting section is hell. We should document common issues and actions to take.
2. Having a dedicated sizing page would be great for **1.** - We currently have [one section for sources.](https://materialize.com/docs/sql/create-source/#sizing-a-source)
3. We should document Console dashboards/tools.
4. As a next step, we can document additional techniques discussed here, like anomaly detection or forecasting.
