### ISSUE TITLE
Include environment id in Kafka sink transactional id

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#23198]
### Feature request

Today, Kafka sinks across multiple Materialize environments can generate identical transactional IDs[1]. These collisions can be problematic if multiple Materialize environments write to the same Kafka cluster. 

Transaction id should include environment id to be globally unique. 

[1] https://github.com/MaterializeInc/materialize/blob/9d3486b884b3df70b0c9f7cb0ca9d808d0d72e0e/src/storage/src/sink/kafka.rs#L473

*Nikhil's addition.* The group iD used to read the sink's past progress information today is _also_ lacking the environment ID. Today's format is `materialize-bootstrap-sink-{SINK ID}`. We should adjust this ID at the same time as we adjust the default `transactional.id`, as it will cause similar permissions issues. Better to force users to update their ACLs just once.

**Comment by guswynn** [comment]
@bkirwi we don't restart transactions on sink restart right? we should be able to change this without a migration?

**Comment by bkirwi** [comment]
That's right.

However, it would be quite bad if there were two versions of MZ writing at the same time with different sink transactional ids, since nothing would prevent them from committing the same data twice. We may want to add an extra check to the rollout plan when this is deployed...

**Comment by petrosagg** [comment]
> However, it would be quite bad if there were two versions of MZ writing at the same time with different sink transactional ids, since nothing would prevent them from committing the same data twice.

Doesn't this mean that we shouldn't change it? How would that extra check work?

**Comment by bkirwi** [comment]
I was mostly thinking of an operational / manual approach - identify environments with sinks and ensure that they're fully shut down before performing the upgrade.

You could probably do something clever by connecting with _both_ producer ids in separate producers, but that seems tricky to get right and to test.

**Comment by petrosagg** [comment]
> You could probably do something clever by connecting with both producer ids in separate producers, but that seems tricky to get right and to test.

That's a great idea! Agreed on testing being tricky but it sounds pretty simple to get right. All we'd have to do would be to call `init_transations` with the old producer id, which would bump the epoch in the broker and fence out any old versions, and then tear that producer down and start a new one with the new producer id. Since the new version of the code is guaranteed to both fance and not use the old producer id we can be certain no more transactions will be committed in the meantime

**Comment by bkirwi** [comment]
I worry about: what if the zombie producer is still starting up, so that it only attempts to claim the transaction id _after_ the newer version attempts to fence it out?

Totally believe you can plug holes like this, but this sort of trickiness is the reason I lean towards the dumb operational solution... hesitant to land code that is both subtle and single-use.

**Comment by benesch** [comment]
Due to ACLs, we're not guaranteed to have permission for the new format of the transactional producer. So I think the safest way to roll this out is to permanently grandfather old sinks into the old format. Otherwise we risk breaking existing sinks after the upgrade because we don't have permissions for the new transactional ID.

Here's how we could do the grandfathering:

  * Introduce a new feature flag called `enable_legacy_kafka_transactional_id_format`. Never set it to `true` for any customers.
  * Introduce a new Kafka sink SQL option called `LEGACY TRANSACTIONAL ID FORMAT`. If the option is set to `true`, the `enable_legacy_kafka_transactional_id_format` must be enabled.
  * Run a migration to install the `LEGACY TRANSACTIONAL ID FORMAT` option in all existing Kafka sinks.
  * (All feature flags are force enabled when bootstrapping the catalog, so even though `enable_legacy_kafka_transactional_id_format` is never set to true for any customers in LaunchDarkly, it's nonetheless enabled when bootstrapping the catalog.)
  * Plumb a `legacy_transactional_id_format` through the Kafka sink code based on the SQL option.
  * Choose the transactional producer ID format accordingly.

Then all existing sinks would continue to use the old transactional ID format, but all _new_ sinks would use the new transactional ID format.

Sinks tend to have a relatively short lifespan today, as they need to be recreated whenever logic changes, so I think we'd actually get all sinks onto the new codepath within a few weeks/months, and then we'd be able to clean up the legacy code.

**Comment by petrosagg** [comment]
I have two observations: 

1. Can we add a permanent `TRANSACTIONAL ID '<pattern>'` option that gets set during purification and for existing sinks we set the pattern we already have? This way we won't need to do any legacy code cleanup / feature flag business and we get a user feature out of it for anyone that wants to customize the id.
2. Why do we put the `worker_id` in the transactional id? We only do transactions from one leader worker which is picked by each worker evaluating `(sink_id.hashed() % total_workers) == worker_id`. However the chosen worker can change if you resize the cluster or if the hashing strategy between two releases changes which means a zombie cluster will not necessarily be fenced out by a new one, i.e we're in trouble. I think the correct id for new clusters should be `mz-producer-{environment_id}-{sink_id}`. Additionally if we took the `TRANSACTIONAL ID <pattern>` approach described above we could remove `worker_id` from the template and **hardcode** the currently chosen worker id number so that we fix the issue even for existing sinks.

**Comment by benesch** [comment]
> 1. Can we add a permanent `TRANSACTIONAL ID '<pattern>'` option that gets set during purification and for existing sinks we set the pattern we already have? This way we won't need to do any legacy code cleanup / feature flag business and we get a user feature out of it for anyone that wants to customize the id.

That seems reasonable to me, though we should consider whether the option should be `TRANSACTIONAL ID PREFIX` to align with `GROUP ID PREFIX`. For group IDs, we can only allow the user to supply a prefix, as we 

I don't _think_ there's ever a reason we'd need to append any additional data to the user-specified transactional ID, because by definition we'll never have multiple producers producing to the sink simultaneously, but we should double check.

> 2. Why do we put the `worker_id` in the transactional id? We only do transactions from one leader worker which is picked by each worker evaluating `(sink_id.hashed() % total_workers) == worker_id`. However the chosen worker can change if you resize the cluster or if the hashing strategy between two releases changes which means a zombie cluster will not necessarily be fenced out by a new one, i.e we're in trouble. I think the correct id for new clusters should be `mz-producer-{environment_id}-{sink_id}`. Additionally if we took the `TRANSACTIONAL ID <pattern>` approach described above we could remove `worker_id` from the template and **hardcode** the currently chosen worker id number so that we fix the issue even for existing sinks.

Yikes! 👍🏽 on hardcoding the currently chosen worker ID number.

I think a default transactional ID of `materialize-{REGION-ID}-{CONNECTION-ID}-{SINK-ID}` would align best with the existing default for group IDs? No need to use `producer` in the name (it's just noise, I think), and we use `materialize` rather than `mz` elsewhere in the Kafka defaults.

----

I think it's probably worth rolling the fix for this into the same release as the fix for https://github.com/MaterializeInc/materialize/issues/18628#issuecomment-1818013171. That way we only need to ask users to recreate their sinks once to get both fixes.

**Comment by petrosagg** [comment]
> That seems reasonable to me, though we should consider whether the option should be `TRANSACTIONAL ID PREFIX` to align with `GROUP ID PREFIX`.

Yes, that sounds good for the user facing interface. Note that for the migration we'd still need to have an internal-only `LEGACY TRANSACTION ID` syntax (that is forbidden for users to type) because the existing ID if of the form `mz-producer-{sink_id}-{worker_id}` which can't be expressed with just a prefix.

Also, a question about backward compatibility more generally: Even if we wrote a migration that transformed the old sinks into a new definition with an additional `LEGACY TRANSACTION ID` option injected into the SQL users could still get tripped up if they have automated scripts that create sinks (e.g for CI) and have configured specific ACLs for their broker. Is this rare enough that we're comfortable rolling out a release with changed defaults? After I typed this I realized that perhaps this was the reason you proposed a feature flag?

**Comment by petrosagg** [comment]
I looked at our documentation today and we say that we require this ACL for transactional ids: `mz-producer-{SINK ID}-*`. This tells me that it should be safe to simply roll out a new version that uses `mz-producer-{sink_id}-{environment-id}` as the transactional id with no migration whatsoever.

**Comment by benesch** [comment]
I only added that documentation recently. I think it's possible that a few folks in the wild granted an ACL based on a `transactional.id` that they saw in their logs, vs. what we recommend in the docs.

I'd also hate for the `transactional.id` to be permanently inconsistent with what we do for `group.id`.

**Comment by petrosagg** [comment]
I fixed the current footgun and I will leave the more involved migration to a separate PR https://github.com/MaterializeInc/materialize/pull/23363

**Comment by benesch** [comment]
In #23438, we discovered that the consumer group ID used to read back the progress information is _also_ lacking the environment ID. We should fix that up too. Added this to the issue description:

> The group iD used to read the sink's past progress information today is also lacking the environment ID. Today's format is materialize-bootstrap-sink-{SINK ID}. We should adjust this ID at the same time as we adjust the default transactional.id, as it will cause similar permissions issues. Better to force users to update their ACLs just once.
