### ISSUE TITLE
Support for FIRST/FIRST_VALUE and LAST/LAST_VALUE functions

### ISSUE THREAD

**Issue by bhoomit** [MaterializeInc/materialize#2321]
Keywords are defined but functionality is not implemented AFAIK. 

If it's not already supported, is there a plan to support this?

**Comment by wangandi** [comment]
`FIRST/FIRST_VALUE` and `LAST/LAST_VALUE` are not supported. The reason they are defined as keywords is because our sql-parser is derived from https://github.com/andygrove/sqlparser-rs , which is a project intended to support many different SQL dialects. (Also, to make migration between versions easier, it is probably better to have more potential functions/keywords reserved than not before people use them as non-keywords in their queries.)

It is unlikely that `FIRST/FIRST_VALUE` and `LAST/LAST_VALUE` will be supported in the coming future. Our priorities are to support the 92 SQL standard followed by PostgreSQL compatibility.

That said, you can get around having FIRST (resp. LAST) by using the query `SELECT colname from foo order by colname asc (resp. desc) limit 1`.

**Comment by bhoomit** [comment]
@wangandi Thanks for clarifying that. I will close this issue now.
