### ISSUE TITLE
Is Materialize distributed?

### ISSUE THREAD

**Issue by theseusyang** [MaterializeInc/materialize#2363]
Hi Team,

Materrialize is a distributed system, or can Materrialize scale horizontally?

like greenplum, Materrialize has master nodes and worker nodes.

**Comment by frankmcsherry** [comment]
Hello,

Materialize is designed to scale horizontally, but we've not been focusing on that with our initial release. In has in the past, and you should expect it to in the future.

Materialize's compute plane does not have master and worker nodes. You can read about the rough architecture in the [Naiad](https://sigops.org/s/conferences/sosp/2013/papers/p439-murray.pdf) paper

**Comment by rjnn** [comment]
Yes, it is a distributed system, designed as such from the ground up. Specifically, Materialize is built on top of Timely Dataflow, which is a scale-out distributed compute engine. 

For now we have not exposed the knobs that take advantage of it, intentionally: we consider current performance off by a factor of 10-100 from what we expect our throughput to be in the medium term. While today we can handle view maintenance in the face of message ingest rates in the ~10s of thousands (which is very competitive with similar systems that require multiple nodes to match Materialize on the subsets of queries that they can even execute), rather than focusing on scaling out the system prematurely, we are focusing on picking the low hanging fruit. 

It will take a while (6 months+?) to stabilize and productionize multi-node materialize. Rather than doing that to enable a 10-node Materialize cluster that can ingest a million Kafka messages per second, we've opted to try (optimistically, please read these numbers as stretch goals, not hard commitments from our side) instead on getting a single node Materialize deployment to handle that throughput this summer.

We'll focus on scaling out Materialize in the future (i.e. next year), once we've really got compelling evidence that a 48-core (r5d.24xlarge) Materialize deployment can go no further. For now, we're 2 orders of magnitude off that, giving us plenty of headroom to focus on.

Do note that this scaling out argument doesn't apply to fault-tolerance - if you're interested in distributing Materialize for resilience against node failure, we plan to implement active-active replication on a quicker timeline, but this does not increase performance, only availability.

**Comment by rjnn** [comment]
For some order of magnitude estimations of what that means, from Dropbox's [production numbers](https://dropbox.tech/infrastructure/finding-kafkas-throughput-limit-in-dropbox-infrastructure#result), my estimation is that a single Materialize node should be able to maintain highly complex views reading the maximum throughput from a 10-partition 10-broker Kafka cluster. It is only that at point that it makes sense to start considering distributed setups (and even then I expect that there will continue to be perf improvements in Materialize).

**Comment by theseusyang** [comment]
Ok, Thanks!
