### ISSUE TITLE
MFP Pushdown + ILIKE query has huge latency

### ISSUE THREAD

**Issue by SangJunBak** [MaterializeInc/materialize#23755]
### What version of Materialize are you using?

v0.79.0

### What is the issue?

**Problem:**
Adding an ILIKE condition with a temporal window can cause latency to jump from 3 seconds to 90 seconds for a huge dataset. However, the temporal window should reduce the data set to a much smaller one so that the ILIKE condition is computationally inexpensive.

**Reproduction steps:**
1. Have a considerable amount of data in `mz_internal.mz_activity_log`. For me, it was 1,660,139 rows generated from SQLSmith
2. Run the following query with a temporal window that returns a small amount of memory:
```sql
  select * from mz_internal.mz_activity_log as mal 
  WHERE 
    prepared_at > now() - interval '1day' 
    AND began_at > now() - interval '1day'
```

This returns ~300 rows under 4 seconds
[CSV of results](https://github.com/MaterializeInc/materialize/files/13603042/materialize_shell_export.3.csv)

3. Add an ILIKE condition on `redacted_sql` to the query
```sql
  select * from mz_internal.mz_activity_log as mal 
  WHERE 
    prepared_at > now() - interval '1day' 
    AND began_at > now() - interval '1day'
    AND redacted_sql ILIKE '%SHOW%';
```

This runs in ~90 seconds and returns a small number of rows.

The explain plan for the query in 3. is:
```
Explained Query:
  Project (#0, #2..=#7, #9..=#16, #8, #1, #20, #19, #18, #21, #22)
    Join on=(#1 = #17) type=differential
      ArrangeBy keys=[[#1]]
        Filter (#11 > 2023-12-05 22:03:10.037 UTC)
          ReadStorage mz_internal.mz_statement_execution_history
      ArrangeBy keys=[[#0]]
        Filter ilike["%SHOW%"](#4) AND (#5 > 2023-12-05 22:03:10.037 UTC)
          ReadStorage mz_internal.mz_prepared_statement_history

Source mz_internal.mz_statement_execution_history
  filter=((#11 > 2023-12-05 22:03:10.037 UTC))
  pushdown=((#11 > 2023-12-05 22:03:10.037 UTC))
Source mz_internal.mz_prepared_statement_history
  filter=(ilike["%SHOW%"](#4) AND (#5 > 2023-12-05 22:03:10.037 UTC))
  pushdown=((#5 > 2023-12-05 22:03:10.037 UTC))
```

There doesn't seem anything computationally expensive with the ILIKE condition. A hypothesis is we're trying to do an MFP pushdown on the ILIKE filter which is computationally expensive. This doesn't occur for any other conditions like ` AND redacted_sql = ''`.

**Comment by bkirwi** [comment]
After stewing on this for a bit, I think this may be because:
1. Filter pushdown is careful to preserve the error semantics of the original query. In particular, if a filter might raise an error on any row in a part, we _always_ fetch the part.
2. We don't track enough info internally to know that `ILIKE` is infallible - ie. it never raises errors on non-error inputs.

Assuming that's right, we could decide to tackle this from either end:
1. We could allow reordering filters to push down more aggressively. The SQL semantics are very generous when it comes to stuff like this.
2. We could add a `is_fallible()` method to `func`, and use that in the interpreter to rule out errors.

**Comment by frankmcsherry** [comment]
We have a method in `func.rs` that covers this, but it is very narrow at the moment:
```
    /// Returns true if the function could introduce an error on non-error inputs.
    pub fn could_error(&self) -> bool {
        match self {
            BinaryFunc::Eq
            | BinaryFunc::NotEq
            | BinaryFunc::Lt
            | BinaryFunc::Gte
            | BinaryFunc::Gt
            | BinaryFunc::Lte => false,
            _ => true,
        }
    }
```
I think reordering the filters makes plenty of sense. A non-compiled MFP (vs a MfpPlan) has no defined evaluation order, and you should feel welcome to re-order predicates as you like!

**Comment by umanwizard** [comment]
@bkirwi how easy is it for persist to properly support this assuming we add ilike to could_error ?

**Comment by bkirwi** [comment]
@umanwizard - very easy turns out: https://github.com/MaterializeInc/materialize/pull/23898. Thanks @frankmcsherry for the tip.

> I think reordering the filters makes plenty of sense. A non-compiled MFP (vs a MfpPlan) has no defined evaluation order, and you should feel welcome to re-order predicates as you like!

This is also quite simple to do; essentially we just have to unwind this change:

https://github.com/MaterializeInc/materialize/blob/1f8dbd727725fece4496f883e671c8460a900e78/src/expr/src/interpret.rs#L280-L285

I'll want to think a little harder to make sure it has no surprising consequences, though.

**Comment by bkirwi** [comment]
Here's a draft for the other half of the issue; relaxing our error semantics: https://github.com/MaterializeInc/materialize/pull/23935

I've written a bit more on that PR about why it has to cash out that way and why it makes me a bit nervous, even though I still think it's worth pursuing.

**Comment by SangJunBak** [comment]
Seems like this is fixed
