### ISSUE TITLE
Don't allow users to create indexes over mz_catalog objects

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#23947]
Currently we allow users to create indexes over catalog objects, for example this works
```
> CREATE INDEX my_index on mz_tables (id);
```
This creates an index on the current cluster named my_index in the mz_catalog schema, because indexes are created in the same schema as the underlying object.

We shouldn't allow this because it means users can create objects in the mz_catalog schema, which should be reserved for system objects.
Also there's a risk that a user creates an index named something that clashes with a relation we add in a future release.

Instead, we should recommend users create views over the catalog table queries they want (therefore in a user schema), and then create the index on top of that view.
Such as
```
> CREATE VIEW cara_tmp_v as SELECT  o.id object_id, s.name as schema_name from mz_objects o LEFT JOIN mz_schemas s ON o.schema_id = s.id;
> CREATE INDEX cara_tmp_i on cara_tmp_v (object_id);
```

**Comment by chaas** [comment]
Note: before we implement this change, we should first check whether any user-created indexes over catalog objects already exist. If so, we'll have to either ask the customer to drop the indexes or continue to support pre-existing ones.

**Comment by jkosh44** [comment]
Just an FYI, this feature was purposely added in the past: https://github.com/MaterializeInc/materialize/issues/3751

Maybe we didn't care or know about the index being created in a system schema.

> Also there's a risk that a user creates an index named something that clashes with a relation we add in a future release.

This isn't a huge risk because all of our system index names start with `mz_` and we prevent users from creating objects with a name that starts with `mz_`.

**Comment by jkosh44** [comment]
PostgreSQL does not allow this, so I think we should follow their example and prohibit this as well.

**Comment by chaas** [comment]
Ah hmm, totally forgot about https://github.com/MaterializeInc/materialize/issues/3751, that was right when we were figuring out the `mz_introspection` strategy, so think it's ok to change our opinion based on what we've learned since then.
Great point on the `mz_` prefix.

It's still odd to allow users to create objects in a system schema, so esp since PostgreSQL doesn't allow it, I agree we should follow their example and prohibit this as well.

@benesch any thoughts since you were part of the original issue convo?

**Comment by benesch** [comment]
> @benesch any thoughts since you were part of the original issue convo?

Just that I think Joe is right here about the cause:

> Maybe we didn't care or know about the index being created in a system schema.

I concur. I think we probably just didn't consider the weirdness of being able to create an index in a system schema.

Thinking about it more, it _is_ reasonable to want to be able to create an index on a system object—e.g., because you want fast access to (say) `mz_views` from a cluster besides `mz_introspection`. But, I think the built-in indexes on `mz_introspection` are pretty good, such that there usually isn't a burning need to create indexes on system objects in user clusters.

I'm supportive of:

  1. Disabling creation of indexes in `mz_catalog` and `mz_internal` for now, since it's very weird and at variance with PostgreSQL to allow users to create indexes in a system schema.
  2. Kicking the can down the road on finding a different way to allow users to create indexes on system objects in user clusters. For example, perhaps it is reasonable to allow creating an index in a _different_ schema than the object itself. That's a can of worms to open, I'm sure, but possibly it is a reasonable approach to pursue.
