### ISSUE TITLE
regression: thread 'coordinator' panicked at src/persist-txn/src/lib.rs:485:10: shard should not be closed

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#23964]
### What version of Materialize are you using?

580d2e024d

### What is the issue?

Several Nightly tests have started panicking as follows:

```
legacy-upgrade-materialized-1     | thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a2a2b95c29cb0a53-1/materialize/tests/src/persist-txn/src/lib.rs:485:10: shard should not be closed
```

https://buildkite.com/materialize/nightlies/builds/5635

ci-regexp: shard should not be closed

**Comment by philip-stoev** [comment]
I was unable to bisect due to technical issues with the legacy upgrade test, but the following two commits fall into the problematic range:

```
commit f2b3465bb0d99811a3054a19da8a78110f27a184
Author: Ben Kirwin <bkirwi@materialize.com>
Date:   Mon Dec 11 17:57:26 2023 -0500

    Clarify 'finalized' vs. 'tombstoned'
    
    In the current state, a shard is a tombstone once it's no longer
    readable or writable, but it may still have part files referenced in the
    trace. We call it 'finalized' only once it's both tombstoned and empty.

commit cccb929c27c3523db24ef23a51e13cb53f3845a7
Author: Joseph Koshakow <koshy44@gmail.com>
Date:   Fri Dec 15 14:31:03 2023 -0500

    persist-txn: apply shard registrations (#23899)
    
    Previously, after registering a data shard into a persist transaction
    handle, the physical upper of the data shard was not moved. However,
    the dataflow operator would wait for something something TODO(jkosh44)
    make this commit message better. Then the dataflow operator is stuck
    waiting for the physical upper of the data shard to advance to the
    registration timestamp.
    
    This commit adds the concept of applying a register, which will advance
    the upper of the data shard to the register timestamp.
    
    Touches #22173
    Touches #22801
```

@bkirwi @jkosh44

**Comment by bkirwi** [comment]
cc @danhhz as txns expert also

**Comment by jkosh44** [comment]
Looking at the stack trace, it's very likely that this is due to my commit. The order of events looks something like this:

- Initialize transactions in the storage controller.
  - Forget all shards.
    - Apply all transactions <= latest write
      - Apply a register by executing an empty caa at the register ts.
        - Get the current upper of the shard.
          - Panic because the shard is closed and there is no upper.

Some questions I have that I'll look into:
- Why is the shard closed?
- If the shard is closed, that implies we've already applied the registration before. Why hasn't the shard compacted past the registration timestamp, allowing us to skip the application of the register.
- Applying transactions (both writes and registers) should be idempotent, however currently they fail if the shard has been closed. Do we need to add logic that returns successfully when applying a transaction on a closed shard?

**Comment by danhhz** [comment]
> Why is the shard closed?

Very likely because whatever it represents was dropped and we're deleting it.

> If the shard is closed, that implies we've already applied the registration before. Why hasn't the shard compacted past the registration timestamp, allowing us to skip the application of the register.

Almost certainly because compaction isn't guaranteed. It works on a capability/hold system, but compaction is always only a performance optimization so persist users are required to be ready to deal with a `downgrade_since(x)` call not actually advancing the global shard since to `x`.

> Applying transactions (both writes and registers) should be idempotent, however currently they fail if the shard has been closed. Do we need to add logic that returns successfully when applying a transaction on a closed shard?

I think apply probably needs to treat "closed" as something that sorts as not less_equal to any possible timestamp. This is exactly what Antichain does, so maybe we just need to make `apply_le` use real Antichain logic?

**Comment by jkosh44** [comment]
> so maybe we just need to make apply_le use real Antichain logic?

That sounds right to me. Or at least update `apply_caa` and `empty_caa` to use Antichains, since that's were the panic is coming from.

**Comment by jkosh44** [comment]
Thoughts on this approach: https://github.com/MaterializeInc/materialize/pull/23989/commits/3c3e78e21b776d901c83c90ad8fe23e59848b207 it seems to resolve the issue and seems a lot less daunting than plumbing `Antichains` through a lot of methods.

https://buildkite.com/materialize/nightlies/builds/5646#018c7e34-9223-47bd-8f09-c3495a3e0776

**Comment by danhhz** [comment]
Oh that approach seems great, I'll go stamp the PR
