### ISSUE TITLE
sqllogictest has become twice as slow

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23980]
### What version of Materialize are you using?

a8e68c5959

### What is the issue?

I'm investigating. Last good version: https://buildkite.com/materialize/sql-logic-tests/builds/5765#_
First bad version: https://buildkite.com/materialize/sql-logic-tests/builds/5767#018c6d75-4bb5-41d9-bbd3-65f833b791a2

**Comment by def-** [comment]
Apparently this was caused by https://github.com/MaterializeInc/materialize/pull/23860 @aljoscha @bkirwi @danhhz Is this expected to be slower and should we just live with that? Otherwise, should we maybe change the defaults for the long SLT at least so that it can run (relatively) quickly. We already had a few instances where SLT became X times slower, now it's doubling in runtime again, this makes large-scale testing harder and harder.

**Comment by danhhz** [comment]
Oh hmmmm, I wonder if pubsub isn't hooked up for sqllogictest?

**Comment by def-** [comment]
Is --persist-pubsub-url all that is requied? If so, I can try to make that work for SLT.

**Comment by danhhz** [comment]
IANASLTExpert, but I think the issue is that SQL essentially replaces environmentd, so we'd have to make sure the following happens:
- The sqllogictest main should start up a pubsub GRPC server like environmentd does. 
- Then it has to be sure to pass `--persist-pubsub-url=foo` to _clusterd_ where foo is some address that clusterd can resolve as the pubsub server running in the sqllogictest main. This might require some docker shenanigans

The nice thing about this is it will almost certainly make SLTs waaay faster than before #23860, and they'll also used far less crdb traffic!

The bad news is I have no idea how involved it is and there's no way I could get to looking at this soon. If you want to pick this up, by all means, but I'm also 100% fine with reverting #23860 and then using this issue as a tracking issue for plumbing pubsub in SLT and getting it unreverted

**Comment by benesch** [comment]
#24023 looks to successfully enable PubSub!
