### ISSUE TITLE
Support microseconds in the http sql api

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#24026]
### Feature request

For both the http and websocket protocols, datetimes are serialized as unix timestamps, which only support millisecond precision. Since Materialize itself supports microseconds, we should have a way to represent these values in our http apis as well.

Since we return numbers as strings anyway, one idea to handle this is include the microseconds as a decimal, e.g. `1703005098935.789`, that way clients that use `parseInt` will continue to work, but they can also handle the decimal if they want.

[Slack context](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1702961226157349)

**Comment by benesch** [comment]
After a quick skim, the problem seems to be our JSON encoding in interchange, which drops microseconds in timestamps on the floor:

https://github.com/MaterializeInc/materialize/blob/edf90b026683390769d5e46e40a18e3df3f5c005/src/interchange/src/json.rs#L160-L167

This means JSON-formatted Kafka sinks are also lacking microseconds, in addition to the HTTP and WS interfaces.

The good news is that we're using strings here, not numbers. That gives us a little flexibility. Here's an example. Right now we convert the timestamp `2023-12-19T06:50:37.123456` to `"1703011837123"`—note the lack of the `456` microseconds. We could instead convert the timestamp to `"1703011837123.456"`. Consumers that support microseconds will be able to parse out the fraction; consumers that only support milliseconds can simply ignore the fraction.

This would technically be a breaking change, but I imagine most consumers today of this format are doing something like `parseInt(ts)` in JavaScript. This will continue to work, even if we start shipping fractional milliseconds! So I think we can get away with this change.
