### ISSUE TITLE
Logging and panics can interleave on same line in output

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24088]
### What version of Materialize are you using?

73b6355108d6

### What is the issue?

In https://buildkite.com/materialize/tests/builds/71794#018c8ed6-1027-43c0-9949-c2867ff0f215 the INFO logging and panic message ended up on the same line, which I believe should not happen:
```
cluster-materialized-1  | thread 'timely:work-3' panicked at src/expr/src/scalar/func/impls/string.rscluster-u1-replica-u1: 2023-12-22T00:10:10.083219Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
cluster-materialized-1  | :1025:9:
cluster-materialized-1  | forced panic
```
It seems that the panic message doesn't write the entire line atomically, I guess having our own panic handler and synchronizing it with the logging would help: https://doc.rust-lang.org/nomicon/panic-handler.html

The immediate problem is that this breaks the parsing we do to detect known panics/errors in CI, see https://github.com/MaterializeInc/materialize/blob/main/doc/developer/ci-regexp.md
But I believe this can also cause confusion on production systems when trying to grep for a specific string and having it interleaved with others.

**Comment by guswynn** [comment]
I need to think about how best to handle this; the default hook writes to stderr, and is fairly complex (it has to handle things like capturing output in tests and what not, and double-panics); recreating it with `tracing` is probably impossible, but we may be able to instead use a simpler version as long as we do not use it in tests...

**Comment by guswynn** [comment]
For posterity, when I get to this, there IS a way to check if there is a no (global or thread-local) subscriber, but its slightly weird:

```
fn main() {
    eprintln!("before setting:");
    tracing::dispatcher::get_default(|d| {
        assert!(dbg!(d.is::<tracing::subscriber::NoSubscriber>()));
    });

    tracing_subscriber::fmt().init();

    eprintln!("after setting:");
    tracing::dispatcher::get_default(|d| {
        assert!(!dbg!(d.is::<tracing::subscriber::NoSubscriber>()));
    });
}
```

**Comment by guswynn** [comment]
@def- I thought about this quite a bit, and did some research, and I am convinced there is no satisfying way to fix this:

Logs (through `tracing`) and the panic message both currently write to stderr. To prevent interleaving, the panic handle specifically must lock it (https://doc.rust-lang.org/std/io/struct.Stderr.html#method.lock). It is insufficient for `tracing` to lock stderr (it currently doesn't, but a vast majority of messages are single-line so we dont see problems), as the panic handler itself is the one buffering lines into `stderr`.

We could write our own panic handler that DOES lock stderr, but there are 2 reasons not too:
- the default panic handler (the one that currently prints out panics) has an immense number of features that we cannot replicate as we don't have nightly features (things like, capturing output for tests, the exact semantics of backtrace formatting, etc). We _could_ make it so we override this handler only in mzcompose/zippy tests so that we lock stderr, but: 
- https://github.com/rust-lang/rust/issues/96706 suggests that locking stderr as part of panic handling comes with the risk of deadlock; its unclear to me how this occurs, but its makes me quite scared


I think the only feasible alternative we have is having logging go to stdout in `mzcompose` (a bit against our philosophy, I know: https://materializeinc.slack.com/archives/C0246GEHL8N/p1704759822272049), and have the error-checking software check the fd's separately. However, my understanding is that docker does NOT make this easy, especially if we want stdout and stderr in one log file in buildkite?

**Comment by def-** [comment]
Yes, this is quite annoying indeed. I don't see a good solution either.

**Comment by def-** [comment]
Actually, how about we make a custom panic handler and just print the panic on one line again like it used to be? That would at least be easy.

**Comment by guswynn** [comment]
@def- as in before: https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html#cleaner-panic-messages

we can do that, but we will have to copy/recreate the backtrace printing that the default panic handler does

**Comment by def-** [comment]
Yes. But actually it doesn't solve the problem fully since we can have interleaving even on the same line still I guess. Somehow we didn't have this issue before Rust 1.73.0

**Comment by guswynn** [comment]
@def- perhaps we were just getting lucky? I do think that logging to stdout and tee-ing stderr and stdout to files for ci to inspect...but also i think this is pretty annoying to do: https://github.com/docker/compose/issues/8098

**Comment by benesch** [comment]
I briefly looked at this today.

> It is insufficient for `tracing` to lock stderr (it currently doesn't, but a vast majority of messages are single-line so we dont see problems)

It does seem like tracing tries very hard to write each log line to stderr atomically: https://github.com/tokio-rs/tracing/issues/668#issuecomment-609945964

**Comment by benesch** [comment]
> * suggests that locking stderr as part of panic handling comes with the risk of deadlock; its unclear to me how this occurs, but its makes me quite scared

Turns out to be trivial to cause this:

```rust
std::thread::spawn(|| {
    let stderr = std::io::stderr::lock().unwrap();
    loop { std::thread::park() }
})

panic!("deadlock will occur if panic handler attempts to take stderr lock")
```

Not sure how much that comes up in practice, but definitely a bit scary. I put up a panic handler in https://github.com/MaterializeInc/materialize/pull/29325 that will attempt to acquire the stderr lock for 1s, then fall back to printing directly to stderr without acquiring the lock.
