### ISSUE TITLE
mz_internal.mz_aws_connections is missing a row after a Backup+Restore or upgrade

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24113]
### What version of Materialize are you using?

1006f7e514

### What is the issue?

https://buildkite.com/materialize/nightlies/builds/5728

Multiple Platform Checks are failiing as  follows:

```
> SELECT assume_role_arn FROM mz_internal.mz_aws_connections a
JOIN mz_connections c ON a.id = c.id
WHERE name = 'aws_assume_role'
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
2:1: error: non-matching rows: expected:
[["assume-role-2"]]
got:
[]
Poor diff:
- assume-role-2
     |
   1 |
   2 | > SELECT assume_role_arn FROM mz_internal.mz_aws_connections a
```

That is, the mz_internal.mz_aws_connections is missing an entry for `assume-role-2` even though an entry for the other AWS connection created in the same test is present.

This is readily reproducible as follows:

```
./mzcompose --ignore-docker-version down -v ; ./mzcompose --ignore-docker-version run default --scenario=BackupAndRestoreAfterManipulate --check=AwsConnection
```

**Comment by philip-stoev** [comment]
@moulimukherjee @guswynn @benesch not sure who would be the right person/team to assign this to...

**Comment by philip-stoev** [comment]
Once it has failed, you can use:

```
psql -p  `docker port platform-checks-materialized-1 | grep '0.0' | grep 6875 | cut -d':' -f2` -h 127.0.0.1 -U materialize 
```
to log in the Mz instance and then you can run:

```
select * from mz_internal.mz_aws_connections;
```
and it will return 1 row. However,
```
materialize=> select count(*) from mz_connections where type = 'aws';
 count 
-------
     2
(1 row)
```
That is, the referential integrity between the two tables has been broken.

I am setting this to a release blocker as this is a form of data corruption with unknown downstream consequences.

**Comment by benesch** [comment]
Ah, this happens if the `materialized` instance is restarted without the necessary environment variables: 

https://github.com/MaterializeInc/materialize/blob/079fbca368526871749987408b9d506154bed1a7/misc/python/materialize/checks/mzcompose_actions.py#L44-L46

@philip-stoev I suspect I added those environment variables to the wrong spot, and they are not in effect after the checks framework restarts the environment. I could use your help to figure out where I should have added those environment variables.

**Comment by philip-stoev** [comment]
@benesch oh , let me check that.

**Comment by philip-stoev** [comment]
@benesch It seems https://github.com/MaterializeInc/materialize/pull/24114 will do the trick, so I will merge it. However, test issues aside, is it a concern that the referential integrity was broken in this situation?

**Comment by benesch** [comment]
> However, test issues aside, is it a concern that the referential integrity was broken in this situation?

Working as designed! If the AWS-related environment variables are missing on restart, I figured it was better to `error!` than to panic the whole `environmentd` and refuse to start up. I made the errors as loud as possible so that they get reported to Sentry in production.

There's no explicit foreign key between `mz_connections` and `mz_aws_connections`, so (IMO) not deep concerning correctness issues here. LMK if you disagree!
