### ISSUE TITLE
Add baked-in roles for query history objects

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#24267]
### Feature request

Currently, only superusers (and `mz_support`, in the case of redacted tables) can query any of the query history tables. We want superusers to be able to grant access to whoever they want, in accordance with their own organizational policies.

There are two ways to do this:

1. https://github.com/MaterializeInc/materialize/issues/24201 , which will allow arbitrary permissions to be set on arbitrary system objects;
2. Add some baked-in roles that have permissions on the relevant objects by default, which will automatically allow superusers to assign whatever users they like to said roles (this issue).

Note that **these projects are orthogonal**. If we do (1), we might still eventually want a way to specify default built-in roles on system objects, and if we do (2), we might still eventually want a way for superusers to specify fine-grained permissions. However, doing either of these projects solves the immediate needs for the query log. Thus, the main question is in which order we should do them.

I advocate for doing (2) (this issue) first, for two reasons:
* It is easier and faster, and
* It makes life easier for users of the statement log. They (or field eng.) don't need to keep track of which set of (mostly undocumented) objects they need to grant permissions to in order for the statement log features in the console to work.

The secondary question is what the builtin roles should be called and what tables they should encompass. Inspiring ourselves by [prior art from Postgres](https://www.postgresql.org/docs/current/predefined-roles.html), I suggest two roles: `mz_read_sql_history` and `mz_read_redacted_sql_history`. I use `sql`  in these names, rather than `statement`, because I intend them to encompass _all_ possible current or future use cases where users can see SQL types by other users, even those that are not directly connected to the present "statement logging" project. For example, I also intend these roles to apply to the optimizer hint tables that @aalexandrov worked on.

CC @benesch , @SangJunBak

**Comment by aalexandrov** [comment]
Can we drop the `_history` part from the proposed role names or come up with a more general term -- we have the history of SQL statements as one use case and the current set of active notices (not their history) as another.

**Comment by umanwizard** [comment]
I agree. Thanks for the suggestion.

**Comment by benesch** [comment]
I'm worried that `mz_read_sql` is not sufficiently clear. E.g., are the notices "SQL"? I can imagine users misinterpreting "SQL", too—e.g. thinking that you need this permission to issue read SQL queries, or something like that.

Some alternatives to suggest:

* `mz_monitor`
* `mz_monitoring`
* `mz_read_monitoring`
* `mz_stats`
* `mz_read_stats`
* `mz_activity`
* `mz_read_activity`


Of the options, I think I like `mz_monitor` the best. It mirrors the `pg_monitor` role, isn't tied to any of the existing terms ("activity log", "statement log", "notice history") nor overloaded terms ("SQL"). I also think for this role it makes sense not to include the `read` word, since I think `mz_write_monitoring` or `mz_write_sql` are roles that could not ever exist (vs. pg's `pg_read_all_data` and `pg_write_all_data`).
