### ISSUE TITLE
adapter: `INSERT` seems unstable for non-constant input

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#24612]
### What version of Materialize are you using?

v0.84.0

### What is the issue?

The `Coordinator::sequence_insert` method attempts to optimize the `plan.values` into a `selection: MirRelationExpr` and has a dedicated path that immediately spawns a task that inserts the raw values and immediately returns if (a) `selection` consists only of constant, and (b) the `INSERT` statement does not use the `RETURNING` syntax:

https://github.com/MaterializeInc/materialize/blob/0a5fb82b0b64f462d459b578d402e0cb2edf651d/src/adapter/src/coord/sequencer/inner.rs#L2836-L2846

However, if this branch is commented out, various tests in CI (both Tests and Nightlies) start failing, indicating possible bugs in the current "default path". See the failing tests in #24610 for example.

I think that:

- Somebody should go through the failing tests and triage for possibly scary bugs that need immediate attention.
- We should add more tests that stress out the non-constant `sequence_insert` path.

**Comment by umanwizard** [comment]
> However, if this branch is optimized out

Do you mean "commented out", rather than "optimized out" ?

**Comment by aalexandrov** [comment]
> Do you mean "commented out", rather than "optimized out" ?

Yes, sorry - fixed!

**Comment by mjibson** [comment]
This can be repro'd on main with no changes:

```
CREATE TABLE t (a INT);
BEGIN;
SELECT 1;
INSERT INTO t VALUES (1) RETURNING 0;
COMMIT;
```

**Comment by mjibson** [comment]
There's another (or the same perhaps) bug here:

```
CREATE TABLE t (i INT);
BEGIN;
SELECT 1;
SELECT * FROM t;
COMMIT
```

will execute the `SELECT * FROM t` on the system cluster because the `SELECT 1` pins the transaction to that cluster due to autorouting probably. If the SELECTs are swapped, then they are both executed on the user cluster: whichever is first wins for the rest of the transaction.

Gut sense: before clusters and autorouting we wanted non-timeline queries like `SELECT 1` to not mess with the transaction status so that a later statement in the txn could do the "nearby objects in the timedomain" thing. My guess is that when we added autorouting which *always* decides on a cluster even for constant queries that don't ever use a cluster, these two features started interacting in ways that no one tested.

**Comment by chaas** [comment]
Is the panic here https://github.com/MaterializeInc/materialize/issues/24341 related?

**Comment by mjibson** [comment]
Probably! Will attach it to the PR.
