### ISSUE TITLE
blue-green: Emit notice if swapped schemas have items with different permissions

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#24689]
### Feature request

If a user runs `ALTER SCHEMA blue SWAP WITH green` and there is an item in both "blue" and "green" with the same name and type, e.g. both contain a table named "t1", but that items has different permissions, we should emit a notice.

As users have started to do blue green deployments, an issue they've run into is when they lose permissions on objects because they forgot to properly set them before the swap

**Comment by benesch** [comment]
Good discussion on this on Slack today: https://materializeinc.slack.com/archives/C05SLRXKNGN/p1709588777068579

This feels similar to the idea of having `ALTER ... SWAP` prohibit swapping schemas with sources https://github.com/MaterializeInc/materialize/issues/24690#issuecomment-1938117651! I think it makes a lot of sense for _some_ tool to make sure that you've got the permissions synced properly between your schemas, but I think it's best if that's a higher level tool that's built on top of `ALTER SWAP`. That keeps `ALTER ... SWAP`'s purpose clear. It's just a low level tool that blindly swaps the named schemas, without any warnings or restrictions. It's up to the user to make sure that make sense.

The higher level tools are better positioned to deliver on a seamless UX here, too. dbt can _abort_ your deploy before you do the swap if the permissions out of sync, which can actively prevent an outage, rather than warning you about one after the fact. dbt will also, [one](https://github.com/dbt-labs/dbt-core/discussions/5781) [day](https://github.com/MaterializeInc/materialize/pull/22076), know what you want to _change_ the new permissions to, rather than only being able to detect mismatches, and can avoid warning you about mismatches that are the result of intentional changes.

**Comment by morsapaes** [comment]
We baked these checks into the blue/green deployment dbt workflow (see #25778, #25794). Closing this issue, based on @benesch's comment above.
