### ISSUE TITLE
Design and prototype source persistence

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#2490]
Required for #1182
Possibly related to #2078 

During the 0.3 timeframe, we should create a technical design for [source persistence](https://github.com/MaterializeInc/materialize/issues/1182) that's been reviewed by the experts in the areas of the code that it will affect.

**Comment by ruchirK** [comment]
Potentially also related to #1210 and #2221 

Writing down some thoughts from yesterday's conversation with Frank. This is purely me musing in a slightly more public space.

What are the goals of source persistence?

1. Decrease load on external systems when Materialize restarts -- currently Materialize does a full table scan on restart
2. Decrease Materialize restart times (at the very least not increase them / bound them to minutes)
3. Persist to storage in a cost efficient way for cloud deployments (S3) but also work on a laptop deployment

Non goals for source persistence:
1. Very low latency Materialize restarts (I think we want to bound it to minutes as opposed to the current world where restart latency is essentially unbounded w.r.t size of inputs
2. Very low latency on persistence (ie its ok to take time after a record arrives to make it persisted)

@rjnn is this set of goals + non goals accurate?

Straw-man definitely-not-great approach:

Copy a user's input data from their owned storage (e.g. Kafka topic) to our copy of it (Kafka actually makes this fairly easy with mirror-maker), and read from that. This approach achieves goal 1 but totally gives up on goals 2 and 3. I don't think we should do this but I've included it as a mental benchmark to weigh other approaches against

More realistic approach:

Source persistence is kind of a special case of sink persistence. With actual sink persistence we want to maintain some metadata about what records we have emitted so that on restart we don't emit them again. We circumvent this problem today by writing to different topics/files on each restart so that duplicates on restart don't happen.

However, if we had a more robust solution to sink persistence that actually solved this problem, you could imagine source persistence as for each source, maintaining a sink for a `select * from source` view and persisting that + on restart first reading from that data and then using the persisted sink metadata to determine from where to start reading the actual source.

**Comment by rjnn** [comment]
Goals are accurate!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ruchirK** [comment]
Ok awesome! Thanks for such a fast response :)

**Comment by ruchirK** [comment]
Writing down another conversation I had with @rjnn today -- the primary reason we don't want to just duplicate things into our own Kafka cluster is because there is a 5x cost advantage to saving things in S3 / tiered storage if we can do so efficiently. Having things in a Kafka deployment does not achieve this. This means that goal (3) in the list of goals above is specifically a design goal for this project and likely more important than goal (2). 

Finally, it seems like we want to focus on persisting sources and not other intermediate state because its unclear at the moment relative tradeoffs between saving and reloading intermediate state vs recomputation. There is however a clear reason that we want source persistence - goal (1) is a documented user pain point.

Open questions for me from talking to @benesch (just musing / writing down my thought process I don't need answers for this right away):

1. Assuming we went down the route of "writing down batches" -- how would we compact them in S3 / other persistent state?
2. How important is it to compact the things we write down? The way I see it -- compaction / "writing things down like a LSM" is pretty orthogonal to sink persistence which is more like "write down an append only log of things"

Finally, a meta-question: how do people feel about this approach to collaborating on design work? If there's another better process you'd like to see please let me know :)

**Comment by cuongdo** [comment]
Changed the name of this issue to include "prototype", because we are prototyping to help inform the design

**Comment by ruchirK** [comment]
I think we can close this issue as we have a design https://docs.google.com/document/d/1pevnBHYEwuigVXK3SMD5S5hhhdAED7VRBt7qNsHeS20/edit?usp=sharing and a prototype outside of materialize https://github.com/ruchirK/persisting-arrangements

**Comment by tisonkun** [comment]
@ruchirK it seems that the design document is private. Is it possible to be public?

**Comment by ruchirK** [comment]
Hi @tisonkun! We've actually switched to a totally new design for source persistence at this point, and hope to make a document for that public soon (in the next few months or so). For now, it might be best to look at https://github.com/MaterializeInc/materialize/blob/main/src/persist/README.md although a lot of stuff from that doc is also subject to change
