### ISSUE TITLE
"stash and persist result variant do not match" log line may get huge

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25043]
### What version of Materialize are you using?

04aff27eb6cdf406132dfbdbc247fff8b1207591

### What is the issue?

When an error occurs, this log line prints the stash and persist state, which can be huge. The line reached a length of 2.4 million characters [in an upgrade test.](https://buildkite.com/materialize/nightlies/builds/6333) Not sure if this is valuable and sensible and if the log tools can deal with it.

**Comment by jkosh44** [comment]
I actually do find the linked error fairly useful, it shows that the stash errored out because it thought we were downgrading versions which is not allowed while persist did not error out. The entire contents of persist are probably useless for this specific failure, but I tend to lean towards giving too much info during an error than too little. Is anything actually falling over due to the size of the error message?

> if the log tools can deal with it.

Is there a specific log tool you're referencing here that breaks with the large output?

**Comment by nrainer-materialize** [comment]
Nope, I just wanted to bring this up.

If we don't consider this a problem, we can close the issue.

**Comment by jkosh44** [comment]
My vote would be to close this issue. If the long log line starts causing issues then we can revisit.
