### ISSUE TITLE
mysql: truncate of MySQL table not reflected

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25051]
### What version of Materialize are you using?

b9f292f

### What is the issue?

```
$ mysql-execute name=mysql
CREATE TABLE truncate_table (f1 int, f2 int);
INSERT INTO truncate_table (f1, f2) VALUES (1, 1);

> create source mz_source
  from mysql connection mysql_conn
  for all tables;

$ mysql-execute name=mysql
TRUNCATE truncate_table;

> SELECT * FROM truncate_table;
```

Truncate is not applied. Note that this is currently also the case for Postgres due to https://github.com/MaterializeInc/materialize/issues/18518.

**Comment by morsapaes** [comment]
`TRUNCATE TABLE` in MySQL is included in the replication stream, and treated as a DDL statement ([docs](https://dev.mysql.com/doc/refman/8.0/en/replication-features-truncate.html)). The bigger question is how we should handle truncations downstream.

As is, I think we're forced to consider truncations an incompatible change, and error the subsource. This feels like a bug, though, rather than expected behavior. As a user, I'd expect my subsource to keep running and it's data to just be drained. From a quick chat with @petrosagg, this is a reasonable ask; we just don't have the required wiring in the ingestion pipeline yet. I'll open an issue!

**Comment by morsapaes** [comment]
Link to #25122.
