### ISSUE TITLE
adapter: Add guard rails around re-sizing `mz_introspection`

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#25134]
### What version of Materialize are you using?

v0.88.0-dev

### What is the issue?

Currently you can resize the `mz_introspection` cluster by running the following commands:

```SQL
CREATE CLUSTER REPLICA mz_introspection.<replica-name> SIZE '<size>';
DROP CLUSTER REPLICA mz_introspection.r1;
```

We should be ensuring the following:

- The system expects the `mz_introspection` replica to be named `r1`. Naming it something else will confuse the system and cause it to remake an `r1` replica on restart. We should prevent users from naming this replica anything but `r1`.
- The replica should have an ID in the `System` namespace. Currently we mistakenly give it an ID in the `User` namespace.
- This action should be restricted to only the `mz_system` role. I'm not sure if we allow any superuser to run this currently.

All of the above also applies to the `mz_system` cluster.

For more details, see: https://materializeinc.slack.com/archives/CTESPM7FU/p1707497185646239

**Comment by benesch** [comment]
We've wanted to convert these clusters to managed clusters, too: https://github.com/MaterializeInc/materialize/issues/22326

Might be nice to do that work together. Otherwise there's a risk of adding a bunch of bespoke guardrails for resizing them as unmanaged clusters that we have to toss once we tackle #22326.

Might also want to bundle together the work to move them to "cc" sizes: https://github.com/MaterializeInc/materialize/issues/24983

And also possibly this: https://github.com/MaterializeInc/accounts/issues/50

**Comment by jubrad** [comment]
With #26187 in, new internal clusters will be managed. This should proved the guardrail against creating any new replicas for internal clusters outside of changing the replication factor of the cluster.  I believe we can close this unless we still want to protect the case where someone alters the cluster to unmanaged?

**Comment by jkosh44** [comment]
We should double check the following before closing this:

> - The replica should have an ID in the System namespace. Currently we mistakenly give it an ID in the User namespace.
> - This action should be restricted to only the mz_system role. I'm not sure if we allow any superuser to run this currently.
