### ISSUE TITLE
thread 'test_old_storage_usage_records_are_reaped_on_restart' panicked at src/environmentd/tests/server.rs:1446:9: Records were not reaped!

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25193]
### What version of Materialize are you using?

1a2eb53a8ebc

### What is the issue?

```
thread 'test_old_storage_usage_records_are_reaped_on_restart' panicked at src/environmentd/tests/server.rs:1446:9:
Records were not reaped!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: server::test_old_storage_usage_records_are_reaped_on_restart::test_impl
             at ./tests/server.rs:1446:9
   3: server::test_old_storage_usage_records_are_reaped_on_restart
             at ./tests/server.rs:1363:1
   4: server::test_old_storage_usage_records_are_reaped_on_restart::{closure#0}
             at ./tests/server.rs:1363:1
   5: <server::test_old_storage_usage_records_are_reaped_on_restart::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/tests/builds/75556#018da301-8e8d-4168-afc0-ae77a65151a0

ci-regexp: Records were not reaped

**Comment by aljoscha** [comment]
@jkosh44  I've seen this fail before, and then I added this: https://github.com/MaterializeInc/materialize/commit/5ca194ae46ce99f2d26dfd2a89108e92a43d9b8c.

Before my recent changes, the `boot_ts` would basically advance by `5000` (I describe this in the commit above). Now, we advance it quite a bit less, which might be to flaky because we sometimes reap as many record as we expect. We could bump that now timestamp by a bit more, to make it more lenient. We could even bump it by 5000 to get back the previous behaviour of the test. Though it was subtly not doing the thing that the test expected it was doing.
