### ISSUE TITLE
thread 'coordinator' panicked at src/storage-controller/src/lib.rs:1492:17: Unknown collection identifier u1324

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25366]
### What version of Materialize are you using?

52db9fc334 (Pull Request #25288)

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/6522#018dc06f-df63-4a5f-a54b-95d18c1268ba
```
[pod/environmentd-0/environmentd] thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-005dd7fc9ed2e5aac-1/materialize/tests/src/storage-controller/src/lib.rs:1492:17: Unknown collection identifier u1324
[pod/environmentd-0/environmentd] stack backtrace:
[pod/environmentd-0/environmentd]    0: rust_begin_unwind
[pod/environmentd-0/environmentd]    1: core::panicking::panic_fmt
[pod/environmentd-0/environmentd]    2: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::update_read_capabilities
[pod/environmentd-0/environmentd]    3: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::update_replica_write_frontiers
[pod/environmentd-0/environmentd]    4: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::add_replica
[pod/environmentd-0/environmentd]    5: <mz_compute_client::controller::ActiveComputeController<mz_repr::timestamp::Timestamp>>::add_replica_to_instance
[pod/environmentd-0/environmentd]    6: <mz_controller::Controller>::create_replicas::{closure#0}
[pod/environmentd-0/environmentd]    7: <mz_adapter::coord::Coordinator>::create_cluster_replicas::{closure#0}
[pod/environmentd-0/environmentd]    8: <mz_adapter::coord::Coordinator>::sequence_create_cluster_replica::{closure#0}::{closure#0}
[pod/environmentd-0/environmentd]    9: <mz_adapter::coord::Coordinator>::sequence_create_cluster_replica::{closure#0}
[pod/environmentd-0/environmentd]   10: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
[pod/environmentd-0/environmentd]   11: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}> as core::future::future::Future>::poll
[pod/environmentd-0/environmentd]   12: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
[pod/environmentd-0/environmentd]   13: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
[pod/environmentd-0/environmentd]   14: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
[pod/environmentd-0/environmentd]   15: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_command::{closure#0}> as core::future::future::Future>::poll
[pod/environmentd-0/environmentd]   16: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
[pod/environmentd-0/environmentd]   17: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
[pod/environmentd-0/environmentd]   18: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
[pod/environmentd-0/environmentd]   19: <mz_adapter::coord::Coordinator>::serve::{closure#0}
[pod/environmentd-0/environmentd]   20: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()> + core::marker::Send>>> as core::future::future::Future>::poll
[pod/environmentd-0/environmentd]   21: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
[pod/environmentd-0/environmentd] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This identifier has been dropped:
```
default/environmentd-0[environmentd]: 2024-02-17T13:57:16.656116Z  INFO message_command:coord::handle_execute{session="8c0cc9c1-07ff-4b46-a53a-87356d9bbd84"}:coord::handle_execute_inner{stmt="DROP TABLE t CASCADE"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop table materialize.public.t (u1324)
```
Maybe this is a similar issue to https://github.com/MaterializeInc/materialize/issues/23037 ? But here t is just a table.

ci-regexp: Unknown collection identifier

**Comment by def-** [comment]
The oldest failure of this I could find was https://buildkite.com/materialize/nightlies/builds/6480 These changes look like they could be responsible: https://github.com/MaterializeInc/materialize/compare/b73cf12afa...fe1b02fbc9

@ggevay https://github.com/MaterializeInc/materialize/pull/25184 manipulated the way read holds are handled, could it be responsible? Especially the code in [[src/adapter/src/coord/read_policy.rs](https://github.com/MaterializeInc/materialize/compare/b73cf12afa...fe1b02fbc9#diff-045a139b6731da5a66e4cd0d02d1d20d1333fd85da8549385a0f681a51f8463e)](https://github.com/MaterializeInc/materialize/pull/25184/files#diff-045a139b6731da5a66e4cd0d02d1d20d1333fd85da8549385a0f681a51f8463e) This is part of v0.88

**Comment by teskje** [comment]
I think this is what's going on:

* We create a table `t` (storage collection) and an index `idx` that reads from `t` (compute collection).
* The compute controller creates read holds on `t` with the storage controller.
* We `DROP TABLE t CASCADE`. Adapter drops both `t` and `idx` with the respective controllers.
* The compute controller drops its read holds on `t` as part of dropping `idx`. However, it does not yet drop the `CollectionState` associated with `idx` because that is cleaned up asynchronously.
* The storage controller observes that all read holds on `t` are dropped and drops `t`.
* We create a new replica in the compute cluster.
* Replica initialization in the compute controller loops through all `CollectionState`s and initializes per-replica write frontiers. This includes installing per-replica read holds on dataflow dependencies.
* Because the `CollectionState` for `idx` has not been cleaned up yet, we also install a per-replica read hold for `t` (the dependency of `idx`. The storage controller doesn't know `t` anymore and returns the "Unknown collection identifier" error.

The bug is that the compute controller tries to install a read hold for a storage collection that has already been dropped. The read holds it tries to install is for the empty frontier (because that's the read frontier of `idx` after it has been dropped), so it actually doesn't try to install a read hold at all. The fix is to ensure that we don't call the storage controller with empty read holds.

**Comment by teskje** [comment]
The panic is made more likely by https://github.com/MaterializeInc/materialize/pull/25046 which made the compute controller clean up dropped collections less frequently.

**Comment by teskje** [comment]
Working on the repro I realized that this panic couldn't occur prior to shard finalization being a thing for table shards. This is why we haven't seen it before https://github.com/MaterializeInc/materialize/pull/25173 got merged.
