### ISSUE TITLE
Source orthogonality

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2537]
Part of technical debt cleanup from #1575. See also the discussion on #2496. 

The Debezium envelope is purely associated with Kafka with Avro encoding. Upsert is not necessarily Kafka or Avro specific. Also technically only Debezium uses "envelope" as official terminology.

Once nested structures are fully supported,  we'd probably be able to eliminate the ENVELOPE syntax and write things like `SELECT DEBEZIUM(rowdata, schema_info) from source`. On the backend, it might optimize to what we already have, but it would various weird structs and special cases we have in create source parsing.

cc: @benesch @umanwizard feel free to add comments or correct me if I've paraphrased something wrong.

**Comment by umanwizard** [comment]
Thank you for writing this up!

**Comment by cuongdo** [comment]
I've renamed this issue, in an attempt to match our current terminology. Currently, one cannot select an arbitrary combination of format, envelope, and source connector. Several features, such as upserts, are currently limited to Avro / Kafka. To paraphrase @umanwizard, the goal is to make connectors, formats, and envelopes syntactic sugar for SQL operations.

Here are some community-reported examples:
* [Using upsert with JSON data read in from a file](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1594949333074500)
* [Being able to update/delete records through file sources](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1593719661335300)

**Comment by umanwizard** [comment]
Rough plan for non-OCF sources:

* Introduce `avro_decode` function which, given an Avro record schema, goes from bytes to a SQL record, (and similar for Protobuf)
* Introduce `repeat` table-valued function such that `repeat(n)` outputs N zero-column rows
* Avro format with `ENVELOPE NONE` is now something like `SELECT r.rec.a, r.rec.b, r.rec.b, ... FROM (SELECT avro_decode(src.bytes) rec FROM src) r` , where `src` is a raw bytes source
* Avro format with `ENVELOPE DEBEZIUM` selects the `before` and `after` records into a "value" field, maps a `diff` column with `+1` for `after` and `-1` for `before`, then does e.g. `SELECT before_and_after.value.a, before_and_after.value.b, before_and_after.value.c FROM before_and_after, repeat(before_and_after.diff)`
* `ENVELOPE UPSERT` ... (TBD, this should also be expressible in SQL but I haven't yet thought about it enough)

For OCF sources:
There is no way to cleanly separate into two stages where we read bytes and then decode into Avro, since the file is self-delimited, i.e., you need to decode avro to understand where one record ends and the next begins.
But, we should be able to separate out everything other than format: we can make OCF sources emit `Row`s with one record value, and then do the logic described above.

**Comment by cuongdo** [comment]
This is postponed, to allow progress on CDC v2

**Comment by awang** [comment]
user request: https://github.com/MaterializeInc/materialize/issues/5176

**Comment by awang** [comment]
closing it, we'd like to make separate issues for followon work
