### ISSUE TITLE
mysql: query on table with time-typed column gets stuck

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25410]
### What version of Materialize are you using?

028031109d

### What is the issue?

```
$ mysql-execute name=mysql
CREATE TABLE t1 (f1 TIME(6));
INSERT INTO t1 VALUES (TIME '838:59:59')

> CREATE SOURCE mz_source
  FROM MYSQL CONNECTION mysql_conn
  FOR ALL TABLES;

> SELECT COUNT(*) > 0 FROM t1;
true
```

The SELECT query gets stuck.

**Comment by rjobanp** [comment]
I think this is a bug due to the fact that mysql's time type supports values from '-838:59:59' and '838:59:59' but postgres/mz only support 00:00:00 to 24:00:00.

I think encountering an out-of-bounds value like this should put the sub-source into an error state. And we should eventually add support to allow specifying `time` columns as `TEXT COLUMNS` as a workaround for ingesting tables with values that don't fit. Will work on this behavior soon
