### ISSUE TITLE
steady-state-source-statistics.td: Wrong result from mz_internal.mz_source_statistics_raw

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25458]
### What version of Materialize are you using?

8bfbb678fcf0

### What is the issue?

This test was just added in https://github.com/MaterializeInc/materialize/pull/25402
Seen in https://buildkite.com/materialize/tests/builds/76415#018dcfbb-bffa-475b-a691-0cb66e4ae0d6
```
> SELECT
  s.name,
  SUM(u.offset_known) > 9,
  SUM(u.offset_known) = SUM(u.offset_committed)
FROM mz_sources s
JOIN mz_internal.mz_source_statistics_raw u ON s.id = u.id
WHERE s.name IN ('upsert')
GROUP BY s.name
ORDER BY s.name
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 22s
^^^ +++
steady-state-source-statistics.td:113:1: error: non-matching rows: expected:
[["upsert", "true", "true"]]
got:
[["upsert", "false", "true"]]
Poor diff:
+ upsert false true
- upsert true true

     |
  49 |     URL '${testdrive ... [rest of line truncated for security]
 112 | 
 113 | > SELECT
     | ^
```
Not sure if it's just a test problem or an actual product issue.

**Comment by guswynn** [comment]
I believe we have a 2min timeout on sql queries in this file, but these statistics are updated only after the kafka source re-fetching metadata every minute, and then we collect statistics every minute. I think the fix is just to make the timeout 3min, like I did with another file in https://github.com/MaterializeInc/materialize/pull/25436. Ill fix this forward in there!

@def- let me know if after that merges, you see this again. I also want to make the kafka metadata fetch interval configurable, so we can reduce all the timeouts here

**Comment by def-** [comment]
3 minutes is a pretty long time. Could we make the statistics faster for tests?

**Comment by guswynn** [comment]
@def- Yes, I will followup and make all the various parameters LD-able so I can speed it all up!

I want that feature to go out in today's release, so ill merge as is, and then followup this afternoon with speeding it up!
