### ISSUE TITLE
What's the right way to separate data that can never be retracted or updated?

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2568]
Consider Kafka metadata, concretely, the offset. This data can never be retracted or updated. We might keep it around, for instance to track some externally relevant notion of "progress" (e.g. what is the max Kafka offset that we have ever seen?)

The problem comes from the fact that this nonretractable metadata is tied up with retractable data. Consider a sequence of messages:

key: foo, value: 5, offset: 1
key: bar, value: 2, offset: 2
Key: foo, value: 3, offset: 3

Aggregations over keys and values need to be mindful of the possibility of retractions. But aggregations over offset does not: we "know" that offsets only ever go up, and this information is useful to propagate through dataflows.

**Comment by rjnn** [comment]
One possible answer here is "don't do that".

Another possible answer might be... construct separate parallel dataflows to carry the metadata around, and that dataflow can drop capabilities?

**Comment by frankmcsherry** [comment]
I'm coming around to the theory that each source should initially present as an append-only stream, and that we layer interpretation on top of this to turn a stream of e.g. CDC statements into actual positive and negative records. Users are allowed to project out the offset or line number, which would allow otherwise similar records to cancel.

I think this all becomes a lot easier with #3691. Maybe a `delay` flavored variant too.

**Comment by rjnn** [comment]
The answer is to ingest it as an append-only source, and then do whatever you want after the fact and create downstream collections.
