### ISSUE TITLE
Can't SELECT a column named date

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2577]
```
materialize=> select * from timestamp_source;
    date    |             ts             |           ts_tz            | mz_obj_no
------------+----------------------------+----------------------------+-----------
 2000-02-01 | 2000-02-01 10:10:10.000297 | 2000-02-01 08:10:10.000232 |         1
 2000-01-01 | 2000-01-01 10:10:10.00089  | 2000-01-01 08:10:10.000857 |         2
(2 rows)
materialize=> select date from timestamp_source;
ERROR:  Parse error:
select date from timestamp_source;
            ^^^^
Expected literal string, found: from
materialize=>
```

but postgres can do it:

```
benesch=# create table t (date date);
CREATE TABLE
benesch=# select date from t;
 date 
------
(0 rows)
```

Note that `SELECT "date"...` and `SELECT fully.qualified.name.date ... ` are workarounds

**Comment by rjnn** [comment]
I'm not sure this is a bug. Using double quotes is a standard sql-ism. I imagine there are good pgcompat reasons to match the postgres behavior, but I advocate to document this as a known limitation and otherwise wait until there are compelling ORM/automated-query-generation reasons to fix this.

**Comment by dantodor** [comment]
I have somehow a similar problem, I wish to understand what I'm doing wrong, I'm not using any SQL reserved words.

Schema:
`materialize=> show columns from my_view;
 connectionId       | YES      | text
 chatbotId          | YES      | int4
 campaignId         | YES      | int4`

Then :

`materialize=> select connectionid from my_view;
ERROR:  column "connectionid" does not exist
materialize=> select connectionId from my_view;
ERROR:  column "connectionid" does not exist
materialize=> select CONNECTIONID from my_view;
ERROR:  column "connectionid" does not exist`

But this works:
`materialize=> select "connectionId" from my_view;`

Is it because of the camelCase ? 
I'm using Materialize reading protobufs from Kafka.  Connecting via standard psql client. 
Haven't tried yet programatically reading columns, but will try soon.

**Comment by ruchirK** [comment]
Let me see if I can reproduce this on my laptop

**Comment by ruchirK** [comment]
Ok I'm able to reproduce this on our end

```
materialize=> create view test ("testId") AS VALUES (1), (2), (3);
CREATE VIEW
materialize=> show columns in test;
 Field  | Nullable | Type
--------+----------+------
 testId | NO       | int4
(1 row)
materialize=> select * from test;
 testId
--------
      1
      2
      3
(3 rows)
```

and then if you query it for testId without quotes it fails because everything is mapped to testid, e.g.

```
materialize=> select testId from test;
ERROR:  column "testid" does not exist
```

However I think this is expected behavior because this is also what postgres does in this situation -- it treats unquoted strings as all lowercase, as you can see below:

```
Test=# create table test ("testId") as values (1), (2), (3);
SELECT 3
Test=# select * from test;
 testId
--------
      1
      2
      3
(3 rows)

Test=# select testId from test;
ERROR:  column "testid" does not exist
LINE 1: select testId from test;
               ^
HINT:  Perhaps you meant to reference the column "test.testId".
```

**Comment by ruchirK** [comment]
I do think that postgres gives a pretty nice hint here and we can likely do the same
