### ISSUE TITLE
persist: make `persist_source` go faster

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25901]
## Summary

Improve the efficiency of `persist_source` until &lt;target TBD>.

Candidate target: `persist_source` can fetch and decode data fast enough that it saturates the network interface.

## Details

We've occasionally fielded reports of ad hoc queries being slow that were traced back to `persist_source` not fetching and decoding data from S3 as efficiently as possible. Here's a recent such Slack conversation: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1709922014747189?thread_ts=1709914504.815139&cid=CU7ELJ6E9

## See also 

* https://github.com/MaterializeInc/materialize/issues/24830
  * Hopefully this avoids some expensive Protobuf decoding.
* https://github.com/MaterializeInc/materialize/issues/20618
  * An alternative spot fix for a certain type of slow ad hoc query.  

cc @danhhz @frankmcsherry

**Comment by danhhz** [comment]
Looks like #20618 will be the initial bit of work for this. It's cheating a bit to call that item "make persist_source go faster" but the bank-for-your-buck is too hard to pass up.

**Comment by danhhz** [comment]
- The second bit of work is https://github.com/MaterializeInc/materialize/pull/26887. It's also a bit creative to include this in the "make persist_source go fast" umbrella, except that previously any work we did to speed up s3 fetching would just make cc replicas OOD faster. Now we slow down fetching when necessary, but only just enough to avoid using too much disk. As a result, we can improve fetching and/or decoding in any order without worry

I've wrapped up a bit of initial investigation of the "speed of light": how fast we could possibly make persist_source go. Breaking it up into 3 parts: bytes from s3, bytes to columnar, columnar to row.

Bytes from S3:
- I wrote a small benchmark program to download a ~2 GiB shard X times
- Running on staging instance with "12 Gbps" (~1500 MiB/s) available (shared between all pods on the node)
- Getting 1050-1300 MiB/s
- The long tail will be hard, let's call that close enough to saturating the network
- This takes ~3.6 cores (!), much of which is in copying kernel buffers
- io_uring is one way to avoid these buffer copies
  - I spent several days trying to connect our s3 library to io_uring and was ultimately unsuccessful
  - It's obviously possible, but there's a good bit of tension between hyper/aws requirements that various things be `Send` (b/c tokio) and the io_uring runtimes wanting to be thread-per-core/`!Send`
  - The available io_uring rust libraries seem fairly immature, and it would probably be a good bit of time investment to get something we'd be comfortable running in prod
- It's yet unclear to me if there are easier tuning parameters that we could use here for some wins
- We also spent a smaller, but significant amount of time in ssl. Unnerving, but it's possible that we [don't actually need https for s3](https://www.durner.dev/app/media/papers/anyblob-vldb23.pdf)

Bytes to Columnar:
- This is parsing the encoded parquet bytes into arrow arrays
- Can also keep up with the above fetching given sufficient cpu https://pprof.me/22df7d6510009f92c6c4a60f29a73711
- Currently uses 0.75-1.15 cores (depending on how you count) for the above
- Ideally this should take basically no cpu, but we're limited by the arrow<->parquet mappings available
- For things like ints, it's indeed basically just a transmute
- However, all of the parquet bytes/strings encodings require per-value work to turn into arrow arrays(!)
- It's possible that the upcoming "view" string/bytes arrow array stuff will help here
- Another option is to use a format other than parquet. We don't actually get much from it in persist's use. I've heard that compute has been considering the introduction of a columnar Row representation and it might make sense for us to roll a direct serialization format for that.
- One unavoidable tension here is between network bandwidth and cpu. If you're maxing out the network interface, one way to get goodput up is to compress it. We're pretty far from being mature enough for me to feel like we have good data on where in the tradeoff space Mz will end up in
- This result doesn't hold up when running things inside shard_source/timely. All the fetching work happens in tokio tasks, so this is a bit surprising. I've investigated it and I believe the issue is imbalance in decode between timely workers. shard_source_descs currently distributes them randomly, but it could probably fix this issue by being smarter for the "snapshot" part of the persist_source

Columnar to Row:
- This is going to completely change with #24830
- So I haven't done much with it yet
- But Parker has been given free rein to hyper optimize how we map Datums to arrow columns (e.g. https://github.com/MaterializeInc/materialize/pull/27336)

**Comment by benesch** [comment]
This is a wonderful summary, @danhhz — thank you so much for writing it up!

Bummer that io_uring support in Rust is so immature. One take here, though, is that we won't need to that level of optimization in the short/medium term. I'm somewhat "hopeful" that there will be enough bottlenecks in compute once decoding is sped up that the S3 fetch speed won't be the bottleneck for a while.

**Comment by danhhz** [comment]
Oh yeah, for sure. Speeding up Columnar to Row is definitely the lowest hanging fruit here

**Comment by danhhz** [comment]
Okay after Parker's schemafied blob work, it seems like we're in decently good shape here. Gonna break this up into separate issues to track the remaining work:

- #24830
- #28405
- #28500
- Some minor work to better balance fetch/decode between workers on the shard_source snapshot. It's currently distributed randomly, but we have sizes available so we could be smarter (for at least the snapshot, seems fine to continue to distribute the "listen" part with the current random logic.
- Some minor work to avoid cpu in Clone and Drop in SegmentedBytes, see for example https://pprof.me/541dad8f66bfaa861ffcd457ccdeaf02/
