### ISSUE TITLE
persist-txn: logical_upper races ahead of the timestamp oracle

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#25962]
### What version of Materialize are you using?

v0.91.0-dev

### What is the issue?

Whenever we forget a shard it appears as though we bump the logical upper of the txn's shard. If you forget a lot of shards all at once then it seems possible that the txn shard's logical upper can race ahead of the timestamp oracle. This causes [environmentd to halt](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/coord/appends.rs#L375-L381) when running a group commit, because the timestmap we commit at is no longer valid.

Related to https://github.com/MaterializeInc/materialize/issues/24963

**Comment by danhhz** [comment]
It's pretty fundamental that removing a shard from persist-txn consumes a timestamp. I think, for now, the fix has to be that we get that timestamp from the oracle, so they stay in sync. Looks like we have a TODO already :)

https://github.com/MaterializeInc/materialize/blob/0932d88d7632a8851a73318039c958d19d80fb6b/src/storage-controller/src/persist_handles.rs#L544-L545

**Comment by danhhz** [comment]
Yeah, ideally. Though looks like register [panics instead of halts](https://github.com/MaterializeInc/materialize/blob/0bf265e4cf9717f8ceedb2952f88404c1314c773/src/storage-controller/src/persist_handles.rs#L526-L533), unsure if that's wrong or if something at a higher level has already ensured the ordering.

IIRC, when I wired this up, I didn't do forget because it happens in the background and so the timestamp usage was racy, so might be a tricky change

**Comment by danhhz** [comment]
@ParkMyCar are you intending to work on this? If not, I might see if @jkosh44 could pick it up for me. No pressure! Just wanting to make sure this doesn't get dropped and that noone's doing duplicate work

**Comment by ParkMyCar** [comment]
I could if needed, but was hoping to focus on columnar stuff. Just chatted with @jkosh44 and he seems interested to pick it up, he and I can sync today on what I know so far!

**Comment by jkosh44** [comment]
So I think something like the following is happening:

The current timestamp oracle read timestamp is `t_o`, and the current txn shard upper is `t_t`, s.t. `t_o > t_t`.

1. User drops `n` tables (s.t. `n > t_o - t_t + 1`) in a single command (ex: `DROP SCHEMA s CASCADE`).
2. `TxnsTableWorker::drop_handle` is called `n` times, which bumps the txn shard upper to `t_t + n`.
3. We write the builtin table updates to `mz_tables` which bumps the timestamp oracle read timestamp to `t_o + 1` (sometimes it's increased by more than 1, but let's ignore that for now).
4. A group commit is initiated, which tries to perform an append at the timestamp oracle time `t_o + 1`. This is less than the txn shard upper (`t_t + n`) and the append fails with an invalid upper error.

----

I've been trying for a couple of hours to repro this with the following `mzcompose` test:

```Python
from materialize.mzcompose.composition import Composition
from materialize.mzcompose.services.materialized import Materialized

SERVICES = [Materialized()]


def workflow_default(c: Composition) -> None:
    c.up("materialized")
    c.sql(
        "ALTER SYSTEM SET max_tables = 10000000;",
        port=6877,
        user="mz_system",
    )
    c.sql(
        "ALTER SYSTEM SET max_objects_per_schema = 10000000;",
        port=6877,
        user="mz_system",
    )
    c.sql("CREATE SCHEMA s1;")
    c.sql("CREATE SCHEMA s2;")
    c.sql("CREATE TABLE s1.t1 (a INT);")
    ddl = ""
    for i in range(3000):
        ddl += f"CREATE TABLE s2.t{i} (a INT);\n"
    c.sql(ddl)
    c.sql("DROP SCHEMA s2 CASCADE;")
    c.sql("INSERT INTO s1.t1 VALUES (1);")

```

The drop has been executing for a LONG time, it is making progress though. At first a bunch of logs of the following format were being logged:
```
environmentd: 2024-03-14T14:50:48.587683Z  INFO coord::handle_message{kind="command-execute"}:message_command:coord::handle_execute{session="1162e85a-96ea-4aa2-802d-06c4325b4550"}:coord::handle_execute_inner{stmt="DROP SCHEMA s2 CASCADE"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_conn:coord::catalog_transact_inner:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop table materialize.s2.t2945 (u2947)
```
then
```
environmentd: 2024-03-14T14:51:14.818213Z  INFO PersistTableWriteWorkerInner::send: mz_storage_controller::persist_handles: drop tables id=User(1673)
```
then
```
environmentd: 2024-03-14T14:51:14.820388Z  INFO coord::handle_message{kind="controller_ready"}: mz_storage_controller: triggering shard finalization due to dropped storage object
```

I'll edit this message if the test ever completes.

----

Open questions (mostly for @danhhz):

- When I was reading the code it looked like `TxnsTableWorker::drop_handle` was called asynchronously and did not block the actual `DROP` command. However from the logs it looks like `DROP` is being blocked until `drop_handle` has been called for all tables. Perhaps, the `DROP` actually did finish but the all of `PersistTableWriteCmd::DropHandle` messages were already queued, so the next command, which queues a `PersistTableWriteCmd::Append` message, has to wait for the drops to finish. So is `TxnsTableWorker::drop_handle` supposed to be done synchronously or asynchronously?

- (This is somewhat related to the above question). The workflow for dropping a table as I understand it is as follows:
 
1. Update read policy s.t. `since` is the empty antichain.
2. Trigger compaction on the table asynchronously.
3. When the compaction work is started, the compaction calls `TxnsHandle::forget`.

Is there a fundamental reason that we can't structure it like the following?:

  1.  Update read policy s.t. `since` is the empty antichain.
  2. Call `TxnsHandle::forget`.
  3. Trigger compaction work on the table asynchronously.
My guess is this won't work because compaction won't be able to compact a table that's been forgotten, but I thought I'd check.

----

Fixes:

- If we can batch the forgets all into a single timestamp that would potentially improve the performance but also remove the issue in practice. It would reduce `n` from the repro above to `1`, which would prevent the txn shard upper from advancing past the timestamp oracle. This relies on the builtin table updates consuming a timestamp oracle timestamp.
- Ideally if possible we would provide a timestamp from the timestamp oracle to `forget`.

**Comment by danhhz** [comment]
I'm not an expert on the drop workflow (though @ParkMyCar was just in there recently!), but I do know there is one bit that needs to be done synchronously:
- To "finalize" (delete) a persist shard, we advance the upper and the since of the shard to the empty antichain. Advancing the upper requires a direct write to the shard.
- If a shard is managed by persist-txn, we are not allowed to write directly to it until the `forget` has finished
