### ISSUE TITLE
Disk usage missing for cc clusters

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#26115]
### What version of Materialize are you using?

v0.91.0 (fe984643d)

### What is the issue?

In my staging environment, I have an unmanaged 25cc cluster with 1 replica, but it reports no disk usage.

```sql
SELECT cr.cluster_id, cr.id AS replica_id, cr.size, c.disk, cru.disk_percent
FROM
    mz_clusters AS c
        JOIN mz_cluster_replicas AS cr ON c.id = cr.cluster_id
        JOIN
            mz_internal.mz_cluster_replica_utilization AS cru
            ON cru.replica_id = cr.id
WHERE c.id = 'u74';

 cluster_id | replica_id | size | disk | disk_percent
------------+------------+------+------+--------------
 u74        | u129       | 25cc |      |
(1 row)
```

**Comment by RobinClowers** [comment]
[Slack thread](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1710784481029189?thread_ts=1710783214.164369&cid=C02PPB50ZHS)

**Comment by guswynn** [comment]
Perhaps this is because cc sizes use arm? In the past, the disk capacity as reported by the cadvisor was always < the disk limit. I suspect a cloud team member will have to weigh in on if amazon does something different with disks on arm instances.

In the short term, we can clamp the `disk capacity` and `disk usage` to the configured limit; the consequences of this is you actually have have a a few more megs of space when reporting 100% usage in the usage view.

**Comment by guswynn** [comment]
This is the fix: https://github.com/MaterializeInc/materialize/pull/26123. I can try it in staging on a cc size tomorrow. Its become increasingly clear to me that there is no way to work around these edge cases, we just have to clamp the usage to the configured limit; the differences in instances, amazon's inconsistency, and the timing issues with the custom metrics server we get the limit our options here

**Comment by chaas** [comment]
Thanks for the quick turnaround and coming up with something!
