### ISSUE TITLE
Expose `millis_behind_latest` information for Kinesis sources

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2616]
Each time we get records from a Kinesis stream, we also get a [`millis_behind_latest` field](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html#Streams-GetRecords-response-MillisBehindLatest) in the result. `millis_behind_latest` is the number of milliseconds the Materialize consumer is behind the tip of the Kinesis stream. 

I'm thinking it would be useful to expose that information to users, but not sure where it should live. @frankmcsherry, would this be something we could log? I'm thinking it will be most useful in: 1) debugging Kinesis sources and, 2) measuring our performance.

**Comment by frankmcsherry** [comment]
Some quick thoughts!

From the description, this sounds like information that is likely to get stale very quickly. So, we could record it but .. for example if we don't do another read for a while it might stay as "just a few ms behind latest" which is no longer morally correct the longer we wait.

It may be that we can pivot this information into something that is a bit more like the Kafka offset information, which remains "correct" even as time advances. There, we might record the most recently read offset, and could at the same time (if we have that information) report the largest offset we are currently aware of. This is similar to "offset behind latest" but written in a form that will remain correct even as time passes.

I'm not really sure from the AWS docs what the sane transformation is (or what the field actually means). It sounds like messages have a "ms" field on them, and this is a way to report something about the largest ms the system still holds on to, but .. the ms field is not actually something that can be relied on I thought? 

Anyhow, if at all possible, we should figure out what sorts of "absolute" statements about progress we can make / record, so that they remain true / clear even as time advances.

**Comment by JLDLaughlin** [comment]
This is closed as of #2688 -- pushing this information to Prometheus feels sufficient
