### ISSUE TITLE
Expose the session variable defaults for each role via a system catalog table

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#26228]
### Feature request

It will be helpful to have a way of getting the session variable defaults for a specific role.

At the moment you can set role-specific variables eg.:

```sql
ALTER ROLE some_role SET transaction_isolation = 'strict serializable';
```

But the only way of retrieving the current value is to connect with that role and do a `SHOW var_name`.

**Comment by chaas** [comment]
Proposal: add a new system catalog table `mz_internal.mz_role_variable_defaults` that contains one row for each (role, session variable) pair that has a default explicitly set.
Columns: `role_id`, `variable_name`, `value`
If we want to be verbose we could name the table `mz_internal.mz_role_session_variable_defaults` and the column `session_variable_name` - to discuss with the sql council.

Alternatively, Postgres writes all the session variable defaults as a json string in a single column in the `pg_roles` table. We think the separate catalog table is more ergonomic. See example:
```
cara=# alter role cara set search_path to caras_schema;
ALTER ROLE
cara=# SELECT rolname, rolconfig FROM pg_roles;
          rolname          |         rolconfig          
---------------------------+----------------------------
 cara                      | {search_path=caras_schema}
 pg_database_owner         | 
 pg_read_all_data          | 
 pg_write_all_data         | 
 pg_monitor                | 
 pg_read_all_settings      | 
 pg_read_all_stats         | 
 pg_stat_scan_tables       | 
 pg_read_server_files      | 
 pg_write_server_files     | 
 pg_execute_server_program | 
 pg_signal_backend         | 
 repl                      | 
(13 rows)

cara=# alter role cara set search_path to default;
ALTER ROLE
cara=# SELECT rolname, rolconfig FROM pg_roles;
          rolname          | rolconfig 
---------------------------+-----------
 cara                      | 
 pg_database_owner         | 
 pg_read_all_data          | 
 pg_write_all_data         | 
 pg_monitor                | 
 pg_read_all_settings      | 
 pg_read_all_stats         | 
 pg_stat_scan_tables       | 
 pg_read_server_files      | 
 pg_write_server_files     | 
 pg_execute_server_program | 
 pg_signal_backend         | 
 repl                      | 
(13 rows)

```

**Comment by benesch** [comment]
> Alternatively, Postgres writes all the session variable defaults as a json string in a single column in the pg_roles table

I think it's actually a `text[]` where each element is formatted as `key=value`, but same idea!

> We think the separate catalog table is more ergonomic.

Agreed!

> Proposal: add a new system catalog table `mz_internal.mz_role_variable_defaults` ...  If we want to be verbose we could name the table `mz_internal.mz_role_session_variable_defaults` and the column `session_variable_name` - to discuss with the sql council.

Even though "variables" or "session variables" is colloquial, the official term (taken from PostgreSQL) is "run-time configuration parameter." And we've tried to be consistent about using that terminology in our documentation and public interfaces (e.g., https://materialize.com/docs/integrations/sql-clients/#runtime-connection-parameters). For short, we'll say "configuration parameters" or "parameters", but we try to avoid "variables". (Many apologies for the naming of `vars.rs`.)

All that to say: I think the right term here is probably "role parameters"! There are "system parameters", "database parameters" (not supported in Materialize), "role parameters", and "session parameters." So that would point towards a table named `mz_role_parameters`.

**Comment by chaas** [comment]
Should we update our docs on session variables (https://materialize.com/docs/sql/show/#session-variables, https://materialize.com/docs/sql/set/) to use the term "parameter" instead of "variable" everywhere too? "Parameters" doesn't show up anywhere on that page. I had actually only seen us reference them as variables everywhere in the docs.

**Comment by benesch** [comment]
Oh, geez, the docs really went down the "variable" direction in the past year since I'd looked closely. I put up https://github.com/MaterializeInc/materialize/pull/26463 to fix!

**Comment by chaas** [comment]
Also for the `parameter_value` column, the value can be either a single string or a list of strings (for cluster/search_path). Not sure there's any precedent on how to encode something that can either be one value or a list of values.
In the case that it's a list, is just converting the var list to a comma separated string acceptable?
Or is an array column type preferable, and it just has one value in most cases?
Postgres just encodes the whole `key=value` pair as text, so thus converts the value to a comma separated string if we want to use that as precedent.

**Comment by benesch** [comment]
> Not sure there's any precedent on how to encode something that can either be one value or a list of values.

Indeed, there is! https://github.com/MaterializeInc/materialize/pull/17658/commits/12f62ae04081ed130aa9e7d38c46eee36523bc3c

> In the case that it's a list, is just converting the var list to a comma separated string acceptable?

Basically yes, but don't roll the logic yourself! There's existing code for safely taking any variable to a string, including for ident lists that need to handle quoting.

> Or is an array column type preferable, and it just has one value in most cases?

String is preferable, I think. PostgreSQL accepts options as `key: string, value: string` in many many places, and so there is a requirement that all configuration parameters values are convertible to/from strings.
