### ISSUE TITLE
Postgres inconsistency: translate inconsistency with special characters

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26553]
### What version of Materialize are you using?

main

### What is the issue?

Seen in https://buildkite.com/materialize/nightly/builds/7310#_
```sql
SELECT '|' || translate('a', convert_from('\x68656c6c6f20f09f918b'::BYTEA, 'utf8') || 'abc', E' mAA m\n\t ') || '|';
```
In Postgres:
```
 ?column?
-----------
 |       |
(1 row)
```
In Materialize:
```
 ?column?
----------
 ||
(1 row)
```

CC @nrainer-materialize I'll try to add an ignore for this.

**Comment by nrainer-materialize** [comment]
This can be simplified to:

```
SELECT '|' || translate('a', '👋a', E'x\t') || '|';
```

Could it be that `👋` is counted as more than one character so that the `a` character of the second parameter is not mapped to `\t` in the third parameter?

**Comment by nrainer-materialize** [comment]
Though, there is no mismatch for

```
SELECT '|' || translate('a', 'ba', E'👋\t') || '|';
```

**Comment by chaas** [comment]
Looked at this briefly, and the Rust code incorrectly uses the `find()` method to find the character's position in the string, since that function returns the byte index of the matching character, not the character index.
We'd want to use `position()` https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position or similar instead.
