### ISSUE TITLE
Implement TAIL AS OF

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2660]
When tailing a query, folks often want a snapshot of the data, along with a tail that lines up _exactly_ starting from the timestamp of the data.

# Solution A

This could be achieved by running two commands: `SELECT *, mz_logical_timestamp() FROM <viewname>`, immediately followed by `TAIL (AS OF t), with `t` being the returned logical timestamp

You'll note that I've added `AS OF t` to the `TAIL` - this reflects that the timestamp picked to execute the `SELECT * ` _must line up exactly_ with the starting point of the subsequent `TAIL`. We do not currently have "AS OF t" modifiers for `TAIL`, although we could.

## Solution B

One remedy here is to combine the two commands into a single command: One candidate way to do this is to add the syntax:

`TAIL WITH SNAPSHOT <viewname>`.

This returns the `SELECT *` results first, followed by the streaming diffs.
This feels like syntactic sugar that's needlessly complicated, but I'm not sure, I wanted to write it out here as that's how I originally thought about it.

**Comment by frankmcsherry** [comment]
I prefer the latter myself. At least, my intuition is that folks are more likely to want to use the latter, and making that as easy as possible seems good.

I'm super hesitant to overload `AS OF`, which elsewhere means "with times advanced to" rather than "ignoring things before". Using that language, `TAIL AS OF t` would mean "accumulate things up to `t` and show me that plus the diffs from then on" which I think makes sense.

**Comment by rjnn** [comment]
I think that makes a lot of sense! I would enthusiastically support `TAIL AS OF t` to accumulate everything to the point `t` and emit them, and then show streaming diffs from thereon.

`TAIL AS OF now()` is simple and elegant!

**Comment by justinj** [comment]
I missed this issue before, going to close under the assumption that this was addressed by #2762.
