### ISSUE TITLE
Web interface for tracking Test Failures

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26727]
### Feature request

Currently when a test fails it's difficult to figure out if this is a known issue, since when it's been occurring, how frequently it happens, etc. Some of our buildkite insights tooling is already helpful here, but I think we should have a dashboard where all of that is tracked and easily visible for QA and devs. Buildkite Analytics might seem similar, but would fall short of many of our requirements.

I'm imagining this a bit like the Sentry interface, where each test failure is logged, they are connected based on error message, the github issue is linked.

**Comment by def-** [comment]
@nrainer-materialize is already starting on uploading ci annotations to the database.

**Comment by nrainer-materialize** [comment]
I think it would be great if we could split this down into smaller tasks.

**Comment by def-** [comment]
At the moment this is pretty exploratory for me, so I'm not sure yet what will work or not and what smaller tasks to generate.

**Comment by nrainer-materialize** [comment]
Thanks for the additional details.
Do you plan to make the first version read-only or will the webserver of step two also conduct writes?

**Comment by def-** [comment]
So far read-only. I'm not sure if we want to move away from having ci-regexp in github.

**Comment by nrainer-materialize** [comment]
Looks great! 😀 

Some feedback and feature requests on the first draft (https://materializeinc.slack.com/archives/C057X0NG91B/p1721085808864639):

### General
* icon: I suggest to use a different icon to not use the same as the CI trigger does. (Or maybe we should use another one for the CI trigger?)

### Test Failures View
* Can we use the LIKE operator to do filtering (at least) in the message field? According to the network traffic, filtering is done at server side. 
* Does the issue column contain a merge of columns `error_type` and `issue` from `build_annotation_error`? Not sure if this is a good idea.
* Can we add a link to the build (job)?
* Can we collapse the text content and limit the row height? (Ok, I just noticed I can toggle the density using the table menu in the upper right corner.)

### Issues View
* Can we link the issue?
* Can we present the date in a way so that it is easier to quickly spot how recent it is (e.g., by using "two days ago" or using some coloring)?
* Can we fetch the issue title from GitHub and display it?
* Should we add a column "occurrences in the last 7 (/30) days"?

### Other
* looks really nices
* behaves surprisingly fast
* unclear what I can do by selecting rows

**Comment by def-** [comment]
> icon: I suggest to use a different icon to not use the same as the CI trigger does. (Or maybe we should use another one for the CI trigger?)

Done

> Can we use the LIKE operator to do filtering (at least) in the message field? According to the network traffic, filtering is done at server side.

We use ILIKE, is that ok?

> Does the issue column contain a merge of columns error_type and issue from build_annotation_error? Not sure if this is a good idea.

Yes, space is restricted: `CASE WHEN error_type = 'KNOWN_ISSUE' THEN issue ELSE error_type END AS issue`

> Can we add a link to the build (job)?

Done

> Can we collapse the text content and limit the row height? (Ok, I just noticed I can toggle the density using the table menu in the upper right corner.)

I hope it's better now

> Can we link the issue?

Done

> Can we present the date in a way so that it is easier to quickly spot how recent it is (e.g., by using "two days ago" or using some coloring)?

I'm now using javascript's local datetime rendering

> Can we fetch the issue title from GitHub and display it?

This is dangerous, can run into github quota if done in client, can read secret issues if done in server!

> Should we add a column "occurrences in the last 7 (/30) days"?

I think the last occurrence is also important, the planned "Issue" view should help here too.

**Comment by nrainer-materialize** [comment]
> We use ILIKE, is that ok?

Yeah, even better.

Great! Thanks for addressing these suggestions! 👍
