### ISSUE TITLE
[Epic] Hydration and rehydration latency metrics per dataflow

### ISSUE THREAD

**Issue by bosconi** [MaterializeInc/materialize#26932]
## Product outcome

Metrics are published that allow internal dashboards to report per-dataflow hydration and rehydration latency, potentially along with normalized metrics such as rate (amount of data per unit time).

## Discovery

Per the MVP metrics section of the [Document and Measure Sources of Unavailability product spec](https://www.notion.so/materialize/Document-and-Measure-Sources-of-Unavailability-in-Materialize-761066423377480c89e8990104bfacc9?pvs=4), the proposed MVP metrics are:

* Hydration time per dataflow.
* Rehydration time per dataflow.

`hydration time` is apparently already measured. [Example Grafana panel](https://grafana.dev.materialize.com/d/f248986d-81c6-42a6-817b-00cd7759d808/compute?orgId=1&viewPanel=63).

Initial questions:
* Is the current `hydration time` metric sufficient for the hydration time ask? (Is it per dataflow?)
* For both hydration and rehydration, would it be useful to publish a normalized `rate` metric (the time per unit of data ingested)?

## Work items

```[tasklist]
- [ ] #1
```

## Decision log

* **6 May 2024.** Issue created.

**Comment by benesch** [comment]
Flagging [ongoing discussion in product brief](https://www.notion.so/Document-and-Measure-Sources-of-Unavailability-in-Materialize-761066423377480c89e8990104bfacc9?d=fb62706cbcaf40979c77e089257500e3&pvs=4#dfd0473dcd0845ee895b8818dbc49883): for compute dataflows, there's no difference between initial hydration and rehydration, and so it wouldn't make sense to have separate metrics, and indeed the terms are used interchangeably internally. For storage dataflows, the initial snapshot looks quite different than rehydration and makes sense to track separately, but there has been some consternation about using "hydration" and "rehydration" noninterchangeably. I believe the counterproposal is to call it "snapshotting" vs "hydration/rehydration".

Note that the existing "hydration time" panel in Grafana is for compute so it measures both "hydration" and "rehydration" time.

**Comment by benesch** [comment]
A few quick thoughts:

  * I suggest we break the link between this issue and the [Document and Measure Sources of Unavailability](https://www.notion.so/materialize/Document-and-Measure-Sources-of-Unavailability-in-Materialize-761066423377480c89e8990104bfacc9) product spec. That spec still has a bunch of outstanding questions. I think there is a much more focused and actionable product spec we could write that limits scope to hydration metrics for dataflows.
  * This information will be useful for the ongoing 0dt efforts, so there's an eng internal reason to prioritize this, beyond whatever product motivation exists!
  * The hydration time panel in Grafana uses the `mz_dataflow_initial_output_duration_seconds` metric, which, IIRC, is something subtly different than hydration time. That may be sufficient to satisfy the product ask, but nonetheless on the engineering side we should be clear whether we mean real hydration or time to initial output.
  * Linking in the discussion from the `REFRESH EVERY` design doc about how we'd design this: https://github.com/MaterializeInc/materialize/pull/22776#discussion_r1565549369
  * I'm in favor of doing the quickest thing possible and putting it in `mz_internal` or `mz_introspection`. We can always build a more general purpose solution later should it become necessary.

**Comment by bosconi** [comment]
@teskje I think it makes sense for you to write up the design you have in mind, either here or in a markdown file, addressing the above questions, and then let's have a quick review and hopefully move forward with this.

**Comment by teskje** [comment]
I think there are three stages to this that each build on each other and each increase usefulness:

# 1. Measuring Hydration Time on the Replica Side

We introduce a new per-collection `ComputeEvent` that is emitted when the `ComputeState` detects a collection as hydrated. This happens based on the as-of: Once the collection's output frontier moves past its as-of, we consider it as hydrated. The logic is the same as what's currently applied by the compute controller to determine `mz_dataflow_initial_output_duration_seconds`, just that it doesn't get confused about reconciliation since the `ComputeState` is aware of that process.

The compute logging dataflow uses the new `ComputeEvent` to expose an introspection index that reports for each collection ID whether the hydration time, or NULL for collections that are not hydrated. The introspection index is made available to SQL clients as a per-replica introspection relation:

```sql
mz_introspection.mz_compute_hydration_times_per_worker (
    export_id text NOT NULL,
    worker_id uint8 NOT NULL,
    hydration_time interval
)
```

This makes hydration times queryable from SQL, but with all the usual drawbacks (inconvenience, potential unresponsiveness) imposed by using a per-replica introspection source.

# 2. Providing a Unified Introspection Relation

We make `mz_internal.mz_compute_hydration_statuses` a unified introspection relation that reads from `mz_introspection.mz_compute_hydration_times_per_worker`. This relation has the same schema as the existing `mz_compute_hydration_statuses` but adds a `hydration_time` column:

```sql
mz_internal.mz_compute_hydration_statuses (
    replica_id text NOT NULL,
    object_id text NOT NULL,
    hydrated boolean NOT NULL,
    hydration_time interval
)
```

The subscribe query will be something along these lines:

```sql
SELECT
    export_id AS object_id,
    mz_unsafe.mz_all(hydration_time IS NOT NULL) AS hydrated,
    CASE mz_unsafe.mz_all(hydration_time IS NOT NULL)
        WHEN true THEN max(hydration_time)
        ELSE NULL
    END AS hydration_time
FROM mz_introspection.mz_compute_hydration_times_per_worker
GROUP BY export_id
```

This makes hydration times queryable without the drawbacks involved with having to query per-replica introspection sources. It doesn't yet provide a way to get at hydration times further back than the last hydration.

# 3. Providing historical Hydration Times

This part I think needs discussion. There are two major avenues here:

## 3.1

We make `mz_internal.mz_compute_hydration_times` a "retained-metrics" relation, setting its compaction window to 30 days. Alternatively, we specify a different compaction window that suits our needs better.

* Advantages:
  * Easy to implement.
  * Automatic cleanup of old updates through persist compaction.
* Disadvantages:
  * Querying historical data requires `AS OF` queries, which don't have great UX.
  * Data includes transient dataflows (SELECTs and SUBSCRIBEs), which blows up its size. SELECTs usually won't show up because their dataflows are dropped quickly, but we can't guarantee that they never show up.

Ways to solve the last disadvantage exist: We can exclude transient dataflows from `mz_compute_hydration_times`, making it less useful for observing the state of SUBSCRIBEs. Or we can make `mz_compute_hydration_times` different from `mz_compute_hydration_statuses` and only exclude transient dataflows from the former while the latter retains its current short compaction window. This assumes that users are interested in the hydration status of SUBSCRIBEs, but not so much their hydration times, which may be true.

## 3.2

We extend the unified introspection mechanism with support for writing the subscribe results to append-only storage-managed collections: Insertions are appended as usual, retractions and replica deletions are ignored. We then introduce a new unified introspection relation, `mz_internal.mz_compute_hydration_history` that is append-only and receives all hydration times of _non-transient_ dataflows in the system.

* Advantages:
  * Convenient to query historical hydration times using a regular `WHERE` filter, no `AS OF` queries required. This also allows comparing hydration times over time in SQL.
  * `mz_compute_hydration_times` stays useful for observing the status of transient dataflows.
* Disadvantages:
  * Higher implementation effort due to the need to extend the unified introspection mechanism. Though not that bad.
  * Cleanup of old data is an unsolved problem. Other existing collections have this as well, so we'll need a solution eventually, but we don't have one yet.

# Open questions:

* Which of the two approaches under (3) should we take?
* Should the relations refer to hydration time as "hydration latency" instead, to mirror `mz_source_statistics`?

**Comment by teskje** [comment]
> The hydration time panel in Grafana uses the `mz_dataflow_initial_output_duration_seconds` metric, which, IIRC, is something subtly different than hydration time.

The difference I am aware of is that `mz_dataflow_initial_output_duration_seconds` is measured by the controller, which doesn't know when dataflows are reused during reconciliation and therefore can report ~instant hydration times when a dataflow was reused even though it really took hours to hydrate that dataflow previously. Apart from that, the metric tries to match our definition of hydrated, i.e. "dataflow has processed the snapshot input". The metric only has this strange name because when we introduced it, it wasn't clear that this should be our definition of "hydrated".

> Will this work encompass storage dataflows too, or will it be limited to compute dataflows?

My proposal above is limited to compute dataflows. For source dataflows, we already have `mz_source_statistics.rehydration_latency`, so I think we are good for those. For sink dataflows, hydration time is still missing. We can consider exposing that through `mz_sink_statistics`, similar to how we do it for sources. Alternatively, we could pick up cluster unification, which would unlock (unified) introspection for storage dataflows as well.

**Comment by teskje** [comment]
I put up a first iteration of parts (1) and (2) here: https://github.com/MaterializeInc/materialize/pull/27972

**Comment by teskje** [comment]
> Which of the two approaches under (3) should we take?

Perhaps this is a good compromise between simplicity of implementation and flexibility:
* Expose hydration times of all collections through the per-replica introspection source.
* Filter out transient collections (SELECTs, SUBSCRIBEs) in the query for the unified introspection relation.
* Make the unified introspection relation a retained metrics collection.

This way the size of the unified introspection relation should stay manageable. It doesn't contain transient dataflows but that's probably fine? In a pinch the hydration times of transient dataflows are still available in the per-replica introspection sources.

**Comment by benesch** [comment]
Yeah, that sounds like a great compromise! I think the design you’ve proposed sounds great on all fronts. No notes. 

> The metric only has this strange name because when we introduced it, it wasn't clear that this should be our definition of "hydrated".

Ah, got it, thanks for clarifying!

> Alternatively, we could pick up cluster unification, which would unlock (unified) introspection for storage dataflows as well.

This is certainly my preference. I don’t think we need to rush to solve this with sink stats. Sinks should pretty much always hydrate immediately, so while it’s always good to have metrics bearing that out, I’m not fussed about the current situation. The source stats don’t report rehydration time properly for certain source variants that rehydrate nearly instantly, and no one has found that to be deeply problematic.

**Comment by teskje** [comment]
> The source stats don’t report rehydration time properly for certain source variants that rehydrate nearly instantly, and no one has found that to be deeply problematic.

Agreed on hydration time reporting being less critical for things that hydrate immediately, but can you expand on what's not working properly with the hydration time reporting for sources?

**Comment by benesch** [comment]
Oh, maybe my knowledge is out of date? Historically we only got rehydration times for upsert sources, IIRC.

**Comment by teskje** [comment]
I did mean to change that at some point (https://github.com/MaterializeInc/materialize/pull/24015), but it's entirely possible that I missed some details about how sources behave!

**Comment by benesch** [comment]
Ah, great! My memory is just out of date. (And I even reviewed #24015. 🙈)
