### ISSUE TITLE
persist: bounded state size (timeboxed)

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#26939]
A two-week timeboxed sprint to see if we can shake out a design and implementation for bounding the amount of shard state stored in CockroachDB—e.g., by using a two level state where some state is stored on S3.

**Comment by bkirwi** [comment]
## Design sketch

In inline writes, we have precedent for data that's kept in the shard state, but spilled out to disk when it gets too large to comfortably hold in memory. I propose treating the part/run metadata similarly: as state that we normally keep inline, but write out to S3 and replace with a pointer if it becomes too large.


- A new struct `HollowRuns` stores some data that we currently store on the top-level `HollowBatch` struct: parts and run metadata.
- Another new struct `HollowRunsRef` is a pointer to a proto-encoded `HollowRuns` that's stored in S3, along with some inline metadata like the sum of the encoded part size.
- We add a new `runs_ref: Option<HollowRunsRef>` field to `HollowBatch`. (Or is a `Vec` better?)
- There are two categories of callers that care about the parts data:
  1. Callers that actually need to know the full list of parts/runs need to become async. In general we only care about the specific parts when we're about to fetch them, though, and that code is already async... so this may not be too invasive.
  2. Lots of non-async code cares about the part count, or the total encoded size, or other stats like this. We should add the appropriate numbers to the `HollowRunsRef`... as long as it's not proportional to the number of parts it's fair game.

My hypothesis is that all callers fall into either 1 or 2 without too much work, so we could add this indirection without a vast refactoring. If so, I think this is plausibly a short project. If not it probably outgrows the timebox.

**Comment by bkirwi** [comment]
@danhhz points out that historically, we were also worried about the sheer number of batches that a shard could accumulate... and the sketch above doesn't cover this. It sounds like we're comfortable keeping the scope to a single batch -- we haven't had that sort of bug in a while, and compaction 2.0 should help keep us to a nice logarithmic number of batches -- but worth calling out!

**Comment by bkirwi** [comment]
Some napkin math:
- If we want to handle about shards with very high part counts, we should handle batches with very high part counts (because the largest batch has roughly ~half of the data in the shard)
- If we want to handle a single very large batch, we should handle a single very long run.
- Let's use 128 MiB for the ideal max size of a `HollowRuns` struct, to match our max data size. Assuming 3KiB or so for each part's metadata, we can fit up to 50k parts or so in one struct. 50k maximum-size parts are enough to store 5TiB or so of data. We'd like to comfortably support shards orders of magnitude larger than this, so it's not safe to assume that even a single run will fit comfortably in memory.
- Restricting ourselves to just a single top-level `HollowRunsRef` field doesn't give us a nice way to represent extremely long runs... we could split our long runs across multiple external blobs, but we need some way to express the ordering.

One slighly oddball way to model this is to make `HollowRunsRef` a possible variant of `BatchPart`.  Feels weird, but semantically it might be fine? (As long as it respects the usual Laws of Runs - in a multipart run, each part should be fully consolidated, with all updates larger than those in any earlier part in the run and smaller than those in any later part of the run.)

**Comment by danhhz** [comment]
Love the BOE math!

Hooking this in as a variant of `BatchPart` sounds reasonable to me, I wouldn't even call it oddball. Though, I think it's probably easier to reason about (at least to me) if it only ever pulls out a subset of a single run (I couldn't tell if this is what you meant or not). The implication is a big batch with multiple big runs would end up with at least one of these per run, but that seems fine?

Three thoughts (my head is mostly loaded up with other things, so these might be nonsense):
- Completely different idea than we've been considering so far, but is there anything interesting to modeling this in the "diffs dimension" instead of the "state/rollup dimension"? I think the answer is no, not sure how it would solve any of the concrete problems other than the "finalize/rountrip-state rewrites everything" one, but figured I'd mention it for the purposes of explicitly rejecting it.
- Does some framing of "variant of BatchPart" bring back the "flush hollowbatches in a spinebatch out" idea back into play? I'm not quite seeing it (and we decided it was out of scope) but somehow feels close-ish? Maybe this argues against my "only flush out a single run" thing above
- Let's walk through how snapshotting incremental compaction progress would work, just to make sure we don't cause our future selves any problems

**Comment by bkirwi** [comment]
> Though, I think it's probably easier to reason about (at least to me) if it only ever pulls out a subset of a single run (I couldn't tell if this is what you meant or not). The implication is a big batch with multiple big runs would end up with at least one of these per run, but that seems fine?

Yeah, I think that limitation is probably helpful and fine... I can't see any reason to spill a `HollowRuns` that is both part of a multipart run and _itself_ contains >1 run, so easy enough to just ban it.

> Completely different idea than we've been considering so far, but is there anything interesting to modeling this in the "diffs dimension" instead of the "state/rollup dimension"?

I'm not sure I understand "diffs dimension" but it seems intriguing!

> Does some framing of "variant of BatchPart" bring back the "flush hollowbatches in a spinebatch out" idea back into play?

It does feel like there's _something_ interesting we could do here, but I don't have my finger on it either, and I think it's probably worth keeping out of scope for now.

> Let's walk through how snapshotting incremental compaction progress would work, just to make sure we don't cause our future selves any problems

So far this looks okay to me; assuming we go with the ideas [here](https://www.notion.so/materialize/Compaction-2-0-notes-b381824518ce4539b1b9f8a898abc5bb?pvs=4#44f72cc5a35f44c9a6f8a1752f65f8be):
- We may need to spill the intermediate compaction outputs out as `HollowRuns`, in the case of a very long compaction output run.
- For the inputs, we have `next_update` available in state. When we resume an incremental compaction, we can skip over `HollowRuns` when the `key_lower` of the next batch is at least the `next_update`.

Though compaction is the main thing I haven't kicked the tires on yet, incremental or otherwise, so I've get less confidence that I've thought it out properly yet...

**Comment by bkirwi** [comment]
Compaction seems fine! Streaming consolidate needs to fetch a `HollowRuns`-backed part whenever it's the next element of a run, but that's fairly straightforward after the more flexible leasing from #27021. The other half is the batch builder, and it looks like the move there is to adapt it to spill out its list of runs to disk if it grows over some threshold.

**Comment by benesch** [comment]
Closing this out for tracking purposes, since this issue was tracking the timeboxed sprint, which is now complete!

The work to actually implement this will be tracked in https://github.com/MaterializeInc/materialize/issues/28755.
