### ISSUE TITLE
Fuse views in dataflow optimization / construction

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2709]
We currently build dataflows that involve multiple views by optimizing and rendering each view independently. This leaves a lot of optimization potential on the floor, and in particular prevents us from moving operators across view boundaries. There are cases where we would like to do predicate pushdown, or reduction pushdown, and instead will have sub-optimal plans (we don't do reduction pushdown yet, but .. yeah we want to soon).

This could be as simple as introducing each view as a `RelationExpr::Let`, though with a carefully chosen identifier so as not to clash. It is probably more complicated than that, but we'll want to do something (or recommend against the use of views, which I don't think we want to do).

**Comment by benesch** [comment]
Is this different from #2592?

**Comment by wangandi** [comment]
I see this as not the same as #2592 yet but potentially becoming the same once #2537 is implemented. 

Suppose you want to materialize a view `v2` that depends on unmaterialized `v1`, which in turn depends on unmaterialized source `s`. 

I see the focus of this issue as "the `RelationExpr` for `v1` and `v2` can be combined into a bigger `RelationExpr`". 
I see the focus of #2592 as "stuff such as maps/filters/projects can be pushed down so that they actually run inside `s`." Once we can express `s` as a `RelationExpr`, these two issues will be the same. But for now, #2592 involves dealing with `LinearOperator` and src/dataflow/src/render/source whereas this issue should not involve changes to the rendering code.
