### ISSUE TITLE
ALTER SINK test flakiness

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27501]
### What version of Materialize are you using?

bccbda1fda

### What is the issue?

```
alter-sink.td:71:1: error: non-matching rows: expected:
[["true"]]
got:
[["<null>"]]
Poor diff:
+ <null>
- true

     |
  16 |     URL '${testdrive ... [rest of line truncated for security]
  54 |     URL '${testdrive ... [rest of line truncated for security]
  70 | 
  71 | > SELECT st.error LIKE '%schema being registered is incompatible with an earlier schema%'
     | ^
importer.proto:2:1: warning: Import empty.proto is unused.
importer.proto:2:1: warning: Import empty.proto is unused.
+++ !!! Error Report
1 errors were encountered during execution
files involved: alter-sink.td
```
Seen in https://buildkite.com/materialize/nightly/builds/8007#018fed53-d171-4bb3-9b56-4ae9ac6c1646

Test/feature were just introduced in https://github.com/MaterializeInc/materialize/pull/27379

ci-regexp: alter-sink.td:71:1: error: non-matching rows: expected

**Comment by petrosagg** [comment]
It might take ~30 seconds or so for the error to be reported. How can I tell testdrive to try for longer?

**Comment by def-** [comment]
Something like this should work: https://github.com/MaterializeInc/materialize/pull/27509

**Comment by petrosagg** [comment]
Thank you @def- !

**Comment by nrainer-materialize** [comment]
This does still occur in https://buildkite.com/materialize/nightly/builds/8021.

**Comment by def-** [comment]
Even after waiting for 6 minutes(!),so definitely doesn't seem like the result will become correct later:
```
2024-06-08 01:36:09 CST	> SELECT st.error LIKE '%schema being registered is incompatible with an earlier schema%'
2024-06-08 01:36:09 CST	FROM mz_sinks s JOIN mz_internal.mz_sink_statuses st ON s.id = st.id
2024-06-08 01:36:09 CST	WHERE s.name = 'incompatible_sink';
2024-06-08 01:42:09 CST	rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 111s 27s
2024-06-08 01:42:10 CST	alter-sink.td:74:1: error: non-matching rows: expected:
2024-06-08 01:42:10 CST	[["true"]]
2024-06-08 01:42:10 CST	got:
2024-06-08 01:42:10 CST	[["<null>"]]
2024-06-08 01:42:10 CST	Poor diff:
2024-06-08 01:42:10 CST	+ <null>
2024-06-08 01:42:10 CST	- true
```

**Comment by petrosagg** [comment]
Yeah in my local testing the error is reported immediately so I'm not sure yet why the error is missed. I had incorrectly diagnosed it as being related to the 30 second restart delay we have for dataflows because I thought that we report the error at the moment of the restart, but we're actually reporting it immediately and then wait for 30 seconds.

**Comment by petrosagg** [comment]
Recording this here too. I got to the bottom of this and the error is caused because the nightly tests run against `redpanda` which has its own schema registry implementation and that implementation does not do compatibility checks. I will look at whether there is flag that can be enabled or if it's not supported in general
