### ISSUE TITLE
Kafka sink management improvements

### ISSUE THREAD

**Issue by jnoynaert** [MaterializeInc/materialize#27775]
### Feature request

Operating Kafka sinks would be smoother with:

- Visibility:
    - Show sink statistics from `mz_internal.mz_sink_statistics`, current and over time, in the sink UI
    - Show current in-progress Kafka sink transactions and transaction/batch history in the sink UI (hopefully also exposed in `mz_internal` if not present so that automated remediation for stuck or long-running transactions is possible)
    - Surface clearer error descriptions when the internal transaction/batch timeout occurs, to distinguish between Kafka broker timeouts and internal Mz limits

- Functionality
    - Add a new connection option to skip transactions, which would apply at the sink level. If there are no transactional consumers, resending failed transactions and dealing with transaction settings is just overhead
    - On initial snapshots, have a much longer default internal Mz timeout (maybe still provide a warning at the usual timeout?), and/or let users configure this at whatever level is appropriate

**Comment by benesch** [comment]
@jnoynaert, thanks again _so much_ for filing this issue. It's an awesome list of suggestions. For our internal project management, we've chopped this up into a bunch of subissues that can be assigned and tracked by the right teams. I'm going to close this out to keep things tidy. Rest assured that we are not closing this as a "wontfix". Rather, a few of the ideas you included here are things we want to prioritize immediately, and it's much easier to do so if we have standalone issues for each idea.

The following is how the new issues to your original request. I've CC'd you on each of these new issues so that you get notified when activity on the issue happens.

>   * Show sink statistics from `mz_internal.mz_sink_statistics`, current and over time, in the sink UI

Tracked in https://github.com/MaterializeInc/materialize/issues/27957.

>   * Show current in-progress Kafka sink transactions and transaction/batch history in the sink UI (hopefully also exposed in `mz_internal` if not present so that automated remediation for stuck or long-running transactions is possible)
>   * Surface clearer error descriptions when the internal transaction/batch timeout occurs, to distinguish between Kafka broker timeouts and internal Mz limits

Tracked in https://github.com/MaterializeInc/materialize/issues/27956.

>   * Add a new connection option to skip transactions, which would apply at the sink level. If there are no transactional consumers, resending failed transactions and dealing with transaction settings is just overhead

Tracked in https://github.com/MaterializeInc/materialize/issues/27958.

>   * On initial snapshots, have a much longer default internal Mz timeout (maybe still provide a warning at the usual timeout?), and/or let users configure this at whatever level is appropriate

Tracked in https://github.com/MaterializeInc/materialize/issues/23955.
