### ISSUE TITLE
20% performance regression in ParallelIngestion

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27945]
### What version of Materialize are you using?

5877d09ac8

### What is the issue?

Started failing in main in https://buildkite.com/materialize/nightly/builds/8256 and also in v0.106.0, thus marking as release blocker for this release.
```
NAME                                | TYPE            |      THIS       |      OTHER      |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
ParallelIngestion                   | wallclock       |          14.073 |          11.669 |    !!YES!!    | 20.6 pct   more/slower
ParallelIngestion                   | messages        |   100000200.000 |   100000258.000 |      no       | 0.0 pct   less/faster
ParallelIngestion                   | memory_mz       |        1791.954 |        1804.352 |      no       | 0.7 pct   less/faster
ParallelIngestion                   | memory_clusterd |         129.890 |         142.002 |      no       | 8.5 pct   less/faster
```
These changes could be responsible: https://github.com/MaterializeInc/materialize/compare/1d680a5e5a...5877d09ac8

Most likely cause: https://github.com/MaterializeInc/materialize/pull/27814 CC @petrosagg 
Less likely cause: https://github.com/MaterializeInc/materialize/pull/27800 CC @ParkMyCar 

I couldn't repro it locally, probably because my machine has too many cores. It happens reliably in CI.

**Comment by nrainer-materialize** [comment]
> Most likely cause: #27814 CC @petrosagg

It's this one.

**Comment by bosconi** [comment]
@petrosagg after discussion with @benesch we think it makes sense to timebox any remaining investigation, and mostly to check there isn't something easy to fix that is contributing to the slowdown. But this work is fundamentally a tradeoff, and a 20% reduction in ingestion speed might just be the cost to pay in exchange for non-OOMing ingestion.

**Comment by petrosagg** [comment]
I got to the bottom of this and the slowdown was due sources using `lgalloc`. This is currently only happening in CI because two features need to be enabled for sources to use `lgalloc` but only one is enabled in production:

* `enable_columnation_lgalloc`: This globally enables `lgalloc` and is enabled in CI and prod
* `enable_compute_chunked_stack`: This globally enables `flatcontainer` instead of `columnation` based containers and is only enabled in CI

`flatcontainer` based containers will first attempt to put data into `lgalloc` backed buffers and if that fails (e.g because `lgalloc` is disabled) it will use normal memory. On the other hand `columnation` based containers directly store data in-memory.

I don't think there is anything to change here so I will close this issue.
