### ISSUE TITLE
Creating a sink with a nontrivial number of records results in temporary loss of interactivity

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2806]
We can reproduce this by creating a sink w/ a materialized view that has tens of thousands or more records -- just create a sink and do any simple query e.g.

```
materialize=> CREATE SINK "materialize"."public"."billing_sink2" FROM "materialize"."public"."billing_monthly_statement" INTO KAFKA BROKER 'localhost:9092' TOPIC 'billing_monthly_statements' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081';
CREATE SINK
Time: 130.902 ms
materialize=> select * from mz_kafka_sinks;
 global_id |                            topic
-----------+--------------------------------------------------------------
 u21       | billing_monthly_statements-u21-1588083365-203249639592080772
(1 row)
Time: 83495.844 ms (01:23.496)
materialize=>
```
this is likely the same issue that was seen here: https://github.com/MaterializeInc/materialize/issues/2576#issuecomment-619246012

Thinking out loud on root cause: we assign one thread to do all of the work for writing out to a sink, and theres no "fuel tank" limiting how much work that thread can do writing down sink data and my understanding of our architecture is that we need all threads to be responsive (not blocked on writing to kafka) in order to service queries.

Things do seem to come back to normal for me after this temporary loss of interactivity. Also note that this relates to #1537

**Comment by frankmcsherry** [comment]
That sounds like a reasonable diagnosis. There could be more things, but for sure the way the code is now when a sink is created on a large materialized source, it gets a full dump of all the data in one shot.

A probably important related issue: differential currently operates under the believe that if you give it X update records, it has permission to do X units of work (this is part of the auto-tradeoff between latency and throughput). When we create a sink (or other dataflow elements) we often dump an entire collection all at once. We may want to meter out the data more carefully to retain responsiveness (or get it over with quickly and train people that dataflow creation is not the cheapest of things).

One example is an arrangement's `as_collection` method which takes batches and streams them out. This does not use fuel either, and will be tricky to control without some rate limiting. Fortunately, it is super easy to write, and we could write our own (maybe push back at the differential repo, but there interactive dataflow construction is less of a central design goal).

The sink operator really isn't that different, but it is probably just substantially more expensive than other operators (each record gets sent to Kafka as its own message, rather than batched).

**Comment by benesch** [comment]
For posterity, #2855 probably makes this situation much better.
