### ISSUE TITLE
mzimage/mzbuild should take file permissions into account for rebuild requirements

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#2809]
Currently changing file permissions for files that need to be COPYed into a docker image requires running `docker rmi $(path/to/mzimage spec IMAGENAME)`

**Comment by benesch** [comment]
Oops, did I get this wrong? https://github.com/MaterializeInc/materialize/pull/2720 might be relevant here. What permissions are you changing? It _should_ notice executable and symlink, but not anything else.

**Comment by quodlibetor** [comment]
It should to also notice writeable, since that affects the writeability of artifacts inside of docker images. Actually all mode bits are translated across to the Docker image, and so should probably be tracked?

**Comment by benesch** [comment]
The fingerprinting is intended to track files that are checked into source control, and the only mode bits that are tracked by Git are symlink/user-executable. The bug that I fixed in #2720 was the result of taking too many mode bits into account and computing different fingerprints on Brennan's machine. If we take additional mode bits into account, we'll have non-deterministic behavior based on individual system's umask, etc.

Maybe we can explode if we detect any non-readable or non-writeable files in the build context? But what are you doing that you are getting non-readable or non-writeable files in the build context in the first place?

**Comment by quodlibetor** [comment]
The issue is changing files to be readable/writeable by different groups. so permissions like `-rw-rw-rw-` to ensure that they are writeable by everyone.

I do think that exploding on anything other than 644 or 744 and saying that they must be modified inside the docker build makes some sense, if git can't track it.

**Comment by benesch** [comment]
Ah, yeah, if you're checking that file into Git, those permissions won't be
preserved for anyone else when they `git pull` anyway. Definitely makes
sense to me to check for rw-r-r or rwx-r-xr-x on everything inside of an
mzbuild context, to force us to chown any added files inside of the
Dockerfile.

**Comment by benesch** [comment]
I think this is actually working as desired, and adding the check to enforce 644/755 doesn't seem urgent. In fact it could break random users downstream who are checking out the Materialize repo in weird configurations.
