### ISSUE TITLE
0dt upgrade: ERROR: No such file or directory (os error 2) in CREATE SOURCE mysql_source2_false

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28570]
### What version of Materialize are you using?

e5c5348ee3

### What is the issue?

[Checks 0dt upgrade, whole-Mz restart](https://buildkite.com/materialize/nightly/builds/8835#0190f018-71bd-4ee8-bafb-09975855ff3c) and the other 0dt upgrade tests started failing:
```
13:1: error: executing query failed: db error: ERROR: No such file or directory (os error 2): ERROR: No such file or directory (os error 2)
     |
   2 | $[version>=5200] pos ... [rest of line truncated for security]
   5 | $ mysql-connect name ... [rest of line truncated for security]
  12 | 
  13 | > CREATE SOURCE mysql_source2_false
     | ^
```
My guess is that this could be related to the already fixed https://github.com/MaterializeInc/materialize/pull/28285 occurring in MySQL connection now while we were still on the old version. This fits with the error not happening in the [Checks 0dt restart of the entire Mz](https://buildkite.com/materialize/nightly/builds/8835#0190f018-71bc-4054-b79d-7593b137e99c). What doesn't make sense to me though is that it happens during CREATE SOURCE now, not when dropping.

The services.log talks about a file in /tmp missing, in relation to connecting to a process:
```
platform-checks-mz_1-1              | cluster-u30-replica-u34-gen-0: 2024-07-26T17:45:05.846759Z  INFO mz_cluster::communication: error connecting to process at /tmp/b709efed244790b682f2e6bfb9ce147d5622e2f0: No such file or directory (os error 2); will retry process=1
```
Discussion on Slack: https://materializeinc.slack.com/archives/C071VTZS1M5/p1722029728874599
ci-regexp: ERROR: No such file or directory (os error 2)

**Comment by def-** [comment]
This disappeared in main again, strange!

**Comment by def-** [comment]
Difference is that it happens for postgres sources now, in both occurrences, and both are in the [Checks 0dt upgrade across four versions](https://buildkite.com/materialize/nightly/builds/8937#01911821-e722-4ea6-8b5a-a51f570c12b4).
This is while on `materialize/materialized:v0.110.3`, so not latest state. @aljoscha Should we be worried about this or ignore since it's something that might be wrong in an older state?

**Comment by benesch** [comment]
I have a theory as to what's going on here.

First up, I think the errors in the logs are red herrings. Those logs are semi-expected when a multi-process cluster boots up on a busy machine. Not every `clusterd` process is able to start listening before other `clusterd` processes start trying to connect.

To confirm that theory, I have a PR that will add more context to failed secret operations: https://github.com/MaterializeInc/materialize/pull/28812

With that PR in place, I expect that the error message we see from the platform checks will show "reading secret uXXX: no such file."

Second, a theory as to the root cause: the orphaned secrets cleanup doesn't respect read only mode!

https://github.com/MaterializeInc/materialize/blob/ea4d9adfeea49e99da74720d9d322b5480c1241c/src/adapter/src/coord.rs#L2200-L2225

So I think the new environment bootstraps the catalog in read only and finds (say) two secrets, then the old env creates a new secret, and then the new env _deletes_ the contents of that new secret from the secrets controller because the secret didn't get loaded into the new env's catalog. Oops! 🙈 

I'd like to get a repro of this bug with #28812 in place to confirm that it really is secrets going missing. If confirmed, I'll put up a PR to make the orphaned secrets cleanup respect RO mode.
