### ISSUE TITLE
parallel-workload: Uploading services.log fails

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#29146]
### What version of Materialize are you using?

11a3c20d1e

### What is the issue?

Most parallel-workload tests timed out because the upload of services.log didn't complete: https://buildkite.com/materialize/nightly/builds/9209#019174b7-ba1d-4a85-b428-6a978b324113
The relevant changes: https://github.com/MaterializeInc/materialize/compare/623ca08e91...11a3c20d1e
Only one stands out: https://github.com/MaterializeInc/materialize/pull/29139
Reproducing locally: `bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --runtime=1500 --complexity=ddl-only --threads=2`

**Comment by def-** [comment]
@teskje Could your change have done something that increased the amount of logs or caused strange logs? This is still a bug in the buildkite artifact uploader I think, but trying to figure out why it's happening now.

**Comment by def-** [comment]
I didn't see this again in https://buildkite.com/materialize/nightly/builds/9211#_, so maybe just a Buildkite infra problem. I'll reopen if it happens again.

**Comment by teskje** [comment]
> Could your change have done something that increased the amount of logs or caused strange logs?

The change removes a possible stall in the tokio runtime. Previously when Timely was unresponsive, that could stall all tokio tasks. With that change, that does't happen. It's possible that we have more logs now because some things producing logs are now less often stalled than before? That would suggest that some task in clusterd is producing a large amount of logs, which doesn't ring any bells off the top of my head.
