### ISSUE TITLE
Musing: dealing with nested inputs is annoying, and requires some automation to 'flatten'/access nested fields

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2933]
A prospect notes that using the JSON accessor fields currently is annoying. Anecdotally, I tend to agree, because writing `foo->>bar->baz` has similarly annoyed me in the past. Could we perhaps extend dot notation to access nested fields? `foo.bar.baz` is just simply more idiomatic.

What would be the barriers to implementing this? Is this simply not idiomatically postgres?

**Comment by benesch** [comment]
There are several landmines here, which is why it works the way that it does. The first is that the SQL grammar has very strict rules for identifiers, and any identifier of the form

```
a.b.c
```

is taken to mean database `a`, schema `b`, and object `c`. The name resolution would get horribly complicated if `a.b.c` could mean "table a.b.c" _or_ "field c of column a.b" _or_ "field c of field b of column a". 

The chapter on composite types in PostgreSQL is illuminating, because composite types do have the syntax you're after.

> To access a field of a composite column, one writes a dot and the field name, much like selecting a field from a table name. In fact, it's so much like selecting from a table name that you often have to use parentheses to keep from confusing the parser. For example, you might try to select some subfields from our on_hand example table with something like:
>
> ```
> SELECT item.name FROM on_hand WHERE item.price > 9.99;
> ```
>
> This will not work since the name item is taken to be a table name, not a column name of on_hand, per SQL syntax rules. You must write it like this:
>
> ```
> SELECT (item).name FROM on_hand WHERE (item).price > 9.99;
> ```
>
> or if you need to use the table name as well (for instance in a multitable query), like this:
>
> ```
> SELECT (on_hand.item).name FROM on_hand WHERE (on_hand.item).price > 9.99;
> ```
>
> Now the parenthesized object is correctly interpreted as a reference to the item column, and then the subfield can be selected from it.
>
> Similar syntactic issues apply whenever you select a field from a composite value. For instance, to select just one field from the result of a function that returns a composite value, you'd need to write something like:
>
> ```
> SELECT (my_func(...)).field FROM ...
> ```

https://www.postgresql.org/docs/current/rowtypes.html#ROWTYPES-ACCESSING

It's also important to note that `->` and `.` are different in a very important way. `->` is dynamic map lookup; `.` is static field lookup. What you are doing with JSON is `json_object["field"]`, and what you are doing with a record is `record_object.field`. The former happens at runtime, while the latter happens at plan time. The only language I know of that fuzzes up this distinction is JavaScript, where `a.field` and `a["field"]` are totally equivalent.

So no matter what you'd need to write (table.col).field, because otherwise we'd have to give up on Postgres compatibility. We could _probably_ make the `(table.col).field` syntax work on JSON types as well as record types, but I would be very uncomfortable doing so anytime soon, since it just smells like there's a good chance we'd stumble into an unfixable Postgres incompatibility.

But! I think the combination of record types, https://github.com/MaterializeInc/materialize/issues/2679, and https://github.com/MaterializeInc/materialize/issues/1494 would mean that we could replace JSON blobs with record types automatically for many customers, where you would get `.` notation. Then you wouldn't need to use the `->` syntax unless you were dealing with truly schemaless JSON blobs, i.e., when you'd actually appreciate the flexibility of `->`.

**Comment by rjnn** [comment]
This is perfect! Thanks for the detailed thoughts. Record types and dot notation is exactly what we want, and it's great that we are already getting there.

**Comment by benesch** [comment]
Closing, since it seems we have a clear path forward and enthusiasm for that path!
