### ISSUE TITLE
`abs` for `numeric`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#2989]
in Postgres:

```
select abs(1::numeric);
```
```
1
```

Implementation DNE in Materialize

**Comment by elindsey** [comment]
This one looks like it's already done, a sqllogictest like this passes:
```
query I
SELECT abs(-1::numeric)
----
1
```
Appears that numeric is only a pgrepr and ends up as a decimal once it hits the actual function logic.

**Comment by benesch** [comment]
Oh, yeah, good catch. The commit that added it is here: https://github.com/MaterializeInc/materialize/commit/e1b526eecdb024d3a1b4b961a115c262331234b4

FYI "numeric" and "decimal" are total synonyms in PostgreSQL and therefore Materialize. I think "decimal" is 10x clearer so that's why Materialize-specific stuff uses that term, but at the boundaries we use Postgres's preferred term "numeric".
