### ISSUE TITLE
Expose progress through sources as a logging source

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#3069]
This presents as a Prometheus metric, but is relatively easy to log and make available through an interactive shell. There are candidates use cases like joining with results to correlate input offsets with output timestamps for downstream reports.

**Comment by krishmanoh2** [comment]
As an end-user, the common ask with respect to streaming systems is the ability to see if mz is current with source of truth. This helps a customer know (among other things)
 
If results are current

If anything is broken?

If there is a lag, determine how much it is and plan accordingly

Is the lag in the source ingest part or the maintenance in the MV? Track source ingest and MV separately.

The valuable part here is showing the currentness of a MV without needing any time fields to be defined in the MV. Other systems in the RDBMS space provide this ability via SCN/LSN etc. SCN provides a txn boundary. 
 
Ideally, as to when the MV was updated - also needs to be maintained across restarts.
 
From Oracle as example - 
 
System Change Numbers (SCNs)
A system change number (SCN) is a logical, internal time stamp used by Oracle Database. SCNs order events that occur within the database, which is necessary to satisfy the ACID properties of a transaction. Oracle Database uses SCNs to mark the SCN before which all changes are known to be on disk so that recovery avoids applying unnecessary redo. The database also uses SCNs to mark the point at which no redo exists for a set of data so that recovery can stop.
 
SCNs occur in a monotonically increasing sequence. Oracle Database can use an SCN like a clock because an observed SCN indicates a logical point in time and repeated observations return equal or greater values. If one event has a lower SCN than another event, then it occurred at an earlier time with respect to the database. Several events may share the same SCN, which means that they occurred at the same time with respect to the database.
 
Every transaction has an SCN. For example, if a transaction updates a row, then the database records the SCN at which this update occurred. Other modifications in this transaction have the same SCN. When a transaction commits, the database records an SCN for this commit.
 
Oracle Database increments SCNs in the system global area (SGA). When a transaction modifies data, the database writes a new SCN to the undo data segment assigned to the transaction. The log writer process then writes the commit record of the transaction immediately to the online redo log. The commit record has the unique SCN of the transaction. Oracle Database also uses SCNs as part of its instance recovery and media recovery mechanisms.

**Comment by elindsey** [comment]
We may want to alter the mz_source_info logging source to encompass this - it has similar info today. Previously this was difficult as offset/ts bindings weren't stable across restart and different instantiations of the same source would have different bindings, but things are now significantly more sane after Ruchir's extensive reworking of the timestamper.

**Comment by frankmcsherry** [comment]
I had a proposal for this that I'm writing down so that folks can start to poke it. It doesn't have to be done this way, but one way is:

We create a new relation `mz_source_progress_idk` which contains at each `time` exactly the maximum offsets, parts, other ways to describe progress in a source, for each source. The intent would be that it continually evolves as the sources move forwards, continually retracting old offsets and introducing new offsets. You would be able to select out records by source, and you would get the continually evolving locations in that source that are reflected as of the time of the view. You could join these results with your results, or just look at them using the same time per a transaction. The result would then be a view that contains exactly query results and the locations through which they are certain to be current.

As an example, we might have a relation that looks like
```
id       | location (JSON because sources are different)
kafka_01 | { part: 0, offset: foo }
kafka_01 | { part: 2, offset: bar }
kafka_02 | { part: 0, offset 5 }
file_03  | { line: 41234 }
...
```
As time goes on, the contents of this relation would change; we might hear about `part: 1` for the first time, there might be a `part: 27` that shows up that was previously unknowable about, we might get other sources, idk. But ideally the collection would never "go backwards" for currently active sources.

**Comment by benesch** [comment]
Superseded by #11908.
