### ISSUE TITLE
More structured TAIL output

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3091]
`TAIL` currently outputs data in a semi-structured form. Given a differential triple like (data, time, diff), the data segment will be output with tabs between the columns, per the PostgreSQL COPY format, but the time and diff field are rendered human readable in their own column.

```
1	2	3	Diff: 1 at 0
```

This means tools that want to parse the diff and time field have to strip out the "Diff: " and "at" bit, which is rather silly.

The reason it works like this is historical, because `TAIL` was originally designed for demos to give folks a sense of the data that was flying past, not to be machine readable.

I think it's probably still possible to change the default output format of `TAIL`, if we so desire. We could also introduce an option to the `TAIL` statement to control this behavior.

/cc @rjnn @umanwizard @justinj

**Comment by justinj** [comment]
Related to #2767

**Comment by frankmcsherry** [comment]
Bouncing up to think about this with @cirego interest in improving TAIL.

I propose producing output structured like
```
TIME FIELD0 FIELD1 ... DIFF
```
sorted first by `TIME` and then by `Row`(perhaps the values of its fields, for readability) and then just whatever `DIFF` happens to be.

Reasoning: folks almost certainly want the data ordered by `time`, and it makes sense to have that be the first field for visual scanning of "which things happened together". The `diff` field doesn't make too much sense as a key (it is what it is; I imagine folks looking for specific changed data, rather than looking for the subtractions). Ordered second by `Row` has the appealing property that you can try and figure out what happened with a specific record more easily.

**Comment by frankmcsherry** [comment]
In addition #1600 is interested in a periodic reminder that time has passed with no changes. This is an important part of anyone actually using tail output without blocking on the last update waiting to be told that the changes are complete for that timestamp. We should consider some semantically meaningful punctuation in the tail output to provide this information.

**Comment by ruchirK** [comment]
> Ordered second by Row has the appealing property that you can try and figure out what happened with a specific record more easily. 

This is totally reasonable but I think this will have the property that some updates from (key, val1) -> (key, val2) will show up with the retraction first, then the insert and others will show up with the insert and then the retraction. I could see this tripping people up. Perhaps a longer term approach would surface all of the fields in a named way and let the user specify the ordering, like they would in a select query (maybe with the time ordering nonegotiable)?

so a user could say `TAIL foo ORDER by key_column, diff;` to get the structure they want

**Comment by cirego** [comment]
So, there are two issues here, as far as I am aware.

1. How to reasonably parse the output from `TAIL`. Seeing that columns is the variable length field but `TIME` and `DIFF` are required, I would prefer to see something like `TIME DIFF COLUMNS ...`.
2. How to know that you've observed all of the updates for a given `TIME`? By splitting the output of `TAIL` across multiple lines, users cannot know if they have read all of the updates for a `TIME`.  We need some method for indicating to the user that all rows for a given `TIME` have been read, so that the user can update their view based on the rows observed.

**Comment by quodlibetor** [comment]
The exact usefulness of COPY as it currently stands is kind of complex:

Most importantly, the [Postgres COPY format](https://www.postgresql.org/docs/9.3/protocol-flow.html#PROTOCOL-COPY) does embed row information inside of it -- the wire protocol is row-framed.

That said, research so far suggests that support for row-by-row access is not guaranteed. Of the  libraries that I've checked that expose the ability to actually stream one row at a time there are:
* the`libpq` C library (via [PQgetCopyData](https://www.postgresql.org/docs/13/libpq-copy.html#LIBPQ-COPY-RECEIVE))
* the Rust postgres library (via various methods and types on CopyOut, e.g. [`BinaryCopyOutIter`](https://docs.rs/postgres/0.17.5/postgres/binary_copy/struct.BinaryCopyOutIter.html))
* possibly the [`C#` npgsql](http://www.npgsql.org/doc/copy.html) library.

Other libraries, like `psycopg2` (copy-related methods start at [`copy_from`](https://www.psycopg.org/docs/cursor.html#cursor.copy_from)) and [`pg8000`](https://github.com/tlocke/pg8000#copy-from-and-to-a-file-1) for Python, `pgJDBC` ([`CopyManager`](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html) seems like the primary interface) don't appear to provide row access, just the ability to bulk copy into a stream.

Assuming that upstream libraries are amenable to it, it seems like one of the most important things that we can do to improve tail is to add support for or document row iteration in upstream libraries. This seems like a generally useful feature, and these libraries are well-maintained, so hopefully adding it where we cannot just document it is acheivable.

**Comment by umanwizard** [comment]
Sub-issues: #4539 and #4540 .
