### ISSUE TITLE
`SHOW CREATE VIEW` loses if user requested `MATERIALIZED`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#3404]
If you put in `CREATE MATERIALIZED VIEW...` the request to create indexes alongside the view gets purified away. Confusing UX for someone new to the product that hasn't yet learned "what is a view" and "what is an index".

There are > 0 possible solutions, including:
- `SHOW CREATE VIEW` also includes `SHOW CREATE INDEX` for all indexes on the view. This breaks the conceptual purity of `SHOW CREATE VIEW` but we're the ones who've atomized these components in such a way.
- If a primary index is created on the view or source (either naturally or #2614), we maintain/add the `MATERIALIZED` keyword in `SHOW CREATE VIEW`

**Comment by frankmcsherry** [comment]
Another option, not to be contrary, is that we should message `CREATE MATERIALIZED ...` as a shortcut for `CREATE ...; CREATE INDEX ON ...`, educate folks about this, and report it as working as intended. I think this is debt from adding the `MATERIALIZED` shortcut rather than keeping things orthogonal, which I'm sure has sailed at this point. I suspect we'll get more cases like this (e.g. duplication of docs, errors where we don't have parity, ...) and it may be worth thinking about the trade-off between clarity and cuteness.

**Comment by sploiselle** [comment]
Ah, I don't think that unexpected non-equivalence of input and output within our own system should be classified as "working as intended!" We like the people who use our software and want them to like us back.

@awang What do you think about this from a product perspective?

**Comment by awang** [comment]
Personally, I think:

(1) Defaults should be easy to use and make sense.  `CREATE MATERIALIZED VIEW` will be heavily used, so we should cater towards new users may just show up to Materialize who may never have read any of our docs, trumping strict correctness.

(2) To balance that tilt, I like allowing users who go outside the defaults and explicitly include any options get exactly what they want. Ie (just an example, not an actual proposal):
`CREATE MATERIALIZED VIEW...` includes the index, similar to what @sploiselle [describes in the first bullet](https://github.com/MaterializeInc/materialize/issues/3404#issue-640861495). Or it's an alias, as [Frank mentioned](https://github.com/MaterializeInc/materialize/issues/3404#issuecomment-645948337)) 

Having one SQL function be syntactic sugar for other functions should be a well-understood paradigm from other SQL databases.  Is there precedent in other SQL systems for having behavior change based on specific clauses?  I can go research if we're not sure.

**Comment by sploiselle** [comment]
My feeling is that materialization is spiritually equivalent to a primary key in an RDBMS, i.e. it speaks to the underlying physical structure you expect the object to persist.

MySQL maintains this information:

```sql
CREATE TABLE test.u (a INT NOT NULL PRIMARY KEY, b INT);
SHOW CREATE TABLE test.u;
+-------+---------------------------------+
| Table | Create Table                    |
+-------+---------------------------------+
| u     | CREATE TABLE `u` (
  `a` int(11) NOT NULL,
  `b` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+-------+---------------------------------+
```

CockroachDB does, as well:

```sql
CREATE TABLE u (a INT PRIMARY KEY, b INT);
SHOW CREATE TABLE u;
  table_name |               create_statement
+------------+-----------------------------------------------+
  u          | CREATE TABLE u (
             |     a INT8 NOT NULL,
             |     b INT8 NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (a ASC),
             |     FAMILY "primary" (a, b)
             | )
```

In an out-of-band convo, Frank brings up a good point that we should determine what the spec of this statement is or should be. Is it "show me how to get back to where I am?" or is it "you typed this in at some point?" I believe we can come up with a principled read of the spec, or at least thoughtfully reverse-engineering it.

However, I also believe that, in any case, losing the request (made unknowingly or not) to create indexes is going to be a footgun for users.

**Comment by benesch** [comment]
Quite honestly, I believe the problem here is that `SHOW CREATE VIEW` is a crappy MySQL-ism that's not very well thought out. `SHOW CREATE TABLE` in MySQL at least has the benefit that there is a syntax for including keys inline in the table definition; we have no such luck with views.
It's just _hard_ to display the SQL for a given database object that will recreate that database object exactly; in fact in the case of views it's strictly impossible, unless we invent some new syntax.

Check out how PostgreSQL handles this:

```sql
benesch=> create materialized view v as select 1 as a, 2 as b;
SELECT 1
benesch=> create index on v (a);
CREATE INDEX
benesch=> \d+ v
                               Materialized view "public.v"
 Column |  Type   | Collation | Nullable | Default | Storage | Stats target | Description 
--------+---------+-----------+----------+---------+---------+--------------+-------------
 a      | integer |           |          |         | plain   |              | 
 b      | integer |           |          |         | plain   |              | 
Indexes:
    "v_a_idx" btree (a)
View definition:
 SELECT 1 AS a,
    2 AS b;
Access method: heap
```

At no point does it try to show you exactly what to type to get that view back, but it does give you the query used to define the view, the indexes on that view, and the names and types of all columns in that view.

Unfortunately supporting `\d+` is still a long ways off, and certain users of Materialize really like being able to type `SHOW CREATE <thing>` because it's easier to remember than `\d+`. Not sure what the right answer is here. 🤷 Including indexes in the output of `SHOW CREATE VIEW` sounds reasonable, though has the small potential of breaking clients that expect just one row.

**Comment by morsapaes** [comment]
(Somehow ended up here.)

Now that materialized views are their own object type and users can brandish a `SHOW CREATE MATERIALIZED VIEW`, it looks like this issue can be closed. The remaining open item AFAIU is `\d+` support, so linking to #9721.

**Comment by benesch** [comment]
Never expected this issue to have a happy ending, but it sure did! Turns out the confusion was because we'd gotten the meaning of "materialized view" wrong. How funny.
