### ISSUE TITLE
Support websocket sources and sinks

### ISSUE THREAD

**Issue by domoritz** [MaterializeInc/materialize#3423]
I would love to have websocket sinks and sources in materialize.

The use case for sinks would be that I could directly connect a web frontend to materialize without an intermediate wrapper (or a Kafka broker).

Websocket sources could be useful to stream data directly from a browser to materialize. I understand that especially sinks will not support authentication but for some use cases (especially prototyping) this may not be an issue.

**Comment by awang** [comment]
Hi @domoritz !  Thanks for the feature request.  By the way, I also wanted to point out a semi-related issue for HTTP POST sources: https://github.com/MaterializeInc/materialize/issues/1701

Our current thought is that v1 will be push-based, but be append-only.  Would you have a strong preference for websockets instead of a HTTP webhook?

**Comment by domoritz** [comment]
Yes, very related. I think HTTP POST works well for sources. However, for sinks I would prefer WebSockets since they don't require constant polling from a client that does not support webhooks (browsers do not support webhooks, right?). 

My use case for sources is to use them to parameterized crossfilter queries (dynamically changing a parameter in the where clause) by joining with another source. I don't think append only would support this use case, though. Do you have a suggestion for how I could parameterize a query instead?

**Comment by cirego** [comment]
@domoritz do you want to send updates directly to the browser or would you be okay with having an intermediate webserver? For my last Skunkworks project, I put together a [proof of concept](https://github.com/cirego/skunkworks-20200717) that shows how to stream a Materialized View to the browser, using Tornado as the webserver. If Materialize supported POST webhooks, that would have simplified my project greatly.

If you want to expose Materialize directly, then I understand the use case for websockets.

As for your second question, I'll ask the team and see where we stand on creating dynamic views with a parameter.

**Comment by domoritz** [comment]
Hi @cirego, talking directly to materialize would be awesome but an intermediate webserver works as well (although it is not as elegant as you noted). Thanks for posting your code!

**Comment by cirego** [comment]
@domoritz Regarding your question on "parameterized views" -- the currently recommended way to do this is to create a [temporary view](https://materialize.io/docs/sql/create-view/#temporary-views) within the SQL session and then run TAIL on that. The view will be cleaned up once the connection is dropped. It's not yet clear how many temporary views we can support.

**Comment by cirego** [comment]
> Hi @cirego, talking directly to materialize would be awesome but an intermediate webserver works as well (although it is not as elegant as you noted). Thanks for posting your code!

Glad to hear that, even if it's not pretty, the webserver route solves the spirit of what you're looking for!

**Comment by domoritz** [comment]
> @domoritz Regarding your question on "parameterized views" -- the currently recommended way to do this is to create a temporary view within the SQL session and then run TAIL on that. The view will be cleaned up once the connection is dropped. It's not yet clear how many temporary views we can support.

With this approach, Materialize doesn't provide any benefit over say Postgres, right? I would have to create a view for every parameter. My use case is cross-filtering with continuous filters (something like https://github.com/uwdata/falcon) so there could be hundreds of queries per minute with very strict latency requirements.

**Comment by rjnn** [comment]
There definitely is a huge performance benefit over Postgres. I think that we've been imprecise on our side, and that's my fault, so let me restate a bit what you should do:

Assuming youre trying to create some parameterized view like so:
`CREATE MATERIALIZED VIEW p AS SELECT foo JOIN bar JOIN baz ... WHERE foo.user = '$1'`

And basically each connection comes in, and just like wants to fill in the value for the user (the `$1`), and `TAIL` a parameterized view.

What we recommend you do with Materialize is like so:

`CREATE MATERIALIZED VIEW unparameterized AS SELECT foo JOIN bar JOIN baz ... GROUP BY foo.user`

This you do, which causes Materialize to go and eagerly maintain the materialization incrementally, all sorted and ready for all the users.

Then, when a transient connection comes along that wants to tail a view for user `x`, you run:

```
CREATE TEMPORARY VIEW p_x AS SELECT * FROM unparameterized WHERE foo.user = x;
TAIL p_x
```

Materialize is clever enough to use all the work already pre-done in building `unparameterized`, since the work is all nicely grouped by `user` already. So even if you have hundreds of connections, each creating a `p_??` for a different user, they should all be fast.

Does that make sense? If it does, then we have some documentation work to do on our side to better explain it to everyone!

**Comment by domoritz** [comment]
Thanks for the follow-up. Your idea works really well for queries that are parameterized by an exact comparison with few parameters over streaming data.

However, for my application, I see three limitations. First, I don't have streaming data but rather the parameter itself can be thought of as the time-varying part of a query. Second, the data may be very large and so the parameterized view could be massive (especially if we have more than one possible group by field). Third, I need to also support range comparisons. For example, I might want to support

```sql
SELECT a, b, count(*)
FROM table
WHERE c > $1 AND c < $2 AND d > $1 AND d < $2
```

I realize that my use case is somewhat specific and not necessarily what Materialize is designed for so feel free to say that it is out of scope!

**Comment by cirego** [comment]
The dataset size limitation can be a concern, but there shouldn't be any problem with the parameters being time-varying or using range queries. Using `WHERE c > $1 AND c < $2 AND d > $1 AND d < $2`  on the temporary view should work as you expect!

**Comment by domoritz** [comment]
Yes, the where clause works but I don't see a way to precompute queries so that the range queries return in a few ms for large (million rows) datasets. I think a materialized view database system could also support fast parameterized queries but is probably out of scope for Materialize.

**Comment by mjibson** [comment]
I have a prototype of tail-over-websockets at https://github.com/mjibson/materialize/tree/websockets (not compiling at the moment). It currently needs some design work as detailed in the commit message. But when it was compiling (i.e., before I realized it had fundamental problems), it seemed to work great over websockets. I'm not currently planning on working on it more unless we decide to make it a real feature.

**Comment by awang** [comment]
What are the fundamental problems with the current prototype? 

We'd definitely love to make this real -- this isn't a top priority at the moment, but if a user has a real case they're interested in testing we'd be more than happy to accelerate the priority of this

**Comment by mjibson** [comment]
Two problems.

1. Figuring out how to correctly cleanup the TAIL once the client websocket disconnects. This currently happens based on the session disconnecting. Since there's no SQL session, there's no cleanup.
2. Correctly supporting more than 1 TAIL at a time for the fake "system session" thing. This probably relates to the above point.

Both of these probably need #5242 fixed first so we have some more correct handling of tail cleanup.

**Comment by krishmanoh2** [comment]
Will graphql with subscriptions do the same as above? If so, that may be a more industry standard method to consume updates.

**Comment by benesch** [comment]
> Will graphql with subscriptions do the same as above? If so, that may be a more industry standard method to consume updates.

GraphQL is a much larger project.

**Comment by wizzard0** [comment]
I vote for the websocket source. While the HTTP source is certainly convenient, the overhead of a HTTP request compared to a websocket message is huge (even without SSL).

**Comment by benesch** [comment]
Closing as completed! 🎉 

We've had a websocket API for a while now (https://materialize.com/docs/integrations/websocket-api/), over which you can submit any SQL command. Running `INSERT` statements over WebSockets gives you WebSocket sources, and running `SUBSCRIBE` over WebSockets gives you WebSocket sinks.
