### ISSUE TITLE
sql: invalid WITH options for Kafka connector are silently ignored

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3562]
`WITH` options that are ignored by our Kafka options extracted do not properly generate an error, as in:

```sql
CREATE SOURCE foo
FROM KAFKA BROKER '...' TOPIC '...' WITH (
    total_garbage = 'bad'
)
```

/cc @sploiselle

**Comment by antifuchs** [comment]
I just hit this and am gonna take a stab at it. The main complicating factor is probably that re-creating the sink from a saved schema will be problematic, but we can remain backwards-compatible, probably... or maybe make a migration that drops unknown fields on upgrade

**Comment by antifuchs** [comment]
Turns out this issue is already resolved! Source creation does now check for invalid options (they bubble up), and you can no longer pass `total_garbage`. The problem I ran into that made me think this issue was still in effect was that using "safe" mode throws an error that makes it appear as if an invalid option was considered valid.
