### ISSUE TITLE
Ability to manually control a compaction watermark

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#3636]
Background: To derive a target table based on Materialize's output CDC stream [of the schema](https://en.wikipedia.org/wiki/Temporal_database#Using_two_axes:_valid_time_and_transaction_time):

Name, Valid From, Valid Till

We need to add the ability for users to disable Materialize compaction.

In addition, customers would be interested understanding the impact on Materialize if compaction is disabled (ie, memory consumption increase).

Also related: #3792 : 
https://materializecommunity.slack.com/archives/C015KDVS7EV/p1596063055258200

**Comment by rjnn** [comment]
To add to Albert's background, (and perform a slight renaming)

Users are interested in Materialize maintaining histories of values for rows, in a way that they can manually control. This is because they want to create `AS OF t` sinks going back to some specific point in time, and be guaranteed that the sink will output _every_ change from time `t` onwards. Currently, compaction happens automagically, which means that when you get around to creating a sink, you don't really have control over what the allowed set of valid times `t` are.

The relevant product to follow here is, I believe, Postgres. Postgres allows for `SELECT ___ AS OF TIMESTAMP ___` queries, and how far back in time you can go is controlled by a process known as "vacuuming". Unfortunately, Postgres autovacuum is fairly annoying, and configured "out of band". We should configure vacuuming "in band", i.e., in the `WITH` options during view and source creation. Vacuum should be allowed to lag realtime, or be set to a constant (e.g. zero).

**Comment by frankmcsherry** [comment]
For anyone who wants to pick this up, the coordinator has a method
```rust
        pub fn set_compaction_latency(&mut self, latency_ms: Option<T>) {
            self.compaction_latency_ms = latency_ms;
        }
```
available on the `Frontiers` struct that allows one to specify a lag, or use `None` to indicate that no compaction should be applied. I think it just needs to be wired to some front-end language items.

**Comment by frankmcsherry** [comment]
Also observed a bit late, the `--logical-compaction-window` command line argument allows you to specify a duration or `off` and this sets the system-wide (except for logging) lag behind committed times that logical compaction will occur. Setting it to `off` would disable compaction system-wide (this is not ideal for careful use, but might be appropriate for testing out performance and potentially some use cases).

**Comment by awang** [comment]
`--logical-compaction-window` looks like it should work! Can we get it documented?

**Comment by ruchirK** [comment]
is anyone actively working on this? @benesch maybe you would know? if not I can put this together fairly quickly I think?

**Comment by frankmcsherry** [comment]
I don't think anyone is, but can we get a spec first? There are a few proposals, and it is a subtle thing to drive around.

**Comment by ruchirK** [comment]
Ok! I understood this to be exactly like the logical compaction window command line argument does, for materialized sources and views, where the user sets it as a with option on source and view creation. does that roughly line up with what you expected?

if so, I'll try to create a draft pr where I implement just for materialized views and we can see how that seems to work? if not, i can definitely write up a more detailed spec

**Comment by frankmcsherry** [comment]
So for example it seems maybe cleaner as part of `ALTER INDEX`. There was also some discussion about whether it should be a lagging time, or the option of a lagging or fixed time (or none).

**Comment by ruchirK** [comment]
got it -- I misunderstood the situation here and thought that we had agreed on the implementation proposed here https://github.com/MaterializeInc/materialize/issues/3636#issuecomment-661857097 but that seems to not be the case

**Comment by frankmcsherry** [comment]
No, I think that was meant to be a quick fix before it was realized that there was the command line argument. It might also be the fix, but wiring it up to `ALTER INDEX` instead of `CREATE MATERIALIZED ..` may make more sense.

**Comment by ruchirK** [comment]
👍 👍

**Comment by benesch** [comment]
PostgreSQL has a nice syntax for this:

```
CREATE INDEX foo ON bar WITH (logical_compaction_window = '10s');
ALTER INDEX foo ON bar SET (logical_compaction_window = '10s');
ALTER INDEX foo ON bar RESET (logical_compaction_window);
```

https://www.postgresql.org/docs/current/sql-createindex.html
