### ISSUE TITLE
ci: upsert streaming test is flaky

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3719]
https://buildkite.com/materialize/tests/builds/9705#337846b2-d6dd-4141-98d5-05d38c5d4087

It's failed a couple times that I've noticed—looks like the Kafka state isn't getting cleared?

**Comment by ruchirK** [comment]
👀

**Comment by ruchirK** [comment]
I'm unable to repro locally and I don't think we are getting the logs back properly from BK so I pushed a commit that hopefully fixes that and will retry until test fails.

The actual ci workflow looks identical to the one in the billing demo more or less and I confirmed that in agents where its failed, it had also succeeded a couple of times beforehand. Overall, nothing obvious jumps out at me.

**Comment by benesch** [comment]
I think we caught some logs from a failed run! https://buildkite.com/materialize/tests/builds/9736#f14fcf6c-1997-47b9-8280-0cb7b624c1f2

**Comment by ruchirK** [comment]
So the log snippet points to race between:

the async callback on the broker to create a topic
and message production to the topic (which triggers topic creation because auto.create.topics defaults to true)

I've pushed a pr to disable the auto create flag, but the race condition is still present as far as I can tell. I'm not sure if this is now benign because the broker will retry the produce request or if we should have a more robust guard for the topic being created before we try to produce messages to it? Alternative take, we keep retrying on topic doesnt exist errors for a bounded amount of time?

**Comment by quodlibetor** [comment]
> Alternative take, we keep retrying on topic doesnt exist errors for a bounded amount of time?

This seems reasonable to me! It's a standard strategy, too, so it doesn't feel like we're doing anything wrong by doing that.

**Comment by benesch** [comment]
Testdrive has robust logic for creating a topic and waiting for its
creation to propagate. Personally I’d factor that logic out into the new
test util crate and start using it in the various load tests.

**Comment by ruchirK** [comment]
Ok I'll take a look at that!
