### ISSUE TITLE
Cache reads from Kafka

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#3791]
We currently allow users to both create and instantiate multiple copies of the same Kafka source. Each distinct source in each dataflow will independently read from Kafka. This makes sense as the dataflow are starting up, as they may be decoupled and reading very different offsets in topics. However, once each dataflow reaches the "tip" of the stream it seems reasonable that Materialize should only pull offsets from Kafka once, independent of the number of source and dataflows that might be interested.

**Comment by benesch** [comment]
This was largely fixed with the transition to platform. Reading from a source in multiple dataflows now instantiates multiple `persist_source`s, rather than multiple Kafka sources. We might want to optimize that someday, but it's 

#7838 is still tracking a related issue, where a cluster with multiple Kafka sources will instantiate more librdkafka instances than ideal.
