### ISSUE TITLE
Sources should be consistent-by-default

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#3793]
Sources in Materialize are currently only consistent if they are BYO sources, or they are re-used in the same dataflow. This can be surprising if a source is re-used across multiple dataflows, whose results are then compared or integrated in another dataflow, as the results no longer represent a consistent view of the input data.

This most likely involves sharing the association of timestamps and offsets made by the RT timestamping logic, which could be as simple as a worker-local share (it needn't go by way of the coordinator, if that simplifies anything).

**Comment by benesch** [comment]
Back in the day, real-time timestamping would write down the timestamps that it used, so that if you turned Materialize off and back on again, the timestamps from the first instance would still apply. That way `SELECT * FROM v` run twice could never go backwards, even if Materialize got turned off and turned back on.

It would be really nice from a UX perspective to recover this behavior somehow, and this behavior has been explicitly requested by a prospect.

**Comment by frankmcsherry** [comment]
To record some discussion that followed. One candidate fix of minimal fidelity is to rely on the maximum offset for each part of a topic monotonically advancing, and the system's `now()` method monotonically advancing (across restarts, perhaps we have to do something silly like write it down), and when creating a new RT source, to first determine all offsets for each part, and assign all records up to those offsets the time `now()`. Probably, we should also create the source with `as_of` of `now()` to indicate that queries earlier than this time "don't make sense".

**Comment by ruchirK** [comment]
I'm working on this to support #2915. #5691 moved sources around so source instances that are responsible for a particular source / partition are all colocated on the same worker, #5685 makes it so that we timestamp byo sources once per source (to be clear, byo sources already have consistent timestamps this is just about making the code more sane.

My next step on this front is to move the timestamp selecting logic out of individual source reading operators' closures and into worker local state. I agree that having a declared as of / compacting away old timestamp bindings / persisting timestamp bindings will all be important I'm not 100% set on how I want to achieve that yet. Specifically I think with exactly once sinks we are going to need to wait to compact old timestamp bindings until the sink has written the timestamp to kafka, but the sink is not guaranteed to be colocated on the same worker as the source (a sink could depend on multiple sources) so I'm not sure where that leaves me. It feels like I want something morally equivalent to a capability, but shareable across threads.

**Comment by frankmcsherry** [comment]
It could be like a capability, but one degree of freedom I think you have is that there is not necessarily a latency requirement to compact this information. Ideally we learn about it from the sinks quickly, but as there could be some random guff in the way (downstream apps needing to ack idk) it is not unreasonable to ask the coordinator to provide this information. That wouldn't be the lowest possible latency, but it would 100% show up in the "log" of what the workers have been asked to do, which seems sane.

**Comment by frankmcsherry** [comment]
A different take: compacting source timestamps downgrades a `SOURCE`'s "as of" capability, and this is something the coordinator should control not the workers.

**Comment by ruchirK** [comment]
I'm setting it up so that the relevant RT worker picks the timestamps. can definitely wire things up so that sinks / other things tell the coordinator what timestamp and the coordinator tells the worker what timestamper to compact up to - it just seems like a lot of communication? (you did say its not lowest latency)

I think theres at least two relevant parties here -- sinks and the various source instances.

If we have timestamp bindings like

[offset1, offset2) -> t1
[offset2, offset3) -> t2
[offset3, offset4) -> t3
[offset4, _ ) -> t4 // this is currently in progress 

And now let's say a sink is in the process of committing t3, and a different source instance is reading the offsets bound to t2, then I think the best compaction we can do at the moment is remove t1 

I suppose we could relax things a bit and say "when the coordinator tells us to compact up to `as_of`, we'll compact up to min(as_of, timestamp of laggiest current source instance)` -- the lack of latency constraints applies everywhere. if the coordinator believes we have data as_of t3 its totally fine to actually have data as of t2 for a while

**Comment by ruchirK** [comment]
yeah I was worried about having the various source instances tell the coordinator "I'm reading t_x now!" and the coordinator reacting to every such read with "ok now compact blah!" but I think its ok if the coordinator doesn't know about the different source instances' read positions but tells the source what to set as_of to, and then the dataflow worker gets around to doing the compaction lazily. does that seem roughly sane?

**Comment by frankmcsherry** [comment]
Another party is the coordinator and the  various sessions that might want to start using the source, and need clarity on from when its timestamps are correct. That's why it feels like the coordinator might want to drive the downgrading of the source timestamp history.

**Comment by ruchirK** [comment]
Sorry, I should have been more clear. I 100% agree that having the coordinator drive around a source's as_of makes sense. My last two messages were only trying to workshop what doing that might look like. I think that broadly, a solution where the coordinator tells the source "this is your new as_of time" but the source has some wiggle room for when it actually goes and physically compacts the timestamp bindings makes sense and is doable.

**Comment by ruchirK** [comment]
this is covered by #6532
