### ISSUE TITLE
Support running as a WASM

### ISSUE THREAD

**Issue by timcash** [MaterializeInc/materialize#3885]
Would it be possible to run this as WASM inside something like Wasmer?
https://wasmer.io/

**Comment by benesch** [comment]
Such a thing is possible in theory, though I doubt it would work out of the box—at the very least it wouldn't be _useful_ out of the box, since you're not going to have networking/filesystem APIs available to hook Materialize up to its built-in Kafka or file sources.

I think making Materialize work under WASM is unlikely to be a priority for us, but could you say more about your use case?

**Comment by timcash** [comment]
WASM can run from inside another application. E.g. node js, the browser, and anything that follows WASI in every case WASM is designed to hook into IO from the host application. This would allow me to embed Materialize in the browser for example and use it for managing my application state. E.g. feed it an event log from a websocket have it calculate deltas and report that back the the UI.

**Comment by benesch** [comment]
Gotcha. I don't think you'd actually want Materialize for that. Have a look at the underlying compute framework, [differential-dataflow](https://github.com/TimelyDataflow/differential-dataflow), which is open source and well documented. It'll be much, much easier to compile Differential to WASM then it will be to compile Materialize to WASM, and if all you're trying to do is write some incremental dataflow programs in the browser, Differential is a much better fit than Materialize.

Timely/Differential make heavy use of threads, so there might be some hiccups there, but with sufficient dedication I'll bet you could get it to work.
