### ISSUE TITLE
Make source persistence work correctly with compacted kafka topics

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4024]
Currently, source persistence assumes that source topics will have infinite retention, and so it looks for dense prefixes of offsets, meaning that it won't persist data from an offset x unless it knows it has seen information for all of the offsets less than x (but greater than or equal to zero)

This approach doesn't work when kafka topics are key-value compacted (see here: http://cloudurable.com/blog/kafka-architecture-log-compaction/index.html ) for a rough explanation. Basically, the kafka log cleaner can discard data at some offset if it determines that at a later time, there was an insert to the same key. Now when we read the topic after compaction, instead of observing offsets ... (offset - 1), (offset), (offset + 1) there will be a gap, and we will observe data from ... (offset - 1), (offset + 1) ...

This breaks the current implementation which first grabs all data that has been currently received, sorts and deduplicates by offsets, and then does a linear scan to find out how many consecutive offsets do we now know about since the last persisted offset.

The fix here is to report ranges of offsets potentially like (prev, current] -- which we could store as `(Option<i64>, <i64>)` and now look for consecutive / contiguous ranges. We know the previous offset seen because consumers receive offsets in order. 
 Since we know that once an offset has been compacted it can never be uncompacted, that means that over time ranges will only grow larger, so we can assign a total order to ranges and only keep the largest ones in case we have two dataflows reading a source and racing with the compaction thread. There's a few more small wrinkles here around restart that we will have to think carefully through, but roughly, speaking, this is the strategy that makes the most sense to me.

**Comment by ruchirK** [comment]
as part of this -- lets also fix the fact that the start / end offsets in filenames are off by one (possibly because mzoffset is 1-indexed)

**Comment by justinj** [comment]
A couple questions about this:

* "We know the previous offset seen because consumers receive offsets in order," if this is true I still don't really understand why we have to go through the whole deal of sorting and finding a prefix in the persister? I think I've asked about this before but it's not really clear to me where we rely on what guarantees
* Re: "ranges of offsets," I don't really understand this bit, is the idea that `(prev, current]` means "for the key pointed to by offset `current`, the most recent offset which also pointed at that key was offset `prev`?" I think I'm misunderstanding because it seems to me like you would need to track _every_ prior offset for a given key to make sure you remember which ones you've already seen?

**Comment by ruchirK** [comment]
* one individual kafka consumer for a given topic and partition receives offsets from that partition in order. however, we don't want to add a builtin assumption that the consumer(s) will tell the persister about offsets in order because

-- there might be multiple consumers reading from the same source (if you define multiple materialized views over the same materialized source for example)
-- it locks us in to a design choice of synchronously sending stuff to the persister? we currently do all of that with synchronous writes to a FIFO queue but we might want to move to asynchronous writes in the future.

* Not quite. What I mean is that we might ingest a topic with some data like

(offset, (key, value))

(1, (k1, x))
(2, (k1, y))
(4, (k2, z))

the precise keys and values don't matter. the point is that the data at offset 3 has been deleted by the kafka log compacter.

Now when the consumer ingests offset 4-- it knows that the offset it previously ingested was 2, so this read covers the interval between (2, 4] and it can tell that to the persister thread, which then won't have to block persistence waiting on data @ offset 3 that will never come

**Comment by justinj** [comment]
Here is my understanding based on some slack conversations, can you confirm this is correct?

The idea is that the Kafka topic can choose to compact certain offsets (the semantics of which are immaterial for our purposes right now, I think). As a consumer, we are guaranteed we will see every message in order, however, we don't want to enforce total ordering in the interface between the Materialize consumers and the persister, so we construct a kind of linked list with each message referring to the one prior, rather than implicitly assuming that the predecessor of the message with offset `x` is the message with offset `x-1`.

**Comment by ruchirK** [comment]
yeah that sounds right to me!

**Comment by andrioni** [comment]
I know the PR fixing it has already been opened, but I just wanted to share that [non-consecutive offsets can apparently happen even on non-compacted topics](https://twitter.com/criccomini/status/1299031453880090624).
