### ISSUE TITLE
Detailed observability on materialized result freshness

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#4104]
Currently it is not straightforward (and for many source types it is impossible) to determine whether materialized is up to date with the current data.

There are various senses of up to date that could be useful, in increasing order of strictness:

1. [ ] Processed the same number of messages as some other (possibly expired) materialized
2. [ ] Processed as many messages as there were in a source when materialized turned on
3. [x] Is keeping up with a source.
4. [ ] View results are strictly at least as current as the source -- this requires knowing that a dataflow has no data remaining to process

Currently we only track (3), and only for Kafka or Kinesis sources. Different sources have different limitations in terms of what it is possible for us to observe, but we should make it easy for folks to know how stale their mz queries are likely to be.

**Comment by andrioni** [comment]
On 3., is there a way to track this without going through Prometheus metrics? I didn't see the Kafka offsets in the `mz` views, but I might have missed it.

**Comment by quodlibetor** [comment]
Currently the only way to view this is via the prometheus metrics, but there are several improvements we should make, in no particular order:

* add file sources (and possibly other source types -- I think we're only tracking kafka and kinesis right now) to the prometheus metrics 
* Put each external source in a system table like `mz_source_data` or `mz_source_info` that has at least its name and current "amount behind"
* update the `/status` endpoint to include information about whether materialized is behind, and also to return a different response code if it is behind on any source

**Comment by cuongdo** [comment]
@quodlibetor @elindsey What is the plan for resolving this issue? How will this information be exposed to the user?

**Comment by elindsey** [comment]
Scope of this task is adding existing source metrics to a new system table.

We already calculate appropriate metrics for all sources, including files (partition offset received/ingested, though no max because there's not a straightforward way of knowing that), so there's no work that needs to be done on the metrics themselves.

Chatting with Alessandro, exposing these in a new system table is the most immediately useful. Exposing these via /status is lower priority, and I think there'd need to be some more discussion around whether or not we want to change healthcheck results based on consumer lag - likely that would need to be configurable. I'll break /status out into its own tracking task separate from this one so things don't get muddled.

**Comment by awang** [comment]
@quodlibetor does the current version meet your requirements -- ie, can i close this out?

**Comment by elindsey** [comment]
I think this task has outlived its usefulness, so I'm going to close it out.
With respect to the original four points: 1 is covered by recent work strengthening linearizability guarantees, 2/3/4 are addressed to varying degrees by #7142 which Nicolle has scoped to a concrete proposal (see https://github.com/MaterializeInc/materialize/issues/7142#issuecomment-873198806 in particular)
