### ISSUE TITLE
Materialize returns wrong date when using prepared statement multiple times

### ISSUE THREAD

**Issue by damienhollis** [MaterializeInc/materialize#4117]
### What version of Materialize are you using?

```
$ materialized -v

```
materialized v0.5.0-dev (b58133f48a2458e8298d169b13fd74cf968ca668)

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [x] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?
When running a query using a prepared statement that returns a timestamp, on the 6th iteration of the query (and all following iterations), the timestamp `2000-01-01 00:00:00` is returned instead of the expected timestamp. 

Note: I have reproduced the issue using a materialize table in the attached zip file but I initially came across this using a materialized view.
[materialize-prepared-statement-issue.zip](https://github.com/MaterializeInc/materialize/files/5152804/materialize-prepared-statement-issue.zip)

### Is the issue reproducible? If so, please provide reproduction instructions.
Yes, see attached zip file. 

### Please attach any applicable log files.
No logs were produced.

**Comment by mjibson** [comment]
I have a repro of this. Investigating.

**Comment by mjibson** [comment]
This is happening because of something related to binary encoding of dates. Here's a smaller repro:

```
import java.sql.*;

public class Main {
  public static void main(String[] args) throws SQLException, ClassNotFoundException {
    Class.forName("org.postgresql.jdbc.PgConnection");
    String url = "jdbc:postgresql://localhost:6875/materialize";
    Connection conn = DriverManager.getConnection(url);
    conn.unwrap(org.postgresql.jdbc.PgConnection.class).setForceBinary(true);

    PreparedStatement st = conn.prepareStatement("SELECT '2010-01-02'::timestamp");
    ResultSet rs = st.executeQuery();
    while (rs.next()) {
      System.out.println(rs.getDate(1));
    }
    rs.close();
    st.close();
    conn.close();
  }
}
```

When connecting to postgres it prints:

```
2010-01-02
```

And mz:

```
2000-01-01
```

The interesting line above there is the `setForceBinary` which forces mz to return results using the binary encoding. Comparison to postgres showed that the bytes coming back are identical, so I think mz is doing the encoding correctly and there must be some other effect going on. For example maybe a session var that postgres sends back during connection start that mz doesn't. I taught mz about integer_datetimes, but that didn't seem to make a difference. I'll keep looking.

I found this by doing wireshark analysis of the packets and noticed that after 5 (no idea why) statements on the empty statement, jdbc starts using named statements and requests binary results. I'm not familiar with pgjdbc enough to know why that is happening, but it's within the spec.

**Comment by mjibson** [comment]
Ah! It was `integer_datetimes`, but I missed sending it initially. Fix incoming.
