### ISSUE TITLE
Reduce memory used for Debezium message deduplication

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#4172]
To properly handle duplicate Debezium messages, we store state for every Debezium message we've received. In one Materialize deployment, this deduplication state is responsible for ~20-25% of their memory use. We should reduce the amount of memory used to a much lower percentage.

cc @umanwizard

**Comment by quodlibetor** [comment]
## The Plan

We've now got buy-in on a plan that will allow us to get down to constant (extremely small) overhead memory usage outside of known windows where we _must_ track bad data. The overall plan is to have three modes of operation:

* Optimal: don't track any additional per-message state. In this mode we trust that Debezium never sends *new* messages that are behind the newest message ever seen for a binlog.
* Time-Constrained Tracking: users can specify that within a specific wall-clock interval (e.g. between January 1st 8am 2020 and February 14th 2pm 2020) they expect that their Debezium may have duplicate messages that are behind the debezium frontier.
* Full Tracking: we track state for every message, guaranteeing that we send only new messages through to the dataflow layer.

In both of the tracking modes we will emit enough diagnostic information to ensure that the same non-duplicate messages are pushed through to the dataflow layer.

We will need to add a bit of padding to the time windows on the time-constrained padding to ensure that messages aren't falsely marked as non-duplicates. This should be user-configurable but I believe that the expectation is that 1 hour would be enough extra to be overwhelmingly unlikely to allow any false negatives. As mentioned, there will be enough diagnostic info in the logs that we should be able to verify that exactly the same messages are accepted.

### Expected Usage

If users report seeing duplicate data in a Materialize dataflow we should tell them to turn on full-tracking mode, which will provide them with enough information to enable windowed full-tracking.

## Implementation

Last week I merged #4422 which causes materialize to only emit warn-level logs when we see a Kafka message that violates the Debezium "expected behavior" of only duplicate messages being sent behind the frontier. That's a bit confusing, so see [this comment](https://github.com/quodlibetor/materialize/blob/642f79289049f6716c6a8f3ae94234064b566eb3/src/interchange/src/avro.rs#L1111-L1138) for an explanation with examples.

That PR doesn't produce enough information for customers to be able to provide a wall-clock time window, nor do we have enough info to be able to turn-on and off duplicate detection, so I'm currently working on threading the timestamp that Debezium or Kafka reports as the message creation time through to our "should we skip it" logic.

After that is done I'll be able to work on the actual "skip in window" syntax and logic.

## Other (possibly future) Alternatives

### Rolling Window of full tracking

If we keep observe the last N minutes of Debezium data around to do deduplication it is possible to keep a constant (memory + cpu) overhead. The largest issue with this is that the exact size of window to use is probably dependent on the deployment.

It is also more complex to implement, and the constant overhead is unfortunate.

### A fancier full-tracking data structure

If we expect that all Debezium-supplied binlog positions have a very well-defined structure -- specifically if binlogs should be continuous in general -- then tracking holes in binlogs or using a interval-merging tree would allow us to track precisely with very low memory overhead.
