### ISSUE TITLE
sql: table column defaults

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#4264]
SQL permits specifying the default value for a column when inserting data if no value is explicitly provided (see #3913). This should be relatively straightforward to support.

```sql
CREATE TABLE t (a int DEFAULT 42)
```

**Comment by petrosagg** [comment]
I started looking at default values now that omitted nullable columns are handled correctly but none of the solutions I could think of looks great.

In general, I think we need to augment the `repr::ColumnType` struct with optional default value information. A default value isn't just a literal so augmenting it with a `Row` or a `Datum` isn't going to cover cases like `DEFAULT CURRENT TIMESTAMP`.

In order to hold any expression (with some restrictions like it can't reference other columns etc), we could add an `Option<sql_parser::ast::Expr>` field. This is the same type included in the `ColumnOption::Default` variant. Unfortunately this introduces a dependency cycle that I'm not sure if can be resolved:

```
error: cyclic package dependency: package `repr v0.1.0 (/home/petrosagg/projects/materialize/src/repr)` depends on itself. Cycle:
package `repr v0.1.0 (/home/petrosagg/projects/materialize/src/repr)`
    ... which is depended on by `sql-parser v0.1.0 (/home/petrosagg/projects/materialize/src/sql-parser)`
    ... which is depended on by `repr v0.1.0 (/home/petrosagg/projects/materialize/src/repr)`
    ... which is depended on by `expr v0.1.0 (/home/petrosagg/projects/materialize/src/expr)`
    ... which is depended on by `dataflow-types v0.1.0 (/home/petrosagg/projects/materialize/src/dataflow-types)`
    ... which is depended on by `dataflow v0.1.0 (/home/petrosagg/projects/materialize/src/dataflow)`
    ... which is depended on by `coord v0.1.0 (/home/petrosagg/projects/materialize/src/coord)`
```

Alternatively, for each column we could be storing an `Option<String>` containing the original text provided by the user. This leaves a lot of ergonomics on the table as all users will have to invoke the appropriate parsing routines to convert into an `Expr`. Maybe we can provide an `Expr::try_from_column_default(c: ColumnType) -> Option<Expr>` implementation downstream to help with that.

That said, the latter is the approach taken by PostgreSQL. Here is the `AttrDefault` struct holding the original default string: https://github.com/postgres/postgres/blob/REL_13_1/src/include/access/tupdesc.h#L25

I'd love to get some feedback and nudging in the right direction for this.

**Comment by benesch** [comment]
Thanks very much for all your hard work here so far, @petrosagg! I have an alternate proposal that should make your life easier. It goes something like this:

  * Add a `table_details(&self) -> Option<Vec<ScalarExpr>>` method to the `sql::catalog::CatalogItem` trait that returns the list of default expressions for the columns in the catalog item, if the catalog item is a table. The inspiration for this method is the [`CatalogItem::index_details`](https://mtrlz.dev/api/rust/sql/catalog/trait.CatalogItem.html#tymethod.index_details) method.

  * Add a `defaults: Vec<ScalarExpr>` field to `coord::catalog::Table` that stores the defaults for a table. You'll need to make some similar modifications to the equivalent type in the SQL crate.
  * Populate the `defaults` field in `handle_create_table`. If a default is not explicitly specified, the default is `Expr::Value(Value::Null)`. If it _is_ specified, you'll want to "lower" the `sql::ast::Expr` to an `expr::ScalarExpr`. The code to lower a default expression will look nearly identical to `plan_index_exprs`, except that you'll want to call `plan_expr` instead of `plan_expr_or_col_index`, and you won't want to put any columns in scope. (Index expressions can refer to columns in the indexed relation, while table default expressions cannot refer to any columns in the table.)

  * Pull the defaults for the table out of `table_details` out in `handle_insert_query`, and inject them as appropriate.

The insight here is that a default is not really part of the _type_ (as in `ColumnType`); it's an attribute that can only be attached to a column of a table. Not modifying `ColumnType` will greatly reduce the scope of the change. :) 

Let me know if you have any questions. I'd be happy to hop on a video call if you'd like!

**Comment by petrosagg** [comment]
That's indeed a lot less tangled, thanks @benesch! I took a quick look at the code and I think I understand how to proceed.

In terms of handling the default expression, I don't think `plan_expr` is enough as I need to check that there are no column expressions anywhere in the AST. Do I understand it correctly?

Also, looking at `plan_expr_or_col_index` it looks like it accepts statements in the form of `CREATE INDEX ON t (1)` as an index referring to the first column of `t`. However I don't see any tests handling this case and it's not valid SQL syntax on PostgreSQL. Is this a bug or some other SQL dialect?

**Comment by petrosagg** [comment]
Ah, I found your PR adding ordinal referencing to support anonymous columns (#1886), that makes sense. I shouldn't be posting comments right before bedtime :sweat_smile: 

Relating to this, what is the policy on deviating on SQL syntax? Cause another way this could have gone is to force the users to name columns and have anonymous ones only as an internal nicety.

**Comment by benesch** [comment]
> Relating to this, what is the policy on deviating on SQL syntax? Cause another way this could have gone is to force the users to name columns and have anonymous ones only as an internal nicety.

Yeah, it's quite possible that allowing anonymous columns was a mistake. Unfortunately we're kind of stuck with that decision now, as there are existing Materialize clusters with views that have unnamed columns. 

In general _extensions_ to PostgreSQL are ok with good reason. Deviations from PostgreSQL are usually a bug, but a permissible with _very_ good reason. (Decimal types, for example, are very different in Materialize than PostgreSQL to unlock extra performance from our underlying compute framework.) Though empirically many things that look like extensions on the surface are actually deviations: there are many SQL features that interact in myriad terrible ways that are not immediately clear.
