### ISSUE TITLE
Ability to evaluate functions with catalog context

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4289]
Right now, we have two places where functions can be evaluated:
1. In `plan_function`, where we have access to the Catalog, but we don't have access to row Datums.
2. In `eval`, where we have access to row Datums, but we don't have access to the Catalog.

Implementing `pg_catalog` requires that we are able to evaluate functions with access to the Catalog and the row Datums simultaneously. To illustrate, `pg_catalog.pg_table_is_visible` returns whether or not a given table is visible in the current schema search path. To calculate the result, we need to check if a provided OID is contained in the Catalog. Currently, this is impossible.

**Comment by benesch** [comment]
Spent some time thinking about this, and there are basically only two ways to solve this that are feasible in our time frame.

Option 1 is to deep copy the catalog on every query and stuff it in the eval context so that it is sent over to the workers when the dataflow is built. This is going to have terrible performance characteristics and is only going to work for one-shot queries—materialized views that use these functions won't ever see the catalog updates. But it is an escape hatch we have available if necessary.

Option 2 is to plan these functions as subselects on top of other pg_catalog views. This is by far my preferred option, since we'll get streaming updates "for free" thanks to all the work you did in #913! Here's how Cockroach implements `pg_table_is_visible` in terms of `pg_class` and `pg_namespace`, for example:

https://github.com/cockroachdb/cockroach/blob/f2056ba8cde1d969b3170b513c974a74b5a2ddbd/pkg/sql/sem/builtins/pg_builtins.go#L1067-L1068

If that makes sense, I can help you tomorrow with creating a new type of function whose definition is a SQL fragment! Prerequisites include implementing `pg_class` and `pg_namespace`, plus sorting out our OID situation for catalog objects.

**Comment by benesch** [comment]
Option 2 got implemented as part of df4b7f1292e911d1d3e3b40fbfff2a6c27ffe844 and fea60ab230bc13158bc5d8d4738524c8a85f9b52, so going to call this solved enough for now!
