### ISSUE TITLE
WARN mz_avro::schema: using deprecated debezium date format

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4442]
I'm getting these warning messages when running chbench, not sure if this is something to be concerned about or not.

**Comment by cuongdo** [comment]
I remember seeing this in the past. It didn't affect anything for load tests, but it's worth looking at whether this only affects chbench or if it affects other workloads.

**Comment by benesch** [comment]
This is explained here: https://debezium.io/documentation/reference/1.3/connectors/mysql.html#_temporal_values

It simply means that you (we) have set the `time.precision.mode` for the Debezium connector to `connect`, which can result in imprecise dates due to infidelity in the MySQL -> Kafka Connect conversion. It's deprecated on Debezium's end, not ours. The new default is `adaptive_time_microseconds`, which I believe we support, but have not yet updated chbench to use.

The fix is probably as simple as just deleting the `time.precision.mode` configuration from wherever it appears.

**Comment by benesch** [comment]
Closing per above.
