### ISSUE TITLE
v2 TAIL

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#4500]
v2 (now): 
1. Upgrade TAIL to support machine-readable output (not just human-readable)
2. 
   2a. Figure out how to get client library support for TAIL:  (In particular, we care about https://www.npgsql.org/). I think the easiest solution is to stream before/after events like debezium/CDCv2 via a callback
   2b. Related, but distinct issue: [npgsql (.NET) throws some `pg_catalog` errors, related to `pg_type` and `pg_description`](https://github.com/MaterializeInc/materialize/issues/4518)

v3 (later): grpc endpoint to stream changes

GRPC with protobuf more efficient. Nice programming experience.  Http/2 with encoding formats inside it

cc @quodlibetor (feel free to update this card to add/edit details, i need to come back to this card and take another more detailed pass)

Most DBs have a way to stream changes we can use as a reference.  Postgres has LISTEN/NOTIFY, [RethinkDB](https://rethinkdb.com/docs/changefeeds/javascript/) and Azure [CosmosDB](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed) have changefeeds. CosmosDB's has rich functionality but is also quite complex.

**Comment by benesch** [comment]
So this issue is proposing a specific technical solution to a product question that isn't described here. Could you say more about what issue this is trying to solve?

I agree that making TAIL/changefeeds more widely usable is important, but I don't think that GRPC is necessarily the right choice as the transport layer, nor do I think that protobuf is necessarily the right choice for the encoding.

Anyway, this is an XL-sized task, and it doesn't seem to me like it belongs in v0.6? I think the most realistic target is getting the design work done for this.

**Comment by awang** [comment]
Yeah, this card is missing a lot of details at the moment unfortunately.  I'll try to add an internal card later today that should hopefully provide you with the context you need.  In the meantime, you can find our raw notes here:  https://docs.google.com/document/d/1WD6jwAJizVMQhKxG3WY6bDKs_1Qn8-vok7Z60-LjHWA/edit#heading=h.axogqbsywyb5

**Comment by awang** [comment]
Yeah, this card is missing a lot of details at the moment unfortunately. I'll try to add an internal card later today that should hopefully provide you with the context you need. In the meantime, you can find our raw notes here: https://docs.google.com/document/d/1WD6jwAJizVMQhKxG3WY6bDKs_1Qn8-vok7Z60-LjHWA/edit#heading=h.axogqbsywyb5

I'll let @quodlibetor chime in on why he believes this isn't a XL-sized task.  If it is in fact XL-though, we should try to scope it down further!

**Comment by quodlibetor** [comment]
I'm working on a detailed response, the full scope of this is indeed XL-sized. I think that there are reasonable smaller tasks that *might* be doable in the weeks before 0.6.

**Comment by quodlibetor** [comment]
Here's what we've discussed as the product feature: clients (e.g. Java, Python) want to be able to say "I am a sink, send me updates".

That is a more specific -- but plausibly more useful -- form of a generic tcp/socket sink (I thought I had created an issue around this, but #1706 #1077 are related) which would allow you to sink updates into an arbitrary socket.

Our current thinking for a long-term vision of what this should look like is as a suite of related features:

* Some sort of framed generic transport layer, my inclination here is to use h2/h3 because it is
  well-supported in most languages and supports bidirectional communication.
* The ability to specify an encoding -- protobuf would make this basically gRPC, but JSON and avro
  are also reasonable transport formats and json makes the most sense as a first pass because of
  complexity problems with schemaful encodings.
* A client library that provides some additional `tail`-related methods that automatically create
  self-sinks and upgrade to using them. Two obvious things that I can imagine here are an API
  which just keeps a local bag or hashmap up to date, and an api which takes a callback to be
  called on each new event.

So the long term vision is some API that clients can use that would look like:

```python
import psycopg2
import materialize


def follow():
    mz = psycopg2.Client()
    mz.execute("CREATE MATERIALIZED VIEW example AS ...")
    mz_client = materialize.Client()
    updating_map = client.tail_map("SELECT my_key, my_field FROM example")

    updating_map["interesting_id"] # interesting behavior
```

This is very much in the scratch/needs to be designed phase, and actually implementing this API isn't on the docket for 0.6 -- strong agree that the most that we can hope for by then is general consensus on a design direction.

If we agree that this is a worthwhile long term goal, then I think that there is a route to get there that allows useful output reasonably quickly.

Optimistically I think we may be able to get phase 1 done in 2-4 weeks, potentially getting it in to 0.6 and potentially getting stated on phase 2.

## Phase 1: support "I want to be a sink" purely in http/1.1

We will need to be able to open a connection to materialize that is ready for receiving requests.

The most minimal way to do this that I believe can still stand as a feature in its own right is to expose an http endpoint that starts a stream on request. So clients would do something morally equivalent to:

```http
GET /api/tail?query="SELECT * FROM view"&snapshot=true&format=json HTTP/1.1
```

And receive tail with snapshot with newline-delimited JSON.

Supporting arbitrary sql at this layer is useful because it enables users to issue projections here, but it may be reasonable to refuse to implement arbitrary queries and instead require the API to refer to a named (not necessarily materialized) view.

I believe that the big chunks of work in this are:

* translating some of our sink work to be able to emit in json format
* adding another place where we can glue client requests to the dataflow layer

This would allow us to start experimenting ASAP and for streams that are expected to be below the 1MB/S (json-encoded) range might be fine for many users.

Possibly we could implement Avro at this phase, but IIRC Avro prefers to have the transport layer be responsible for framing records. Right now we use either kafka messages or Avro Object Container File to frame records, and if avro has no built-in tools for framing I'd rather switch to a framed transport before implementing it.

## Phase 2: support h2 framed delivery

This involves

* adding an h2/h3 stream support
* support avro encoding

The biggest work here would be adding another protocol and doing framing in terms of it. I'm not sure if Avro clients are used to streams that start with their schema, or if we would be required to support a schema registry at this point. A schema registry is an extra step.

## Phase 3: Add schema registry/dynamic schema generation

We will want to allow users to fetch schemas for known views. The api for this should exactly match the API defined in Phase 1 in terms of acceptable parameters. So something like:

```http
GET /api/schema?query="SELECT * FROM view"&snapshot=true&format=avro HTTP/1.1
```

This gives clients the ability to download schemata for their clients and compile them into their clients.

## Phase 4: Protobuf

With phase 3 we can expose proto schemas for whatever folks want.

## Phases N-M: A client library

At this point users can build whatever they need and it would be on us to make it actually pleasant to use, potentially along the API that I suggested before getting into phases.

**Comment by benesch** [comment]
Thanks for writing all of this up, @quodlibetor. A smattering of thoughts follow.

  * Can you or @awang say more about the product requirements here? Why isn't `TAIL` sufficient for their use case? There are a few problems with `TAIL` for sure (#3091), but I'd love if we could just fix those `TAIL` warts to make it more usable for folks. Plus, any alternative to `TAIL` is going to struggle to solve many of the same issues.

  * Why does `TAIL` need to support formats? Presumably the goal is to get the data into native types in the client's programming language, just like SQL drivers do. And if that's the case, that's basically already possible with `TAIL`. Since we repurpose the pgwire `COPY` protocol, clients that support `COPY` get decoding of `TAIL` bytes "for free." rust-postgres has a nice implementation, for example: https://docs.rs/postgres-binary-copy/0.5.0/postgres_binary_copy/index.html

    IMO formats are primarily useful when the end goal is persistence. If we need to write to Kafka or to a file, then picking a format that has wide support makes sense. But if the goal is simply to get some in-memory bytes from Materialize directly into another application, then I don't see why you would ever want something besides the pgwire format—it's by far the highest fidelity encoding, since it maps nearly directly to Materialize types. There are always weird encoding issues when we have to map the Materialize data model onto an interchange format's data model.

  * I _really_ don't want to be in the business of supplying a Materialize-specific client to users. This has been one of the overarching design goals of the system from the start. If we need to get in the business of supplying a Materialize-specific client, that decision needs to be made deliberately and for a very, very good reason. Maintaining high-quality clients in several languages requires substantially more engineering than I think we have available for the foreseeable future. If we're considering a path where supplying Materialize-specific drivers is expected, then we need to get buy-in from a fairly large set of folks on the team.

What I'm having trouble envisioning is a use case where a) a Kafka/file sink can't be made to work, b) `TAIL` can't be made to work, but c) a Materialize-specific client would be acceptable. If you're writing a backend service, then presumably running `TAIL` via a PostgreSQL client is possible—doubly so if you're already using a PostgreSQL client to issue `SELECT`s against Materialize.

If you're writing a backendless web application, I can see why you might want Materialize to speak HTTP instead of pgwire—pretty darn hard to run pgwire from the browser! But exposing a Materialize instance to the public internet is definitely not a viable production deployment option today, so you're going to need some sort of intermediary to perform authentication and authorization anyway... and I think that intermediary could just as well provide a bridge between HTTP and pgwire for `TAIL`s.

This feels analogous to our decision to provide tables instead of an HTTP source type. Tables are the more fundamental type. You can easily implement an HTTP API atop tables, but not vice versa. 

Finally, if there is a good reason to provide an HTTP API, why not follow a standard that already exists, like https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events? I think that could save us from needing to write Materialize-specific clients in several different languages.

**Comment by cuongdo** [comment]
@benesch has outlined the technical concerns. I have two more fundamental concerns:

1. Before creating a technical design for an XL-sized feature and adding a lot of code and ongoing maintenance, let's first be explicit about the product requirements. For example, the title of this issue specifies the means ("grpc endpoint") rather than the user need. Knowing the requirements helps us work together to design & implement something that balances technical complexity and satisfying users. For future tasks of similar magnitude, we should document product requirements / user stories before starting to talk about technical solutions.
2. Perhaps I'm reading too much into the 0.6 milestone for this feature, but I'm concerned about adding another way to exfiltrate data before improving existing means of doing that, such as TAIL and SINKs.

Let's pause the technical decision and focus on documenting the product requirements.

**Comment by cuongdo** [comment]
Assigning to @awang for clarification of the requirements and user stories.

**Comment by quodlibetor** [comment]
> the goal is to get the data into native types in the client's programming language, just like SQL drivers do. And if that's the case, that's basically already possible with TAIL. Since we repurpose the pgwire COPY protocol, clients that support COPY get decoding of TAIL bytes "for free." rust-postgres has a nice implementation, for example: https://docs.rs/postgres-binary-copy/0.5.0/postgres_binary_copy/index.html

Hmm yes my understanding *was* that the COPY protocol is unframed, essentially just a stream of bytes that psql emits to the terminal or to a file, and that there was no good way to get individual rows out of it without manually parsing/doing our own custom escaping. Not sure where I got that idea from, the [javadoc for the pgJDBC driver](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html) *looks* like it only handles streaming bytes (since the writers are all `java..io`), but it definitely talks about writing data into a database, which means it must be capable  of something structured.

**Comment by quodlibetor** [comment]
Since the underlying tail protocol _does_ support row-by-row results, I'm going to add a comment in #3091 with more info about how that's exposed.

**Comment by mjibson** [comment]
After some internal discussion our current thoughts are:

1. Change `TAIL` to be a normal rows-producing statement (just like `SELECT`).
2. Give `TAIL` columns like `diff`, `timestamp`, `cols...`.
3. Give `TAIL` optional syntax that will produce "timestamp X is done" messages. This will create a new column `done` or something that is either `true` with a timestamp (and the other columns are null) or `null` with populated columns.

| timestamp | done | diff | col_key |
| - | - | - | - |
| 1580000000000 | NULL | 1 | insert_key |
| 1580000000000 | true | NULL | NULL |
| 1580000000001 | NULL | 1 | will_delete |
| 1580000000001 | true | NULL | NULL |
| 1580000000003 | NULL | -1 | will_delete |
| 1580000000003 | true | NULL | NULL |
| 1580000000005 | NULL | 1 | will_update_old |
| 1580000000005 | true | NULL | NULL |
| 1580000000007 | NULL | -1 | will_update_old |
| 1580000000007 | NULL | 1 | will_update_new |
| 1580000000007 | true | NULL | NULL |

4. Implement `COPY TO` with `query` support: `COPY (<query>) TO STDOUT`. This will allow us to add text, csv, and binary support more generally to anything that can produce rows. So `TAIL` would look like `COPY (TAIL view_name) TO STDOUT WITH (format binary)`.

This is good because it allows drivers that don't buffer all row results to just to a normal `TAIL` and loop through the results. For drivers that don't support that they can use whatever flavor of COPY they want (text, csv, binary). This will build two orthogonal features that can be used together without the semantics of one bleeding into the other. `TAIL` can still get `UNTIL` support if users want, and we could also teach COPY whatever users need.

**Comment by awang** [comment]
Marking this as done, @mjibson feel free to veto if not though!
