### ISSUE TITLE
pgcompat: support information_schema._pg_expandarray

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4506]
Required to support PgJDBC: https://github.com/MaterializeInc/materialize/issues/3727

`information_schema._pg_expandarray` query can be [found here](https://github.com/postgres/postgres/blob/16e3ad5d143795b05a21dc887c2ab384cce4bcb8/src/backend/catalog/information_schema.sql#L43).

Requires support for the following:
- [x] `pg_catalog.array_lower`: https://github.com/MaterializeInc/materialize/pull/4514
- [x] `pg_catalog.array_upper`: https://github.com/MaterializeInc/materialize/pull/4515
- [X] `pg_catalog.generate_series(start, stop)`: https://github.com/MaterializeInc/materialize/pull/2857
- [x] `pg_catalog.generate_series(start, stop, step)`: https://github.com/MaterializeInc/materialize/pull/7953

**Comment by cuongdo** [comment]
What user workflow requires this?

**Comment by benesch** [comment]
PgJDBC uses this function.

**Comment by JLDLaughlin** [comment]
Added Nikhil's comment to the issue description!

**Comment by JLDLaughlin** [comment]
Bonus: [fix the `generate` functions to make them more generic](https://github.com/MaterializeInc/materialize/pull/7953#discussion_r692556475)!

**Comment by mjibson** [comment]
Progress on this at https://github.com/mjibson/materialize/tree/expandarray. Doesn't work correctly for the empty input case because that should return 0 rows instead of NULL. This is due to how subexpressions work since this is currently implemented as a subexpression. Some ideas: make this a table/set returning function so that it's only valid on the RHS of a FROM. Not sure what we'd do about using it as a scalar value though. In pgjdbc it's used on the scalar side: https://github.com/pgjdbc/pgjdbc/blob/151b287732a551c380dcaa34f9c0549aeeb26208/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L2050

Which means I don't think that'd help do what we need which is to unblock pgjdbc. In postgres this returns a set:
https://github.com/postgres/postgres/blob/16e3ad5d143795b05a21dc887c2ab384cce4bcb8/src/backend/catalog/information_schema.sql#L44

So this is blocked on #1546 for now.

**Comment by chaas** [comment]
@mjibson I'm cleaning up old tickets - is this done?

**Comment by mjibson** [comment]
I think so.
