### ISSUE TITLE
Reduce breakage in release load tests

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#4538]
During the recent release cycles, we've had delayed load test runs because of the following:

1. Outdated documentation
2. Broken load test. These have been caused by both infrastructure code changes and changes to this repo, so any solution should detect breakage caused by all repos that our load tests depend on.

Let's fix both of these.

For the second item, a strawman proposal is: create a smoke test for our nightly tests and complain *loudly* if the load test is broken, like sending a message to Slack or sending emails. Have it run either nightly or on every change. However, make sure that CI doesn't take too long to run as a result.

**Comment by cuongdo** [comment]
This will be worked on as part of @quodlibetor's time as 0.5.1 release manager.

**Comment by quodlibetor** [comment]
Now that we've got grafana-powered slack Alerts on the materialize nightlies, I'm trying to think of a good way to fix the "outdated documentation" part of this. I can't think of anything that would allow us to *close* this. I would love some ideas.

The issue that I keep running into is that breakage comes from three independent sources, and essentially any engineer at the company could introduce changes at any of these sources, so we can't go with an "education" strategy.

The sources are:

* changes to infra documentation: the biggest issue here was that links would occasionally go stale. I added markdown-link-check a few months ago, but that doesn't help with links from the handbook to the docs.
* changes to infra itself -- changes to the infra CLI API are typically isolated and unrelated to docs, so folks don't think of updating release load tests docs when other aspects of the api change. I'm not sure how to lint against this in any sort of automated way.
* changes to materialize -- sometimes people change the steps in the release process because we want to increase testing of materialize. This happened with chaos, for example, which added a release step that was obvious when first written but not obvious to the next person running the tests. But this also happened when we changed something in the billing demo, causing it to crash instead of run to completion. That was unrelated to the release process and not top of mind, so I'm not sure what we could have done

Possible solutions:

### docs robustness improvements

We could either move all release-related docs from the handbook to the `/doc` directory and make sure that everything is a relative link. We can't really go in the other direction because of module-internal docs, and linking to source files.

Alternatively, we could write a `mkdocs` plugin that rewrites relative links that leave the handbook root into something that is absolute relative to the infra repo. It doesn't seem that hard to do, so I created an issue to track it: https://github.com/MaterializeInc/infra/issues/720

I don't believe that stale links are a huge problem right now, but I do recall it being a bit annoying, in particular to link to various module-specific READMEs.

There was also this other issue https://github.com/MaterializeInc/materialize/issues/3978 , but it is, for the most part, just about improving docs in general, nothing that had gone awry due to code changes.

### Infra Change Robustness

I believe that the biggest annoyance around this recently was the introduction of new security-oriented cli tools and wrappers. My preference in the past has been to use wrapper scripts so that docs don't need to change (e.g. in [this pr](https://github.com/MaterializeInc/infra/pull/306)) but there has been pushback that that can be confusing because then folks don't know what's going on under the hood.

The alternative is to say that the first-time initialization of the infra repo should be executed every time someone does anything in the repo (e.g. the first commit that introduced aws-vault documented setting it up). But that seems basically unusable.

Either way, we could balance the release coordinator so that the release manager never comes from the infra team two releases in a row -- that reduces the amount of time that changes have to bitrot before someone not using the tools daily can run into issues. Or we could go the opposite way and say that the release manager should *only* come from infra.

Other than that, I'm not sure what we can do to improve this -- "please consider docs impact" is already something that we should be thinking when we issue PRs.

### Materialize Change Robustness

Hopefully the recent alerts will catch changes that cause conditions to change in a way that the existing load tests start to fail. There are a couple more that I can think of to improve this:

* improving alerting on our nightly tests should help a bit -- it is currently catching the changes to the billing demo that broke the process the last couple times.
* increasing the change burden when changing some of our load tests. I'm not sure how to automate
this, the rule should be something along the lines of:

  > if you change a release-validation load test, you need to run it for 24 hours to verify that
  > your changes don't break the release process.

**Comment by quodlibetor** [comment]
We have added a bunch of alerting to our existing monitoring, which has helped with this. Not currently planning on working on this a lot, so removing myself as assigned.

**Comment by benesch** [comment]
Closing as stale. The release load test mentioned here is long gone.
