### ISSUE TITLE
release: load tests need to be divorced from demos etc.

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#4559]
Load tests are ideally as stable as possible so that their results from release to release can be compared. This is presently very hard to achieve because most load tests are repurposed demos. Making the demo better often makes the load test worse.

**Comment by ruchirK** [comment]
I'm not sure what cases you're referring to where making the demo better makes the load test worse? or is it just that making changes to the demo degrades the consistency of the load test from release to release?

**Comment by benesch** [comment]
Yeah, that's exactly what I mean!

**Comment by ruchirK** [comment]
I think I agree with you in general, but I also feel like the featureset is changing so fast that we should be adding new things to the load tests to exercise new functionality? the topk in the billing demo is an example of that -- as soon as we got lateral joins a bunch of folks felt it would be good to add to the billing demo explicitly for load test purposes so that we could catch any future regressions to TopK processing.

Not sure how to resolve that -- perhaps we need to more strictly use versions in our load tests / demos? Also agree that its confusing and weird that the billing "demo" is never really used for demo purposes now and is almost exclusively a load test

**Comment by benesch** [comment]
> I think I agree with you in general, but I also feel like the featureset is changing so fast that we should be adding new things to the load tests to exercise new functionality?

I think that's exactly what I'm getting at? Like, it is great that we have an actual test/demo of using `LATERAL JOIN`s! And I agree that adding production-y tests like that is worthwhile. But the way the load tests are presently set up are at odds with this goal. The instructions for the billing load test are: make sure the billing demo doesn't crash, and make sure the graphs of Materialize's CPU usage/memory usage look the same or better than the last run. That means any perturbation of the billing demo itself corrupts the evaluation criteria.

There are several options here off the top of my head:

  * After changing a load test harness, backfill the load test results on a few recent releases so that we have a baseline for the next release.

  * Commit to having just independent load test harnesses and basically never change them. 

To be honest, I'm not sure how sensitive the load tests are presently to catching anything besides catastrophic regressions? Like, are any of them sensitive enough to surface your recent improvements to TopK memory usage? My guess is not! I think we're going to need much more targeted and isolated benchmarks to squeeze out the noise if the goal is to catch smaller-scale regressions.

**Comment by benesch** [comment]
This got fixed! Via Philip's feature benchmark.
