### ISSUE TITLE
UX - Basic installer for materialize

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4595]
Can we have a basic installer for materialize?

Installer can do several things - 

Validate env as in 
OS version
Number of CPU
Memory available
Any process running on port 6875
Non privileged user 

Walks the user through the basic config - data directory, log directory, ports to use etc, configures a config file (currently not enabled), creates a startup script among others

This can also be used to serve as a way to capture details from a customer installation for support.

@rjnn

**Comment by benesch** [comment]
This is an intentional design decision. Materialize is easy enough to install and configure that I do not believe an interactive installer is justified.  If there are specific deficiencies in the installation experience, let's see if we can address those in the current framework! Specifically there are a few asks here.

  * Describing how to configure Materialize. I think this is already well described in our CLI docs: https://materialize.io/docs/cli/
  * Validating the environment. We can just do this whenever you start up the `materialized` binary. We already do a bit of this to warn you if your nofiles ulimit is too low.
  * Capturing anonymized user information. We've started doing some of this with an automatic upgrade check that runs on startup. It would be quite straightforward to also send up information about the user's system as part of that check.
  * Startup scripts. This already exists if you install via the apt package. `sudo systemctl start materialized` will launch Materialize with a default configuration, for example.
  * Nonprivileged user. Again this is automatically created by the apt package.

If the ask here is to provide an RPM, that's definitely something we intend to do, to complement the apt package. Would that address your concerns?

**Comment by krishmanoh2** [comment]
It is preferable that whatever ships in apt or yum packages is also available in the tarball available for download. An end-user may not have the ability to install a package (lacks privileges) or not able to use the materialize repo (company policy).

An installer is fairly basic - it does pre-reqs and prevents mistakes during configuration. Rather than have the user run materialize and then figure out that the environment is not right, the installer can prevent this at the onset.

**Comment by benesch** [comment]
> It is preferable that whatever ships in apt or yum packages is also available in the tarball available for download. An end-user may not have the ability to install a package (lacks privileges) or not able to use the materialize repo (company policy).

I'm not sure I understand the ask here. The same binary that's in the apt package is in the tarball. If the goal is to install the systemd unit file into the right spot, that's something that requires root privileges, so if you don't have privileges to install apt packages, you almost certainly do not have privileges to install systemd unit files. Plus the correct location for the systemd unit file is inherently platform specific—not all Linuxes even _use_ systemd—so it's not really something that makes sense to include in a tarball that attempts to be usable on nearly all Linux distributions.

> Rather than have the user run materialize and then figure out that the environment is not right, the installer can prevent this at the onset.

So, in a world with an installer, you have to run the installer, and then run `materialized`. In the current world, you just run `materialized`. In either case, the first command that you run will tell you whether things are configured correctly. The installer just adds an extra step to the process.

**Comment by rjnn** [comment]
I think this is an issue where our intentional 'single binary' structure conflicts with the 'installer' way of doing things, and as @benesch noted, we've chosen the single binary path intentionally. if there are things that we should report/warn about, we should have those reports and warning happen on startup.
