### ISSUE TITLE
UX - Create and use a config file for materialize

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4596]
Materialize on download and untar has 2 directories - bin and etc. However do not see any config file in the etc directory. It does not look like there is an option to use a config file either.

Using a config file with parameters ensures consistent startup. This is an industry standard. 

Can we enable a config file option for materialize?

@rjnn

**Comment by benesch** [comment]
The reason we don't presently support a config file is because deployment strategies that use Docker and Kubernetes make the config file experience subpar. Config files work great when you are installing software yourself, manually, on a Linux box. But when you're using the materialized Docker image, it's kind of a pain to inject a config file into the image. It's much easier to just set command-line flags in your Docker/Kubernetes configuration.

We may need to support a config file down the road, but I don't think the extra complexity we'd need to parse and validate a config file is sufficiently justified yet. There are plenty of ways to ensure consistent startup without a config file, i.e., by adding the desired configuration as command-line options in a startup script.

**Comment by rjnn** [comment]
Great point @benesch. There's a bit of an intentional design choice here to optimize for single binary/containerized/cloud deployments @krishmanoh2 which is why there's 3-4 issues where you're running against that. Let's give this a few weeks to see if it comes up again.
