### ISSUE TITLE
UX: Startup script for materialize

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4597]
The documented method of running materialize is to run materialize as a foreground process manually invoking the options as needed.

Having a startup script (which is pre-configured by the installer with the right options) is more elegant and also error-free method to start materialize.

This ties into Enterprise readiness as well.

@rjnn

**Comment by benesch** [comment]
Discussed a bit in https://github.com/MaterializeInc/materialize/issues/4595#issuecomment-715456922. There is already a systemd unit file that ships with the apt package.

**Comment by krishmanoh2** [comment]
Can we include this script in the tarball download?

**Comment by benesch** [comment]
It's a systemd unit file, and the location into which it should be installed varies from platform to platform. I'm not sure it makes sense to include it in the tarball. In a world where we have an RPM package, I think we should encourage folks to use either the RPM or apt package rather than the tarball. The tarball is mostly intended for experimentation.

**Comment by rjnn** [comment]
I think this is a scenario where the single-binary and the fact that cloud deployments are our preferred production deployment mean that installer/scripts are more the aegis of infra. I'm closing this for now, but @benLogN feel free to add some color if you think we could get prescriptive in the documentation for how we should guide users to deploy Materialize in on-prem installations to match what we think is the best way to deploy Materialize in our cloud infra.
