### ISSUE TITLE
source-caching: use source name as directory prefix to improve readability 

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4641]
Currently the directory structure for persistence is {data-directory}/persistence/{source-id}

If we can change source-id to source-name, would make it easier to correlate files to a specific source.

**Comment by benesch** [comment]
I think this would unfortunately be dangerous? @ruchirK would know for sure. Source IDs are unique over the entire lifetime of a cluster. But names can be reused if a source is dropped and recreated, or via `ALTER RENAME`.

**Comment by ruchirK** [comment]
Ah yes. I had spoken about this with Krishna before he filed the ticket and I had a feeling that I may be forgetting something and this is it -- source names can be reused in one restart so using _just_ source_names for directories would be bad because at the moment we don't delete cached data when a source is dropped.

However, we could make the directory names be {source-id}-{source-name} which might work if we can rename folders when sources are renamed. I'm hesitant to do this as it will further complicate the implementation for unclear benefit.

@krishmanoh2 if its alright with you I'm going to mark this ticket as later, and see if initial users report a usability problem with the current directory structure.

**Comment by benesch** [comment]
> I'm hesitant to do this as it will further complicate the implementation for unclear benefit.

I agree!

**Comment by awang** [comment]
I think making it easy to map from `source_id` to `source_name` is a legitimate request (is it available in `mz_catalog`?), but agreed that changing the directory names is dangerous, and not worth the risks
