### ISSUE TITLE
SELECT DISTINCT ON (col) doesn't work

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#4663]
```
materialize=> select distinct on (a) from a;
ERROR:  function "on" does not exist
```

This definitely doesn't parse correctly, but not sure if the underlying plumbing supports grouped columns like this

**Comment by justinj** [comment]
I think we can support this, I believe it's semantically a TopK with limit 1.

**Comment by benesch** [comment]
I've been looking at this a bit. `DISTINCT ON` is designed to be applied concurrently with `ORDER BY`, but it's unclear if we actually want to do that in Materialize or not.

**Comment by rjnn** [comment]
If we do do this at `ORDER BY` time, isn't that still possible? For each group, we discard all but the first row.

So the question is which implementation direction to choose: whether to do this ahead of time with topKs, or to do this at order by time by adding some complexity to the order by operator in order to keep track of which distinct groups it has seen rows for

**Comment by benesch** [comment]
Right. Something else to consider is that we'll need a TopK-based implementation no matter what for subqueries.
