### ISSUE TITLE
pg_catalog empty tables

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#4749]
could we put in some empty tables for `pg_catalog`?  that way, we can at least prevent 3rd party libraries from erroring out

suggested by @krishmanoh2

**Comment by benesch** [comment]
This is not an actionable issue. Yes, we can stub out more of pg_catalog. But we are intentionally not just adding stubs for things willy nilly, because there is a very low probability that a stub empty table will be sufficient for a given PostgreSQL application.

Could you please file specific issues about specific PostgreSQL tools that we want to consider supporting instead? Thanks.

**Comment by awang** [comment]
thanks! makes sense
