### ISSUE TITLE
Restrict arrangement imports to those we use

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#4887]
The dataflow layer currently imports all arrangements for a source, because we don't have great communication about which arrangements we will actually use. We roughly know the points where arrangements *are* used, as we perform analyses, but this information is not communicated back up.

While not a major problem, it creates dataflow graphs that look like
<img width="1139" alt="Screen Shot 2020-11-26 at 7 20 25 AM" src="https://user-images.githubusercontent.com/5741500/100350454-e99f8b80-2fb7-11eb-8cf5-af46b6898670.png">

**Comment by wangandi** [comment]
A wrench in the works:
We have the ability to use indexes to speed up filtering (specifically `<expr> = <literal>` filters), but the code for that is in the dataflow rendering layer and assumes that we import all indexes corresponding to a view/source. https://github.com/MaterializeInc/materialize/blob/eb8cdbacaa0e9484d7c35fc937be30503caa75b6/src/dataflow/src/render/context.rs#L210

To avoid an regression in this functionality, we would need the arrangement import restricting functionality to become aware of filters around `RelationExpr::Get{id: Id::Global(...), typ: ...}`.

**Comment by frankmcsherry** [comment]
I see! Probably, eventually, we would like the "transform/optimization" layer to be in charge of figuring this out, right? As in, it is a thing that could be known ahead of time, but just happens to be determined in the dataflow layer at the moment.

We should start to form a list of things like this (perhaps other things, like join and reduce planning) that happen to occur in dataflow at the moment, but it would be smart to lift up to .. idk "physical planning++" somewhere after optimization.

**Comment by frankmcsherry** [comment]
This was diagnosed to be part of the root cause of https://github.com/MaterializeInc/materialize/issues/11134

If one creates a large number of indexes on a collection, we'll import them all and then not use them, stressing things out when "large" is one thousand. So this has performance implications, not just presentational issues.

**Comment by wangandi** [comment]
I realized that the ability to use indexes to speed up filtering (specifically `<expr> = <literal>` filters) is now in the MIR -> LIR transformation code instead of dataflow rendering, which means that handling this issue now becomes feasible. 

I have a prototype for a fix for this issue that currently runs as long as you don't give it a query with a join. We [feed `Plan::from_mir`](https://github.com/wangandi/materialize/blob/318c267a4ccf835d29528c5920f05e588a2184b5/src/dataflow-types/src/plan/mod.rs#L1528) a mutable reference to a list that tracks arrangements that it [chooses to use](https://github.com/wangandi/materialize/blob/318c267a4ccf835d29528c5920f05e588a2184b5/src/dataflow-types/src/plan/mod.rs#L1021). Then we [replace `DataflowDescription::index_imports` with only the ones on the list](https://github.com/wangandi/materialize/blob/318c267a4ccf835d29528c5920f05e588a2184b5/src/dataflow-types/src/plan/mod.rs#L1539).
