### ISSUE TITLE
Runtime error handling

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#489]
In various cases, the sql spec says that the query should abort and throw an error. 

In our case, aborting an entire long-running view because of eg a division by 0 is poor UX. At the moment we just return null instead in many cases, but this can cause surprising behavior downstream eg if fed into an aggregate. 

How can we indicate errors without aborting the whole view or accidentally smothering the error? 

A strawman proposal is that we add `Datum::Error{cause: ErrorCause}` and that every sql func should propagate that error if received as an argument. Performance considerations are assumed to be solved by someone else.

**Comment by cuongdo** [comment]
Moved to 0.3, because this is still important but is likely not going to make it in the next day

**Comment by benesch** [comment]
The big lift on this is nearly done.

Some musings about what work remains. Errors within a dataflow are always transient (unless you have a constant error) and can be resolved by removing the data that's causing the scalar expression evaluation to fail. After #2441, we have a good handle on that.

Now, there are also errors that can occur at the edges of the system, with sources and sinks, and the errors can be either permanent or transient.

|| permanent | transient |
-|--|--|
| **source** ||
| **sink** ||

I don't yet have a good handle on to handle all of these errors. Some rough thoughts:

* Permanent source errors can be handled by dropping the oks collection and pushing the permanent error message into the errs collection. Probably want that permanent error to be the error returned to the client, rather than some random division-by-zero error that's lying around.
* Transient source errors can be handled by pushing a temporary error message into the errs collection, and retracting that error message if/when the error is resolved.
* Transient/permanent sink errors need to go... somewhere. They're not really dataflow errors, because they don't bubble up when you issue a SELECT, but rather need to get stashed away in the catalog somewhere, and surfaced to the user via some dedicated system objects or logging.

Possibly it is better to think of transient errors (Kafka broker going down, for example) as status updates, that get published to a status stream that is completely separate from the error stream. 

This concept of informational streams associated with objects is the best design I've come up with. If every source/view/sink has an associated status/error stream that just returns string error messages, that might be a pretty usable and pretty simple means of surfacing transient and permanent errors, respectively, to advanced users.

**Comment by benesch** [comment]
Oh, and we already have an issue for tracking errors with Kafka sinks specifically: #1539.
