### ISSUE TITLE
Potential log spam from librdkafka: No bootstrap.servers configured: client will not be able to connect to Kafka cluster

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4939]
Running the chbench demo, when I open up the logs, I see many messages in the following form:

`INFO librdkafka: CONFWARN [thrd:app]: No bootstrap.servers configured: client will not be able to connect to Kafka cluster`

It's difficult to tell if these messages are important and/or actionable by the user.

**Comment by elindsey** [comment]
Yoink, grabbing this one. 🙂 

We have a step during purification that does a loose validation of the kafka config. During that validation we don't set the bootstrap.servers, which triggers this warning. The warning is benign (because later when we build the real config we do set this parameter), but is noisy and makes for a confusing log. I'll fix this.

**Comment by elindsey** [comment]
This is now fixed in trunk.

**Comment by cirego** [comment]
Thank you @elindsey!
