### ISSUE TITLE
Support using SCRAM-SHA-256/512 SASL mechanism for connecting to a Kafka cluster

### ISSUE THREAD

**Issue by kyloon** [MaterializeInc/materialize#4955]
Materialize currently does not support using `SCRAM-SHA-256` and `SCRAM-SHA-512` SASL mechanisms to connect to a Kafka cluster.

Query:
```sql
CREATE SOURCE topic
FROM KAFKA BROKER 'kafka:9092' TOPIC 'topic'
WITH (client_id=materialize, security_protocol=sasl_plaintext, sasl_mechanisms=scram_sha_512); 
```

Result:
```
ERROR: ERROR:  Client creation error: Unsupported SASL mechanism: SCRAM_SHA_512
```

**Comment by rjnn** [comment]
thanks @kyloon for the request. @sploiselle can we get a quick estimate on the effort size here? as an aside, should this be sent in the future to the external integrations team for triage? tagging you only because you did the SASL work on sources, so probably have the faster effort size estimation.

**Comment by sploiselle** [comment]
@rjnn I'm unfamiliar with how easy it is to plug in other SASL-based auth mechanisms into Kafka; the original plaintext work was ~2 weeks, and I'd _expect_ something in that ballpark, though hopefully a bit faster. That being said, it's possible that we run into issues where [`rust-sasl`](https://github.com/MaterializeInc/rust-sasl) don't work out of the box, in which case, we're gated by Nikhil's time and interest in resolving any shortcomings.

**Comment by rjnn** [comment]
Thanks @sploiselle. assigned to @awang for triage and prioritization.

**Comment by benesch** [comment]
I'm not eager to add tests for these more esoteric forms of authentication. Since @sploiselle got the scaffolding in place for authenticated Kafka connections, the hardest and most finicky part of supporting a new authentication method is actually writing the Docker + Java configurations. But since we've got thorough tests for SSL/GSSAPI, we can probably just flip the bit on enabling SCRAM, and rely on librdkafka's test suite to have shaken out most of the bugs. PR incoming.

**Comment by benesch** [comment]
Actually, this already works! Just use `'scram-sha-512'`, i.e., with hyphens instead of underscores.

```
CREATE SOURCE topic
FROM KAFKA BROKER 'kafka:9092' TOPIC 'topic'
WITH (client_id=materialize, security_protocol=sasl_plaintext, sasl_mechanisms='scram-sha-512', sasl_username='user', sasl_password='pass'); 
```

**Comment by rjnn** [comment]
Just need to add to docs!
