### ISSUE TITLE
indexes should be renamed if materialized view is renamed

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5096]
### What version of Materialize are you using?

```
$ materialized -v
0.6.1-dev
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [X] Built from source

### What was the issue?

If I create a materialized view and rename it, I'm unable to create another materialized view with the original name.

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes! See:
```
materialize=> create materialized view blah as select 1;
CREATE VIEW
materialize=> alter view blah rename to blah1;
ALTER VIEW
materialize=> create materialized view blah as select 1;
ERROR:  catalog item 'blah_primary_idx' already exists
```

**Comment by sploiselle** [comment]
You can manually rename the index that got "left behind" using the same [`alter`](https://materialize.com/docs/sql/alter-rename/) command, which would free up the name. Any kind of automatic solution is pretty fraught given that we don't actually track whether or not an object got materialized upon creating or afterward.

**Comment by benesch** [comment]
Yeah, agree that renaming indexes is probably dangerous. (~Could see what Postgres does, but I bet it just leaves the old index names behind.~ Confirmed.)

I think the issue here is that we're not looking for names besides `t_primary_idx` for that index. In other contexts will do the auto-name-finding thing, where we add `1` to the name, then `2`, and so on. I guess we must not do that for primary indexes?
