### ISSUE TITLE
Support Upsert envelope for protobuf source format

### ISSUE THREAD

**Issue by yuhui-lin** [MaterializeInc/materialize#5176]
Quote from document:

> Note that protobuf sources currently only support append-only writes to Materialize.

Do you have a plan to add this support in near future?

**Comment by rjnn** [comment]
Yes we do. We're refactoring our sources to make them more modular at the moment, so that we can support the full cross-set of <envelopes, formats, sources>, once that is done this should fall out of that refactor. cc @umanwizard to track this issue and indicate when it is resolved. A quick timeline estimate would also be helpful!

**Comment by nmeagan11** [comment]
Closing as this is complete.
