### ISSUE TITLE
recognize and explicitly reject "DROP MATERIALIZED VIEW"

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#5227]
I'm on a fairly recent version of mz `materialized v0.6.1-dev (080235337)`

When I create a materialized view I can't execute `DROP MATERIALIZED VIEW` on it but on postgres that works fine

see for example

```
Test=# create table test (a int);
CREATE TABLE
Test=# insert into test values (2147483647), (2147483647), (2147483647);
INSERT 0 3
Test=# create materialized view test_sum as select sum(a) from test;
SELECT 1
Test=# drop materialized view test_sum;
DROP MATERIALIZED VIEW
Test=#
```

In materialize a similar sequence of commands fails with

```
materialize=> drop materialized view test_sum;
ERROR:  Expected DATABASE, SCHEMA, TABLE, VIEW, SOURCE, SINK, INDEX, or TYPE after DROP, found MATERIALIZED
LINE 1: drop materialized view test_sum;
             ^
materialize=>
```

pg docs for this command: https://www.postgresql.org/docs/13/sql-dropmaterializedview.html

**Comment by wangandi** [comment]
All views, regardless of materialized-ness are dropped using "drop views". See https://materialize.com/docs/sql/drop-view/#main

The reasoning is that in Materialize, views can go from materialized to unmaterialized and then back to materialized back again. It would be annoying for a user to have to check the current materialized-ness of a view in order to figure out how to drop it.

**Comment by ruchirK** [comment]
I see. It still seems a bit strange to not support `DROP MATERIALIZED VIEW` for views that are materialized when the command is invoked but perhaps this is complicated by the fact that indexes can come in and out of existence. I don't have strong opinions on whether or not we should support this but I do think we should add it to known limitations if we decide not to support it? does that seem right?

**Comment by benesch** [comment]
I don't know that I'd really call this a limitation, exactly.

So to give a bit more context, along the lines of what @wangandi mentioned, in PostgreSQL there are two separate types of view-like objects: views, and materialized views. These are two very distinct type of entities, and you can't go between the two. So it makes sense that `DROP MATERIALIZED VIEW` can't be used on normal views and vice-versa in PostgreSQL, because it's the equivalent of using `DROP TABLE` on a view. 

Now, there is something analogous in PostgreSQL, which is temporary tables. You type `CREATE TEMPORARY TABLE t (a int)` to get a temporary table, but you type `DROP TABLE t` to drop that table. And `DROP TEMPORARY TABLE t` is actually a syntax error. The `TEMPORARY` keyword in PostgreSQL works just like the `MATERIALIZED` keyword in Materialize: it specifies a property of the object, rather than specifying a totally different type of object.

We _could_ just accept `DROP MATERIALIZED VIEW` as an alias for `DROP VIEW`, but I don't love the idea of being able to use `DROP MATERIALIZED VIEW` on a non-materialized view. Seems weird! 

So here's my proposal: let's make `DROP MATERIALIZED VIEW` a command that we explicitly recognize but _reject_ if we see it, with a helpful error message that says "please use `DROP VIEW`". That leaves the door open to alternate behavior in the future, too, if we decide it's not the right call, but I think it is also a strict improvement on the current situation.

**Comment by ruchirK** [comment]
that makes a lot of sense to me. Perhaps its also worth calling out why we made this choice out in the `DROP VIEW` docs in a bit more detail - I think a simplified version of Nikhil's comment is sufficient to explain things.

**Comment by ruchirK** [comment]
taking this for a new hire!
