### ISSUE TITLE
Receiving error: `error handling connection in pgwire server: early eof`

### ISSUE THREAD

**Issue by jslauthor** [MaterializeInc/materialize#5246]
### What version of Materialize are you using?

`materialized v0.6.0 (9ed7c170f)`

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [X] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?

I'm receiving this error `Jan 09 17:26:35.504 ERROR materialized::mux: error handling connection in pgwire server: early eof` every time I use `pgx` `Query` in Go (`pgx` v4.10.1). I'm receiving the data as expected, so it's not a high priority error.

### Is the issue reproducible? If so, please provide reproduction instructions.

Here's how I'm connecting to materialized:

```golang

func NewDB() (*pgxpool.Pool, error) {
	config, err := pgxpool.ParseConfig(os.Getenv("MATERIALIZE_URL"))
	if err != nil {
			log.Fatalf("Unable to parse config: %v\n", err)
	}

	dbpool, err := pgxpool.ConnectConfig(context.Background(), config)
	if err != nil {
		panic("Failed to connect to Materialize!")
	}

	return dbpool, err;
}

```

Here's how I'm querying materialize:

```golang

func GetLatestMessagesForRoom(mdb *pgxpool.Pool, roomname string, limit int) []model.MessageJSON {
	if limit == 0 {
		limit = 10
	}

	var messages []model.MessageJSON
	// For some reason PGX doesn't like integer limits in prepared statements in Query, so we need to swap out the 
	// constant in a string first, then use the prepared statement for the roomname
	sql := strings.Replace("SELECT user_id, message, room_name, user_name, CAST(ts as Timestamp) AS ts FROM json_chat_view2 WHERE room_name = $1 ORDER BY ts DESC LIMIT $2;", "$2", strconv.Itoa(limit), -1)
	rows, err := mdb.Query(context.Background(), sql, roomname)
	defer rows.Close()

	if err != nil {
		log.Errorf("Unable to select messages: %v", err)
	}
	
	for rows.Next() {

		var userID, message, roomName, username string
		var timestamp time.Time
		
		err := rows.Scan(&userID, &message, &roomName, &username, &timestamp)
		if err != nil {
			log.Errorf("Could not retreive latest messages for room: %v", err)
		}

		msg := model.MessageJSON{
			Username: username, 
			Message: message, 
			Roomname: roomName, 
			UserID: userID,
			Timestamp: timestamp.String(),
		}

		messages = append(messages, msg)
	}
	
	return messages
}

```

**Comment by benesch** [comment]
Thanks for the report and the detailed reproduction steps! I managed to track this down. As you identified, the error is harmless. The issue is that when you create a pgx connection, pgx will optimistically use TLS. Since you're not running Materialize with TLS enabled, Materialize will gracefully reject that TLS connection attempt, but pgx then abruptly abandons the connection. That's the error message you're seeing in the logs. This doesn't actually cause a problem in practice, because pgx immediately opens a new, non-TLS connection that succeeds.

Other PostgreSQL clients don't abandon the connection after a failed TLS negotiation, which is why this hasn't come up before. But it appears that what pgx is doing is totally valid per the PostgreSQL protocol specification, so I've opened #5247 to avoid logging an error in this situation.
