### ISSUE TITLE
Report jemalloc stats in a mz catalog view

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5294]
mz uses jemalloc for memory allocation. Currently mz does not report jemalloc stats.  

jemalloc reports a number of useful stats that can help an end-user optimize jemalloc for their specific environment. By reporting these stats, we allow end-users to give them better insight into mz.

**Comment by ruchirK** [comment]
mz doesn't always use jemalloc fwiw - we use the system allocator when Materialize is running on MacOS. Also, I'm not sure if you've seen the memory sampling endpoint that Brennan added a while ago, that can also help out with getting insight into Materialize.

My larger question with this issue is: which jemalloc statistics do we think will help users optimize for their specific environment? Most of the jemalloc statistics offer pretty granular data around "how much memory of various sizes are we allocating" (you can see a sample here https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Basic-Allocator-Statistics ) and while I think that's extremely useful to Materialize developers, its less clear to me how that could be useful to Materialize users who won't already be intimately familiar with how Materialize manages memory. Like say jemalloc tells the user "Materialize allocated 16 kb blocks 3456 times" -- I'm not sure what an end user will be able to do with that knowledge.

Of course, if you have specific examples of stats that you think would be useful I'd love to learn more about those.

**Comment by krishmanoh2** [comment]
I do not believe any enterprise customer would deploy mz on macos. The purpose for reporting stats is a way for the end-user to understand why system cpu time can be high when running mz. It is towards more visibility into mz.

**Comment by ruchirK** [comment]
Sure thats a fair point. I guess what I'm trying to say is that allocator stats offer a really granular amount of specific detail into something that end users would have a hard time interpreting and using. Even though I'm a Materialize engineer its hard even for me to translate jemalloc statistics into something actionable, because you need to be familiar with when / why Materialize allocates things to know if when the stats tell you that "Materialize allocated 16 kb blocks 3456 times" -- is that normal, or bad? I don't see how someone who wasn't familiar with the Materialize source code could interpret that.

Thats why I'm not sure jemalloc stats would be useful for the end user. Again, if you have a specific example of a statistic that could have helped in the past I'd love to learn more about it

**Comment by benesch** [comment]
No longer relevant in platform.
