### ISSUE TITLE
sql: split name resolution into a separate pass

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5302]
@justinj is already working on this, but better to file the issue late than never. The gist is that the way our name resolution is intertwined with SQL planner is the blocker for several important issues:

  * Full `ALTER ... RENAME` support (#5301).
  * Using something besides relative column offsets in the planner. Keeping track of column offsets that move around as you plan parts of the query gets annoying fast.
  * Tweaking the decorrelator to be more understandable. Tracking column indices in the planner is hard enough, but triply so in the decorrelator.

**Comment by cuongdo** [comment]
Which parts did @justinj already finish?

**Comment by justinj** [comment]
Just the first part!

**Comment by jkosh44** [comment]
After some discussion and research here are my initial thoughts/proposal. This is potentially naive of some constraints that I'm not familiar with and can hopefully be broken slightly into smaller changes.

# Proposal
1. The first step of planning should be to convert all known names to their global Id.
2. Internally planning will only use global ids and not names.
3. DDLs still should be able to defer id/oid allocation to sequencing.
4. `create_sql` catalog items will use ids instead of names.
5. `SHOW CREATE X` will convert the ids to fully qualified names.

# Implementation Details
- Implementing 1 and 2 at a high level should be to add a step to the beginning of planning that converts a `Statement<Raw>` to a `Statement<Aug>`. Then all planning functions take some `XStatement<Aug>`. 
- I think the current augmented statements are not sufficient to actually satisfy the requirement. For example consider the `CreateIndexStatement` struct
https://github.com/MaterializeInc/materialize/blob/ed3e35746698b7824f2c63886759cdec6625eb09/src/sql-parser/src/ast/defs/statement.rs#L675-L687
in both `Raw` and `Aug` forms, the `on_name` field remains an `UnresolvedObjectName`. This would need to change so that the `Aug` form contains a global id. Changing the type to `T::ObjectName` may solve this specific issue, but each statement type will need to be updated appropriately.
- A good first task is probably to implement 1 and 2 for non-column objects.

**Comment by benesch** [comment]
This sounds absolutely spot on to me! You're 100% right that `CreateIndex` needs to change the type of `on_name` to `T::ObjectName`. As a general rule, I think the only place `UnresolvedObjectName` should appear in the AST (besides as a potential concrete implementation of `T::ObjectName`) is in the `name` field of `CREATE ...` statements; the one name we don't want to resolve is the one that names the object that we're trying to create.

**Comment by jkosh44** [comment]
After working on this for a bit I just wanted to write out the tasks that I think will complete steps 1 and 2

- [ ] Convert `Statement<Raw>` to `Statement<Aug>` at the beginning of `mz_sql::plan::statement::plan`
- [ ] Modify statements to only use `UnresolvedObjectName` when the object hasn't been created yet.
- [ ] Modify all `plan_<statement>` functions to accept augmented statements instead of raw statements and fix all compiler errors.
- [ ] Modify catalog state to track items by ID and create API to query by id
  - [ ] It's possible that we can remove all state and API that tracks items by name, I'm not sure yet
- [ ] Modify planning to "resolve" all catalog items by id (It would be more accurate to say get here instead of resolve since the names should have already been resolved).
  - [ ] It's possible that we may just want to include references to Catalog items in the augmented statements, not sure yet.
- [ ] Investigate error handling. All lot of errors will have moved from planning to name resolution and these should be handled appropriately and give reasonable error messages.
- [ ] See what's broken

**Comment by benesch** [comment]
> It's possible that we can remove all state and API that tracks items by name, I'm not sure yet

Yeah, definitely the _rest_ of planning shouldn't need the API surface area that tracks items by name! 

> Modify planning to "resolve" all catalog items by id (It would be more accurate to say get here instead of resolve since the names should have already been resolved).

👍🏽 👍🏽 👍🏽 

> It's possible that we may just want to include references to Catalog items in the augmented statements, not sure yet.

That would be _awesome_! But it's probably a total nightmare of lifetimes.

**Comment by benesch** [comment]
I'm going to say that https://github.com/MaterializeInc/materialize/pull/12858 completes this issue, even though we haven't wired up roles or functions yet. Roles are half baked, so they don't do proper name resolution yet. We'll tackle them part of role-based access control (#677), when we make roles real. Name resolution for functions will only matter once we support SQL UDFs (#5112), so we can tackle functions them..
