### ISSUE TITLE
Test limits of dbt-materialize adapter

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5448]
This combines the following issues from the former `dbt-materialize` repository: https://github.com/MaterializeInc/dbt-materialize/issues/12, https://github.com/MaterializeInc/dbt-materialize/issues/13, https://github.com/MaterializeInc/dbt-materialize/issues/14, https://github.com/MaterializeInc/dbt-materialize/issues/15.

Test `dbt-adapter` with:
- [x] [pre and post-hooks](https://docs.getdbt.com/docs/building-a-dbt-project/hooks-operations/)
- [x] [sources](https://docs.getdbt.com/docs/building-a-dbt-project/using-sources/)
- [x] [custom schemas](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas/)
- [x] [dbt test command](https://docs.getdbt.com/reference/commands/test/)

I fully expect that some or most of these things won't work out of the box! Our `dbt-materialize` macros are sufficient for basic demos, but if it gets traction we should look at these features ASAP.

**Comment by morsapaes** [comment]
:ballot_box_with_check: **Works**
:hammer_and_wrench: **Works, but wonky**

### Pre- and -post hooks :ballot_box_with_check:

Tested creating sources and sinks using pre- and -post hooks and didn't run into issues. It also seems like a few users have used this successfully, too (including in production). One thing to keep in mind, though, is that creating sinks using post-hooks [can be racy](https://materializeinc.slack.com/archives/CUFFL8UBC/p1620415844146200).

### Sources :hammer_and_wrench:

The issue raised in #8744 was, in the end, just me being ~dumb at~ new to dbt back then. The lineage graph [gets a bit weird](https://gist.github.com/morsapaes/03cb046ba4a984da644263c7e22cf094?permalink_comment_id=4165053#gistcomment-4165053) if custom source materializations are referenced using `source()` (as they're technically defined as models), but it seems possible to work around it using:

```
models:
  - name: market_orders_raw
    docs:
      show: false
```

The node still shows, but at least it's...greyed out:

<img width="1434" alt="Screenshot 2022-05-12 at 23 01 11" src="https://user-images.githubusercontent.com/23521087/168245967-12766f6c-a11d-41e1-99bc-464dd65d363d.png">

### Custom schemas :ballot_box_with_check:

We should consider whether we want to override the [default naming convention](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas#understanding-custom-schemas) (the `dbt-postgres` adapter does not), but it otherwise works:

```sql
--stg_market_order.sql

{{ config(materialized='view', schema='staging') }}
```

```sql
materialize=> show schemas;

      name
----------------
 public
 public_staging
```

### Tests :ballot_box_with_check:

@ahelium implemented a pretty cool hack in #12238 that allows storing test results in materialized views that can be used for alerting downstream. So, `dbt test` not only works, but it's been "Materialize-d". 🤩 

<hr>

The default implementation of some dbt concepts (like `seeds`) won't make sense in Materialize Cloud. I'll open a new epic issue soon to track work that needs to be done in the context of `dbt-materialize`+Materialize Cloud.
