### ISSUE TITLE
sql: add support for CREATE OR REPLACE TABLE

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5544]
Right now, we only support `CREATE TABLE` (without the `OR REPLACE` option). We should add `OR REPLACE` functionality to tables to match `VIEW` and `MATERIALIZED VIEW` behavior.

**Comment by benesch** [comment]
`CREATE OR REPLACE VIEW` is a special view-only thing, actually. There's no `CREATE OR REPLACE TABLE` in PostgreSQL. There's `CREATE TABLE IF NOT EXISTS`, but that of course is not quite the same.

The thinking is that it can make sense to blow away an existing view because the underlying data is still *somewhere*, but `CREATE OR REPLACE TABLE` will blow away the existing data in your table, and that's probably not what you wanted.

**Comment by benesch** [comment]
I'm going to close this out per the above, @JLDLaughlin, but let me know if you disagree!
