### ISSUE TITLE
support compressed avro OCF sinks

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5558]
(requested by a community member, see #[materialized](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1612221715097200))

**Comment by benesch** [comment]
Here is a description for this issue:

> Avro OCF files support compression via a "codec" (https://avro.apache.org/docs/current/spec.html#Required+Codecs). This codec is metadata that gets written into the file header. This makes life easy for us in Avro OCF sources, because the file will tell us what codec to use. But in _sinks_ we'll need to introduce some syntax that will allow users to explicitly request that Materialize use a particular codec when it generates the file.

**Comment by koenfaro90** [comment]
Only enquired about this in #materialize because I was attempting to decode the resulting OCF file from a sink and ran into some issues with the AVRO-parsing JS libs not supporting the decimal-type out of the box, browsing through the libs'source led to the idea that data could somehow be compressed. Not a request from my side in any way or form!
