### ISSUE TITLE
EXTRACT/DATE_PART/DATE_TRUNC of DATE parts allowed on TIME values

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5701]
```
$ materialized -v
materialized v0.7.1-dev (c682e6b3a) 

```

### What was the issue?

One is allowed to extract DATE parts out of of TIME values

### Is the issue reproducible? If so, please provide reproduction instructions.

```
                                                         ^
materialize=> select extract(year from cast('11:11:11' as time));
 date_part 
-----------
         0 <- incorrect value returned
(1 row)
```

Contrast with postgresql:

```
pstoev=# select extract(year from cast('11:11:11' as time));
ERROR:  "time" units "year" not recognized
```

The time unit is only recognized if the second argument of EXTRACT / DATE_TRUNC is of a type that that has that information.

**Comment by jkosh44** [comment]
Can I take this issue? I'm trying to get some Rust practice and figure a beginner issue here is a good place.

The issue seems to be that the `extract` function, or `date_part` as it's referred to in it's internal implementation, is not implemented for the `Time` type. Therefore the planner coerces the `Time` type to an `Interval` type, since `date_part` is implemented for the `Interval` type. Since year and other date related fields are valid for `Ineterval`s, it returns 0 instead of an error. 

One solution is to just implement `date_part` for `Time` which returns an error if the user tries to extract a date related field. I have a POC doing that here: [https://github.com/jkosh44/materialize/commit/783240dd4a02263bdeb642f0c64f6df456f5dc6c](https://github.com/jkosh44/materialize/commit/783240dd4a02263bdeb642f0c64f6df456f5dc6c) which seems to fix the issue. I just need to clean it up and add tests.

**Comment by jkosh44** [comment]
I'm just noticing now that this issue includes `DATE_TRUNC`. On postgres `DATE_TRUNC` actually does allow truncation of date related fields on `TIME` datatypes. For example:
```
postgres=# SELECT DATE_TRUNC('year', cast('11:11:11' as time));
 date_trunc 
------------
 00:00:00
(1 row)
```

The reason is actually the same reason as why Materialize allows the extraction of date related fields. The `TIME` gets coerced into an `INTERVAL`, where date related fields are valid.

```
postgres=# SELECT pg_typeof(DATE_TRUNC('year', cast('11:11:11' as time)));
 pg_typeof 
-----------
 interval
(1 row)

```

So it's probably best to not fix this for `DATE_TRUNC` unless Postgres changes this behavior.
