### ISSUE TITLE
docs: --logging-granularity command-line option missing documentation

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#5775]
https://materialize.com/docs/cli/ seems to be missing the --logging-granularity CLI argument 

an explanation of the entire logging infrastructure would be nice to have in the documentation. No matter what I do I never get anything more than announcements about DDL statements in the log.

Internal chat: https://materializeinc.slack.com/archives/CMNT2QSBZ/p1613474317361800

**Comment by benesch** [comment]
Per discussion on Slack: the reason this flag isn't documented is because `--logging-granularity` implies (to me, at least) that this controls the granularity of the log messages that get written to stderr and/or the log file specified with `--log-file`. 

I think we need another term to describe what the dataflow logging is. One option is to go verbose

```
--dataflow-logging-granularity
```

and educate folks on what "dataflow logging" is.

The other option is to pick a new phrase—I'll propose "monitoring"—and use it consistently to refer to dataflow logging:

```
---monitoring-granularity
```

@frankmcsherry you are the one who is most likely to have opinions here. Thoughts?

**Comment by benesch** [comment]
A new contender has emerged: `--introspection-frequency`
