### ISSUE TITLE
aws sources: Support assuming roles directly in materialized

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5895]
Users have an expectation that a correctly configured AWS `credentials` or `profile` file will cause systems to assume configured roles. Unfortunately Rusoto does not do this out of the box ([issue](https://github.com/rusoto/rusoto/issues/1758), [pr](https://github.com/rusoto/rusoto/pull/1842)) -- afaict it doesn't even provide a generic profile/credentials parser.

Adding an StsAssumedRoleProvider into our provider chain isn't a huge lift, but deciding whether we require users to specify a `role_arn` in the source constructor or do the right thing and extract the role_arn from a provided profile is important. If there are not any decent credentials parsers around then we will need to implement that as well. The above-linked PR looks reasonable to a first approximation, for this specific use case.

While S3 is in experimental mode we could do the hackier thing and require the role_arn inside the source's `WITH` clause, with an intention to never stabilize that option, which would unblock #5891 and similar use cases.

**Comment by quodlibetor** [comment]
Also relevant is https://github.com/rusoto/rusoto/pull/1897

**Comment by quodlibetor** [comment]
We're currently hoping that the new AWS-supported Rust SDK makes implementing this much easier, and we're deprioritizing it until the upstream support lands.

**Comment by alex-hunt-materialize** [comment]
@benesch While the AWS SDK migration makes this much easier, I don't think we've actually added support for assuming roles directly in materialized yet. At the least, the docs have not been updated to reflect how to do it. https://materialize.com/docs/sql/create-source/text-s3/#aws-credentials-with-options

**Comment by quodlibetor** [comment]
I spoke with alex and am working on this now.

**Comment by benesch** [comment]
What’s the plan? There are some design questions in the original issue description.

**Comment by alex-hunt-materialize** [comment]
By default, we probably want to use whatever profile/credentials are currently configured. The default credentials provider should do this automatically if we use it. This will not be sufficient for all use cases, especially for Materialize Cloud, but will probably be good for most on-prem or self hosted use cases.

We probably want some way to provide the role_arn per source (using a `WITH` clause?). We'd probably use the default credentials provider to get the default profile/credentials, and then do an STS Assume Role call to assume the role specified by the role_arn.

It might be user friendly to also give them a way to provide a default role_arn to assume, in addition to the per source configuration, since I assume most users will only operate in a single account and will only use one role.

**Comment by quodlibetor** [comment]
Currently I'm looking into exactly how all the pieces fit together, I'll write something up before I start coding.

**Comment by quodlibetor** [comment]
Okay I've gone through all the docs of all relevant things and AFAICT we should be able to improve things by teaching Materialize sources to understand **both** `profile` and `role_arn` WITH options. They should play well with each other, and are complimentary.

---

We do **currently** support configurations from the environment -- at least, using `aws-vault exec ... -- materialized` works correctly with the `testdrive/esoteric/s3.td` file modified to remove everything except the `region` from the with clauses (we hard-require the region in materialized code, but that seems like something left over from rusoto that we should get rid of).

**Comment by benesch** [comment]
SGTM
