### ISSUE TITLE
s3 sources: Support gzip-compressed objects

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5904]
Currently the s3 source transparently supports gzip-compression over the wire, but they do not support compressed objects.

It should be reasonably straightforward to pass the objects that we're downloading through a decompressor after adding the `COMPRESSION <type>` clause to the s3 source syntax.

**Comment by cirego** [comment]
Looking at the documentation for [rusoto_s3::PutObjectRequest](https://rusoto.github.io/rusoto/rusoto_s3/struct.PutObjectRequest.html), we can specify `content_type` and `content_encoding` for the uploaded object. However, it's not yet clear if these are indicators for whether or not the content is already gzipped or if it should be gzipped by Rusoto.

We also don't know if it's sufficient to use these headers when reading data, rather than requiring a `COMPRESSION <type>` clause to the source create statement. @quodlibetor asked the very reasonable question: If I uploaded a gzipped file to S3, does it set the headers correctly?
