### ISSUE TITLE
Handling of duplicate columns names in TAIL

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5908]
The TAIL command adds three extra columns to the output of a materialized view: `timestamp`,
`diff` and `progressed` (optional). If a user creates a materialized view with a column of the
same name, then the output of `diff` will contain multiple columns with the same name.

This may or may not be a problem on it's own, but it can cause problems for downstream consumers.
For example, a user may wish to use a [row
factory](https://www.psycopg.org/psycopg3/docs/row-factories.html) to automatically convert the
row into a different object type.

In particular, the observed behavior in Python is that the `dict_row` cursor factory will
silently swallow one of the columns (observations appear to indicate that the last instance of a
column name will win).

In the case of `namedtuple_row`, Python will raise a stacktrace:

```
Traceback (most recent call last):
  File "psycopg3_tail.py", line 59, in <module>
    main()
  File "psycopg3_tail.py", line 54, in main
    loop.run_until_complete(tail_view(args))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "psycopg3_tail.py", line 34, in tail_view
    async for row in cursor.stream(query):
  File "/usr/local/lib/python3.8/dist-packages/psycopg3-2.99.0-py3.8.egg/psycopg3/cursor.py", line 655, in stream
    rec = self._tx.load_row(0)
  File "/usr/local/lib/python3.8/dist-packages/psycopg3-2.99.0-py3.8.egg/psycopg3/_transform.py", line 200, in load_row
    return self.make_row(record)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/psycopg3-2.99.0-py3.8.egg/psycopg3/rows.py", line 60, in make_row
    nt = _make_nt(key)
  File "/usr/local/lib/python3.8/dist-packages/psycopg3-2.99.0-py3.8.egg/psycopg3/rows.py", line 83, in _make_nt
    return namedtuple("Row", fields)  # type: ignore[return-value]
  File "/usr/lib/python3.8/collections/__init__.py", line 370, in namedtuple
    raise ValueError(f'Encountered duplicate field name: {name!r}')
ValueError: Encountered duplicate field name: 'diff'
```

It seems like we should do something, but I'm not sure what. Perhaps reserve the `diff` and `progressed` keywords?

**Comment by benesch** [comment]
Thanks for raising this issue!

For any users seeing this issue, an easy workaround is to rename any `diff`/`progressed` columns in the underlying query via a `SELECT` query in the `TAIL`:

```
TAIL (SELECT diff AS diff_safe FROM (<underlying query>)) 
```

Agree it would be nice to make this more ergonomic, though. Note that reserving `diff` and `progressed` won't help too much, I'm afraid. All that means is you'd have to type

```
TAIL (SELECT 1 AS "diff")
```

to see the issue, rather than:

```
TAIL (SELECT 1 AS diff)
```

I also want to note that you can trigger this situation in PostgreSQL too if your query has duplicate column names:

```
benesch=> select 1 as a, 2 as a;
 a | a 
---+---
 1 | 2
(1 row)
```

So maybe there is a standard practice for handling queries like that with dict/namedtuple accessors. Though I suspect the standard practice is "don't use duplicate column names". 

One option is to simply reject `TAIL`ing any relation that contains a `diff` or `progressed` field.

**Comment by benesch** [comment]
@mjibson would love your hot take here.

**Comment by mjibson** [comment]
I came here without knowing you had commented with this in my clipboard:

```
mjibson=# select 1 a, 2 a;
 a | a 
---+---
 1 | 2
(1 row)
```

I like the `mz_diff` option and leaving any possible other column duplication up to users.

**Comment by cirego** [comment]
Thanks for the responses and for clarifying the point about duplicate columns.

It seems to me that prefixing the columns with "mz_" is a good precaution.
