### ISSUE TITLE
document WITH (tail=true) on files

### ISSUE THREAD

**Issue by mrgleeco** [MaterializeInc/materialize#6059]
Such docs may exist - please point me to links if it does!

Assuming a supported/documented scenario like 
```
CREATE SOURCE FROM FILE '/tmp/streaming.json' WITH(tail=true)
```
What happens if the file is removed?
What if the file is recreated?
What if it is truncated?

**Comment by ruf-io** [comment]
@mrgleeco these are very good questions, and you are correct I don't see them in Docs.

I'm going to do two things:
1. Follow up with you here with a quick answer to the three questions.
2. Turn this issue into a documentation request to provide permanent answers in our docs.

Thanks for pointing this out.

**Comment by ruf-io** [comment]
OK here's the full answer.

First, it may be helpful to know how Materialize works under the hood: When a **FILE** source is materialized, MZ opens a file descripter, reads to the end of the file, and then sleeps perpetually until it gets a file-changed event, at which point it will try to read from the current position.

**What happens if the file is edited/truncated?** - Keeping in mind that Materialize assumes your file source is append-only and reads updates from "current position", edits to a file won't be reflected in Materialize and edits will likely corrupt the "current position" in Materialize, breaking future appends to the file.

**What happens if the file is removed?** - an **existing** materialized view on the file will behave as if no subsequent updates are being made. (No errors.)  If you create a **new** materialized view on the now-deleted source file, you will trigger an error `Error: file source: unable to open file at path </path/to/file.json>`

**What if the file is recreated?** - Keeping in mind the "open file descriptor" from above, an **existing** materialized view on a file that gets recreated will start to break/corrupt silently, materialize won't properly ingest new lines from the recreated file. 

We'll get a more permanent answer added to DOCS!

**Comment by ruf-io** [comment]
One more note: We intend to improve FILE-based SOURCEs based on what users need for real-world use cases, (here's some good related discussion: https://github.com/MaterializeInc/materialize/issues/3773) 

If you're use case depends on better FILE handling, please share and we'll factor it in to future work!

**Comment by awang** [comment]
Hi @mrgleeco I'm closing this issue, but please reopen if something is unclear or if you have more questions!

**Comment by benesch** [comment]
> Hi @mrgleeco I'm closing this issue, but please reopen if something is unclear or if you have more questions!

Did you mean to close this, @awang?
