### ISSUE TITLE
EOS Kafka sinks should fail at create time if their inputs are nondeterministic

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#6121]
Today we allow creating EOS kafka sinks from kinesis and table sources. Neither of those sources are deterministically replayable, so it doesn't make sense for us to build a sink with eos semantics off of them.

At CREATE SINK time we should validate that EOS sinks only contain kafka or file sources as inputs.

Ideally this check would live somewhere inline with the CREATE SINK statement, similar to our current auth validation - that way we can fail fast and give the user a nice error. That means logic should live somewhere within the coord and not in sources/kafka.rs.

**Comment by aljoscha** [comment]
I determined a couple of options trade-offs:
 - a good place to put the check would be `plan_create_sink()` in `sql`
 - the problem with that is that we don't have access to the fully parsed source, which is only available in the `Catalog` of `coord`. (`sql` also has a `Catalog` but it only has the raw/unparsed SQL statement for the `CREATE SOURCE`)

I can re-create the parsed source in `plan_create_sink()` using sth like:
```rust
let mut depends_on = vec![from.id()];
depends_on.extend(from.uses());

// figure out all the source dependencies, determine whether they're ok
for dep in depends_on.iter() {
    let item = scx.get_item_by_id(&dep);
    if item.item_type() == CatalogItemType::Source {
        let create_sql = item.create_sql();
        let parsed_source = crate::parse::parse(create_sql)
            .expect("Sql for existing source should be valid sql");
        info!("Parsed source: {:?}", parsed_source);
        let parsed_source = parsed_source
            .expect_element("A source statement should only yield one parsed source statement");
        let source_statement =
            if let Statement::CreateSource(create_source_stmt) = parsed_source {
                info!("The one parsed source: {:?}", create_source_stmt);
                create_source_stmt
            } else {
                bail!("Could not parse existing source statement from catalog!");
            };

        let planned_source = plan_create_source(scx, source_statement);

        info!("Planned source: {:?}", planned_source);
        // TODO: use this for our purposes
    } else {
        info!("Dep is not a source: {:?}", item.name());
    }
}
```

(this is PoC code)

I'm not sure I like re-parsing the source like this because it seems a bit brittle but it would work.

Side remark: we're tying things quite closely together with this, that is the Kafka Sink is tied to the Kafka Source and/or we hardcode some known working combinations. It's not well abstracted/separated. I also feel a bit iffy about that.

Any thoughts?

**Comment by aljoscha** [comment]
I could add a method `get_source()` (or `get_source_connector()`) to the `Catalog` trait (in `sql`) which is usually a proxy for `Catalog` (in `coord`) which "knows" the fully parsed source. Specifically, the method would go into `CatalogItem` (the trait in `sql`), which already has `func()` for getting a function, so it would fit in well there.

Alternatively, I could add a method like `supports_consistency()` (name TBD) to `Catalog` (`CatalogItem`) which would allow `plan_create_sink()` to query if all of the sources support consistency. This would loosen the coupling a bit because we wouldn't hard code the list of supported sources in the sink code.

**Comment by JLDLaughlin** [comment]
Jumping in without much context--are we saying all `Kafka` and `File` sources have exactly once semantics? Or will we need additional information from these sources to know if they are exactly once?

Instead of adding anything to the `Catalog`, I would probably do something like the following:
- Add a new function to the [`CatalogItem` Trait](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement/ddl.rs#L1237) named something like `source_connector_type`. 
- The implementation of `source_connector_type` will look something like [`item_type`](https://github.com/MaterializeInc/materialize/blob/8393376589accc4e11800a16bf31d1c2d79a01ff/src/coord/src/catalog.rs#L2364), except it will match on the [`Source`'s inner `SourceConnector`](https://github.com/MaterializeInc/materialize/blob/8393376589accc4e11800a16bf31d1c2d79a01ff/src/coord/src/catalog.rs#L183) type instead.
- Once you have the [resolved `from`](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement/ddl.rs#L1237) in `plan_create_sink`, use the new `source_connector_type` to `bail!()` early if the connector type is not `Kafka` or `File`.

**Comment by aljoscha** [comment]
We will need additional information. For example, for Kafka we need to know whether the Source uses BYO timestamping/consistency. This is only true temporarily, though. When @ruchirK lands more of the source/ts persistence work more configurations will become supported.

I think that's why we would need the `SourceConnector`, via sth like `get_source_connector()` on the `CatalogItem` trait.

**Comment by ruchirK** [comment]
I think we should just build enough smarts to detect whatever will not be allowed long term e.g. tables and kinesis sources and stuff like that and not worry too much about stuff thats short term churn. I'm actively working on the rt timestamp durability stuff and it should be here <soonish> and regardless, byo sources are not well documented anyway so its not like anyone is rushing to try out exactly once sinks with byo?

**Comment by aljoscha** [comment]
@ruchirK So you're leaning more towards a *deny* list? I initially thought about going with an explicit *allow* list but am happy to be convinced otherwise. 👍

**Comment by ruchirK** [comment]
yeah i was leaning more towards a coarse deny list (e.g. block all kinesis, table, and s3, system logs based sources) i just feel like its not worth a lot of extra effort to detect "rt kafka sources wont work with eos right now" because that will change [soonish]

if the delta in effort is not very strong then i have less of a preference towards either coarseness or the allow / deny-ness of the list
