### ISSUE TITLE
wrong result: Fields are referenced by position rather than name during AVRO schema resolution

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6134]
### What version of Materialize are you using?

```
v0.7.2-dev (46234d1f7)
```

### What was the issue?

The Avro specification says "the ordering of fields may be different: fields are matched by name." when it comes to matching two schemas. However, Materialize seems to think that two fields in position X are identical.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
$ set colf1f2={"type": "record", "name": "colf1f2", "fields": [ {"name": "f1", "type": "int"} , {"name": "f2", "type": "int"}] }
$ set colf2f1={"type": "record", "name": "colf2f1", "fields": [ {"name": "f2", "type": "int"} , {"name": "f1", "type": "int"}] }

$ kafka-create-topic topic=resolution-col-order

$ kafka-ingest format=avro topic=resolution-col-order schema=${colf1f2} timestamp=1
{"f1": 123, "f2": 234}

> CREATE MATERIALIZED SOURCE resolution_col_order
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-resolution-col-order-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${colf2f1}'
  ENVELOPE NONE

> SELECT * FROM resolution_col_order
f2 f1
-----
234 123
```

In other words, we expect that the stuff we inserted in the ```f2``` field of the JSON will show up in the ```f2``` column of the source. However, this is not the case as the test above fails like this:

```
avro-resolution-column-order.td:14:1: error: non-matching rows: expected:
[["234", "123"]]
got:
[["123", "234"]]
Diff:
extra row: ["123", "234"]
row missing: ["234", "123"]

     |
  13 | 
  14 | > SELECT * FROM resolution_col_order
     | ^
```

Or ```123``` from ```f1``` went into column ```f2```

This test is a part of a larger batch of tests so there is no need to push it along with the fix if you add me to the PR.

**Comment by philip-stoev** [comment]
Here is another example:

```
$ set colf1={"type": "record", "name": "colf1", "fields": [ {"name": "f1", "type": "int"} ] }
$ set colf2={"type": "record", "name": "colf2", "fields": [ {"name": "f2", "type": "int"} ] }

$ kafka-create-topic topic=resolution-col-name

$ kafka-ingest format=avro topic=resolution-col-name schema=${colf1} timestamp=1
{"f1": 123}

> CREATE MATERIALIZED SOURCE resolution_col_name
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-resolution-col-name-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${colf2}'
  ENVELOPE NONE

> SELECT * FROM resolution_col_name
f2
----
123
```
Stuff inserted into ```f1``` arrives in ```f2```

**Comment by umanwizard** [comment]
I think these aren't actually bugs in schema resolution.

Avro messages do not have embedded schemas - in order to discover the correct schema for decoding, we rely on the Confluent Schema Registry. However, in your test, you have not specified a Schema Registry URL.

So we are not even attempting to do resolution/evolution here; and we are just using the literal schema you provided and attempting to decode all the messages with that.

A better test would be

(1) ingest some data,
(2) create a source, using Schema Registry - now it will use as its reader schema the latest published value to SR.
(3) ingest some new data, with a different writer schema.

Now it will have to resolve that WS against its RS.

I will leave this issue open, since we could probably give better errors or warnings here when this "just attempt to read with the literal schema goes wrong", but close the other one, since they are not actually separate bugs in resolution.

**Comment by philip-stoev** [comment]
I am closing this issue as all the items herein have been accounted for.
