### ISSUE TITLE
Allow creating Avro/CSR sources with older reader schemas, rather than forcing use of the latest

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#6170]
Today, if a user specifies a confluent schema registry, we will use the topic's most recent schema as the reader schema. In many cases this will not be what the user wants -- we should give a way to specify an older schema, or a custom inline schema. (In the latter case, it would also be good if we make schema resolution error messages better so people will understand what is going wrong if they give an incompatible schema).

**Comment by farslanku** [comment]
It might be good if another strategy than topicNameStrategy is possible. It might be by specifying the id of the schema, or specifying the version of a schema with a different name as well. One use case is, the reader might want to use an older version of the schema, and also might want to use a completely different schema. You might wonder why the latter is needed. Imagine a scenario where millions of messages with ten different topics will be merged into one topic to be read by Mz within a single source. If this merger service just pushes the data as bytes without dealing with any schema registration for performance reasons, it would be cool to process this in Mz.
On the other hand, it is not a super necessary request, because it is solved currently by just registering the schema with a rest call to the schema registry so that Mz can process it.

**Comment by sploiselle** [comment]
retiring old issue
