### ISSUE TITLE
Measure and improve speed of Kafka/avro sinks

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#6200]
We have done significant work to speed up Avro decoding (decoding directly into `Row`s, without building a useless, intermediate `avro::Value` object). However, we haven't done any corresponding thing for sinks. Furthermore, we have no benchmark or load tests for sinks.

**Comment by cuongdo** [comment]
@aljoscha is working on measuring the speed.

**Comment by aljoscha** [comment]
Ah sorry, @umanwizard, I didn't see this issue. I started looking into this for #6035

**Comment by aljoscha** [comment]
After quite some spelunking I (hopefully) have a decent understanding of the performance bottlenecks. Before that, here's a graph of how a simple Kafka -> Kafka pipeline gets rendered into a dataflow:

<img width="1088" alt="Screenshot 2021-04-12 at 20 02 05" src="https://user-images.githubusercontent.com/68551/114441691-fd950400-9bcb-11eb-9dd1-839625d5bbf2.png">

Some things to note here:

- Avro decoding happens in parallel on all workers
- For DEBEZIUM/UPSERT encoding we have `ArrangeByKey->combine_at_timestamp` which arranges and then sorts records by timestamp, to correctly determine `before`/`after` fields for DEBEZIUM  and to verify that we don't have multiple messages at the same timestamp for UPSERT
- The whole pipeline of arrange, combine at timestamp, Avro Encode, Kafka Sink happens on only one worker, which processes all the records

The three main performance bottlenecks I see are (I will expand on each of them below):

1. For the Sink, we do everything on one worker
2. We need the arrange/sorting to be able to emit DEBEZIUM/UPSERT records
3. (related to 2.) the arrange/sorting messes with the order of records, which forces the sink to keep a lot of queued records in memory

Side note: they're all quite related.

### Everything on one worker

For non-keyed data, I don't see yet what we can do. If we want to emit DEBEZIUM data it seems we need to do it from one worker. For keyed records (if the sink has only for UPSERT, AFAIK) we could parallelize by exchanging by key.

It would be nice if we could at least pull the Avro Encode step up in front of the Arrange but I think we can't do that because in order to be able to encode we need to first sort and determine the before/after fields.

It would really help to parallelize Avro encoding because it is the most expensive task the sink pipeline does.

### Need for Arrange/Sorting

I split this from "everything on one worker" because they're not strictly tied together. As I said above, we probably have to to it all on one worker for DEBEZIUM. For UPSERT, though, we might be able to exchange by key/hash. I still need to see if CDCv2 would also need the sorting step.

### Arrange/Sorting messes with the order of records

The sink uses the frontier to determine when it is "safe" to emit records. Without the Arrange/Sort operation, records would arrive at the sink right on the capability (and frontier), the sink could therefore get by without ever queuing records for later.

With arrange/sort in there, the records that the sink receives can be quite a bit beyond the frontier. In extreme cases, when the Kafka source reads fast enough, the sink is forced to queue almost the entire history of the topic before it can emit. In my testing of reading a topic with 20mm records, the sink will queue all 20mm records before it starts emitting. With larger topic sizes Materialize will OOM in this situation.

The problem seems to be that Arrange will receive all the records very quickly, it will then hold on to the earliest capability while it does its thing and only when all records have been processed can we move on. This is exacerbated by the fact that Kafka reading and Avro decoding can happen in parallel while the Arrange operation processes all records on only one worker. The source will quickly rip trough the input, leaving the Arrange operator to work through a huge backlog.

If the Arrange operation could work through its input more gradually, the sink would have to queue/stash fewer records. This happens, for example, when we run Materialize with only one worker. In this case, the source cannot read as quickly because it's sharing time with all the other operators.

**This is the part I still know least about. I have to read up on how Arrange works and why it behaves like this with the timestamps/frontiers.**

## Summary

The biggest problem is that the Sink has to queue too many records because of how the Arrange messes with the timestamps. Starting Materialize with a pre-filled Kafka topic can lead to OOM crashes.

The second problem is performance, mostly because we do everything on one worker. While this is not good, it is not as bad as crashing.

**Comment by umanwizard** [comment]
A few thoughts:

1. It's possible to encode Avro stuff in parallel; you would just need another stage after that to put everything back in order (because we must emit things to the sink in timestamp order). It might still be faster, but we would have to measure.
2. Avro encoding is extremely inefficient currently. We could get a multiple times speedup even on one worker by rewriting the avro encoder, as I did with the decoder last year, to completely avoid allocations while encoding.

**Comment by aljoscha** [comment]
https://docs.google.com/document/d/10tGqUf7GddJ-sB0nycfUzjgKFZjsjmyOVi0WZpUBYUg/edit#
