### ISSUE TITLE
Redundant table elimination does not kick in for outer joins

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6384]
If there is an outer join with a guaranteed-at-most-a-single-match join condition and a SELECT list that does not reference the right side of the join, then that side is redundant and can be thrown out altogether.

This is currently the case for inner joins:

```
materialize=> explain select a1.* from t1 as a1 join t1 as a2 ON (a1.key = a2.key);
           Optimized Plan            
-------------------------------------
 %0 =                               +
 | Get materialize.public.t1 (u7955)+
```

but not for outer joins:

```
materialize=> explain select a1.* from t1 as a1 left join t1 as a2 ON (a1.key = a2.key);
           Optimized Plan            
-------------------------------------
 %0 =                               +
 | Get materialize.public.t1 (u7955)+
 | Negate                           +
                                    +
 %1 =                               +
 | Get materialize.public.t1 (u7955)+
                                    +
 %2 =                               +
 | Union %0 %1                      +
 | Map null, null                   +
                                    +
 %3 =                               +
 | Get materialize.public.t1 (u7955)+
 | Project (#0, #1, #0, #1)         +
                                    +
 %4 =                               +
 | Union %2 %3                      +
 | Project (#0, #1)                 +
```

By contrast, postgresql is able to remove the redundant table even for outer joins:

```
pstoev=# create table t1 (key integer primary key, nokey integer);
CREATE TABLE
pstoev=#  explain select a1.* from t1 as a1 left join t1 as a2 ON (a1.key = a2.key);
                       QUERY PLAN                        
---------------------------------------------------------
 Seq Scan on t1 a1  (cost=0.00..32.60 rows=2260 width=8)
(1 row)
```

To get a source with a primary key semantics in MZ, run the following testdrive:

```
$ set keyschema={
    "type": "record",
    "name": "Key",
    "fields": [
        {"name": "key", "type": "string"}
    ]
  }

$ set schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"nokey", "type":"string"}
        ]
    }

$ kafka-create-topic topic=t1

> CREATE MATERIALIZED SOURCE t1
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC
  'testdrive-t1-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT
```

**Comment by wangandi** [comment]
Taking this for a new hire.

It seems that the way to fix this is to just add a new transform that notices that when an input is being unioned with its negation and cancels them out.

```
 %0 =                               +
 | Get materialize.public.t1 (u7955)+
 | Negate                           +
                                    +
 %1 =                               +
 | Get materialize.public.t1 (u7955)+
                                    +
 %2 =                               +
 | Union %0 %1                      +
 | Map null, null                   +
```
-----

Specs for the transform: 
For each subexpression matching `MirRelationExpr::Union { base: Box<MirRelationExpr>, inputs: Vec<MirRelationExpr>}`:
Check each input (this includes `base`) to see if it is a `MirRelationExpr::Negate`. If input `i` is a `Negate`, take the expression inside the `Negate` and see if there exists an input `j` that it matches. If such an input `j` exists, change the inputs `i` and `j` to be `MirRelationExpr::Constant` with zero rows but the same `RelationType` as `i`. 

(The responsibility for cleaning up the `MirRelationExpr::Constant`s lies with the `FoldConstant` transform.) 

-----

Testing the transform:

You can create the testdrive test the way Philip describes in the issue description, or you can create a sqllogictest (See sqllogictest guide [here](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/sqllogictest.md)). I personally prefer using sqllogictest whenever possible since it does not require turning Kafka on.
