### ISSUE TITLE
"Not using key due to error" warning in log should be an error in the stream, as data is being discarded

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6385]
### What version of Materialize are you using?

```
v0.7.2-dev (1221d30e7)
```

### What was the issue?

One is allowed to have a key schema without an ENVELOPE. This results in the following warning in the log:

```
2021-04-08T08:07:27.204915Z  WARN dataflow_types::types: Not using key due to error: Value schema missing primary key column: key
```

So this is a warning about an error in the source stream. I believe this should be treated as a full blown error in the source stream and reported to the SQL client. The key values being ingested are being discarded, which is an information loss of sorts.

### Is the issue reproducible? If so, please provide reproduction instructions.

Use this testdrive test:

```
$ set keyschema={
    "type": "record",
    "name": "Key",
    "fields": [
        {"name": "key", "type": "string"}
    ]
  }

$ set schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"nokey", "type":"string"}
        ]
    }

$ kafka-create-topic topic=t1

$ kafka-ingest format=avro topic=t1 key-format=avro key-schema=${keyschema} schema=${schema} publish=true
{"key": "key1"} {"nokey": "nokey1"}
{"key": "key2"} {"nokey": "nokey2"}

> CREATE MATERIALIZED SOURCE t1
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC
  'testdrive-t1-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'

> SELECT * FROM t1
nokey1
nokey2
```
Either the ```CREATE SOURCE``` or the ```SELECT``` should have failed . Instead, as the last SELECT shows, the key column/information has been lost altogether.

**Comment by aljoscha** [comment]
@philip-stoev As of https://github.com/MaterializeInc/materialize/pull/6487 the log message is no longer printed. Before that change, `DataEncoding::desc` would always have access to both the key and value avro schema and would do the check that logs the error message. Now, that code only gets a key schema if it really needs it.

I think it can be argued that ignoring the key of a message is fine, the same way that only reading a subset of columns from messages is fine. But I'm very happy to be convinced otherwise.

Maybe @quodlibetor (who did the changed mentioned above) also has an opinion on this.

**Comment by philip-stoev** [comment]
I think discarding keys is more serious than discarding columns, as the presence of those keys may be assumed downstream for all sorts of stuff. We should do our best to protect the customer from shooting themselves in the foot.

**Comment by aljoscha** [comment]
I dug a bit deeper. This was actually consciously changed to allow cases where the key cannot be used: https://github.com/MaterializeInc/materialize/pull/3679.

Some context: except for UPSERT sources, the _key_ from Kafka is only used as an optimization in the Debezium upsert logic. I think to automatically derive a primary key for the collection. Plus, the key columns always have to be a subset of the value columns for this to work, so the key never has any extra data on top of the columns.

Right now, if there were columns in the key that are not in the value, and if users tried to access those columns, that wouldn't work, but users would notice. I can see this as a potential feature request.

Regarding where this behaviour is problematic. What are the cases where users would shoot themselves in the foot when we don't use the Kafka _key_? If they  try to use columns from the key that are not there they would notice it (because the columns are not there). If they tried to use some unique key property that we don't know about from the key, they would also notice.

I did potentially discover a problem where that check is actually wrong in the current code base and we now don't even print a warning for that, could be a red herring, though. I will keep digging.

cc @umanwizard who did the relaxation in https://github.com/MaterializeInc/materialize/pull/3679.

**Comment by aljoscha** [comment]
For me, what's a bit more concerning is this test:

```
# Test that deduplication=full accepts mis-ordered Debezium data.

$ kafka-create-topic topic=misordered-dbz-data

$ set new-dbz-schema={
    "type": "record",
    "name": "envelope",
    "fields": [
      {
        "name": "before",
        "type": [
          {
            "name": "row",
            "type": "record",
            "fields": [
              {"name": "a", "type": "long"},
              {"name": "b", "type": "long"}
            ]
          },
          "null"
        ]
      },
      { "name": "after", "type": ["row", "null"] },
      {
        "name": "source",
        "type": {
          "type": "record",
          "name": "Source",
          "namespace": "io.debezium.connector.mysql",
          "fields": [
            {
              "name": "snapshot",
              "type": [
                {
                  "type": "string",
                  "connect.version": 1,
                  "connect.parameters": {
                    "allowed": "true,last,false"
                  },
                  "connect.default": "false",
                  "connect.name": "io.debezium.data.Enum"
                },
                "null"
              ],
              "default": "false"
            },
            {
              "name": "file",
              "type": "string"
            },
            {
              "name": "pos",
              "type": "long"
            },
            {
              "name": "row",
              "type": "int"
            }
          ],
          "connect.name": "io.debezium.connector.mysql.Source"
        }
      }
    ]
  }

$ set new-dbz-key-schema={"type": "record", "name": "row", "fields": [{"name": "a", "type": "long"}]}

$ kafka-ingest format=avro key-format=avro topic=misordered-dbz-data schema=${new-dbz-schema} key-schema=${new-dbz-key-schema} timestamp=1 publish=true
{"a": 5} {"before": null, "after": {"row":{"a": 5, "b": 3}}, "source": {"file": "binlog", "pos": 1, "row": 0, "snapshot": {"string": "true"}}}
{"a": 5} {"before": null, "after": {"row":{"a": 5, "b": 3}}, "source": {"file": "binlog", "pos": 1, "row": 0, "snapshot": {"string": "true"}}}
{"a": 1} {"before": null, "after": {"row":{"a": 1, "b": 1}}, "source": {"file": "binlog", "pos": 2, "row": 0, "snapshot": {"string": "false"}}}
{"a": 2} {"before": null, "after": {"row":{"a": 2, "b": 3}}, "source": {"file": "binlog", "pos": 1, "row": 0, "snapshot": {"string": "false"}}}
{"a": -1} {"before": null, "after": {"row":{"a": -1, "b": 7}}, "source": {"file": "binlog", "pos": 1, "row": 1, "snapshot": {"string": "false"}}}
{"a": 2} {"before": null, "after": {"row":{"a": 2, "b": 3}}, "source": {"file": "binlog", "pos": 1, "row": 0, "snapshot": {"string": "false"}}}
{"a": 1} {"before": null, "after": {"row":{"a": 1, "b": 1}}, "source": {"file": "binlog", "pos": 2, "row": 0, "snapshot": {"string": "false"}}}
{"a": 3} {"before": null, "after": {"row":{"a": 3, "b": 4}}, "source": {"file": "binlog2", "pos": 2, "row": 0, "snapshot": {"string": "false"}}}

> CREATE MATERIALIZED SOURCE misordered_dbz
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-misordered-dbz-data-${testdrive.seed}'
  WITH (deduplication = 'full')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE DEBEZIUM

> SELECT * FROM misordered_dbz
a b
---
1 1
2 3
-1 7
3 4
5 3
```
Is passes, and uses the key data correctly. If you remove the keys from the test, the test will fail because of wrong results. *BUT*  on `v0.7.2-dev (1221d30e7)` it would still log that warning about not using they key even though it seems to be using the key. The problem is that the verification logic compares the column names of the key (here `a`) against the `before`/`after` column names of the Debezium value schema.

**Comment by aljoscha** [comment]
I could see us doing some more targeted checks here, for example _make sure the key fits when requesting duplication = full_, which right now would silently not work if the key is not suitable.

**Comment by aljoscha** [comment]
I'll summarize the current behaviour and suggest things that we could do.

Our treatment of keys depends heavily on the source envelope:

 - With `ENVELOPE NONE` (the default), we completely ignore the Kafka key. We don't use it for anything internally, and users cannot access it in queries. I don't think there's harm in that, users will notice that they cannot access columns in they key. One exception might be when they just directly sink a `SELECT * from foo` to a source, and then notice that the columns that happen to be in the Kafka key are not written. Though we loose the information about whether Row columns come from the value or key after the source. For the use case where we care about the key, UPSERT sinks, users would notice because they have to manually specify the key fields on the sink, which would fail when the fields are missing.
 - With `ENVELOPE UPSERT`, we use the key in the upserting logic and users can use the fields of the key in queries.
 - With `ENVELOPE DEBEZIUM`, we use the key for deduplication when `deduplication = full` is requested. For this to work, the columns in the key must be a subset of the columns of the value. If this is not the case, we log a warning but continue, producing potentially different results, refer  to the "misordered-dbz" test I mentioned above. There's supposed to be no columns in the key that are not in the value, and users couldn't access those in queries.

Potential asks (future work):

 - Allow access to columns in the key with `ENVELOPE NONE`. This would treat the key as just data, similar to the columns in the value, with no other special significance (like with UPSERT).
 - Fail hard when `deduplication = full` is requested and the key is not suitable. This was purposefully relaxed in https://github.com/MaterializeInc/materialize/pull/3679.

(( I'm not 100% sure about the significance of keys with `ENVELOPE DEBEZIUM` when users don't request `deduplication = full`, but I think they are completely ignored. ))

@philip-stoev & @umanwizard Please take another look. :pray:

**Comment by umanwizard** [comment]
Having thought more about this, I don't think it's a P1 issue.

We should indeed fail hard for the `deduplication = full` case, because that's the only place where Kafka keys are semantically meaningful. For `UPSERT`, this is not an issue at all, and we probably shouldn't even warn (do we now?). For `DEBEZIUM`, this issue will only prevent various optimizations from being applied; it will not cause correctness issues.

Indeed, we do not allow people to access key columns currently, but that's a known issue and feature request that @quodlibetor is addressing in https://github.com/MaterializeInc/materialize/issues/5863 .

The only other really actionable thing here is to make it fail hard in the full dedupe case; @aljoscha do you plan to work on that?

**Comment by aljoscha** [comment]
> @aljoscha do you plan to work on that?

I would, yes. The change would be: when `ENVELOPE DEBEZIUM` and `deduplication = full` are requested we fail instead of logging a warning. I think that should already be it.

For `ENVELOPE UPSERT`, the key columns don't have to be a subset of the value columns, and we don't check or log anything.

**Comment by philip-stoev** [comment]
Apologies for the late response. Thank you very much for the discussion -- please proceed as you see fit. After  #5863 lands and keys are exposed, I will be able to check for any residual correctness issues that may have remained and provide provable test cases.
