### ISSUE TITLE
Support equality operator for arrays

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#6402]
Right now, we get this:
```
materialize=> select ARRAY[1,2,3] = ARRAY[1,2,3];
ERROR:  no overload for integer[] = integer[]: arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts
```

Postgres supports equality operations on arrays, along with a bunch of other operations that we currently don't support: https://www.postgresql.org/docs/12/functions-array.html

**Comment by uce** [comment]
The `=` operator was added as part of #6648.

I started into looking into the other equality operations and realized that our derived implementations of `Ord`/`PartialOrd` don't match the expected Postgres behaviour:

> The comparison operators compare the array contents element-by-element, using the default B-tree comparison function for the element data type, and sort based on the first difference. In multidimensional arrays the elements are visited in row-major order (last subscript varies most rapidly). If the contents of two arrays are equal but the dimensionality is different, the first difference in the dimensionality information determines the sort order.
> -- https://www.postgresql.org/docs/13/functions-array.html#ARRAY-OPERATORS-TABLE

We currently compare based on row-packed format and don't respect nesting when comparing elements, e.g. `ARRAY[[1]] < ARRAY[1]` would compare `[1] < 1` instead of `1 < 1`.
