### ISSUE TITLE
MIR: Allow metadata calculation to use memoized information

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#6615]
Currently, `MirScalarExpr::typ` and `MirRelationExpr::typ` are recursive functions.

We often find ourselves in the pattern where we do something akin to a post-order traversal of a `Mir*Expr`, and at each node, we call `Mir*Expr::typ`. The resulting performance is not great since the `typ` call results in recursing back down the entire subtree again.
https://github.com/MaterializeInc/materialize/blob/77145e6847b885eedc8aa40c5bae486f62a3fd20/src/expr/src/explain.rs#L186

Instead, during a post-order traversal of a `Mir*Expr`, we should be able to just calculate the RelationType of the current node based on the RelationTypes we have already calculated for its children node. 

I envision changing `visit_mut` so that instead of taking a function with argument `|e: Mir*Expr|`, the arguments would be `|e: Mir*Expr, children_types :Vec<RelationType>, e_type: RelationType|`.

**Comment by uce** [comment]
Frank pointed out that we would probably want to look at this more holistically as part of a potential optimizer pipeline refactoring.

**Comment by asenac** [comment]
If we wanted to avoid the recomputation of the type information during a fusion transform such as fusion::Join, we would need to keep and pass around a parallel tree with that information, instead of just a vector with the type of the inputs.

```rust
struct TypeInfo {
    typ: RelationType,
    inputs: Vec<Box<TypeInfo>>,
}
```

The `action` method invoked during the post order traversal would take the current relation and a `inputs: &mut Vec<Box<TypeInfo>>` vector with the type information of its inputs, so each transform would be responsible for updating the `inputs` vector if the layout of the relation changes.

When going up one level, the type information for the relation just visited will be computed by passing the `inputs` vector to `MirRelationType::typ` and returning a new node with its output plus the `inputs` vector.

A draft of this idea is outlined below:

```rust
pub struct TypeInfo {
    typ: repr::RelationType,
    input_types: Vec<Box<TypeInfo>>,
}

pub trait LocalTransform: std::fmt::Debug {
    fn transform(
        &self,
        relation: &mut MirRelationExpr,
        input_types: &mut Vec<TypeInfo>,
    ) -> Result<(), TransformError>;

    fn debug(&self) -> String {
        format!("{:?}", self)
    }
}

#[derive(Debug)]
pub struct PostOrderTransforms {
    transforms: Vec<Box<dyn LocalTransform + Send>>,
    stack: Vec<Vec<TypeInfo>>,
}

impl PostOrderTransforms {
    fn new(transforms: Vec<Box<dyn LocalTransform + Send>>) -> Self {
        Self {
            transforms,
            stack: vec![vec![]],
        }
    }
}

impl Transform for PostOrderTransforms {
    fn transform(
        &self,
        relation: &mut MirRelationExpr,
        _: TransformArgs,
    ) -> Result<(), TransformError> {
        let mut input_types = Vec::new();
        // note: MirRelationExpr::try_visit_mut now takes an instance of MirRelationExprMutVisitor
        relation.try_visit_mut(&mut self)?;
        Ok(())
    }
}

trait MirRelationExprMutVisitor<E> {
    fn pre(&mut self, relation: &mut MirRelationExpr) -> Result<(), E>;
    fn post(&mut self, relation: &mut MirRelationExpr) -> Result<(), E>;
}

impl MirRelationExprMutVisitor<TransformError> for PostOrderTransforms {
    fn pre(&mut self, relation: &mut MirRelationExpr) -> Result<(), TransformError> {
        self.stack.push(Vec::new());
        Ok(())
    }
    fn post(&mut self, relation: &mut MirRelationExpr) -> Result<(), TransformError> {
        let mut input_types = self.stack.pop().unwrap();
        for transform in self.transforms.iter() {
            // the transform is responsible for updating `input_types` if the layout
            // of the current relation changes
            transform.transform(relation, &mut input_types)?;
        }
        let input_types = input_types.drain(..).map(|e| Box::new(e)).collect_vec();
        // note: MirRelationExpr::typ now takes the type of its inputs as a parameter
        let typ = relation.typ(input_types.iter().map(|e| e.typ));
        self.stack
            .last()
            .unwrap()
            .push(TypeInfo { typ, input_types });
        Ok(())
    }
}
```

Eventually, this could be extended by adding more information we may want to cache in `TypeInfo` struct. This mechanism could be generalized to accommodate transforms that need to pass information around, like literals being lifted and such.
