### ISSUE TITLE
pg-cdc: CHAR type not handled, "unknown catalog item 'bpchar'" error on CREATE VIEWs

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6741]
### What version of Materialize are you using?

```
materialized v0.7.4-dev (adc7083b1)
```

### What was the issue?

```CHAR``` columns can not be replicated, as they arrive as postgres internal type of ```bpchar``` that is not understood by Mz.

### Is the issue reproducible? If so, please provide reproduction instructions.

On the postgres side:

```
postgres=# create table t8( f1 char(5));
CREATE TABLE
```

On the mz side:

```
materialize=> CREATE VIEWS FROM SOURCE "mz_source" (t8);
ERROR:  unknown catalog item 'bpchar'
```

otherwise the data seems correct in the source:

```
  oid  |                                          row_data                                           
...
 16539 | {"abc  "}
...
```

**Comment by petrosagg** [comment]
At the surface this is a problem with our parser because we should accept `bpchar` as a datatype. However, there is a more general problem I discovered. Materialize currently treats `char` columns as `text`, leading to incorrect results with respect to postgres. `char` and `bpchar` (blank padded char) store a string where the trailing white space is ignored. 

Here is the difference in behaviour:

postgres:
```sql
postgres=> CREATE TABLE foo3 (f1 char(4));
CREATE TABLE
postgres=> INSERT INTO foo3 VALUES ('1  ');
INSERT 0 1
postgres=> SELECT length(f1) FROM foo3;
 length
--------
      1
postgres=> SELECT pg_typeof(f1) FROM foo3;
 pg_typeof
-----------
 character
```

materialize:
```sql
materialize=> CREATE TABLE foo3 (f1 char(4));
CREATE TABLE
materialize=> INSERT INTO foo3 VALUES ('1  ');
INSERT 0 1
materialize=> SELECT length(f1) FROM foo3;
 length
--------
      3
materialize=> SELECT pg_typeof(f1) FROM foo3;
 pg_typeof
-----------
 text
```

I think I'll fix the parser to accept `bpchar` with the same behaviour as the current `char` (which is incorrect) and create a separate issue for fixing chars. What do you think?
