### ISSUE TITLE
storage/sources/postgres: support enum types

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6818]
### What version of Materialize are you using?

```
v0.7.4-dev (82ae64f89)
```

### What was the issue?

The ```ENUM``` type is not supported. ```CREATE SOURCE``` returns the following error:

```
db error: ERROR: unknown type OID: 16386
```

Materialize does not support ```ENUM``` , but Debezium is able to work around this by creating the source as ```TEXT```.

### Is the issue reproducible? If so, please provide reproduction instructions.

I intended to push the following test:

```
# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

#
# Test the ENUM data type
#


# Insert data pre-snapshot
$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER USER postgres WITH replication;
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TYPE enum1 AS ENUM ('val1', 'val2');
CREATE TABLE enum_type ( f1 enum1);
INSERT INTO enum_type VALUES ('val1'), ('val2');

CREATE PUBLICATION mz_source FOR ALL TABLES;

> CREATE MATERIALIZED SOURCE mz_source
  FROM POSTGRES HOST 'host=postgres port=5432 user=postgres password=postgres sslmode=require dbname=postgres'
  PUBLICATION 'mz_source';

> SELECT COUNT(*) > 0 FROM mz_source;
true

> CREATE VIEWS FROM SOURCE mz_source;

# Insert the same data post-snapshot
$ postgres-execute connection=postgres://postgres:postgres@postgres
INSERT INTO t1 SELECT * FROM t1;

> SELECT pg_typeof(f1) FROM t1 LIMIT 1;
text

> SELECT * FROM t1;
val1
val1
val2
val2
```

**Comment by philip-stoev** [comment]
HSTORE tool, which Debezium converts to JSON.

**Comment by benesch** [comment]
Before we do any automatic conversions, we should think through the backwards compatibility implications.

Let's say we follow Debezium and automatically convert enum to text and hstore to JSON. What do we do down the road if we add support for enum and hstore types to Materialize? Ideally we'd stop performing the conversion, and represent Postgres enums and hstores as enums and hstores in Materialize. Will that break existing Postgres sources that were expecting text/JSON columns rather than enum/hstore columns?

The solution could be as simple as requiring a `WITH (convert_enum_to_text)` option. Or perhaps this isn't an issue at all, because we hardcode the types when you run `CREATE VIEWS ... FROM SOURCE`. 

Anyway, my point is just that this is worth thinking through!

**Comment by philip-stoev** [comment]
having a WITH option would be a good compromise. The other way to "fix" this would be to get a more meaningful error message printed out ("type XXX not supported").

The case with ```MONEY``` may require a bit of background reading though -- it seems to me that if it is underlyingly stored in Pg as ```DECIMAL``` then it would be safe for it to be replicated into Mz as a ```DECIMAL```.

**Comment by rjnn** [comment]
We should support this by adding support for postgres ENUMs. I've renamed the issue.
https://www.postgresql.org/docs/current/datatype-enum.html

cc @ggnall

**Comment by benesch** [comment]
> We should support this by adding support for postgres ENUMs.

Right—that's always been the plan! This issue used to be about adding support for both enum types and the `hstore` type. We should file a separate issue for `hstore` before we close this, so that it doesn't get lost.

The open design question here is whether we need to support `CREATE TYPE AS ENUM`, and somehow sync enums between PostgreSQL and Materialize, or if we can just cast the enum to `text` for now. The latter will be _much_ easier, but as I mentioned in my last comment we should have a plan for how we might allow users to choose between the two behaviors in the future, if that becomes important.

**Comment by morsapaes** [comment]
Closing in favor of #25881. Opened a separate issue for the `hstore` data type (#25880).
