### ISSUE TITLE
debezium: write data in sinks in a way that can be read by our sources

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#6834]
As @cirego pointed out in https://github.com/MaterializeInc/materialize/pull/6795#issuecomment-846290293, the consistency data that we emit from sinks is not compatible with our source requirements.

Relevant comment in code: https://github.com/MaterializeInc/materialize/blob/4671e059bc490486aadb774dac6a78113a7fab8e/src/interchange/src/avro/encode.rs#L26

**Comment by aljoscha** [comment]
cc @ruchirK, who originally wrote that comment in the code

**Comment by antiguru** [comment]
In #7097 we added support for emitting the `data_collections` field to the consistency topic. This would allow downstream clients to determine which collection changed. In our case, it is trivially the same information included in `event_count`, because our topics always only cover a single source relation. This is a first step towards allowing our code to re-ingest our own sinks with de-duplication and exactly-once semantics.

Still, there is more work to be done on order to fully ingest our own sinks. The following list documents my findings, which may be incomplete/incorrect.
* We do not have a established mechanism to pass transaction metadata on topics to potential sources. Other Debezium sources emit what's called the `source` metadata, for example transaction IDs, LSN, etc. This information is used within Materialize to map a source's transaction information into progress information. Materialize sinks only emit the `transaction` attribute. Internally, we still look for the `source` attribute, and should probably keep doing so to maintain Debezium compatibility.
* We cannot easily change the schema of a sink because it is stored in the catalog. We would need to have a clear upgrade path if we were to change it, or document a breaking change. Currently, Materialize refuses to start when a source schema changes.
* The Avro schema we use to encode the consistency topic has to decide on the order of fields. Avro schema seem to be position-dependent and happily decode data in incorrect order.

Some of the changes can be found in #7033 (https://github.com/antiguru/materialize/tree/debezium_6834), but more work is needed to properly enable this feature.

**Comment by elindsey** [comment]
This is a concrete point of https://github.com/MaterializeInc/materialize/issues/3618, deduplicating
