### ISSUE TITLE
views + sources: gracefully handle invalid input

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#6861]
Right now, if you feed invalid input into an append-only source that gets plumbed to a view for which it throws an `EvalError`, there is no way to un-wedge the view. Is it possible to provide some other behavior? As a straw man, can we add an option to a view that understands that inputs that throw `EvalError` should be treated as e.g. `NULL`?

**Comment by aljoscha** [comment]
Some context from Flink, which probably shouldn't serve as a role model here:
 - there is no concept of *MATERIALIZED VIEWS*, or even *VIEWS*, that a Flink cluster would maintain/keep track of
 - when a SQL query is submitted, it is wholly self contained and cannot be interactively queried or further re-used
 - a SQL query is turned into a Flink Job, which runs on a Flink cluster. the cluster doesn't know about SQL or what's in the Job
 - mostly, queries read from a source and write to a sink
 - when there is an error, say a parsing error, the Flink job that resulted from that query will simply fail and not be restarted

This feels related to my comments here: https://github.com/MaterializeInc/materialize/pull/6843. The second to last item in the list (about dealing with errors).

**Comment by frankmcsherry** [comment]
It feels tricky to think up good "default" behavior, in part because it departs from postgres: if you have a table that you only insert into, postgres will keep giving you back errors no matter how many times you issue the query; you need a new query. We also have some other ways that errors can be introduced other than by scalar evaluation.

Some candidate ideas:
1. Provide a `MirScalarExpr::could_error()` method that would allow `EXPLAIN` to warn folks if their view could potentially error.
2. Provide a SQL method `NULLIFERROR(expr)` that converts errors into nulls. 
3. Encourage folks who are worried about this to `EXCEPT ALL` their CSV source with a table into which they can insert retractions (or `UNION ALL` and then submit negative records, but probably stress out some non-negativity invariants).
4. Allow folks to `SELECT` from the non-error collections (we maintain the right answers modulo erroring records, we just prevent you from seeing them with `SELECT`).

**Comment by benesch** [comment]
Closing in favor of #6367 and #22430.
