### ISSUE TITLE
Document how to use exactly-once sinks

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#7073]
We've added a new `exactly_once` WITH option (which needs to be documented).  Note that both `exactly_once` and `consistency_topic` need to be set for exactly_once to work.

example:
``` 
CREATE SINK output2 FROM input_rt
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'output-rt-sink-${testdrive.seed}'
  WITH (exactly_once=true, consistency_topic='output-sink-consistency-${testdrive.seed}')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}
```

Note that this is an experimental-only option. I don't recall the exact procedure for how to document this in the release notes

**Comment by krishmanoh2** [comment]
Does it make a difference if using envelope upsert/debezium ?

**Comment by awang** [comment]
the consistency topic is something we read from only on startup, and we write from periodically, e.g. once per second.  it's something we don't expect end-users to need to use, but it is something that Materialize needs to provide exactly-once.

both debezium and upsert sources should work. I know we’ve tested debezium sources but idk how much we’ve tested upsert sources

**Comment by msudberg** [comment]
Minor correction: `consistency_topic` remains the same, but the option `exactly_once` has been renamed `reuse_topic`. (Renaming is #7492 and discussion is in #7390.)

**Comment by aljoscha** [comment]
There is basic documentation now: https://github.com/MaterializeInc/materialize/blob/48d85e1/doc/user/content/sql/create-sink.md#enabling-topic-reuse-after-restart.

Do we want to add much more besides putting a sentence in there that mentions that compaction can be enabled on the consistency topic?

**Comment by krishmanoh2** [comment]
What happens if the consistency topic is deleted?

**Comment by krishmanoh2** [comment]
Is there a behavior difference - upsert versus debezium?

**Comment by aljoscha** [comment]
> What happens if the consistency topic is deleted?

If it is deleted while materialize is running, I expect there will be an error and the sink will fail. I will double check. If it's deleted while materialize is down, before restarting, you will get duplicate output. We basically "forget" what we have written so far and write it out again.

> Is there a behavior difference - upsert versus debezium?

There shouldn't be any difference.

**Comment by msudberg** [comment]
To summarize: 

1) Based on Slack discussions, we don't mention experimental features in release notes; they seem to be socialized on a case-by-case basis with appropriate clients. However, thanks to @aljoscha, this feature is now in beta and can be put in the release notes.

2) We have documented the `exactly_once` feature (now renamed `topic_reuse`) as a [`CREATE SINK`](https://materialize.com/docs/sql/create-sink/) option.

3) It sounds like we should add a guide on topic reuse to our new (more task-oriented) guides section which will cover:

- How to set up topic reuse
- How to control the size of the consistency topic (possibly also should be added to `CREATE SINK`)
- Examples of topic reuse with compaction and upsert
- Explain what happens when the consistency topic is deleted (should definitely be added to `CREATE SINK`)
