### ISSUE TITLE
persist: precisely define the domain of Datum

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#7141]
Context: I'm writing a PR that Encodes/Decodes Row into the Vec<u8> format we'll use to persist it. (The actual encoding we're using isn't the relevant bit for this issue.) In that PR, I'm writing "golden" tests which have various interesting Datums and hardcode the result of running Encode of them. The test then checks that Decoding the hardcoded bytes gets back the expected Datum; the intention is to catch any errors in reading back something we previously wrote.

At the moment, our definition of what exactly is an allowable value for each Datum type is imprecise. (I _think_ it currently is option (d) below). Int64 is straightforward enough to reason about but dates/times/decimals are harder. This leads to 2 problems:
1) It's unclear exactly which edge cases need to be included in the golden test.
2) It's difficult to write a low-level datadriven test involving various datums. Our current datadriven tests focus more around scripting data coming from postgres or kafka, but this is too heavyweight for unit tests. My original plan was to use the sql parser, but there are real edge cases we want to test that sql doesn't support but avro does.

We could work around (2) by not using datadriven but (1) would still be an issue. I feel like this is something we need to figure out before 1.0.

Specific example to spur discussion: datetime (without time zone)
- pgwire encodes datetimes as an int64 number of microseconds before/since 2000-01-01 00:00:00, so can represent microsecond increments for the ~300,000 years around that date.
- The avro spec has logical types for local-timestamp-millis and local-timestamp-micros which are int64 millis and micro offsets from the unix epoch (1970-01-01 00:00:00).
- I haven't looked extensively, but there could be others (ISO 8601 in a text file?)
- Internally, we represent this as a chrono NaiveDateTime, which stores this as an i32 date (documented as Jan 1, 262145 BCE to Dec 31, 262143 CE) and a (u32 sec, u32 nano) time, which can store any time on that day with nanosecond precision.

I realize dates 300,000 years in the future is very edge-case-y, but that's exactly one of the things I want to make sure we get right in the row encoding/decoding tests.

Some possible options for what we declare (and should then document) as the domain of allowable datetimes in mz:
a) The intersection of all datetime domains for all source and sink types/formats/encodings.
b) The union of all datetime domains for all source and sink types/formats/encodings.
c) Whatever postgres does.
d) Whatever our internal representation happens to support.
e) Something else

My initial reactions to these:
a) This is a bummer because we disallow stuff that's present in sources. It could be seriously limiting to the product for someone to have valid avro datetimes in kafka that we simply reject.
b) Maybe workable? This will mean that for each sink, there could be data in mz that we can't faithfully pass to it. But, we'll necessarily have to solve the UX issues for this at some point. Perhaps more worrisome is that adding support for any new source or sink would imply that we might need to do the work of expanding the domains of various types. Easy-ish if the internal representation happens to already cover them, probably very hard if it doesn't.
c) This worked well for CRDB but the only real way they have to get data into/out of the system was pgwire. We have other first-class sources and sinks, which may make this less of a good fit.
d) This ties us very closely to whatever we happen to be using as the internal representation right now. I'm not enough of a domain expert to have a useful opinion on how scary that is. In practice, chrono is probably fine, but we've already switched decimal libraries once so that one worries me a bit more. In theory, it's certainly worth considering leaving ourselves the option of swapping internals out.
e) Any ideas?

**Comment by danhhz** [comment]
cc @benesch @rjnn @frankmcsherry to help loop in whoever has an opinion on this/the stakeholders

**Comment by benesch** [comment]
Ooh, ok, so presented like this I think I have a definite preference for (b) over (c). I think the most compelling reason, having thought about it some more is that if you need to send one of those edge-case date/times over pgwire, you actually do have a workaround! You can do some math to get the date/time into a more primitive representation—e.g., one int64  decentrepresenting year/month/day and another int64 representing time of day. Whereas if Materialize can't represent your source format's date/time at all, you're just totally out of luck unless you preprocess your data. (Right? Does that make sense?)

cc @umanwizard too, since he has `Row` thoughts.

**Comment by benesch** [comment]
FWIW, not too worried about `Decimal`, because we've been moving in a direction of making it strictly more precise, not less. But the same isn't true of `chrono`, of course, because it has a much wider range than Postgres and I can see us wanting to turn that way down.

**Comment by umanwizard** [comment]
> But the same isn't true of chrono, of course, because it has a much wider range than Postgres

Dan's original post claims the Postgres range is +/- 300,000 years, and the Chrono range is from Jan 1, 262145 BCE to Dec 31, 262143 CE -- doesn't this imply that Chrono is actually narrower? (Though higher resolution)

**Comment by umanwizard** [comment]
I agree with Nikhil that option (b) seems the best.

**Comment by danhhz** [comment]
> Dan's original post claims the Postgres range is +/- 300,000 years, and the Chrono range is from Jan 1, 262145 BCE to Dec 31, 262143 CE -- doesn't this imply that Chrono is actually narrower? (Though higher resolution)

That's a great point. Just looked at the postgres docs, and it says `timestamp` supports from 4713 BC - 294276 AD. No idea why the truncation on the lower end (presumably borrowing some bits for something), but this does appear to be wider than chrono on the upper end (262143).

**Comment by danhhz** [comment]
Quickly tested this and postgres does allow dates outside the stated chrono range:
```
# select TIMESTAMP '262146-10-19 10:23:54';
       timestamp
-----------------------
 262146-10-19 10:23:54
(1 row)
```

I tried to see what materialize does, but it seems to cut out even before the end of the chrono range (seems like a parsing error?):
```
materialize=> select TIMESTAMP '2004-10-19 10:23:54';
      ?column?
---------------------
 2004-10-19 10:23:54
(1 row)

materialize=> select TIMESTAMP '262142-10-19 10:23:54';
ERROR:  invalid input syntax for type timestamp: expected_dur_like_tokens can only be called with HOUR, MINUTE, SECOND; got YEAR: "262142-10-19 10:23:54"
```

**Comment by mjibson** [comment]
An idea: consider our array and list types. They have many similarities, and arrays can be converted to lists. Lists exist to support things that postgres arrays don't do, including better support for avro. Lists however don't have a binary pgwire representation, so we force users to use some text representation if they want them over pgwire. What if we take the same approach to other types in avro that are different enough from the postgres equivalent, like an `AvroTimestamp` type? It could support conversion to and from normal timestamp (and of course error if it doesn't fit). This would allow us to make the date/time/timestamp/interval types match postgres more closely (excepting things like #https://github.com/MaterializeInc/materialize/issues/10566), and give us the freedom to support types either closely or exactly as their source representation.

Drawbacks to this:
1. A custom type must have its own pgwire binary representation, which requires us to provide modules for the various language drivers to support them (or, more realistically, just tell folks to either use pgwire text, or otherwise cast to text if their driver requires binary). These problems are exactly the same as the ux issues from b above, so even if we chose b we still have to figure this part out
2. There could reasonably be two versions of many types, which is a lot of types. But we already have array and list and thought it was reasonable to duplicate some work there. This would increase the amount of operator, cast, and function coverage we may have to support. But that kinda feels like not too difficult typing?

**Comment by benesch** [comment]
@mjibson: that sounds like a _fantastic_ idea. I love it.

I wonder if we should bump up the priority on [`DOMAIN`](https://www.postgresql.org/docs/current/sql-createdomain.html) types. Where the PostgreSQL types are wider than the Avro/Protobuf types, the `AvroTimestamp` type could just be defined as a domain over the PostgreSQL type. That could eliminate a lot of the typing. For example, Avro has a a "timestamp-millis" type that could easily be a domain over the normal timestamp type that rejects any timestamps with fractional milliseconds.

**Comment by aljoscha** [comment]
What, if anything, do we still want to do for this issue?

**Comment by mjibson** [comment]
I have taken this issue. My current plan is to implement (c), and change our date/time/timestamp types to do whatever postgres does, and have fallible casts when interfacing with avro.

**Comment by mjibson** [comment]
The current approach is actually a), the intersection of supported formats. We can at a future date add native avro/kafka types that support native ranges for those, but that's out of scope for our current release schedule.

**Comment by benesch** [comment]
SGTM! Thanks again for taking this one, @mjibson. Do you feel that we're on track for Oct 12?

**Comment by mjibson** [comment]
> Do you feel that we're on track for Oct 12?

Yes. Dates are done, timestamp pr is out. I believe the others will be smaller or are already safe.

**Comment by mjibson** [comment]
I believe all datums have been fixed or checked now.
