### ISSUE TITLE
Determining Once a View Is Up-To-Date

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#7142]
### Summary

When a user starts up Materialize, they want a way to determine when their views are caught up and ready to use. Obtaining this information should be user-friendly and queryable within Materialize, and will help users run Materialize in production more easily. This feature is of medium priority.

### Use Case

Upon restart of Materialize, all of the data has to be re-processed. Because of this, it takes some amount of time for views to get back up to date with Kafka. For example, if users have a month of customer data, when Materialize initially starts processing that data, the resulting view will be quite stale. In order to determine when a view is up to date, the current recommendation is to use the <code>consumer_lag</code> column in <code>mz_kafka_consumer_partitions</code>, which is a system table that contains a row for each partition being read by a Kafka consumer in the system. However, this is just a workaround and not the best long-term solution, and only works for Kafka. Implementing a queryable, user-friendly way to determine the status of a view will help users run Materialize in production more easily.

### User Stories

As a user of Materialize, after startup, I want to know when a view is caught up and ready to use.

### Functional Spec

**Related GH issues:** [3069](https://github.com/MaterializeInc/materialize/issues/3069) (similar issue)

Because this needs to be queryable, there should be a system table (either new or existing) which holds two columns:

- <code>offset_lag</code>: the number of offsets a particular view is behind (column type: <code>bigint</code>)
- <code>time_lag</code>: the amount of time in milliseconds a particular view is behind (column type: <code>int</code>)

Note this is also assuming we only need this feature for Kafka source types.

Additionally, we should expose this information on the [health check page](https://materialize.com/docs/ops/monitoring/#health-check).

### Appendix

[Internal Google doc](https://docs.google.com/document/d/1AWZr-0Y8YmmII8szDZ0YY3cYUs0HkwrIc6GSSicjppc/edit#)

**Comment by frankmcsherry** [comment]
Some quick thoughts:

1. I don't think `mz_views` is the right place for this information. That table holds information about view definitions, but these are not necessarily materialized views, just any old view in the system. Many won't exist in actual dataflows. We have instead `mz_materialization_frontiers` which contains per-materialization information about the timestamps completely reflected in each materialization.

2. I have to admit to being confused about what #4990 is calling for. The `mz_materialization_frontiers` collection has the times through which each materialization is current. It looks like the convo has evolved a bit, but work stalled out (and idk where it ended up).

What I think is missing is an associated between Kafka offsets and the MZ timestamps to which they correspond; this was the intent of #3069, though I'm sure under-articulated. It seems like this combined with `mz_materialization_dependencies` which relates materializations and the sources on which they depend would allow one to pull out the Kafka offsets reflected in each materialization whose sources are Kafka sources.

**Comment by nmeagan11** [comment]
@frankmcsherry that's a good point about <code>mz_views</code>. I was going by what is [documented](https://materialize.com/docs/sql/system-catalog/#mz_catalog), and have now realized that not all tables are listed there (related GH issue #3984).

As long as the requirement of having this be queryable within Materialize is met, then I'm satisfied. An idea is to combine the information between <code>mz_materialization_frontiers</code> and <code>mz_objects</code>, as it's not obvious to me in <code>mz_materialization_frontiers</code> alone what view a <code>global_id</code> is associated with (or perhaps there is another table I don't know exists).

cc: @elindsey and @benesch as I've talked to them both about this

**Comment by frankmcsherry** [comment]
I'm happiest if it is queryable too. The thing we've historically done that might fit is to create a new system view, which we define to be whatever query it takes to produce the associated results. I've also discussed this briefly with @antiguru who might be up for prototyping some queries based on what we have, and report back on what we are missing (perhaps picking up #4990). Not signing anyone up, but tagging in potentially interested parties.

**Comment by benesch** [comment]
To take what @frankmcsherry's been saying above even further: I don't think #4990 is a blocker for this issue. In fact this issue sounds much easier than #4990.

**Comment by nmeagan11** [comment]
I've updated the spec above to incorporate all feedback, specifically:

- removed mention of #4990
- tightened requirement around showing the lag for both offsets and time, and removed reference to any particular system table
- added requirement to expose this information on the health check page

@benesch i'm happy to close #4990 and iterate on this issue if you are

**Comment by elindsey** [comment]
I think the only data we're missing today is the kafka offset/mz ts association - with that we should be able to piece together a query from the existing system tables that shows the kafka offset lag per view. This was the original intent of #4990, but that task spiraled into a few different directions and should be closed (it's more confusing than helpful at this point). Tracking the kafka offset/mz ts mapping has also gotten easier with Ruchir's recent work done to support EOS.

Two things we may hit on the technical side: our max offset tracking relies on a separate metadata fetch loop due to librdkafka limitations, so the offset lag will be somewhat loose. If lag_time refers to the time between the recent tip of Kafka and the mz view updating then we'll hit two complications, one from tracking lag using two separate clocks on two machines, and two from needing to find an API that gives us the tip ts or ts for the current max offset (we may be able to get that from the metadata fetch loop, not sure).

**Comment by benesch** [comment]
> @benesch i'm happy to close #4990 and iterate on this issue if you are

Sounds great! Done.

**Comment by awang** [comment]
To confirm my behavior expectations -- 

1. Users would want to look at _both_ source lag (`consumer_lag` in `mz_kafka_consumer_partitions`) and the view lag to identify whether any parts of Materialize are lagging
2. This lag number will be appropriate, whether data is arriving or not.  Specifically, if no new source data is being ingested (and there is no view lag), both `offset_lag` and `time_lag` will report zero

**Comment by awang** [comment]
Here's an internal doc from @krishmanoh2 on a slightly different user workflow:  https://docs.google.com/presentation/d/1WsINKmuSn4g60ZOxSCT7lPwLbsBi4_5rEOvs8x41Rn0/edit#slide=id.ge33e9b3382_0_35

This allows users to distinguish between a view that is lagging and has no updates (`last_updated`)

**Comment by frankmcsherry** [comment]
> Users would want to look at both source lag (consumer_lag in mz_kafka_consumer_partitions) and the view lag to identify whether any parts of Materialize are lagging

Why do would they want source lag, if they have the view lag?

**Comment by frankmcsherry** [comment]
Also, I recommend to avoid confusion we maybe change the title to "Determining *Once* a View Is Up-To-Date" to indicate that this issue is / appears to be only communicating a single bit on start-up, rather than maintaining information about up-to-datedness as the source of data grows. I'd really like to do both, but as written the issue isn't about the latter.

**Comment by nmeagan11** [comment]
I agree that the spec is written specifically for start-up, and so I'm happy to change the title from _When_ to _Once_, and open a new issue specifically for the case where we are maintaining this information post start-up as the source of data grows.

**Comment by elindsey** [comment]
Summarizing the three remaining, concrete eng tasks that I see, in order:

1. Be able to answer "what Kafka source offsets are reflected in a given dependent view at its frontier"

This is https://github.com/MaterializeInc/materialize/issues/3069 and involves plumbing offset/mz ts mappings through logging in a way that they can be joined with mz_materialization_dependencies/mz_source_info/mz_materialization_frontiers.

2. Given 1, be able to answer "how far behind are those Kafka offsets from what we view as the current Kafka max offset"

This means the max offset that we currently poll for in the timestamper needs to be available internally. 

Note: "what we view as the current max" is because this max is polled for on a set interval, so it may give us a sawtooth pattern. There's no current workaround for that without significant librdkafka changes, but is relevant future work.

3. Given 1 and 2, extend it to be able to answer "according to Kafka's clock, what's the time difference between when those Kafka offsets were written and when what we view as the current Kafka max offset was written"

Conceptually this is extending the offset to a tuple of `(offset, time Kafka assigned when this offset was written)`. The tricky part will be finding appropriate Kafka APIs to get that information.

**Comment by antiguru** [comment]
I implemented a variant that allows users to observe the progress of the initial data loading using the system catalog: #7265. I'll go ahead an unassign myself.

**Comment by awang** [comment]
Some notes from today's discussion with one of the requestors:

* What happens if this query is slow to respond (especially when the system is loaded)? A slow responding query (1-2s) is "okay", but it's a bigger deal if it hangs altogether.
* (side note) Because of the above hanging issue, we brainstormed whether writing out to a sink as a temporary solution makes sense.  Some questions with the sink approach include: 
  * we only support avro ocf format today (something like json would be much easier to use)
  *  how often would the sink be written to? There might be also be a known issue with avro ocf (need to confirm).

**Comment by benesch** [comment]
> Some notes from today's discussion with one of the requestors:
> 
> * What happens if this query is slow to respond (especially when the system is loaded)? A slow responding query (1-2s) is "okay", but it's a bigger deal if it hangs altogether.
> * (side note) Because of the above hanging issue, we brainstormed whether writing out to a sink as a temporary solution makes sense.  Some questions with the sink approach include:
>   
>   * we only support avro ocf format today (something like json would be much easier to use)
>   * how often would the sink be written to? There might be also be a known issue with avro ocf (need to confirm).

The only solution to loss of interactivity is to fix loss of interactivity, as described in #1537. If the dataflow workers are wedged on compute, they are not writing sink records, so that's not actually a workaround.

**Comment by benesch** [comment]
The workflow graph in the console has largely solved this. The missing piece is source progress information, which we're tracking in #23154.
