### ISSUE TITLE
s3 csv: no way to remove header row, always ingested as normal data

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7145]
### What version of Materialize are you using?
cloud as of June 24th

### What was the issue?

The ```HEADER``` option is supported only for CSV file sources, not for CSV stored on S3. Therefore, the user has no choice but to have the header row ingested as regular data. There will be one such row per CSV file ingested.

I think this qualifies as a "wrong result" type of inconsistency issue. The only relatively fragile workaround is to create a materialized source on top of the S3 CSV source that filters out the header row.

Given that CSV file sources are not possible in Materialize cloud, s3 CSV remains the only option to ingest such data.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> CREATE MATERIALIZED SOURCE csv_example
FROM S3 DISCOVER OBJECTS MATCHING '**/*.csv' USING BUCKET SCAN 'philip-stoev-materialize', SQS NOTIFICATIONS 'philip-stoev-materialize'
WITH (region = 'eu-central-1' , access_key_id='...', secret_access_key = '...')
FORMAT CSV WITH HEADER;
ERROR:  CSV format with headers only works with file connectors
```

**Comment by benesch** [comment]
So, as discussed with @umanwizard and @awang in person, the issue here is that the `WITH HEADER` option auto-detects how many columns the CSV has and what their names are. This works great with file sources where there is only one CSV file. It it is harder with S3 because there are multiple CSV files, and those CSV files may have headers that disagree.

I think the proposal is to teach the SQL purifier to pick _one_ of the S3 objects at random and use the header from that file. Those aren't ideal semantics but probably workable.
