### ISSUE TITLE
mz_logical_timestamp errors for select versus create materialized view statements

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#7164]
### What version of Materialize are you using?

```
materialized v0.8.0 (b2fe225f1)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [x] Homebrew tap
* [ ] Built from source

### What was the issue?

I'm unsure if this is an actual bug or just a very confusing error statement which needs to be improved, but using `mz_logical_timestamp` for a temporal filter seems to expect a specific type when creating a materialized view, and not when writing a select statement.

### Is the issue reproducible? If so, please provide reproduction instructions.

Run Materialize and execute the following:

<pre>
<code>
materialize=> CREATE MATERIALIZED SOURCE market_orders_raw FROM PUBNUB
SUBSCRIBE KEY 'sub-c-4377ab04-f100-11e3-bffd-02ee2ddab7fe'
CHANNEL 'pubnub-market-orders';
materialize=> CREATE MATERIALIZED VIEW orders AS SELECT (text::json->'timestamp')::double precision as time, (text::json->'symbol')::text as sym, (text::json->'bid_price')::float as bid_price, (text::json->'order_quantity')::bigint as quantity, (text::json->'trade_type')::text as order_type from market_orders_raw;
materialize=> SELECT sym,count(*) FROM orders WHERE mz_logical_timestamp() >= 1000*time AND mz_logical_timestamp() < 1000*time + 5000 GROUP BY sym;
      sym      | count 
---------------+-------
 "Apple"       |     2
 "Google"      |     3
 "Elerium"     |     2
 "Bespin Gas"  |     3
 "Linen Cloth" |     7
(5 rows)

materialize=> CREATE MATERIALIZED VIEW valid_orders AS SELECT sym,count(*) FROM orders WHERE mz_logical_timestamp() >= 1000*time AND mz_logical_timestamp() < 1000*time + 5000 GROUP BY sym;
ERROR:  "Unsupported temporal predicate: `mz_logical_timestamp()` must be directly compared to a non-temporal expression "
</code>
</pre>

Casting time to numeric seems to fix this:

<pre>
<code>materialize=> CREATE MATERIALIZED VIEW valid_orders AS SELECT sym,count(*) FROM orders WHERE mz_logical_timestamp() >= 1000*time::numeric AND mz_logical_timestamp() < 1000*time::numeric + 5000 GROUP BY sym;
CREATE VIEW
materialize=> select * from valid_orders;
      sym      | count 
---------------+-------
 "Apple"       |     3
 "Google"      |     3
 "Elerium"     |     5
 "Bespin Gas"  |     3
 "Linen Cloth" |     2
(5 rows)</code>
</pre>

Obviously, I could change my <code>CREATE MATERIALIZED VIEW orders</code> statement to cast time to a numeric off the bat, but it's unclear to me (and not noted in the [documentation](https://materialize.com/docs/sql/functions/now_and_mz_logical_timestamp/#example)) that it requires strictly a numeric type for the time column, and further more that it works in a SELECT statement but not in creating a materialized view.

**Comment by benesch** [comment]
So @frankmcsherry the reason this happens is that the SQL fragment

```
mz_logical_timestamp() < 10::float
```

gets planned as:

```
            CallBinary(<)  -----------------+
       /                                    |
CallUnary(CastNumericToFloat64)         Literal(100.0)
      |
mz_logical_timestamp()
```

That is, because the comparison occurs on two different types, both types are
cast to a common type—in this case, double precision. Because the cast gets
injected on the mz_logical_timestamp side, this hides the comparison from the
temporal filter detector.

Contrast to `mz_logical_timestamp() < 1::int`, where instead a cast to numeric
gets injected on the RHS, and (I suspect) the temporal filter logic works just
fine.

Not sure what the right fix is. I think just a better error message would do the
trick (e.g., "you need to compare mz_logical_timestamp to a value of type
`numeric`, not `real`), but not sure how best to detect that. Detecting the
injected promotion to double precision is a little bit gross, but so is sniffing
out temporal filters in the SQL planner.

**Comment by frankmcsherry** [comment]
I think it should be easy to change the error message to be 
```
ERROR:  "Unsupported temporal predicate: `mz_logical_timestamp()` must be directly compared to a numeric non-temporal expression"
```
The function `mz_logical_timestamp()` is documented as being of type `numeric`; I don't think we've documented our type promotion rules.

**Comment by benesch** [comment]
While that is an improvement I fear the `numeric` qualifier will be lost in the error message, and we'll need to provide an even more explicit hint to users. 

This will be easy-ish once @sploiselle lands the APD refactor. At the moment it's hard to detect the injection of the `CastNumericToFloat64` cast because it's not one function call but a multiplication and some other crap.
