### ISSUE TITLE
docs: s3 csv docs describe ENVELOPE but it's not listed in syntax diagram

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#7166]

**Comment by petrosagg** [comment]
for whoever picks this up, the same is true for file sources

**Comment by msudberg** [comment]
@mjibson @petrosagg - Do the S3-CSV and the file sources support anything but append-only envelopes? Because right now that looks like the only option, and therefore specifying `ENVELOPE NONE` (the default) is the same as not specifying anything. For simplicity's sake, I think it's worth not cluttering up the RR diagrams.

**Comment by mjibson** [comment]
I don't know! I noticed this because I was trying to learn about how these worked at all.
