### ISSUE TITLE
persist: specifically how should coord+dataflow+persist work for table INSERTs (and other writes)

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#7424]
I wanted to discuss concretely how INSERTs should work in a world with both persistence and a multi-machine deployment. An analogous question exists for persisted sources but I think the answer to this will be informative for that.

Assumptions
- The coordinator shouldn't acknowledge an INSERT to a user before it's been durably persisted. I don't think this is controversial, but if it is, let's discuss sideband.
  - Given that the coordinator doesn't allow blocking work at the point of insert, it needs some sort of notification that the INSERT has been persisted.
- In the future, we'd like to support deployments with one coordinator, but several dataflow machines. (This is my understanding of our initial scale-out architecture, please correct if I'm wrong.) One consequence of this is that the coordinator cannot rely on being in the same process as every dataflow worker.

Question
- Do we plan on the coordinator at some point directly handing an INSERT to a dataflow input handle (and leaving any resharding/cross-process communication entirely to dataflow)? This would rule out a deployment shape where we have a pure coordinator process and pure dataflow processes. The alternative is (presumably) that the coordinator has some sort of rpc mechanism within itself. I have no opinion either way, just trying to understand our plans.

Some options, perhaps there are others I'm missing
- (1) The coordinator is entirely responsible for persisting tables. Any new writes are made durable before handing them to dataflow. On restart, the replayed writes are presented to dataflow indistinguishable from new writes.
  - This works well from a new data perspective, but it's a little awkward when the process restarts and replays new data. This replay processing ends up being a pretty natural fit as a dataflow operator but AFAIU doesn't fit the coord paradigm as well. Workable but unfortunate.
  - The persistence core provides (will soon provide) indexed access to the persisted data. It should be possible to adapt this to be presented to dataflow as a Trace (even Arranged). Option (1) prevents us from taking advantage of this and also means that we may make a (fairly redundant) in-memory arrangement. It's unclear how others feel about how workable/worthwhile this is.
- (2) Coord directly talks to an input handle from a dataflow operator responsible for persisting it. This assumes the answer to my question above is that coord always has an in-process dataflow worker.
  - We're still working out how to map dataflow's correctness semantics to a persistent operator, but I'm optimistic that we can do it.
  - (a) One variant of this is that this boundary involves a callback/channel from dataflow to coord. We can, morally and in code, put this bit on the "sources" side of the dataflow crate when we split it.
  - (b) Another variant involves coord watching dataflow progress and using that to ungate the INSERT response. Polling a probe would work but it'd be nice to avoid polling.
- (3) Coord talks to the dataflow input handle (potentially on another machine) through RPC. This assumes the other answer to my question above.
  - Presumably the RPC response is used to signal that the INSERT has been persisted and coord can respond to the user. The non-coord side of this RPC then has a similar problem which needs to be solved with something like (1) or (2).

**Comment by danhhz** [comment]
cc @frankmcsherry @benesch @ruchirK thoughts?

**Comment by frankmcsherry** [comment]
This is all "forward looking" vs "this month" but:

Imo, (1) has a lot of nice things going for it. We probably avoid some complexity due to multiple paths along which data could move and arrive. Not just for dataflow, but e.g. "storage accounting", idk other attendant services.

Based on reading perhaps too much into it, maybe "The coordinator is entirely responsible for persisting tables" is too strong and ~entirely~ should get struck; the coordinator could be in charge of getting the data to a common storage layer, neither by writing it down itself nor by routing it to a running dataflow. E.g. by handing it off to a storage mechanism that can return with a notification when something is durable. Something kin to "INSERT writes the data to Kafka/S3".

> but it's a little awkward when the process restarts and replays new data.

I think you mean here "if the coordinator needs to replay the data itself" which does sound bad. It seems less bad if the coordinator puts the data somewhere like a storage layer though, right?

> Coord directly talks to an input handle ...

I think the coordinator piloting the data around may end up with scalability issues. At least, I'm not sure what the story would be for fivetran style use, where large volumes of data are showing up as large batch DML statements. I think the coordinator would probably like to route these off to "storage" asap (perhaps not even seeing the data at all, if it can avoid it). I'm also less clear what happens if e.g. the coordinator decides some dataflow should be spun up at a different scale, or with a different plan; would it mirror the table contents so that it can re-state them at the new dataflow?

If it turns out that dataflow is just the coord's way of starting persistence work, we could break those apart as responsibilities and think about the storage layer independent of the dataflow layer (and allow folks to interact directly with the storage layer).

**Comment by danhhz** [comment]
Yeah, sorry if I was unclear about "forward looking" vs "this month"! I find it helpful to understand where we are headed.

I've thought a bunch about what you've said in this issue and my README PR, but I'm finding it hard to coherently express my thoughts without an answer to the following question, so please allow me to ask it first.

I have always imagined the boundary between the "messy interface with the external world" part of what is currently src/dataflow and the "single correct answer" part would be the boundary between two differential operators. Eliding all kinds of detail, for a table this looks like:

    InputHandle -> [persistence operator] *->* [arrange operator]

In this world, everything after the `*->*` is deterministic and has a single correct answer in terms of what goes through it. For a source it looks something like:

    [kafka operator] -> [persistence operator] *->* [sql operator] -> [sql operator] -> [arrange operator]

You mention option (1) has some nice things going for it. For a table, this looks something like:

    (coord and persistence, but not in dataflow operators) *->* InputHandle -> [input operator] -> [arrange operator]

Please correct me if I'm reading too much into it, but from [your comment on the source trait PR](https://github.com/MaterializeInc/materialize/pull/7400#discussion_r668849835), I'm guessing you also prefer something analogous for sources. Perhaps something like:

    (kafka and persistence, but not in dataflow operators) *->* InputHandle -> [input operator] -> [sql operator] -> [sql operator] -> [arrange operator]

Broadly, in the first two, the boundary where things start having a single correct answer is between two dataflow operators and in the second it's the InputHandle at the beginning of the dataflow. Both approaches seem very much workable to me. I suspect (though I'm not yet confidant) that there are some nice things that come out of the first way and I don't see strong advantages to the second. But my read is that you have the opposite opinion, is that right? If so, what am I missing?

(To be explicit: I'm not yet arguing for the first, just looking right now to fill what appears to be a gap in my understanding.)

**Comment by frankmcsherry** [comment]
> But my read is that you have the opposite opinion, is that right? 

I'm sorry, I'm a bit confused about which things are "the first two" vs "the second" etc.

I roughly imagine a pipeline, not necessarily a "dataflow" but could be, that looks like
```
[data arrives] -> [persisted, with timestamps] *->* [dead simple source operator; cdc like] -> [differential stuff] -> [beyond]
```
The `*->*` link does not have a hard requirement to co-locate its two endpoints: imo, "storage" and "compute". It might be nice to do, because less communicating, but it isn't mandatory in the way that the various differential bits do need to be co-located (e.g. because progress tracking needs to happen).

The `*->*` link is also a natural isolation boundary, where we might e.g. want the right hand side of the link to be able to start up, shut down, stall out, etc without negatively impacting the left hand side of the link. We might want to be able to run the left hand side even without a right hand side at all. We might want to transition between different instantiations of the right hand side (numbers of workers, versions of MZ, re-optimized query plans) none of which needs to interrupt the act of durably persisting the input data.

So, I think for me the `*->*` as I think it is being used above seems to be a natural decoupling point between a thing that I think we want to be pretty stable and predictable (persisting) and parts that we expect to go up and down for reasons good and bad (compute).

Is that clarifying? I'm not sure if I answered the right questions, but maybe it helps!

**Comment by danhhz** [comment]
Aha it is!

To say this back and make sure I have it, `[persisted, with timestamps]` and `[dead simple source operator; cdc like]` are potentially even on different machines. Would that mean `[dead simple source operator; cdc like]` is then the bit responsible for replaying the persisted data on restart? (If it instead was `[persisted, with timestamps]`, then we're potentially grabbing data from s3 just to send it back out over the network which feels wasteful.)

Also, does "cdc like" in `[dead simple source operator; cdc like]` mean cdcv2? If so, what do you see as the advantage of that here over something that's closer to a timely capture event stream?

**Comment by frankmcsherry** [comment]
> ... are potentially even on different machines.

Yes, especially if the differential dataflow stuff is likely to hose a machine. Maybe different processes? No strong feels here, but looking toward the future, probably different .. machines/process/containers/idk. It misses out on cheap handing around of pointers if in the same address space, but .. since those pointers probably (maybe?) needed to round-trip through disk for persistence maybe not so much? The story for optimistic concurrency could be easier on the same machine, but I think the "disaggregate storage and compute" story is pretty compelling.

> Would that mean [dead simple source operator; cdc like] is then the bit responsible for replaying the persisted data on restart?

Yes, in my half-thought-through take. I kinda imagine "restart" being "turn on these dataflows, starting from these times" which will prompt a pull of accumulated data up through those times, and initiate a tap on the stream from that time too. But, as a thing that storage is able to provide (e.g. a few S3 buckets/blobs, and a Kafka topic/offsets) on demand (w/o having a prior established relationship with the starting up dataflows).

> Also, does "cdc like" in [dead simple source operator; cdc like] mean cdcv2?

Not necessarily, sorry. I just meant "capable of producing all the data, times, diffs, and progress stuff on its own". Could certainly be a mix of e.g. arrangement batches and streamed diffs; whatever is handiest, but w/o any guesswork about what times should things have.

I should say, this is all one take that follows I think a "standard" disaggregated architecture, which might be missing a bunch of important nuance. For example, folks who show up with their own Kafka topics .. probably don't want to have to copy all of their data into `[persisted, with timestamps]`, and perhaps the storage module is equally happy holding on to topic information and "reclocking" sidecar data (I should have linked you at earlier: https://github.com/MaterializeInc/materialize/pull/7422). There could be other reasons this isn't as trivial as "spin up storage nodes here, compute nodes there", and it certainly gives up some peak performance. All negotiable, but the above is representative of the disaggregated architecture.

**Comment by frankmcsherry** [comment]
> The story for optimistic concurrency could be easier on the same machine, but I think the "disaggregate storage and compute" story is pretty compelling.

A follow up thought: the `[persisted, with timestamps]` module may have flavors of roles that might make getting data to the workers differently easy:
1. For TABLE data, and let's say other "volatile" sources, everything probably goes through the module. It's too scary to show it to computation without writing it down first / being very concerned.
2. For Kafka data, and other sources that are largely durable, but not in their final form, the module may only need to mint and hand out durable offset -> timestamp bindings. It probably also collects the data for batching and compaction, but this isn't on the critical path. 
3. For any magical CDC data, the module would just be about collecting the data for batching and compaction off the critical path.

So, in this take, the `[persisted, with timestamps]` module may be responsible for persisting the data on the critical path, and may be responsible for minting and persisting timestamp data on the critical path, but it also might only need to do a subset of that on the critical path. It would still want to present back compacted data for new instances of sources, but all of that compaction work can probably happen quietly to the side, and when cycles are available (it would only influence how long until we can GC the Kafka data / allow the postgres replication slot to drop records / etc).

**Comment by danhhz** [comment]
I'm sold. I've been thinking so far of being able to separate storage and compute as s3 and then materialize. This is more like mzstorage and mzcompute and it definitely makes more sense as a boundary between the two.

I feel like the OP has been clarified enough that I'm going to close this issue and update #7356 with this thinking.

> The story for optimistic concurrency could be easier on the same machine

What's being concurrently read/written here?

**Comment by frankmcsherry** [comment]
Ah sorry, the concurrency between query answering and input persisting. So, you could get started on the computation, produce the results, and only surface/commit the results once the corresponding input timestamps are made durable.
