### ISSUE TITLE
sql: allow configuring TAIL to prevent compacting if it client disconnects

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#7435]
If a client unexpectedly disconnects from TAILing some data, users would like to be able to do a TAIL AS OF from a new connection based on the previous `mz_time` received. This probably won't work, though, since we'll have compacted the timestamps. Do something so that we can prevent compaction until there's another TAIL going.

**Comment by mjibson** [comment]
One way to do this is configure a higher compaction time with `ALTER INDEX some_primary_idx SET (logical_compaction_window = '5min')`, so I think we want to demonstrate why that's difficult or problematic before adding this feature.

**Comment by frankmcsherry** [comment]
This is very close to being supported in the `Controller`. It explicitly watches for compaction commands for sinks (e.g. tail) and will not allow compaction if the sink is not "allowed to compact". What that means for TAIL is likely "user acknowledged the updates".

cc: @umanwizard as de-sinkifying TAIL clashes a bit with this, and we might want to sort out what that mean (potentially, that `Tail` still needs a `GlobalId` so that we can speak about it).

**Comment by benesch** [comment]
Note that this is very tightly related to #17541. Durable subscribes sound like exactly the right way to indicate to Materialize that you want your subscribe to survive a client disconnect.

**Comment by benesch** [comment]
Superseded by read holds: https://github.com/MaterializeInc/materialize/issues/22835. 🎉
