### ISSUE TITLE
Environment variable CREATE...WITH options

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#7467]
See https://github.com/MaterializeInc/product/issues/118 for original, raw user request (internal-only).

In order to satisfy "encryption at rest", a user would like to avoid storing unencrypted secrets in Materialize's catalog file.  One way to do so is to pass these secrets to Materialize via environment variable. (there may be better options that we haven't yet explored)  These secrets will then be passed to the instance Materialize is running on via the customer's secrets management platform.

Some examples of secrets that they would want to pass in this format are `sasl_password` ([Kafka sources](https://materialize.com/docs/sql/create-source/text-kafka/#kerberos-with-options)), and `secret_access_key` ([S3 sources](https://materialize.com/docs/sql/create-source/text-s3/)).  Note that environment variables are [already supported for S3 sources](https://materialize.com/docs/sql/create-source/text-s3/#aws-credentials-with-options).

### Option 1

To make this as consistent as possible with what we're already doing for S3, one possible method is something like:

If `sasl_username` is specified but not `sasl_password`, then check for the environment variable `KAFKA_SASL_PASSWORD`.

### Option 2
One downside of Option 1 is that all sources need to use the same secret. Another option could be to add new WITH options, such as `env_sasl_password`, where the corresponding environment variable is used.

cc @benesch because this proposal might be completely different from what he is thinking of

**Comment by benesch** [comment]
Yeah, option 2 is what I was thinking of, except with a suffix rather than a prefix (`sasl_password_env`, possibly `sasl_password_file` one day.)

Default environment variables are supported for S3 sources because they're just a total requirement for dealing with anything AWS related. We should try to avoid inventing anything similar for other sources though unless there is already a standard. Implicit configuration like that causes no shortage of headaches. Option 2 is the way to go.
