### ISSUE TITLE
Enable `debug-assertions = true` in CI/test

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#7473]
We currently use release builds in CI, as these same binaries are then deployed. However, we would like to observe debug panics as part of our test workflow as e.g. integer overflow, and other `debug_assert!` lines indicates errors. However, we don't want to ship that code at users, maybe.

So, not obvious how to fix, without distinguishing between test binaries and shipped binaries.

**Comment by benesch** [comment]
Yeah, it's definitely a little thorny, because there are moments where you want to do black box testing of literally the same bits you ship to customers, which our current tests are great at, and then there are moments you want to do white box testing and put your fingers on the scale in exchange for more information, which our current tests don't really allow for. 

One thing we could consider is an assertion that is enabled dynamically at runtime. We could add a macro like `mz_debug_assert!`:

```rust
// Elsewhere
static DEBUG_ASSERTS: AtomicBool = AtomicBool::new(false);

macro_rules mz_debug_assert! {
    ($arg:...) => {
        if DEBUG_ASSERTS.get() {
            assert!($arg...)
        }
    }
}
```

and then you could enable these debug assertions via a CLI flag or env var or something.
