### ISSUE TITLE
sql: wrong results with outer join due to incorrect name resolution

### ISSUE THREAD

**Issue by asenac** [MaterializeInc/materialize#7618]
### What version of Materialize are you using?

```
$ materialized -v

```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [x] Built from source
* [ ] Materialize Cloud

### What was the issue?

Postgres;

```
asenac=> create table t1(f1 int, f2 int);
CREATE TABLE
asenac=> create table t2(f1 int, f2 int);
CREATE TABLE
asenac=> insert into t1 values (1, 2);
INSERT 0 1
asenac=> select * from t1 left join t2 using (f1) where t2.f1 is not null;
 f1 | f2 | f2 
----+----+----
(0 rows)

asenac=> 
```

Materialize:

```
materialize=> select * from t1 left join t2 using (f1);
 f1 | f2 | f2 
----+----+----
  1 |  2 |   
(1 row)

materialize=> select * from t1 left join t2 using (f1) where t2.f1 is not null;                                                                                                                             
 f1 | f2 | f2 
----+----+----
  1 |  2 |   
(1 row)

materialize=>
```

`t2.f1` is resolved erroneously as `t1.f1`. Same happens for natural outer joins.

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, same as above.

**Comment by sploiselle** [comment]
The issue here is that `USING` joins perform a coalesce on the joined columns, and then project away the inputs. In this case, we project `coalesce(t1.f1, t2.t1)`, and then "drop" `t1.f1` and `t2.f1`, so neither survive the `FROM` planning.

This means that `t2.f1 IS NOT NULL` is getting rewritten not to `t1.f1 IS NOT NULL`, but more like `coalesce(t1.f1, t2.f2) IS NOT NULL`.

The fix to this is some version of delaying the projection that occurs during `plan_using_constraint` until _after_ planning the `WHERE` clause. I'll do a more thorough investigation later, but it's possible that this situation is unique to `USING` because it's maybe the only `FROM` expression that projects away columns.

**Comment by philip-stoev** [comment]
I am setting this to P2 as it has the potential to affect a wide set of queries.

**Comment by sploiselle** [comment]
Just for an update that I've continued tinkering with this but the problem is tricky when applying `USING` to the same column more than once. I have a sketch of an approach that's promising but need to spend some time on fleshing it out.
