### ISSUE TITLE
repr,sql: support unsigned types

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#7629]
Currently we follow PostgreSQL and support only signed integer types. We should add support for the corresponding unsigned integer types as well:

  * `uint2` (16-bit unsigned int)
  * `uint4` (32-bit unsigned int)
  * `uint8` (64-bit unsigned int)

The most motivating use case right now is supporting ingest from Protobuf messages that use unsigned types. See https://github.com/MaterializeInc/materialize/pull/7623 for some context there.

As usual, Tom Lane shows the way. See [this message](https://www.postgresql.org/message-id/29540.1217014326%40sss.pgh.pa.us) from pgsql-hackers:

> Consider the idea of not having any uint4-specific arithmetic operators,
> but instead providing the following:
> 
> 
> 	* assignment casts from int4 and int8 to uint4
> 	  (these throw error if out of range, of course)
> 	* implicit cast from uint4 to int8 (can never fail)
> 
> 
> The effect of providing the latter cast would be that any arithmetic
> involving a uint4 column would automatically be done in int8.  Which
> would make it a shade slower than a native implementation, but probably
> not enough slower to be a problem --- and you'd avoid having to write
> dozens of operators and underlying support functions.  Storing into the
> uint4 column would work fine with no extra notation because of the
> assignment casts.
> 
> Moreover, you'd avoid cluttering the system with a pile of cross-type
> operators, which we have recently realized are not a good thing, because
> they increase the likelihood of "ambiguous operator" problems --- see
> http://archives.postgresql.org/pgsql-hackers/2008-06/msg00750.php
> 
> 
> For uint8 you'd have to promote to numeric to guarantee no failure
> in the implicit cast; which is going to be a rather bigger performance
> hit, but I don't really see uint8 as being a type with huge demand.

See also [pguint](https://github.com/petere/pguint), a PostgreSQL extension from one of the core developers that adds the above types to PostgreSQL, plus `int8` and `uint8`. The approach taken there was to codegen hundreds of functions to support e.g. `int4 < uint4`, `int4 + uint8`, .... 

Roughly, I think these are the casts we'd want to support:

From | To | Type
--|--|--
`uint2` | `text` | Assignment
`text` | `uint2` | Explicit
`uint4` | `text` | Assignment
`text` | `uint4` | Assignment
`uint8` | `text` | Assignment
`text` | `uint8` | Assignment
`uint2` | `uint4` | Implicit
`uint2` | `uint8` | Implicit
`uint2` | `int4` | Implicit
`uint2` | `int8` | Implicit
`uint2` | `numeric` | Implicit
`uint2` | `float4` | Implicit
`uint2` | `float8` | Implicit
`uint4` | `uint2` | Assignment
`uint4` | `uint8` | Implicit
`uint4` | `int4` | Assignment
`uint4` | `int8` | Implicit
`uint4` | `numeric` | Implicit
`uint4` | `float4` | Implicit
`uint4` | `float8` | Implicit
`uint8` | `uint2` | Assignment
`uint8` | `uint4` | Assignment
`uint8` | `int4` | Assignment
`uint8` | `int8` | Assignment
`uint8` | `numeric` | Implicit
`uint8` | `float4` | Implicit
`uint8` | `float8` | Implicit
`int2` | `uint2` | Assignment
`int2` | `uint4` | Assignment
`int2` | `uint8` | Assignment
`int4` | `uint2` | Assignment
`int4` | `uint4` | Assignment
`int4` | `uint8` | Assignment
`int8` | `uint2` | Assignment
`int8` | `uint4` | Assignment
`int8` | `uint8` | Assignment
`numeric` | `uint2` | Assignment
`numeric` | `uint4` | Assignment
`numeric` | `uint8` | Assignment
`float4` | `uint2` | Assignment
`float4` | `uint4` | Assignment
`float4` | `uint8` | Assignment
`float8` | `uint2` | Assignment
`float8` | `uint4` | Assignment
`float8` | `uint8` | Assignment

And then adding the basic arithmetic functions *just* for the case where both
arguments are of the same uint type, e.g.:

  * `uint2` + `uint2` -> `uint2`
  * `uint2` - `uint2` -> `uint2`
  * ...

I think that makes a lot of stuff just work out nicely. A query like

```
SELECT 1::uint2 + 1
```

will plan successfully but with return type int4. If you want to stay in
int2 land:

```
SELECT 1::uint2 + 1::uint2
```

**Comment by sploiselle** [comment]
I think the support for things like `int4 < uint4`, `int4 + uint8` is unnecessary for us rn. If you want to add those types, you can use `numeric + numeric`. This, I believe, what the general proposal is and is just agreeing with Tom Lane––no surprise there. Just wanted to make sure that was unambiguous in case someone else picks up this work.

I do believe we also need the slew of casts from the extant types to the new `uint` types. If you wanted to be fussy, you could require them to be Explicit, though without poring over it too much, I think Assignment would work. A few things about this, in case you aren't convinced!
- These casts will be required to even support `1::uint2`, which is going to come in as a `Datum::Int32`.
- Because these casts would be Assignment, there's no risk that they'd get chosen for e.g. binary operations.
- Every type supports Assignments casts to every other type in the same "type category." Excluding these would be an unergonomic exception.

Just to make it concrete, here's the list I propose concatenating onto yours:

From | To | Type
--|--|--
`int2` | `uint2` | Assignment
`int2` | `uint4` | Assignment
`int2` | `uint8` | Assignment
`int4` | `uint2` | Assignment
`int4` | `uint4` | Assignment
`int4` | `uint8` | Assignment
`int8` | `uint2` | Assignment
`int8` | `uint4` | Assignment
`int8` | `uint8` | Assignment
`numeric` | `uint2` | Assignment
`numeric` | `uint4` | Assignment
`numeric` | `uint8` | Assignment
`float4` | `uint2` | Assignment
`float4` | `uint4` | Assignment
`float4` | `uint8` | Assignment
`float8` | `uint2` | Assignment
`float8` | `uint4` | Assignment
`float8` | `uint8` | Assignment

One minor nit about the list in the initial issue filing is that `text` to any int type should be an Explicit cast (they're marked as Assignment in the list, which makes intuitive sense, but strictly typed text values (`1::text`), cannot be inserted into any kind of int column). Not to be pedantic, just want to make sure that doesn't get lost somewhere along the way.

**Comment by benesch** [comment]
Oh, hah, I just totally spaced and forgot about the reverse casts. Great call. Tyvm!

**Comment by benesch** [comment]
I've applied your bug fixes to the issue description. Thanks again, Sean!

**Comment by mjibson** [comment]
Worthwhile to also discuss the pgwire encoding. Text is obvious, but will we handle binary or bail like lists and maps?

**Comment by benesch** [comment]
I think the binary encoding is fortunately _way_ more obvious for unsigned integers: you just send the integer like you would normally.

**Comment by mjibson** [comment]
Not all possible uint values fit into the space of signed ints, so that'd only work if we error if it doesn't fit (certainly a bad idea) or always upcast to the next biggest type or numeric. https://www.postgresql.org/docs/current/xtypes.html says that custom types must have a text encoding, and can optionally have a binary encoding. We could choose to do whatever postgres does when a user asks for binary encoded custom types but the type extension doesn't support it. If we do this, someone could try to build pguint and see what happens in this case.

**Comment by benesch** [comment]
I don’t understand! The binary encoding of a u32 will just be the four
bytes in big endian order (or, rather, whatever endianness signed ints
use). Then it’s up to clients to interpret them as unsigned ints rather
than twos complement signed ints.

**Comment by mjibson** [comment]
> Then it’s up to clients to interpret them

This is the deal killer for me. Only some postgres drivers allow users to provide their own custom binary type decoder. Is your argument that for users who really really want non-standard types, there's enough motivation for them to plug into their driver (or possibly fork the driver) so they can use the binary protocol? My gut is that they'll just use text encoding.

I mean, we could provide it, but we should test what happens if they give their driver a signed type and the driver happily attempts to interpret the bytes as signed instead of unsigned.

**Comment by benesch** [comment]
> > Then it’s up to clients to interpret them
> 
> This is the deal killer for me. Only some postgres drivers allow users to provide their own custom binary type decoder. Is your argument that for users who really really want non-standard types, there's enough motivation for them to plug into their driver (or possibly fork the driver) so they can use the binary protocol? My gut is that they'll just use text encoding.
> 
> I mean, we could provide it, but we should test what happens if they give their driver a signed type and the driver happily attempts to interpret the bytes as signed instead of unsigned.

That won't happen because we'll invent new OIDs for the type! Like, there is no possibility of driver confusion here, because unsigned types will present as a new scary OID that the driver doesn't know how to handle, and you'll have to explicitly tell it how to interpret the bytes, if you want to use the binary encoding.

My point is that there's no good reason _not_ to provide a binary encoding here, because the binary encoding is obvious. And it's ok if no drivers support it to start. (Unlike list/map types, where we'd have to spend a lot of time figuring out what the right binary encoding is, and figuring out what system tables need to exist to transmit the information about the embedded element/key/value types.)

**Comment by benesch** [comment]
#10899 took a small step towards this by adding a `Datum::UInt32` variant that's used by `ScalarType::Oid` and friends. The next step is adding a `ScalarType::UInt32` variant that's exposed to users as `uint4`, plus the same machinery for `uint2` and `uint8`.

**Comment by mxcoder** [comment]
Hi everyone, any update on this? Maybe even using an optional flag for compatibility?
This is completely stopping involvement on a company level due historical protobuf schemas.

**Comment by mxcoder** [comment]
Hello! Looking really forward to test this for our use cases, when should I find it available in the public container images?

**Comment by benesch** [comment]
@mxcoder I'm afraid that this change is only slated for a new cloud-native version of Materialize that we're launching later this year. We don't currently have plans to backport this change to v0.26 LTS. 

We are publishing an all-in-one Docker image with the new cloud-native version of Materialize (materialize/materialized:unstable), but for development and testing purposes only; it has unfavorable performance characteristics when running in one Docker container, rather than our cloud environment.
