### ISSUE TITLE
Support for postgres logical replication functions

### ISSUE THREAD

**Issue by henrytseng** [MaterializeInc/materialize#7814]
Is there any work being done on postgres logical replication functions?

For example,

```
select pg_is_in_recovery(),pg_is_wal_replay_paused(), pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn(), pg_last_xact_replay_timestamp();
```

Trying this on version `0.9.0` at the moment.

**Comment by benesch** [comment]
I don't believe so. We wouldn't want to expose those functions directly, because a single `materialized` instance might be reading from any number of PostgreSQL sources. But we might be able to expose e.g. the last-received LSN for a given PostgreSQL source in a system table somewhere.

Can you say more about your use case?

**Comment by henrytseng** [comment]
Ah, I see since it's not in the context of a database.  We're ingesting
from multiple sources but we'd be looking to track the LSN to know if our
views have been updated.

**Comment by benesch** [comment]
Yep, exactly! Totally makes sense. @elindsey you were asking about this yesterday in Slack—can you triage?

**Comment by elindsey** [comment]
Thanks for the feature request Henry!

The plan is to eventually expose this in a system table, similar to how upstream Kafka offsets are exposed today. Right now that work's blocked on some internal rearchitecting. The relevant issue to follow is https://github.com/MaterializeInc/materialize/issues/7873 - I'm going to close this one out in favor of that one.
