### ISSUE TITLE
persist: initial stability/perf tuning

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#7902]
A combination of observations, investigations, diagnoses, and TODO list for transparency and collaboration. Living document.

New Metrics
- Number of batches at each compaction level?

TODO
- Compaction selection strategy tuning
- Figure out why there's more uncompacted data than ruchir expects

**Comment by danhhz** [comment]
Ran some experiments earlier this week to see how well we hold up to persisting mz_metrics and mz_metric_histograms (aka just the --persistent-system-tables flag), both locally and on mzcloud. This is pre compaction. Some takeaways:

- We were able to run out of 1000MB of space on mzcloud within a day. Tables being persisted couldn't be queried (the coord's seals were failing, so we weren't closing out new timestamps and coord won't select as of old ones). New tables couldn't be created (because the catalog is on the same disk) but non-persisted tables were responsive. Surprisingly decent handling of out-of-disk given that we haven't thought about it much.
- It was hard to detect that we were out of space from the metrics I was looking at. I might have been missing something or we might need to track this.
- I let another one run over the weekend with a ton of disk and it was unresponsive to basically everything when I came back. This was before any persist metrics, so I had no way to diagnose anything here. My wild guess is that META got too big and it made the runtime loop fall permanently behind. Run this experiment again soon.

**Comment by danhhz** [comment]
I ran some experiments yesterday with compaction hooked up (a combination of #7883 and some hacks) but without #7847. Again just with --persistent-system-tables.

<img width="1839" alt="Screen Shot 2021-08-17 at 3 12 21 PM" src="https://user-images.githubusercontent.com/52528/129927844-2a40091c-3140-432b-bc7d-a8a46bc721e5.png">

Notes:
- Good: Meta size seems to be stable
- Neutral/interesting: You can clearly see the compaction strategy in the blob write bytes graph (another below where it's even more clear).
- Bad: The disk write rate and usage are both pretty volatile for such an even write rate.
  - TODO: Put more thought into our compaction selection.
- Bad: We're writing 1.75MB/s pretty consistently.
  - Part of this is that our write amplification is probably bad right now (need more metrics for this). The batching change that just merged may already help with this.
  - Even if we fix write amp, the raw incoming data right  might just be too much disk usage to turn on by default for something that's not actually a win for customers. We may have to revisit the August milestone and pick a less heavily traffic'd table. At the moment, it's persisting both mz_metrics and mz_metric_histograms so maybe just one of these. (Or maybe we just tell anyone who complains about the opt-out.

**Comment by ruchirK** [comment]
I thought through my testing plan for today and in the interest of doing good science I figured I would write everything down before I did any experiments.

The main thing I want to measure is "what's the user pain of running with `--experimental --persistent-system-tables` in terms of resource consumption, because ultimately that's going to determine if we can place persistent system tables in beta or not, or whether we need to do fewer tables, sample less metrics, etc.

To that effect the main thing I want to measure is: whats the difference in cpu / memory / disk utilization between running stock mz and mz with persistence enabled across the following setups listed below, and I also want to have a better mental model around "how do the metrics tables change over time with different usage". In my head I've been assuming that they are roughly staticly sized, but perhaps that is not true.

macbook + mz running with 6 timely workers
32 vcpu ec2 instance running with 16 timely workers

and the following workloads:

1. Nothing / testdrive -- really low load, just want to get a baseline for both how large the metrics are and how good we are at persisting them. Also want to see how the number of metrics changes as people issue queries (e.g. does it double after running testdrive, or is it more like a 10% increase)

2. Billing demo with a `num_worker` partition topic. Not sure how many messages to put in total, but I want to push materialize to see at least 1/2 `num_worker` cores fully utilized.

3. Stress test mode: run the billing demo with the following configuration changes:
--retain-prometheus-metrics=60min
--metrics-scraping-frequency=50ms

these two should really increase the volume of metrics. compaction interval is already 1ms so we can't ramp that up more aggressively. Table capabilities are not driven by timestamp frequency iirc but can explore if theres any way to dial that up as well. 

This setup should give us a better idea of "what does the system look like if we start of deviate from our assumptions of relatively small amount of writes / small working set" and hopefully give us a better sense of whether the persistence crate or the overall system's tipping points are (e.g. "once we start trying to maintain a working set of X bytes we really fall off a cliff")

**Comment by danhhz** [comment]
I ran an mzcloud testovernight, which stopped after a few hours. Runtime loop seemed fine so my only theory was "out of space" which isn't surfaced well in our current metrics (well known problem at this point). Ruchir reminded me we have an integral metric for how much we've written to blob, so I grabbed the raw number, which was ~20GB. I provisioned it with 10GB so that mystery is solved. (And another emerges, is our metric wrong or did I get more disk than I asked for?)

One other curious thing is a couple of dips in write count shortly after our biggest compactions. No real theories here, but the fact that it seems tied to large compactions makes me less worried about it.

![image](https://user-images.githubusercontent.com/52528/130259630-27189826-97d9-4d05-807a-4bc32185d253.png)

**Comment by ruchirK** [comment]
>  a couple of dips in write count shortly after our biggest compactions

That makes intuitive sense to me. Our biggest compactions will involve a lot of reading and consolidating so it makes sense that the extra time spent on doing that would lead to a larger batch of writes the next time we see writes and so we'd be writing fewer blobs.

**Comment by danhhz** [comment]
Ah the 20GB is because we repeatedly overwrite META, of course. The rough doubling of the available storage is pure coincidence

**Comment by ruchirK** [comment]
I had a perf realization: we are unintentionally doing trace compactions in a way that makes things worse for us.

Lets say you have 2 tables that were created at the same time. If they both receive a steady flow of writes and have identical seals, they will both generate new trace batches every time we call `drain_unsealed`. That basically means their compaction trees will be the same. Any time table A needs to compact two level N batches to make a level N + 1 batch, table B will need to do the same.

Assuming both tables are roughly the same size, this means the current setup effectively doubles the peak write bandwidth. If instead there was some difference between the two tables or some source of randomization in the compaction selection strategy, then their large compactions would not happen close together in time, and we would spread the load out more evenly.

**Comment by danhhz** [comment]
Ran this over the weekend as of #7964 and it's still going! Prometheus was on my laptop, so lots of data is missing (I'm very excited for @antifuchs's cloud prometheus work). No idea if the crazy spikes are real or artifacts of my laptop going to sleep, but they're worth looking into.

Another oddity is that blob_delete_count is much lower than blob_write_count for the entire time of the test. Pretty sure that's because META writes get counted in the latter but not the former (when they get overwritten). I've been meaning to break out the various things in the Blob Writes graph into meta/unsealed/trace, which would also help make this more obvious too.

![image](https://user-images.githubusercontent.com/52528/130491445-be113925-ffd6-4cee-945d-7ad2e92fc4e6.png)

**Comment by danhhz** [comment]
Nikhil manually confirmed our disk usage on the raw instance, which lines up with the graphs. GG @ruchirK looks like your delete stuff is working perfectly! Also encouraging is that our latencies spent in persist seem indistinguishable today from what they were on friday.

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
...
...             9.8G  199M  9.6G   2% /mzdata
...
# du -a
...
12  ./persist/log
...
160664  ./persist/blob
160680  ./persist
```

**Comment by ruchirK** [comment]
perhaps I'm missing something but I'm confused as to why the `trace_bytes_count` is so much higher than the `unsealed_bytes_count` (161 mb vs 25 mb). This seems like its logical / physical compactions that are pending and waiting to happen, but I kinda thought that the pending overhead would be upper bounded by 2x the base data size?

I'm sure there's something I'm thinking about wrong here.

**Comment by danhhz** [comment]
Good question. I don't have an answer, but here's some musing. We're getting 77KB/s in. 77KB * 5 * 60 = ~23MB, which lines up pretty well with what is in unsealed. Given that we're not compacting unsealed, just waiting to drop that batch, this makes sense to me.

This also means 5min of data plus the retractions is ~23MB. At any given time, we should have about 5m of worth of uncompactable data in trace (half of 23MB) and the rest should be compactable. So I agree that this isn't ideal.

What I can't wrap my head around is, for some newly minted batch coming out of unsealed, what is the expected number of compactions it goes through before meeting its retraction? There's some math here but I'm not seeing it quite yet. Something about number of batches that get minutes in the 5 minutes between when data gets moved into trace vs when its retraction gets moved into trace. Then something about how many compactions have to happen for it to be merged with a batch at level N. The graph above of trace size has a very regular pattern, which continues fractal-ly if you zoom in to the graph.

**Comment by danhhz** [comment]
Load tests seem stable over the course of a week.

![image](https://user-images.githubusercontent.com/52528/132369272-373fa44c-7bb9-46aa-afdf-fc14a58f6c05.png)

I also left an mzcloud instance up with no traffic for ~11 days. The monitoring was on my laptop, so we don't have intermediate data, but the metrics at the start and end of those 11 days are similar.

Start: 
![image](https://user-images.githubusercontent.com/52528/132378682-663a4974-4a20-4b2b-b5a3-6075d75bc1c3.png)

End: 
![image](https://user-images.githubusercontent.com/52528/132378716-48e48882-b0b7-49f6-a82d-fe320da8efae.png)
