### ISSUE TITLE
sql/dataflow: fast path not used when there's an index

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#8269]
The test from #8241 (https://github.com/MaterializeInc/materialize/issues/8241#issuecomment-918129088) causes a non-fast path to be used in sequence_peek, even though it boils down to a select over an index. @frankmcsherry says this isn't supposed to happen (it should use an existing arrangement), and so someone should look into it.

**Comment by frankmcsherry** [comment]
I looked over this, and I think it boils down to the fact that view inlining does not occur until a `DataflowDesc` is created. So, what we have from the example is 
```sql
CREATE TABLE t1 (f1 INTEGER, f2 INTEGER);
CREATE INDEX i1 ON t1 (f2);
CREATE VIEW v1 AS SELECT * FROM t1;
SELECT * FROM v1;
```
and here `v1` is a thing .. that doesn't have an index. If we were to go and inline it, all would be good and we'd see that it optimizes down to a select from a table with two indexes. But that code (building a `DataflowDesc`) only occurs in the slow path code, rather than before the fast/slow determination.

**Comment by frankmcsherry** [comment]
We also see the same suboptimal behavior for the constant determination as well, where the set-up
```sql
CREATE VIEW foo AS VALUES (1);
CREATE VIEW bar AS SELECT * FROM foo;
SELECT * FROM bar;
```
goes through dataflow construction as well, even though it optimizes to a constant.

It seems like `Coordinator::sequence_peek` mostly needs a bit of attention, probably at least to form the dataflow graph that we would ship, and then determine if there is a fast path around shipping it as a dataflow (e.g. if it is a constant, or a read out of an index).
