### ISSUE TITLE
Fix published mz-avro crate on crates.io

### ISSUE THREAD

**Issue by jorgecarleitao** [MaterializeInc/materialize#8669]
Hi,

I think I have found a memory-safety/soundness issue on this crate while reviewing it.

`read_exact` method creates an uninitialized buffer and passes it to user-provided Read implementation. This is unsound, because it may allow safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

[This part](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) from the `Read` trait documentation explains the issue:

> It is your responsibility to make sure that buf is initialized before calling read. Calling read with an uninitialized buf (of the kind one obtains via MaybeUninit<T>) is not safe, and can lead to undefined behavior.

This idiom has been referenced in rustsec as UB in the past e.g. [here](https://rustsec.org/advisories/RUSTSEC-2020-0154.html) or [here](https://rustsec.org/advisories/RUSTSEC-2021-0014.html).

The offending line is 

https://github.com/MaterializeInc/materialize/blob/386a0715280d57c02305f5578fe2e46c64cc32c3/src/avro/src/reader.rs#L265

Thanks!

**Comment by jorgecarleitao** [comment]
Hey, I suggest we write a security advisory [here](https://github.com/rustsec/advisory-db) so that users of `mz-avro` are notified by `cargo audit` that they should audit their applications and verify that they do not:

1. use implementations of `Read` that do not fill the buffer on `exact_read`
2. re-use the buffer if the read errors

once we have a release, we can update the advisory so that users are instead recommended to update the repo.

**Comment by jorgecarleitao** [comment]
I have filled one, since this is now 4 months old.

**Comment by pinkforest** [comment]
@petrosagg @elindsey there is only one crate version in crates.io and there is 272 downloads on it

The crate version has not been updated since this was fixed and I assume the one in crates.io would be affected by this as no new versions are published after this was fixed in the associated crate.

However since I am not sure whether the crate is supposed to be used via crates.io I am not sure what the impact is if any -

Maybe if it's not used via crates.io then maybe you could use the yank operation on crates.io so nobody uses it anymore ?

Or if it is indeed supposed to be used via crates.io then alternatively could you bump the crates version and publish fixed one ?

Or would you prefer an informational advisory to deter people using the crates.io version in a rare case someone uses it ?

Thanks for the assistance :purple_heart:

**Comment by brennanvincent** [comment]
We are mainly using the in-tree mz-avro; the one on crates.io is ancient.

I'll publish an updated version in a few days. Thanks for letting me know, @pinkforest .

**Comment by pinkforest** [comment]
Great thank you - 

Could you do cargo yank for the old version after so nobody is going to build with that ?

Also would you be on board for us to publish informational advisory so e.g. tooling like cargo deny will raise an informational warning about it advising to move to the new published version once the fix is available if someone had compiled a binary previously with it and they were using cargo-auditable.

Cheers

**Comment by brennanvincent** [comment]
Sure, but please point out in the advisory that there is only UB in the case where a user provides a struct whose `Read` impl inspects its `read_exact` buffer before writing into it. It's indeed possible to use the trait unsoundly, but only by writing a highly unidiomatic `Read` impl.

**Comment by pinkforest** [comment]
Great - Thank you for the input - enjoy the weekend :purple_heart:
