### ISSUE TITLE
Add validation support for QGM models

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#8958]
The QGM model that is going to be merged as part of #8801 is a bit loosely defined. 

The initial [original QGM design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20210707_qgm_sql_high_level_representation.md) lists a number of "subtle constraints that are not explicit in the representation above":

- [x] `BaseTable`, `TableFunction` and `Values` cannot have input quantifiers.
- [x] `Union`, `Except` and `Intersect` can only have input quantifiers of type `Foreach`.
- [ ] Distinctness can only be enforced in `Select`, `Union`, `Except` and `Intersect` boxes.
- [x] Subquery quantifiers (`All`, `Any`, `Existential` and `Scalar`) are only allowed in `Select` boxes.
- [x] `Grouping` must have a single input quantifier of type `Foreach` ranging over a `Select` box.
- [x] A `Grouping` box is always ranged-over by a `Select` box.
- [x] `OuterJoin` must have at least an input quantifier of type `PreservedForeach` and at most one quantifier of type `Foreach`. An `OuterJoin` with all `PreservedForeach` input quantifiers represents a `FULL OUTER JOIN`.
- [x] `PreservedForeach` quantifiers can only exist in `OuterJoin` boxes.

*Notes*:
- Temporarily during the generation of the query model we could allow subquery quantifiers in `OuterJoin` boxes for subqueries in the `ON`-clause of the outer join, but should push down the subquery to the non-preserving side. 
- In QGM, there is no distinction between a `LEFT JOIN` and a `RIGHT JOIN`, since that's a concept that belongs only in the AST.

To improve the quality of the software and as a mechanism for diagnosing errors, we need to be able to identify QGM instances that don't satisfy the above constraints.

We have two different methods for doing that:
1. Improve the model definition to track model constraints syntactically through the model structure.
2. Add a mechanism to validate model instances against the above constraints at runtime.

Method (1) has the benefits that the guarantees are static - there is no way to define transformations that validate these assumptions, and a successful `rustc` compilation can be seen as a proof that a transformation is correct (at least w.r.t. these constraints). The downside of this method is that the Rust type system is not powerful enough to encode all constraints, and even what can be encoded might have a negative impact the ergonomics and readability of our model transformation logic.

Method (2) has the benefit of being quite general and extensible, but has the downside that the validation is asserted at runtime.

As an initial attempt to address this problem, we will therefore go 100% with (2). As we make progress with #8073, we might revisit the initial QGM encoding and encode some constraints through syntax as proposed in (1), especially if we understand how to do that without compromising the logic for transforming trees.

**Comment by asenac** [comment]
A few more that are missing from the original list:

* `BoxScalarExpr::Aggregate` is only allowed as a top level expression in the projection of a `Grouping` box. These boxes can only contain column references, aggregate expressions in their projection or constants (that will eventually be lifted by `ConstantLifting` transform).
* `BoxScalarExpr::Windowing` is only allowed as a top level expression in the projection of a `Windowing` box. These boxes can only contain column references, windowing expressions in their projection or constants (that will eventually be lifted by `ConstantLifting` transform).
* Computed expressions in the projection are only allowed in `Select` boxes.

Note that we might need to allow input quantifiers in `TableFunction` boxes if we want to do query decorrelation as a transformation, since we would need to a way of representing Mir's FlatMap's semantics vs. Hir's CallTable semantics.

Also, note that the following constraints are just conventions and can be relaxed if needed, since there is nothing semantically invalid about them:

* Computed expressions could be allowed in the projection of any box. `Grouping` and `Windowing` boxes could contain expressions computed from columns from its input quantifier.
* Subquery quantifiers could be allowed in `OuterJoin` boxes.
* Distinctness could be enforced by any box, but `OuterJoin` ones.
* `Grouping` and `Windowing` boxes could be ranged over by and range over any type of box.
