### ISSUE TITLE
"LIMIT must be an integer constant" in prepared statements

### ISSUE THREAD

**Issue by Linksku** [MaterializeInc/materialize#8961]
### What version of Materialize are you using?

0.9.10

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [x] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?

When a prepared statement has LIMIT's as value as a binding, I get "LIMIT must be an integer constant". I think this is coming from Materialize.

I'm using Knex (https://github.com/knex/knex), which always has the LIMIT value as prepared value. E.g. this:

```
knex('view1').select('foo').limit(10);
```

Would produce:

```
select "foo" from "view1" limit $1;
```

This error doesn't occur when I don't have the LIMIT as a prepared value:

```
select "foo" from "view1" limit 10;
```

It's possible to work around this in Knex, but it's ugly.

### Please attach any applicable log files.

No errors in logs.

**Comment by frankmcsherry** [comment]
I wonder if this might be related https://github.com/MaterializeInc/materialize/issues/7071. Roughly, that rather than require *constant* values, the whole pipeline could accept expressions (and late bound constants). Perhaps the prepared statements flow should also accept late bound constants too, but .. floating the issue for context.

**Comment by Linksku** [comment]
For anyone else having the same issue with Knex, I found a way to make it not make the limit a prepared value:

```
Knex.QueryBuilder.extend('limitRaw', function (sql: string, bindings: any[]) {
  // @ts-ignore
  this._statements.push({
    grouping: 'limit',
    type: 'limitRaw',
    value: this.client.raw(sql, bindings),
  });
  return this;
});
```

**Comment by sploiselle** [comment]
`RowSetFinishing`'s `limit` + `offset` feature has two distinct uses:
- Modifying the output of a `SELECT`
- Converting `HirRelationExpr` to `TopK`

@andrioni mentioned we could potentially accept parameters from queries for the `limit` and `offset` values. This seems natural and requires the least amount of refactoring because both literals and parameters require being turned into `HirScalarExpr::Literal`.

Making this change to `RowSetFinishing` then also naturally cascades into amending `HirRelationExpr::TopK` to take the same fields.

Once we've made this change to `TopK`, though, there's no need to ensure we have literals for either `RowSetFinishing` or `TopK` until after optimization––something like `1+1` could get reduced to a constant.

However, there are a few sticking points:
- Other `RelationExpr`s don't rely on optimization to discover that the input was correct, so this machinery DNE and maybe shouldn't.
- Inclusive in the above point is actually optimizing those `ScalarExpr`s, which isn't totally obvious to me how that happens. I believe it's part of `LiteralLifting` but I don't immediately see how this would work because I'm unfamiliar with the optimization code paths.
- In the `SELECT` case, `RowSetFinishing` is not part of a `RelationExpr`, so would require an optimization pass to try to convert the expressions into constants. However, there is no machinery by which to optimize lonesome `ScalarExpr`s. Again, maybe there shouldn't be.

## Alternative design

We could get out from underneath this complexity by very narrowly allowing only literals and parameters. This requires creating a `HirRowSetFinishing` that we take to the existing `RowSetFinishing` during planning (by calling `bind_parameters` on the `HirRowSetFinishing` `limit` and `offset`, and then casting the value to `usize`).

However, this is also annoying because we have to rely on supported data types for the literal expressions, and the largest data type we support is `i64`, though we expect the limit and offset to be usize. After we enable support for unsigned integers, this won't be an issue.

This also does mean futzing with `HirRelationExpr::TopK`, as well, and then extracting its constant values when going to `MirRelationExpr::TopK`.

All of this is fiddly enough that having some mechanism of simply accepting expressions is preferable--Frank mentions #7071 and I think working on that issue has more yield than this hack.

**Comment by sploiselle** [comment]
Closing this in favor of #7071
