### ISSUE TITLE
Mirror `SHOW` data as views

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#913]
Various aspects of the system catalog are currently interrogated with `SHOW` commands. Several bits of tools would prefer query access to these as relations, to avoid reconstructing joins in application logic (for example, metabase picking out column names from primary key identifiers).

We could aim to have the various `SHOW` commands either mirror or be based off of data that exists relationally, which eases some amount of tool-based reflection and might open up some other doors. For example, #435 would just be a change in the query if it was instead `SELECT * FROM mz_sources`.

**Comment by benesch** [comment]
I thought @justinj and I had worked out a sane design for this. Specifically:

  * Change `Coord::local_input_time` to track wall clock time instead of a monotonic integer that increases from zero.
  * Mirror various catalog information (some of which is already in logging views) as local inputs. Stamp modifications with the current local input time.
  * Periodically advance the local input time.
  * Ensure that timestamp selection for a query that involves local inputs always reads at a time >= to the local input time.

Do you have specific concerns with that design, Frank?

FWIW I don't think (1) is workable. I think even still there there are some queries that we can't reduce to constant expressions even when the queries are over constant data, so we need the escape hatch of actually rendering a dataflow. I think it is probably more work to get machinery hooked up to isolate the dataflow layer from the catalog contents than it is to just mirror the catalog contents to the dataflow layer.

(3) isn't particularly important—I agree it seems a bit of an anti pattern to expect consistent results between the Materialize catalog and an upstream source of data—aligning the catalog with RT sources via wall clock time seems philosophically consistent to me. Real-time timestamping is YOLO mode anyway, so the fact that it only weakly aligns with the catalog data seems ok to me. But I would be fine with leaving `Coord::local_input_time` in its own time domain, and just letting queries that join catalog and non-catalog views fail on timestamp selection, the way I presume joining a logging view with a non-logging view fails today.

**Comment by wangandi** [comment]
(3) would be important if we want `SHOW` data to include, say, the size of a particular index. Though, sizes are not officially part of the `information_schema`, so we could train users in using logging views to view sizes instead.

**Comment by frankmcsherry** [comment]
Yeah a bunch of concerns. Mostly that this was the first discussion I had seen of the designs, and I thought it was worth writing down the plan vs doing it and then discovering if there were issues.

1. Are we planning on mirroring catalog data twice in the dataflow layer? If `mz_catalog_names` uses coordinator-local times it can't obviously be joined as it currently is in logging views, or for frontier information, or ... etc. If twice, how do we keep people sane about which one they are looking at? If not twice, do we force the logging in to some coordinator-local reckoning, or have the coordinator use the logging reckoning?

2. The current timestamps are in milliseconds, which imposes a limit on the number of distinct updates we can push through the system. This might be fine, but it seems to build in at least a millisecond for anything that needs to hit the dataflow layer. Do we want to increase the resolution of timestamps?

The (1) proposal seems like it could handle the criteria for #2576, in that it is just a SELECT and does not require view maintenance. The work there would be instead ensuring that constant evaluation can happen for all queries, rather than rigging up dataflow inputs. I think (1) isn't sufficient for a bunch of other use cases, but it would likely be one of the lowest-latency paths for responding to these queries.

**Comment by benesch** [comment]
(1) is going to result in a lot of extra complexity in the coordinator which doesn't have a lot of room for extra complexity. Plus I'm not sure how it solves the problem of `mz_catalog_names` wanting to sometimes be a catalog view and sometimes wanting to be a logging view. Would its consistency properties change depending on whether you joined it against a logging view or another catalog view?

How hard would it be to get the catalog views into the logging time domain? Does the coordinator advance the logging timestamps, or is that handled automatically by timely?

**Comment by benesch** [comment]
From a discussion on Slack, a design that seems promising is this. Adjust `Coordinator::local_input_time` to use a `time::Instant` instead of a monotonically increasing integer. (This is slightly different from the proposal above, which used wall clock time instead of a `time::Instant`.) Initialize this instant when the coordinator boots, which will keep it roughly in the same domain as the workers' logging timer. Use this timer to drive around local input sources for catalog views, as described above.

**Comment by JLDLaughlin** [comment]
This is done!

**Comment by benesch** [comment]
Closing out these three-digit issues is so satisfying! Thanks very much for slogging through all the views, @JLDLaughlin.🙇
