### ISSUE TITLE
Support `information_schema`

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#9182]
`information_schema` is a database schema composed of views to provide information about tables, views and other objects. Supporting it would be helpful, as it is one of the main standard ways of introspecting a database, even though we provide other alternatives, like `SHOW TABLES` and `pg_catalog`.

This is an umbrella issue to track overall `information_schema` support.

Main views:
- [x] #9181
- [x] `information_schema.views`
- [x] `information_schema.tables`
- [x] `information_schema.schemata`
- [x] `information_schema.character_sets`

**Comment by morsapaes** [comment]
Ran into this while trying to spin up Materialize + [Lightdash](https://docs.lightdash.com/):

```bash

error: select * from information_schema.tables where table_name = $1 and table_schema = current_schema() - unknown catalog item 'information_schema.tables'
```

**Comment by joacoc** [comment]
Ran into same issue while coding with [knex.js](http://knexjs.org). After going deep a little more, it seems that Lightdash uses knex.js internally. 

This happens when Knex's `pg-compiler` tries to interact with Materialize schema:
https://github.com/knex/knex/blob/master/lib/dialects/postgres/schema/pg-compiler.js

The idea behind this experiment was to make easier development lifecycle tasks like:
https://knexjs.org/#Migrations

**Comment by morsapaes** [comment]
Thanks for digging around a bit more, @joacoc! I gave up before getting into the `knex` codebase — it helps that you pinpointed where the first problematic query is being issued.

**Comment by ruf-io** [comment]
Reverse ETL from Rudderstack depends on _at least_ `information_schema.schemata` - It might not actually be possible even with schemata support because it looks like Rudderstack follows a similar behavior to Census where status of syncs is tracked in a custom schema in the database, as opposed to in S3 like Hightouch.
