### ISSUE TITLE
reuse-topic: Fence existing kafka consistency topics before determining latest ts

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#9249]
Frank pointed out the following sequence in slack:
```
1. MZ writes some stuff to the consistency and data topics transactionally,
2. Kafka goes to sleep just before committing this; writes are still enqueued,
3. MZ restarts and attempts to read MAX_OFFSET from Kafka,
4. Kafka wakes up and handles (3.) before (1.).
```

Kafka provides a mechanism to avoid this -- picking a `transactional.id` for the producer -- which allows for linearizability across restarts.

However, we determine the lastest ts we've seen (`get_latest_ts`) _before_ completing the fencing by starting up the producers with the same `transactional.id`s.  This means we could read an inconsistent latest ts.  When doing this, we want to make sure we do not write new data to the producers until we've determined the latest ts.

**Comment by elindsey** [comment]
Fencing of old producers with the same `transactional.id` occurs during `initTransaction` API calls. So in code the problem is that all the logic to setup the sink, find the latest written ts from the Kafka topic, etc. occurs in the coord when re-bootstrapping the sink connector, but the `initTransaction` calls occurs much later, once the sink itself has actually been created (with the previously construct sink connector).

**Comment by elindsey** [comment]
https://www.confluent.io/blog/transactions-apache-kafka/ is a relevant blog post for anyone who would like context
