### ISSUE TITLE
performance: degraded performance when we have more than 1 element in the IN list

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#9473]
### What version of Materialize are you using?

```
v0.10.0 (c14633f59)
```

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?

Performance degrades when we have more than 1 element in an IN list.

### Is the issue reproducible? If so, please provide reproduction instructions.

```sql
CREATE TABLE numbers (a int NOT NULL);
CREATE INDEX numbers_idx_a ON numbers (a);
```

After populating the table with some data, when we do a `SELECT` with an equality filter we get the following results:

```sql
mz> select * from numbers WHERE "a" =1;
Time: 0.012s
mz> select * from numbers WHERE "a" =1;
Time: 0.012s
mz> select * from numbers WHERE "a" =1;
Time: 0.012s
mz> select * from numbers WHERE "a" IN (1);
Time: 0.013s
mz> select * from numbers WHERE "a" IN (1,1);
Time: 0.013s
mz> select * from numbers WHERE "a" IN (1,1);
Time: 0.013s
```

However, when you add more than 1 element to the IN list we get the following results:

```sql
mz> select * from numbers WHERE "a" IN (1,2);
Time: 0.125s
mz> select * from numbers WHERE "a" IN (1,2);
Time: 0.115s
mz> select * from numbers WHERE "a" IN (1,2);
Time: 0.118s
```

**Comment by frankmcsherry** [comment]
Just to read out what I think is the answer, `IN` statements turn in to equality predicates in filters. When we have just one there, we are able to use indexed look-up, and traverse a different code path than otherwise.
```
materialize=> explain plan for select * from numbers WHERE "a" = 1;
             Optimized Plan             
----------------------------------------
 %0 =                                  +
 | Get materialize.public.numbers (u15)+
 | Filter (#0 = 1)                     +
 
(1 row)

materialize=> explain plan for select * from numbers WHERE "a" IN (1,1);
             Optimized Plan             
----------------------------------------
 %0 =                                  +
 | Get materialize.public.numbers (u15)+
 | Filter (#0 = 1)                     +
 
(1 row)

materialize=> explain plan for select * from numbers WHERE "a" IN (1,2);
             Optimized Plan             
----------------------------------------
 %0 =                                  +
 | Get materialize.public.numbers (u15)+
 | Filter ((#0 = 1) || (#0 = 2))       +
 
(1 row)

materialize=> 
```
The first two *should* be faster than the latter, especially with a large amount of data in the table (I'm not sure how much data is present). We could improve this, e.g. by supporting multiple indexed lookups rather than one, and do have some issues open about improved `IN` planning (I'll track those down and link them; unfortunately, searching for "in" results in many hits).

**Comment by frankmcsherry** [comment]
Btw, the issue seems great, in that it is very specific. The other `IN` issues were a bit more nebulous about "things we could do". Keeping this around seems great, and very actionable in principle.

**Comment by frankmcsherry** [comment]
One way to check out the difference is to use `explain physical plan for <view>`, which in these cases return
```
materialize=> explain physical plan for select * from numbers WHERE "a" IN (1,1);
                Physical Plan                
---------------------------------------------
 {                                          +
   "Get": {                                 +
     "id": {                                +
       "Global": {                          +
         "User": 15                         +
       }                                    +
     },                                     +
...
     "key_val": [                           +
       [                                    +
         {                                  +
           "Column": 0                      +
         }                                  +
       ],                                   +
       {                                    +
         "data": [                          +
           4,                               +
           1,                               +
           0,                               +
           0,                               +
           0                                +
         ]                                  +
       }                                    +
     ]                                      +
   }                                        +
 }                                          +
 
(1 row)
```
and
```
materialize=> explain physical plan for select * from numbers WHERE "a" IN (1,2);
                  Physical Plan                  
-------------------------------------------------
 {                                              +
   "Get": {                                     +
     "id": {                                    +
       "Global": {                              +
         "User": 15                             +
       }                                        +
     },                                         +
...
     },                                         +
     "key_val": null                            +
   }                                            +
 }                                              +
 
(1 row)
```
The `key_val` component of the physical plan reports whether we have a key and value pair to use for indexed look up. In the first case yes (the value `1`, written out as our encoded bytes). In the second case, no.

**Comment by frankmcsherry** [comment]
I had a few ideas for potential solutions, or potential scoping thoughts.

One take on this is that everywhere we currently look for `<expr> = <literal>` to form indexed lookups, we could probably as easily look for chains of `OR`s of these, with a common expression, and extract a list instead. I believe everywhere we *use* the expressions, we could use a list as well (we would need to generalize some code, but heading in to an arrangement keyed by that expression, it would mean iterating through a list, rather than seeking to one value).

Another take is that, in the limit, we want `IN` expressions to be their own thing. In DryadLINQ folks would capture large hash sets, and do lookups using them as part of `map` and `filter` statements. It makes sense implementation-wise to represent these as maps of some form (hash, btree, idk) and provide constant time access to them, rather than unfold them as a very complicated expression. This would mean enriching `*ScalarExpr`, and probably antagonizing the parser and various other layers (`IN` is also used across relations instead of scalar collections).

Perhaps in the take above, we instead plan `IN` as joins, albeit with constant collections of potentially small size, and only later look for the smarter implementation that does a constant join not as a differential join but as something simpler with a hash map or hash set.

**Comment by ggevay** [comment]
Fixed in https://github.com/MaterializeInc/materialize/issues/13151
