### ISSUE TITLE
TailResponse: Remove Complete, Dropped states

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#9479]
The `TailResponse` enum currently has the following states:
* `Progress(Antichain)`
* `Rows(Vec<_>)`
* `Complete`
* `Dropped`

In Timely, an empty antichain would include the dropped/complete case. Determine if this is true for tail sinks and if yes, remove the complete and dropped variants (or make sure that the variants can be removed by adjusting the implementation).

**Comment by umanwizard** [comment]
Complete and Dropped are a no-op for sinks:

https://github.com/MaterializeInc/materialize/blob/9e2679824/src/coord/src/tail.rs#L111-L114

Returning `true` here causes the sink to be dropped, but this will never run, because they will have already been dropped since the `TailResponse::Progress` match arm returns `true` when `upper` is empty, which will happen before the operator can be dropped, assuming it's true that Timely will always notify an operator of the empty frontier before dropping it (is this true?)
