### ISSUE TITLE
Peek should have sequence numbers

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#9521]
At the moment, a peek is identified by a connection id. This means that the coordinator can ensure that there is only one peek in flight at a time, but this nonetheless introduces ambiguity when there are other reasons for concurrency. For example, active replicas load up a sequence of commands, which may include many peeks with the same identifier, and corresponding responses all with the same identifier.

If the coordinator, or perhaps the dataflow client, were to annotate peek requests with a sequence number, all distinct peek requests would have distinct identifiers (the pair of connection id and sequence number). This would reduce ambiguity, and allow an additional level of error checking (to ensure that the correct peek responses are returning). It would also allow multiple concurrent requests with the same connection id.

Alternately, peek requests should have no concept of connection id, and just a sequence number. The coordinator is then able to map the sequence number back to a connection as it deems appropriate.

**Comment by benesch** [comment]
For posterity: @mjibson, @jkosh44, @frankmcsherry, and I chatted through this, and we decided that the "sequence" part wasn't actually important. Just having a unique identifier is all that was actually needed. So #11016 implements this with UUIDs instead of sequence numbers. No reason we couldn't swap the UUID for a different sequence-able type in the future, though, if we discover a reason we want that.
