### ISSUE TITLE
sql: support psql `\d <object>`

### ISSUE THREAD

**Issue by mkysel** [MaterializeInc/materialize#9595]
pg_catalog does not support all expected columns on the pg_class table. There might be other queries that `\d` executes that are also not supported.

The query is as follows:
```
SELECT c.relchecks,
       c.relkind,
       c.relhasindex,
       c.relhasrules,
       c.relhastriggers,
       c.relrowsecurity,
       c.relforcerowsecurity,
       c.relhasoids,
       FALSE AS relispartition,
                '',
                c.reltablespace,
                CASE
                    WHEN c.reloftype = 0 THEN ''
                    ELSE c.reloftype::pg_catalog.regtype::pg_catalog.text
                END,
                c.relpersistence,
                c.relreplident
FROM pg_catalog.pg_class c
LEFT JOIN pg_catalog.pg_class tc ON (c.reltoastrelid = tc.oid)
WHERE c.oid = $OID;
```

**Comment by jkosh44** [comment]
`pg_class` columns that need to be added for this and some notes (https://www.postgresql.org/docs/current/catalog-pg-constraint.html):

- [ ] `relchecks`: Number of CHECK constraints on the table (see `pg_constraint`). Might be able to be filled in from `ALTER TABLE ADD CONSTRAINT...` syntax, otherwise should be filled in with 0.
- [ ] `relhasindex`: True if table has index. Should be able to derive this from `mz_objects` and `mz_indexes`.
- [ ] `relhasrules`: True if table has rules (see pg_rewrite). We do not support creating rules so this should be filled in as false.
- [ ] `relhastriggers`: True if table has triggers (derived from pg_triggers). We do not support creating triggers so this should be filled in as false.
- [ ] `relrowsecurity`: True if table has row-level security enabled (see pg_policy). We do not support row level security so should be filled in as false.
- [ ] `relforcerowsecurity`: True if row-level security will also apply to table owner (see pg_policy). We do not support row level security so should be filled in as false.
- [ ] `relhasoids`: This column was removed in pg v12 and up, so we can fill this in with false.
- [ ] `relispartition`: True if table or index is a partition. We do not support table partitioning so this should be filled in as false.
- [ ] `reltablespace`: Oid of the tablespace in which this relation is stored (derived from pg_tablespace). This has to do with how the data is laid out on disk. 0 implies default tablespace so we can fill in with 0.
- [ ] `reloftype`: OID of underlying composite type for typed tables, 0 for everything else (derived from pg_type). We do not support typed tables, so we can fill this in with 0.
- [ ] `relpersistence`: p = permanent table, u = unlogged table, t = temporary table. We do not support unlogged tables, but we do support temporary tables. I'm not sure if we already store the necessary info in another mz_catalog table. If not we should be able to.
- [ ] `reispopulated`: Columns used to form “replica identity” for rows: d = default (primary key, if any), n = nothing, f = all columns, i = index with indisreplident set (same as nothing if the index used has been dropped). We don't support replication, so while we might be able to properly fill this column, it's probably not worth it. So we'll fill it with d.
- [ ] `reltoastrelid`: OID of TOAST table associated with this table, zero if none. Do we use TOAST tables?? (TODO find out)

**Comment by jkosh44** [comment]
For `relcheck` it looks like we have the parsing code to parse constraints, but we don't actually support it yet, so we can fill this in with 0.

**Comment by jkosh44** [comment]
For `reltoatsrelid` we don't use TOAST tables so we can se this to 0.

For `relpersistence` until #8805 is fixed only permanent tables show up in `pg_class`. So we can fill this in with 't' and defer fixing it to #8805 .

**Comment by jkosh44** [comment]
@mkysel How did you get the query required for `\d <object>`? When I connect to postgres with the `--echo-hidden` flag and run `\d a` (a is some random table) I get 8 different queries dumped to the console.

**Comment by jkosh44** [comment]
Full list of queries executed by `\d object_table` (where `object_table` is some table:
```
********* QUERY **********
SELECT c.oid,
  n.nspname,
  c.relname
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relname OPERATOR(pg_catalog.~) '^(object_table)$' COLLATE pg_catalog.default
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 2, 3;
**************************

********* QUERY **********
SELECT c.relchecks, c.relkind, c.relhasindex, c.relhasrules, c.relhastriggers, c.relrowsecurity, c.relforcerowsecurity, false AS relhasoids, c.relispartition, '', c.reltablespace, CASE WHEN c.reloftype = 0 THEN '' ELSE c.reloftype::pg_catalog.regtype::pg_catalog.text END, c.relpersistence, c.relreplident, am.amname
FROM pg_catalog.pg_class c
 LEFT JOIN pg_catalog.pg_class tc ON (c.reltoastrelid = tc.oid)
LEFT JOIN pg_catalog.pg_am am ON (c.relam = am.oid)
WHERE c.oid = '16454';
**************************

********* QUERY **********
SELECT a.attname,
  pg_catalog.format_type(a.atttypid, a.atttypmod),
  (SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid, true)
   FROM pg_catalog.pg_attrdef d
   WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef),
  a.attnotnull,
  (SELECT c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type t
   WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation) AS attcollation,
  a.attidentity,
  a.attgenerated
FROM pg_catalog.pg_attribute a
WHERE a.attrelid = '16454' AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum;
**************************

********* QUERY **********
SELECT pol.polname, pol.polpermissive,
  CASE WHEN pol.polroles = '{0}' THEN NULL ELSE pg_catalog.array_to_string(array(select rolname from pg_catalog.pg_roles where oid = any (pol.polroles) order by 1),',') END,
  pg_catalog.pg_get_expr(pol.polqual, pol.polrelid),
  pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid),
  CASE pol.polcmd
    WHEN 'r' THEN 'SELECT'
    WHEN 'a' THEN 'INSERT'
    WHEN 'w' THEN 'UPDATE'
    WHEN 'd' THEN 'DELETE'
    END AS cmd
FROM pg_catalog.pg_policy pol
WHERE pol.polrelid = '16454' ORDER BY 1;
**************************

********* QUERY **********
SELECT oid, stxrelid::pg_catalog.regclass, stxnamespace::pg_catalog.regnamespace::pg_catalog.text AS nsp, stxname,
pg_catalog.pg_get_statisticsobjdef_columns(oid) AS columns,
  'd' = any(stxkind) AS ndist_enabled,
  'f' = any(stxkind) AS deps_enabled,
  'm' = any(stxkind) AS mcv_enabled,
stxstattarget
FROM pg_catalog.pg_statistic_ext
WHERE stxrelid = '16454'
ORDER BY nsp, stxname;
**************************

********* QUERY **********
SELECT pubname
FROM pg_catalog.pg_publication p
JOIN pg_catalog.pg_publication_rel pr ON p.oid = pr.prpubid
WHERE pr.prrelid = '16454'
UNION ALL
SELECT pubname
FROM pg_catalog.pg_publication p
WHERE p.puballtables AND pg_catalog.pg_relation_is_publishable('16454')
ORDER BY 1;
**************************

********* QUERY **********
SELECT c.oid::pg_catalog.regclass
FROM pg_catalog.pg_class c, pg_catalog.pg_inherits i
WHERE c.oid = i.inhparent AND i.inhrelid = '16454'
  AND c.relkind != 'p' AND c.relkind != 'I'
ORDER BY inhseqno;
**************************

********* QUERY **********
SELECT c.oid::pg_catalog.regclass, c.relkind, inhdetachpending, pg_catalog.pg_get_expr(c.relpartbound, c.oid)
FROM pg_catalog.pg_class c, pg_catalog.pg_inherits i
WHERE c.oid = i.inhrelid AND i.inhparent = '16454'
ORDER BY pg_catalog.pg_get_expr(c.relpartbound, c.oid) = 'DEFAULT', c.oid::pg_catalog.regclass::pg_catalog.text;
**************************
```

**Comment by jkosh44** [comment]
```
SELECT c.oid,
  n.nspname,
  c.relname
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relname OPERATOR(pg_catalog.~) '^(object_table)$' COLLATE pg_catalog.default
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 2, 3;
```

- [X] pg_class.oid
- [X] pg_namespace.nspname
- [X] pg_class.oid
- [X] pg_namespace.oid
- [X] pg_class.relnamespace
- [X] pg_class.relname
- [X] pg_table_is_visible function

**Comment by jkosh44** [comment]
```
SELECT a.attname,
  pg_catalog.format_type(a.atttypid, a.atttypmod),
  (SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid, true)
   FROM pg_catalog.pg_attrdef d
   WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef),
  a.attnotnull,
  (SELECT c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type t
   WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation) AS attcollation,
  a.attidentity,
  a.attgenerated
FROM pg_catalog.pg_attribute a
WHERE a.attrelid = '16454' AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum;
```

- [X] pg_attribute.attname
- [X] format_type function
- [X] pg_attribute.atttypid
- [X] pg_attribute.atttypmod
- [X] pg_get expr function
- [X] pg_attrdef.adbin
- [X] pg_attrdef.adrelid
- [X] pg_attribute.attrelid
- [X] pg_attrdef.adnum
- [X] pg_attribute.attnum
- [X] pg_attribute.atthasdef
- [X] pg_attribute.attnotnull
- [X] pg_attribute.attidentity
- [ ] pg_attribute.attgenerated
- [X] pg_attribute.attisdropped
- [ ] pg_attribute.attcollation
- [X] pg_type.oid
- [ ] pg_type.typcollation

- [ ] pg_collation.collname
- [ ] pg_collation.oid

**Comment by jkosh44** [comment]
This one did not show up when running against PG, but did show up when running against MZ. Most likely a difference in the server versions:
```
SELECT c2.relname, i.indisprimary, i.indisunique, i.indisclustered, i.indisvalid, pg_catalog.pg_get_indexdef(i.indexrelid, 0, true),
  pg_catalog.pg_get_constraintdef(con.oid, true), contype, condeferrable, condeferred, i.indisreplident, c2.reltablespace
FROM pg_catalog.pg_class c, pg_catalog.pg_class c2, pg_catalog.pg_index i
  LEFT JOIN pg_catalog.pg_constraint con ON (conrelid = i.indrelid AND conindid = i.indexrelid AND contype IN ('p','u','x'))
WHERE c.oid = '20299' AND c.oid = i.indrelid AND i.indexrelid = c2.oid
ORDER BY i.indisprimary DESC, c2.relname;
```

- [X] `pg_class.relname`
- [X] `pg_index.indisprimary`
- [X] `pg_index.indisunique`: true if index is unique. Other than primary key indexes, MZ doesn't support creating unique indexes, and `indisprimary` is already filled in with false, so we can fill this in with false.
- [X] `pg_index.indisclustered`: true if table was last clustered on this index. MZ doesn't support clustering tables on indexes so we can fill this in with false.
- [X] `pg_index.indisvalid`: true if index is valid. From some research it seems like occasionally in Postgres when creating an index concurrently using the `CREATE INDEX CONCURRENTLY` syntax, the creation can fail. The index is kept around but marked as invalid in `pg_indexes` with this column. Since index creation can't fail in MZ, we can just fill this in with true.
- [ ] `pg_catalog.pg_get_indexdef(index oid [, column integer, pretty boolean ])`: econstructs the creating command for an index. (This is a decompiled reconstruction, not the original text of the command.) If column is supplied and is not zero, only the definition of that column is reconstructed.

**Comment by jkosh44** [comment]
```
SELECT pol.polname, pol.polpermissive,
  CASE WHEN pol.polroles = '{0}' THEN NULL ELSE pg_catalog.array_to_string(array(select rolname from pg_catalog.pg_roles where oid = any (pol.polroles) order by 1),',') END,
  pg_catalog.pg_get_expr(pol.polqual, pol.polrelid),
  pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid),
  CASE pol.polcmd
    WHEN 'r' THEN 'SELECT'
    WHEN 'a' THEN 'INSERT'
    WHEN 'w' THEN 'UPDATE'
    WHEN 'd' THEN 'DELETE'
    END AS cmd
FROM pg_catalog.pg_policy pol
WHERE pol.polrelid = '16454' ORDER BY 1;
```

- [X] `pg_catalog.pg_policy.X`: MZ doesn't support row level security policy so all this table can be made empty with all NULL rows.

**Comment by jkosh44** [comment]
```
SELECT c.oid::pg_catalog.regclass
FROM pg_catalog.pg_class c, pg_catalog.pg_inherits i
WHERE c.oid = i.inhparent AND i.inhrelid = '16454'
  AND c.relkind != 'p' AND c.relkind != 'I'
ORDER BY inhseqno;
```

- [X] `pg_inherits.X`: We do not support table inheritance so we can fill this in with an empty table.
