### ISSUE TITLE
Consider configuring smithy default timeouts.

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#9644]
Currently (as of #9642) we explicitly configure the aws client library's timeout handler. Possibly at some point after https://github.com/awslabs/aws-sdk-rust/issues/317 is resolved we will want to switch to using the `rt-tokio` feature instead.

**Comment by benesch** [comment]
Looks like the root issue here is that we reinvent `aws_config::Config` in `aws_util` because the upstream type doesn't implement `Clone`. If we could replace `aws_util::AwsConfig` with `aws_config::Config` this issue (and possibly others in the future) would disappear. I've filed https://github.com/awslabs/aws-sdk-rust/issues/352 to track.
