### ISSUE TITLE
sql: add support for `array_cat`

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#9801]
### Feature request

[PG's `array_cat`](https://www.postgresql.org/docs/9.1/functions-array.html) function would make concatenating arrays easier.

A possible workaround mentioned [here](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1640803815398200?thread_ts=1640798411.396400&cid=C015KDVS7EV) is to use a list with `list_cat`, then `unnest` the list, and finally use `array_agg` in order to mimic the PG's `array_cat` function.

**Comment by sploiselle** [comment]
We don't really want to be in the business of supporting arrays any more than necessary ([docs](https://materialize.com/docs/sql/types/array/)); is there a specific tool that uses this feature that we want to unblock?

**Comment by andrioni** [comment]
This one came from a user asking about it in [Community Slack](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1640798411396400). Since the workaround is not great (`array_agg` is nasty in terms of memory utilization) and I had some free time, I went and implemented it in #9819.
(We will require `array_remove` for pgcli and psql support, so I also took it as an opportunity to get more used to the array internals.)

**Comment by sploiselle** [comment]
In general, I am very apprehensive about making arrays ergonomic for folks––lest they think they want to use arrays, only to find out that they actually want lists as soon as they e.g. want to use any sources other Postgres.

Things like `array_remove` are the exception, which are seemingly necessary to interop with drivers--hence my question what tool this supports.

If this feature doesn't work toward providing compatibility for some nameable third-party tool, I'm less inclined to support it until we develop a measured plan for long-term array support.

That all being said, this could be gated behind the experimental flag, so will review #9819 with that in mind.

**Comment by andrioni** [comment]
Closing it as #9819 was merged already.
